Chromoting: Fix JS compile warning in client_screen.js.
client_screen.js:420: ERROR - inconsistent return type
found   : (boolean|number)
required: boolean
  return version && version >= 4;
                 ^

BUG=none
TEST=none


Review URL: http://codereview.chromium.org/9361005

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@121024 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 99623b013af0c702a7eb065b2c52aa577efd73e0