chromeos: Remove print statements from tools/cros.DEPS/DEPS
The print statements caused a syntax error in the DEPS file of the official
builds. The DEPS file for the official builds seems be generated with some
script by merging DEPS files, and it resulted in a syntax error in the
generated DEPS file:

starting gclient
...
Error: There is a syntax error in C:\b\build\slave\win\build\chrome-official\DEPS
Line #1, character 6: "ERROR: src/tools/cros.DEPS/DEPS has been merged into src/DEPS."

BUG=108090
TEST=run gclient sync locally with the empty DEPS file in .gclient file, and confirm there was no error.
NOTRY=true
TBR=nsylvain


Review URL: https://chromiumcodereview.appspot.com/10696063

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@145085 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: dabd2eb358b432c18842bcb43295f1a1ff57692b