[chromium] Remove unused variable (gcc 4.6 complains about this) https://bugs.webkit.org/show_bug.cgi?id=73335
../../third_party/WebKit/Source/WebCore/platform/graphics/chromium/cc/CCDamageTracker.cpp:296:19:
error: variable 'oldReplicaMaskRect' set but not used [-Werror=unused-but-set-variable]

* platform/graphics/chromium/cc/CCDamageTracker.cpp:
(WebCore::CCDamageTracker::extendDamageForRenderSurface):

git-svn-id: svn://svn.chromium.org/blink/trunk@101398 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: 0f572c1b14996e0378e777f9e73162f598ac9897