portage_util: unit test for always_live GetSourceInfo() call
Add a unit test for the fix introduced here:

commit b0c35e763156 ("portage_util: correct number of args to
SourceInfo()")

which added the required 5th argument to the always_live case in
GetSourceInfo().  Without the above fix this new test will fail:

  $ ./lib/portage_util_unittest
  .................................................................E....
  ........
  ======================================================================
  ERROR: [chromite.lib.portage_util_unittest]
  ProjectAndPathTest.testParseAlwaysLive
  Tests if an ebuild which is always live is correctly handled.
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/mnt/host/source/chromite/lib/timeout_util.py", line 191, in
    TimeoutWrapper
      return func(*args, **kwargs)
    File "/mnt/host/source/chromite/lib/portage_util_unittest.py", line
    332, in testParseAlwaysLive
      [fake_project], [], [fake_localname], fake_ebuild_contents)
    File "/mnt/host/source/chromite/lib/portage_util_unittest.py", line
    304, in _MockParseWorkonVariables
      return ebuild.GetSourceInfo(self.tempdir, MANIFEST)
    File "/mnt/host/source/chromite/lib/portage_util.py", line 784, in
    GetSourceInfo
      return SourceInfo(projects=[], srcdirs=[], subtrees=[])
  TypeError: __new__() takes exactly 5 arguments (4 given)

  ----------------------------------------------------------------------
  Ran 79 tests in 5.875s

  FAILED (errors=1)

BUG=None
TEST=portage_util_unittest both with and without the change in commit
b0c35e763156

Change-Id: Ifd78b25ea24709c2288a344705e660e96d7372c6
Signed-off-by: Ross Zwisler <zwisler@google.com>
Reviewed-on: https://chromium-review.googlesource.com/1456404
Commit-Ready: Ross Zwisler <zwisler@chromium.org>
Tested-by: Ross Zwisler <zwisler@chromium.org>
Reviewed-by: Ned Nguyen <nednguyen@google.com>
Reviewed-by: Don Garrett <dgarrett@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>