Revert 271459 "Remove stray platform_file.h from webkit"
This broke Android:
http://build.chromium.org/p/chromium.linux/builders/Android%20Builder/builds/30310
FAILED: /mnt/data/b/build/goma/gomacc /mnt/data/b/build/slave/Android_Builder/build/src/third_party/android_tools/ndk//toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -MMD -MF obj/content/shell/app/content_shell_lib.shell_main_delegate.o.d -DV8_DEPRECATION_WARNINGS -DBLINK_SCALE_FILTERS_AT_RECORD_TIME -D_FILE_OFFSET_BITS=64 -DNO_TCMALLOC -DDISABLE_NACL -DCHROMIUM_BUILD -DUSE_LIBJPEG_TURBO=1 -DENABLE_WEBRTC=1 -DUSE_PROPRIETARY_CODECS -DENABLE_CONFIGURATION_POLICY -DDISCARDABLE_MEMORY_ALWAYS_SUPPORTED_NATIVELY -DSYSTEM_NATIVELY_SIGNALS_MEMORY_PRESSURE -DENABLE_EGLIMAGE=1 -DENABLE_AUTOFILL_DIALOG=1 -DCLD_VERSION=1 -DENABLE_PRINTING=1 -DENABLE_MANAGED_USERS=1 -DVIDEO_HOLE=1 '-DCONTENT_SHELL_VERSION="19.77.34.5"' -DMOJO_USE_SYSTEM_IMPL -DLIBPEERCONNECTION_LIB=1 -DGTEST_HAS_POSIX_RE=0 -DMEDIA_DISABLE_LIBVPX -DPOSIX_AVOID_MMAP -DSK_ENABLE_INST_COUNT=0 -DSK_SUPPORT_GPU=1 '-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' -DSK_ENABLE_LEGACY_API_ALIASING=1 -DSK_ATTR_DEPRECATED=SK_NOTHING_ARG1 -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_WILL_NEVER_DRAW_PERSPECTIVE_TEXT -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_SUPPORT_LEGACY_N32_NAME -DSK_SUPPORT_LEGACY_BUILDMIPMAP -DSK_SUPPORT_LEGACY_SHADER_LOCALMATRIX -DSK_SUPPORT_LEGACY_GETTOTALCLIP -DSK_BUILD_FOR_ANDROID -DSK_USE_POSIX_THREADS -DSK_DEFERRED_CANVAS_USES_FACTORIES=1 -DSK_IGNORE_UNDERLINE_POSITION_FIX -DU_USING_ICU_NAMESPACE=0 -DU_STATIC_IMPLEMENTATION -DCHROME_PNG_WRITE_SUPPORT -DPNG_USER_CONFIG -DCHROME_PNG_READ_PACK_SUPPORT -DMESA_EGL_NO_X11_HEADERS -DAPPCACHE_USE_SIMPLE_CACHE -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DANDROID -D__GNU_SOURCE=1 -DUSE_STLPORT=1 -D_STLP_USE_PTR_SPECIALIZATIONS=1 '-DCHROME_BUILD_ID=""' -DHAVE_SYS_UIO_H -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -I../.. -I../../third_party/khronos -I../../gpu -I../../skia/config -I../../third_party/WebKit/Source -Igen -I../../third_party/WebKit -Igen/content -Igen/net -I../../third_party/skia/src/core -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../skia/ext -I../../third_party/WebKit -I../../third_party/icu/source/common -I../../third_party/npapi -I../../third_party/npapi/bindings -I../../third_party/libpng -I../../third_party/zlib -I../../third_party/libwebp -I../../third_party/ots/include -I../../third_party/qcms/src -I../../third_party/iccjpeg -I../../third_party/libjpeg_turbo -I../../third_party/icu/source/i18n -Igen/ui/gl -I../../third_party/mesa/src/include -I../../v8/include -Igen/webkit -Igen/content/shell -fstack-protector --param=ssp-buffer-size=4 -Werror -fno-exceptions -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-unused-local-typedefs -march=armv7-a -mtune=generic-armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb -fno-tree-sra -fno-partial-inlining -fno-early-inlining -fno-tree-copy-prop -fno-tree-loop-optimize -fno-move-loop-invariants -fno-caller-saves -Wno-psabi -mthumb-interwork -ffunction-sections -funwind-tables -g -fstack-protector -fno-short-enums -finline-limit=64 -Wa,--noexecstack --sysroot=/mnt/data/b/build/slave/Android_Builder/build/src/third_party/android_tools/ndk//platforms/android-14/arch-arm -I/mnt/data/b/build/slave/Android_Builder/build/src/third_party/android_tools/ndk//sources/cxx-stl/stlport/stlport -Os -fno-ident -fdata-sections -ffunction-sections -fomit-frame-pointer -funwind-tables -g1 -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare -Wno-abi  -c ../../content/shell/app/shell_main_delegate.cc -o obj/content/shell/app/content_shell_lib.shell_main_delegate.o
../../content/shell/app/shell_main_delegate.cc: In static member function 'static void content::ShellMainDelegate::InitializeResourceBundle()':
../../content/shell/app/shell_main_delegate.cc:265:17: error: 'kInvalidPlatformFileValue' is not a member of 'base'
   if (pak_fd != base::kInvalidPlatformFileValue) {
                 ^

> Remove stray platform_file.h from webkit
> 
> BUG=322664
> 
> Review URL: https://codereview.chromium.org/289003006

TBR=rvargas@chromium.org

Review URL: https://codereview.chromium.org/293743004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@271464 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: f1b171b812baa8d798274afb46516ef437bb6d46