Revert "Reland "Adds code in ViewAccessibility to manage the focus of AXVirtualView descendants""
This reverts commit 8aa453a99d85b885e8cff5a65862dbbf77a0ea7d [formerly f144f4a9852b708a30e8710f66ff57c55ce3cfa1].

Breaks compile on "Linux Chromium OS ASan LSan":

https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/Linux%20Chromium%20OS%20ASan%20LSan%20Builder/41713

../../ui/views/accessibility/ax_virtual_view.cc:2396: error: undefined reference to 'ui::AXPlatformNodeBase::GetData() const'
obj/ui/views/libviews.a(obj/ui/views/views/ax_virtual_view.o):ax_virtual_view.cc:vtable for views::AXVirtualView: error: undefined reference to 'ui::AXPlatformNodeDelegateBase::GetTreeData() const'
obj/ui/views/libviews.a(obj/ui/views/views/ax_virtual_view.o):ax_virtual_view.cc:vtable for views::AXVirtualView: error: undefined reference to 'ui::AXPlatformNodeDelegateBase::GetIndexInParent() const'
obj/ui/views/libviews.a(obj/ui/views/views/ax_virtual_view.o):ax_virtual_view.cc:vtable for views::AXVirtualView: error: undefined reference to 'ui::AXPlatformNodeDelegateBase::GetReverseRelations(ax::mojom::IntAttribute, int)'
obj/ui/views/libviews.a(obj/ui/views/views/ax_virtual_view.o):ax_virtual_view.cc:vtable for views::AXVirtualView: error: undefined reference to 'ui::AXPlatformNodeDelegateBase::GetReverseRelations(ax::mojom::IntListAttribute, int)'
obj/ui/views/libviews.a(obj/ui/views/views/ax_virtual_view.o):ax_virtual_view.cc:vtable for views::AXVirtualView: error: undefined reference to 'ui::AXPlatformNodeDelegateBase::GetTableRowCount() const'
obj/ui/views/libviews.a(obj/ui/views/views/ax_virtual_view.o):ax_virtual_view.cc:vtable for views::AXVirtualView: error: undefined reference to 'ui::AXPlatformNodeDelegateBase::GetTableColCount() const'
obj/ui/views/libviews.a(obj/ui/views/views/ax_virtual_view.o):ax_virtual_view.cc:vtable for views::AXVirtualView: error: undefined reference to 'ui::AXPlatformNodeDelegateBase::GetColHeaderNodeIds() const'
obj/ui/views/libviews.a(obj/ui/views/views/ax_virtual_view.o):ax_virtual_view.cc:vtable for views::AXVirtualView: error: undefined reference to 'ui::AXPlatformNodeDelegateBase::GetColHeaderNodeIds(int) const'
obj/ui/views/libviews.a(obj/ui/views/views/ax_virtual_view.o):ax_virtual_view.cc:vtable for views::AXVirtualView: error: undefined reference to 'ui::AXPlatformNodeDelegateBase::GetRowHeaderNodeIds() const'
obj/ui/views/libviews.a(obj/ui/views/views/ax_virtual_view.o):ax_virtual_view.cc:vtable for views::AXVirtualView: error: undefined reference to 'ui::AXPlatformNodeDelegateBase::GetRowHeaderNodeIds(int) const'
obj/ui/views/libviews.a(obj/ui/views/views/ax_virtual_view.o):ax_virtual_view.cc:vtable for views::AXVirtualView: error: undefined reference to 'ui::AXPlatformNodeDelegateBase::GetCellId(int, int) const'
obj/ui/views/libviews.a(obj/ui/views/views/ax_virtual_view.o):ax_virtual_view.cc:vtable for views::AXVirtualView: error: undefined reference to 'ui::AXPlatformNodeDelegateBase::GetTableCellIndex() const'
obj/ui/views/libviews.a(obj/ui/views/views/ax_virtual_view.o):ax_virtual_view.cc:vtable for views::AXVirtualView: error: undefined reference to 'ui::AXPlatformNodeDelegateBase::CellIndexToId(int) const'
obj/ui/views/libviews.a(obj/ui/views/views/ax_virtual_view.o):ax_virtual_view.cc:vtable for views::AXVirtualView: error: undefined reference to 'ui::AXPlatformNodeDelegateBase::GetTargetForNativeAccessibilityEvent()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[15380/16841] LINK ./app_list_unittests






Original change's description:
> Reland "Adds code in ViewAccessibility to manage the focus of AXVirtualView descendants"
> 
> This is a reland of c94ff46283a5b23a28d3d8ba51293d51feff05f3 [formerly cb9c309136ca43808267b83a6c603557805af943]
> 
> TBR=afakhry@chromium.org,dmazzoni@chromium.org,sky@chromium.org
> 
> Original change's description:
> > Adds code in ViewAccessibility to manage the focus of AXVirtualView descendants
> >
> > Also renamed some methods to make interface more consistent.
> > In preparation for more changes in AXVirtualView.
> > R=dmazzoni@chromium.org, aleventhal@chromium.org
> >
> > Change-Id: Ib417493794cc16536e20c3ce72dc8b00ba8568a9
> > Reviewed-on: https://chromium-review.googlesource.com/c/1296621
> > Reviewed-by: Ahmed Fakhry <afakhry@chromium.org>
> > Reviewed-by: Dominic Mazzoni <dmazzoni@chromium.org>
> > Reviewed-by: Scott Violet <sky@chromium.org>
> > Commit-Queue: Nektarios Paisios <nektar@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#602876}
> 
> Change-Id: I08aa777df2ce4a7fc93e30e00ef4aced623fdd6e
> Reviewed-on: https://chromium-review.googlesource.com/c/1301796
> Commit-Queue: Nektarios Paisios <nektar@chromium.org>
> Reviewed-by: Nektarios Paisios <nektar@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#603148}

TBR=ellyjones@chromium.org,dmazzoni@chromium.org,sky@chromium.org,afakhry@chromium.org,nektar@chromium.org,aleventhal@chromium.org

Change-Id: Ie75dec553acb4ea618665de25f5729f1feb51e12
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/1302499
Reviewed-by: Dominic Mazzoni <dmazzoni@chromium.org>
Commit-Queue: Dominic Mazzoni <dmazzoni@chromium.org>
Cr-Commit-Position: refs/heads/master@{#603159}
Former-commit-id: 0be054cb3f6c6aa89e4f7b5d22a56cd05fd3d23d