Revert 284518 "Disable a flaky test."
This broke compile on android:
http://build.chromium.org/p/chromium/builders/Android/builds/26268/steps/compile/logs/stdio

../android_webview/javatests/src/org/chromium/android_webview/test/AwContentsClientShouldOverrideUrlLoadingTest.java:794:
cannot find symbol
symbol  : class DisabledTest
location: class
org.chromium.android_webview.test.AwContentsClientShouldOverrideUrlLoadingTest
    @DisabledTest
     ^
1 error

> Disable a flaky test.
> 
> BUG=395817
> TEST=none
> TBR=joth
> 
> Review URL: https://codereview.chromium.org/408043002

TBR=pkasting@chromium.org

Review URL: https://codereview.chromium.org/407003002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@284530 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 47ef173364275729e9a616fa2d89d8441960e64d