crosfs: Fix missing result assignment
The -B flag when combined with -z fails due to this bug.

BUG=none
TEST=manual
crosfw -Bz

See that it no longer gives this error:

  File "/mnt/host/source/chromite/scripts/crosfw.py", line 480, in RunBuild
    if result.returncode:
UnboundLocalError: local variable 'result' referenced before assignment

Change-Id: Iaa71ce460cc8c99e8756a1b46ab38365b968b471
Signed-off-by: Simon Glass <sjg@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/62543
Reviewed-by: Che-Liang Chiou <clchiou@chromium.org>