Revert of Host-side implementation of ARC Intent handler (patchset #5 id:80001 of https://codereview.chromium.org/1590723003/ )
Reason for revert:
This may have broken the ChromeOS trybots:

https://build.chromium.org/p/tryserver.chromium.linux/builders/chromeos_amd64-generic_chromium_compile_only_ng/builds/81609/steps/compile%20%28with%20patch%29/logs/stdio

../../chrome/browser/chromeos/arc/arc_intent_helper_bridge_impl.cc: In member function 'virtual void arc::ArcIntentHelperBridgeImpl::OnOpenUrl(const mojo::String&)':
../../chrome/browser/chromeos/arc/arc_intent_helper_bridge_impl.cc:39:16: error: no matching function for call to 'GURL::GURL(const mojo::String&)'
   GURL gurl(url);

Original issue's description:
> Host-side implementation of ARC Intent handler
>
> The new interface, OnOpenUrl(), is implemented in
> arc_intent_helper_bridge_impl.cc. ARC-side CLs for
> the interfacve are ag/845051/ and ag/845044/.
>
> BUG=577929
> TEST=http, https, and mailto URLs are passed from ARC
>
> Committed: https://crrev.com/cd9c7593531d0590f04b601b5152d8f1620384b2 [formerly 379e0814ff680203c0b4d88cc77d339f0d03f70f]
> Cr-Commit-Position: refs/heads/master@{#370240}

TBR=dcheng@chromium.org,hidehiko@chromium.org,lhchavez@chromium.org,xiyuan@chromium.org,yusukes@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=577929

Review URL: https://codereview.chromium.org/1607603005

Cr-Commit-Position: refs/heads/master@{#370289}

Former-commit-id: 15d94b7c0e0b17e973d144c03c7f69f9e0f62309