Revert of ash: Use system tray mojo interface to show system update tray icon (patchset #6 id:100001 of https://codereview.chromium.org/2558043006/ )
Reason for revert:
Broke compile on Google Chrome ChromeOS:

https://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20ChromeOS/builds/26896

../../chrome/browser/component_updater/pepper_flash_component_installer.cc:94:3: error: no type named 'SystemTrayClient' in namespace 'chromeos'; did you mean simply 'SystemTrayClient'?
  chromeos::SystemTrayClient* tray = chromeos::SystemTrayClient::Get();
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
  SystemTrayClient
../../chrome/browser/ui/ash/system_tray_client.h:27:7: note: 'SystemTrayClient' declared here
class SystemTrayClient : public ash::mojom::SystemTrayClient,
      ^
../../chrome/browser/component_updater/pepper_flash_component_installer.cc:94:38: error: no member named 'SystemTrayClient' in namespace 'chromeos'; did you mean simply 'SystemTrayClient'?
  chromeos::SystemTrayClient* tray = chromeos::SystemTrayClient::Get();
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                     SystemTrayClient
../../chrome/browser/ui/ash/system_tray_client.h:27:7: note: 'SystemTrayClient' declared here
class SystemTrayClient : public ash::mojom::SystemTrayClient,
      ^
2 errors generated.

Original issue's description:
> ash: Use system tray mojo interface to show system update tray icon
>
> Change the flow so that Chrome explicitly asks ash to show the icon
> rather than having ash ask Chrome whether there is an update available.
>
> * Add ShowUpdateIcon to system_tray.mojom
> * Introduce update.mojom
> * Migrate ash to using ash::mojom::UpdateSeverity internally
> * Migrate update methods from SystemTrayDelegate to SystemTrayClient
> * Add a new SystemTrayClientTest and move existing Flash test there
>
> Also add docs for SystemTrayItem (used by TrayUpdate) since tray view
> vs. default view vs. detailed view always confuses me.
>
> BUG=647412
> TEST=chrome browser_tests, ash_unittests
>
> Committed: https://crrev.com/f7a07cdf4b8402ab2a55497f02092256b20398ed [formerly 196ee3b66b3700733cecb8472d63d872d99e3783]
> Cr-Commit-Position: refs/heads/master@{#438051}

TBR=msw@chromium.org,kerrnel@chromium.org,tsepez@chromium.org,waffles@chromium.org,sky@chromium.org,jamescook@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=647412

Review-Url: https://codereview.chromium.org/2568413002
Cr-Commit-Position: refs/heads/master@{#438064}

Former-commit-id: 9dac09552e919158ba3654c64155dc0903bb8ace