Revert "chromite: Remove TreeIsOpen and dependencies."
This reverts commit 30edf2a584d17068c90c20b5b8d34d0b9dedd205.

Reason for revert: breaks master-paladin with error:
ERROR: <type 'exceptions.AttributeError'>: 'ValidationPool' object has no attribute 'FilterChangesForThrottledTree'

Original change's description:
> chromite: Remove TreeIsOpen and dependencies.
> 
> TEST=./run_tests
> BUG=chromium:903420
> 
> Change-Id: I980e604bd5e0d7f18a0534deb8c00b88560db4c2
> Reviewed-on: https://chromium-review.googlesource.com/1577652
> Commit-Ready: Evan Hernandez <evanhernandez@chromium.org>
> Tested-by: Evan Hernandez <evanhernandez@chromium.org>
> Reviewed-by: Dhanya Ganesh <dhanyaganesh@chromium.org>
> Reviewed-by: Mike Nichols <mikenichols@chromium.org>

Bug: chromium:903420
Change-Id: I4e8789d4591119b0e9369d7c52c2d60a1c6e31a5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/1583402
Reviewed-by: Rong Chang <rongchang@chromium.org>
Commit-Queue: Rong Chang <rongchang@chromium.org>
Tested-by: Rong Chang <rongchang@chromium.org>