Ensure deletion of temporary frames for WebRTC video quality test.
In https://chromiumcodereview.appspot.com/17588003
the old PyAuto test was converted to a browser_test.
Unfortunately the --delete_frames flag that was sent to
the rgba_to_i420_converter program defaults to false if
omitted.

I'm setting NOTRY since this test doesn't run on the trybots anyway. 
I'm running a few of them just to sanity check compilation.

NOTRY=True
BUG=363576
TEST=Ran the program manually and verified the flag gets set:
$ out/Release/rgba_to_i420_converter --delete_frames=true
You have entered:
delete_frames=true, frames_dir=., height=-1, output_file=output.yuv, width=-1,
Error: width or height cannot be <= 0!
Also compiled the chromium_builder_webrtc target and ran:
out/Release/browser_tests --run-manual --ui-test-action-max-timeout=300000 --gtest_filter=WebRtcVideoQualityBrowserTest.MANUAL_TestVGAVideoQuality

Review URL: https://codereview.chromium.org/238803003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@265273 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 9754c19c60c44f8571d3b72b5441c9408516b247