BUILD FIX (r146687): setDefaultMIMEType() is unused in ResourceHandleCFNet.cpp on iOS
Fixes the following build failure:

    Source/WebCore/platform/network/cf/ResourceHandleCFNet.cpp:98:13: error: unused function 'setDefaultMIMEType' [-Werror,-Wunused-function]
    static void setDefaultMIMEType(CFURLResponseRef response)
                ^
    1 error generated.

* platform/network/cf/ResourceHandleCFNet.cpp:
(WebCore::setDefaultMIMEType): Add #if !PLATFORM(MAC)/#endif
guard.

git-svn-id: svn://svn.chromium.org/blink/trunk@146718 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: a70ff71636a616d3e880075b57878e62ecbfd49a