Revert of DevTools: Roll Lighthouse binary to 2.0.0-alpha.7 (patchset #5 id:40001 of https://codereview.chromium.org/2888263002/ )
Reason for revert:
webview perfbot failing with:

TraceImportError: No clock sync markers exist pairing clock domain "LINUX_FTRACE_GLOBAL" with target clock domain "TELEMETRY".

http://crbug.com/724423

Original issue's description:
> DevTools: Roll Lighthouse binary to 2.0.0-alpha.7
> Hash: aebc9bdf53754ffd360f7c54c752b046383c2d1b
>
> BUG=663085
> R=pfeldman@chromium.org, phulce@chromium.org
>
> Review-Url: https://codereview.chromium.org/2888263002 .
> Cr-Original-Commit-Position: refs/heads/master@{#472680}
> Committed: https://chromium.googlesource.com/chromium/src/+/fb8e982573d177c91bfeb69b9148819d1ce7eea1 [formerly 5b84a98141df91643a05bcb8e81c9f0398e6ba81]
> Review-Url: https://codereview.chromium.org/2888263002 .
> Cr-Commit-Position: refs/heads/master@{#472913}
> Committed: https://chromium.googlesource.com/chromium/src/+/6850b5de67619520e3d9de2f4c46c0185043d7bb [formerly a9b28ebe7c619f7025e9b9c20671967eb3a440f3]

TBR=pfeldman@chromium.org,phulce@chromium.org,paulirish@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=663085

Review-Url: https://codereview.chromium.org/2894113002
Cr-Commit-Position: refs/heads/master@{#473167}

Former-commit-id: 54276de3358920fed87c8a1975b0fd7cbec2b92f