Remove cq_name
Some configs in revision 2bfc67a in external/github.com/catapult-project/catapult repo have validation errors. luci-config had to reject all configs in this revision.

ERROR: cq.cfg: cq_name is no longer used and can and should be removed. Please, do so now
Please correct these errors. If you have questions, ask CCed people.

If a .proto file was updated recently, the service performing validation of "invalid" file(s) may need to be redeployed.

Configs in revision 20d3d66 will remain active until new valid ones are committed.

Change-Id: I1f22e3ee5578230f056a048f337162c02ff91806
Reviewed-on: https://chromium-review.googlesource.com/1176265
Reviewed-by: John Budorick <jbudorick@chromium.org>
Reviewed-by: Annie Sullivan <sullivan@chromium.org>
Commit-Queue: Annie Sullivan <sullivan@chromium.org>

Former-commit-id: a9e5877d09a0d2d2f324ee973ca9fb6fe95f5449