portage_util: correct number of args to SourceInfo()
An additional "subdirs" argument was added to SourceInfo() here:

commit 3dbb2932da86 ("portage_util: Readd CROS_WORKON_SUBDIR
compatibility.")

but the 'always_live' callsite in GetSourceInfo() was not updated.
If you run through this code now, you get:

  File "/mnt/host/source/chromite/lib/portage_util.py", line 784, in
  GetSourceInfo
    return SourceInfo(projects=[], srcdirs=[], subtrees=[])
  TypeError: __new__() takes exactly 5 arguments (4 given)

BUG=None
TEST=I found this while working to fix 'cros_workon info' output for
kernel ebuilds.  With this change the always_on ebuilds work correctly
with my updated "cros_workon info" code.

Change-Id: Ifde0ecd7becbfc55f0061648ebc8d5e20bd7d02c
Signed-off-by: Ross Zwisler <zwisler@google.com>
Reviewed-on: https://chromium-review.googlesource.com/1454289
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Tested-by: Ross Zwisler <zwisler@chromium.org>
Reviewed-by: Don Garrett <dgarrett@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>