2011-01-13  Eric Seidel  <eric@webkit.org>
        Reviewed by Mihai Parparita.

        webkit-patch suggest-reviewers fails due to invalid utf8 in ChangeLog files
        https://bugs.webkit.org/show_bug.cgi?id=52416

        Example: webkit-patch suggest-reviewers -g ca3890fe74d94d85d6bfa48f9ea497b094d8e717
        UnicodeDecodeError: 'utf8' codec can't decode bytes in position 536-538: invalid data

        I also added FIXMEs about the changed_files returning deleted files problem
        which is causing the other most common exception for suggest-reviewers
        (and is probably breaking sheriff-bots blame detection).

        * Scripts/webkitpy/common/checkout/api.py:
        * Scripts/webkitpy/common/checkout/api_unittest.py:
        * Scripts/webkitpy/common/checkout/scm.py:

git-svn-id: svn://svn.chromium.org/blink/trunk@75761 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: b97e78993da9d0bfa34ca5c2b9c3395e3ab8fcf3