cros_build_lib: always include failing command in RunCommandError
If we execute a command that doesn't exist, the default output is
useless to people trying to triage:
$ python -c 'from chromite.lib import cros_build_lib; cros_build_lib.RunCommand(["/asdf"])'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "chromite/lib/cros_build_lib.py", line 619, in RunCommand
    raise RunCommandError(estr, CommandResult(cmd=cmd), exception=e)
chromite.lib.cros_build_lib.RunCommandError: return code: None
[Errno 2] No such file or directory

Nowhere in this output does it include the value of |cmd|.  When the
call is buried in a few layers, it becomes even less obvious what the
actual missing program is.  Now the output looks like:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "chromite/lib/cros_build_lib.py", line 618, in RunCommand
    raise RunCommandError(estr, CommandResult(cmd=cmd), exception=e)
chromite.lib.cros_build_lib.RunCommandError: return code: None; command: /asdf
[Errno 2] No such file or directory

BUG=chromium:565228
TEST=`./cbuildbot/run_tests` passes

Change-Id: Id236b5515d21da46daadc62e1ce78f7b57e8d7e0
Reviewed-on: https://chromium-review.googlesource.com/315571
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Christopher Wiley <wiley@chromium.org>