Fix context menu tests
testDismissContextMenuOnClick instrumentation test fails because we
click on a notification instead of a view in the app which causes a
java.lang.SecurityException: "Injecting to another application requires
INJECT_EVENTS permission."

To work around this issue, this CL changes the test to click roughly
the bottom right corner of the screen.

Bug: 1001966
Change-Id: I3f0d3c06ad72450217b936ea17d896db4162deb8
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1792685
Reviewed-by: Theresa  <twellington@chromium.org>
Commit-Queue: Sinan Sahin <sinansahin@google.com>
Cr-Commit-Position: refs/heads/master@{#695179}

Former-commit-id: 5cb0eb175aacfae5316f9d92c1adbf6ebf0d05f3