Fix vprintf_stderr_common() to compile with -Wshorten-64-to-32 <http://webkit.org/b/107126>
Reviewed by Darin Adler.

Fixes the following build error:

    Assertions.cpp:92:22: error: implicit conversion loses integer precision: 'CFIndex' (aka 'long') to 'int' [-Werror,-Wshorten-64-to-32]
            int length = CFStringGetMaximumSizeForEncoding(CFStringGetLength(str), kCFStringEncodingUTF8);
                ~~~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

* wtf/Assertions.cpp:
(vprintf_stderr_common): Use CFIndex type instead of int for the
return value of CFStringGetMaximumSizeForEncoding().

git-svn-id: svn://svn.chromium.org/blink/trunk@139982 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: db43cf88c63f32b168bb4c268882d9646031ff0b