Revert of Installs test CA to android devices as part of browser startup so that apps can be tested with prox… (patchset #8 id:140001 of https://codereview.chromium.org/572123002/)
Reason for revert:
Userdebug build perf bots are still missing dependencies:
ImportError: No module named OpenSSL

Also, we'll need to gracefully degrade on user builds:
CertInstallError: Cert Install Failed

Original issue's description:
> Installs test CA to android devices as part of browser startup so that apps can be tested with proxy HTTPS server without code changes.
>
> BUG=412826
>
> Committed: https://crrev.com/b5e396094dd05f0cc419e558f201f4761bed67d9 [formerly f28d9cace2df4a9dcaa992c4df5b85e3b2674dbb]
> Cr-Commit-Position: refs/heads/master@{#296619}
>
> Committed: https://crrev.com/85022c5df03e3223c7b584898406d5e4097867cf [formerly 10eb77a2c2843664e7d55d8a4535d66b7f95d9c8]
> Cr-Commit-Position: refs/heads/master@{#297653}

TBR=nednguyen@google.com,slamm@google.com,slamm@chromium.org,hjd@chromium.org,friedman@chromium.org,wuhu@google.com
NOTREECHECKS=true
NOTRY=true
BUG=412826

Review URL: https://codereview.chromium.org/617263004

Cr-Commit-Position: refs/heads/master@{#297697}

Former-commit-id: 36c8d5e285ab85c424151ae207797d17dc7d3d00