third_party/blink/common:headers depends on //media/mojo/interfaces:interfaces
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8910998052779382944/+/steps/compile/0/stdout
In file included from ../../third_party/blink/renderer/modules/mediastream/mock_media_stream_registry.cc:10:
In file included from ../../third_party/blink/public/platform/modules/mediastream/media_stream_audio_source.h:16:
In file included from ../../third_party/blink/public/platform/modules/mediastream/web_platform_media_stream_source.h:9:
../../third_party/blink/public/common/mediastream/media_stream_request.h:19:10: fatal error: 'media/mojo/interfaces/display_media_information.mojom.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1 error generated.

Change-Id: I9200c6c67ada890a5de4f529ab8f19bc82528087
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1651530
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#667880}

Former-commit-id: b3f91fc6abd713d2c727c63fb58c5c23af70da15