Use regular emerge for updating Portage itself.
When updating Portage itself, we should use emerge for the upgrade so
that we can rely on the built-in logic for making sure no new modules
are loaded in after the install. This helps avoid the following
traceback when upgrading to Portage 2.1.11.31:

  pym/portage/package/ebuild/getmaskingreason.py line 14:
  from portage.versions import catpkgsplit, _pkg_str
  ImportError: cannot import name _pkg_str

BUG=chromium-os:35982
TEST=Install old version of portage, then use build_packages to install
     new version of Portage. Prior to this change, we get a traceback.
     After the change, the upgrade works. Also run trybots on all
     platforms.

Change-Id: I1af98f89b50b2f23ffc72d7872d795a3e240fc45
Reviewed-on: https://gerrit.chromium.org/gerrit/37295
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Ready: David James <davidjames@chromium.org>
Tested-by: David James <davidjames@chromium.org>