lint: fix running on files outside of the manifest
Running on files external to the manifest fails currently due to the
pylintrc logic:

$ cros lint ~/test.py
cros: Unhandled exception:
Traceback (most recent call last):
  ...
  File "/usr/local/src/chromiumos/chromite/cros/commands/cros_lint.py", line 90, in Run
    for pylintrc, paths in sorted(_GetPylintGroups(files).items()):
  File "/usr/local/src/chromiumos/chromite/cros/commands/cros_lint.py", line 29, in _GetPylintGroups
    project_path = _GetProjectPath(path)
  File "/usr/local/src/chromiumos/chromite/cros/commands/cros_lint.py", line 19, in _GetProjectPath
    manifest = git.ManifestCheckout.Cached(path)
  File "/usr/local/src/chromiumos/chromite/lib/git.py", line 744, in Cached
    search=search)
  File "/usr/local/src/chromiumos/chromite/lib/git.py", line 541, in _NormalizeArgs
    raise OSError(errno.ENOENT, "Couldn't find repo root: %s" % (path,))
OSError: [Errno 2] Couldn't find repo root: /usr/local/google/home/vapier/test.py

BUG=None
TEST=`cros lint ~/test.py` works
TEST=`cros cros/commands/cros_lint.py` uses local pylintrc

Change-Id: I2fab4a5558459c55ec0431c970f0dbdb5aaaa39a
Reviewed-on: https://chromium-review.googlesource.com/190960
Reviewed-by: David James <davidjames@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>