Revert of Mac: Share kScrollbarPixelsPerCocoaTick between ui:: and blink:: events (patchset #5 id:140001 of https://codereview.chromium.org/2226933004/ )
Reason for revert:
Somehow... this slipped through the trybots -
web_input_event_builders_mac_unittest.mm:586:49:error: too many arguments to function call, expected 2, have 4

Original issue's description:
> Mac: Share kScrollbarPixelsPerCocoaTick between ui:: and blink:: events
>
> Currently scrolling in MacViews with a "real" mouse wheel is too fast. A
> multiplier is applied that maps the values used for
> kCGScrollEventUnitLine to (effectively) kCGScrollEventUnitPixel, and the
> one used for MacViews was too big. Share the constant that content::
> uses by moving it to ui/events/cocoa/cocoa_event_utils.h
>
> Add a test to ensure the event types agree. Problem: the initializers on
> NSEvent for creating test events are too limited. We also want to beef
> up testing of scroll event streams for elastic scrolling and whatnot, so
> move the stuff in events_mac_unittest.mm to cocoa_test_event_utils:: for
> creating test scroll events.
>
> BUG=615948
>
> Committed: https://crrev.com/77a6a0505b428f6848b819026115887bfda5693a [formerly 315a111b6cdd928cbd0862dd97f5a98482dd0261]
> Cr-Commit-Position: refs/heads/master@{#411216}

TBR=avi@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=615948

Review-Url: https://codereview.chromium.org/2234143003
Cr-Commit-Position: refs/heads/master@{#411223}

Former-commit-id: 941118827f5240dedb40082cffb1ead6c6d621cc