Revert "[gin] Allow posting non-nestable tasks through V8"
This reverts commit 2e5d334e59df30b83f346eb2df1a2d8998879ee6 [formerly 7f08809af15106c04feb6188b5d54c93af19472b].

Reason for revert: broke compilation
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8932945363042209344/+/steps/compile/0/stdout

../../gin/v8_foreground_task_runner.h:27:60: error: only virtual member functions can be marked 'override'
    void PostNonNestableTask(std::unique_ptr<v8::Task> task) override;
                                                             ^~~~~~~~
  ../../gin/v8_foreground_task_runner.h:34:40: error: only virtual member functions can be marked 'override'
    bool NonNestableTasksEnabled() const override;

Original change's description:
> [gin] Allow posting non-nestable tasks through V8
> 
> Will be used to allow V8 posting top-level tasks.
> 
> Bug: chromium:843903
> Change-Id: I97caa705b561fa8832ef8a11abfc3eefe47ec3f8
> Reviewed-on: https://chromium-review.googlesource.com/c/1273140
> Reviewed-by: Jochen Eisinger <jochen@chromium.org>
> Commit-Queue: Michael Lippautz <mlippautz@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#598802}

TBR=mlippautz@chromium.org,jochen@chromium.org

Change-Id: I5d427abfe85e3b69a3d649ee190406a5d9583d9e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: chromium:843903
Reviewed-on: https://chromium-review.googlesource.com/c/1277086
Reviewed-by: Vasilii Sukhanov <vasilii@chromium.org>
Commit-Queue: Vasilii Sukhanov <vasilii@chromium.org>
Cr-Commit-Position: refs/heads/master@{#598804}
Former-commit-id: 0174bab48c75e579b8369652e5ed5b4c8dcb11de