Catch native load error and rethrow new error to provide a better stack trace.
BUG=https://github.com/google/trace-viewer/issues/984

Assuming base.html is fixed to make sure browser related
logic doesn't raise exception.
Run: ./tracing/build/d8_runner tracing/tracing/base/math.html --search_path=tracing/tracing

*Without patch:*
Traceback (most recent call last):
  File "./tracing/build/d8_runner", line 13, in <module>
    sys.exit(d8_runner.main())
  File "/usr/local/google/home/nednguyen/github/trace-viewer/tracing/build/d8_runner.py", line 144, in main
    js_args=args.js_args)
  File "/usr/local/google/home/nednguyen/github/trace-viewer/tracing/build/d8_runner.py", line 89, in ExecuteFile
    return ExecuteFileWithD8(temp_boostrap_file, js_args)
  File "/usr/local/google/home/nednguyen/github/trace-viewer/tracing/build/d8_runner.py", line 128, in ExecuteFileWithD8
    (js_file_path, js_args, out, err))
RuntimeError: Exception raised when executing /tmp/tmpQBybjj/_tmp_boostrap.js with args 'None':
/tmp/tmpQBybjj/_tmp_boostrap.js:76: Error loading file
  __actual_load(_stripStartingSlashIfNeeded(file_path));

*With patch:*
Traceback (most recent call last):
  File "./tracing/build/d8_runner", line 13, in <module>
    sys.exit(d8_runner.main())
  File "/usr/local/google/home/nednguyen/github/trace-viewer/tracing/build/d8_runner.py", line 144, in main
    js_args=args.js_args)
  File "/usr/local/google/home/nednguyen/github/trace-viewer/tracing/build/d8_runner.py", line 89, in ExecuteFile
    return ExecuteFileWithD8(temp_boostrap_file, js_args)
  File "/usr/local/google/home/nednguyen/github/trace-viewer/tracing/build/d8_runner.py", line 128, in ExecuteFileWithD8
    (js_file_path, js_args, out, err))
RuntimeError: Exception raised when executing /tmp/tmp4UEnuF/_tmp_boostrap.js with args 'None':
/tmp/tmp4UEnuF/_tmp_boostrap.js:84: Error: Error in loading /gl-matrix-min.js: Error loading file
    throw new Error('Error in loading ' + file_path + ': ' + err);
          ^
Error: Error in loading /gl-matrix-min.js: Error loading file
    at load (/tmp/tmp4UEnuF/_tmp_boostrap.js:84:11)
    at eval (/usr/local/google/home/nednguyen/github/trace-viewer/tracing/tracing/base/math.html:2:1)
    at loadHTML (/tmp/tmp4UEnuF/_tmp_boostrap.js:75:3)
    at /tmp/tmp4UEnuF/_tmp_boostrap.js:90:1

R=nduca@chromium.org

Review URL: https://codereview.appspot.com/247490043.


Former-commit-id: df5cb2530bd1a607613fc3e642a5917d6e580f35