Revert of Enable hermetic builds for iOS. (patchset #4 id:100001 of https://codereview.chromium.org/2546613004/ )
Reason for revert:
IndexError: list index out of range

Original issue's description:
> Enable hermetic builds for iOS.
>
> BUG=669094
>
> Committed: https://crrev.com/673b6870184dfb38f9b2dee2c8983ab5fbd172a6 [formerly 080de20fe53a35ec6b5ce89470261157f9389db3]
> Cr-Commit-Position: refs/heads/master@{#437269}

TBR=erikchen@chromium.org,kjellander@chromium.org,sdefresne@chromium.org,rsesek@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=669094

Review-Url: https://codereview.chromium.org/2552383006
Cr-Commit-Position: refs/heads/master@{#437273}

Former-commit-id: 73c24cdb89cee4af2adb7021dbd05d4418525ef8