Revert http://crrev/203700 - "Implementing uploading of a WebRTC diagnostic log."
This reverts commit 6552bb4b174838230a5ba455083d6edccde20c7c [formerly 731c1368a3d9780b031894988ca68fd9a904c853].

../../chrome/browser/media/webrtc_logging_handler_host.cc: In member function 'void WebRtcLoggingHandlerHost::OpenLogIfAllowed()':
../../chrome/browser/media/webrtc_logging_handler_host.cc:73:error: 'chromeos::CrosSettings' has not been declared
../../chrome/browser/media/webrtc_logging_handler_host.cc:73:error: 'kStatsReportingPref' is not a member of 'chromeos'

http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20ChromeOS/builds/54135/steps/compile/logs/stdio#error1

BUG=None
TBR=grunell@chromium.org

Review URL: https://codereview.chromium.org/15714007

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@203701 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: b1672c4c028c1c0b0e804cc46ad0a496270cb428