Refactor the recovery component action handler for Windows.
This CL refactors the implementation of the recovery component action
handler for Windows so that most of the code can be reused in the
future for macOS recovery component. It also adds a unit test.

This is trying to reland
https://chromium-review.googlesource.com/c/chromium/src/+/1946020
which failed on Linux with:

recovery_improved_component_installer.cc:94:11: error: no member named 'start_hidden' in 'base::LaunchOptions'
options.start_hidden = true;
~~~~~~~ ^

Bug: 1029953
Change-Id: I685963ed8b281d5709867c55b73617a121e7b78b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1949224
Reviewed-by: Joshua Pawlicki <waffles@chromium.org>
Commit-Queue: Sorin Jianu <sorin@chromium.org>
Cr-Commit-Position: refs/heads/master@{#721257}

Former-commit-id: 1a7d78d75244299df203057a8b3a8e13546bae22