Revert of Upstream iOS implementation of Autocomplete factories. (patchset #2 id:20001 of https://codereview.chromium.org/1277543003/ )
Reason for revert:
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/ios/chrome/browser/autocomplete/ios_chrome_browser.autocomplete_scheme_classifier_impl.armv7.o.d -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -DDISABLE_NACL -DCHROMIUM_BUILD -DCR_CLANG_REVISION=242792-1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_CONFIGURATION_POLICY -DSYSTEM_NATIVELY_SIGNALS_MEMORY_PRESSURE -DDONT_EMBED_BUILD_METADATA -DFIELDTRIAL_TESTING_ENABLED -DDISABLE_FTP_SUPPORT=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DUSE_SYSTEM_LIBXML -DMOJO_USE_SYSTEM_IMPL -DPROTOBUF_USE_DLLS -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DSK_SUPPORT_GPU=0 -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DUSE_LIBPCI=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DNS_BLOCK_ASSERTIONS=1 -D_FORTIFY_SOURCE=2 -Igen -I../.. -I/Applications/Xcode6.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk/usr/include/libxml2 -I../../skia/config -I../../third_party/khronos -I../../gpu -I../../breakpad/src -Igen/protoc_out -I../../third_party/protobuf -I../../third_party/protobuf/src -I../../third_party/dom_distiller_js/dist/proto_gen -I../../third_party/cacheinvalidation/overrides -I../../third_party/cacheinvalidation/src -Igen/components/strings -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../skia/ext -I../../third_party/google_toolbox_for_mac -I../../third_party/google_toolbox_for_mac/src -I../../third_party/google_toolbox_for_mac/src/AppKit -I../../third_party/google_toolbox_for_mac/src/DebugUtils -I../../third_party/google_toolbox_for_mac/src/Foundation -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -isysroot /Applications/Xcode6.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk -Os -gdwarf-2 -fvisibility=hidden -Werror -Wnewline-eof -miphoneos-version-min=7.0 -arch armv7 -Wall -Wendif-labels -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-selector-type-mismatch -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fno-threadsafe-statics -Xclang -load -Xclang /b/build/slave/iOS_Device__ninja_/build/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -Wobjc-missing-property-synthesis -fobjc-call-cxx-cdtors  -c ../../ios/chrome/browser/autocomplete/autocomplete_scheme_classifier_impl.mm -o obj/ios/chrome/browser/autocomplete/ios_chrome_browser.autocomplete_scheme_classifier_impl.armv7.o
../../ios/chrome/browser/autocomplete/autocomplete_scheme_classifier_impl.mm:20:27: error: no member named 'StringToLowerASCII' in namespace 'base'
  DCHECK_EQ(scheme, base::StringToLowerASCII(scheme));
                    ~~~~~~^

Original issue's description:
> Upstream iOS implementation of Autocomplete factories.
>
> Provide iOS implementation for AutocompleteClassifier, InMemoryURLIndex
> and ShortcutsBackend factories as BrowserStateKeyedServiceFactory.
>
> Provide iOS implementation for AutocompleteProviderClient and
> AutocompleteSchemeClassifier.
>
> BUG=516635
>
> Committed: https://crrev.com/e9ec79ad85a5f3330f61f86c31b0fce5ad670d2b [formerly a3e5ce5bf10b96e24dd4e0440606336f362c3235]
> Cr-Commit-Position: refs/heads/master@{#342981}

TBR=blundell@chromium.org,sdefresne@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=516635

Review URL: https://codereview.chromium.org/1286123003

Cr-Commit-Position: refs/heads/master@{#342982}

Former-commit-id: a91b4915fd7038c8bbea8b02cd6a8ac5a92bae8a