Modular build: Fix build failure occurring when building from scratch
The previous change (r3801) had a mistake in which build.py would fail
when run on a pristine source tree, with the error:

btarget.TargetNotBuiltException: Target 'nacl-src-orig' has not been built yet

Fix it so that this placeholder target is considered built.

The change is prepared by Mark Seaborn.
Original ReviewURL: http://codereview.chromium.org/5371003/

BUG=http://code.google.com/p/nativeclient/issues/detail?id=852
TEST=delete native_client/../../src.state and run "python build.py -b"
Review URL: http://codereview.chromium.org/5340006

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@3804 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: 431166f7c99740e89df659d70acb6c2c347ff7ae