Fix chromium compilation in linux-rel
Currently, linux-rel fails to build due to an unused return value
warning:

../../third_party/openscreen/src/platform/base/logging.cc:42:3: error: ignoring
return value of function declared with 'warn_unused_result' attribute
[-Werror,-Wunused-result]
  write(g_log_fd, ss.str().c_str(), ss.str().size());

This patch fixes this issue by DCHECKing the return.

Change-Id: I6574cf628813d23f39970cdbf8ecac75efe71842
Reviewed-on: https://chromium-review.googlesource.com/c/openscreen/+/1618251
Reviewed-by: mark a. foltz <mfoltz@chromium.org>
Commit-Queue: Jordan Bayles <jophba@chromium.org>