Reland "[CompositeAfterPaint] Rebaseline tests"
This reverts commit 3e2eba6e48acbf9ee9cc8aaa293ff0b52ff4fa49 [formerly fb7771dc34be83226f9dc85b99a2886e2d2645ae].

Reason for revert: Long filenames excluded.

Original change's description:
> Revert "[CompositeAfterPaint] Rebaseline tests"
> 
> This reverts commit 8f1d00c43b094a359ce323bc373f7a54fe0df125 [formerly 9dc83eebac2edb5cbfa7dac1b1226f3f2cbb3128].
> 
> Reason for revert: causes bot_update failure on Win x64 Builder (dbg).
> 
> Sample build: https://ci.chromium.org/p/chromium/builders/ci/Win%20x64%20Builder%20%28dbg%29/99428
> 
> ---
> error: unable to create file third_party/blink/web_tests/flag-specific/enable-blink-features=CompositeAfterPaint/virtual/controls-refresh/fast/forms/controls-new-ui/color-scheme-validation/color/color-suggestion-picker-appearance-with-scrollbar-expected.png: Filename too long
> ---
> 
> Original change's description:
> > [CompositeAfterPaint] Rebaseline tests
> > 
> > Most of these rebaselines are for the mock scrollbar change which missed
> > rebaselining for CAP.
> > 
> > The other rebaselines are for new tests added for
> > virtual/controls-refresh.
> > 
> > TBR=schenney@chromium.org
> > 
> > Change-Id: Ia710bd0bf371eae8367c1ee3739691985f314840
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1888572
> > Reviewed-by: Xianzhu Wang <wangxianzhu@chromium.org>
> > Commit-Queue: Xianzhu Wang <wangxianzhu@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#710590}
> 
> TBR=wangxianzhu@chromium.org,schenney@chromium.org
> 
> Change-Id: Ic072356ff05e5c738f9b830a3ac398d0d8cb4f73
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1889710
> Reviewed-by: Takashi Sakamoto <tasak@google.com>
> Commit-Queue: Takashi Sakamoto <tasak@google.com>
> Cr-Commit-Position: refs/heads/master@{#710696}

TBR=wangxianzhu@chromium.org,tasak@google.com,schenney@chromium.org

Change-Id: Ia3500803eb9f24d078cc8919b453821147e3df9a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1890950
Reviewed-by: Xianzhu Wang <wangxianzhu@chromium.org>
Commit-Queue: Xianzhu Wang <wangxianzhu@chromium.org>
Cr-Commit-Position: refs/heads/master@{#710882}

Former-commit-id: dfc855bbc6ed9c84216104b7b224a3401f7c036b