Revert "DOMException use String instead of char*"
This reverts commit 9a434bc83c868fcf500de224f6e67adb07c46849.

Broke the build:
../../third_party/WebKit/Source/core/dom/DOMException.cpp: In static member function 'static WTF::PassRefPtr<WebCore::DOMException> WebCore::DOMException::create(WebCore::ExceptionCode, const WTF::String&)':
../../third_party/WebKit/Source/core/dom/DOMException.cpp:102: error: operands to ?: have different types 'WTF::ASCIILiteral' and 'const char [6]'
ninja: build stopped: subcommand failed.

TBR=arv@chromium.org
BUG=

Review URL: https://codereview.chromium.org/19460009

git-svn-id: svn://svn.chromium.org/blink/trunk@154532 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: 45e2163dc9f70cd4d8835c9ceaff8e1ea826a076