Revert of Separate trace config classes into multiple files (patchset #3 id:40001 of https://codereview.chromium.org/2085683002/ )
Reason for revert:
causing catapult roll failure: telemetry_perf_unittests

[1/1] measurements.measurement_smoke_test.MeasurementSmokeTest.testAllMeasurementInstance failed unexpectedly 0.0945s:
  Traceback (most recent call last):
    File "/tmp/isolated_run4dWHfM/tools/perf/measurements/measurement_smoke_test.py", line 63, in testAllMeasurementInstance
      _GetAllPossiblePageTestInstances()
    File "/tmp/isolated_run4dWHfM/tools/perf/measurements/measurement_smoke_test.py", line 52, in _GetAllPossiblePageTestInstances
      pt = benchmark_class().CreatePageTest(options)
    File "/tmp/isolated_run4dWHfM/third_party/catapult/telemetry/telemetry/benchmark.py", line 229, in CreatePageTest
      opts = self.CreateTimelineBasedMeasurementOptions()
    File "/tmp/isolated_run4dWHfM/tools/perf/benchmarks/tracing.py", line 45, in CreateTimelineBasedMeasurementOptions
      options.config.chrome_trace_config.SetMemoryDumpConfig(memory_dump_config)
    File "/tmp/isolated_run4dWHfM/third_party/catapult/telemetry/telemetry/timeline/chrome_trace_config.py", line 104, in SetMemoryDumpConfig
      'Must pass SetMemoryDumpConfig a MemoryDumpConfig instance')
  TypeError: Must pass SetMemoryDumpConfig a MemoryDumpConfig instance

https://build.chromium.org/p/tryserver.chromium.linux/builders/linux_chromium_rel_ng/builds/250550/steps/telemetry_perf_unittests%20%28with%20patch%29%20on%20Ubuntu-12.04/logs/stdio

Original issue's description:
> Separate trace config classes into multiple files
>
> BUG=catapult:#2413
> TBR=nednguyen@google.com
>
> Committed: https://chromium.googlesource.com/external/github.com/catapult-project/catapult/+/2b9b47934acdf996b415cccaf0fdbba0a9c601e8 [formerly b4b7367a811e5c877df6ed0ef069342b03d8666d]

TBR=nednguyen@google.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=catapult:#2413

Review-Url: https://codereview.chromium.org/2085343004

Former-commit-id: ea4633b677af6cde215b0476fdfd5f1363cab1bf