Rename AppListMainViewTest::ContentsView to AppListMainViewTest::GetContentsView to avoid build failure
The usage of unqualified ContentsView causes the build failure while using gcc 4.8 toolchain as below

ui/app_list/views/app_list_main_view_unittest.cc:157:70:
error: declaration of ‘app_list::ContentsView* app_list::test::{anonymous}::AppListMainViewTest::ContentsView()’ [-fpermissive]
   ContentsView* ContentsView() { return main_view_->contents_view(); }
                                                                      ^
In file included from ../../ui/app_list/views/app_list_main_view_unittest.cc:18:0:
ui/app_list/views/contents_view.h:45:7: error: changes meaning of ‘ContentsView’ from ‘class app_list::ContentsView’ [-fpermissive]
 class APP_LIST_EXPORT ContentsView : public views::View,

Review URL: https://codereview.chromium.org/771063002

Cr-Commit-Position: refs/heads/master@{#306360}

Former-commit-id: 381fea549f67c655b991b77cefe2c468d81c754d