Compilation error when an array is presented in the arguments
We have to remove the square brackets if presented otherwise the
array variable will be passed as variable[] and that will cause a build
failure:

gen/modules/desktop_capture/linux/pipewire_stubs.cc:85:26: error: expected expression
  pw_init_ptr(argc, argv[]);
                         ^

Change-Id: I60595a0ce4a4f618fcb904cc3654ce4304fd1ff9
Reviewed-on: https://chromium-review.googlesource.com/c/1312950
Reviewed-by: Thomas Anderson <thomasanderson@chromium.org>
Reviewed-by: Scott Graham <scottmg@chromium.org>
Commit-Queue: Thomas Anderson <thomasanderson@chromium.org>
Cr-Commit-Position: refs/heads/master@{#604975}
Former-commit-id: a664fd3b4131e5291f024e721af72c69acdec408