Fix bug caught by clang's -Wlogical-not-parentheses
../../ppapi/proxy/ppb_image_data_proxy.cc:153:9: error: logical not is only applied to the left hand side of this comparison [-Werror,-Wlogical-not-parentheses]
    if (!images_[i].image->type() == type)
        ^                         ~~
../../ppapi/proxy/ppb_image_data_proxy.cc:153:9: note: add parentheses after the '!' to evaluate the comparison first
    if (!images_[i].image->type() == type)
        ^
         (                               )
../../ppapi/proxy/ppb_image_data_proxy.cc:153:9: note: add parentheses around left hand side expression to silence this warning
    if (!images_[i].image->type() == type)
        ^
        (                        )
1 error generated.

(Since PPB_ImageData_Shared::ImageDataType currently has only two values, this is no behavior change.)

BUG=262248
R=yzshen@chromium.org

Review URL: https://codereview.chromium.org/19954006

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@212908 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 2b53078fea6c2c2aa00502850824d8269c796dce