[Dice] Add error action button to account control in settings
When the user has an actionable sync error, a button to resolve
the error is shown in the sync account control row on settings
pages.

Exception: The passphrase action button is not shown on the sync
page because this page has its customized passphrase UI.

Bug: 902949
Change-Id: I558a79be8cb75f2a9260bf8e3236e7ef956627db
Reviewed-on: https://chromium-review.googlesource.com/c/1333768
Commit-Queue: Thomas Tangl <tangltom@chromium.org>
Reviewed-by: Scott Chen <scottchen@chromium.org>
Cr-Commit-Position: refs/heads/master@{#608405}
Former-commit-id: b3de1b05dc5f39519b8088e265391c5d9e132c7a