[Qt][Mac] Unreviewed fix the build after r138413 https://bugs.webkit.org/show_bug.cgi?id=105686
Don't use a temporary const reference so the compiler doesn't make a copy.
An example compile error (clang):
Source/WebCore/loader/CookieJar.cpp:73:67: error: copying parameter of type 'WebCore::NetworkStorageSession' invokes deleted constructor
    return platformStrategies()->cookiesStrategy()->cookiesForDOM(SESSION(document), document->firstPartyForCookies(), url);


* loader/CookieJar.cpp:
(WebCore::cookies):
(WebCore::setCookies):
(WebCore::cookiesEnabled):
(WebCore::cookieRequestHeaderFieldValue):
(WebCore::getRawCookies):
(WebCore::deleteCookie):


git-svn-id: svn://svn.chromium.org/blink/trunk@138421 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: 15b5040edcb0687d92119020a1c19caf2183fcb9