Revert "[Telemetry] Split key_mobile_sites pages to key_mobile_sites_smooth and key_mobile_sites_repaint"
This reverts commit a51a062868b205012eea00dc500ec15952672664 [formerly 68689c53a539564a078ebe3473eb99748561b3b4].

broke telemetry_perf_unittests
http://build.chromium.org/p/chromium.linux/buildstatus?builder=Linux%20Tests&number=18027
http://build.chromium.org/p/chromium.mac/buildstatus?builder=Mac10.8%20Tests&number=1928
http://build.chromium.org/p/chromium.mac/buildstatus?builder=Mac10.6%20Tests&number=1887

  Traceback (most recent call last):
    File "/mnt/data/b/build/slave/Linux_Tests/build/src/tools/telemetry/telemetry/decorators.py", line 55, in wrapper
      func(*args, **kwargs)
    File "/mnt/data/b/build/slave/Linux_Tests/build/src/tools/perf/page_sets/page_set_unittest.py", line 18, in testSmoke
      self.RunSmokeTest(page_sets_dir, top_level_dir)
    File "/mnt/data/b/build/slave/Linux_Tests/build/src/tools/telemetry/telemetry/unittest_util/page_set_smoke_test.py", line 145, in RunSmokeTest
      page_set = page_set_class()
    File "/mnt/data/b/build/slave/Linux_Tests/build/src/tools/perf/page_sets/key_mobile_sites_smooth.py", line 132, in __init__
      self.AddPage(_CreatePageClassWithSmoothInteractions(page_class)(self))
  AttributeError: 'KeyMobileSitesSmoothPageSet' object has no attribute 'AddPage'

TBR=nednguyen
NOTRY=true
BUG=418375

Review URL: https://codereview.chromium.org/792803003

Cr-Commit-Position: refs/heads/master@{#308923}

Former-commit-id: ad282a69cf43d7f6b9e515bb97d7fc75825a33d3