tools/android/loading Ignore 'p' trace events
These events can happen in practice, and thus the analysis should not
crash in that case. Instead, these events are now ignored.

The error was:

__init__ at tools/android/loading/tracing.py:318
  'Deprecated event: %s' % tracing_event)

DevToolsConnectionException: Deprecated event: {u'name': u'EmbeddedWorkerInstance::Start', u'tts': 163020, u'args': {u'step': u'OnProcessAllocated', u'Is New Process': False}, u'pid': 13875, u'ts': 517201903, u'cat': u'ServiceWorker', u'tid': 13898, u'ph': u'p', u'id': u'0xaf5594c526a89982'}

Review URL: https://codereview.chromium.org/1853753004

Cr-Commit-Position: refs/heads/master@{#385174}

Former-commit-id: 6c2cfd7db70f6686439c78d8829a603c3605fb6e