Reland of MediaPerceptionPrivate API impl and testing. (patchset #1 id:1 of https://codereview.chromium.org/2899223003/ )
Reason for revert:
Reverting revert and then applying fix to compile issue so the original CL can be re-landed.

Original issue's description:
> Revert of MediaPerceptionPrivate API impl and testing. (patchset #24 id:460001 of https://codereview.chromium.org/2858353002/ )
>
> Reason for revert:
> This CL does not compile on ChromiumOS x86-generic. Error:
> [10333/23428] CXX obj/extensions/browser/api/api/media_perception_private_api.o
> FAILED: obj/extensions/browser/api/api/media_perception_private_api.o
> /b/c/goma_client/gomacc i686-pc-linux-gnu-g++ -B/b/c/b/ChromiumOS_x86_generic_Compile/.cros_cache/chrome-sdk/tarballs/x86-generic+9536.0.0+target_toolchain/usr/x86_64-pc-linux-gnu/i686-pc-linux-gnu/binutils-bin/2.25.51-gold -MMD -MF obj/extensions/browser/api/api/media_perception_private_api.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_ASH=1 -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DOS_CHROMEOS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DUSE_EGL -DTOOLKIT_VIEWS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY -DSK_HAS_JPEG_LIBRARY -DSK_SUPPORT_GPU=1 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -I../.. -Igen -I../../third_party/libwebp -I../../third_party/khronos -I../../gpu -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/libwebm/source -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/encode -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/third_party/vulkan -I../../third_party/skia/include/gpu -I../../third_party/skia/src/gpu -I../../third_party/skia/src/sksl -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../third_party/boringssl/src/include -I/b/c/b/ChromiumOS_x86_generic_Compile/.cros_cache/chrome-sdk/tarballs/x86-generic+9536.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz/usr/include/nss -I/b/c/b/ChromiumOS_x86_generic_Compile/.cros_cache/chrome-sdk/tarballs/x86-generic+9536.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz/usr/include/nspr -Igen -I../../third_party/WebKit -Igen/third_party/WebKit -I../../v8/include -Igen/v8/include -Igen -I/b/c/b/ChromiumOS_x86_generic_Compile/.cros_cache/chrome-sdk/tarballs/x86-generic+9536.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz/usr/include/dbus-1.0 -I/b/c/b/ChromiumOS_x86_generic_Compile/.cros_cache/chrome-sdk/tarballs/x86-generic+9536.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz/usr/lib/dbus-1.0/include -fno-strict-aliasing -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -m32 -msse2 -mfpmath=sse -mmmx -pthread -Wall -Werror -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g2 -gsplit-dwarf --sysroot=../../../.cros_cache/chrome-sdk/tarballs/x86-generic+9536.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz -fvisibility=hidden -std=gnu++11 -Wno-narrowing -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -march=i686 -pipe -march=i686 -pipe -pipe -march=i686 -mfpmath=sse -mmmx -msse -msse2 -msse3 -D__google_stl_debug_vector=1 -c ../../extensions/browser/api/media_perception_private/media_perception_private_api.cc -o obj/extensions/browser/api/api/media_perception_private_api.o
> ../../extensions/browser/api/media_perception_private/media_perception_private_api.cc: In function 'std::string extensions::{anonymous}::CallbackStatusToErrorMessage(const CallbackStatus&)':
> ../../extensions/browser/api/media_perception_private/media_perception_private_api.cc:30:1: error: control reaches end of non-void function [-Werror=return-type]
>  }
>  ^
> cc1plus.elf: all warnings being treated as errors
>
> Original issue's description:
> > MediaPerceptionPrivate API impl and testing.
> >
> > BUG=709180
> >
> > Review-Url: https://codereview.chromium.org/2858353002
> > Cr-Commit-Position: refs/heads/master@{#474260}
> > Committed: https://chromium.googlesource.com/chromium/src/+/e19aac9020752439d072e0f63b0b36e3c2033e5a [formerly 247725c00faa32d43ce0d8d8833edf4167b36ee1]
>
> TBR=rkc@chromium.org,mattfrazier@chromium.org,weigua@chromium.org,sque@chromium.org,bmayer@chromium.org,tbarzic@chromium.org,rkc@google.com,stevenjb@chromium.org,rdevlin.cronin@chromium.org,lasoren@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=709180
>
> Review-Url: https://codereview.chromium.org/2899223003
> Cr-Commit-Position: refs/heads/master@{#474269}
> Committed: https://chromium.googlesource.com/chromium/src/+/1d0809a5537449be345aacf8ea7fe6ad9b604d61 [formerly 467392f531896372d0b804579dbcb43653b5f304]

TBR=rkc@chromium.org,mattfrazier@chromium.org,weigua@chromium.org,sque@chromium.org,bmayer@chromium.org,tbarzic@chromium.org,rkc@google.com,stevenjb@chromium.org,rdevlin.cronin@chromium.org,vitaliii@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
# lasoren@: Removed auto-generated skipped CQ checks.
# NOPRESUBMIT=true
# NOTREECHECKS=true
# NOTRY=true
BUG=709180

Review-Url: https://codereview.chromium.org/2901983003
Cr-Commit-Position: refs/heads/master@{#474333}

Former-commit-id: 36fd42f5b428e6bc287cc53d6c5f2f12aebdd397