Revert "[leveldb_proto] Add support for automatic conversion to client type."
This reverts commit 9af2179239bdf7e7c5aa275b19d122c50782f936 [formerly fe51f52034fb1d57844759a258eca133a9f69ff8].

Reason for revert: Breaks ios-simulator-xcode-clang

https://ci.chromium.org/p/chromium/builders/ci/ios-device-xcode-clang/89533

In file included from ../../components/feature_engagement/internal/tracker_impl.cc:36:
In file included from ../../components/leveldb_proto/public/proto_database_provider.h:13:
../../components/leveldb_proto/internal/proto_database_impl.h:204:5: error: no matching function for call to 'MakeCheckOpValueString'
    DCHECK_EQ(std::make_unique<P>(), proto);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../base/logging.h:978:31: note: expanded from macro 'DCHECK_EQ'
#define DCHECK_EQ(val1, val2) DCHECK_OP(EQ, ==, val1, val2)
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../base/logging.h:950:29: note: expanded from macro 'DCHECK_OP'
  EAT_STREAM_PARAMETERS << (::logging::MakeCheckOpValueString(      \
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../components/leveldb_proto/internal/proto_database_impl.h:214:10: note: in instantiation of function template specialization 'leveldb_proto::(anonymous namespace)::ParseToProto<feature_engagement::Event>' requested here
  return ParseToProto<T>(serialized_entry);
         ^
../../components/leveldb_proto/internal/proto_database_impl.h:288:20: note: in instantiation of function template specialization 'leveldb_proto::(anonymous namespace)::ParseToClientType<feature_engagement::Event, feature_engagement::Event, nullptr>' requested here
      auto entry = ParseToClientType<P, T>(serialized_entry);
                   ^
../../components/leveldb_proto/internal/proto_database_impl.h:480:38: note: in instantiation of function template specialization 'leveldb_proto::(anonymous namespace)::ParseLoadedEntries<feature_engagement::Event, feature_engagement::Event>' requested here
                     base::BindOnce(&ParseLoadedEntries<P, T>,
                                     ^
../../components/leveldb_proto/internal/proto_database_impl.h:77:3: note: in instantiation of member function 'leveldb_proto::ProtoDatabaseImpl<feature_engagement::Event, feature_engagement::Event>::LoadEntriesWithFilter' requested here
  ProtoDatabaseImpl(ProtoDbType db_type,
  ^
...

Original change's description:
> [leveldb_proto] Add support for automatic conversion to client type.
> 
> The leveldb_proto::ProtoDatabase is a widely used storage backend in
> Chrome, but it only supports storing protocol buffers when using the
> external API.
> 
> This CL makes it possible for clients to use ProtoDatabase<P, T>,
> where P is their proto type, and T is their own type. Previously it was
> only possible to pass in a proto type as the template argument. If no
> client type is specified, it defaults to providing the proto type as
> the API for all calls like before, so no changes are required to
> current clients.
> 
> For clients to be able to use this, they must implement conversion
> methods to and from their proto type and their client type. This must
> be within the leveldb_proto namespace and for T=ClientStruct and
> P=ClientProto it would have the form:
> namespace leveldb_proto {
> void DataToProto(const ClientStruct& data, ClientProto* proto);
> void ProtoToData(const ClientProto& proto, ClientStruct* data);
> }  // namespace leveldb_proto
> 
> For retrieving a database of proto type ClientProto, use:
> auto db = ProtoDatabaseProviderFactory::GetForBrowserContext(...)
>               -> GetDB<ClientProto>(...);
> For automatically converting to a different data type, use:
> auto db = ProtoDatabaseProviderFactory::GetForBrowserContext(...)
>               -> GetDB<ClientProto, ClientStruct>(...);
> 
> Bug: 939986
> Change-Id: I3587d9e9fb72d30a39276a66df4eafa5b9e7fdcb
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1513279
> Reviewed-by: Filip Gorski <fgorski@chromium.org>
> Reviewed-by: oysteine <oysteine@chromium.org>
> Commit-Queue: Tommy Nyquist <nyquist@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#639674}

TBR=nyquist@chromium.org,fgorski@chromium.org,oysteine@chromium.org

Change-Id: I3d0ee06b31227a17fd75a1c72fc79e54c8204154
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 939986
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1516115
Reviewed-by: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Commit-Queue: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Cr-Commit-Position: refs/heads/master@{#639685}
Former-commit-id: 2a15ae9df1d9fb5b4edc81fc3476115a172b06ab