Reland "Workaround for MSVC compile error"
This reverts commit 3f4fbc952b9a251f8968c894b7c94d685c1e91b8 [formerly 2beb9191c6c2781e3ec951beb12e8ada6e0d516b].

Reason for revert: actually... let's keep the bot green and follow-up when you have a chance. Thanks!

Original change's description:
> Revert "Workaround for MSVC compile error"
> 
> This reverts commit 91239edd35034fede9a1596aa5ac4c10354ca46b [formerly 0e68cf3c41473758837e87a90bbfd598c02bb420].
> 
> Reason for revert: Not LGTM (see original CL)
> 
> Original change's description:
> > Workaround for MSVC compile error
> > 
> > This is workaround for MSVC compile error.
> > ../../base/task_scheduler/task_tracker.cc(458): error C2440: 'initializing': cannot convert from 'base::HistogramBase *const (*)[2]' to 'base::HistogramBase *const (*&)[2]'
> > 
> > This has been happening on
> > https://ci.chromium.org/buildbot/chromium.fyi/WinMSVC64%20Goma%20Canary/6721
> > 
> > Change-Id: I64401b69a4ad2e1f9ea4716e127f26b0de662909
> > Reviewed-on: https://chromium-review.googlesource.com/1084131
> > Reviewed-by: Nico Weber <thakis@chromium.org>
> > Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#563995}
> 
> TBR=gab@chromium.org,thakis@chromium.org,tikuta@chromium.org
> 
> Change-Id: I7ec4980c495d322e7c0cf96b478a8be37a3abda3
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/1085928
> Reviewed-by: Gabriel Charette <gab@chromium.org>
> Commit-Queue: Gabriel Charette <gab@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#564192}

TBR=gab@chromium.org,thakis@chromium.org,tikuta@chromium.org

Change-Id: I4e5c93d6f306698c89ff653d4733e6921caae78b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/1085969
Reviewed-by: Gabriel Charette <gab@chromium.org>
Commit-Queue: Gabriel Charette <gab@chromium.org>
Cr-Commit-Position: refs/heads/master@{#564199}
Former-commit-id: 91f4df98ca3ab2ca788d25641b4b7d882678e97b