Fix a lint issue with UsbMidiDeviceAndroid.java.
Currently, the lint warns at:
Error: Call requires API level 18 (current min is 14):
    android.hardware.usb.UsbDeviceConnection#bulkTransfer [NewApi]

So we need to add @TargetApi to suppress this lint error.

BUG=327768

Review URL: https://codereview.chromium.org/276943002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@269528 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 93bc6213b729bff7d1fae5bc79356c8d7b328f48