Revert of Remove adb_commands from android_browser_backend and android_browser_backend_settings. (patchset #6 id:100001 of https://codereview.chromium.org/1213423003/)
Reason for revert:
Speculative revert. Looks like this patch broke android bots with "AttributeError: 'WebviewShellBackendSettings' object has no attribute '_backend_settings'".

See https://build.chromium.org/p/chromium.gpu/builders/Android%20Debug%20%28Nexus%205%29/builds/866.

Original issue's description:
> Remove adb_commands from android_browser_backend and android_browser_backend_settings.
>
> Pulled from https://codereview.chromium.org/1167173002/
>
> BUG=476709
>
> Committed: https://crrev.com/ad630f737d53b3317d47cdcca0c6070be2082288 [formerly 2e706aa8db5d0cfd09573ad56903868c4d8cd4ee]
> Cr-Commit-Position: refs/heads/master@{#338229}

TBR=jbudorick@chromium.org,nednguyen@chromium.org,sullivan@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=476709

Review URL: https://codereview.chromium.org/1224273007

Cr-Commit-Position: refs/heads/master@{#338276}

Former-commit-id: 983ac23f007eb5bfb10f5516460998cbd18f388b