Revert of Add Mojo interface for AudioDecoder (patchset #2 id:20001 of https://codereview.chromium.org/1809483002/ )
Reason for revert:
Compile failures on Windows GN bots:
https://build.chromium.org/p/chromium.win/builders/Win%20x64%20GN/builds/11754

e:\b\build\slave\win_x64_gn\build\src\out\release_x64\gen\media\mojo\interfaces\audio_decoder.mojom.h(79): error C2059: syntax error: 'constant'
e:\b\build\slave\win_x64_gn\build\src\out\release_x64\gen\media\mojo\interfaces\audio_decoder.mojom.h(79): error C3805: 'constant': unexpected token, expected either '}' or a ','
e:\b\build\slave\win_x64_gn\build\src\out\release_x64\gen\media\mojo\interfaces\audio_decoder.mojom.h(216): error C2589: 'constant': illegal token on right side of '::'
e:\b\build\slave\win_x64_gn\build\src\out\release_x64\gen\media\mojo\interfaces\audio_decoder.mojom.h(216): error C2059: syntax error: '::'

Original issue's description:
> Add Mojo interface for AudioDecoder
>
> For Spitzer, the audio decoder that supports encryption has to be
> instantiated in the GPU process. The decoder has to be split
> between a proxy and a service.
>
> This CL contains Mojo interface only.
>
> BUG=542910
>
> Committed: https://crrev.com/bc8ea7e4e1c6352797a5244c5163ef517dc5d8c3 [formerly cabbc3cc9b0c18f25d91f17bb6cdded528366695]
> Cr-Commit-Position: refs/heads/master@{#381360}

TBR=xhwang@chromium.org,timav@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=542910

Review URL: https://codereview.chromium.org/1808623002

Cr-Commit-Position: refs/heads/master@{#381389}

Former-commit-id: 36247d5f2daf9c6a65a7fdd7c6e7d4dd11fee12a