Clean up code a bit in MockPeerConnectionImpl. This addresses an issue in non-clang builds on ubuntu 12.04 using gcc 4.6.4 which has been in there for a while now:
The error is as follows:

../../content/renderer/media/mock_peer_connection_impl.cc: In member function
'virtual bool content::MockPeerConnectionImpl::GetStats(webrtc::StatsObserver*,
webrtc::MediaStreamTrackInterface*,
webrtc::PeerConnectionInterface::StatsOutputLevel)':
../../content/renderer/media/mock_peer_connection_impl.cc:280:3: error: in C++98
'value' must be initialized by constructor, not by '{...}'
../../content/renderer/media/mock_peer_connection_impl.cc:293:5: error: in C++98
'value2' must be initialized by constructor, not by '{...}'

R=xians@chromium.org

Review URL: https://codereview.chromium.org/415403002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@285547 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 40cb6e8aa01746da8234334b609d03325b1441fb