<http://webkit.org/b/57239> Use forward class declaration instead of including header
Reviewed by Dan Bernstein.

Adding a "using namespace WebCore;" statement in a header may
cause issues when <WebCore/Length.h> is included before
<CoreText/CoreText.h>.

Length.h defines the LengthType enum with a 'Fixed' value.
CoreText.h includes MacTypes.h, which has a
"typedef SInt32 Fixed;" statement, and then CoreText.h includes
other headers that also use 'Fixed', but expect the typedef to
be defined, not the enum.  If another header includes
"using namespace WebCore;" before CoreText.h, the
following compiler errors result (paths abbreviated):

    CoreText.framework/Headers/SFNTLayoutTypes.h:689: error: reference to 'Fixed' is ambiguous
    MacTypes.h:184: error: candidates are: typedef SInt32 Fixed
    Length.h:37: error:                 WebCore::LengthType WebCore::Fixed
    SFNTLayoutTypes.h:689: error: 'Fixed' does not name a type

* platform/mac/HTMLConverter.h: Use forward declaration of
DocumentLoader class instead of including header.  Remove the
unused "using namespace WebCore;" statement.

git-svn-id: svn://svn.chromium.org/blink/trunk@82128 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: 2918138d93907896a9eac16e51db62e10a9f54e2