cc: GN Build fix.
Add missing entries to cc sources list.

This should fix the following errors:
../../cc/output/compositor_frame_metadata.cc:14: error: undefined
reference to 'cc::ViewportSelectionBound::ViewportSelectionBound()'
../../cc/trees/layer_tree_host.cc:120: error: undefined reference to
'cc::LayerSelectionBound::LayerSelectionBound()'

http://build.chromium.org/p/tryserver.chromium/builders/linux_chromium_gn_rel/builds/22568/steps/compile/logs/stdio

This was found while doing:
https://codereview.chromium.org/361373002/

BUG=None
TEST=None
R=danakj@chromium.org

Review URL: https://codereview.chromium.org/369123002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@281299 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: b2ba2d4ddc3f87e328c7e074fd1f82d22e19f0dc