Revert "Add a histogram to record IPP versions."
This reverts commit d176f5a09300f44a94845f5a4b056e57d4633187 [formerly da07f633faa18b1e603244c3700622faff09b92c].

Reason for revert: Broke libFuzzer ChromeOS bot
https://ci.chromium.org/p/chromium/builders/ci/Libfuzzer%20Upload%20Chrome%20OS%20ASan?limit=200
../../chrome/browser/chromeos/printing/printer_info_cups.cc:95:3: error: [chromium-style] auto variable type must not deduce to a raw pointer type.
auto iter = std::find_if(
^~~~
auto*
1 error generated.

Original change's description:
> Add a histogram to record IPP versions.
> 
> Adding Printing.CUPS.HighestIppVersion which will record the largest
> version a printer supports when it is queried during setup.
> 
> Bug: chromium:1020016
> Change-Id: I7180ed1f147b812d660903381af7aaba6e500bcb
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1892193
> Reviewed-by: Bailey Berro <baileyberro@chromium.org>
> Reviewed-by: Jesse Doherty <jwd@chromium.org>
> Commit-Queue: Sean Kau <skau@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#714028}

TBR=jwd@chromium.org,skau@chromium.org,baileyberro@chromium.org

Change-Id: I603b7c6535f386416d718e2034462aa544fcbd05
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: chromium:1020016
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1908627
Reviewed-by: Abhishek Arya <inferno@chromium.org>
Commit-Queue: Abhishek Arya <inferno@chromium.org>
Cr-Commit-Position: refs/heads/master@{#714108}

Former-commit-id: 14e567754ff9abe972a63c95bea8d8150b22307f