Revert of Update mojo Decryptor interface to support reusing shared memory (patchset #3 id:60001 of https://codereview.chromium.org/1766093004/ )
Reason for revert:
Broke the win build:

https://build.chromium.org/p/chromium.win/builders/Win%20x64%20GN/builds/11754/steps/compile/logs/stdio

FAILED: ninja -t msvc -e environment.x64 -- E:\b\build\goma/gomacc.exe "E:\b\depot_tools\win_toolchain\vs_files\a3796183a9fc4d22a687c5212b9c76dbd136d70d\VC\bin\amd64/cl.exe" /nologo /showIncludes /FC @obj/media/mojo/services/application/service_factory_impl.obj.rsp /c ../../media/mojo/services/service_factory_impl.cc /Foobj/media/mojo/services/application/service_factory_impl.obj /Fdobj/media/mojo/services/application_cc.pdb
e:\b\build\slave\win_x64_gn\build\src\media\mojo\services\mojo_decryptor_service.h(99): error C2039: 'unordered_map': is not a member of 'std'
e:\b\depot_tools\win_toolchain\vs_files\a3796183a9fc4d22a687c5212b9c76dbd136d70d\vc\include\list(15): note: see declaration of 'std'
e:\b\build\slave\win_x64_gn\build\src\media\mojo\services\mojo_decryptor_service.h(99): error C2143: syntax error: missing ';' before '<'
e:\b\build\slave\win_x64_gn\build\src\media\mojo\services\mojo_decryptor_service.h(99): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
e:\b\build\slave\win_x64_gn\build\src\media\mojo\services\mojo_decryptor_service.h(100): error C2238: unexpected token(s) preceding ';'
FAILED: ninja -t msvc -e environment.x64 -- E:\b\build\goma/gomacc.exe "E:\b\depot_tools\win_toolchain\vs_files\a3796183a9fc4d22a687c5212b9c76dbd136d70d\VC\bin\amd64/cl.exe" /nologo /showIncludes /FC @obj/media/mojo/services/cdm_service/mojo_cdm_service.obj.rsp /c ../../media/mojo/services/mojo_cdm_service.cc /Foobj/media/mojo/services/cdm_service/mojo_cdm_service.obj /Fdobj/media/mojo/services/cdm_service_cc.pdb
e:\b\build\slave\win_x64_gn\build\src\media\mojo\services\mojo_decryptor_service.h(99): error C2039: 'unordered_map': is not a member of 'std'
e:\b\depot_tools\win_toolchain\vs_files\a3796183a9fc4d22a687c5212b9c76dbd136d70d\vc\include\list(15): note: see declaration of 'std'
...

Original issue's description:
> Update mojo Decryptor interface to support reusing shared memory
>
> Now that VideoFrames are transported across mojo using shared memory,
> the original needs to stay around until the other side is no longer
> using it, after which the shared memory can be reused for a
> subsequent VideoFrame.
>
> BUG=510153
>
> Committed: https://crrev.com/8fb5db27b5418f913c311adf8e9427253cd942f4 [formerly 30752f9101640c873987758baa4b11407aaf3029]
> Cr-Commit-Position: refs/heads/master@{#381361}

TBR=xhwang@chromium.org,rockot@chromium.org,jrummell@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=510153

Review URL: https://codereview.chromium.org/1809573002

Cr-Commit-Position: refs/heads/master@{#381383}

Former-commit-id: 0ab19d0f23f04db37d71a79b9446bdb9bbae9c27