Revert of [ash-md] Adds Material Design elements to VPN page (patchset #3 id:40001 of https://codereview.chromium.org/2506873002/ )
Reason for revert:
Failed compilation on Linux ChromiumOS: https://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Full/builds/56721/steps/compile/logs/stdio

error: no member named 'InkDropStyle' in 'ash::SystemMenuButton'
in vpn_list_view.cc

Original issue's description:
> [ash-md] Adds Material Design elements to VPN page
>
> This CL changes the looks of VPN provider header rows. It does not yet
> make those rows sticky since this would have exposed the challenge that
> the current implementation of sticky rows has with the child controls
> in scroll contents that have layers (such as the "Disconnect" buttons
> in this page).
>
> BUG=663477
>
> Committed: https://crrev.com/4fa324b7ab47a5807c7cd400ddab8b9543d5957b [formerly e7e95626e7731055758ae07f67f5cab889637e55]
> Cr-Commit-Position: refs/heads/master@{#432807}

TBR=tdanderson@chromium.org,varkha@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=663477

Review-Url: https://codereview.chromium.org/2511693002
Cr-Commit-Position: refs/heads/master@{#432814}

Former-commit-id: ae11de8293fe9f66f99895f5f56dd6e27bdf1e8d