Fix build error with gcc 4.9.3
native_backend_kwallet_x.cc:391:1:
  error: control reaches end of non-void function [-Werror=return-type]

Regression introduced by https://codereview.chromium.org/2057123002

BUG=602624

R=vabr@chromium.org

Review-Url: https://codereview.chromium.org/2090343002
Cr-Commit-Position: refs/heads/master@{#401601}

Former-commit-id: 450339b9492844c74ba3b07aebca7d6c5770b984