NaCl: Update revision in DEPS, r12810 -> r12835
This includes PNaCl's merge of LLVM 3.4.

Due to Clang 3.4's new warnings, I've disabled some warnings in the
NaCl SDK's build of gtest, which gave:
gtest-filepath.cc:87:12: error: unused variable 'kPathSeparatorString' [-Werror,-Wunused-const-variable]

This pulls in the following Native Client changes:

r12811: (jfb) Update TOOL_REVISIONS for PNaCl r12786->r12809
r12812: (kschimpf) Test pnacl-compress fixpointing.
r12813: (jfb) Update TOOL_REVISIONS for PNaCl r12809->r12810
r12814: (dyen) Attempt to unify our platform/OS and architecture collapsing in python
r12815: (jvoung) Remove NACL_RODATA_FLAG to go between -Trodata-segment, and --section-start.
r12816: (mseaborn) PNaCl: Merge LLVM 3.4: update Git revs, driver scripts and test expectations
r12817: (jfb) Update TOOL_REVISIONS for PNaCl r12810->r12816 to bring in merge of LLVM 3.4
r12818: (mseaborn) Fix download_toolchains.py (breakage from r12814)
r12819: (mseaborn) PNaCl: LLVM 3.4 merge: Update test expectations for flaky tests on Cygwin
r12820: (mcgrathr) Update chrome_rev to current LKGR
r12822: (noelallen) Roll bionic
r12823: (mseaborn) IRT: Hide the "dev_getpid" IRT interface by default
r12824: (noelallen) Roll bionic toolchain into TOOL_REVs
r12825: (bradnelson) Adding timeout mechanism to command tester.
r12826: (jvoung) Apply -f*-sections and --gc-sections to IRT build.
r12827: (mseaborn) IRT: Disable various IRT interfaces for in-browser-translated PNaCl pexes
r12828: (jvoung) Remove -reduce-memory-footprint: just make it the default w/ streaming.
r12829: (sbc) Roll glibc version in tools/REVISIONS
r12830: (bradnelson) Fix multidomain_test flake on x86-32 windows.
r12831: (jvoung) Make pnacl-readelf a slightly better wrapper around readelf.
r12832: (mseaborn) PNaCl: Remove toolchain's dependency on x86-32 version of libtinfo on Linux
r12833: (bradnelson) Wait longer for debug_stub_tests, kill more effectively on windows.
r12834: (jvoung) PNaCl: Update LLVM revision in pnacl/COMPONENT_REVISIONS
r12835: (jfb) Update TOOL_REVISIONS for PNaCl r12816->r12832

BUG=none
TEST=browser_tests and nacl_integration

Review URL: https://codereview.chromium.org/187673006

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@255395 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: a87b08bd8843802296e7f8925b14088deb6a2941