Revert 125220 - Now that uploading to breakpad works on all threads add it to all places that we could return an unrecoverable error. Those places include: 1. Failed model association resulting in unrecoverable error being called on DTC. 2. When disabling a single type due to a perdatatype error. 3. Failing to download requested types resulting in unrecoverable error.
Clang error on cros: 

In file included from ./chrome/browser/sync/glue/app_notification_data_type_controller.h:12:
./chrome/browser/sync/glue/ui_data_type_controller.h:80:11: error: [chromium-style] Overriding method must be marked with OVERRIDE.
  virtual void RecordUnrecoverableError(
          ^

BUG=
TEST=


Review URL: http://codereview.chromium.org/9428054

TBR=lipalani@chromium.org
Review URL: https://chromiumcodereview.appspot.com/9592023

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@125223 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 0645650e4f85fc149e5a4ce8243e470ce05c1f67