Revert of Update the Supervised User confirmation dialog when the profile changes (patchset #4 id:100001 of https://codereview.chromium.org/1298823004/ )
Reason for revert:
Likely cause of breaks the Linux GN bot:

http://build.chromium.org/p/chromium.linux/builders/Linux%20GN/builds/30848
http://build.chromium.org/p/chromium.linux/builders/Linux%20GN/builds/30852

ManageProfileUITest.CloseConfirmationOnDelete (run #1):
[ RUN      ] ManageProfileUITest.CloseConfirmationOnDelete
LaunchProcess: failed to execvp:
/tmp/run_tha_testdq28RT/out/Release/nacl_helper
[1:1:0821/120709:ERROR:nacl_fork_delegate_linux.cc(314)] Bad NaCl helper startup ack (0 bytes)
Xlib:  extension "RANDR" missing on display ":9".
Xlib:  extension "RANDR" missing on display ":9".
[14021:14021:0821/120709:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused
[14021:14021:0821/120709:WARNING:password_store_factory.cc(349)] Using basic (unencrypted) store for password storage. See http://code.google.com/p/chromium/wiki/LinuxPasswordStorage for more information about password storage options.
[14021:14042:0821/120709:ERROR:nacl_browser.cc(270)] Failed to open NaCl IRT file "/tmp/run_tha_testdq28RT/out/Release/nacl_irt_x86_64.nexe": -4
[14021:14021:0821/120710:WARNING:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
[14021:14021:0821/120710:INFO:CONSOLE(1324)] "Running TestCase ManageProfileUITest.CloseConfirmationOnDelete", source: test_api.js (1324)
[14021:14021:0821/120710:ERROR:web_ui_test_handler.cc(76)] undefinedFailed: RUN_TEST_F("ManageProfileUITest","CloseConfirmationOnDelete")
TypeError: SupervisedUserCreateConfirmOverlay.onDeletedProfile is not a function
    at Object.\u003Canonymous> (manage_profile_browsertest.js:421:38)
    at Object.Test.runTest (test_api.js:341:16)
    at Object.TestCase.runTest (test_api.js:478:22)
    at Object.TestCase.run (test_api.js:508:14)
    at RUN_TEST_F (test_api.js:1325:21)
    at expectFunc (test_api.js:1120:20)
    at runTestFunction (test_api.js:1193:37)
    at runTest (test_api.js:1167:18)
    at \u003Canonymous>:1:1
gen/chrome/test/manage_profile_browsertest-gen.cc:97: Failure
Value of: RunJavascriptTestF(false, "ManageProfileUITest", "CloseConfirmationOnDelete")
  Actual: false
Expected: true
[  FAILED  ] ManageProfileUITest.CloseConfirmationOnDelete, where TypeParam =  and GetParam() =  (857 ms)

Original issue's description:
> Update the Supervised User confirmation dialog when the profile changes
>
> Observe the ProfileInfoCache and update or close the Supervised User
> creation confirmation dialog when the new profile is renamed or deleted.
>
> BUG=501224
>
> Committed: https://crrev.com/abb5c745e02886a09d0b2c68912fb830d2c4b29b [formerly a6dd3c973b60ce7438b9648210fed2b40599536f]
> Cr-Commit-Position: refs/heads/master@{#344826}

TBR=mlerman@chromium.org,treib@chromium.org,pam@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=501224

Review URL: https://codereview.chromium.org/1307023002

Cr-Commit-Position: refs/heads/master@{#344859}

Former-commit-id: 8dbd0f5c7ecb5809b8cc77b727c5039e1eb84f83