Revert "Migrate PanelState from enum to @IntDef + remove one Map"
This reverts commit 9b7f270afd7046f01bf6debb9d381fb006f57cc2 [formerly d9d05e1816ec9476566bda460d9a394d629f8afc].

Reason for revert: 
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
  at org.chromium.chrome.browser.compositor.bottombar.OverlayPanelBase.getPreviousPanelState	(OverlayPanelBase.java: 620)
  at org.chromium.chrome.browser.compositor.bottombar.OverlayPanelBase.updatePanelForHeight	(OverlayPanelBase.java: 783)
  at org.chromium.chrome.browser.compositor.bottombar.OverlayPanelBase.setPanelHeight	(OverlayPanelBase.java: 758)
  at org.chromium.chrome.browser.compositor.bottombar.OverlayPanelAnimation.lambda$animatePanelTo$0$OverlayPanelAnimation	(OverlayPanelAnimation.java: 354)
  at org.chromium.chrome.browser.compositor.bottombar.OverlayPanelAnimation$$Lambda$0.onAnimationUpdate	(OverlayPanelAnimation.java)
  at org.chromium.chrome.browser.compositor.animation.CompositorAnimator.doAnimationFrame	(CompositorAnimator.java: 207)
  at org.chromium.chrome.browser.compositor.animation.CompositorAnimationHandler.pushUpdate	(CompositorAnimationHandler.java: 108)
  at org.chromium.chrome.browser.compositor.animation.CompositorAnimationHandler.pushUpdate	(CompositorAnimationHandler.java: 91)
  at org.chromium.chrome.browser.compositor.layouts.LayoutManager.onUpdate	(LayoutManager.java: 361)
  at org.chromium.chrome.browser.compositor.layouts.LayoutManager.onUpdate	(LayoutManager.java: 344)
  at org.chromium.chrome.browser.compositor.CompositorViewHolder.onCompositorLayout	(CompositorViewHolder.java: 738)
  at org.chromium.chrome.browser.compositor.CompositorView.onCompositorLayout	(CompositorView.java: 316)

Original change's description:
> Migrate PanelState from enum to @IntDef + remove one Map
> 
> @IntDef/@StringDef annotation are preferred way for declaring
> set of String/int values
> 
> 1. they need less space in APK than enum, see
> https://developer.android.com/topic/performance/reduce-apk-size#remove-enums
> 2. they give more control over allowed values than "static final" values
> 
> Main goal of patch is writing PanelState enum in the form common with other Chrome @IntDef:
> 
> 1. with @IntDef first, @Retention second
>    and related @interface third
> 2. with values inside @interface
> 3. with NUM_ENTRIES declaring number of entries
> 4. with comment about numbering from 0 without gaps
> 5. with @Retention(RetentionPolicy.SOURCE)
> 6. without "static final" in the @interface
> 
> There is additionally removed one unnecessary Map.
> 
> BUG=919666
> 
> Change-Id: I8149a0800bd5c0bb205028d230edadc83016ebb9
> Reviewed-on: https://chromium-review.googlesource.com/c/1142764
> Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> Reviewed-by: Donn Denman <donnd@chromium.org>
> Reviewed-by: David Trainor <dtrainor@chromium.org>
> Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#635196}

TBR=dtrainor@chromium.org,donnd@chromium.org,agrieve@chromium.org,marcin@mwiacek.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 919666, 936105
Change-Id: I58863b9ffe0dbdf311f0feb459729445b75af179
Reviewed-on: https://chromium-review.googlesource.com/c/1488575
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/master@{#635677}
Former-commit-id: 59ff769d101db57cf931afd11da30fd30f3b75c7