Revert "Attempt to deflake TabsTest#testToolbarSwipePrevTab*"
This reverts commit 79309931dccd26a6f862a5f7c1723f559e251c7a [formerly 76b7028543ea8ad2066bebd7077b121732d9e8d4].

Reason for revert:
ava.util.concurrent.TimeoutException: waitForCallback timed out!
	at org.chromium.base.test.util.CallbackHelper.waitForCallback(CallbackHelper.java:191)
	at org.chromium.base.test.util.CallbackHelper.waitForCallback(CallbackHelper.java:210)
	at org.chromium.chrome.browser.TabsTest.runToolbarSideSwipeTestOnCurrentModel(TabsTest.java:1627)
	at org.chromium.chrome.browser.TabsTest.testToolbarSwipeOnlyTab(TabsTest.java:1477)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.chromium.base.test.ScreenshotOnFailureStatement.evaluate(ScreenshotOnFailureStatement.java:37)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.chromium.chrome.test.ChromeActivityTestRule$1.evaluate(ChromeActivityTestRule.java:114)
	at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)

Original change's description:
> Attempt to deflake TabsTest#testToolbarSwipePrevTab*
> 
> This patch updated the toolbar swipe tests to not depend on criteria
> helpers and operate on about:blank pages rather than the ntp. Most
> importantly, this fixes an issue where we assert tab selection before
> waiting for the callback.
> 
> Bug: 813584
> Change-Id: I1e743291add6398bc3eebc06c03c6c69cefc21f9
> Reviewed-on: https://chromium-review.googlesource.com/1044538
> Reviewed-by: Ted Choc <tedchoc@chromium.org>
> Commit-Queue: Matthew Jones <mdjones@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#556240}

TBR=tedchoc@chromium.org,mdjones@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 813584
Change-Id: I5a6e7d7f585cae58772eb2474b08b45a2d71439c
Reviewed-on: https://chromium-review.googlesource.com/1048646
Commit-Queue: Ted Choc <tedchoc@chromium.org>
Reviewed-by: Ted Choc <tedchoc@chromium.org>
Reviewed-by: Matthew Jones <mdjones@chromium.org>
Cr-Commit-Position: refs/heads/master@{#556672}
Former-commit-id: a22c499ff243528554803aa68940ec5022a2708e