Revert "net: add Snap Start tests"
This reverts commit r65714. It broke the Linux shared library builders:

SOLINK(target) out/Debug/obj.target/net/libnet_base.so
/usr/bin/ld: error: out/Debug/obj.target/openssl/third_party/openssl/openssl/crypto/sha/sha512t.o: multiple definition of 'main'
/usr/bin/ld: out/Debug/obj.target/openssl/third_party/openssl/openssl/crypto/sha/sha256t.o: previous definition here

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@65715 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 79128ad5039f5e88c75fe89867c4401bb0a3ed4c