Revert of Fix flakiness of DesktopDragDropClientAuraX11Tests (https://codereview.chromium.org/431973006/)
Reason for revert:
http://build.chromium.org/p/chromium.memory/builders/Linux%20ASan%20LSan%20Builder/builds/11578/steps/compile/logs/stdio#error1

FAILED: /b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/ui/views/widget/desktop_aura/views.desktop_drag_drop_client_aurax11.o.d -DV8_DEPRECATION_WARNINGS -DBLINK_SCALE_FILTERS_AT_RECORD_TIME -D_FILE_OFFSET_BITS=64 -DNO_TCMALLOC -DCHROMIUM_BUILD -DCR_CLANG_REVISION=214024 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_X11=1 -DUSE_CLIPBOARD_AURAX11=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DUSE_XI2_MT=2 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DUSE_UDEV -DENABLE_EGLIMAGE=1 -DADDRESS_SANITIZER -DMEMORY_TOOL_REPLACES_ALLOCATOR -DMEMORY_SANITIZER_INITIAL_SIZE -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DCLD2_DATA_SOURCE=static -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DVIEWS_IMPLEMENTATION -DGL_GLEXT_PROTOTYPES -DSK_ENABLE_INST_COUNT=0 -DSK_SUPPORT_GPU=1 '-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' -DSK_ENABLE_LEGACY_API_ALIASING=1 -DSK_ATTR_DEPRECATED=SK_NOTHING_ARG1 -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_WILL_NEVER_DRAW_PERSPECTIVE_TEXT -DSK_SUPPORT_LEGACY_PICTURE_CLONE -DSK_SUPPORT_LEGACY_GETDEVICE -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DSK_USE_POSIX_THREADS -DSK_DEFERRED_CANVAS_USES_FACTORIES=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DUSE_NSS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DLEAK_SANITIZER -DWTF_USE_LEAK_SANITIZER=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../third_party/wtl/include -I../.. -I../../skia/config -I../../third_party/khronos -I../../gpu -I../../third_party/skia/src/core -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../skia/ext -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -Igen/ui/resources -Igen/ui/strings '-I../../third_party/libc++/trunk/include' '-I../../third_party/libc++abi/trunk/include' -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-exceptions -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /b/build/slave/Linux_ASan_LSan_Builder/build/src/tools/clang/scripts/../../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -B/b/build/slave/Linux_ASan_LSan_Builder/build/src/third_party/binutils/Linux_x64/Release/bin -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -m64 -march=x86-64 -fno-omit-frame-pointer -gline-tables-only -fsanitize=address -fsanitize=leak -O2 -fdata-sections -ffunction-sections -fno-slp-vectorize -funwind-tables -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare -std=gnu++11 -nostdinc++  -c ../../ui/views/widget/desktop_aura/desktop_drag_drop_client_aurax11.cc -o obj/ui/views/widget/desktop_aura/views.desktop_drag_drop_client_aurax11.o
In file included from ../../ui/views/widget/desktop_aura/desktop_drag_drop_client_aurax11.cc:5:
../../ui/views/widget/desktop_aura/desktop_drag_drop_client_aurax11.h:166:8:error: no type named 'vector' in namespace 'std'
  std::vector< ::Atom> GetOfferedDragOperations();
  ~~~~~^
../../ui/views/widget/desktop_aura/desktop_drag_drop_client_aurax11.h:166:14:error: expected member name or ';' after declaration specifiers
  std::vector< ::Atom> GetOfferedDragOperations();
  ~~~~~~~~~~~^
../../ui/views/widget/desktop_aura/desktop_drag_drop_client_aurax11.cc:316:32:error: no member named 'GetOfferedDragOperations' in 'views::DesktopDragDropClientAuraX11'
    actions_ = source_client_->GetOfferedDragOperations();
               ~~~~~~~~~~~~~~  ^
../../ui/views/widget/desktop_aura/desktop_drag_drop_client_aurax11.cc:614:34:error: use of undeclared identifier 'GetOfferedDragOperations'
  std::vector< ::Atom> actions = GetOfferedDragOperations();
                                 ^
../../ui/views/widget/desktop_aura/desktop_drag_drop_client_aurax11.cc:924:52:error: out-of-line definition of 'GetOfferedDragOperations' does not match any declaration in 'views::DesktopDragDropClientAuraX11'
std::vector< ::Atom> DesktopDragDropClientAuraX11::GetOfferedDragOperations() {
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~


Original issue's description:
> Fix flakiness of DesktopDragDropClientAuraX11Tests
> 
> I suspect that the flakiness was caused by X11WholeScreenMoveLoop::RunMoveLoop()
> sometimes failing. This CL fixes this potential source of flakiness by using
> a stub move loop in tests.
> 
> BUG=396468
> TEST=None
> TBR=erg
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=287622

TBR=erg@chromium.org,pkotwicz@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=396468

Review URL: https://codereview.chromium.org/443773003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@287627 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 35f5421c0ebda7ab13426c9453bd7be40b262d2c