Fix C++11-illegal truncation per VS 2015
C++ 11 makes it illegal to do truncating conversions when initializing
aggregates such as structs. The VC++ 2015 builder reported this error:

device\usb\usb_device_handle_impl.cc(823): error C2397: conversion from
'int' to 'uint8_t' requires a narrowing conversion

On this code:

endpoint_map_[endpoint.address] = {interface_number,
                                   endpoint.transfer_type};

interface_number is an int, but EndpointMapValue::interface_number is a
uint8_t. Making consistent use of int seems like the best solution.

R=reillyg@chromium.org
BUG=527561

Review URL: https://codereview.chromium.org/1311483003

Cr-Commit-Position: refs/heads/master@{#347086}

Former-commit-id: 233fa64d514bd37db474246a851a5f4ccd0fc295