[Android] Fix x86 build after c71f754dab67 [formerly 1f6acfe7dd08].
../../content/common/sandbox_linux/android/sandbox_bpf_base_policy_android.cc:45:10:
  error: 'sandbox::bpf_dsl::BoolExpr content::{anonymous}::RestrictSocketArguments()'
  defined but not used [-Werror=unused-function]

BUG=663249,655300
TBR=rickyz@chromium.org

Review-Url: https://codereview.chromium.org/2483253002
Cr-Commit-Position: refs/heads/master@{#430621}

Former-commit-id: 6cf1cba773058a061075f2a05c06f7fa61d3143b