Revert "[Media Router] PresentationRequest cleanup round 1."
This reverts commit dd278d0ed424c403027d4a272fd4b228775bf8d2 [formerly 008d9944bd493e04153cd1812d52b6709d036d5d].

Reason for revert:

This seems to have broken the build on Chrome for Chrome OS.

../../chrome/browser/media/router/presentation_service_delegate_impl_unittest.cc:417:57: error: chosen constructor is explicit in copy-initialization
      {main_frame_process_id_, main_frame_routing_id_}, {}, frame_origin_);
                                                        ^~
../../build/linux/debian_jessie_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/debug/vector:79:7: note: explicit constructor declared here
      vector(const _Allocator& __a = _Allocator())
      ^
../../content/public/browser/presentation_request.h:23:48: note: passing argument to parameter 'presentation_urls' here
                      const std::vector<GURL>& presentation_urls,
                                               ^



Original change's description:
> [Media Router] PresentationRequest cleanup round 1.
> 
> Move PresentationRequest to content/browser and use it in
> PresentationServiceDelegate where applicable.
> - Replace GetMediaSources() method with helper function in c/b/m/r.
> - Replace Equals() method with a helper function in PSDImpl.
> - PresentationRequest is now a struct.
> 
> 
> Other things to consider after this patch:
> - Move PresentationRequest out of CPCR, maybe make
>   ShowMediaRouterDialogForPresentation take a PR and 2 callbacks?
> -- the callbacks can be wrapped in a struct internal to MRDC.
> - Remove the PR equality checking - we don't need this if we know
> the PresentationRequest has not been reset.
> - Support moves for PresentationRequest. Right now it's effective in
> only one place but further cleanups may find it useful.
> 
> 
> Bug: 664326, 708209
> Change-Id: I0ead3d0c2a8cc73849a6d007369e2ab13f1467d2
> Reviewed-on: https://chromium-review.googlesource.com/578528
> Reviewed-by: Avi Drissman <avi@chromium.org>
> Reviewed-by: mark a. foltz <mfoltz@chromium.org>
> Commit-Queue: Derek Cheng <imcheng@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#489064}

TBR=avi@chromium.org,mfoltz@chromium.org,imcheng@chromium.org

Change-Id: I5f4dde8982386104081caba7cbac91339e930129
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 664326, 708209
Reviewed-on: https://chromium-review.googlesource.com/583908
Reviewed-by: Fady Samuel <fsamuel@chromium.org>
Commit-Queue: Fady Samuel <fsamuel@chromium.org>
Cr-Commit-Position: refs/heads/master@{#489073}
Former-commit-id: 66d441e7c4fc2e6a41be8a10f6974d026388138e