Revert of Fail gracefully if no Chrome trace or insufficient power samples. (patchset #8 id:140001 of https://codereview.chromium.org/2371873002/ )
Reason for revert:
crbug.com/650306

Causing BattOr tests to fail with:
MapFunctionError: Cannot read property 'bounds' of undefined

Original issue's description:
> Fail gracefully if no Chrome trace or insufficient power samples.
>
> If there is no Chrome trace available or power samples do not cover
> the entire region, return no metrics rather than crashing or
> returning bogus metric values.
>
> BUG=catapult:#2867
>
> Committed: https://chromium.googlesource.com/external/github.com/catapult-project/catapult/+/991ccd046c5ad9a8afb9100d4d95a57fe2882ddb [formerly 5c9f7723faa3ba50ff48094ae5dd4d00cfaaad1a]

TBR=benjhayden@chromium.org,eakuefner@chromium.org,nednguyen@google.com,alexandermont@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=catapult:#2867

Review-Url: https://codereview.chromium.org/2376193005

Former-commit-id: 4a9b8db369bd30aa0d4b38461ac92d8acf9b1849