Revert "[ios] Create UI test for page info (site info)"
This reverts commit cd463a8a8c6f774d5578a017b7c8ead3faf74242 [formerly d3708f200f801c47e2eb8c18d8f6fa3c521b7faf].

Reason for revert: This is failing all over downstream:

PageInfoTestCase/testShowPageInfoAndDismissOnDeviceRotation:
../../ios/chrome/browser/ui/page_info/page_info_egtest.mm:45: error: -[PageInfoTestCase testShowPageInfoAndDismissOnDeviceRotation] : Exception: AssertionFailedException

It looks like when this fails, it leaves the simulator in the rotated state, and causes a bunch of other tests to fail too.

Link for example of failure: https://logs.chromium.org/logs/chrome/bb/internal.bling.main/ipad11-simulator-x64/9508/+/recipes/steps/ios_chrome_ui_egtests__iPad_Air_iOS_11.4__on_Mac/0/logs/PageInfoTestCase__x2f_testShowPageInfoAndDismissOnDeviceRotation/0

Original change's description:
> [ios] Create UI test for page info (site info)
> 
> This CL creates an UI integration test that tests that the
> page info view gets automatically dismissed on device rotation.
> 
> Change-Id: I02611cc2fab5a214b74af01d15cd8d12e19eff6e
> Reviewed-on: https://chromium-review.googlesource.com/c/1338561
> Commit-Queue: edchin <edchin@chromium.org>
> Reviewed-by: Gauthier Ambard <gambard@chromium.org>
> Reviewed-by: Rohit Rao <rohitrao@chromium.org>
> Reviewed-by: edchin <edchin@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#608844}

TBR=rohitrao@chromium.org,edchin@chromium.org,gambard@chromium.org

Change-Id: I383646fb5c9be8bf8bff4dd54d2dc9d46cf14a5a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/1341203
Reviewed-by: Justin Cohen <justincohen@chromium.org>
Commit-Queue: Justin Cohen <justincohen@chromium.org>
Cr-Commit-Position: refs/heads/master@{#609097}
Former-commit-id: e50b55afcbbdf62bc4103061131947a148fae710