Revert 281286 "Add gyp machinery to build with packed ARM relati..."
Broke Android compile:
FAILED: cd ../../net; python ../build/android/gyp/pack_arm_relocations.py "--enable-packing=0" "--stripped-libraries-dir=../out/Release/gen/stripped_libraries" "--packed-libraries-dir=../out/Release/net_unittests_apk/libs/armeabi-v7a" "--libraries-file=../out/Release/net_unittests_apk/native_libraries.json" "--stamp=../out/Release/net_unittests_apk/pack_arm_relocations.stamp"
Traceback (most recent call last):
  File "../build/android/gyp/pack_arm_relocations.py", line 108, in <module>
    sys.exit(main())
  File "../build/android/gyp/pack_arm_relocations.py", line 99, in main
    CopyArmLibraryUnchanged(library_path, output_path)
  File "../build/android/gyp/pack_arm_relocations.py", line 58, in CopyArmLibraryUnchanged
    shutil.copy(library_path, output_path)
  File "/usr/lib/python2.7/shutil.py", line 117, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: u'../out/Release/net_unittests_apk/libs/armeabi-v7a/libnet_unittests.so'
ninja: build stopped: subcommand failed.

> Add gyp machinery to build with packed ARM relative relocations.
> 
> Add gypi and python files to support packing ARM relative relocations
> during the build process.
> 
> Define a use_relocation_packer gyp variable to turn ARM relocation
> packing on and off (currently set to 0).
> 
> BUG=385553
> 
> Review URL: https://codereview.chromium.org/358863002

TBR=simonb@chromium.org

Review URL: https://codereview.chromium.org/370633002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@281303 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 9c87bca9664c4912bcce5eec031c11b089e4dc91