Modifications to skpicture_printer
* Changed the output directory option to '-s' and '--skp-outdir' because this was broken, running run_multipage_benchmarks with skpicture_printer resulted in the following error: 
optparse.OptionConflictError: option -o/--outdir: conflicting option string(s): -o 

* Added additional browser options due on recent changes in Skia/Chromium code base.

Review URL: https://chromiumcodereview.appspot.com/15665003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@202895 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: a1b5ca87c89db9adcb46cbe5b07a4ebfd7f4caea