Revert "[subresource_filter] Move test-only JNI calls out of binary"
This reverts commit e2b895eff8d049816e5b32c04c76f8477aedf912 [formerly 39b4e33b85eda61eca33e85a14f46b6955e0716c].

Reason for revert:
https://ci.chromium.org/buildbot/chromium/Android/84236[32116/66287]

In file included from gen/services/network/public/mojom/network_service.mojom-shared.h:23:
gen/services/network/public/mojom/network_service.mojom-shared-internal.h:26:10: fatal error: 'services/network/public/mojom/websocket.mojom-shared-internal.h' file not found
#include "services/network/public/mojom/websocket.mojom-shared-internal.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original change's description:
> [subresource_filter] Move test-only JNI calls out of binary
> 
> Before, the JNI shim called into native code that was compiled into
> Chrome proper.
> 
> Now, due to r517541 there is a better way to do this by including the
> JNI code in libchromefortest.
> 
> Bug: None
> Change-Id: I9f34f5105366b927d6dd6676d97a9da6d2540385
> Reviewed-on: https://chromium-review.googlesource.com/997877
> Commit-Queue: Charlie Harrison <csharrison@chromium.org>
> Reviewed-by: Yaron Friedman <yfriedman@chromium.org>
> Reviewed-by: John Budorick <jbudorick@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#551131}

TBR=yfriedman@chromium.org,csharrison@chromium.org,jbudorick@chromium.org

Change-Id: If96fd947654bd36763943de4302f5a820a467f22
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: None
Reviewed-on: https://chromium-review.googlesource.com/1013344
Reviewed-by: Avi Drissman <avi@chromium.org>
Commit-Queue: Avi Drissman <avi@chromium.org>
Cr-Commit-Position: refs/heads/master@{#551143}
Former-commit-id: 35fa6fe4568290b0c90ed047924ba390f4bf3d12