Revert "Implement ReadableStreamNative::PipeTo"
This reverts commit 050e6fedf9135db2800f1369e9aff74f23924001 [formerly cb0d298d9daf972764b7dfd61b53bb2f2d4d6a97].

Reason for revert: compilation error
https://ci.chromium.org/p/chromium/builders/ci/linux-rel/22483

In file included from ../../third_party/dawn/src/tests/unittests/validation/DynamicStateCommandValidationTests.cpp:15:
../../third_party/dawn/src/tests/unittests/validation/ValidationTest.h:20:10: fatal error: 'dawn/dawncpp_traits.h' file not found
#include "dawn/dawncpp_traits.h"
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Since "dawncpp_traits.h" is generated file, it seems dependency description may miss something.

Original change's description:
> Implement ReadableStreamNative::PipeTo
> 
> Bug: 902633
> Change-Id: Iba34012af3de4037103e9df647c0971b54b77e02
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1531938
> Reviewed-by: Yutaka Hirano <yhirano@chromium.org>
> Commit-Queue: Adam Rice <ricea@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#646681}

TBR=ricea@chromium.org,yhirano@chromium.org

Change-Id: Ic9a390aa9372c4fab6c44c1bf38e69c9e6a7d4ac
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 902633
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1547625
Reviewed-by: Yoshifumi Inoue <yosin@chromium.org>
Commit-Queue: Yoshifumi Inoue <yosin@chromium.org>
Cr-Commit-Position: refs/heads/master@{#646685}
Former-commit-id: 816c6e5bd078aad9c393d736920c2b8f128d18e0