Disable NEON support on ARMv6 build targets.
ARMv6 does not support NEON. Despite this, inside a BUILD.gn
"if (arm_use_neon)" will be entered for builds targeting ARMv6.

This means any build that perhaps includes different files for NEON builds will
work incorrectly for ARMv6 targets.

As an example, Clang deliberately errors when attempting to use NEON intrinsics
when targeting ARMv6:
/b/build/slave/Android_Cronet_ARMv6_Builder/build/src/third_party/llvm-build/Release+Asserts/lib/clang/6.0.0/include/arm_neon.h:28:2:
error: "NEON support not enabled"
This probably happens in GCC as well but I haven't confirmed that. Either way,
the build should correctly set target features.

BUG=759993

Change-Id: I0b099823604d25fae20c80a72f7fca28ab6b5121
Reviewed-on: https://chromium-review.googlesource.com/639931
Reviewed-by: Adenilson Cavalcanti <cavalcantii@chromium.org>
Reviewed-by: Nico Weber <thakis@chromium.org>
Commit-Queue: Nico Weber <thakis@chromium.org>
Cr-Commit-Position: refs/heads/master@{#498220}
Former-commit-id: c53d7a2dff27ede9ab0643064e7764de606bcd0d