components: build fix about GenericChangeProcessor
clang complains it doesn't initialize const member, so this CL calls the
default constructor explicitly.

../../components/sync_driver/generic_change_processor.cc:157:38: error: default initialization of an object of const type 'const syncer::AttachmentIdList' (aka 'const vector<syncer::AttachmentId>') without a user-provided default constructor
      const syncer::AttachmentIdList empty_list_of_attachment_ids;
                                     ^
                                                                 {}
1 error generated.

Review URL: https://codereview.chromium.org/1579533002

Cr-Commit-Position: refs/heads/master@{#368627}

Former-commit-id: 8fe05e777f1b8be62cb2caeab59ccb292868eed6