Revert of Change base::Value::ListStorage to std::vector<base::Value> (patchset #14 id:260001 of https://codereview.chromium.org/2740143002/ )
Reason for revert:
Appears to have broken compile on ChromeOS. Needs a rebase?

FAILED: obj/extensions/browser/api/networking_private/networking_private/networking_private_chromeos.o
In file included from ../../extensions/browser/api/networking_private/networking_private_chromeos.cc:21:
In file included from ../../chromeos/network/network_connection_handler.h:18:
In file included from ../../chromeos/cert_loader.h:18:
In file included from ../../net/cert/cert_database.h:13:
../../net/cert/x509_certificate.h:22:10: fatal error: 'net/net_features.h' file not found
#include "net/net_features.h"
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.

https://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20ChromeOS/builds/32152

Original issue's description:
> Change base::Value::ListStorage to std::vector<base::Value>
>
> This CL is a first step to inlining base::ListValue. It is proposed to use an
> std::vector<base::Value> as the underlying ListStorage. This CL implements the
> change and updates the code accordingly.
>
> TBR=bajones@chromium.org, dbeam@chromium.org, stevenjb@chromium.org
> BUG=646113
> CQ_INCLUDE_TRYBOTS=master.tryserver.blink:linux_trusty_blink_rel
>
> Review-Url: https://codereview.chromium.org/2740143002
> Cr-Commit-Position: refs/heads/master@{#463618}
> Committed: https://chromium.googlesource.com/chromium/src/+/5bcc45d6ccb2af3ead7880d90b1b03c217999747 [formerly ebab0defaea3aed024283a64088ebc0cd352b47f]

TBR=brettw@chromium.org,rdevlin.cronin@chromium.org,flackr@chromium.org,skym@chromium.org,rsesek@chromium.org,bajones@chromium.org,dbeam@chromium.org,stevenjb@chromium.org,jdoerrie@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=646113

Review-Url: https://codereview.chromium.org/2816513002
Cr-Commit-Position: refs/heads/master@{#463630}

Former-commit-id: df600cdcab705df0e7a43823c1bca99924542cb4