Fully qualify all references to fileapi::FileSystemType
This avoids a name conflict between winnt.h's FileSystemType enumerator
value and Chromium's fileapi::FileSystemType enum type.  MSVC doesn't
care, but Clang diagnoses this with:
  error: must use 'enum' tag to refer to type 'FileSystemType' in this scope

I could use the enum tag to avoid this ambiguity, but it would be very
inconsistent with other Chromium code.  A full nested name specifier
seems better.

R=thakis@chromium.org,hans@chromium.org
TBR=kinuko@chromium.org
BUG=82385

Review URL: https://codereview.chromium.org/345673002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@278332 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 26e815d0eabbad22bf036dc237e898e2f500e937