Revert of aura: Fix a crash related to nested event-dispatch. (https://codereview.chromium.org/180973007/)
Reason for revert:
Broke Linux Clang (dbg):

http://build.chromium.org/p/chromium.linux/builders/Linux%20Clang%20%28dbg%29/builds/56926/steps/compile/logs/stdio

../../ui/aura/window_event_dispatcher_unittest.cc:1855:7:error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
      target_->GetDispatcher()->OnEventFromSource(&move);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~
../../ui/aura/window_event_dispatcher_unittest.cc:1925:3:error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
  dispatcher()->OnEventFromSource(&move);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~
2 errors generated.
ninja: build stopped: subcommand failed.

Original issue's description:
> aura: Fix a crash related to nested event-dispatch.
> 
> If events are being dispatched from a nested message-loop, and the target of the
> outer loop is hidden or moved to another dispatcher during dispatching events in
> the inner loop, then reset the target for the outer loop.
> 
> BUG=347012
> R=sky@chromium.org
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=254150

TBR=sky@chromium.org,sadrul@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=347012

Review URL: https://codereview.chromium.org/184733003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@254183 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 03436e5648f50f9e4e1f4ad1136e8b428e196094