Reland of Establish Mojo connection prior to constructing RendererCompositorFrameSink (patchset #1 id:1 of https://codereview.chromium.org/2902883002/ )
Reason for revert:
Shouldn't have been reverted.

Original issue's description:
> Revert of Establish Mojo connection prior to constructing RendererCompositorFrameSink (patchset #4 id:60001 of https://codereview.chromium.org/2899083002/ )
>
> Reason for revert:
> Compilation failure:
>
> c:\b\c\b\win_chrome\src\chrome\browser\ui\webui\settings\metrics_reporting_handler.cc(66): error C2065: 'DictionaryValue': undeclared identifier
> c:\b\c\b\win_chrome\src\chrome\browser\ui\webui\settings\metrics_reporting_handler.cc(66): error C2672: 'base::MakeUnique': no matching overloaded function found
> c:\b\c\b\win_chrome\src\chrome\browser\ui\webui\settings\metrics_reporting_handler.cc(66): error C2974: 'base::MakeUnique': invalid template argument for 'T', type expected
> c:\b\c\b\win_chrome\src\base\memory\ptr_util.h(69): note: see declaration of 'base::MakeUnique`
>
> in https://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Win/builds/18360
>
> Original issue's description:
> > Establish Mojo connection prior to constructing RendererCompositorFrameSink
> >
> > In order to better match the signature of ClientCompositorFrameSink's
> > constructor, it's better to establish a MojoCompositorFrameSink before
> > constructing a RendererCompositorFrameSink and then pass the interface
> > pointer to its constructor.
> >
> > Review-Url: https://codereview.chromium.org/2899083002
> > Cr-Commit-Position: refs/heads/master@{#474148}
> > Committed: https://chromium.googlesource.com/chromium/src/+/ac597dbaf9e854b4a000e883cd7c30c35846c96f [formerly 2f5f09f37f44b88d39917da4a8e096765300b936]
>
> TBR=fsamuel@chromium.org,piman@chromium.org,samans@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
>
> Review-Url: https://codereview.chromium.org/2902883002
> Cr-Commit-Position: refs/heads/master@{#474155}
> Committed: https://chromium.googlesource.com/chromium/src/+/0611ebf3d6bac67524b8b41e76cf107aee87bf01 [formerly 8e1228014277cc5d28b09db8546a93031879b6a7]

TBR=fsamuel@chromium.org,piman@chromium.org,yosin@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review-Url: https://codereview.chromium.org/2900293003
Cr-Commit-Position: refs/heads/master@{#474258}

Former-commit-id: a61ab21892d351e22b39b2a17c2b9948f6866525