Revert "Match Modern spec for spacing between tiles and other views."
This reverts commit 35b812c0a00989b22afb3f164c78165f88115d26 [formerly 8f6dd43d6c9f5b420e6cca59ecf829079acd5480].

Reason for revert: appears to be causing failure in org.chromium.chrome.browser.suggestions.TileGroupUnitTest#testRenderTileViewReplacing

java.lang.IllegalArgumentException: ChromeHome
	at org.chromium.chrome.browser.ChromeFeatureList.isEnabled(ChromeFeatureList.java:67)
	at org.chromium.chrome.browser.util.FeatureUtilities.isChromeHomeEnabled(FeatureUtilities.java:278)
	at org.chromium.chrome.browser.util.FeatureUtilities.isChromeHomeModernEnabled(FeatureUtilities.java:325)
	at org.chromium.chrome.browser.suggestions.TileGridLayout.<init>(TileGridLayout.java:48)
	at org.chromium.chrome.browser.suggestions.TileGroupUnitTest.setupView(TileGroupUnitTest.java:391)
	at org.chromium.chrome.browser.suggestions.TileGroupUnitTest.testRenderTileViewReplacing(TileGroupUnitTest.java:318)

https://uberchromegw.corp.google.com/i/chromium.linux/builders/Android%20Tests/builds/45361

Original change's description:
> Match Modern spec for spacing between tiles and other views.
> 
> Bug: 760185
> Change-Id: I6a16b5a7542056998201bb27189bf95658521b9e
> Reviewed-on: https://chromium-review.googlesource.com/645855
> Reviewed-by: Nicolas Dossou-Gbété <dgn@chromium.org>
> Commit-Queue: Michael van Ouwerkerk <mvanouwerkerk@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#498925}

TBR=mvanouwerkerk@chromium.org,dgn@chromium.org

Change-Id: I0478e9911d20619457acc635a15945c700d9a469
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 760185
Reviewed-on: https://chromium-review.googlesource.com/646581
Reviewed-by: Mike Wittman <wittman@chromium.org>
Commit-Queue: Mike Wittman <wittman@chromium.org>
Cr-Commit-Position: refs/heads/master@{#498984}
Former-commit-id: 78329a28eceedae5bba7307208a2ef08219c84ef