alerts: catch all oauth2client.client exceptions too
Just hit a rare crash on the signers where the server flaked:
Traceback (most recent call last):
  File "/cros/signer/signing_poller.py", line 1516, in StartSigner
    poller = SetupSigner(argv)
  ...more signer-specific frames...
  File "/cros/signer/chromite/lib/alerts.py", line 330, in SendEmailLog
    attachment=attachment, extra_fields=extra_fields)
  File "/cros/signer/chromite/lib/alerts.py", line 291, in SendEmail
    server.Send(msg)
  File "/cros/signer/chromite/lib/alerts.py", line 175, in Send
    service.users().messages().send(userId='me', body=payload).execute()
  File "/cros/signer/chromite/third_party/oauth2client/util.py", line 140, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/cros/signer/chromite/third_party/googleapiclient/http.py", line 833, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/cros/signer/chromite/third_party/googleapiclient/http.py", line 160, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/cros/signer/chromite/third_party/oauth2client/client.py", line 572, in new_request
    self._refresh(request_orig)
  File "/cros/signer/chromite/third_party/oauth2client/client.py", line 854, in _refresh
    self._do_refresh_request(http_request)
  File "/cros/signer/chromite/third_party/oauth2client/client.py", line 907, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
HttpAccessTokenRefreshError: Invalid response 502.

Since there's nothing we can really do with any of these exceptions,
swallow them all, log a warning, and return False.

BUG=None
TEST=unittests pass

Change-Id: I72756c3110a1f1fb163d24ed712bc1ef6e35c290
Reviewed-on: https://chromium-review.googlesource.com/679894
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Dan Shi <dshi@google.com>