Revert "viz: Move CompositorFrame's mojom from cc to services/viz"
This reverts commit 0546f5b30710300c7a50b19af88a143a78c5cea3 [formerly 7839147c2ef53597debd48b0f75f2030c49caf3b].

Reason for revert: Culprit CL for build breakage:

Error:
../../cc/ipc/cc_serialization_perftest.cc:11:10: fatal error: 'cc/ipc/compositor_frame.mojom.h' file not found
#include "cc/ipc/compositor_frame.mojom.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original change's description:
> viz: Move CompositorFrame's mojom from cc to services/viz
> 
> TBR=sky@chromium.org
> Bug=722935
> 
> Cq-Include-Trybots: master.tryserver.blink:linux_trusty_blink_rel
> Change-Id: I1fe2b3ab68a4bce06869ce3ea92ffd1b76dcd289
> Reviewed-on: https://chromium-review.googlesource.com/601190
> Commit-Queue: Saman Sami <samans@chromium.org>
> Reviewed-by: Saman Sami <samans@chromium.org>
> Reviewed-by: Tom Sepez <tsepez@chromium.org>
> Reviewed-by: Robert Kroeger <rjkroege@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#492170}

TBR=rjkroege@chromium.org,sky@chromium.org,tsepez@chromium.org,samans@chromium.org

Change-Id: I3466865c523f900055bef8440d32016aead83253
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Cq-Include-Trybots: master.tryserver.blink:linux_trusty_blink_rel
Reviewed-on: https://chromium-review.googlesource.com/602742
Reviewed-by: Joe Downing <joedow@chromium.org>
Commit-Queue: Joe Downing <joedow@chromium.org>
Cr-Commit-Position: refs/heads/master@{#492177}
Former-commit-id: f4e59f15f8dadd5ef22278f8e05ff5c62b3af3bd