Revert "Revert "Initialize LayoutTableCell.is_spanning_collapsed_row_ to avoid MSAN error""
This reverts commit 1463790e0bace3e573f947367a46e86eb04ed760 [formerly 7a948ec8379c9d294676044731a94288042bbd08].

Reason for revert: This fix was reverted because the CL it fixes was reverted. The original CL has been relanded and now the fix should work.


Original change's description:
> Revert "Initialize LayoutTableCell.is_spanning_collapsed_row_ to avoid MSAN error"
> 
> This reverts commit cf3f5652899ad5be079994fa536b9618764b115f [formerly b25f768cdadae5ad6462136dac42a411fa4be103].
> 
> Reason for revert: Caused compile error.
> 
> https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium.webkit%2FWebKit_Mac_Builder__dbg_%2F209280%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout
> 
> ../../third_party/WebKit/Source/core/layout/LayoutTableCell.cpp:63:7: error: member initializer 'is_spanning_collapsed_row_' does not name a non-static data member or base class
>       is_spanning_collapsed_row_(false),
>       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> 
> Original change's description:
> > Initialize LayoutTableCell.is_spanning_collapsed_row_ to avoid MSAN error
> > 
> > TBR: joysyu@google.com
> > Bug: 751407
> > Change-Id: I3bb805d6f6c2a555925ce3ccf514e1e4b2d8df0a
> > Reviewed-on: https://chromium-review.googlesource.com/597031
> > Reviewed-by: Tsuyoshi Horo <horo@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#491295}
> 
> TBR=horo@chromium.org,joysyu@google.com
> 
> Change-Id: Ice425494d4c1de47a48497636401616d9fe6cc89
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 751407
> Reviewed-on: https://chromium-review.googlesource.com/597093
> Reviewed-by: Tsuyoshi Horo <horo@chromium.org>
> Commit-Queue: Tsuyoshi Horo <horo@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#491318}

TBR=horo@chromium.org,joysyu@google.com

Change-Id: Ic130312825f08f443d5f3bf5fbddac556607d4aa
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 751407
Reviewed-on: https://chromium-review.googlesource.com/597707
Reviewed-by: Guido Urdaneta <guidou@chromium.org>
Commit-Queue: Guido Urdaneta <guidou@chromium.org>
Cr-Commit-Position: refs/heads/master@{#491323}
Former-commit-id: 0d3a6f1cd01ac1375f275623e48e1c890532ad2c