BUILD FIX: Platform.h:1212:22: error: '__MAC_OS_X_VERSION_MIN_REQUIRED' is not defined, evaluates to 0 [-Werror,-Wundef]
This fixes the following build error introduced in r140366 for
Bug 107098:

    Platform.h:1212:22: error: '__MAC_OS_X_VERSION_MIN_REQUIRED' is not defined, evaluates to 0 [-Werror,-Wundef]
    #if PLATFORM(MAC) && __MAC_OS_X_VERSION_MIN_REQUIRED >= 1080 && !PLATFORM(IOS)
                         ^
    1 error generated.

* wtf/Platform.h: Check !PLATFORM(IOS) first so that iOS builds
do not try to evaluate __MAC_OS_X_VERSION_MIN_REQUIRED.

git-svn-id: svn://svn.chromium.org/blink/trunk@140988 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: 0368252e78619dfb2682490a0ffb51036deb42bb