Preemptively prevent naming conflicts between blink and content.
This CL prevents a naming conflict that would happen after the Great Blink
rename between:
1. Methods of content::UserMediaClientImplUnderTest class (i.e. RequestUserMedia)
2. Methods of blink::WebUserMediaClient class (i.e. requestUserMedia)

The naming conflicts are prevented by:
- Removing/inlining content::UserMediaClientImplUnderTest methods that are only
  called from a single callsite: SetMediaDeviceChangeObserver and
  RemoveMediaDeviceChangeObserver
- Adding a ForTest suffix to 3 other methods of
  content::UserMediaClientImplUnderTest: RequestUserMediaForTest (2 overloads)
  and RequestMediaDevices.

Without this CL, after the Great Blink Rename we would get build errors like below:

  ../../content/renderer/media/user_media_client_impl_unittest.cc:169:8: error: 'content::UserMediaClientImplUnderTest::RequestMediaDevices' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void RequestMediaDevices() {
	 ^
  ../../content/renderer/media/user_media_client_impl.h:66:8: note: hidden overloaded virtual function 'content::UserMediaClientImpl::RequestMediaDevices' declared here: different number of parameters (1 vs 0)
    void RequestMediaDevices(
	 ^
  ../../content/renderer/media/user_media_client_impl_unittest.cc:175:8: error: 'content::UserMediaClientImplUnderTest::SetMediaDeviceChangeObserver' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void SetMediaDeviceChangeObserver() {
	 ^
  ../../content/renderer/media/user_media_client_impl.h:68:8: note: hidden overloaded virtual function 'content::UserMediaClientImpl::SetMediaDeviceChangeObserver' declared here: different number of parameters (1 vs 0)
    void SetMediaDeviceChangeObserver(
	 ^

BUG=582312

Review-Url: https://codereview.chromium.org/2673523002
Cr-Commit-Position: refs/heads/master@{#447672}

Former-commit-id: abf006eeadeedad6d1cdb777c584e94b43945fdb