Revert "Cleanup XR usage of EmbeddedTestServer"
This reverts commit 0d9197f2adff0a66153727ba982b17fcca00d4f3 [formerly a8f4b1704bef97e31836dae3ab4601387a521aaa].

Reason for revert: Suspect this CL caused a failure of org.chromium.chrome.browser.customtabs.CustomTabActivityTest#testCloseButtonBehaviourWithDynamicModule 

https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/Android%20CFI/3725

org.junit.ComparisonFailure: expected:<http[s://www.google.com/search?q=cat]> but was:<http[://127.0.0.1:37221/chrome/test/data/android/test.html]>
  	at org.junit.Assert.assertEquals(Assert.java:115)
  	at org.junit.Assert.assertEquals(Assert.java:144)
  	at org.chromium.chrome.browser.customtabs.CustomTabActivityTest.testCloseButtonBehaviourWithDynamicModule(CustomTabActivityTest.java:1195)


Original change's description:
> Cleanup XR usage of EmbeddedTestServer
> 
> Cleans up manual usage of EmbeddedTestServer in XR tests, which was both
> adding a lot of duplicate code and had the potential to fail to clean up
> the server if the test failed, which could then affect other tests.
> 
> This is achieved by making EmbeddedTestServerRule lazy and applying it
> to all ChromeActivityTestRules, not just WebappActivityTestRule.
> 
> Bug: 901923
> Change-Id: I431dac3ce2488a1a5762a1ab1f5ec68aea16c9f5
> Reviewed-on: https://chromium-review.googlesource.com/c/1320024
> Commit-Queue: Brian Sheedy <bsheedy@chromium.org>
> Reviewed-by: Tommy Nyquist <nyquist@chromium.org>
> Reviewed-by: Paul Jensen <pauljensen@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#609556}

TBR=nyquist@chromium.org,pauljensen@chromium.org,bsheedy@chromium.org

Change-Id: I676439292a0f90ee353dadef415437415d82bba4
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 901923
Reviewed-on: https://chromium-review.googlesource.com/c/1343265
Reviewed-by: Maxim Kolosovskiy <kolos@chromium.org>
Commit-Queue: Maxim Kolosovskiy <kolos@chromium.org>
Cr-Commit-Position: refs/heads/master@{#609665}
Former-commit-id: 0b49f5dccde73328df40f843666ab4a0b8608e3a