Replace required quotes in check_insn
clang fails to notice inline asm support without quoting the insn
in the source, failing with:

check_insn armv5te qadd r0, r0, r0
.../test.c:1:34: error: expected string literal in 'asm'
void foo(void){ __asm__ volatile(qadd r0, r0, r0); }

The correct code, produced by this CL, is:

void foo(void){ __asm__ volatile("qadd r0, r0, r0"); }

Bug: 840959
Change-Id: Ibed36978d0b141c7d3369956ab2cf78c0a8c2a88
Reviewed-on: https://chromium-review.googlesource.com/1050727
Reviewed-by: Matthew Wolenetz <wolenetz@chromium.org>