cros_mark_as_stable: check for stable 9999 ebuilds
We do not want 9999 ebuilds to be marked as stable, so make sure to
check for & error out explicitly.  Otherwise, if we add a new stable
9999 ebuild, we get the confusing error:

	ERROR: Missing 9999 ebuild in .../chromiumos-overlay/media-libs/glmark2

This makes no sense because there is a 9999 ebuild in there, but it
was marked as stable.

BUG=None
TEST=`./portage_utilities_unittest.py` passes
TEST=`./cros_mark_as_stable_unittest.py` passes
TEST=multi step test:
	- add 9999 ebuild with stable KEYWORDS
	- run `cros-cbuildbot arm-tegra2-paladin`
	- see new error message

Change-Id: Ibb536ce65eaeb6364ea6c9b42f5402655bca7d05
Reviewed-on: https://gerrit.chromium.org/gerrit/19787
Reviewed-by: David James <davidjames@chromium.org>
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>