Suppress traceback spam around real error messages.
Right now, if an exception is thrown in a subprocess, we get a lot of
traceback spam. If a real error happens, we should print that exception,
but there's no need to print the whole stack of BackgroundExceptions.

Example spam:

Traceback (most recent call last):
  File ".../chromite/buildbot/cbuildbot_background.py", line 97, in run
    step()
  File ".../chromite/buildbot/cbuildbot_background.py", line 205, in _TaskRunner
    raise BackgroundException('\n' + ''.join(tracebacks))
BackgroundException:

Example actual exception:

Traceback (most recent call last):
  File ".../chromite/buildbot/cbuildbot_background.py", line 195, in _TaskRunner
    task(*x)
  File ".../chromite/scripts/cros_list_buildbot_crashes.py", line 99, in _ProcessCrashListForBot
    for line in self._ListCrashesForBot(bot_id, build_config):
  File ".../chromite/scripts/cros_list_buildbot_crashes.py", line 87, in _ListCrashesForBot
    print_cmd=False)
  File ".../chromite/lib/cros_build_lib.py", line 476, in RunCommand
    raise RunCommandError(str(e), cmd, None)
RunCommandError: ('[Errno 2] No such file or directory', ['gsutil', 'ls', 'gs://chromeos-image-archive/x86-zgb-release/R19-*.dmp.txt'], None)

This change removes the spam but leaves the actual exception.

BUG=chromium-os:27567
TEST=Ran example script which throws exception.

Change-Id: I3eb3c3039b152e48708265f36599243c78716e66
Reviewed-on: https://gerrit.chromium.org/gerrit/17671
Reviewed-by: Brian Harring <ferringb@chromium.org>
Commit-Ready: David James <davidjames@chromium.org>
Tested-by: David James <davidjames@chromium.org>