Revert "[StartSurface] Implement explore surface with feeds"
This reverts commit 67b1aa8cd45961a205c5a2d502e2e4e370b3f5f7 [formerly a076c4e21fcded5d2bc85622b17db777a71664e2].

Reason for revert:
Compile failure List of errors:
../../chrome/android/feed/core/java/src/org/chromium/chrome/browser/feed/FeedNewTabPage.java:147: error: cannot find symbol

Original change's description:
> [StartSurface] Implement explore surface with feeds
> 
> Screenshots:
> https://drive.google.com/file/d/14ssIg6-tvLU_yAa8RTZEPHNsvbfGYgTa/view?usp=sharing
> 
> This CL split the original FeedNewTabPage, FeedNewTabPageMediator and StreamLifecycleManager
> into multiple classes, but we do not expect visible changes on FeedNewTabPage.
> 
> This CL also fixed the dummy FeedNewTabPage which was broken by
> https://chromium-review.googlesource.com/c/chromium/src/+/1709731
> 
> Bug: 982018
> Change-Id: I933cb01789d5eda8a196de00e4bf279bb7d6d785
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1715410
> Reviewed-by: David Trainor <dtrainor@chromium.org>
> Reviewed-by: Sky Malice <skym@chromium.org>
> Commit-Queue: David Trainor <dtrainor@chromium.org>
> Commit-Queue: Ganggui Tang <gogerald@chromium.org>
> Auto-Submit: Ganggui Tang <gogerald@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#681412}

TBR=dtrainor@chromium.org,yusufo@chromium.org,gogerald@chromium.org,skym@chromium.org

Change-Id: I6af1d483fc1b912d1b60d2ba9b7280125c65b410
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 982018
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1721000
Reviewed-by: Natalie Chouinard <chouinard@chromium.org>
Commit-Queue: Natalie Chouinard <chouinard@chromium.org>
Cr-Commit-Position: refs/heads/master@{#681427}

Former-commit-id: fe13c74942c6d5bec64ac764b559ed5dace82f7e