Revert of mash: Convert TrayBackgroundView to wm common types (patchset #4 id:60001 of https://codereview.chromium.org/2091933002/ )
Reason for revert:
Causing compile errors
- https://build.chromium.org/p/chromium/builders/Win/builds/44650

FAILED: obj/ash/ash/web_notification_tray.obj
ninja -t msvc -e environment.x86 -- C:\b\build\slave\cache\cipd\goma/gomacc.exe "C:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/ash/ash/web_notification_tray.obj.rsp /c ../../ash/system/web_notification/web_notification_tray.cc /Foobj/ash/ash/web_notification_tray.obj /Fd"obj/ash/ash_cc.pdb"
c:\b\build\slave\win\build\src\ash\system\web_notification\web_notification_tray.cc(510): error C3861: 'status_area_widget': identifier not found
c:\b\build\slave\win\build\src\ash\system\web_notification\web_notification_tray.cc(510): error C2227: left of '->system_tray' must point to class/struct/union/generic type
c:\b\build\slave\win\build\src\ash\system\web_notification\web_notification_tray.cc(510): note: type is 'unknown-type'
c:\b\build\slave\win\build\src\ash\system\web_notification\web_notification_tray.cc(510): error C2227: left of '->SetNextFocusableView' must point to class/struct/union/generic type

Original issue's description:
> mash: Convert TrayBackgroundView to wm common types
>
> Also convert StatusAreaWidget usage to WmShelf. This is closer to the long-
> term pattern we want, where StatusAreaWidget is accessed via wm types.
>
> * Eliminate the TrayBackgroundView::status_area_widget() accessors
> * Cache a copy of StatusAreaWidget* in subclasses where needed
>
> Move the following interdependent files:
> move_source_file.py ash/system/tray/tray_background_view.* ash/common/system/tray/
> move_source_file.py ash/system/tray/tray_bubble_wrapper.* ash/common/system/tray/
> move_source_file.py ash/system/tray/tray_event_filter.* ash/common/system/tray/
> move_source_file.py ash/system/tray/system_tray_bubble.* ash/common/system/tray/
>
> BUG=619636
> TEST=ash_unittests
> TBR=stevenjb@chromium.org for 1 line rename in c/b/ui/chromeos/
>
> Committed: https://crrev.com/8178a8c975788551d01cb2d8d869a2275cd060ca [formerly f6f6340048f0ec9535c310d16dd515133fb04c50]
> Cr-Commit-Position: refs/heads/master@{#401769}

TBR=msw@chromium.org,stevenjb@chromium.org,jamescook@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=619636

Review-Url: https://codereview.chromium.org/2097733002
Cr-Commit-Position: refs/heads/master@{#401792}

Former-commit-id: 3c51f5db7293b1e6100d44e71497428cde6d520a