ozone: Fix embedded component build with enable_printing==0
PDF support is removed from skia without printing, but VectorPlatformDeviceSkia
inherits from SkPDFDevice. We need to remove VectorPlatformDeviceSkia as well.

This fixes the following undefined symbol errors.

lib/libskia.so: error: undefined reference to 'SkPDFDevice::~SkPDFDevice()'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::SkPDFDevice(SkTSize<int> const&, SkTSize<int> const&, SkMatrix const&)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::getDeviceCapabilities()'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::onAttachToCanvas(SkCanvas*)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::onDetachFromCanvas()'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::clear(unsigned int)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::drawPaint(SkDraw const&, SkPaint const&)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::drawPoints(SkDraw const&, SkCanvas::PointMode, unsigned long, SkPoint const*, SkPaint
 const&)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::drawRect(SkDraw const&, SkRect const&, SkPaint const&)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::drawRRect(SkDraw const&, SkRRect const&, SkPaint const&)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::drawPath(SkDraw const&, SkPath const&, SkPaint const&, SkMatrix const*, bool)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::drawBitmap(SkDraw const&, SkBitmap const&, SkMatrix const&, SkPaint const&)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::drawSprite(SkDraw const&, SkBitmap const&, int, int, SkPaint const&)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::drawBitmapRect(SkDraw const&, SkBitmap const&, SkRect const*, SkRect const&, SkPaint
const&, SkCanvas::DrawBitmapRectFlags)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::drawText(SkDraw const&, void const*, unsigned long, float, float, SkPaint const&)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::drawPosText(SkDraw const&, void const*, unsigned long, float const*, float, int, SkPa
int const&)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::drawTextOnPath(SkDraw const&, void const*, unsigned long, SkPath const&, SkMatrix con
st*, SkPaint const&)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::drawVertices(SkDraw const&, SkCanvas::VertexMode, int, SkPoint const*, SkPoint const*
, unsigned int const*, SkXfermode*, unsigned short const*, int, SkPaint const&)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::drawDevice(SkDraw const&, SkBaseDevice*, int, int, SkPaint const&)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::onReadPixels(SkBitmap const&, int, int, SkCanvas::Config8888)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::allowImageFilter(SkImageFilter*)'
lib/libskia.so: error: undefined reference to 'SkPDFDevice::onCreateCompatibleDevice(SkBitmap::Config, int, int, bool, SkBaseDevice::Usage)'

TEST=build with GYP_DEFINES="embedded==1 component=shared_library"

Review URL: https://codereview.chromium.org/78713006

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@236813 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 50385017473665890b30f0aec17d1bcd9e4bf9fa