execution_context: Include <bitset> for std::bitset
IWYU. This also fixes the libstdc++ build after commit 1e283e5c9 ("Make
OriginTrialContext and FeaturePolicyParser not depend on Document"):

In file included from ../../third_party/blink/renderer/core/css/css_selector.cc:35:
In file included from ../../third_party/blink/renderer/core/css/parser/css_parser_context.h:11:
../../third_party/blink/renderer/core/execution_context/execution_context.h:368:8: error: no template named 'bitset' in namespace 'std'
  std::bitset<static_cast<size_t>(mojom::FeaturePolicyFeature::kMaxValue) + 1>
  ~~~~~^

Bug: 957519
Change-Id: I7280794adc273c34e3ba636731204b5c1ec3b9ca
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1660863
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Reviewed-by: Dave Tapuska <dtapuska@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#669737}

Former-commit-id: 2bf7a9d7fff70a8bdc7cd5d1d7b3b19f0177e976