Fix a compilation issue when building with VS2013 and optimization set to "max".
For some reasons (I'm still trying to find them) those 2 DCHECKs make the link step to fail when building nacl64.exe (and maybe some other target) with VS2013 and optimization set to 'max'

Here's the error that I get:
[1537/6627] LINK_EMBED nacl64.exe
FAILED: D:\src\depot_tools\python276_bin\python.exe gyp-win-tool link-with-manifests environment.x64 True nacl64.exe "D:\src\depot_tools\python276_bin\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:nacl64.exe @nacl64
.exe.rsp" 1 mt.exe rc.exe "obj\chrome\chrome_nacl_win64.nacl64.exe.intermediate.manifest" obj\chrome\chrome_nacl_win64.nacl64.exe.generated.manifest ..\..\build\win\compatibility.manifest
LibDef: Total time = 0.015s
  OptRef: Total time = 0.000s
Generating code
d:\src\chrome\src\sandbox\win\src\sharedmem_ipc_client.cc(34) : fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 227)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information
INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\link.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
Final: Total time = 27.940s
Traceback (most recent call last):
  File "gyp-win-tool", line 293, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 70, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 158, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "D:\src\depot_tools\python276_bin\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)

This CL fix this, for the first dcheck it might be because we're comparing a LONG to a ChannelState (and the linker he's unhappy when looking for the conversion routine), but for the second one I have really no idea what's happening, all I know is that using DCHECK_LE instead of DCHECK shouldn't change anything here, and that it fix the build.


R=cpu@chromium.org
CC=scottmg@chromium.org

BUG=344980

Review URL: https://codereview.chromium.org/172853002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@252213 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 29bbcf4db6b9591d606b04eb4b3bafccb945179d