Revert "ui: Lower applist and shelf blur quality"
This reverts commit f414d035bce4091ca409ec489225fef0a1172799 [formerly 3856a7a9a32d02b0aaeb143728c26161ec4b54cb].

Reason for revert:
https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/chromeos-daisy-rel/35823
failed in compile:
FAILED: obj/ash/app_list/app_list/app_list_view.o 
...
-c ../../ash/app_list/views/app_list_view.cc -o obj/ash/app_list/app_list/app_list_view.o
../../ash/app_list/views/app_list_view.cc:513:43: error: no member named 'SetBackdropFilterQuality' in 'ui::Layer'
    app_list_background_shield_->layer()->SetBackdropFilterQuality(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
1 error generated.

Original change's description:
> ui: Lower applist and shelf blur quality
> 
> crrev.com/c/1300235 introduced the option to lower the quality of backdrop
> filters.
> 
> This CL lowers the quality of the backdrop blur one the shelf and the
> applist shield.
> 
> In this way the texture allocations needed to apply the filter by cc will
> be significantly smaller/faster and applying the filter itself will also
> be faster on the GPU.
> 
> Bug: 897369
> Change-Id: I57be9434c02b77b38315e0f998d23eda5d277e43
> Reviewed-on: https://chromium-review.googlesource.com/c/1306234
> Reviewed-by: Mitsuru Oshima <oshima@chromium.org>
> Commit-Queue: Daniele Castagna <dcastagna@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#603660}

TBR=oshima@chromium.org,dcastagna@chromium.org

Change-Id: Ie3fb29b6d37cd8b409ab5ac910b39a1c52531c6e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 897369
Reviewed-on: https://chromium-review.googlesource.com/c/1307058
Reviewed-by: Chase Phillips <cmp@chromium.org>
Commit-Queue: Chase Phillips <cmp@chromium.org>
Cr-Commit-Position: refs/heads/master@{#603746}
Former-commit-id: 0b75ca717c92673139447b965fd179450a5d55bd