Add public_deps for //ios/chrome/browser/tabs, //ios/chrome/browser/ui/tabs and //ios/web
//ios/chrome/browser/tabs details:
tab.h includes files from these targets, therefore they are part of //ios/chrome/browser/tabs public interface.

Example error:
In file included from ../../ios/chrome/browser/ui/stack_view/stack_view_egtest.mm:13:
In file included from ../../ios/chrome/browser/tabs/tab.h:17:
In file included from ../../ios/web/public/web_state/ui/crw_web_delegate.h:15:
In file included from ../../ios/web/public/ssl_status.h:12:
In file included from ../../net/cert/x509_certificate.h:25:
../../third_party/boringssl/src/include/openssl/base.h:71:10: fatal error: 'openssl/is_boringssl.h' file not found

//ios/chrome/browser/ui/tabs details:
tab_view.h includes headers from these targets, thus they are part of //ios/chrome/browser/ui/tabs public interface.

Example error:
In file included from ../../ios/chrome/browser/ui/tabs/tab_strip_egtest.mm:9:
In file included from ../../ios/chrome/browser/ui/tabs/tab_view.h:11:
In file included from ../../ios/chrome/browser/tabs/tab.h:17:
In file included from ../../ios/web/public/web_state/ui/crw_web_delegate.h:15:
In file included from ../../ios/web/public/ssl_status.h:12:
In file included from ../../net/cert/x509_certificate.h:25:
../../third_party/boringssl/src/include/openssl/base.h:71:10: fatal error: 'openssl/is_boringssl.h' file not found

//ios/web:web_arc details:
ssl_status.h includes headers from net, thus they are part of //ios/web:web_arc public interface.

Example error:
    In file included from ../../ios/chrome/browser/ui/payments/payment_request_manager.mm:31:
    In file included from ../../ios/web/public/ssl_status.h:12:
    In file included from ../../net/cert/x509_certificate.h:25:
    ../../third_party/boringssl/src/include/openssl/base.h:71:10: fatal error: 'openssl/is_boringssl.h' file not found

BUG=none

Review-Url: https://codereview.chromium.org/2873203002
Cr-Commit-Position: refs/heads/master@{#471037}

Former-commit-id: 2791788c6454704a4d6f8f6a917a3017b20f966a