Revert "Only allocate the hyphen-appending buffer if we intend to use it."
This reverts commit 6bd592cd8c98e184d3c62be2f3c59cadfc67535a.

Fixes compile error for Win builder:

c:\b\build\slave\webkit-win-latest-dbg\build\src\third_party\webkit\source\core\rendering\inlinetextbox.cpp(1524) : error C2220: warning treated as error - no 'object' file generated
c:\b\build\slave\webkit-win-latest-dbg\build\src\third_party\webkit\source\core\rendering\inlinetextbox.cpp(1524) : warning C4018: '>=' : signed/unsigned mismatch

BUG=

Review URL: https://codereview.chromium.org/22715007

git-svn-id: svn://svn.chromium.org/blink/trunk@155851 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: 4bf13f03ceb6c24c4323030926de0e3dd21dbe31