Revert of Make the notification builder more XPC friendly (patchset #6 id:100001 of https://codereview.chromium.org/2053613002/ )
Reason for revert:
Broke compilation on Mac https://build.chromium.org/p/chromium/builders/Mac/builds/16903/steps/compile/logs/stdio

../../chrome/browser/ui/cocoa/notifications/notification_builder_mac.mm:11:10: fatal error: 'chrome/grit/generated_resources.h' file not found
#include "chrome/grit/generated_resources.h"

Original issue's description:
> Make the notification builder more XPC friendly
>
> Move it to ui/cocoa/notifications where the xpc service will eventually live.
> Make it a static library so it can be linked by both the app and the XPC.
> Make sure the build operation only uses information from the underlying
> dictionary.
>
> BUG=571056
>
> Committed: https://crrev.com/13ddcf8b7a1bdf4cdfb58342e98351e5204be197 [formerly aafb03bf0df164a2fb86db117ae6053e9578c437]
> Cr-Commit-Position: refs/heads/master@{#400672}

TBR=jochen@chromium.org,peter@chromium.org,rsesek@chromium.org,miguelg@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=571056

Review-Url: https://codereview.chromium.org/2080733002
Cr-Commit-Position: refs/heads/master@{#400679}

Former-commit-id: 9753d56a309ead6e186dc28dcd821f63c1c3e458