Revert 243714 "Update GPU feature tests to expect no GPU on Wind..."
Failing on main waterfall Vista Tests (1):

[ RUN      ] GpuFeatureTest.MultisamplingAllowed
[4884:2868:0108/183111:2787078:ERROR:desktop_root_window_host_win.cc(757)] NOT IMPLEMENTED
test\gpu\gpu_feature_browsertest.cc(305): error: Value of: GpuDataManager::GetInstance()->IsFeatureBlacklisted( gpu::GPU_FEATURE_TYPE_MULTISAMPLING)
  Actual: true
Expected: expect_blacklisted
Which is: false

> Update GPU feature tests to expect no GPU on Windows <=Vista
> 
> BUG=243476
> 
> Review URL: https://codereview.chromium.org/128893002

TBR=ccameron@chromium.org

Review URL: https://codereview.chromium.org/130693002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@243749 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 1b901f991e41b90ba95a3aeee8dac56d783d55cc