cros_chrome_sdk: Print a link to a board's builder when its SDK is missing.
This will be useful in failed LKGM update CLs so a gardener/sheriff can
copy-paste the link and go straight to the board's release builder.

Currently, missing SDK errors look like:
ERROR: cros chrome-sdk failed before completing.
ERROR: Cannot find SDK for u'amd64-generic-full' with version 12638.0.0.
ERROR: (Re-run with --debug for more details.)

With this patch, they now look like:
ERROR: cros chrome-sdk failed before completing.
ERROR: Cannot find SDK for amd64-generic-full with version 12638.0.0 from its builder: http://cros-goldeneye/chromeos/legoland/builderHistory?buildConfig=amd64-generic-full
ERROR: (Re-run with --debug for more details.)

BUG=chromium:1019838
TEST=unittest

Change-Id: Ie9b42b4f5c0709e1efea2bcd3a69e113915f2da0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/1893445
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Tested-by: Ben Pastene <bpastene@chromium.org>
Reviewed-by: Steven Bennetts <stevenjb@chromium.org>
Reviewed-by: Achuith Bhandarkar <achuith@chromium.org>