Revert 233840 "Add CreateRegionFromSkRegion and update DesktopRo..."
Caused compile error on chrome os builders
e.g. http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20%28x86%29/builds/17724

chromeos-chrome-33.0.1704.0_alpha-r1: ui/gfx/path_x11.cc: In function '_XRegion* gfx::CreateRegionFromSkRegion(const SkRegion&)':
chromeos-chrome-33.0.1704.0_alpha-r1: ui/gfx/path_x11.cc:20:18: error: narrowing conversion of '(& i.SkRegion::Iterator::rect())->SkIRect::x()' from 'int' to 'short int' inside { } is ill-formed in C++11 [-Werror=narrowing]
chromeos-chrome-33.0.1704.0_alpha-r1: ui/gfx/path_x11.cc:20:32: error: narrowing conversion of '(& i.SkRegion::Iterator::rect())->SkIRect::y()' from 'int' to 'short int' inside { } is ill-formed in C++11 [-Werror=narrowing]
chromeos-chrome-33.0.1704.0_alpha-r1: ui/gfx/path_x11.cc:20:50: error: narrowing conversion of '(& i.SkRegion::Iterator::rect())->SkIRect::width()' from 'int' to 'short unsigned int' inside { } is ill-formed in C++11 [-Werror=narrowing]
chromeos-chrome-33.0.1704.0_alpha-r1: ui/gfx/path_x11.cc:20:69: error: narrowing conversion of '(& i.SkRegion::Iterator::rect())->SkIRect::height()' from 'int' to 'short unsigned int' inside { } is ill-formed in C++11 [-Werror=narrowing]
chromeos-chrome-33.0.1704.0_alpha-r1: cc1plus: all warnings being treated as errors

> Add CreateRegionFromSkRegion and update DesktopRootWindowHostX11 to use it.
> 
> SkRegion can now be converted directly to an X11 Region, rather than via SkPath, thereby avoiding the lack of support for non-contiguous regions in the SkPath to Region conversion step.
> 
> This CL is deliberately a minimal fix, suitable for merging.
> 
> BUG=315236
> 
> Review URL: https://codereview.chromium.org/65463002

TBR=wez@chromium.org

Review URL: https://codereview.chromium.org/66533003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@233932 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 21c8f5b8e33e4e28f177abacb774cc1ba1ac137b