cbuildbot: disable yama kernel hardlink security checks
Yama will disallow hardlinking files that a user does not have write
access to.  This breaks the cros_setup_toolchains logic which creates
packages by hardlinking root owned files into a directory.

Otherise the builds fail like so:
Traceback (most recent call last):
  File "/home/chrome-bot/trunk/chromite/buildbot/cbuildbot_background.py", line 237, in _TaskRunner
    task(*x)
  File "/home/chrome-bot/trunk/chromite/scripts/cros_setup_toolchains.py", line 914, in CreatePackagableRoot
    _BuildInitialPackageRoot(output_dir, paths, elfs, ldpaths, root=root)
  File "/home/chrome-bot/trunk/chromite/scripts/cros_setup_toolchains.py", line 785, in _BuildInitialPackageRoot
    os.link(path, dst)
OSError: [Errno 1] Operation not permitted

BUG=chromium-os:36453
TEST=hand ran this func on a bot and it tried to set yama to 0 when it was enabled, and returned when it was disabled
TEST=`cbuildbot chromiumos-sdk` no longer errors out when run on our buildbots

Change-Id: Ifb2cc466b0e49b158e73f3a964d1a47c6be1c906
Reviewed-on: https://gerrit.chromium.org/gerrit/39160
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>