Revert "Move downloadResponseHandler to components/download"
This reverts commit 72f7e1df9f3ae9efa87dfc57156c21c39853072c [formerly 824bbddf005642cd9c6b9818ce57dd82905ca84d].

Reason for revert: reverting in hopes of making tree green. The linux x64 bot has been flakely failing. For example, https://logs.chromium.org/v/?s=chromium%2Fbb%2Fchromium%2FLinux_x64%2F59821%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout and 

FAILED: obj/components/download/internal/common/internal/download_response_handler.o 
/b/c/goma_client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/components/download/internal/common/internal/download_response_handler.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DCR_CLANG_REVISION=\"325667-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DCOMPONENTS_DOWNLOAD_IMPLEMENTATION -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_32 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -I../.. -Igen -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../third_party/boringssl/src/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -pthread -fcolor-diagnostics -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -fdebug-prefix-map=/b/c/b/linux_clobber/src/out/Release=. -no-canonical-prefixes -m64 -march=x86-64 -Wall -Werror -Wextra -Wimplicit-fallthrough -Wthread-safety -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -Wno-enum-compare-switch -Wno-null-pointer-arithmetic -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -isystem/b/c/b/linux_clobber/src/build/linux/debian_sid_amd64-sysroot/usr/include/glib-2.0 -isystem/b/c/b/linux_clobber/src/build/linux/debian_sid_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wno-header-guard -isystem/b/c/b/linux_clobber/src/build/linux/debian_sid_amd64-sysroot/usr/include/nss -isystem/b/c/b/linux_clobber/src/build/linux/debian_sid_amd64-sysroot/usr/include/nspr -std=gnu++14 -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include --sysroot=../../build/linux/debian_sid_amd64-sysroot -fvisibility-inlines-hidden -c ../../components/download/internal/common/download_response_handler.cc -o obj/components/download/internal/common/internal/download_response_handler.o
In file included from ../../components/download/internal/common/download_response_handler.cc:5:
../../components/download/public/common/download_response_handler.h:16:10: fatal error: 'services/network/public/mojom/url_loader.mojom.h' file not found
#include "services/network/public/mojom/url_loader.mojom.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original change's description:
> Move downloadResponseHandler to components/download
> 
> No major change in functionality, just moving the files
> 
> Bug: 803135
> Change-Id: I93737ed4539c1b3ddc25212814ef9b9c903ac882
> Reviewed-on: https://chromium-review.googlesource.com/944545
> Reviewed-by: Helen Li <xunjieli@chromium.org>
> Reviewed-by: David Trainor <dtrainor@chromium.org>
> Reviewed-by: Bo <boliu@chromium.org>
> Commit-Queue: Min Qin <qinmin@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#540736}

TBR=boliu@chromium.org,dtrainor@chromium.org,qinmin@chromium.org,xunjieli@chromium.org

Change-Id: I1863660ebd431022abe2bf919ab38925fead91af
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 803135
Reviewed-on: https://chromium-review.googlesource.com/947983
Reviewed-by: Scott Violet <sky@chromium.org>
Commit-Queue: Scott Violet <sky@chromium.org>
Cr-Commit-Position: refs/heads/master@{#540756}
Former-commit-id: 73899cc3563736ac15f97dab1aeebe8179f936eb