Avoid unreachable code warning on Windows
Attempt to avoid

FAILED: ninja -t msvc -e environment.x86 -- C:\b\build\goma/gomacc "C:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\components\history\content\browser\history_content_browser.download_constants_utils.obj.rsp /c ..\..\components\history\content\browser\download_constants_utils.cc /Foobj\components\history\content\browser\history_content_browser.download_constants_utils.obj /Fdobj\components\history_content_browser.cc.pdb
c:\b\build\slave\win\build\src\components\history\content\browser\download_constants_utils.cc(105) :error C2220: warning treated as error - no 'object' file generated
c:\b\build\slave\win\build\src\components\history\content\browser\download_constants_utils.cc(105) : warning C4702: unreachable code
c:\b\build\slave\win\build\src\components\history\content\browser\download_constants_utils.cc(106) : warning C4702: unreachable code

Hopefully this doesn't cause warnings on other platforms?

TBR=sdefresne@chromium.org,erg@chromium.org,mark@chromium.org

Review URL: https://codereview.chromium.org/848713002

Cr-Commit-Position: refs/heads/master@{#311059}

Former-commit-id: b0499c6bea41c2f0bdc07600ca44a98155e08495