[GN] Only define libvpx_intrinsics_* target if they are used.
When targetting iOS, the libvpx_intrinsics_* targets ends up with an
empty sources property which causes libtool too fail with the error:

  error: libtool: no files specified
  Usage: libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
  Usage: libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]

Only define the targets on platform that use them (i.e. use the same
check for defining the target and adding the dependency).

BUG=webrtc:5586

Review-Url: https://codereview.chromium.org/1993453003
Cr-Commit-Position: refs/heads/master@{#394465}

Former-commit-id: 02743854d68b65334fa29e7ddd953f7ffe19efaf