Fix WeakPtr pretty-printing
As of [1], is_valid_ is no longer a member of base::WeakReference,
so the pretty- printer was broken like this:
  Traceback (most recent call last):
    File "/usr/local/google/home/thomasanderson/dev/chromium_2/src/tools/gdb/gdb_chrome.py", line 128, in to_string
      return '%s%s' % (self.typename, typed_ptr(self.ptr()))
    File "/usr/local/google/home/thomasanderson/dev/chromium_2/src/tools/gdb/gdb_chrome.py", line 166, in ptr
      if flag and flag['is_valid_']:
  gdb.error: There is no member or method named is_valid_.
The fix is to call IsValid() instead, which also does the flag_ check.

[1] https://chromium.googlesource.com/chromium/src/+/45b2fac3456670afd0ec7508043571ec57a244b7 [formerly ff1eab6792bc012492f1ebcb1f042c520fe2d838]

BUG=None
R=thakis

Change-Id: Ib1a433246f7a030a3cfd744764c83c46b8cdb0d2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1690721
Commit-Queue: Thomas Anderson <thomasanderson@chromium.org>
Auto-Submit: Thomas Anderson <thomasanderson@chromium.org>
Reviewed-by: Nico Weber <thakis@chromium.org>
Cr-Commit-Position: refs/heads/master@{#675358}

Former-commit-id: 2b6022954b9fb600f15e08002a148187f4f986da