Revert "Enable WebNavigationApiTest.UserAction"
This reverts commit 6a3b5c5ebf4cd2c1ee57cf07c73862d4111120dd [formerly 2c3ec3ced96f6050c1bbcc0c4a8b9ebc12917a7f].

Reason for revert: still failing (https://build.chromium.org/p/chromium.win/builders/Win%207%20Tests%20x64%20%281%29/builds/27201)

[ RUN      ] WebNavigationApiTest.UserAction
[5936:1628:0804/040823.764:WARNING:chrome_browser_main_win.cc(483)] Command line too long for RegisterApplicationRestart:  --brave-new-test-launcher --cfi-diag=0 --gtest_also_run_disabled_tests --gtest_filter=WebNavigationApiTest.UserAction --single_process --test-launcher-bot-mode --test-launcher-summary-output="e:\b\s\w\iou7dp23\output.json" --user-data-dir="C:\Users\CHROME~2\AppData\Local\Temp\scoped_dir4492_8435\d4492_12222" --disable-offline-auto-reload --disable-renderer-backgrounding --no-first-run --no-default-browser-check --enable-logging=stderr --safebrowsing-disable-auto-update --disable-default-apps --wm-window-animations-disabled --disable-component-update --test-type=browser --force-color-profile=srgb --disable-zero-browsers-open-for-tests --ipc-connection-timeout=30 --allow-file-access-from-files --dom-automation --log-gpu-control-list-decisions --disable-backgrounding-occluded-windows --disable-gl-drawing-for-tests --override-use-software-gl-for-tests --force-color-profile=srgb --allow-legacy-extension-manifests --disable-features=NetworkPrediction --flag-switches-begin --flag-switches-end --restore-last-session about:blank
[5936:1628:0804/040824.460:WARNING:render_frame_host_impl.cc(2614)] OnDidStopLoading was called twice.
[5936:1628:0804/040824.539:INFO:CONSOLE(0)] "[FAIL] userAction: Received unexpected event 'onCreatedNavigationTarget':{"sourceFrameId":1,"sourceProcessId":1,"sourceTabId":0,"tabId":1,"timeStamp":0,"url":"chrome-extension://idlghkhmcoiheemhcoibdoomgdknhjdi/b.html"}
Error
    at Object.handleRequest (extensions::binding:64:27)
    at Object.<anonymous> (extensions::binding:374:32)
    at captureEvent (chrome-extension://idlghkhmcoiheemhcoibdoomgdknhjdi/_test_resources/api_test/webnavigation/framework.js:194:17)
    at chrome-extension://idlghkhmcoiheemhcoibdoomgdknhjdi/_test_resources/api_test/webnavigation/framework.js:223:5
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:140:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at dispatchArgs (extensions::event_bindings:260:26)
    at dispatchEvent (extensions::event_bindings:269:7)", source: chrome-extension://idlghkhmcoiheemhcoibdoomgdknhjdi/test_userAction.html (0)
../../chrome/browser/extensions/api/web_navigation/web_navigation_apitest.cc(537): error: Value of: catcher.GetNextResult()
  Actual: false
Expected: true
Failed 1 of 1 tests

Original change's description:
> Enable WebNavigationApiTest.UserAction
> 
> Bug: 662160
> Change-Id: If252b4f8765eb70218f6c89d8794c05566700fbe
> Reviewed-on: https://chromium-review.googlesource.com/600768
> Reviewed-by: Alex Moshchuk <alexmos@chromium.org>
> Commit-Queue: Nasko Oskov <nasko@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#491817}

TBR=nasko@chromium.org,alexmos@chromium.org

Change-Id: Ieeabb0b39759aa8b94916d7c10b3c867d106a142
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 662160
Reviewed-on: https://chromium-review.googlesource.com/602147
Reviewed-by: Vasilii Sukhanov <vasilii@chromium.org>
Commit-Queue: Vasilii Sukhanov <vasilii@chromium.org>
Cr-Commit-Position: refs/heads/master@{#491995}
Former-commit-id: 5769cefdcb9f8a47e9edc90b9f1e7b76c813b6bb