Web Inspector: exception in remote front-end load handler due to undefined reference to workerManager https://bugs.webkit.org/show_bug.cgi?id=71889
Move calls to WorkerManager load handlers into doLoadedDone method which is
called in case of remote front-end too.

Reviewed by Pavel Feldman.

* inspector/front-end/inspector.js:
(WebInspector.loaded):

git-svn-id: svn://svn.chromium.org/blink/trunk@99692 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: 49a20f22d98706cb28c9be4e26937b74f2658c19