Revert "Activate Network traffic annotation tests for Linux trybot."
This reverts commit 9f85e3d91a0b6f18e85b1ff1f87a9cc680b68824 [formerly 86ff9bc4d831eebf5c0f0b0a04214d1b28e50c3f].

Reason for revert:
flaky, i.e. see

https://ci.chromium.org/buildbot/tryserver.chromium.linux/linux_chromium_rel_ng/634904
https://ci.chromium.org/buildbot/tryserver.chromium.linux/linux_chromium_rel_ng/634934
https://ci.chromium.org/buildbot/tryserver.chromium.linux/linux_chromium_rel_ng/634954

which fail with
Returned error text: Traceback (most recent call last):
  File "/b/c/b/linux/src/tools/clang/scripts/run_tool.py", line 315, in <module>
    sys.exit(main())
  File "/b/c/b/linux/src/tools/clang/scripts/run_tool.py", line 281, in main
    f.write(compile_db.GenerateWithNinja(args.p))
  File "/b/c/b/linux/src/tools/clang/pylib/clang/compile_db.py", line 94, in GenerateWithNinja
    GetNinjaPath(), '-C', path, '-t', 'compdb', 'cc', 'cxx', 'objc',
  File "/b/c/b/linux/src/tools/clang/pylib/clang/compile_db.py", line 76, in GetNinjaPath
    os.path.dirname(os.realpath(__file__)), '..', '..', '..', 'third_party',
AttributeError: 'module' object has no attribute 'realpath'




Original change's description:
> Activate Network traffic annotation tests for Linux trybot.
>
> Traffic annotation tests are updated to run on the changed files instead
> of the whole repository, which should make tests much faster.
>
> Bug: 690323
> Bug: 788035
> Change-Id: I4eb7c173f5d677cdb9944f02e9c15dfa0a374b10
> Reviewed-on: https://chromium-review.googlesource.com/856456
> Reviewed-by: Martin Šrámek <msramek@chromium.org>
> Reviewed-by: Dirk Pranke <dpranke@chromium.org>
> Commit-Queue: Ramin Halavati <rhalavati@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#528573}

TBR=dpranke@chromium.org,msramek@chromium.org,rhalavati@chromium.org


Bug: 690323, 788035
Change-Id: I048be491eb64c221bb4edeab2e0d2aa051b5faa7
Reviewed-on: https://chromium-review.googlesource.com/892383
Reviewed-by: John Abd-El-Malek <jam@chromium.org>
Cr-Commit-Position: refs/heads/master@{#532741}
Former-commit-id: 0e0e6d654fcdae192825324c811798a63dff0ae9