gamepad: Include <string.h> for memset()
IWYU after commit b8fdf46c ("Consolidate code to set device::Gamepad id
field"), which also fixes the libstdc++ build:

../../device/gamepad/public/cpp/gamepad.cc:28:3: error: use of undeclared identifier 'memset'; did you mean 'wmemset'?
  memset(id, 0, sizeof(id));

Bug: 957519
Change-Id: I5b5a8d9d7bc0de6e5b32ddd29ce0c5c17c883ac3
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1649496
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Commit-Queue: Matt Reynolds <mattreynolds@chromium.org>
Reviewed-by: Matt Reynolds <mattreynolds@chromium.org>
Cr-Commit-Position: refs/heads/master@{#667236}

Former-commit-id: bbe92eaa4e33f1f736d7bda73d195f935ed36caf