Fix unhelpful presubmit message
Before:
  File "/usr/local/google/home/dtseng/projects/chrome/src/third_party/chromevox/third_party/closure-library/closure/bin/build/depstree.py", line 56, in __init__
    raise NamespaceNotFoundError(require, source)
NamespaceNotFoundError: Namespace "cvox.AbstractEarcons" never provided. Required in <jsbundler.SourceWithPaths object at 0x7fcc566aa150>

After:
  File "/usr/local/google/home/dtseng/projects/chrome/src/third_party/chromevox/third_party/closure-library/closure/bin/build/depstree.py", line 56, in __init__
    raise NamespaceNotFoundError(require, source)
NamespaceNotFoundError: Namespace "cvox.AbstractEarcons" never provided. Required in common/classic_earcons.js
Issue:
closure-library/closure/bin/build/depstree.py
(part of Closure Library code)
does:
          raise NamespaceNotFoundError(require, source)

but |source| has no stringification that's friendly so you get the raw
jsbundler.SourceWithPaths
(which inherits from the Closure Library |Source| class).

Fix by providing __str__ in the jsbundler.SourceWithPaths object (so we don't have to mod Closure Library).

Change-Id: I72ca69869690661aabebc2b68843d7b2a8e6d428
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1929915
Reviewed-by: Steven Bennetts <stevenjb@chromium.org>
Commit-Queue: David Tseng <dtseng@chromium.org>
Cr-Commit-Position: refs/heads/master@{#718269}

Former-commit-id: 638a5c7542205b1613d58d2ba8bb6b608bb16cbe