Revert "Roll WebKit DEPS: 132872 -> 132896."
This reverts commit 004e1cbe4a8ae6ccd77a59d2fdbfa8617674386c.

Broke webkit_compositor_bindings_unittests on multiple bots:

WebTransformationMatrixTest.verifyRotateAxisAngle3dForDegenerateAxis:
web_transformation_matrix_unittest.cc(643): error: The difference between (0) and (A).m11() is 1, which exceeds (1e-14), where
(0) evaluates to 0,
(A).m11() evaluates to 1, and
(1e-14) evaluates to 1e-014.
web_transformation_matrix_unittest.cc(643): error: The difference between (-1) and (A).m21() is 1, which exceeds (1e-14), where
(-1) evaluates to -1,
(A).m21() evaluates to 0, and
(1e-14) evaluates to 1e-014.
web_transformation_matrix_unittest.cc(644): error: The difference between (1) and (A).m12() is 1, which exceeds (1e-14), where
(1) evaluates to 1,
(A).m12() evaluates to 0, and
(1e-14) evaluates to 1e-014.
web_transformation_matrix_unittest.cc(644): error: The difference between (0) and (A).m22() is 1, which exceeds (1e-14), where
(0) evaluates to 0,
(A).m22() evaluates to 1, and
(1e-14) evaluates to 1e-014.

TBR=podivilov

BUG=none
TEST=none

Review URL: https://codereview.chromium.org/11276063

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@164936 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 5463b8c6cd805712163c5fa9154edc169e06f843