Disable WebContentsObserverAndroidTest#testDidFirstVisuallyNonEmptyPaint
It broke on Android Tests (dbg)

http://build.chromium.org/p/chromium.webkit/builders/Android%20Tests%20%28dbg%29/builds/21342

[FAIL] org.chromium.content.browser.WebContentsObserverAndroidTest#testDidFirstVisuallyNonEmptyPaint:
java.util.concurrent.TimeoutException: waitForCallback timed out!
  at org.chromium.content.browser.test.util.CallbackHelper.waitForCallback(CallbackHelper.java:183)
  at org.chromium.content.browser.test.util.CallbackHelper.waitForCallback(CallbackHelper.java:191)
  at org.chromium.content.browser.test.util.CallbackHelper.waitForCallback(CallbackHelper.java:197)
  at org.chromium.content.browser.WebContentsObserverAndroidTest.testDidFirstVisuallyNonEmptyPaint(WebContentsObserverAndroidTest.java:70)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
  at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
  at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
  at org.chromium.content_shell_apk.ContentShellTestBase.runTest(ContentShellTestBase.java:227)
  at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
  at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
  at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)

BUG=411931
TBR=keishi, reed

Review URL: https://codereview.chromium.org/554713002

Cr-Commit-Position: refs/heads/master@{#293738}

Former-commit-id: 833089c8f5bec9a81323cbb314689f9569eb6ec8