chromeos: Fix a clang build error in CandidateWindowView.
Clang doesn't like the destructor to be inlined in .h file.

./chrome/browser/chromeos/input_method/candidate_window_view.h:32:3: error: [chromium-style] Complex destructor has an inline body.

The error was caused by crrev.com/110492

TEST=chrome builds
BUG=none

Review URL: http://codereview.chromium.org/8585043

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@110563 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: e354398e7fe14c39b09920c3e57cbd9adda67b29