Revert of Roll PDFium to 1e580a10fad09833552deb797128e00c50d74bce (patchset #1 id:1 of https://codereview.chromium.org/989213003/)
Reason for revert:
Broke at least Win8 GN

http://build.chromium.org/p/chromium.win/builders/Win8%20GN/builds/5379/steps/compile/logs/stdio

FAILED: ninja -t msvc -e environment.x86 -- E:\b\build\goma/gomacc.exe "E:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/third_party/pdfium/samples/pdfium_diff.image_diff_png.obj.rsp /c ../../third_party/pdfium/samples/image_diff_png.cc /Foobj/third_party/pdfium/samples/pdfium_diff.image_diff_png.obj /Fdobj/third_party/pdfium/samples/pdfium_diff_cc.pdb
e:\b\build\slave\win8_gn\build\src\third_party\pdfium\samples\image_diff_png.cc(246) :error C2220: warning treated as error - no 'object' file generated
e:\b\build\slave\win8_gn\build\src\third_party\pdfium\samples\image_diff_png.cc(246) : warning C4702: unreachable code
e:\b\build\slave\win8_gn\build\src\third_party\pdfium\samples\image_diff_png.cc(574) : warning C4702: unreachable code
FAILED: ninja -t msvc -e environment.x86 -- E:\b\build\goma/gomacc.exe "E:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/third_party/pdfium/samples/pdfium_test.image_diff_png.obj.rsp /c ../../third_party/pdfium/samples/image_diff_png.cc /Foobj/third_party/pdfium/samples/pdfium_test.image_diff_png.obj /Fdobj/third_party/pdfium/samples/pdfium_test_cc.pdb
e:\b\build\slave\win8_gn\build\src\third_party\pdfium\samples\image_diff_png.cc(246) :error C2220: warning treated as error - no 'object' file generated
e:\b\build\slave\win8_gn\build\src\third_party\pdfium\samples\image_diff_png.cc(246) : warning C4702: unreachable code
e:\b\build\slave\win8_gn\build\src\third_party\pdfium\samples\image_diff_png.cc(574) : warning C4702: unreachable code
ninja: build stopped: subcommand failed.

Original issue's description:
> Roll PDFium to 1e580a10fad09833552deb797128e00c50d74bce
>
> This brings in:
> 1e580a1 Fix multiply defined macro in zlib.h on linux_chromium_clobber_rel_ng builder.
> 0700106 Make conversions for CPDF_Link explicit.
> 8842c62 Fix the pdfium component build.
> 5a370d7 Make conversion between CPDF_Dest and its object explicit.
> 7348fae Add gmock to .gitignore
> 624b6c1 Make conversion between CPDF_Action and its dictionary explicit.
> 61c25ee Merge to Master: Fix a compiling error in fxjs_v8.h
> e1671bd Kill off JS_ErrorString type.
> b720d0a Return error information from pdfium to JS.
> 944ccad Do hit tests against Annots in reverse order.
> 5b47dbf Remove unused IDS_ constants from pdfium.
> 3d25502 Pull in gmock for standalone pdfium builds.
> ec61a85 Upgrade openjpeg to revision 2997.
> 42a8ada Implement a delegate for EmbedderTests.
> 57e4c86 Kill off unused IFXJS interface methods.
> 4351ac2 Fix compilation error on Windows.
> f9cfdda Add small flate decode unit test.
> e796478 Kill multi-byte comments in fxet_list.h
> 23f9288 Convert pdfium expected test results to PNG format.
> 0fd53cf Fix GN build after PNG support backport
> ef1e85c Backport PNG output format to origin/master branch.
>
> BUG=445408,457493,PDFIUM:123
>
> Committed: https://crrev.com/fe047d9a4f0cee8d8ee21a5b2eb0ce44d5f07b60 [formerly 608e59f9ceecd5b60ae5e50c4f0da4bc6a7f405e]
> Cr-Commit-Position: refs/heads/master@{#319781}

TBR=brettw@chromium.org,thestig@chromium.org,tsepez@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=445408,457493,PDFIUM:123

Review URL: https://codereview.chromium.org/996523002

Cr-Commit-Position: refs/heads/master@{#319785}

Former-commit-id: bcbfc458e472b390d618791ff033d6730e556cd9