Revert of Move ENABLE_PROFILING to build flags system. (patchset #3 id:40001 of https://codereview.chromium.org/1499773002/ )
Reason for revert:
breaks Mac compile:

debug/profiler.cc:9:10: fatal error: 'base/debug/debugging_flags.h' file not found
#include "base/debug/debugging_flags.h"

Original issue's description:
> Move ENABLE_PROFILING to build flags system.
>
> This flag is only used in 3 files so having a global define is unnecessary.
>
> Moves the build flag to compiler.gni so it can be included by the new target in base that generates the header, as well as the tcmalloc target.
>
> The tcmalloc target now conditionally compiles the profiler depending on this flag. This is something the GYP build does but was inconsistent in GN. This results in the tcmalloc source files not being compiled in normal builds.
>
> This should remove the static initializer in tcmalloc profiling in the normal build.
>
> Independently, remove an iostream use in gin logging. Use printf instead.
>
> BUG=559766
> NOPRESUBMIT=true
> (on account of changing the printf, which I did not add)
>
> Committed: https://crrev.com/93ed9d558ad42d02d376e422d12e2503c13c7d17 [formerly 41619210895837ee1a0063b786fed2b587ccc362]
> Cr-Commit-Position: refs/heads/master@{#363156}

TBR=dpranke@chromium.org,brettw@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=559766

Review URL: https://codereview.chromium.org/1497953002

Cr-Commit-Position: refs/heads/master@{#363161}

Former-commit-id: 3c2d33560c6ab491e6c689474128656785b9bb8f