Fix frequent Windows bot failure
The Windows bots often fail because they can't delete a directory. pynacl contains two directory deletion functions: one that retries with exponential backup (up to 32 seconds), and one that retries once after making the file writable. Go back to having a single function that combines both approaches. We might want to consider sacrificing a goat too if the Windows Gods don't sacrifice the folder.

R=ncbray@chromium.org, bradnelson@chromium.org

Failure example from a recent run of bot nacl-toolchain-win7-pnacl-x86_64:

FAILED: rmtree (u'E:\\b\\build\\slave\\nacl-toolchain\\build\\native_client\\toolchain\\win_x86\\nacl_x86_newlib',)

RETRY: rmtree (u'E:\\b\\build\\slave\\nacl-toolchain\\build\\native_client\\toolchain\\win_x86\\nacl_x86_newlib',)

FAILED: rmtree (u'E:\\b\\build\\slave\\nacl-toolchain\\build\\native_client\\toolchain\\win_x86\\nacl_x86_newlib',)

RETRY: rmtree (u'E:\\b\\build\\slave\\nacl-toolchain\\build\\native_client\\toolchain\\win_x86\\nacl_x86_newlib',)

FAILED: rmtree (u'E:\\b\\build\\slave\\nacl-toolchain\\build\\native_client\\toolchain\\win_x86\\nacl_x86_newlib',)

RETRY: rmtree (u'E:\\b\\build\\slave\\nacl-toolchain\\build\\native_client\\toolchain\\win_x86\\nacl_x86_newlib',)

FAILED: rmtree (u'E:\\b\\build\\slave\\nacl-toolchain\\build\\native_client\\toolchain\\win_x86\\nacl_x86_newlib',)

RETRY: rmtree (u'E:\\b\\build\\slave\\nacl-toolchain\\build\\native_client\\toolchain\\win_x86\\nacl_x86_newlib',)

FAILED: rmtree (u'E:\\b\\build\\slave\\nacl-toolchain\\build\\native_client\\toolchain\\win_x86\\nacl_x86_newlib',)

Traceback (most recent call last):

  File "native_client/build/package_version/package_version.py", line 1296, in <module>

    sys.exit(main(sys.argv[1:]))

  File "native_client/build/package_version/package_version.py", line 1289, in main

    return COMMANDS[arguments.command].do_cmd_func(arguments)

  File "native_client/build/package_version/package_version.py", line 856, in _DoSyncCmd

    quiet=arguments.quiet)

  File "native_client/build/package_version/package_version.py", line 500, in ExtractPackageTargets

    pynacl.file_tools.RemoveDir(dest_package_dir)

  File "E:\b\build\slave\nacl-toolchain\build\native_client\pynacl\file_tools.py", line 246, in RemoveDir

    Retry(shutil.rmtree, path)

  File "E:\b\build\slave\nacl-toolchain\build\native_client\pynacl\file_tools.py", line 220, in Retry

    op(*args)

  File "E:\b\depot_tools\python276_bin\lib\shutil.py", line 247, in rmtree

    rmtree(fullname, ignore_errors, onerror)

  File "E:\b\depot_tools\python276_bin\lib\shutil.py", line 247, in rmtree

    rmtree(fullname, ignore_errors, onerror)

  File "E:\b\depot_tools\python276_bin\lib\shutil.py", line 256, in rmtree

    onerror(os.rmdir, path, sys.exc_info())

  File "E:\b\depot_tools\python276_bin\lib\shutil.py", line 254, in rmtree

    os.rmdir(path)

WindowsError: [Error 5] Access is denied: u'E:\\b\\build\\slave\\nacl-toolchain\\build\\native_client\\toolchain\\win_x86\\nacl_x86_newlib\\.tmp\\core_sdk'

Review URL: https://codereview.chromium.org/886253002


Former-commit-id: 7bdb00bdeb26ffe139744dc74df25eb9cf1f9b82