For webkit_glue::MockWebFrame, define setScrollOffset() that will be soon introduced.
(by https://bugs.webkit.org/show_bug.cgi?id=54632).

Otherwise, landing the WebKit patch results in Chromium build breakage.
Example:
.\glue\media\buffered_resource_loader_unittest.cc(87) : error C2259: 'testing::NiceMock<MockClass>' : cannot instantiate abstract class
    with
    [
      MockClass=webkit_glue::MockWebFrame
    ]
    due to following members:
    'void WebKit::WebFrame::setScrollOffset(const WebKit::WebSize &)' : is abstract
    c:\b\build\slave\webkit-win-latest-rel\build\src\third_party/WebKit/Source/WebKit/chromium/public/WebFrame.h(146) : see declaration of 'WebKit::WebFrame::setScrollOffset'

BUG=none
TEST=none

Review URL: http://codereview.chromium.org/6538049

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@75367 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 29a643cfae48661a282ef72131644c62f532b06d