Revert of Move scaling of ui resources for scrollbars to the time of upload (patchset #1 id:1 of https://codereview.chromium.org/2280663002/ )
Reason for revert:
Sorry about the spam. Re-reverting now that https://codereview.chromium.org/2282433002 which depends on this patch has been reverted.

Original issue's description:
> Reland of Move scaling of ui resources for scrollbars to the time of upload (patchset #1 id:1 of https://codereview.chromium.org/2278083002/ )
>
> Reason for revert:
> Reverting this broke compile:
>
> cc/layers/painted_scrollbar_layer.cc:83:29: error: no member named 'GetRendererCapabilities' in 'cc::LayerTreeHost'
>   return layer_tree_host()->GetRendererCapabilities().max_texture_size;
>          ~~~~~~~~~~~~~~~~~  ^
>
> Original issue's description:
> > Revert of Move scaling of ui resources for scrollbars to the time of upload (patchset #6 id:100001 of https://codereview.chromium.org/2276633003/ )
> >
> > Reason for revert:
> > Sorry, seems to have caused LayerTreeHostScrollbarsPixelTest.HugeTransformScale to fail on Mac10.10 Tests,  Mac10.11 Tests, Win 7 Tests x64 (1), Win10 Tests x64, Mac10.9 Tests and Linux Tests, with failures like:
> >
> > [8034:1287:0825/033725:3059591139598:ERROR:pixel_comparator.cc(50)] Number of pixel with an error: 672
> > [8034:1287:0825/033725:3059591187709:ERROR:pixel_comparator.cc(51)] Error Bounding Box : 0,304 368x66
> > [8034:1287:0825/033725:3059610880597:ERROR:pixel_test_utils.cc(79)] Pixels do not match!
> > [8034:1287:0825/033725:3059610905829:ERROR:pixel_test_utils.cc(80)] Actual: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAYAAACAvzbMAAAF4ElEQVR4nO3ZQY1CQRRFwccEUWhhgQEMYAED7FGDKtJsxsCcTYdMVQt4d3eS/w9rrTUAX+g+97nNbfeMbS5zmec8t93/2XYZgK8mIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAcnzMY/cGgOQ1r90T/rXjda67NwDwhXzCAiAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREACS43nOuzcAEJzmtPX+4b3ea+sCAJLD79t2f60lIAD8mX8gACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJB9NHxfMgTV5VwAAAABJRU5ErkJggg==
> > [8034:1287:0825/033725:3059610929427:ERROR:pixel_test_utils.cc(81)] Expected: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAYAAACAvzbMAAAF4klEQVR4nO3ZQY1CQRRFwfcJotDCYhQgAAsIQABqMEXSo2HOpkOmysC7u5N0H2utNQBf6DGPuc9994xtfuZnXvPadv+07TIAX01AAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIDk/Jzn7g0AyXveuyf8a+fb3HZvAOALecICIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQAJLzda67NwAQXOay9f7xWZ+1dQEAyWlOc8yx7f6x1hIQAP7MHwgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICADJLzUdF8xyVTjQAAAAAElFTkSuQmCC
> > ../../cc/test/layer_tree_pixel_test.cc:124: Failure
> > Value of: MatchesPNGFile(*result_bitmap_, ref_file_path, *pixel_comparator_)
> >   Actual: false
> > Expected: true
> >
> > Original issue's description:
> > > Move scaling of ui resources for scrollbars to the time of upload
> > >
> > > Instead of trying to figure out what the max texture size is on the
> > > main thread, and scale raster to meet that, just raster freely. Then
> > > when uploading the UIResource to a texture, we can easily tell what
> > > the max texture size is, and if the UIResource is too large, scale it
> > > down to fit in a texture.
> > >
> > > R=enne
> > > BUG=606056
> > > CQ_INCLUDE_TRYBOTS=master.tryserver.blink:linux_precise_blink_rel
> > > NOTRY=true
> > >
> > > Committed: https://crrev.com/4c2a9d0df015efbeb7d8276936c9d360c01c054a [formerly 941e52edd1522f7c3935aa4f4d763c43578b4944]
> > > Cr-Commit-Position: refs/heads/master@{#414202}
> >
> > TBR=enne@chromium.org,danakj@chromium.org
> > # Skipping CQ checks because original CL landed less than 1 days ago.
> > NOPRESUBMIT=true
> > NOTREECHECKS=true
> > NOTRY=true
> > BUG=606056
> >
> > Committed: https://crrev.com/52400e45f50c14d4ce2d52cc738b9d3d78067250 [formerly 706757873f077fcf245c8e4054a5dfd8424d5ed2]
> > Cr-Commit-Position: refs/heads/master@{#414391}
>
> TBR=enne@chromium.org,danakj@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=606056
>
> Committed: https://crrev.com/4d3765c044a5bd55febe4c6812641dfc938ca25a [formerly f56ab5d893d9c1ff735136d8df7d738b16634a7a]
> Cr-Commit-Position: refs/heads/master@{#414394}

TBR=enne@chromium.org,danakj@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=606056

Review-Url: https://codereview.chromium.org/2282443002
Cr-Commit-Position: refs/heads/master@{#414411}

Former-commit-id: 4e32d1b85ab14a1e8ed25250345267c0c7364e38