Revert of Linux UI: Switch to the Gtk3 theme (patchset #1 id:1 of https://codereview.chromium.org/2709333002/ )
Reason for revert:
This seems to have broken various tests on a Linux bot: https://uberchromegw.corp.google.com/i/chromium.linux/builders/Linux%20Tests%20%28dbg%29%281%29%2832%29

e.g.: https://chromium-swarm.appspot.com/task?id=3480d58abbe19910&refresh=10&show_raw=1

Relevant line from the output:
../../out/Debug/chrome: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

Original issue's description:
> Reland of Linux UI: Switch to the Gtk3 theme (patchset #1 id:1 of https://codereview.chromium.org/2711753004/ )
>
> Reason for revert:
> The -Wsentinel error should be fixed by https://codereview.chromium.org/2707313002/
>
> Original issue's description:
> > Revert of Linux UI: Switch to the Gtk3 theme (patchset #1 id:1 of https://codereview.chromium.org/2670623002/ )
> >
> > Reason for revert:
> > Broke the build:
> > https://build.chromium.org/p/chromium.linux/builders/Linux%20Builder%20%28dbg%29%2832%29/builds/63779
> >
> > [3232/5256] CXX obj/chrome/browser/ui/libgtkui/libgtk3ui/native_theme_gtk3.o
> > FAILED: obj/chrome/browser/ui/libgtkui/libgtk3ui/native_theme_gtk3.o
> > /b/c/goma_client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/browser/ui/libgtkui/libgtk3ui/native_theme_gtk3.o.d -DLIBGTKUI_IMPLEMENTATION -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=\"289944-2\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DCOMPONENT_BUILD -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -DUSE_GCONF -DUSE_CUPS -DGL_GLEXT_PROTOTYPES -DUSE_GLX -DUSE_EGL -DTOOLKIT_VIEWS=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DSK_IGNORE_DW_GRAY_FIX -DSK_IGNORE_DIRECTWRITE_GASP_FIX -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSKIA_DLL -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_SUPPORT_GPU=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DPROTOBUF_USE_DLLS -DBORINGSSL_SHARED_LIBRARY -DUSING_V8_SHARED -I../.. -Igen -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/gconf/2 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/dbus-1.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/lib/i386-linux-gnu/dbus-1.0/include -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/glib-2.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/lib/i386-linux-gnu/glib-2.0/include -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/glib-2.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/lib/i386-linux-gnu/glib-2.0/include -I../../third_party/khronos -I../../gpu -I../../third_party/libwebp -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/glib-2.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/lib/i386-linux-gnu/glib-2.0/include -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/gtk-3.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/pango-1.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/gio-unix-2.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/atk-1.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/cairo -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/gdk-pixbuf-2.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/freetype2 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/pixman-1 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/libpng12 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/gtk-3.0/unix-print -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/gtk-3.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/atk-1.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/cairo -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/gdk-pixbuf-2.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/pango-1.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/gio-unix-2.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/freetype2 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/glib-2.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/lib/i386-linux-gnu/glib-2.0/include -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/pixman-1 -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/libpng12 -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -Igen/chrome -Igen/chrome -Igen/chrome -Igen/chrome -Igen/components -Igen/components -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/include/gpu -I../../third_party/skia/src/gpu -I../../third_party/skia/src/sksl -I../../third_party/mesa/src/include -I../../third_party/libwebm/source -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../third_party/boringssl/src/include -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/nss -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/nspr -Igen -I../../third_party/WebKit -Igen/third_party/WebKit -I../../v8/include -Igen/v8/include -Igen/ui/resources -Igen/ui/resources -Igen/ui/views/resources -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -fcolor-diagnostics -m32 -msse2 -mfpmath=sse -mmmx -momit-leaf-frame-pointer -pthread -mstack-alignment=16 -mstackrealign -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-block-capture-autoreleasing -O0 -fno-omit-frame-pointer -g2 -gsplit-dwarf --sysroot=../../build/linux/debian_wheezy_i386-sysroot -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wno-unused-function -Wno-unused-local-typedef -Wno-header-guard -fvisibility-inlines-hidden -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=gnu++11 -fno-rtti -fno-exceptions -c ../../chrome/browser/ui/libgtkui/native_theme_gtk3.cc -o obj/chrome/browser/ui/libgtkui/libgtk3ui/native_theme_gtk3.o
> > ../../chrome/browser/ui/libgtkui/native_theme_gtk3.cc:542:74: error: missing sentinel in function call [-Werror,-Wsentinel]
> >     gtk_style_context_get(context, state, "min-height", &min_height, NULL);
> >                                                                          ^
> >                                                                          , nullptr
> > ../../build/linux/debian_wheezy_i386-sysroot/usr/include/gtk-3.0/gtk/gtkstylecontext.h:736:6: note: function has been explicitly marked sentinel here
> > void gtk_style_context_get          (GtkStyleContext *context,
> >      ^
> > 1 error generated.
> >
> > Original issue's description:
> > > Linux UI: Switch to the Gtk3 theme
> > >
> > > Sets "use_gtk3 = true" by default.
> > >
> > > BUG=79722
> > > TBR=dpranke@chromium.org
> > >
> > > Review-Url: https://codereview.chromium.org/2670623002
> > > Cr-Commit-Position: refs/heads/master@{#452118}
> > > Committed: https://chromium.googlesource.com/chromium/src/+/30e3e11a7bffd7161a2022a87381dd3dc2871a0a [formerly 872a494bba52e597388aec738d9d681183a3d47b]
> >
> > TBR=erg@chromium.org,mmoss@chromium.org,thomasanderson@google.com
> > # Skipping CQ checks because original CL landed less than 1 days ago.
> > NOPRESUBMIT=true
> > NOTREECHECKS=true
> > NOTRY=true
> > BUG=79722
> >
> > Review-Url: https://codereview.chromium.org/2711753004
> > Cr-Commit-Position: refs/heads/master@{#452149}
> > Committed: https://chromium.googlesource.com/chromium/src/+/6a465c4de45692139260b94462e60092dd86e2a9 [formerly 4ebd84e40a1c791117a8d3f7b85c13cfdf816864]
>
> TBR=erg@chromium.org,mmoss@chromium.org,fgorski@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=79722
>
> Review-Url: https://codereview.chromium.org/2709333002
> Cr-Commit-Position: refs/heads/master@{#452208}
> Committed: https://chromium.googlesource.com/chromium/src/+/8f845bb7f158bf6779dff1748c407c58ce36f755 [formerly d6f69d9b551e64dae8d9fca247116de7827c2a76]

TBR=erg@chromium.org,mmoss@chromium.org,fgorski@chromium.org,qiankun.miao@intel.com,thomasanderson@google.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=79722

Review-Url: https://codereview.chromium.org/2713513006
Cr-Commit-Position: refs/heads/master@{#452468}

Former-commit-id: b298b9de02d88e38719642806407be6abb630f04