GLVisualPickerGLX: Include <bitset> for std::bitset
IWYU. This fixes the libstdc++ build after commit cc2d59dfb7 [formerly a4e1df9823] ("Fix window
compositing with alpha channels on HDR displays"):

../../ui/gl/gl_visual_picker_glx.cc:24:17: error: no member named 'bitset' in namespace 'std'
    return std::bitset<8 * sizeof(decltype(x))>(x).count();
           ~~~~~^
../../ui/gl/gl_visual_picker_glx.cc:27:29: error: invalid operands to binary expression ('void' and 'void')
      bits(visual.red_mask) + bits(visual.green_mask) + bits(visual.blue_mask);
      ~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~

Bug: 957519
Change-Id: If19a691d424ddd55475e673fe9cb733ba7a326f1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1910083
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Commit-Queue: Jonathan Backer <backer@chromium.org>
Reviewed-by: Jonathan Backer <backer@chromium.org>
Cr-Commit-Position: refs/heads/master@{#714211}

Former-commit-id: a9559bef0887dd082b73677041656f7ff4345b49