Revert of Enable connection to Mojo services from Blink (patchset #19 id:360001 of https://codereview.chromium.org/2460723003/ )
Reason for revert:
Caused some build failures, looks like missing dependencies?

https://build.chromium.org/p/chromium.gpu/builders/GPU%20Win%20Builder/builds/56562/steps/compile/logs/stdio

FAILED: obj/third_party/WebKit/Source/platform/heap/heap/ThreadState.obj
ninja -t msvc -e environment.x86 -- E:\b\c\cipd\goma/gomacc.exe "E:\b\depot_tools\win_toolchain\vs_files\d3cb0e37bdd120ad0ac4650b674b09e81be45616\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/third_party/WebKit/Source/platform/heap/heap/ThreadState.obj.rsp /c ../../third_party/WebKit/Source/platform/heap/ThreadState.cpp /Foobj/third_party/WebKit/Source/platform/heap/heap/ThreadState.obj /Fd"obj/third_party/WebKit/Source/platform/heap/heap_cc.pdb"
e:\b\c\b\win\src\third_party\webkit\public\platform\platform.h(59): fatal error C1083: Cannot open include file: 'services/service_manager/public/interfaces/connector.mojom-blink.h': No such file or directory

Original issue's description:
> Enable connection to Mojo services from Blink
>
> This CL enables connections to Mojo services from Blink; more specifically,
> from //third_party/WebKit/Source/modules, where dependencies on Chromium
> code are in general undesired (including on Mojo services' client
> libraries). To enable connecting to services without using the
> Service Manager's client library, this CL does the following:
>
> (1) Adds a method to Platform that exposes the connection to the
> ServiceManager as a service_manager::mojom::blink::ConnectorPtr.
> (2) Builds a bare-bones ServiceConnector around this ConnectorPtr that
> supports connecting to Mojo services by name from Blink.
> (3) Ports TimeZoneMonitor to be hosted in the Device Service as an example
> of connecting to an interface that is hosted in a service other than
> //content/browser from Blink.
>
> ServiceConnector being "bare-bones" includes the facts that:
> - Unlike blink::InterfaceProvider, blink::ServiceConnector is currently
> thread-hostile. This should be easy to relax using similar mechanisms as
> InterfaceProviderImpl.
> - There is currently no API for obtaining an InterfaceProvider for a given
> service (or a thread-safe wrapper, per the above comment). Again, this should
> be easy to add.
>
> This CL also moves the definition of the device service name to mojom instead
> of C++ in order to facilitate using this constant from Blink.
>
> BUG=612341
> TEST=http://crbug.com/288697#c12: load the page, change the system time zone,
>      and then click "recheck" to ensure that the renderer picks up the new
>      time zone. Don't reload the page, which is likely to give you a new
>      renderer process, use the "recheck" link on the page.
>
> Committed: https://crrev.com/f2b9524bc7695c8ced8c0e64fef85aeb09f92235 [formerly 8e3745ac05d7918a91ff9efb02280a7c1443de5c]
> Cr-Commit-Position: refs/heads/master@{#439498}

TBR=jochen@chromium.org,dcheng@chromium.org,esprehn@chromium.org,haraken@chromium.org,noel@chromium.org,rockot@chromium.org,blundell@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=612341

Review-Url: https://codereview.chromium.org/2589493006
Cr-Commit-Position: refs/heads/master@{#439506}

Former-commit-id: bbfdf0517f5986ea2e356067644eb5be1e4de264