Android: fix link error for android_full_debug=1
android_full_debug=1 fails to link with "undefined reference to
__cxa_bad_typeid". Work around this by telling the linker to ignore
unused input sections.

Review URL: https://chromiumcodereview.appspot.com/13772007

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@193737 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 3f05e9167ba720356bdcf866d7456e3c3e53056d