Revert 193777 "url: Changes to make it build standalone."
url/url_canon_stdstring.h:65: error: undefined reference to 'vtable for url_canon::StdStringCanonOutput'


> url: Changes to make it build standalone.
> 
> - Update the gyp file.
> - Rename the gyp file from googleurl.gyp to url.gyp, so it matches the directory
> name.
> - Update the header include paths.
> - Update the header include guards.
> - Rename the target name from googleurl to url and googleurl_unittests to
> url_unittests.
> - Add missing OVERRIDEs where clang complains.
> 
> BUG=229660
> TEST=url_unittests
> R=brettw@chromium.org
> 
> Review URL: https://codereview.chromium.org/14016005

TBR=tfarina@chromium.org
Review URL: https://codereview.chromium.org/14264002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@194155 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 2244f0a5a874fd21da847fca2afc26dc16de7ccc