Revert "BUILD FIX (r146558): Call [super dealloc] from -[TinyDOMNode dealloc]"
This fixes a build failure introduced by this change:

    Source/JavaScriptCore/API/tests/testapi.mm:206:6: error: ARC forbids explicit message send of 'dealloc'
        [super dealloc];
         ^     ~~~~~~~
    1 error generated.

Not sure why this didn't fail locally on my Mac Pro.

* API/tests/testapi.mm:
(-[TinyDOMNode dealloc]): Remove call to [super dealloc].

git-svn-id: svn://svn.chromium.org/blink/trunk@146603 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: 5911b46403a5a74f5c9708ee17bec3a7e55c02b4