Revert of Roll ANGLE 592ab9dd9..38832d179d. (patchset #1 id:1 of https://codereview.chromium.org/912423002/)
Reason for revert:
Breaks Win8 GN build: http://build.chromium.org/p/chromium.win/builders/Win8%20GN/builds/4638

FAILED: ninja -t msvc -e environment.x86 -- E:\b\build\goma/gomacc.exe "E:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/third_party/angle/src/libANGLE/renderer/d3d/libANGLE.ProgramD3D.obj.rsp /c ../../third_party/angle/src/libANGLE/renderer/d3d/ProgramD3D.cpp /Foobj/third_party/angle/src/libANGLE/renderer/d3d/libANGLE.ProgramD3D.obj /Fdobj/third_party/angle/libANGLE_cc.pdb
e:\b\depot_tools\win_toolchain\vs2013_files\vc\include\concrt.h(313) : error C2220: warning treated as error - no 'object' file generated
e:\b\depot_tools\win_toolchain\vs2013_files\vc\include\concrt.h(313) : warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc

Original issue's description:
> Roll ANGLE 592ab9dd9..38832d179d.
>
> https://chromium.googlesource.com/angle/angle/+log/592ab9dd9..38832d179d
>
> BUG=450257,447419,452587,453543
>
> Committed: https://crrev.com/8831ab0f762f549404b02f001c5a36655bf2948a [formerly 3d2f2ff2b1527148d12cd92177951516ae9d1ede]
> Cr-Commit-Position: refs/heads/master@{#315862}

TBR=bajones@chromium.org,kbr@chromium.org,zmo@chromium.org,jmadill@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=450257,447419,452587,453543

Review URL: https://codereview.chromium.org/889653006

Cr-Commit-Position: refs/heads/master@{#315879}

Former-commit-id: f46813fc5d985fccb715e278a984ad7348f11b3a