Revert 172038 > google_apis: Rename DocumentFeed to ResourceList > > DocumentFeed was a misnomer, as this class represented a resource list. > > Along the way, add more useful comments in gdata_wapi_parser.h, and > fix wrong variable names like 'doc'. > > > BUG=164090 > TEST=none > > > Review URL: https://chromiumcodereview.appspot.com/11499006
The CL broke the tree:
../../chrome/browser/chromeos/extensions/file_browser_event_router.h:91:16:error: 'OnDocumentFeedFetched' marked 'override' but does not override any member functions
  virtual void OnDocumentFeedFetched(int num_accumulated_entries) OVERRIDE;

TBR=satorux@chromium.org
Review URL: https://codereview.chromium.org/11503010

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@172039 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: beff6b317b2cc88775aa889f9bd600c2ca0bcfbd