Fix missing #include in nacl_entry_points.h
Attempt to fix the error that occurred on some of the Chromium Linux
buildbots when updating DEPS to include r2744:

./native_client/src/trusted/plugin/nacl_entry_points.h:52: error: ‘string’ is not a member of ‘std’

Review URL: http://codereview.chromium.org/3034022

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@2776 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: f910369f9801bf9412a64fd6883afbfb3a951b29