[DevTools] Fix "TypeError: database.getTableNames is not a function" when adding/removing tables in the Application tab
In the Application tab, an uncaught exception was thrown when adding/removing
WebSQL tables.

This bug was introduced with this change
(https://chromium.googlesource.com/chromium/src/+/388ba57c%5E%21/#F2) that
renamed `getTableNames` but didn't update one of its callers. The fix is
to use `tableNames` instead.

While testing the fix and having a closer look at the bug, I noticed two
other minor issues, which I also address here:

1) When collapsing/expanding the database node, tables would be added over and
over again, as seen in the screenshot below. This was another regression from
the same change above, where `removeChildren` was removed from `_updateChildren`,
so I added it back.

2) Tables disappear every time a new one is added/removed, and the user needs
to expand the database node again. I added a call to updateChildren so that
this extra step is not needed and the list is updated as necessary.

Let me know if you want 1) and 2) to be separate CLs but they're so minor I
thought it'd be overkill.

Before: https://imgur.com/a/skjKslL
After: https://imgur.com/EIoyKkU

Bug: 1006737
Change-Id: I3feb82d281f890bf18be3bcc7ba14c87739f9435
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1825794
Reviewed-by: Yang Guo <yangguo@chromium.org>
Commit-Queue: Fabio Rocha <fabio.rocha@microsoft.com>
Cr-Commit-Position: refs/heads/master@{#700728}

Former-commit-id: fd6b8c7ae5985d29af6af2e5b5884b5cd41b4e4c