Remove variable shadowing in blink/modules/peerconnection
In an effort to reduce or even ban variable shadowing, this renames
a variable to avoid such shadowing. I'm interested in prohibiting
shadowing because I think it might prevent potential jumbo problems.

The warning this avoids is:
third_party/blink/renderer/modules/peerconnection/rtc_peer_connection.cc:1200:20: error: declaration shadows a local variable [-Werror,-Wshadow]
  for (auto const& transport_iterator : dtls_transports_by_mid_) {
                   ^
third_party/blink/renderer/modules/peerconnection/rtc_peer_connection.cc:1187:8: note: previous declaration is here
  auto transport_iterator = dtls_transports_by_mid_.find(mid);
       ^

Bug: 923510
Change-Id: Ia9e1734c1bd1aa42bf4b13f6d2b43fe28b6ed511
Reviewed-on: https://chromium-review.googlesource.com/c/1478872
Commit-Queue: Daniel Bratell <bratell@opera.com>
Commit-Queue: Kentaro Hara <haraken@chromium.org>
Auto-Submit: Daniel Bratell <bratell@opera.com>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Cr-Commit-Position: refs/heads/master@{#633746}
Former-commit-id: 295bc21a6a64c7519afceb091699e0f666324881