Fixed content_browsertest isolate: webgl_conformance removed.
https://codereview.chromium.org/104723003 broke the content browsertests
on Android with

MappingError: /b/build/slave/Android_Tests__JB_GalaxyNexus__dbg_/
build/src/third_party/webgl_conformance/ is not a directory but
ends with "/"

This patch should fix that.

R=zmo@chromium.org,maruel@chromium.org
BUG=326173

Review URL: https://codereview.chromium.org/108083002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@239231 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: bc833b402b2c0161160fd65e5226d925c035e529