Windows run-webkit-tests broke if --disable-breakpad was used
Running run-webkit-tests in Windows with --disable-breakpad resulted in

AttributeError raised: 'WinPort' object has no attribute '_crash_service'
Traceback (most recent call last):
  File "src\third_party\WebKit\Tools\Scripts\webkitpy\layout_tests\run_webkit_tests.py", line 73, in main
    run_details = run(port, options, args, stderr)
  File "src\third_party\WebKit\Tools\Scripts\webkitpy\layout_tests\run_webkit_tests.py", line 381, in run
    run_details = manager.run(args)
  File "src\third_party\WebKit\Tools\Scripts\webkitpy\layout_tests\controllers\manager.py", line 278, in run
    self._clean_up_run()
  File "src\third_party\WebKit\Tools\Scripts\webkitpy\layout_tests\controllers\manager.py", line 359, in _clean_up_run
    self._port.clean_up_test_run()
  File "L:\src\clean_chromium\src\third_party\WebKit\Tools\Scripts\webkitpy\layout_tests\port\win.py", line 150, in clean_up_test_run
    if self._crash_service:

R=dpranke@chromium.org

Review URL: https://codereview.chromium.org/808163002

git-svn-id: svn://svn.chromium.org/blink/trunk@187488 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: 1de8b284e51aaaf1d214060c162cb99db6fe61a4