Revert "Revert "Don't cache suggestion or download thumbnails on low-memory devices.""
This reverts commit f5abd48e92788fdc04a897b3b1da66c8e90a1e21 [formerly b087611eda04ebe142bd9ff5d471b8df488ff033].

Reason for revert: Not cause of test failure.

Original change's description:
> Revert "Don't cache suggestion or download thumbnails on low-memory devices."
> 
> This reverts commit c230561fbeac322b269e6d8e1991a9163492ac73 [formerly 78ff44b8ab5faa97295d76468f99bd1457d3dcca].
> 
> Reason for revert: Suspect change braking tablet testers:
> https://uberchromegw.corp.google.com/i/chromium.android/builders/KitKat%20Tablet%20Tester
> 
> TileGridLayoutTest#testNumColumnsCalculatedEqualToMeasurement:
> java.lang.AssertionError: The calculated number of columns should be equal to the minimum number of columns across screen orientations. expected:<6> but was:<5>
> 
> Will reland if bots are not fixed.
> 
> Original change's description:
> > Don't cache suggestion or download thumbnails on low-memory devices.
> > 
> > Bug: 718925
> > Change-Id: Ie11a88d9864bf6e4a4e85f7dc15c4e4e01bb00fe
> > Reviewed-on: https://chromium-review.googlesource.com/574856
> > Reviewed-by: Maria Khomenko <mariakhomenko@chromium.org>
> > Reviewed-by: Theresa <twellington@chromium.org>
> > Commit-Queue: Bernhard Bauer <bauerb@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#488639}
> 
> TBR=bauerb@chromium.org,mariakhomenko@chromium.org,twellington@chromium.org
> 
> # Not skipping CQ checks because original CL landed > 1 day ago.
> 
> Bug: 718925
> Change-Id: I281ef5ea1430dac383eaaf11a63ce34db8ab45ab
> Reviewed-on: https://chromium-review.googlesource.com/583546
> Commit-Queue: Matthew Jones <mdjones@chromium.org>
> Reviewed-by: Matthew Jones <mdjones@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#489113}

TBR=bauerb@chromium.org,mariakhomenko@chromium.org,twellington@chromium.org,mdjones@chromium.org,sfiera@chromium.org

Change-Id: If5647bde5e90bf34bf96c6d4177e0eba1c1103eb
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 718925
Reviewed-on: https://chromium-review.googlesource.com/583794
Reviewed-by: Matthew Jones <mdjones@chromium.org>
Commit-Queue: Matthew Jones <mdjones@chromium.org>
Cr-Commit-Position: refs/heads/master@{#489122}
Former-commit-id: 7eaaf6584917d6b270ae1db6ca9eed36ce5aaffb