Revert "Make protobuf enums canonical for ReadState/WriteState/ConnectState."
This reverts commit 92382d23921907628a841af83500a1d51f9a66bd [formerly f1624ddce4b88a5a950f65b511677b914c9caefb].

Broke Google Chrome ChromeOS compile:

http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20ChromeOS/builds/72048/steps/compile/logs/stdio

In file included from gen/extensions/browser/api/generated_api_registration.cc:20:
In file included from ../../extensions/browser/api/cast_channel/cast_channel_api.h:16:
../../extensions/browser/api/cast_channel/cast_socket.h:19:10: fatal error: 'extensions/browser/api/cast_channel/logging.pb.h' file not found
         ^

(Manually reverted because of file add.)

TBR=kmarshall@chromium.org
BUG=

Review URL: https://codereview.chromium.org/588433002

Cr-Commit-Position: refs/heads/master@{#295611}

Former-commit-id: 4b10ffbe3ef9bcc9a1007ae12b7ef7c71db6022b