Revert of Update mojo sdk to rev c02a28868825edfa57ab77947b8cb15e741c5598 (patchset #3 id:120001 of https://codereview.chromium.org/1296453004/ )
Reason for revert:
Compilation error by missing include file:

../../content/renderer/usb/web_usb_client_impl.cc -o obj/content/renderer/renderer/web_usb_client_impl.o
In file included from ../../content/renderer/usb/web_usb_client_impl.cc:14:
../../content/renderer/usb/web_usb_device_impl.h:17:10: fatal error: 'third_party/mojo/src/mojo/public/cpp/bindings/error_handler.h' file not found
#include "third_party/mojo/src/mojo/public/cpp/bindings/error_handler.h"

FAILED: /mnt/data/b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/content/renderer/renderer/web_usb_client_impl.o.d -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -DENABLE_MDNS=1 -DENABLE_NOTIFICATIONS -DENABLE_PEPPER_CDMS -DENABLE_PLUGINS=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DDONT_EMBED_BUILD_METADATA -DUSE_UDEV -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_ASH=1 -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_CLIPBOARD_AURAX11=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_GLIB=1 -DUSE_OPENSSL=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DENABLE_WEBRTC=1 -DENABLE_EXTENSIONS=1 -DENABLE_CONFIGURATION_POLICY -DENABLE_TASK_MANAGER=1 -DENABLE_THEMES=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_GOOGLE_NOW=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_HIDPI=1 -DENABLE_TOPCHROME_MD=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DENABLE_BACKGROUND=1 -DENABLE_PRE_SYNC_BACKUP -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DSAFE_BROWSING_SERVICE -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=245402-1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DCOMPONENT_BUILD -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -D_GLIBCXX_DEBUG=1 -DCONTENT_IMPLEMENTATION -DBORINGSSL_SHARED_LIBRARY -DGL_GLEXT_PROTOTYPES -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSKIA_DLL -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_SUPPORT_GPU=1 -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=0 -DGTEST_HAS_RTTI=0 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_LIBJPEG_TURBO=1 -DCHROME_PNG_WRITE_SUPPORT -DPNG_USER_CONFIG -DV8_SHARED -DUSING_V8_SHARED -DMOJO_USE_SYSTEM_IMPL -D_DEBUG -DFEATURE_ENABLE_SSL -DFEATURE_ENABLE_VOICEMAIL -DEXPAT_RELATIVE_PATH -DGTEST_RELATIVE_PATH -DNO_MAIN_THREAD_WRAPPING -DNO_SOUND_SYSTEM -DLINUX -DWEBRTC_LINUX -DWEBRTC_POSIX -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DPROTOBUF_USE_DLLS -DMESA_EGL_NO_X11_HEADERS -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -I../.. -Igen -I/usr/include/nss -I/usr/include/nspr -I../../third_party/boringssl/src/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../third_party/khronos -I../../gpu -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/include/gpu -I../../third_party/skia/src/gpu -I../../third_party/libwebp -I../../testing/gtest/include -I../../third_party/WebKit -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/npapi -I../../third_party/npapi/bindings -I../../third_party/libjpeg_turbo -I../../third_party/iccjpeg -I../../third_party/libpng -I../../third_party/zlib -I../../third_party/ots/include -I../../third_party/qcms/src -I../../v8/include -I../../third_party/mojo/src -Igen/third_party/mojo/src -I../../third_party/webrtc/overrides -I../../third_party/libjingle/overrides -I../../third_party/libjingle/source -I../../testing/gtest/include -I../../third_party -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../third_party/protobuf -Igen -I../../third_party/mesa/src/include -I../../third_party/libyuv -I../../third_party/libyuv/include -I../../third_party/webrtc/overrides -I../../third_party -I../../third_party/webrtc/modules/interface -I../../third_party/webrtc/modules/audio_device/include -I../../third_party/webrtc/modules/audio_device/dummy -I../../third_party/libvpx/source/libvpx -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -m64 -march=x86-64 -funwind-tables -fPIC -pipe -pthread -B../../third_party/binutils/Linux_x64/Release/bin -fcolor-diagnostics -Wall -Wsign-compare -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-char-subscripts -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-reserved-user-defined-literal -Wno-inconsistent-missing-override -Wno-shift-negative-value -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -add-plugin -Xclang find-bad-constructs -Wheader-hygiene -Wstring-conversion -O0 -g2 -gsplit-dwarf -Wno-header-guard -Wno-incompatible-pointer-types -Wthread-safety -fno-threadsafe-statics -fvisibility-inlines-hidden -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=gnu++11 -fno-rtti -fno-exceptions -c ../../content/renderer/usb/web_usb_client_impl.cc -o obj/content/renderer/renderer/web_usb_client_impl.o
In file included from ../../content/renderer/usb/web_usb_client_impl.cc:14:
../../content/renderer/usb/web_usb_device_impl.h:17:10: fatal error: 'third_party/mojo/src/mojo/public/cpp/bindings/error_handler.h' file not found
#include "third_party/mojo/src/mojo/public/cpp/bindings/error_handler.h"

Original issue's description:
> Update mojo sdk to rev c02a28868825edfa57ab77947b8cb15e741c5598
>
> This updates lots of code which was missing an include of
> mojo/public/cpp/bindings/binding.h (which used to be included
> transitively from mojom-generated headers), and gets rid of
> references to mojo::ErrorHandler.
>
> BUG=None
> TBR=jam@chromium.org,ben@chromium.org
> TBR=mfoltz@chromium.org
> TBR=mek@chromium.org
> TBR=xhwang@chromium.org
> TBR=shess@chromium.org
>
> Committed: https://crrev.com/883a4e367a369e0882ead1a0850bab77028653fe [formerly 0b56a692d5c342a7093c361ff6ccb464c9d54947]
> Cr-Commit-Position: refs/heads/master@{#344957}

TBR=ben@chromium.org,jam@chromium.org,rockot@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=None

Review URL: https://codereview.chromium.org/1311613002

Cr-Commit-Position: refs/heads/master@{#344959}

Former-commit-id: b83114bc5c6ad0b6bfef4f0589bd49216630169c