Avoid class verification for SafeBrowsingResponse in onSafeBrowsingHit
This adds the utility class WebViewCompatUtilsForOMR1. It moves references to
SafeBrowsingResponseAdapter, which was added in OMR1, into a separate class.
On pre-OMR1 devices, this reduces log spam caused by a NoClassDefFoundError.
It also improves startup time.

Bug: 791099, 838702
Test: adb logcat | grep 'Failed resolution of'
Test: run cts -m CtsWebkitTestCases -t android.webkit.cts.WebViewClientTest#testOnSafeBrowsingHit
Change-Id: Icf52a70925be506f9b7c46ed592f5b64f43ab14c
Reviewed-on: https://chromium-review.googlesource.com/1081081
Reviewed-by: Nate Fischer <ntfschr@chromium.org>
Reviewed-by: Bo <boliu@chromium.org>
Commit-Queue: James Wallace-Lee <jamwalla@chromium.org>
Cr-Commit-Position: refs/heads/master@{#564706}
Former-commit-id: 8e1b1e2edf0209df0dd4ec0f479dc70379efcff7