vs2015: add missing include in snprintf header
Otherwise, it warns that

d:\src\cr2\src\third_party\ffmpeg\compat\msvcrt\snprintf.c(40): error C2220: warning treated as error - no 'object' file generated
d:\src\cr2\src\third_party\ffmpeg\compat\msvcrt\snprintf.c(40): warning C4013: 'avpriv_vsnprintf' undefined; assuming extern returning int

I guess this is new behaviour for .c files? Not sure.