Revert of Revert of clang/win: Fix a few warnings in targets not in chromium_builder_tests. (patchset #1 id:1 of https://codereview.chromium.org/519463003/)
Reason for revert:
Reland, wasn't the reason for the redness. (https://codereview.chromium.org/521703002/ was.)

Original issue's description:
> Revert of clang/win: Fix a few warnings in targets not in chromium_builder_tests. (patchset #3 id:40001 of https://codereview.chromium.org/526513002/)
>
> Reason for revert:
> Speculative, might have broken InstallerStateTest.InitializeTwice on XP: http://build.chromium.org/p/chromium.win/builders/XP%20Tests%20%281%29/builds/32481
>
> InstallerStateTest.InitializeTwice (run #1):
> [ RUN      ] InstallerStateTest.InitializeTwice
> c:\b\build\slave\win_builder\build\src\chrome\installer\util\installer_state_unittest.cc(639): error: Value of: wcsstr(installer_state.target_path().value().c_str(), BrowserDistribution::GetSpecificDistribution( BrowserDistribution::CHROME_BINARIES)-> GetInstallSubDir().c_str())
>   Actual: false
> Expected: true
> [  FAILED  ] InstallerStateTest.InitializeTwice (219 ms)
>
> InstallerStateTest.InitializeTwice (run #2):
> [ RUN      ] InstallerStateTest.InitializeTwice
> c:\b\build\slave\win_builder\build\src\chrome\installer\util\installer_state_unittest.cc(639): error: Value of: wcsstr(installer_state.target_path().value().c_str(), BrowserDistribution::GetSpecificDistribution( BrowserDistribution::CHROME_BINARIES)-> GetInstallSubDir().c_str())
>   Actual: false
> Expected: true
> [  FAILED  ] InstallerStateTest.InitializeTwice (109 ms)
>
>
> Original issue's description:
> > clang/win: Fix a few warnings in targets not in chromium_builder_tests.
> >
> > Also don't use "default" as a variable name, as it's a keyword.
> > Also fix a bug where a wstring was passed to %ls.
> >
> > No real behavior change.
> >
> > BUG=82385
> > R=hans@chromium.org
> > TBR=cpu, vitalybuka
> >
> > Committed to pending queue: https://chromium.googlesource.com/chromium/src/+/d7efa09
>
> TBR=hans@chromium.org,robertshield@chromium.org,gab@chromium.org,vitalybuka@chromium.org,cpu@chromium.org
> NOTREECHECKS=true
> NOTRY=true
> BUG=82385
>
> Committed: https://chromium.googlesource.com/chromium/src/+/280d25ce64ab9ee6789eefe3a62eb47c2b0a3222 [formerly dae20dafcfd3ccc439ccc5b3d5e21ad611d13c23]

TBR=hans@chromium.org,robertshield@chromium.org,gab@chromium.org,vitalybuka@chromium.org,cpu@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=82385

Review URL: https://codereview.chromium.org/525013003

Cr-Commit-Position: refs/heads/master@{#292818}

Former-commit-id: beb9fd30c68dd27606de80a2d017cddeeb799c3b