Revert 136728 - Disable precompiled headers when using 2010 on an Official build.
(Reverted due to build errors on Win Builder 2010 (dbg):
 NameError: name 'buildtype' is not defined while evaluating condition 'OS=="win"
 and MSVS_VERSION=="2010" and buildtype!="Official"' in src\build\all.gyp while
 trying to load src\build\all.gyp)

bug=127875
R=bradnelson

Review URL: https://chromiumcodereview.appspot.com/10392063

TBR=kerz@chromium.org
Review URL: https://chromiumcodereview.appspot.com/10387096

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@136735 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 75de721b7a3aa1b97189dac543487cf06080ec42