Revert "Implement iOS test sharding with multiple simulators on test_runner."
This reverts commit d4d487b074951c779c46bd06b3fef28496fdd9b0 [formerly e56e2bba7ccd18b1da071171909f326924eb0230].

Reason for revert: Breaking downstream device tests:

Using Xcode version 9.2 build 9C40b at /b/swarm_slave/w/ir/Xcode.app/Contents/Developer
Traceback (most recent call last):
  File "src/ios/build/bots/scripts/run.py", line 228, in <module>
    sys.exit(main())
  File "src/ios/build/bots/scripts/run.py", line 73, in main
    return 0 if tr.launch() else 1
  File "/b/swarm_slave/w/ir/src/ios/build/bots/scripts/test_runner.py", line 489, in launch
    result = self._run(cmd=cmd, shards=self.shards or 1)
AttributeError: 'DeviceTestRunner' object has no attribute 'shards'



Original change's description:
> Implement iOS test sharding with multiple simulators on test_runner.
> 
> Details in doc:
> https://docs.google.com/document/d/1QaAZgmYuEImL1wAYJQxPcbex-fPLVd3rx8oMMKIgZX8/edit#
> 
> Bug: 808267
> Cq-Include-Trybots: master.tryserver.chromium.mac:ios-simulator-cronet;master.tryserver.chromium.mac:ios-simulator-full-configs
> Change-Id: I55fc27fcf31120a7c9d39e8953f72a39dd6394a7
> Reviewed-on: https://chromium-review.googlesource.com/917309
> Commit-Queue: Menglu Huang <huangml@chromium.org>
> Reviewed-by: Sergey Berezin <sergeyberezin@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#537731}

TBR=sergeyberezin@chromium.org,huangml@chromium.org

Change-Id: I6a8e30d1fa5e9e1f5e2d7af3f620f967841cddcb
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 808267
Cq-Include-Trybots: master.tryserver.chromium.mac:ios-simulator-cronet;master.tryserver.chromium.mac:ios-simulator-full-configs
Reviewed-on: https://chromium-review.googlesource.com/926822
Reviewed-by: Justin Cohen <justincohen@chromium.org>
Commit-Queue: Justin Cohen <justincohen@chromium.org>
Cr-Commit-Position: refs/heads/master@{#537802}
Former-commit-id: bcf3583c7dacd391109250d58eb5c705efc78df1