Fix chromeos link error.
I started getting a link error after this revision landed:
crrev.com/241873

../../chrome/browser/chromeos/input_method/input_method_engine.cc:222:
error:
undefined reference to 'ui::KeycodeConverter::GetInstance()'
../../chrome/browser/chromeos/input_method/input_method_engine.cc:227:
error:
undefined reference to 'ui::KeycodeConverter::CodeToNativeKeycode(char
                const*)'
clang: error: linker command failed with exit code 1 (use -v to see
                invocation)

I fixed it by adding the missing dependency dom4_keycode_converter to
browser_chromeos.

BUG=326931
TEST=None
TBR=komatsu@chromium.org,shuchen@chromium.org,nona@chromium.org

Review URL: https://codereview.chromium.org/115693011

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@242300 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 04e19123d8957824ad1b166df019f2afbc774f96