Error checking to clarify SYSTEMROOT errors
Occasionally developers hit this cryptic error:

Exception: Environment x variable "SYSTEMROOT" required to be set to valid path

The error message is well intentioned but inevitably misleading. The problem is
rarely if ever caused by SYSTEMROOT not being set. In the most recent case it
was caused by the "SetEnv.cmd && set" command failing.

This change adds to bits of error checking - checking the error code of the
Popen command, and ensuring that the results coming in to
_ExtractImportantEnvironment are plausible. Both of these checks can detect this
particular error, and one or both of them should detect future problems.

R=scottmg@chromium.org

Review URL: https://codereview.chromium.org/1501673004 .