Revert "Simplify how the FSLP background rect is chosen."
This reverts commit 2b6b62c35a2475c50b910acadf191d73a8fcf090 [formerly 94b94d9e214e35a7fb922e229b279a769060a840].

Reason for revert: Appears to cause compile failures on https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/Mac/43669

../../ui/accelerated_widget_mac/ca_layer_tree_unittest_mac.mm:83:69: error: too few arguments to function call, expected 4, have 3
      superlayer, std::move(ca_layer_tree), properties->scale_factor);


Original change's description:
> Simplify how the FSLP background rect is chosen.
> 
> Before, the background size was reconstituted from the layer tree by
> taking the union of of black and video layers. Now, the actual size is
> plumbed through.
> 
> Change-Id: I0cb643b350ef7e4fca06e3bfd419e24861a2e3c6
> Reviewed-on: https://chromium-review.googlesource.com/1142962
> Reviewed-by: ccameron <ccameron@chromium.org>
> Commit-Queue: Sidney San Martín <sdy@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#576521}

TBR=ccameron@chromium.org,sdy@chromium.org

Change-Id: Ic60c1b3a4156165d63b077f0b066553f62ea93fe
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/1143940
Reviewed-by: Alex Moshchuk <alexmos@chromium.org>
Commit-Queue: Alex Moshchuk <alexmos@chromium.org>
Cr-Commit-Position: refs/heads/master@{#576534}
Former-commit-id: 2697c5f8a855e63591f3789280c70b3397db025c