Fix some build deps for //extensions/browser/api/guest_view, //extensions/common, //extensions/renderer.
//extensions/browser/api/guest_view: guest_view_internal_api.h includes extensions/browser/extension_function.h. The same problem exists for other subdirs of e/b/api/guest_view/. Cannot add //extensions/browser as a dep to //extensions/browser/api/guest_view because that would create a circular dependency.
Merge all those subdir files into //extensions/browser/api and specify all the public_deps of extension_function.h there. (This doesn't fix the underlying circular includes issue, but does clean things up a little bit.)

Example failure:
In file included from gen/extensions/browser/api/generated_api_registration.cc:9:
In file included from ../../extensions/browser/api/guest_view/web_view/web_view_internal_api.h:15:
In file included from ../../extensions/browser/guest_view/web_view/web_view_guest.h:14:
In file included from ../../components/guest_view/browser/guest_view.h:9:
In file included from ../../components/guest_view/browser/guest_view_base.h:15:
In file included from ../../components/zoom/zoom_observer.h:8:
In file included from ../../components/zoom/zoom_controller.h:16:
In file included from ../../content/public/browser/web_contents_observer.h:15:
In file included from ../../content/public/browser/navigation_controller.h:24:
In file included from ../../content/public/common/referrer.h:10:
In file included from ../../net/url_request/url_request.h:26:
In file included from ../../net/base/net_error_details.h:9:
In file included from ../../net/http/http_response_info.h:14:
In file included from ../../net/ssl/ssl_info.h:20:
In file included from ../../net/ssl/ssl_config.h:12:
In file included from ../../net/cert/x509_certificate.h:25:
../../third_party/boringssl/src/include/openssl/base.h:68:10: fatal error: 'openssl/opensslconf.h' file not found

//extensions/common: move //content/public/common to public_deps, as extensions/common/extension_messages.h includes files from there.
//extensions/renderer: add dep on //extensions/common, as many files in extensions/renderer include extensions/common/extension_messages.h.

Example failure for both of those:
In file included from ../../extensions/renderer/service_worker_request_sender.cc:9:
In file included from ../../extensions/common/extension_messages.h:16:
In file included from ../../content/public/common/common_param_traits.h:24:
In file included from ../../content/public/common/common_param_traits_macros.h:13:
In file included from ../../content/public/common/referrer.h:10:
In file included from ../../net/url_request/url_request.h:26:
In file included from ../../net/base/net_error_details.h:9:
In file included from ../../net/http/http_response_info.h:14:
In file included from ../../net/ssl/ssl_info.h:20:
In file included from ../../net/ssl/ssl_config.h:12:
In file included from ../../net/cert/x509_certificate.h:25:
../../third_party/boringssl/src/include/openssl/base.h:68:10: fatal error: 'openssl/opensslconf.h' file not found

BUG=711670

Review-Url: https://codereview.chromium.org/2812013003
Cr-Commit-Position: refs/heads/master@{#464802}

Former-commit-id: 2dbc3ed538ce6f3470af81dab163ca6e3c018bbc