Revert of Migrate Local Discovery from net::IPAddressNumber to net::IPAddress. (patchset #4 id:400001 of https://codereview.chromium.org/1534583002/ )
Reason for revert:
Doesn't build on the 'all' builders:

..\..\chrome\tools\service_discovery_sniffer\service_discovery_sniffer.cc(60,26)
:  error: invalid operands to binary expression ('const net::IPAddress' and
'net::IPAddressNumber' (aka 'vector<unsigned char>'))
  if (service.ip_address != net::IPAddressNumber()) {
      ~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~
..\..\chrome\tools\service_discovery_sniffer\service_discovery_sniffer.cc(61,34)
:  error: no matching function for call to 'IPAddressToString'
    printf("\tIP Address: %s\n", net::IPAddressToString(
                                 ^~~~~~~~~~~~~~~~~~~~~~
..\..\net/base/ip_address_number.h(51,24) :  note: candidate function not
viable: no known conversion from 'const net::IPAddress' to 'const
IPAddressNumber' (aka 'const vector<unsigned char>') for 1st argument
NET_EXPORT std::string IPAddressToString(const IPAddressNumber& addr);
                       ^
..\..\net/base/ip_address_number.h(41,24) :  note: candidate function not
viable: requires 2 arguments, but 1 was provided
NET_EXPORT std::string IPAddressToString(const uint8_t* address,

https://build.chromium.org/p/chromium/builders/Linux%20x64/builds/14840/steps/compile/logs/stdio

Original issue's description:
> This CL migrates Local Discovery from net::IPAddressNumber to net::IPAddress.
>
> This CL is part of the net::IPAddressNumber migration[1].
>
> BUG=496258
>
> [1] https://code.google.com/p/chromium/issues/detail?id=496258#c10
>
> Committed: https://crrev.com/7b124af27f0e5451bba2b1fe2659a567c3a7ebe4 [formerly aed54d71aad92c60a684f21e30e90bd2f4d9cc7f]
> Cr-Commit-Position: refs/heads/master@{#372550}

TBR=dgozman@chromium.org,eroman@chromium.org,vitalybuka@chromium.org,martijn@martijnc.be
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=496258

Review URL: https://codereview.chromium.org/1653573003

Cr-Commit-Position: refs/heads/master@{#372551}

Former-commit-id: ed6b7232e4c771c3136e2ade9339453a2969df5e