image: Mark move operations noexcept
Commit 201f4b9bb4 [formerly 97ad318786] ("Store account image in AccountInfo") broke the GCC build
when it added a gfx::Image to a class whose move constructor and assignment
operators are marked with noexcept:

    ../../components/signin/core/browser/account_info.cc:31:1: error: function ‘AccountInfo::AccountInfo(AccountInfo&&)’ defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification ‘’
     AccountInfo::AccountInfo(AccountInfo&& other) noexcept = default;
     ^~~~~~~~~~~
    ../../components/signin/core/browser/account_info.cc:35:14: error: function ‘AccountInfo& AccountInfo::operator=(AccountInfo&&)’ defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification ‘’
     AccountInfo& AccountInfo::operator=(AccountInfo&& other) noexcept = default;
                  ^~~~~~~~~~~

With GCC, having that noexcept marker requires all members to be marked with
noexcept themselves, and gfx::Image was missing it.

clang is fine because we pass -fno-exceptions and it disables the same error
there, while GCC continues to raise it (bug 843143 and its corresponding CL
have a longer discussion on this issue).

gfx::Image's move constructor and assignment operators do not do anything,
so we can just mark them noexcept too.

Bug: 819294
Change-Id: I799a29bc2dee9773c3ccabcdc5f4450767925b3c
Reviewed-on: https://chromium-review.googlesource.com/c/1379764
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Reviewed-by: Robert Sesek <rsesek@chromium.org>
Cr-Commit-Position: refs/heads/master@{#617133}
Former-commit-id: d47a661f6d429269feaec001451be492b96d1dd3