Fix undefined reference to xkbcommon
This patch fixes linking problem with undefined reference to xkbcommon
when xkbcommon is set to true with linux target on debug builds.

BUG=

Review-Url: https://codereview.chromium.org/2888493004
Cr-Commit-Position: refs/heads/master@{#477231}

Former-commit-id: c26fae7c6a56756e7df11d5f344ad878d17a0134