Fix chrome_java FindBugs errors found when switching to n sdk.
(with some simplification of CrashFileManager.java)

FindBugs reported the following issues:
NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE: Possible null pointer dereference due to return value of called method
  In class org.chromium.chrome.browser.crash.CrashFileManager
  In method org.chromium.chrome.browser.crash.CrashFileManager.getAllFilesSorted()
  Method invoked at CrashFileManager.java:[line 258]
  Known null at CrashFileManager.java:[line 257]
OBL_UNSATISFIED_OBLIGATION_EXCEPTION_EDGE: Method may fail to clean up stream or resource on checked exception
  In class org.chromium.chrome.browser.share.ShareHelper$3
  In method org.chromium.chrome.browser.share.ShareHelper$3.doInBackground(Void[])
  Reference type java.io.OutputStream
  Obligation to clean up resource created at ShareHelper.java:[line 398] is not discharged
  Path continues at ShareHelper.java:[line 399]
REC_CATCH_EXCEPTION: Exception is caught when Exception is not thrown
  In class org.chromium.chrome.test.ChromeActivityTestCaseBase
  In method org.chromium.chrome.test.ChromeActivityTestCaseBase.prepareUrlIntent(Intent, String)
  At ChromeActivityTestCaseBase.java:[line 486]
REC_CATCH_EXCEPTION: Exception is caught when Exception is not thrown
  In class org.chromium.chrome.test.ChromeActivityTestCaseBase
  In method org.chromium.chrome.test.ChromeActivityTestCaseBase.endPerfTest(String)
  At ChromeActivityTestCaseBase.java:[line 859]
OBL_UNSATISFIED_OBLIGATION_EXCEPTION_EDGE: Method may fail to clean up stream or resource on checked exception
  In class org.chromium.chrome.test.util.RenderUtils
  In method org.chromium.chrome.test.util.RenderUtils.saveBitmap(Bitmap, File)
  Reference type java.io.OutputStream
  Obligation to clean up resource created at RenderUtils.java:[line 179] is not discharged
  Path continues at RenderUtils.java:[line 180]
NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE: Possible null pointer dereference due to return value of called method
  In class org.chromium.chrome.browser.crash.CrashTestCase
  In method org.chromium.chrome.browser.crash.CrashTestCase.tearDown()
  Method invoked at CrashTestCase.java:[line 41]
  Known null at CrashTestCase.java:[line 41]
RV_RETURN_VALUE_IGNORED_NO_SIDE_EFFECT: Return value of method without side effect is ignored
  In class org.chromium.chrome.browser.customtabs.CustomTabFromChromeExternalNavigationTest
  In method org.chromium.chrome.browser.customtabs.CustomTabFromChromeExternalNavigationTest.testIntentWithRedirectToApp()
  Called method org.chromium.content.browser.test.util.Criteria.equals(Object, Callable)
  At CustomTabFromChromeExternalNavigationTest.java:[line 121]

BUG=623989

Review-Url: https://codereview.chromium.org/2416963005
Cr-Commit-Position: refs/heads/master@{#425384}

Former-commit-id: 90b4cf429c7e73e94f04a43bf573d98f03b80477