Revert of mojo: Convert gles2 to the new thunking system (https://codereview.chromium.org/413303002/)
Reason for revert:
Suspected for breaking official mac builder. Link:

http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Mac/builds/19071/

Error is:

FAILED:  /* snip */ python ../tools/isolate_driver.py check --isolated "../out/Release/mojo_apps_js_unittests.isolated" --isolate "mojo_apps_js_unittests.isolate" /*snip*/
Traceback (most recent call last):
  File "/Volumes/data/b/build/slave/google-chrome-rel-mac/build/src/tools/swarming_client/utils/file_path.py", line 488, in fix_native_path_case
    os.path.join(native_case_path, raw_part))
OSError: File /Volumes/data/b/build/slave/google-chrome-rel-mac/build/src/out/Release/libmojo_gles2.dylib doesn't exist


Original issue's description:
> mojo: Convert gles2 to the new thunking system.
> 
> BUG=386799
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=286365

TBR=viettrungluu@chromium.org,erg@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=386799

Review URL: https://codereview.chromium.org/425193002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@286387 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 1e66770e8a5d12de9c3772204866a0675be6e065