Revert "Refer to ui::ResourceBundle with namespace."
This reverts commit 4ae6ef8caea1ec0a90f7e855e796b4cd46114278 [formerly d7b19dd0be5d3c5538dfa71c9108139ea21ce00a].

Reason for revert: widespread compile failures, e.g.

../../ui/base/resource/resource_bundle_ios.mm:93:10: error: use of undeclared identifier 'sequence_checker_'
  DCHECK(sequence_checker_.CalledOnValidSequence());

Original change's description:
> Refer to ui::ResourceBundle with namespace.
> 
> ResourceBundle became ui::ResourceBundle in r72038 but many callers
> still refer to it without the namespace.
> 
> TBR=jamescook@chromium.org,treib@chromium.org
> 
> Change-Id: Ic0b7116beabc945ea4ac27cf4d65dc177274cc85
> Reviewed-on: https://chromium-review.googlesource.com/696139
> Commit-Queue: Lei Zhang <thestig@chromium.org>
> Reviewed-by: Sadrul Chowdhury <sadrul@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#510005}

TBR=jamescook@chromium.org,sadrul@chromium.org,ben@chromium.org,thestig@chromium.org,treib@chromium.org

Change-Id: Ib4428ba90efe811331e8190c9d22608d94d51cd6
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/727442
Reviewed-by: Trent Apted <tapted@chromium.org>
Commit-Queue: Trent Apted <tapted@chromium.org>
Cr-Commit-Position: refs/heads/master@{#510009}
Former-commit-id: 74e916d010cac59f80c48983348348a2d81ccb06