Revert "Add number of native relocations to .size file metadata"
This reverts commit 7eaf232e512983dd9c9e39ead2b0f5cd30a67df4 [formerly 26aa61db964554b516d6c667dbb970172a742460].

Reason for revert:

From bug  https://crbug.com/1019618
Error message:
~~~
  File "/b/s/w/ir/cache/builder/src/tools/binary_size/libsupersize/archive.py", line 1679, in _CountRelocationsFromElf
    relocations = re.search('RELCOUNT\s*(.+)', stdout).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
~~~

This is very likely caused by this CL. It prevents building the Clank
Official binaries, so reverting it speculatively

Original change's description:
> Add number of native relocations to .size file metadata
> 
> In furtherance of possibly putting a limit on additional native relocations
> added to the binary. A count of native relocations is now included in the
> metadata of the .size file.
> 
> Bug: 1012373
> Change-Id: Id3b4aa17d920f20435edffa5cda9ab8c0a309ade
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1879504
> Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> Auto-Submit: Mohamed Heikal <mheikal@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#709716}

TBR=agrieve@chromium.org,mheikal@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 1012373
Change-Id: I39638201732b09a2228ba9c0fc4050f75d38934c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1888934
Reviewed-by: Arthur Sonzogni <arthursonzogni@chromium.org>
Commit-Queue: Arthur Sonzogni <arthursonzogni@chromium.org>
Cr-Commit-Position: refs/heads/master@{#710717}

Former-commit-id: 936b64788e51fc5800a4f5bfc4f9167e3ef82abc