Disabled cc_poster_circle from rep perf test
Currently map fyi bots which run rendering_representative_perf_tests fail as a result of:

DevtoolsTargetCrashException: Devtools target crashed
(/b/s/w/ir/third_party/catapult/telemetry/telemetry/internal/backends/chrome_inspector/inspector_backend.py:539 _AddDebuggingInformation) Received a socket error in the browser connection and the tab no longer exists. The tab probably crashed.

While investigating this issue, this test can be disabled.
TBR=kbr@chromium.org

Bug: chromium:968119
Change-Id: I71fbb8f3e296203a9b556544ce2a8fc6345a9566
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1634385
Commit-Queue: Behdad Bakhshinategh <behdadb@chromium.org>
Reviewed-by: Caleb Rouleau <crouleau@chromium.org>
Reviewed-by: Jonathan Ross <jonross@chromium.org>
Cr-Commit-Position: refs/heads/master@{#664305}

Former-commit-id: 53855e57317e88d5ae19ac9964ffa17a4c965c49