Revert "Migrate assistant_volume_control.mojom to the new Mojo types"
This reverts commit 9d699d32c7290bb22a4a743f51ea57a60c7f3c5c [formerly b0784c2f3ec19a5f97051b03c1164c562697d29a].

It's breaking the chrome bots at compile time, for example:

https://ci.chromium.org/p/chrome/builders/ci/chromeos-amd64-generic-google-rel/7364

../../chromeos/services/assistant/platform/volume_control_impl.cc -o obj/chromeos/services/assistant/lib/volume_control_impl.o
../../chromeos/services/assistant/platform/volume_control_impl.cc:26:23: error: no member named 'ash' in namespace 'mojo'; did you mean simply 'ash'?
  mojo::PendingRemote<mojo::ash::mojom::VolumeObserver> observer;
                      ^~~~~~~~~
                      ash
gen/ash/public/mojom/constants.mojom.h:45:11: note: 'ash' declared here
namespace ash {
          ^
../../chromeos/services/assistant/platform/volume_control_impl.cc:103:3: error: use of undeclared identifier 'volume_control_ptr_'; did you mean 'volume_control_'?
  volume_control_ptr_->SetVolume(new_volume * 100.0, user_initiated);
  ^~~~~~~~~~~~~~~~~~~
  volume_control_
../../chromeos/services/assistant/platform/volume_control_impl.h:48:52: note: 'volume_control_' declared here
  mojo::Remote<ash::mojom::AssistantVolumeControl> volume_control_;
                                                   ^
../../chromeos/services/assistant/platform/volume_control_impl.cc:108:3: error: use of undeclared identifier 'volume_control_ptr_'; did you mean 'volume_control_'?
  volume_control_ptr_->SetMuted(muted);
  ^~~~~~~~~~~~~~~~~~~
  volume_control_
../../chromeos/services/assistant/platform/volume_control_impl.h:48:52: note: 'volume_control_' declared here
  mojo::Remote<ash::mojom::AssistantVolumeControl> volume_control_;

Original change's description:
> Migrate assistant_volume_control.mojom to the new Mojo types
> 
> Convert the implementation and all users of the
> ash::mojom::AssistantVolumeControl and VolumeObserver interfaces.
> 
> Bug: 955171
> Change-Id: Id4fd8931ecc2d29eaff0b25defb909bf0f491aca
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1795422
> Reviewed-by: Oksana Zhuravlova <oksamyt@chromium.org>
> Reviewed-by: Emily Stark <estark@chromium.org>
> Reviewed-by: Mitsuru Oshima <oshima@chromium.org>
> Commit-Queue: Henrique Ferreiro <hferreiro@igalia.com>
> Cr-Commit-Position: refs/heads/master@{#696007}

TBR=oshima@chromium.org,estark@chromium.org,hferreiro@igalia.com,oksamyt@chromium.org

Change-Id: I2eedac2da7539200787789a6436666b68bd067e8
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 955171
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1800516
Reviewed-by: Sorin Jianu <sorin@chromium.org>
Commit-Queue: Sorin Jianu <sorin@chromium.org>
Cr-Commit-Position: refs/heads/master@{#696045}

Former-commit-id: b97e0056e63cfa538d6d6a09c846fc8d183a1e8f