Revert of Reland Introduce mojo interface for collecting StackSamplingProfiler data (patchset #3 id:40001 of https://codereview.chromium.org/2253013008/ )
Reason for revert:
Appears to break compile on Mac: https://build.chromium.org/p/chromium/builders/Mac/builds/18700/

Error:
[10847/43976] LIBTOOL-STATIC obj/components/metrics/libcall_stacks.a
FAILED: obj/components/metrics/libcall_stacks.a
rm -f obj/components/metrics/libcall_stacks.a && TOOL_VERSION=1468839730 python ../../build/toolchain/mac/filter_libtool.py libtool -static  -o obj/components/metrics/libcall_stacks.a
error: /Applications/Xcode5.1.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no files specified

Original issue's description:
> Reland Introduce mojo interface for collecting StackSamplingProfiler data
>
> Adds interfaces, typemaps, and tests for collecting
> StackSamplingProfiler result types. The collection interface will be
> used to receive stack profiles from non-browser processes.
>
> This change was previously reverted in
> https://codereview.chromium.org/2264613002/ for introducing a skia
> dependency that broke cronet. The dependency has been removed and the
> new code has been split into independent targets.
>
> BUG=517958
>
> Committed: https://crrev.com/245a1498b75136c76b72dc8f5f3cd92e405287cd [formerly a6e65bb0cea385fc9fa82a5a1af4a5c3616e43e4]
> Cr-Commit-Position: refs/heads/master@{#413285}

TBR=sky@chromium.org,tsepez@chromium.org,isherman@chromium.org,wittman@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=517958

Review-Url: https://codereview.chromium.org/2267483002
Cr-Commit-Position: refs/heads/master@{#413293}

Former-commit-id: 0078b95aa4f7d5183924fd9113276e2dde312ca5