Fix android gn builds.
android_chromium_gn_compile_dbg is red failing to compile a cc file:
In file included from ../../device/vibration/android/vibration_jni_registrar.cc:9:0:
../../device/vibration/vibration_manager_impl_android.h:9:54: fatal error: device/vibration/vibration_manager.mojom.h: No such file or directory
 #include "device/vibration/vibration_manager.mojom.h"
                                                      ^

This was added with incorrect dependencies in
https://codereview.chromium.org/583663003/ two weeks ago, but
apparently no clobber happened since then.  The problem can be
reproduced locally by running

  rm -rf out/Debug
  gn gen out/Debug --args=is_debug=true\ os=\"android\"\ cpu_arch=\"arm\"\ use_goma=true\ goma_dir=\"$HOME/goma\"
  ninja -C out/Debug obj/device/vibration/android/android.vibration_jni_registrar.o

BUG=none
R=dcheng@chromium.org

Review URL: https://codereview.chromium.org/826593003

Cr-Commit-Position: refs/heads/master@{#309591}

Former-commit-id: fc38eeb37ff940849dd4e577b5e20b6598f38859