Revert "Reland: Android: Make Linker.java optimized out when use_chromium_linker=false"
This reverts commit f90a7cd31ffa6b939a6f823969f571617f825359 [formerly 206ddf5d9f91aa43dd086edc48c5b78be4aa7ab4].

Reason for revert: causes compile failure on android-archive-rel bot

Sample build: https://ci.chromium.org/p/chromium/builders/ci/android-archive-rel/4265

Sample log: https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8903288806742935296/+/steps/compile/0/stdout?format=raw
---
lib.java/android_webview/support_library/callback/callback_java.jar lib.java/android_webview/glue/glue.jar lib.java/android_webview/support_library/support_lib_glue_java.jar lib.java/build/android/buildhooks/build_hooks_android_impl_java.jar )
In ../../base/android/proguard/chromium_apk.flags:
  Ignoring option: -optimizationpasses
In ../../base/android/proguard/chromium_apk.flags:
  Ignoring option: -optimizations
Item boolean org.chromium.base.library_loader.LibraryLoaderConfig.areTestsEnabled() was not discarded.
boolean org.chromium.base.library_loader.LibraryLoaderConfig.areTestsEnabled()
|- is invoked from:
|  void org.chromium.content.app.ContentChildProcessServiceDelegate.onConnectionSetup(android.os.Bundle,java.util.List)
|- is reachable from:
|  org.chromium.content.app.ContentChildProcessServiceDelegate
|- is referenced in keep rule:
|  ../../base/android/proguard/chromium_code.flags:29:1

Item boolean org.chromium.base.library_loader.LibraryLoaderConfig.useChromiumLinker() was not discarded.
boolean org.chromium.base.library_loader.LibraryLoaderConfig.useChromiumLinker()
|- is invoked from:
|  void org.chromium.content.app.ContentChildProcessServiceDelegate.onConnectionSetup(android.os.Bundle,java.util.List)
|- is reachable from:
|  org.chromium.content.app.ContentChildProcessServiceDelegate
|- is referenced in keep rule:
|  ../../base/android/proguard/chromium_code.flags:29:1

Error: Discard checks failed.
Compilation failed
---


Original change's description:
> Reland: Android: Make Linker.java optimized out when use_chromium_linker=false
> 
> This reverts commit b97e1f2161969fb52ba8ce87ec5ebc48c7127b63 [formerly f6e84797fd5f0f524bc5b858cbed06d69485385e].
> 
> Reason for reland: Removed -checkdiscards.
> 
> TBR=agrieve # Trivial rename
> 
> Change-Id: I8924fb2ef16ba1a1704e33634c45471c56d84e21
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1780955
> Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> Reviewed-by: Sam Maier <smaier@chromium.org>
> Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#692947}

TBR=agrieve@chromium.org,lizeb@chromium.org,smaier@chromium.org

Change-Id: I99b31d3eb3ee630e5270fe9c9f747a9867d8e57e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1784019
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#692984}

Former-commit-id: 0ad8ca815dba77327cca78db959f88d81ab79267