Fix a lint issue with Desktop.java.
Currently, the lint warns at:
Error: Field requires API level 19 (current min is 14):
    android.view.View#SYSTEM_UI_FLAG_IMMERSIVE_STICKY [InlinedApi]

So we need to add @SuppressLint to suppress this lint error.

BUG=327768

Review URL: https://codereview.chromium.org/420393006

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@287466 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: e7d0d0f9ebc47fc277dd08b836e2bfa8fd902243