Revert "egl: Use official khronos version of eglext.h"
This reverts commit ca05dd731e6359df86148ad4d177e5b783432986 [formerly 17e5bbe6b2bf33a075db985bce9dcae991fd99e5].

Reason for revert: Compile failure
FAILED: obj/ui/gl/gl/gl_image_dxgi.obj 
ninja -t msvc -e environment.x64 -- C:\b\c\goma_client/gomacc.exe "c:\b\c\win_toolchain\vs_files\9bc7ccbf9f4bd50d4a3bd185e8ca94ff1618de0b\vc\tools\msvc\14.11.25503\bin\hostx64\x64/cl.exe" /nologo /showIncludes  @obj/ui/gl/gl/gl_image_dxgi.obj.rsp /c ../../ui/gl/gl_image_dxgi.cc /Foobj/ui/gl/gl/gl_image_dxgi.obj /Fd"obj/ui/gl/gl_cc.pdb"
../../ui/gl/gl_image_dxgi.cc(116): error C2065: 'EGL_D3D_TEXTURE_SUBRESOURCE_ID_ANGLE': undeclared identifier

on build:
https://build.chromium.org/p/chromium.win/builders/Win%20x64%20Builder%20%28dbg%29/builds/58992


Original change's description:
> egl: Use official khronos version of eglext.h
> 
> The remaining chromium-specific extension definitions aren't
> actually used from this header.
> 
> Bug: 769415
> Test: Compiles
> Cq-Include-Trybots: master.tryserver.chromium.android:android_optional_gpu_tests_rel;master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel
> Change-Id: I097c93e456e6e7c8b89f15dab61aed281e7ab8db
> Reviewed-on: https://chromium-review.googlesource.com/703734
> Reviewed-by: Kenneth Russell <kbr@chromium.org>
> Commit-Queue: Brian Anderson <brianderson@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#507524}

TBR=brianderson@chromium.org,kbr@chromium.org

Change-Id: I14baa9ee558aa92b057325cb4ec5d95a69575655
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 769415
Cq-Include-Trybots: master.tryserver.chromium.android:android_optional_gpu_tests_rel;master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel
Reviewed-on: https://chromium-review.googlesource.com/708054
Reviewed-by: Vincent Scheib <scheib@chromium.org>
Commit-Queue: Vincent Scheib <scheib@chromium.org>
Cr-Commit-Position: refs/heads/master@{#507535}
Former-commit-id: c5dff3b05d1cfa98e705130d2b037b6ef696ce6e