Revert "Refactor of Canvas2DLayerBridge resource model"
This reverts commit 0bd2c2d38ebed194b504734b0b0f640f2125b0a6 [formerly 1559b27f89ed89733c3c38b5eb06e27259224bab].

Reason for revert: Reverting in hopes of fixing android builder. https://build.chromium.org/p/chromium.webkit/builders/Android%20Builder/builds/124650 output:

../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.gold: error: obj/third_party/WebKit/Source/platform/unit_tests/Canvas2DLayerBridgeTest.o: multiple definition of 'blink::kSoftwareFallbackList'
../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.gold: obj/third_party/WebKit/Source/platform/platform/CanvasResourceProvider.o: previous definition here

...

Original change's description:
> Refactor of Canvas2DLayerBridge resource model
> 
> Transition to polymorphic RAII model. The purpose of this change
> is to improve the maintainability and extendability of the code.
> The GpuMemoryBuffer code is also getting a drive-by optimization
> that will eliminate unnecessary gpu commandbuffer flushing and
> verified sync tokens, which result in synchronous IPCs.
> 
> TBR=jwd@chromium.org
> 
> Bug: 773466
> Cq-Include-Trybots: master.tryserver.chromium.linux:linux_layout_tests_slimming_paint_v2
> Change-Id: Id0365d057e1e8c265f7d6457bfcfa211c40778f5
> Reviewed-on: https://chromium-review.googlesource.com/728340
> Commit-Queue: Justin Novosad <junov@chromium.org>
> Reviewed-by: Jesse Doherty <jwd@chromium.org>
> Reviewed-by: Justin Novosad <junov@chromium.org>
> Reviewed-by: Fernando Serboncini <fserb@chromium.org>
> Reviewed-by: Olivia Lai <xlai@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#514637}

TBR=jwd@chromium.org,junov@chromium.org,fserb@chromium.org,xlai@chromium.org

Change-Id: I23c79e41076c80544058bc6000fd15f1a5f92b7f
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 773466
Cq-Include-Trybots: master.tryserver.chromium.linux:linux_layout_tests_slimming_paint_v2
Reviewed-on: https://chromium-review.googlesource.com/757297
Reviewed-by: Scott Violet <sky@chromium.org>
Commit-Queue: Scott Violet <sky@chromium.org>
Cr-Commit-Position: refs/heads/master@{#514648}
Former-commit-id: 686d08a6616f09d3bbdd025f208b65de8e7cb5d9