cbuildbot_config: partially revert gs.PUBLIC_BASE_HTTPS_URL
This is apparently breaking the Chrome official builders.  We'll need to
sort this out, but at least get things working again.

python /b/build/slave/linux32_beta/build/src/webkit/tools/layout_tests/run_webkit_tests.py --help
Stopping Xvfb with pid 10005 ...
Xvfb pid file removed
Traceback (most recent call last):
  File "../../../scripts/slave/chromium/layout_test_wrapper.py", line 211, in <module>
    sys.exit(main())
  File "../../../scripts/slave/chromium/layout_test_wrapper.py", line 208, in main
    return layout_test(options, args)
  File "../../../scripts/slave/chromium/layout_test_wrapper.py", line 102, in layout_test
    command.extend(['--master-name', slave_utils.GetActiveMaster() or ''])
  File "/b/build/scripts/slave/bootstrap.py", line 66, in GetActiveMaster
    for slave in chromium_utils.RunSlavesCfg(path):
  File "/b/build/scripts/common/chromium_utils.py", line 1016, in RunSlavesCfg
    execfile(os.path.join(slaves_cfg), local_vars)
  File "/b/build/masters/master.chromiumos.tryserver/slaves.cfg", line 69, in <module>
    slaves = _AllocateSlaves()
  File "/b/build/masters/master.chromiumos.tryserver/slaves.cfg", line 52, in _AllocateSlaves
    configs = chromium_utils.GetCBuildbotConfigs()
  File "/b/build/scripts/common/chromium_utils.py", line 1066, in GetCBuildbotConfigs
    raise ExternalError('%s failed with error %s\n' % (config_path, error))
common.chromium_utils.ExternalError: /b/build/third_party/cbuildbot_chromite/buildbot/cbuildbot_config.py failed with error Traceback (most recent call last):
  File "/b/build/third_party/cbuildbot_chromite/buildbot/cbuildbot_config.py", line 18, in <module>
    from chromite.lib import gs
ImportError: No module named chromite.lib

BUG=None
TEST=`buildbot/cbuildbot_config_unittest.py` passes

Change-Id: I17327cb7dbbdec4ec00375749e0d27e7f65927f4
Reviewed-on: https://gerrit.chromium.org/gerrit/41593
Reviewed-by: David James <davidjames@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>