content: build fix about ContentDecryptorDelegate
clang complains it doesn't initialize const member, so this CL calls the
default constructor explicitly.

../../content/renderer/pepper/content_decryptor_delegate.cc:1070:32: error: default initialization of an object of const type 'const Decryptor::AudioFrames' (aka 'const list<scoped_refptr<media::AudioBuffer> >') without a user-provided default constructor
  const Decryptor::AudioFrames empty_frames;
                               ^
                                           {}
../../content/renderer/pepper/content_decryptor_delegate.cc:1282:41: error: default initialization of an object of const type 'const media::Decryptor::AudioFrames' (aka 'const list<scoped_refptr<media::AudioBuffer> >') without a user-provided default constructor
    const media::Decryptor::AudioFrames empty_frames;
                                        ^
                                                    {}
2 errors generated.

Review URL: https://codereview.chromium.org/1575833002

Cr-Commit-Position: refs/heads/master@{#368626}

Former-commit-id: c8c01a1673e799bfdc37b266acf68118cd759b08