Revert of Restrict use of two app-launching command line flags (patchset #8 id:140001 of https://codereview.chromium.org/2108853002/ )
Reason for revert:
Breaks official builds.
chrome/browser/extensions/unpacked_installer.cc:43:12: error: unused variable 'kUnpackedExtensionInsteadOfAppError'

Original issue's description:
> Restrict use of two app-launching command line flags
>
> Mitigate abuse of the load-and-launch-app and load-apps flags by
> disallowing loading of non-app extensions from these flags.
>
> For the official build, the flags no-op instead of showing an error popup
> to avoid giving users with hijacked shortcuts a bad time (the error
> message is shown then Chrome shuts down)
>
> BUG=624098
>
> Committed: https://crrev.com/10245e9f60680fccec307bbbcaaf3e8fa516b599 [formerly 93c60cd3ef5908984e173112dc09345bb5714036]
> Cr-Commit-Position: refs/heads/master@{#407824}

TBR=rdevlin.cronin@chromium.org,asargent@chromium.org,msw@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=624098

Review-Url: https://codereview.chromium.org/2180853004
Cr-Commit-Position: refs/heads/master@{#407830}

Former-commit-id: f50203526865893d6dc176e69f6a073116e5872b