Revert of Gate SK_FREETYPE_MINIMUM_RUNTIME_VERSION by use_system_freetype flag (patchset #2 id:20001 of https://codereview.chromium.org/2876853004/ )
Reason for revert:
This is causing a build failure on the Linux GPU FYI bots, likely because of a BUILD.gn error.

First failing build:
https://build.chromium.org/p/chromium.gpu.fyi/builders/GPU%20Linux%20Builder%20%28dbg%29/builds/81418

Error text:
FAILED: gles2_conform_test_windowless
python "../../build/toolchain/gcc_link_wrapper.py" --output="./gles2_conform_test_windowless" -- <snip> -lfreetype
./libskia.so: error: undefined reference to 'FT_Get_Var_Design_Coordinates'
./libskia.so: error: undefined reference to 'FT_Set_Default_Properties'

Original issue's description:
> Gate SK_FREETYPE_MINIMUM_RUNTIME_VERSION by use_system_freetype flag
>
> BUG=719345
> R=bungeman
>
> Review-Url: https://codereview.chromium.org/2876853004
> Cr-Commit-Position: refs/heads/master@{#473117}
> Committed: https://chromium.googlesource.com/chromium/src/+/3fe1a5154fd7b4f76426829a3f96d7e91deb0ce2 [formerly f677dc5c2d440d6e074a1d624e8a0b7a68371e08]

TBR=bungeman@chromium.org,fmalita@chromium.org,reed@chromium.org,drott@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=719345

Review-Url: https://codereview.chromium.org/2892163003
Cr-Commit-Position: refs/heads/master@{#473181}

Former-commit-id: b68636d648c64b4312aa050486b74cccd6ceece4