Revert "cros_mark_as_stable: push down cwd"
This reverts commit 393903d60b78fe8c2812acbc68ae25466225f8bf

It broke http://chromegw/i/chromium.chromiumos/builders/ChromiumOS%20%28amd64%29/builds/1935/steps/Uprev/logs/stdio

with 
INFO: 12:50:42: RunCommand: ['cros_sdk', '--', '../../chromite/buildbot/cros_mark_chrome_as_stable', u'--tracking_branch=master', '--boards=amd64-generic', '--force_revision=137208', 'spec'] in /b/cbuild.amd64/src/scripts
Traceback (most recent call last):

  File "../../chromite/buildbot/cros_mark_chrome_as_stable", line 516, in <module>
    main()

  File "../../chromite/buildbot/cros_mark_chrome_as_stable", line 497, in main
    tracking_branch)

TypeError: __init__() takes exactly 4 arguments (3 given)
Change-Id: I65a32027b562b8a245c02ea1b4a2260f42f37608
Reviewed-on: https://gerrit.chromium.org/gerrit/22730
Reviewed-by: Chris Sosa <sosa@chromium.org>
Reviewed-by: Bernie Thompson <bhthompson@chromium.org>
Tested-by: Peter Mayo <petermayo@chromium.org>