Revert of ServiceWorker: Use scheduler's default task queue for posting tasks on main thread (patchset #1 id:1 of https://codereview.chromium.org/958523002/)
Reason for revert:
Highly speculative revert after views_unittests broke on win7:

http://build.chromium.org/p/chromium.win/builders/Win7%20Tests%20%28dbg%29%281%29/builds/35660

c:\b\build\slave\win_builder__dbg_\build\src\ui\views\accessibility\native_view_accessibility_win_unittest.cc(190): error: Value of: infobar_accessible.IsSameObject(targets[0])

This patch does change task queuing, which makes it seem slightly more likely to break stuff than the others in the blamelist.

Original issue's description:
> ServiceWorker: Use scheduler's default task queue for posting tasks on main thread
>
> This fixes a task ordering bug between WebMessagePortChannelImpl and
> ServiceWorkerScriptContext. The former posts tasks via the Blink
> scheduler's default task queue, and the latter was using the MessageLoop
> directly. This patch makes tasks from service worker to the main thread
> go through the scheduler.
>
> BUG=460833
> TEST=http/tests/serviceworker/postmessage-msgport-to-client.html
>
> Committed: https://crrev.com/fb5a2a5c5604a359862be6fb554cce513af4abc8 [formerly a7fe515e3ca07e260b58ebf460f842601266ed87]
> Cr-Commit-Position: refs/heads/master@{#318022}

TBR=kinuko@chromium.org,skyostil@chromium.org,ksakamoto@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=460833

Review URL: https://codereview.chromium.org/954993002

Cr-Commit-Position: refs/heads/master@{#318040}

Former-commit-id: 64250e71c15dfe3576d8e4077e4dfb04f9382482