Remove -Wl,--no-undefined from default Android config
This is needed to enable in-tree libc++ on Android.  Otherwise, we'll see errors
that look like this:

FAILED: libwebviewchromium.so libwebviewchromium.so.TOC lib.unstripped/libwebviewchromium.so
ld.lld: error: undefined symbol: __cxa_guard_acquire
>>> referenced by aw_contents.cc:122 (../../android_webview/browser/aw_contents.cc:122)
>>>               obj/android_webview/common/aw_contents.o:(android_webview::(anonymous namespace)::g_locale())

The issue is that libc++abi is not a dependency of libc++ in asan builds --
instead it's exported from executables to prevent multiple definitions of
libc++abi symbols.

-Wl,-z,-defs is normally added only for non-sanitizer builds [1] on Linux,
Android, and Fuchsia.  But the Android-specific config adds -Wl,--no-undefined
(which is identical to -Wl,-z,-defs) all the time.

The solution is to simply remove the Android-specific -Wl,--no-undefined and
rely on the -Wl,-z,defs added by //build/config/compiler:compiler.

[1] https://cs.chromium.org/chromium/src/build/config/compiler/BUILD.gn?rcl=940ea69733b5b2376fdcd2aeec446abef9b0d7a1 [formerly c6dd1fda26ff8dddd92ba7830e8696afe3b031f5]&l=398

BUG=916962
R=thakis

Change-Id: If6887c96a0eaeeac3c831511e3e4519dac3532b5
Reviewed-on: https://chromium-review.googlesource.com/c/1387399
Reviewed-by: Nico Weber <thakis@chromium.org>
Commit-Queue: Thomas Anderson <thomasanderson@chromium.org>
Cr-Commit-Position: refs/heads/master@{#618335}
Former-commit-id: acb62c29f149da5137ccf33762e16e53a47c511f