Revert "[ios] Creates SigninPromoView UIRefresh styling."
This reverts commit e9e1bb5dea466d56346cef662ffb5427a83853b0 [formerly add11c4c0f952690a953202c709a06f3cc11784c].

Reason for revert: Breaks egtests when UIRefresh is disabled.

Test Case '-[RecentTabsTableTestCase testRecentTabSigninPromoReloaded]' started.
../../ios/chrome/browser/ui/authentication/signin_earlgrey_utils.mm:39: error: -[RecentTabsTableTestCase testRecentTabSigninPromoReloaded] : Exception: NoMatchingElementException
Exception Name: NoMatchingElementException
Exception Reason: Cannot find UI Element.
Exception with Assertion: {
  "Assertion Criteria":  "assertWithMatcher:isNotNil",
  "Element Matcher":  "((respondsToSelector(accessibilityIdentifier) && accessibilityID('kSigninPromoPrimaryButtonId')) && matcherForSufficientlyVisible(>=0.750000))",
  "Recovery Suggestion":  "Check if the element exists in the UI hierarchy printed below. If it exists, adjust the matcher so that it accurately matches element."
}
Exception Details: Error Trace: [
  {
    "Description":  "Interaction cannot continue because the desired element was not found.",
    "Error Domain":  "com.google.earlgrey.ElementInteractionErrorDomain",
    "Error Code":  "0",
    "File Name":  "GREYElementInteraction.m",
    "Function Name":  "-[GREYElementInteraction matchedElementsWithTimeout:error:]",
    "Line":  "124",
    "TestCase Class":  "RecentTabsTableTestCase",
    "TestCase Method":  "testRecentTabSigninPromoReloaded"
  }
]

Original change's description:
> [ios] Creates SigninPromoView UIRefresh styling.
> 
> - Updates SigninPromoView to support a new UI Layout based on UIRefresh Phase 1 flag and a new
> flag received on init.
> - Some minor refactoring to stop calling self on init in SigninPromoView.
> 
> Screenshots:
> https://drive.google.com/open?id=1FnR436FEX9_3GwFbIIrJsQ8qHZOdqJpl
> https://drive.google.com/open?id=1__aPHb1ye3WkiHKHJp9kIyJ6hhABq1Y6
> https://drive.google.com/open?id=1ibjz3nnXHBrO_akJm4e9tgghpD85f3u0
> https://drive.google.com/open?id=1dCVkiMW1IMQjWkxcegVxi8r1PLh5ZCqM
> 
> Bug: 805188
> Cq-Include-Trybots: luci.chromium.try:ios-simulator-full-configs;master.tryserver.chromium.mac:ios-simulator-cronet
> Change-Id: I1268388da06c57eb9c1610c3547314929bb8c107
> Reviewed-on: https://chromium-review.googlesource.com/1107216
> Commit-Queue: Sergio Collazos <sczs@chromium.org>
> Reviewed-by: edchin <edchin@chromium.org>
> Reviewed-by: Jérôme Lebel <jlebel@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#570864}

TBR=rohitrao@chromium.org,jlebel@chromium.org,edchin@chromium.org,sczs@chromium.org

Change-Id: I2bf65f4e8848786eb3d60c2db4adb768eed3692b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 805188
Cq-Include-Trybots: luci.chromium.try:ios-simulator-full-configs;master.tryserver.chromium.mac:ios-simulator-cronet
Reviewed-on: https://chromium-review.googlesource.com/1118178
Reviewed-by: Rohit Rao <rohitrao@chromium.org>
Commit-Queue: Rohit Rao <rohitrao@chromium.org>
Cr-Commit-Position: refs/heads/master@{#571058}
Former-commit-id: 8a61b90cb0b8fd3ac69a97bc642fa1e2179bac44