Revert "Revert "Refactor CSSPropertyDescriptor structure, rename it to CSSPropertyAPI.""
This reverts commit b152ece694f1c0df5811e9af1f73f56eec9d79ef [formerly dfb913febffa8232f3a0009e0ef729d2b4050ca5].

Reason for revert: Actual breaking CL was https://chromium-review.googlesource.com/c/603029

Original change's description:
> Revert "Refactor CSSPropertyDescriptor structure, rename it to CSSPropertyAPI."
> 
> This reverts commit 024e32d47ab5a5eabd295ede18038569f29f2785 [formerly cfd7e50f2eb11851dc562c826cba85a028280618].
> 
> Reason for revert: Does not compile.
> 
> gen/blink/core/css/properties/CSSPropertyAPI.cpp:245:33: error: unused variable 'base_api' [-Werror,-Wunused-const-variable]
> static constexpr CSSPropertyAPI base_api;
>                                 ^
> https://build.chromium.org/p/chromium.gpu/builders/GPU%20Mac%20Builder/builds/98526
> 
> Original change's description:
> > Refactor CSSPropertyDescriptor structure, rename it to CSSPropertyAPI.
> > 
> > Design doc (with benchmarks!):
> > https://docs.google.com/document/d/1uwS_TT8VBWSQNYMnOggwqcnv6YU85FIFvD_egxPSn6o/edit
> > 
> > This CL changes the current "struct that contains 
> > function-pointer-or-nulls" CSSPropertyDescriptor design to 
> > instead use virtual function dispatch andstatic constexpr for 
> > returning a pointer to a CSSPropertyAPI or subclass.
> > 
> > 
> > This makes the call sites cleaner, as since there cannot be null 
> > function pointers any more, this allows us to write:
> > 
> > CSSPropertyAPI::Get(property_id).ParseSingleValue(...);
> > 
> > and avoid the if statement that we would require with the current
> > implementation:
> > 
> > CSSPropertyDescriptor& d = CSSPropertyDescriptor::Get(property_id);
> > if (d.ParseSingleValue)
> >   d.ParseSingleValue(...);
> > 
> > My benchmarks (details in the linked doc) show no speed penalty for 
> > doing this for getting an API, or for calling functions on it (in 
> > fact, it's probably faster). Inspecting the assembly generated from 
> > the benchmarks also shows that the use of constexpr correctly 
> > causes the compiler to avoid allocating any memory for instances of 
> > CSSPropertyAPI or subclasses, so function calls are still just 
> > dereferencing straight into the vtable of the CSSPropertyAPI 
> > subclass.
> > 
> > 
> > Notes:
> > - CSSPropertyAPI.h/.cpp and CSSPropertyAPICustom.cpp replace
> > CSSPropertyDescriptor.
> > - To avoid CSSPropertyAPICustom.cpp from getting too big, I created a
> > temporary "CSSPropertyAPICustomHelper" containing the not yet
> > ribbonized helper functions it requires.
> > 
> > file moves undetected by gerrit:
> > - The generator css_property_apis.py was split into two files:
> > make_css_property_api.py, and make_css_property_api_headers.py.
> > - CSSPropertyAPIFiles.h.tmpl was renamed to CSSPropertyAPIHeaders.h.tmpl
> > 
> > 
> > Gist showing curated diff of generated files:
> > CSSPropertyAPI.cpp
> > CSSPropertyAPIAlignItems.h // A longhand API header
> > CSSPropertyDescriptor.cpp
> > CSSPropertyDescriptor.h
> > CSSShorthandPropertyAPIAnimation.h // A shorthand API header
> > https://gist.github.com/wilddamon/2261ef381b648f9fe3cf9ed8ac037cd3/revisions
> > 
> > Gist showing diff between CSSPropertyAPI.cpp and the old
> > CSSPropertyDescriptor.cpp:
> > https://gist.github.com/wilddamon/ee1afa93637b85b4d1291b8a1d985b16/revisions
> > 
> > Gist showing diff between CSSPropertyParser.cpp and
> > CSSPropertyAPICustomHelper.cpp:
> > https://gist.github.com/wilddamon/9e81c157f98ff1dbb68d43a79f89fe9c/revisions
> > 
> > Gist showing diff between make_css_property_apis.py and
> > make_css_property_api.py:
> > https://gist.github.com/wilddamon/4d4ee2c2223c9b5ab7c857ab31aa68ec/revisions
> > 
> > Gist showing diff between make_css_property_apis.py and
> > make_css_property_api_headers.py
> > https://gist.github.com/wilddamon/08443f2980054866ebeef972b00d1746/revisions
> > 
> > Bug: 545324
> > Change-Id: Ie5465c02faa010094f78821c024f87c231bd2264
> > Reviewed-on: https://chromium-review.googlesource.com/589469
> > Commit-Queue: meade_UTC10 <meade@chromium.org>
> > Reviewed-by: Renée Wright <rjwright@chromium.org>
> > Reviewed-by: Bugs Nash <bugsnash@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#492265}
> 
> TBR=rjwright@chromium.org,meade@chromium.org,jiameng@chromium.org,bugsnash@chromium.org
> 
> Change-Id: Iee795ea0afa4e45903c8485ed17bfb9b4a6432e5
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 545324
> Reviewed-on: https://chromium-review.googlesource.com/602430
> Reviewed-by: vitaliii <vitaliii@chromium.org>
> Commit-Queue: vitaliii <vitaliii@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#492275}

TBR=rjwright@chromium.org,meade@chromium.org,vitaliii@chromium.org,jiameng@chromium.org,bugsnash@chromium.org

Change-Id: Ia06ce2272bd9fc43b49152018e1a1880c6b97e63
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 545324
Reviewed-on: https://chromium-review.googlesource.com/603010
Reviewed-by: meade_UTC10 <meade@chromium.org>
Commit-Queue: meade_UTC10 <meade@chromium.org>
Cr-Commit-Position: refs/heads/master@{#492279}
Former-commit-id: e38bd1e31c4c1394bae7ba113b23b1315e3be861