Revert "Remove ChrootPaths class"
This reverts commit 31fd5803ed957a8152728208c770e10580f8c7d8.

Reason for revert: Breaks a bunch of unittests:

ERROR: [chromite.service.sdk_unittest] CreateTest.testCreate
AttributeError: 'CreateArguments' object has no attribute 'paths'

FAIL: [chromite.api.controller.sdk_unittest] SdkCreateTest.testTrueArguments
AssertionError: Expected call: CreateArguments(replace=False, bootstrap=True, use_image=False, paths=<ANY>)
Actual call: CreateArguments(replace=False, bootstrap=True, use_image=False, cache_dir='', chroot_path='')

Original change's description:
> Remove ChrootPaths class
> 
> This class only had two fields that can easily just be passed as args.
> 
> BUG=None
> TEST=None
> 
> Change-Id: I41716b009975cd01479949adca02d802d9614aaf
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/2044991
> Tested-by: Chris McDonald <cjmcdonald@chromium.org>
> Commit-Queue: Chris McDonald <cjmcdonald@chromium.org>
> Reviewed-by: Alex Klein <saklein@chromium.org>

Change-Id: Ie1761dbb875dd089e70259cda7f3f5d4e0400cf0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/2049184
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>