Reviewed by Richard
	Fix for this bug:

	Radar 3260323 (Some links at nike.com cause assertion failure
	(connectionDidFinishLoading sent after cancel))

	Added a flag which is set when a load is cancelled. This flag prevents
	bad behvior when loads that finish cause the load itself to be
	cancelled (which could happen with a javascript that changes the
	window location). This is used to prevent both the body of
	cancelWithError: and the body of connectionDidFinishLoading: running
	for a single delegate. Cancelling wins.

        * WebView.subproj/WebBaseResourceHandleDelegate.h:
        * WebView.subproj/WebBaseResourceHandleDelegate.m:
        (-[WebBaseResourceHandleDelegate connectionDidFinishLoading:]):
        (-[WebBaseResourceHandleDelegate cancelWithError:]):


git-svn-id: svn://svn.chromium.org/blink/trunk@4443 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: f171125aae9b519489af5319caf53cf27b906548