Revert 151955 "Avoid DEFINE_STATIC_LOCAL for Strings."
Broke android build:
http://build.chromium.org/p/chromium.webkit/builders/Android%20Builder%20%28dbg%29/builds/12850

FAILED: /b/build/goma/gomacc
/mnt/data/b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/ndk//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++
-MMD -MF
obj/third_party/WebKit/Source/core/accessibility/webcore_remaining.AccessibilityListBox.o.d
-D_FILE_OFFSET_BITS=64 -DUSE_LINUX_BREAKPAD -DNO_TCMALLOC -DDISABLE_NACL
-DCHROMIUM_BUILD -DUSE_LIBJPEG_TURBO=1 -DENABLE_WEBRTC=1
-DUSE_PROPRIETARY_CODECS -DENABLE_GPU=1 -DUSE_OPENSSL=1 -DENABLE_EGLIMAGE=1
-DENABLE_AUTOFILL_DIALOG=1 -DENABLE_LANGUAGE_DETECTION=1
'-DWEBCORE_NAVIGATOR_VENDOR="Google Inc."' -DWEBKIT_IMPLEMENTATION=1
-DENABLE_3D_PLUGIN=1 -DENABLE_BATTERY_STATUS=0 -DENABLE_CANVAS_USES_MAILBOX=0
-DENABLE_CSS3_TEXT=0 -DENABLE_CSS_DEVICE_ADAPTATION=0 -DENABLE_CSS_EXCLUSIONS=1
-DENABLE_CSS_REGIONS=1 -DENABLE_CUSTOM_SCHEME_HANDLER=0
-DENABLE_ENCRYPTED_MEDIA_V2=1 -DENABLE_GRAPHICS_CONTEXT_ANNOTATIONS=0
-DENABLE_SVG_FONTS=1 -DENABLE_TOUCH_ICON_LOADING=1 -DENABLE_XHR_TIMEOUT=0
-DWTF_USE_CONCATENATED_IMPULSE_RESPONSES=1 -DENABLE_CALENDAR_PICKER=0
-DENABLE_FAST_MOBILE_SCROLLING=1 -DENABLE_INPUT_SPEECH=0
-DENABLE_LEGACY_NOTIFICATIONS=0 -DENABLE_MEDIA_CAPTURE=1
-DENABLE_NOTIFICATIONS=0 -DENABLE_ORIENTATION_EVENTS=1 -DENABLE_PRINTING=0
-DENABLE_NAVIGATOR_CONTENT_UTILS=0 -DWTF_USE_NATIVE_FULLSCREEN_VIDEO=1
-DENABLE_8BIT_TEXTRUN=1 -DWTF_USE_WEBAUDIO_OPENMAX_DL_FFT=1
-DENABLE_WEB_AUDIO=1 -DENABLE_OPENTYPE_VERTICAL=1 -DWTF_USE_HARFBUZZ=1
-DU_USING_ICU_NAMESPACE=0 -DU_STATIC_IMPLEMENTATION -DSK_BUILD_NO_IMAGE_ENCODE
-DSK_DEFERRED_CANVAS_USES_GPIPE=1
'-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"'
-DGR_AGGRESSIVE_SHADER_OPTS=1 -DSK_ENABLE_INST_COUNT=0 -DSK_USE_POSIX_THREADS
-DSK_BUILD_FOR_ANDROID -DHAVE_ENDIAN_H -DCHROME_PNG_WRITE_SUPPORT
-DPNG_USER_CONFIG -DLIBXML_STATIC -DLIBXSLT_STATIC -DANDROID -D__GNU_SOURCE=1
-DUSE_STLPORT=1 -D_STLP_USE_PTR_SPECIALIZATIONS=1 '-DCHROME_BUILD_ID=""'
-DHAVE_SYS_UIO_H -DDYNAMIC_ANNOTATIONS_ENABLED=1
-DWTF_USE_DYNAMIC_ANNOTATIONS=1 -D_DEBUG -I../../third_party/icu/public/common
-I../../third_party/icu/public/i18n -I../../third_party/khronos -I../../gpu
-I../.. -I../../third_party -I../../third_party/WebKit
-I../../third_party/WebKit/Source -Igen/webkit -Igen/webkit/bindings
-I../../third_party/openmax_dl -I../../third_party/angle/include/GLSLANG
-I../../skia/config -I../../third_party/skia/src/core
-I../../third_party/skia/include/config -I../../third_party/skia/include/core
-I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf
-I../../third_party/skia/include/gpu -I../../third_party/skia/include/gpu/gl
-I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe
-I../../third_party/skia/include/ports -I../../third_party/skia/include/utils
-I../../skia/ext -I../../third_party/iccjpeg
-I../../third_party/leveldatabase/src/include
-I../../third_party/leveldatabase/src -I../../third_party/leveldatabase
-I../../third_party/libwebp -I../../third_party/libpng
-I../../third_party/libxml/linux/include -I../../third_party/libxml/src/include
-I../../third_party/libxslt -I../../third_party/npapi
-I../../third_party/npapi/bindings -I../../third_party/ots/include
-I../../third_party/qcms/src -I../../third_party/sqlite
-I../../third_party/zlib -I../../v8/include -I../../third_party/libjpeg_turbo
-fstack-protector --param=ssp-buffer-size=4 -fno-exceptions
-fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers
-fvisibility=hidden -pipe -fPIC -fno-strict-aliasing -Wno-format -march=armv7-a
-mtune=cortex-a8 -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb -fno-tree-sra
-fuse-ld=gold -Wno-psabi -mthumb-interwork -ffunction-sections -funwind-tables
-g -fstack-protector -fno-short-enums -finline-limit=64 -Wa,--noexecstack
--sysroot=/mnt/data/b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/ndk//platforms/android-14/arch-arm
-I/mnt/data/b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/ndk//sources/cxx-stl/stlport/stlport
-Os -g -fomit-frame-pointer -fdata-sections -ffunction-sections -g1 -fno-rtti
-fno-threadsafe-statics -fvisibility-inlines-hidden -Wno-c++0x-compat
-Wno-deprecated -Wno-abi  -c
../../third_party/WebKit/Source/core/accessibility/AccessibilityListBox.cpp -o
obj/third_party/WebKit/Source/core/accessibility/webcore_remaining.AccessibilityListBox.o
In file included from
../../third_party/WebKit/Source/core/accessibility/AccessibilityNodeObject.h:32:0,
                   from
                   ../../third_party/WebKit/Source/core/accessibility/AccessibilityRenderObject.h:32,
                                    from
                                    ../../third_party/WebKit/Source/core/accessibility/AccessibilityListBox.h:32,
                                                     from
                                                     ../../third_party/WebKit/Source/core/accessibility/AccessibilityListBox.cpp:30:
                                                     ../../third_party/WebKit/Source/core/accessibility/AccessibilityObject.h:663:22:error:
                                                     prototype for 'const
                                                     WTF::String&
                                                     WebCore::AccessibilityObject::actionVerb()
  const' does not match any in class 'WebCore::AccessibilityObject'
  ../../third_party/WebKit/Source/core/accessibility/AccessibilityObject.h:438:20:error:
  candidate is: virtual WTF::String WebCore::AccessibilityObject::actionVerb()
  const


  etc
> Avoid DEFINE_STATIC_LOCAL for Strings.
> 
> This pattern saved memory allocation at the expense of bloating
> code size. Prefer small code size when these aren't bottlenecks.
> 
> Saves 72 bytes per string, for a total of 2448 bytes
> for this change.
> 
> BUG=247082
> 
> Review URL: https://chromiumcodereview.appspot.com/16457004

TBR=dmazzoni@chromium.org

Review URL: https://codereview.chromium.org/16503005

git-svn-id: svn://svn.chromium.org/blink/trunk@151957 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: 41383183971b55ce3eb33be30dbb079554239aa7