Android: Teach resource_sizes.py about ".part.end" section
.part.end is a new section introduced by "partitioned libraries", a part
of DFMS. It's a NOBITS section, so needs to be counted the same as .bss.

This fixes some CQ runs failing due to:
AssertionError: Padding was: $SOME_SMALL_NEGATIVE_NUMBER

Bug: 1002085
Change-Id: I49e892d22f8888fd991202d99bc67e342c06db52
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1791999
Auto-Submit: Andrew Grieve <agrieve@chromium.org>
Reviewed-by: Christopher Grant <cjgrant@chromium.org>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/master@{#694841}

Former-commit-id: 573e52741bfd0c51e55fcd9ae7c4c9759f4c076a