Revert of Move RenderingTest initialization back into SetUp. (patchset #1 id:1 of https://codereview.chromium.org/1649813003/ )
Reason for revert:
This broke the build when Oilpan is disabled.

../../third_party/WebKit/Source/core/layout/LayoutTestHelper.cpp:37:77: error: no viable conversion from 'WTF::OwnPtr<FrameLoaderClient>' to 'WTF::PassOwnPtr<FrameLoaderClient>'
    m_pageHolder = DummyPageHolder::create(IntSize(800, 600), &pageClients, m_frameLoaderClient, settingOverrider());
                                                                            ^~~~~~~~~~~~~~~~~~~

Original issue's description:
> Move RenderingTest initialization back into SetUp.
>
> In http://crrev.com/362320, the initialization of m_pageHolder was moved into
> the ctor.  Unfortunately, settingOverrider() is a virtual method, so it cannot
> be correctly called from the ctor (it will not dispatch to the subclass).
>
> Committed: https://crrev.com/bf6f54ee249cf7e4d39e8f714a76a7c7c0fff6fb [formerly 0808979ecf83a8ad64d77f94c1b9f409c0d62b30]
> Cr-Commit-Position: refs/heads/master@{#372720}

TBR=chrishtr@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/1654233002

Cr-Commit-Position: refs/heads/master@{#372744}

Former-commit-id: 125e7c8682fc5b8f707194f6af66be4abbe13826