Revert of GpuMemoryBuffer interface change: Map(**) to Map() and memory(plane); stride(plane) (patchset #5 id:610001 of https://codereview.chromium.org/1401183003/ )
Reason for revert:
Broke Win x64 GN compilation:

e:\b\build\slave\win_x64_gn\build\src\components\mus\gles2\mojo_gpu_memory_buffer.cc(78) :error C2220: warning treated as error - no 'object' file generated
e:\b\build\slave\win_x64_gn\build\src\components\mus\gles2\mojo_gpu_memory_buffer.cc(78) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data

Original issue's description:
> GpuMemoryBuffer interface change: Map(**) --> Map() + memory(plane); GetStride(*) --> stride(plane)
>
> And at the same time clean up/simplify/homogeneise
> uses of those APIs.
>
> buffer_format_util.cc:RowSizeForBufferFormatChecked()
> is only used in unittests and internally to the file, this CL
> restricts it to the .cc file. Also a function there is only
> used in test --> added ForTesting() suffix.
>
> BUG=542225
> CQ_INCLUDE_TRYBOTS=tryserver.blink:linux_blink_rel
>
> Committed: https://crrev.com/bc747afe4d9a5317f3837457daba5c26702dacef [formerly a11ca23b4ae411b4dc6cd8ff755e366680e80776]
> Cr-Commit-Position: refs/heads/master@{#355396}

TBR=reveman@chromium.org,avi@chromium.org,bajones@chromium.org,dalecurtis@chromium.org,fsamuel@chromium.org,miu@chromium.org,mcasas@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=542225

Review URL: https://codereview.chromium.org/1409163003

Cr-Commit-Position: refs/heads/master@{#355511}

Former-commit-id: 5f26dd6169a6b113ddfb66f6c1c8ed74a259e269