Revert of Certificate Transparency: Require diverse Signed Certificate Timestamps (patchset #9 id:160001 of https://codereview.chromium.org/1326803002/ )
Reason for revert:
Broke LInux GN build:
http://build.chromium.org/p/chromium.linux/builders/Linux%20GN%20Clobber/builds/6084/steps/compile/logs/stdio

FAILED: ../../native_client/toolchain/linux_x86/pnacl_newlib/bin/pnacl-clang++ -Wl,--fatal-warnings -Wl,-O1 -Wl,--gc-sections -Wl,--as-needed -o newlib_pnacl/remoting_client_plugin_newlib.pexe.debug -Wl,--start-group @newlib_pnacl/remoting_client_plugin_newlib.pexe.debug.rsp  -Wl,--end-group    && ../../native_client/toolchain/linux_x86/pnacl_newlib/bin/pnacl-finalize newlib_pnacl/remoting_client_plugin_newlib.pexe.debug -o newlib_pnacl/remoting_client_plugin_newlib.pexe
newlib_pnacl/obj/net/net/cert_policy_enforcer.o: error: undefined reference to 'net::ct::IsLogOperatedByGoogle(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >)'
ninja: build stopped: subcommand failed.

Original issue's description:
> Certificate Transparency: Require diverse Signed Certificate Timestamps
>
> Update the certificate policy enforcement code to catch up with the
> requirement of one SCT from a Google-operated log and one from
> non-Google operated log, see discussion in:
>
> https://groups.google.com/a/chromium.org/forum/#!topic/ct-policy/Udh1ddi1MrY
>
> BUG=425174
>
> Committed: https://crrev.com/3323059846223c9b6619fe157254ea8f735229af [formerly 5eccb2ca1d7420c5420646177b2ceb8bf9c2bfa3]
> Cr-Commit-Position: refs/heads/master@{#350810}

TBR=rsleevi@chromium.org,eranm@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=425174

Review URL: https://codereview.chromium.org/1368833003

Cr-Commit-Position: refs/heads/master@{#350822}

Former-commit-id: 82e736fc73dde62583d39ae1cbbf1f91eeca054b