Revert "Use HarfBuzz on windows"
Looks like it breaks build on Win x64 Release build (chromium).

http://build.chromium.org/p/tryserver.chromium/builders/win_x64_rel/builds/54241/steps/compile/logs/stdio#error1

FAILED: ninja -t msvc -e environment.x64 -- E:\b\build\goma\gomacc.exe
"C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\amd64\cl.exe"
/nologo /showIncludes /FC
@obj\third_party\harfbuzz-ng\src\harfbuzz-ng.hb-fallback-shape.obj.rsp /c
..\..\third_party\harfbuzz-ng\src\hb-fallback-shape.cc
/Foobj\third_party\harfbuzz-ng\src\harfbuzz-ng.hb-fallback-shape.obj
/Fdobj\third_party\harfbuzz-ng\harfbuzz-ng.pdb
e:\b\build\slave\win\build\src\third_party\harfbuzz-ng\src\hb-font-private.hh(237)
:error C2220: warning treated as error - no 'object' file generated
e:\b\build\slave\win\build\src\third_party\harfbuzz-ng\src\hb-font-private.hh(237)
: warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
e:\b\build\slave\win\build\src\third_party\harfbuzz-ng\src\hb-font-private.hh(375)
: warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data

BUG=313423
TBR=eae
R=eae

Review URL: https://codereview.chromium.org/73703002

git-svn-id: svn://svn.chromium.org/blink/trunk@162075 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: 482b39c4ec011368d799d540c1f150af8d29f654