Set public_deps for //components/google/core/browser.
Header files in components/google/core/browser include files from these targets, therefore they should be public_deps.

Example error:
In file included from ../../chrome/browser/rlz/chrome_rlz_tracker_delegate.cc:24:
In file included from ../../components/search_engines/template_url_service.h:23:
In file included from ../../components/google/core/browser/google_url_tracker.h:17:
In file included from ../../net/url_request/url_fetcher.h:19:
In file included from ../../net/url_request/url_request.h:26:
In file included from ../../net/base/net_error_details.h:9:
In file included from ../../net/http/http_response_info.h:14:
In file included from ../../net/ssl/ssl_info.h:20:
In file included from ../../net/ssl/ssl_config.h:12:
In file included from ../../net/cert/x509_certificate.h:25:
../../third_party/boringssl/src/include/openssl/base.h:68:10: fatal error: 'openssl/opensslconf.h' file not found

BUG=none

Review-Url: https://codereview.chromium.org/2812403003
Cr-Commit-Position: refs/heads/master@{#464302}

Former-commit-id: 888cf7c28286229cb62da42125ee41302d32b2de