Make TextSuggestionMenuTest less flaky
This test was disabled because try bots were failing on the assert statement
that checks that the misspelled word is actually being deleted. In local testing
on my Nexus 6P, the test failed on 5 out of 36 runs.

I determined that the problem is that there's a race condition which means that
after we've determined that suggestionsPopupWindow is non-null (and even if we
also verify suggestionsPopupWindow.isShowing(), although the test wasn't
checking this), the delete button may not have been measured/laid out yet. In
this case, when the test attempts to click on the center of the delete button,
it ends up clicking on the "Add to dictionary" button instead. The fix is to
keep polling until the delete button's width or height is non-zero.

After this fix, I ran the test for approximately 100 iterations on my Nexus 6P.
It passed 91 times, and 9 times it failed with an un-related error:

junit.framework.AssertionFailedError: Tab never selected/initialized

while attempting to run
ChromeActivityTestCaseBase.startMainActivityOnBlankPage() in
TextSuggestionMenuTest.startMainActivity(). This seems like flakiness in the
underlying test infrastructure that I can't really do anything about. The try
bots do not appear to be failing with this error.

Bug: 749138
Change-Id: Ib83a5776f69c26dbdf0732d2e23bee9ac59d740c
Reviewed-on: https://chromium-review.googlesource.com/587373
Reviewed-by: Ted Choc <tedchoc@chromium.org>
Commit-Queue: Ryan Landay <rlanday@chromium.org>
Cr-Commit-Position: refs/heads/master@{#489765}
Former-commit-id: 6dd7bd1733a1cf6e2a3baf047b2f22f5668f5feb