Revert "[Payment Request] Adds a navigation bar to the country picker."
This reverts commit bce135e8e84134b6e4d00bdaccf5847666fe3f67 [formerly 266e6ebd419359717c8d6aadf9311717765883f7].

Reason for revert: 

Sorry for another revert! The test is failing on iPhone 5s and iPad retina on iOS 9.

SCPaymentsPickerTestCase/testVerifySelection: 
../../ios/showcase/payments/sc_payments_picker_egtest.mm:249: error: -[SCPaymentsPickerTestCase testVerifySelection] : Exception: NoMatchingElementException

Exception Name: NoMatchingElementException
Exception Reason: Cannot find UI element.
Exception with Action: {
  "Action Name" : "Tap",
  "Element Matcher" : "((((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches((respondsToSelector(accessibilityIdentifier) && accessibilityID('kPaymentRequestPickerRowAccessibilityID')))) && ((kindOfClass('UILabel') || kindOfClass('UITextField') || kindOfClass('UITextView')) && hasText('Canada')) && kindOfClass('UILabel') && matcherForSufficientlyVisible(>=0.750000)) && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) && accessibilityTraits: UIAccessibilityTraitSelected))))",
  "Recovery Suggestion" : "Check if the element exists in the UI hierarchy printed below. If it exists, adjust the matcher so that it accurately matches element."
}

Exception Details: Error Trace: [
  {
    "Description" : "Interaction cannot continue because the desired element was not found.",
    "Error Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
    "Error Code" : "0",
    "File Name" : "GREYElementInteraction.m",
    "Function Name" : "-[GREYElementInteraction matchedElementsWithTimeout:error:]",
    "Line" : "124",
    "TestCase Class" : "SCPaymentsPickerTestCase",
    "TestCase Method" : "testVerifySelection"
  }
]

Original change's description:
> [Payment Request] Adds a navigation bar to the country picker.
> 
> Video of the fix in action:
> https://drive.google.com/file/d/0B4g_WskzVRJdQUVjLUE2RWRWREE/view?usp=sharing
> 
> This is a second attempt at fixing this issue. The first one was reverted due to failures in ios_showcase_egtests on smaller devices. Those failures were caused by the fact that some elements were off-screen, and EarlGrey was unable to select them.
> 
> Bug: 767154
> Change-Id: I60df99bf12a0a0858c900faa6544bf562667eda8
> Reviewed-on: https://chromium-review.googlesource.com/678020
> Reviewed-by: edchin <edchin@chromium.org>
> Reviewed-by: Moe Ahmadi <mahmadi@chromium.org>
> Commit-Queue: Marc-Antoine Courteau <macourteau@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#503771}

TBR=macourteau@chromium.org,edchin@chromium.org,mahmadi@chromium.org

Change-Id: Iff3bb784ec3b3a572830aefc35ffaabd040e313d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 767154
Reviewed-on: https://chromium-review.googlesource.com/679576
Reviewed-by: edchin <edchin@chromium.org>
Commit-Queue: edchin <edchin@chromium.org>
Cr-Commit-Position: refs/heads/master@{#503898}
Former-commit-id: 496ac1fe788b3622b7508dd643a89fb2c0925906