Revert "chrome_cleaner/os unit tests, part 1: a-f"
This reverts commit f7c3bab071adabb0168b45b245e4d916c1872f30 [formerly 47a44d77e048b49dea46b0a36f09996f52518061].

Reason for revert: Test failures on some bots
https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/Win10%20Tests%20x64%20%28dbg%29/2064
../../chrome/chrome_cleaner/os/disk_util_unittest.cc(892): error: Value of: HasZoneIdentifier(target_exe_path)
  Actual: false
Expected: true
Stack trace:
Backtrace:
	StackTraceGetter::CurrentStackTrace [0x00007FF663FC6FE0+80]
	testing::internal::UnitTestImpl::CurrentOsStackTraceExceptTop [0x00007FF663FE254A+90]
	testing::internal::AssertHelper::operator= [0x00007FF663FE204A+90]
	chrome_cleaner::DiskUtilTests_ZoneIdentifierWhenProcessIsRunning_Test::TestBody [0x00007FF663EECF4C+2924]
../../chrome/chrome_cleaner/os/disk_util_unittest.cc(897): error: Value of: base::ReadFileToString(stream_path, &content)
  Actual: false
Expected: true

Original change's description:
> chrome_cleaner/os unit tests, part 1: a-f
> 
> Also add test_util add extra setup that uses it to the test harness/
> 
> Bug: 830892
> Change-Id: Iae1bb4323f6a0b25339d13e702135c2a3625c99d
> Reviewed-on: https://chromium-review.googlesource.com/1141146
> Commit-Queue: Joe Mason <joenotcharles@chromium.org>
> Reviewed-by: Chris Sharp <csharp@chromium.org>
> Reviewed-by: Penny MacNeil <pennymac@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#577240}

TBR=csharp@chromium.org,pennymac@chromium.org,joenotcharles@chromium.org

Change-Id: Icf4ceab27056789e7aeb20f7c979aa9a3e52f3f1
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 830892
Reviewed-on: https://chromium-review.googlesource.com/1147961
Reviewed-by: Hajime Hoshi <hajimehoshi@chromium.org>
Commit-Queue: Hajime Hoshi <hajimehoshi@chromium.org>
Cr-Commit-Position: refs/heads/master@{#577439}
Former-commit-id: 6aa87588310f489658a5238241949d409f717a71