Revert of Enabling included files when reloading local NTP with --local-ntp-reload. (patchset #7 id:120001 of https://codereview.chromium.org/1376243005/ )
Reason for revert:
Break iOS Device ninja Build Bot

https://build.chromium.org/p/chromium.mac/builders/iOS_Device_%28ninja%29/builds/29414

Compilation failed as

In file included from ../../chrome/browser/search/local_files_ntp_source.cc:19:
../../third_party/re2/re2/re2.h:186:10: fatal error: 're2/stringpiece.h' file not found
#include "re2/stringpiece.h"

which is added in this CL.

Original issue's description:
> Enabling included files when reloading local NTP with --local-ntp-reload.

TBR=fserb@chromium.org,mathp@chromium.org,tmartino@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/1442793002

Cr-Commit-Position: refs/heads/master@{#359364}

Former-commit-id: c4f7330abe94c5b80ec82ae9c312ad7ae52318b0