Nonsfi mode: Use gnueabi flavor of arm in the target triple for libpthread.
Using the gnueabi environment means that the stack alignment is 16 rather than
4 bytes. The backend had this correct (which is what matters) but after 3.5
the frontent sanity-checks its version of the datalayout string against the
backend's, so they must match.

The frontend error is:

error: backend data layout
'e-m:e-p:32:32-f64:32:64-v64:32:64-v128:32:128-a:0:32-n32-S128' does not match
expected target description
      'e-m:e-p:32:32-f64:32:64-v64:32:64-v128:32:128-a:0:32-n32-S32

R=mseaborn@chromium.org
BUG= https://code.google.com/p/nativeclient/issues/detail?id=3930

Review URL: https://codereview.chromium.org/734163005

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@14105 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: 8a1f84c1d4234d592945fea0aa696b803c49fe24