Revert of [Android] Don't use a device blacklist if one isn't provided. (patchset #1 id:1 of https://codereview.chromium.org/1314823011/ )
Reason for revert:
Speculative revert, some builders (Nexus 5, 6 and 9 under chromium.gpu) are failing at the device status check step after this change due to:

  File "build/android/buildbot/bb_device_status_check.py", line 154, in blacklisting_device_status
    if not serial in blacklist.Read():
AttributeError: 'NoneType' object has no attribute 'Read'

See http://build.chromium.org/p/chromium.gpu/builders/Android%20Debug%20%28Nexus%205%29/builds/2067 for example.

Original issue's description:
> [Android] Don't use a device blacklist if one isn't provided.
>
> BUG=517709
>
> Committed: https://crrev.com/c2b7b48348ebed5f884b2734f090d51506f04f90 [formerly be5c91849d2196f97c7a4e0b3e90597c3f2b4c40]
> Cr-Commit-Position: refs/heads/master@{#347473}

TBR=rnephew@chromium.org,jbudorick@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=517709

Review URL: https://codereview.chromium.org/1306653005

Cr-Commit-Position: refs/heads/master@{#347489}

Former-commit-id: 0179090eb844b39ea55bd70e8e2202c4d3a81026