ui: events: add missing files to GN build
error: undefined reference to 'ui::TouchEventLogEvdev::TouchEventLogEvdev()'

BUG=none

Review URL: https://codereview.chromium.org/1218873010

Cr-Commit-Position: refs/heads/master@{#337598}

Former-commit-id: 101cbaaeffb2d1a1c250a280940388cb962b3a29