Revert "put goma client in depot_tools"
This reverts commit 77780358011f8e20c68ba10aa1282f1f9f65734f.

Reason for revert: AttributeError: 'GomaEnvPosix' object has no attribute 'RestartCompilerProxy'

Original change's description:
> put goma client in depot_tools
> 
> install goma client cipd package in depot_tools.
> 
> should not use $MYPATH/goma_ctl in cipd_bin_setup
> since $MYPATH/goma_ctl uses cipd_bin_setup in itself,
> so causing recursive calls.
> invoke python to run .cipd/goma_ctl.py in cipd_bin_setup
> instead.
> 
> Bug: b/77663154
> Change-Id: I9f82c766a886a2acfb899e3594e5f05a7b7bc75a
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/1866350
> Reviewed-by: Edward Lesmes <ehmaldonado@chromium.org>
> Reviewed-by: Dirk Pranke <dpranke@chromium.org>
> Commit-Queue: Fumitoshi Ukai <ukai@chromium.org>

TBR=sque@chromium.org,ukai@chromium.org,yyanagisawa@google.com,vadimsh@chromium.org,dpranke@chromium.org,tikuta@chromium.org,ehmaldonado@chromium.org,yekuang@google.com

Change-Id: Ie050dfb524dd885634c31be829d733613e80aece
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: b/77663154
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/1872129
Reviewed-by: Fumitoshi Ukai <ukai@chromium.org>
Commit-Queue: Fumitoshi Ukai <ukai@chromium.org>