Fix PNaCl FYI bots by dropping the "scons-tests-pic" step
r11386 introduces the following error on the PNaCl FYI bots:

.../arm-pc-nacl-ld.gold: error: .../toolchain/pnacl_linux_x86/newlib/usr/lib/libc.a: symbol '_impure_ptr' used as both __thread and non-__thread
.../arm-pc-nacl-ld.gold: scons-out/nacl-x86-64-pnacl-pic-clang/obj/tests/infoleak/test_fpu_control_word.o: previous definition here
tests/infoleak/test_fpu_control_word.c:122: error: undefined reference to '_impure_ptr'
tests/infoleak/test_fpu_control_word.c:129: error: undefined reference to '_impure_ptr'

Since we are not trying to support dynamic linking or -fPIC in the
PNaCl toolchain at the moment, we don't need to make this obscure test
configuration work, so we can drop the nacl_pic=1 invocations from the
PNaCl tests.

This will also reduce the buildbot cycle time and reduce the bots'
energy consumption.

This particular test failure is fallout from always running
"-nacl-expand-tls" in pnacl-ld.py, which has the comment "Note that
running this means we do not support linking against native code that
uses TLS variables".  test_fpu_control_word.c is built as native code;
it uses stderr, which becomes the TLS var _impure_ptr.

BUG=https://code.google.com/p/nativeclient/issues/detail?id=3435
TEST=trybots

Review URL: https://codereview.chromium.org/15755013

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@11394 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: d680f6b0d41277044a4baee4dd93318a8d6ca54e