Revert of Oilpan: Schedule an idle garbage collection after receiving the kGCCallbackScheduleIdleGarbageColle… (patchset #2 id:20001 of https://codereview.chromium.org/2871743002/ )
Reason for revert:
This CL causes a compile error on the CI:
https://build.chromium.org/p/chromium/builders/Linux%20x64/builds/39399

The error log was:
[46869/52874] CXX obj/third_party/WebKit/Source/core/core_generated/V8GCController.o
FAILED: obj/third_party/WebKit/Source/core/core_generated/V8GCController.o
(snip)
../../third_party/WebKit/Source/bindings/core/v8/V8GCController.cpp:446:21: error: no member named 'kGCCallbackScheduleIdleGarbageCollection' in namespace 'v8'
    if (flags & v8::kGCCallbackScheduleIdleGarbageCollection) {

Original issue's description:
> Oilpan: Schedule an idle garbage collection after receiving the kGCCallbackScheduleIdleGarbageCollection callback flag.
>
> BUG=chromium:718484
> NOTRY=true
>
> Review-Url: https://codereview.chromium.org/2871743002
> Cr-Commit-Position: refs/heads/master@{#470860}
> Committed: https://chromium.googlesource.com/chromium/src/+/5b9fd296eac0e46b5255f0864b9837d1adf09f95 [formerly 9b107d47bd61d2ed77c923ad22dca27b226c9236]

TBR=haraken@chromium.org,hpayer@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=chromium:718484

Review-Url: https://codereview.chromium.org/2873873004
Cr-Commit-Position: refs/heads/master@{#470865}

Former-commit-id: bcf974f311836b1b26cdc3969e6e9bf3211c0550