Revert 233191 "Simplify GPU blacklist for WinAura"
Various WebGL-related tests started failing on XP and Vista:
http://build.chromium.org/p/chromium.win/buildstatus?builder=XP%20Tests%20%282%29&number=31628
http://build.chromium.org/p/chromium.win/buildstatus?builder=XP%20Tests%20%283%29&number=25055
http://build.chromium.org/p/chromium.win/buildstatus?builder=Vista%20Tests%20%281%29&number=41714
http://build.chromium.org/p/chromium.win/buildstatus?builder=Vista%20Tests%20%282%29&number=39756
http://build.chromium.org/p/chromium.win/buildstatus?builder=Vista%20Tests%20%283%29&number=35336

Example:

browser\extensions\requirements_checker_browsertest.cc(47): error: Value of: actual_errors
Actual: { "WebGL is not supported.", "CSS3d is not supported." }
Expected: expected_errors
Which is: {}

> Simplify GPU blacklist for WinAura
> 
> The gpu is completely blacklisted on all vista and XP machines with aura. All other blacklisting of them is redundant.
> 
> BUG=315199
> 
> Review URL: https://codereview.chromium.org/58343007

TBR=jbauman@chromium.org

Review URL: https://codereview.chromium.org/60833004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@233210 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 732d63973660399f881380080def56763e0b8847