Fix missing mock_network_state_helper.h dependency.
I've seen this a few times, most recently: https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Ftryserver.chromium.linux%2Flinux_chromium_chromeos_rel_ng%2F423107%2F%2B%2Frecipes%2Fsteps%2Fcompile__with_patch_%2F0%2Fstdout

/b/c/goma_client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/browser/chromeos/test_support/mock_network_state_helper.o.d ...
In file included from ../../chrome/browser/chromeos/login/mock_network_state_helper.cc:5:
In file included from ../../chrome/browser/chromeos/login/mock_network_state_helper.h:8:
In file included from ../../chrome/browser/chromeos/login/helper.h:16:
../../ui/views/view.h:22:10: fatal error: 'ui/accessibility/ax_enums.h' file not found

Review-Url: https://codereview.chromium.org/2877443003
Cr-Commit-Position: refs/heads/master@{#470709}

Former-commit-id: b23370c2e00320f1c53d7e91a8876bb9a899f08a