Unreviewed build fix for chromium/mac & clang.
Fix the macro redefinition error by r94927, because chromium set
ENABLE_JSC_MULTIPLE_THREADS=0 in WebKit/chromium/features.gypi and
it is not PLATFORM(QT).
 ../../JavaScriptCore/wtf/Platform.h:512:9: error: 'ENABLE_JSC_MULTIPLE_THREADS' macro redefined [-Werror]
 #define ENABLE_JSC_MULTIPLE_THREADS 1
 <command line>:43:9: note: previous definition is here
 #define ENABLE_JSC_MULTIPLE_THREADS 0
 1 error generated.

* wtf/Platform.h:

git-svn-id: svn://svn.chromium.org/blink/trunk@94939 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: 255b0ecf53e38a247649c618453cee2bdacf954b