FilmGrain::AddNoise: capture local array by reference
fixes a build error under vs14:
src\film_grain.cc(760): error C2075:
'libgav1::FilmGrain<8>::AddNoise::<lambda_150bf7f5cbb22a5b17efed23e6daa122>::planes_to_blend':
array initialization requires a brace-enclosed initializer list

PiperOrigin-RevId: 300852580
Change-Id: I62a92167146705ed4cbaf4917a5a266b3cd71f51