Revert of Evacuate ComputedStyle references from the CSS*Value hierarchy (patchset #1 id:1 of https://codereview.chromium.org/2345893004/ )
Reason for revert:
Tree is red; this patch fails to compile:

../../third_party/WebKit/Source/core/css/CSSValuePair.h:42:12: error: incomplete result type 'WTF::String' in function definition
    String customCSSText() const

Original issue's description:
> Evacuate ComputedStyle references from the CSS*Value hierarchy
>
> Fold uses of:
>
>   CSSPrimitiveValue::create(..., const ComputedStyle&)
>   CSSValuePair::create(..., const ComputedStyle&)
>
> into the (few) users. Handle the fall-out.
>
> Committed: https://crrev.com/821a0f909245c49b8ae2cd0ad5ccec206353d781 [formerly ba9df880383908b052d5a7d00abb32deec94cfc5]
> Cr-Commit-Position: refs/heads/master@{#419382}

TBR=sashab@chromium.org,timloh@chromium.org,fs@opera.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review-Url: https://codereview.chromium.org/2343343002
Cr-Commit-Position: refs/heads/master@{#419385}

Former-commit-id: 533dcff13b0b002494a3040d2f90de937a93e76d