Revert 285142 "Open the WrenchMenu on mouseover when dragging a ..."
Caused ToolbarViewInteractiveUITest.TestWrenchMenuOpensOnDrag to
start being flaky on Vista:

http://build.chromium.org/p/chromium.win/builders/Vista%20Tests%20%281%29/builds/47593/steps/interactive_ui_tests/logs/TestWrenchMenuOpensOnDrag

e.g. test output:

ToolbarViewInteractiveUITest.TestWrenchMenuOpensOnDrag (run #1):
[ RUN      ] ToolbarViewInteractiveUITest.TestWrenchMenuOpensOnDrag
c:\b\build\slave\win_builder\build\src\chrome\browser\ui\views\toolbar\toolbar_view_interactive_uitest.cc(145): error: Value of: browser_actions()->VisibleBrowserActions()
  Actual: 0
Expected: 1u
Which is: 1
[  FAILED  ] ToolbarViewInteractiveUITest.TestWrenchMenuOpensOnDrag, where TypeParam =  and GetParam() =  (374 ms)

> Open the WrenchMenu on mouseover when dragging a browser action
> 
> Enable dragging from the main container to the overflow container by opening the
> wrench menu when hovering over the button while dragging a browser action. This
> also requires keeping the menu open while the drag is happening.
> 
> Note: this doesn't fix drag calculations for the overflow menu.
> In an effort to keep these patches small, that will come later.
> 
> BUG=393038
> 
> Review URL: https://codereview.chromium.org/399143004

TBR=rdevlin.cronin@chromium.org

Review URL: https://codereview.chromium.org/416903002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@285301 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: ddcfa8052dae1d1f3b2045b06789e565039c21bd