GCC: fix clash with predefined macro "linux" in performance_manager features
The changeset "[PM] Add a dynamic tcmalloc implementation for Linux & CrOS"
introduces a build regression because of naming a namespace as "linux". But
in GCC that word is predefined:

    ../../chrome/browser/performance_manager/graph/policies/policy_features.h:62:11: error: expected identifier before numeric constant
     namespace linux {

Bug: 819294
Change-Id: Iecaf87987bd851ec4ee130e71451d5be40fc5517
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1768416
Commit-Queue: Sigurður Ásgeirsson <siggi@chromium.org>
Reviewed-by: Sigurður Ásgeirsson <siggi@chromium.org>
Cr-Commit-Position: refs/heads/master@{#689920}

Former-commit-id: 3a089d3f7942ceacdb3489f86a2d45506a7ac7d7