Changes introduces by r189102 causes following warning on Visual Studio 2012:
src\content\browser\devtools\renderer_overrides_handler.cc(78) : error C2220: warning treated as error - no 'object' fil
 generated
src\content\browser\devtools\renderer_overrides_handler.cc(78) : warning C4703: potentially uninitialized local pointer

TBR=kkania@chromium.org
BUG=n/a

Review URL: https://codereview.chromium.org/12989012

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@189752 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 04c73cbb3ee891ae446652af2e95a892aa467a0f