Revert of android: Introduce a ui::PlatformWindow implementation for android. (patchset #5 id:120001 of https://codereview.chromium.org/1180573004/)
Reason for revert:
Breaks Win GN bots:

http://build.chromium.org/p/chromium.win/builders/Win%20x64%20GN/builds/2751

e:\b\build\slave\win_x64_gn\build\src\components\view_manager\native_viewport\platform_viewport_common.cc(64) : error C3861: 'platform_window_reset': identifier not found
e:\b\build\slave\win_x64_gn\build\src\components\view_manager\native_viewport\platform_viewport_common.cc(64) : error C2664: 'ui::WinWindow::WinWindow(const ui::WinWindow &)' : cannot convert argument 1 from 'native_viewport::PlatformViewportCommon *const ' to 'const ui::WinWindow &'
        Reason: cannot convert from 'native_viewport::PlatformViewportCommon *const ' to 'const ui::WinWindow'
        No constructor could take the source type, or constructor overload resolution was ambiguous

Original issue's description:
> android: Introduce a ui::PlatformWindow implementation for android.
>
> This change introduces a ui::PlatformWindow implementation for android, and uses
> that from view_manager. The implementation of PlatformWindowAndroid is copied over
> from PlatformViewportAndroid. The various PlatformViewport implementations are
> merged into a single PlatformViewportCommon implementation, that uses the common
> ui::PlaformWindow abstraction for managing the windows.
>
> BUG=487881
>
> Committed: https://crrev.com/f7c1dc864863bd0438b0995d5557397a59b9341d [formerly 870d6cf7d409b5e7dae82c98bfaeaa5137a652d9]
> Cr-Commit-Position: refs/heads/master@{#334262}

TBR=ben@chromium.org,sadrul@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=487881

Review URL: https://codereview.chromium.org/1184913004

Cr-Commit-Position: refs/heads/master@{#334281}

Former-commit-id: 707589fabd6b34ba22bf9e3299f603511fd21f48