pynacl/file_tools: use unlink if symlink, rmdir if truly a dir
os.path.isdir will say True for both symlinks and dirs
which is mostly okay since ops like listdir still work
even on symlinks. However, os.rmdir only works if the
thing is actually a directory. Test if it's a link before
deciding how to remove it.

Try to fix bots that got stuck in extract_package step:

Traceback (most recent call last):
  File "/mnt/data/b/build/slave/nacl-toolchain/build/native_client/build/package_version/package_version.py", line 1296, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/mnt/data/b/build/slave/nacl-toolchain/build/native_client/build/package_version/package_version.py", line 1289, in main
    return COMMANDS[arguments.command].do_cmd_func(arguments)
  File "/mnt/data/b/build/slave/nacl-toolchain/build/native_client/build/package_version/package_version.py", line 746, in _DoExtractCmd
    quiet=arguments.quiet)
  File "/mnt/data/b/build/slave/nacl-toolchain/build/native_client/build/package_version/package_version.py", line 562, in ExtractPackageTargets
    pynacl.file_tools.MoveAndMergeDirTree(temp_src_dir, destination_dir)
  File "/mnt/data/b/build/slave/nacl-toolchain/build/native_client/pynacl/file_tools.py", line 202, in MoveAndMergeDirTree
    MoveAndMergeDirTree(source_item, destination_item)
  File "/mnt/data/b/build/slave/nacl-toolchain/build/native_client/pynacl/file_tools.py", line 202, in MoveAndMergeDirTree
    MoveAndMergeDirTree(source_item, destination_item)
  File "/mnt/data/b/build/slave/nacl-toolchain/build/native_client/pynacl/file_tools.py", line 202, in MoveAndMergeDirTree
    MoveAndMergeDirTree(source_item, destination_item)
  File "/mnt/data/b/build/slave/nacl-toolchain/build/native_client/pynacl/file_tools.py", line 215, in MoveAndMergeDirTree
    Retry(os.rmdir, src_dir)
  File "/mnt/data/b/build/slave/nacl-toolchain/build/native_client/pynacl/file_tools.py", line 245, in Retry
    op(*args, **kwargs)
OSError: [Errno 20] Not a directory: '/mnt/data/b/build/slave/nacl-toolchain/build/native_client/toolchain/linux_x86/pnacl_newlib/.tmp/x86_64-nacl/lib64/32'
Executing: ['/usr/bin/python', '/mnt/data/b/build/slave/nacl-toolchain/build/native_client/build/package_version/package_version.py', '--annotate', '--packages', 'linux_x86/pnacl_newlib', 'extract', '--overlay-tar-dir', '/mnt/data/b/build/slave/nacl-toolchain/build/native_client/toolchain_build/out/packages', '--skip-missing']
Traceback (most recent call last):
  File "buildbot/packages.py", line 158, in <module>
    sys.exit(main(sys.argv[1:]))
  File "buildbot/packages.py", line 151, in main
    skip_missing=arguments.skip_missing)
  File "buildbot/packages.py", line 125, in ExtractPackages
    extract_args)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/mnt/data/b/build/slave/nacl-toolchain/build/native_client/build/package_version/package_version.py', '--annotate', '--packages', 'linux_x86/pnacl_newlib', 'extract', '--overlay-tar-dir', '/mnt/data/b/build/slave/nacl-toolchain/build/native_client/toolchain_build/out/packages', '--skip-missing']' returned non-zero exit status 1
exit code (as seen by runtest.py): 1

BUG=none
R=bradnelson@chromium.org, dschuff@chromium.org

Review URL: https://codereview.chromium.org/1280453002 .


Former-commit-id: 9d857b98e2c8810e01008941606dc835e55dce36