Defer setting model until timeline-view is attached.
Setting the model on tr-ui-timeline-view before the element is attached causes a
crash, this happens (for example) if we open a trace then quickly switch away to
another tab.

Without the fix, the new test crashes:
Error: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at DomApi.(anonymous function) [as appendChild] (http://localhost:8003/components/polymer/polymer-mini.html:1242:26)
    at HTMLElement.set model [as model] (http://localhost:8003/tracing/ui/timeline_view.html:407:45)
    at TestCase.testFn_ (http://localhost:8003/tracing/ui/timeline_view_test.html:166:16)
    at TestCase.run (http://localhost:8003/tracing/base/unittest/test_case.html:84:19)
    at TestRunner.<anonymous> (http://localhost:8003/tracing/base/unittest/test_runner.html:235:48)
    at Promise (<anonymous>)
    at TestRunner.runCurrentTestCase_ (http://localhost:8003/tracing/base/unittest/test_runner.html:232:14)
    at TestRunner.runOneTestCase_ (http://localhost:8003/tracing/base/unittest/test_runner.html:180:12)
    at Promise.resolve.then (http://localhost:8003/tracing/base/unittest/test_runner.html:137:43)
    at <anonymous>

BUG=catapult:#3184,catapult:#3297

Review-Url: https://codereview.chromium.org/3000343002

Former-commit-id: cad1ea2451b707e3ff575492258358f9945ae64d