Reland: Get rid of redundant member function Position::offsetForPositionAfterAnchor()
This patch gets rid of redundant member function
|Position::offsetForPositionAfterAnchor()| to make source code smaller for
improving code health since it is used only once.

This patch is a preparation of getting rid of legacy editing position.

This patch is a reland of https://crrev.com/1254423009, which failed on 
android_clan_dbg_recipe by undefined reference to
|EditingAlgorithm<blink::NodeTraversal>::lastOffsetForEditing()|.

Rather than exporting related classes, this patch moves implementation of
|deprecatedEdigintOffset()| into CPP file from header file to keep number
of exported symbols small.

BUG=513114
TEST=n/a; no behavior changes

Review URL: https://codereview.chromium.org/1252263007

git-svn-id: svn://svn.chromium.org/blink/trunk@199871 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: 79966579ae3c8b782e3f57076d3185903dc31ed0