Revert of [V8][Metric] Initial implementation of the RuntimeStatsMetric (patchset #6 id:100001 of https://chromiumcodereview.appspot.com/2415963002/ )
Reason for revert:
This is causing test failures on the CQ and locally.

Link to bot with CQ failures:
https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Linux%20Tryserver/builds

From a local run on linux:

TypeError: tr.v.ValueSet is not a constructor
    at Object.testFn_ (http://127.0.0.1:8003/tracing/metrics/v8/runtime_stats_metric_test.html:179:18)
    at Object.run (http://127.0.0.1:8003/tracing/base/unittest/test_case.html:79:19)
    at Object.<anonymous> (http://127.0.0.1:8003/tracing/base/unittest/test_runner.html:218:52)
    at Object.runCurrentTestCase_ (http://127.0.0.1:8003/tracing/base/unittest/test_runner.html:216:14)
    at Object.runOneTestCase_ (http://127.0.0.1:8003/tracing/base/unittest/test_runner.html:169:12)

Original issue's description:
> [V8][Metric] Initial implementation of the RuntimeStatsMetric
>
> This CL implements a runtime stats metric that extracts the runtime
> stats info from the V8ThreadSlices up to interactive time.
> Then these values are grouped by 'type'. Each type is a single value
> histogram. Histograms are repeated for count and duration.
>
> Each 'Type' histogram has a RelatedValueMap that describes the
> individual runtime stats used to calculate that 'type' data.
>
> BUG=catapult:#2938
>
> Committed: https://chromium.googlesource.com/external/github.com/catapult-project/catapult/+/4431daed5cdefc6d71adcf01921755273d8c7d63 [formerly 55c4800f013cba6cb2a4b77e8c49b643d56a8873]

TBR=eakuefner@chromium.org,benjhayden@chromium.org,cbruni@chromium.org,lpy@chromium.org,nednguyen@google.com,fmeawad@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=catapult:#2938

Review-Url: https://chromiumcodereview.appspot.com/2439953002

Former-commit-id: 96f25d9aa22bdc48bb9e6fa417585fb150caa0a1