Revert "Handle Open/Verify android apps for Assistant"
This reverts commit 70f1128794cb08314b58c8f3615e99f511739b5d [formerly d20781e198ad7f985311737a00f7324c549f81b1].

Reason for revert: Causes compile failure in Google Chrome ChromeOS

https://ci.chromium.org/buildbot/chromium.chrome/Google%20Chrome%20ChromeOS/59164

In file included from ../../chromeos/services/assistant/assistant_manager_service_impl.cc:5:
../../chromeos/services/assistant/assistant_manager_service_impl.h:142:31: error: no type named 'AndroidAppInfo' in namespace 'chromeos::assistant::action'; did you mean 'mojom::AndroidAppInfo'?
  void OnOpenAndroidApp(const action::AndroidAppInfo& app_info,
                              ^~~~~~~~~~~~~~~~~~~~~~
                              mojom::AndroidAppInfo
gen/chromeos/services/assistant/public/mojom/assistant.mojom.h:1276:8: note: 'mojom::AndroidAppInfo' declared here
class  AndroidAppInfo {
       ^

Original change's description:
> Handle Open/Verify android apps for Assistant
> 
> Bug: b/117793081
> Test: Manual Test
> Change-Id: If747d3317cb163715ff907839203e0c0eee57a1c
> Reviewed-on: https://chromium-review.googlesource.com/c/1352341
> Commit-Queue: Yue Li <updowndota@chromium.org>
> Reviewed-by: Xiaohui Chen <xiaohuic@chromium.org>
> Reviewed-by: Sam McNally <sammc@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#612448}

TBR=sammc@chromium.org,xiaohuic@chromium.org,updowndota@chromium.org,llin@chromium.org

Change-Id: If0edc6853dfdce343f6f52edd6bc059f8c7ec1aa
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: b/117793081
Reviewed-on: https://chromium-review.googlesource.com/c/1356164
Reviewed-by: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Commit-Queue: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Cr-Commit-Position: refs/heads/master@{#612484}
Former-commit-id: cf111e8e868a431216ad29a8b16d4c647b57ba1a