BUILD FIX: FormController.cpp fails to build on 32-bit architectures
This fixes the following build failure introduced in r121004 for
Bug 89628:

    FormController.cpp:62:36: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Werror,-Wshorten-64-to-32]
        state.m_values.reserveCapacity(valueSize);
        ~~~~~                          ^~~~~~~~~

* html/FormController.cpp:
(WebCore::FormControlState::deserialize): Change type of
valueSize from uint64_t to size_t.

git-svn-id: svn://svn.chromium.org/blink/trunk@121032 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: 71a2281a9bfc8337acbb4eae0459a92ab2ec4192