Mojo: ~0 -> ~0u, since the compiler on Linux Trusty doesn't like the conversion.
From the FYI bots:
FAILED: c++ -MMD -MF obj/mojo/system/mojo_system_unittests.shared_buffer_dispatcher_unittest.o.d [...]
../../mojo/system/shared_buffer_dispatcher_unittest.cc: In member function ‘virtual void mojo::system::{anonymous}::SharedBufferDispatcherTest_DuplicateBufferHandleOptionsValid_Test::TestBody()’:
../../mojo/system/shared_buffer_dispatcher_unittest.cc:183:3: error: narrowing conversion of ‘-1’ from ‘int’ to ‘MojoDuplicateBufferHandleOptionsFlags {aka unsigned int}’ inside { } is ill-formed in C++11 [-Werror=narrowing]
   };
      ^

As a drive-by, eliminate a couple of static_casts that no one wants.

R=darin@chromium.org
TBR=darin@chromium.org

Review URL: https://codereview.chromium.org/333803012

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@277186 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: fd3836f435bf04ce0f72b42fe50f9a2b8c8835b8