cros_portage_upgrade: fix clean up of stray objects
The current clean up logic assumes that it's only upgrading a package
that has been committed to the tree.  If it's not (because a previous
run failed or whatever), the git rm step fails due to git not knowing
anything about the file:

$ cros_portage_upgrade --upgrade --force --board daisy:stumpy:x86-alex hdparm
...
cleaning up /home/vapier/trunk/src/third_party/portage-stable/sys-apps/hdparm
fatal: pathspec 'sys-apps/hdparm/hdparm-9.39.ebuild' did not match any files
Keeping upstream cache at /tmp/portage.
cros_portage_upgrade: Unhandled exception:
Traceback (most recent call last):
...
chromite.lib.cros_build_lib.RunCommandError: return code: 128
Failed command "'git' 'rm' '-rf' u'sys-apps/hdparm/metadata.xml'
	u'sys-apps/hdparm/hdparm-9.20.ebuild' u'sys-apps/hdparm/hdparm-9.39.ebuild'
	u'sys-apps/hdparm/files'", cwd=/home/vapier/trunk/src/third_party/portage-stable,
	extra env={'GIT_PAGER': 'cat'}

Let's use the --ignore-unmatch flag to fix that, and then manually run
unlink on all the files that still exist.

BUG=chromium:212189
TEST=created a dummy file in sys-apps/hdparm and ran upgrade; did not see traceback and dummy file was cleaned

Change-Id: Ib8efd596ad3cda4c453f703f1a02feacca5ee35b
Reviewed-on: https://gerrit.chromium.org/gerrit/66503
Reviewed-by: Matt Tennant <mtennant@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>