Revert "Add animated voice interaction icon."
This reverts commit c8f36499a9b1f527769cce31f44314ecd1d5466d [formerly 875aa3d7b80dd3d6a2f0a265d4ca1875b502abc6].

Reason for revert:

Breaks the M61 branch build

cc -o obj/ash/ash/voice_interaction_overlay.o
../../ash/shelf/voice_interaction_overlay.cc:170:43: error: no member named 'since_origin' in 'base::TimeTicks'
    uint64_t now = base::TimeTicks::Now().since_origin().InMilliseconds();

Original change's description:
> Add animated voice interaction icon.
> 
> BUG=b:62276007
> TEST=build flash locally, see animation as spec
> TBR=xiaohuic@google.com
> 
> (cherry picked from commit 497dbff00a087f4b5147039fde2efcd7a9a44195 [formerly cc92f7aea52bd87500cab8538687da6e756aaed0])
> 
> Change-Id: I5542b68e084fe465c2f8b424b521c8faef51f686
> Reviewed-on: https://chromium-review.googlesource.com/585245
> Commit-Queue: Xiaohui Chen <xiaohuic@chromium.org>
> Reviewed-by: Mitsuru Oshima <oshima@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#490447}
> Reviewed-on: https://chromium-review.googlesource.com/595143
> Reviewed-by: Vladislav Kaznacheev <kaznacheev@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3163@{#198}
> Cr-Branched-From: 4ed6f3464972596ad6c696f9d7937b9e8061d641 [formerly ff259bab28b35d242e10186cd63af7ed404fae0d]-refs/heads/master@{#488528}

TBR=kaznacheev@chromium.org,oshima@chromium.org,xiaohuic@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: b:62276007
Change-Id: Ie8e554ca79f054e0e4d18621402123455950aa9c
Reviewed-on: https://chromium-review.googlesource.com/597071
Reviewed-by: James Cook <jamescook@chromium.org>
Cr-Original-Commit-Position: refs/branch-heads/3163@{#229}
Cr-Original-Branched-From: 4ed6f3464972596ad6c696f9d7937b9e8061d641 [formerly ff259bab28b35d242e10186cd63af7ed404fae0d]-refs/heads/master@{#488528}(cherry picked from commit c69b95b9ee63fc0f7aceef3589eff02532914144 [formerly 020cdf35035e30942aa34ca571fce561bff18cf6])
Reviewed-on: https://chromium-review.googlesource.com/598507
Commit-Queue: Xiaohui Chen <xiaohuic@chromium.org>
Cr-Commit-Position: refs/heads/master@{#491521}
Former-commit-id: 1737b40ca5cf2c05f5b6c90d342dae31dbad09f3