Revert "Migrate AssistantAudioDecoderFactory to new Mojo types"
This reverts commit f309833a371f085cf1e739c860d85f2e741ec67b [formerly 78abc7fa8a34ff4357d7a048d228eefcb9506a9d].

Reason for revert:
Break the build:
../../chromeos/services/assistant/platform/audio_stream_handler.cc:31:43: error: no viable conversion from 'typename remove_reference<InterfacePtr<AssistantAudioDecoderClient> &>::type' (aka 'mojo::InterfacePtr<chromeos::assistant::mojom::AssistantAudioDecoderClient>') to 'mojo::PendingRemote<AssistantAudioDecoderClient>'
      mojo::MakeRequest(&audio_decoder_), std::move(client),


Original change's description:
> Migrate AssistantAudioDecoderFactory to new Mojo types
> 
> This CL applies the new Mojo types to CreateAssistantAudioDecoder
> in AssistantAudioDecoderFactory interface.
> 
>   - Convert FooRequest to mojo::PendingReceiver.
>   - Convert FooPtr to mojo::PendingRemote or mojo::Remote.
> 
> Bug: 955171
> Change-Id: I2de4cb0561c69201335817ec6a873258a30d9a00
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1871503
> Commit-Queue: Gyuyoung Kim <gyuyoung@igalia.com>
> Reviewed-by: Oksana Zhuravlova <oksamyt@chromium.org>
> Reviewed-by: Tao Wu <wutao@chromium.org>
> Reviewed-by: Sam McNally <sammc@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#709059}

TBR=sammc@chromium.org,wutao@chromium.org,gyuyoung@igalia.com,oksamyt@chromium.org

Change-Id: I3890551d694ab28db3ba476e0771c99993c3b270
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 955171
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1879690
Reviewed-by: Tao Wu <wutao@chromium.org>
Commit-Queue: Tao Wu <wutao@chromium.org>
Cr-Commit-Position: refs/heads/master@{#709103}

Former-commit-id: 51b403b08ec04a9946508512bc4f9dd1eb947456