Revert "WebUI[MD-refresh]: replace most paper-input with cr-inputs"
This reverts commit e45ebcae30695436567bc097dbc6452bea72d467 [formerly 9a7643defbc3e5114439b6d2240eed0715c1705c].

Reason for revert: 

MediaRouterElementsBrowserTest.MediaRouterContainerFilterPart1 became
flaky in Mac10.11, 10.12, and 10.13 after this landed.

https://test-results.appspot.com/dashboards/flakiness_dashboard.html#tests=MediaRouterElementsBrowserTest.MediaRouterContainerFilterPart1

https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/Mac10.12%20Tests/13846

[ RUN      ] MediaRouterElementsBrowserTest.MediaRouterContainerFilterPart1
[35158:6151:0618/184304.560701:WARNING:notification_platform_bridge_mac.mm(510)] AlertNotificationService: XPC connection invalidated.
[35158:775:0618/184305.696851:WARNING:CONSOLE(0)] "Styling master document from stylesheets defined in HTML Imports is deprecated. Please refer to https://goo.gl/EGXzpw for possible migration paths.", source:  (0)
[35158:775:0618/184306.249427:INFO:CONSOLE(1236)] "Running TestCase MediaRouterElementsBrowserTest.MAYBE_MediaRouterContainerFilterPart1", source: file:///b/s/w/ir/chrome/test/data/webui/test_api.js (1236)
[35158:775:0618/184306.545042:WARNING:CONSOLE(16)] "Invalid keyframe value for property marginBottom: 44", source: chrome://resources/polymer/v1_0/web-animations-js/web-animations-next-lite.min.js (16)
[35158:775:0618/184306.545170:WARNING:CONSOLE(16)] "Invalid keyframe value for property marginBottom: 44", source: chrome://resources/polymer/v1_0/web-animations-js/web-animations-next-lite.min.js (16)
[35158:775:0618/184306.602655:ERROR:CONSOLE(48)] "Mocha test failed: MediaRouterContainerFilterPart1 focus sink search input
Error: Script error. (:0)
", source: file:///b/s/w/ir/chrome/test/data/webui/mocha_adapter.js (48)
[35158:775:0618/184306.602796:ERROR:CONSOLE(206)] "Uncaught AssertionError: expected 'sink-list' to equal 'filter'", source: file:///b/s/w/ir/third_party/chaijs/chai.js (206)
[35158:775:0618/184306.688827:WARNING:CONSOLE(16)] "Invalid keyframe value for property marginBottom: 44", source: chrome://resources/polymer/v1_0/web-animations-js/web-animations-next-lite.min.js (16)
[35158:775:0618/184306.688978:WARNING:CONSOLE(16)] "Invalid keyframe value for property marginBottom: 44", source: chrome://resources/polymer/v1_0/web-animations-js/web-animations-next-lite.min.js (16)
[35158:775:0618/184306.878527:WARNING:CONSOLE(16)] "Invalid keyframe value for property marginBottom: 44", source: chrome://resources/polymer/v1_0/web-animations-js/web-animations-next-lite.min.js (16)
[35158:775:0618/184306.878646:WARNING:CONSOLE(16)] "Invalid keyframe value for property marginBottom: 44", source: chrome://resources/polymer/v1_0/web-animations-js/web-animations-next-lite.min.js (16)
[35158:775:0618/184307.420478:WARNING:CONSOLE(16)] "Invalid keyframe value for property marginBottom: 44", source: chrome://resources/polymer/v1_0/web-animations-js/web-animations-next-lite.min.js (16)
[35158:775:0618/184307.420605:WARNING:CONSOLE(16)] "Invalid keyframe value for property marginBottom: 44", source: chrome://resources/polymer/v1_0/web-animations-js/web-animations-next-lite.min.js (16)
[35158:775:0618/184308.705393:WARNING:CONSOLE(16)] "Invalid keyframe value for property marginBottom: 44", source: chrome://resources/polymer/v1_0/web-animations-js/web-animations-next-lite.min.js (16)
[35158:775:0618/184308.705526:WARNING:CONSOLE(16)] "Invalid keyframe value for property marginBottom: 44", source: chrome://resources/polymer/v1_0/web-animations-js/web-animations-next-lite.min.js (16)
[35158:775:0618/184308.710999:WARNING:CONSOLE(16)] "Invalid keyframe value for property marginBottom: 44", source: chrome://resources/polymer/v1_0/web-animations-js/web-animations-next-lite.min.js (16)
[35158:775:0618/184308.711145:WARNING:CONSOLE(16)] "Invalid keyframe value for property marginBottom: 44", source: chrome://resources/polymer/v1_0/web-animations-js/web-animations-next-lite.min.js (16)
[35158:775:0618/184308.845267:WARNING:CONSOLE(16)] "Invalid keyframe value for property marginBottom: 44", source: chrome://resources/polymer/v1_0/web-animations-js/web-animations-next-lite.min.js (16)
[35158:775:0618/184308.845353:WARNING:CONSOLE(16)] "Invalid keyframe value for property marginBottom: 44", source: chrome://resources/polymer/v1_0/web-animations-js/web-animations-next-lite.min.js (16)
[35158:775:0618/184308.850290:ERROR:web_ui_test_handler.cc(100)] Test Errors: 1/12 tests had failed assertions.

Original change's description:
> WebUI[MD-refresh]: replace most paper-input with cr-inputs
> 
> This CL replaces most paper-inputs with cr-inputs within the code-base.
> After this CL, the 3 places that still has paper-input remaining are:
> - chrome/browser/resources/chromeos/login/
> - chrome/browser/resources/pdf/
> - ui/file_manager/
> 
> There are planned follow-up CLs to replace paper-input in the above 3
> areas as well.
> 
> Bug: 832177
> Cq-Include-Trybots: luci.chromium.try:closure_compilation
> Change-Id: I7acc7e0a26a6bd3d40ec6828608717fd97bd0c73
> Reviewed-on: https://chromium-review.googlesource.com/1086357
> Commit-Queue: Scott Chen <scottchen@chromium.org>
> Reviewed-by: Demetrios Papadopoulos <dpapad@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#568241}

TBR=dpapad@chromium.org,scottchen@chromium.org

Change-Id: I1dd101893378c8354c48e72d9f56231ec1ee9850
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 832177
Cq-Include-Trybots: luci.chromium.try:closure_compilation
Reviewed-on: https://chromium-review.googlesource.com/1105207
Reviewed-by: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Commit-Queue: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Cr-Commit-Position: refs/heads/master@{#568320}
Former-commit-id: e25ce18197c99f1b063bf85e816562a5c8340214