Revert r12140: PNaCl: Put newlib before libnacl on the link line.
This is causing linking failures in the PNaCl FYI bots
(small exception handling tests):

Error: command failed 1 toolchain/pnacl_linux_x86/bin/pnacl-translate -arch x86-32 --pnacl-allow-exceptions --allow-llvm-bitcode-input /tmp/tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.final.pexe -o /tmp/tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.nexe
/tmp/tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.nexe---tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.final.pexe---.o:/tmp/tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.final.pexe:function exit: error: undefined reference to 'free'
/tmp/tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.nexe---tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.final.pexe---.o:/tmp/tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.final.pexe:function exit: error: undefined reference to 'free'
/tmp/tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.nexe---tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.final.pexe---.o:/tmp/tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.final.pexe:function _start: error: undefined reference to 'malloc'
/tmp/tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.nexe---tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.final.pexe---.o:/tmp/tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.final.pexe:function _start: error: undefined reference to 'malloc'
/tmp/tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.nexe---tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.final.pexe---.o:/tmp/tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.final.pexe:function atexit: error: undefined reference to 'malloc'
/tmp/tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.nexe---tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.final.pexe---.o:/tmp/tc_test_llvm_pnacl_x86-32_O3_eh_scope1.C.final.pexe:function atexit: error: undefined reference to 'malloc'
/mnt/data/b/build/slave/linux-pnacl-x86_64-tests-x86_32/build/native_client/pnacl/git/gcc/libgcc/../gcc/unwind-dw2-fde.c:586: error: undefined reference to 'free'
/mnt/data/b/build/slave/linux-pnacl-x86_64-tests-x86_32/build/native_client/pnacl/git/gcc/libgcc/../gcc/unwind-dw2-fde.c:196: error: undefined reference to 'free'

[  FAILED  ] translate-x86: /tmp/nacl_compiler_test/gcc-4.6.1/gcc/testsuite/g++.dg/eh/scope1.C

We end up with: "declare extern_weak noalias i8* @malloc(i32) #3", instead of actually linking malloc
into the bitcode!  This might be because libc.a has
a weak malloc "w malloc", but I'm not sure.

It hopefully doesn't affect stable ABI bitcode, but
let's make the FYI bots green for now and investigate.

This reverts the link order to what it was before.

BUG= https://code.google.com/p/nativeclient/issues/detail?id=3687
R=stichnot@chromium.org

Review URL: https://codereview.chromium.org/24336003

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@12187 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: 9e762e10cb617ec3144f02adbfb30d773407e194