Revert "chromite: Remove TreeIsOpen and dependencies."
This reverts commit e057820e36f58e99d052b914b104d1c0eba9fca6.

Reason for revert:Broke the CQ master builder

https://cros-goldeneye.corp.google.com/chromeos/healthmonitoring/buildDetails?buildbucketId=8915697068235833824

[1;31m19:13:53: ERROR: <type 'exceptions.AttributeError'>: 'module' object has no attribute 'TreeIsClosedException'
Traceback (most recent call last):
  File "/b/s/w/ir/cache/cbuild/repository/chromite/lib/failures_lib.py", line 230, in wrapped_functor
    return functor(*args, **kwargs)
  File "/b/s/w/ir/cache/cbuild/repository/chromite/cbuildbot/stages/sync_stages.py", line 773, in PerformStage
    except validation_pool.TreeIsClosedException as e:
AttributeError: 'module' object has no attribute 'TreeIsClosedException'
[0m

Original change's description:
> chromite: Remove TreeIsOpen and dependencies.
> 
> TEST=./run_tests
> BUG=chromium:903420
> 
> Change-Id: If08789053b882127950b9fa45d53437d13131552
> Reviewed-on: https://chromium-review.googlesource.com/1568051
> Commit-Ready: Evan Hernandez <evanhernandez@chromium.org>
> Tested-by: Evan Hernandez <evanhernandez@chromium.org>
> Reviewed-by: Dhanya Ganesh <dhanyaganesh@chromium.org>

Bug: chromium:903420
Change-Id: If81f024e0f679eaef32b0a4744a1ee369e65b73d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/1576281
Reviewed-by: Keith Haddow <haddowk@chromium.org>
Commit-Queue: Keith Haddow <haddowk@chromium.org>
Tested-by: Keith Haddow <haddowk@chromium.org>