Revert "Implement updated array buffer allocator in gin"
This reverts commit 1348968f1a5ff91483d050b5b30e95b88855d6b4 [formerly 714060db89bbb6dc78229cd0b582bd51df8f1bd4].

Reason for revert: This broke the cronet builds:
FAILED: lib_net_unittests__library.so lib_net_unittests__library.so.TOC ...
../../gin/array_buffer.cc:40: error: undefined reference to 'base::AllocPages(void*, unsigned long, unsigned long, base::PageAccessibilityConfiguration)'
../../gin/array_buffer.cc:55: error: undefined reference to 'base::FreePages(void*, unsigned long)'
../../gin/array_buffer.cc:67: error: undefined reference to 'base::SetSystemPagesInaccessible(void*, unsigned long)'
../../gin/array_buffer.cc:70: error: undefined reference to 'base::SetSystemPagesAccessible(void*, unsigned long)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

https://uberchromegw.corp.google.com/i/chromium.android/builders/Android%20Cronet%20Marshmallow%2064bit%20Builder/builds/10832

Original change's description:
> Implement updated array buffer allocator in gin
> 
> Bug: chromium:720302
> Change-Id: I127daca6ee9954774b8ff23382ba38cb23da7318
> Reviewed-on: https://chromium-review.googlesource.com/543670
> Commit-Queue: Eric Holk <eholk@chromium.org>
> Reviewed-by: Jochen Eisinger <jochen@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#481959}

TBR=eholk@chromium.org,jochen@chromium.org

Change-Id: Id51402c6a8e87ef8af6eb3d0f8c8332f52eeefdb
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: chromium:720302
Reviewed-on: https://chromium-review.googlesource.com/546676
Reviewed-by: Ted Choc <tedchoc@chromium.org>
Commit-Queue: Ted Choc <tedchoc@chromium.org>
Cr-Commit-Position: refs/heads/master@{#481970}
Former-commit-id: dea76b7b72e53291607621c905a52c38f8eef279