Relanding - https://codereview.chromium.org/20565006/ The CL was reverted due to this error, c:\b\build\slave\google-chrome-rel-win\build\src\chrome/browser/feedback/feedback_util.h(13): fatal error C1083: Cannot open include file: 'chrome/browser/feedback/proto/common.pb.h': No such file or directory
This CL neither changes line 13 in feedback_util.h (which includes the generated protobuf file), nor does it change common.proto, which is used to generate common.ph.h; so it seems very probable that this build error is a flake.

TBR=rkc@chromium.org
BUG=None.

Review URL: https://codereview.chromium.org/22253004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@215683 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: b8192877c5720ca2d294bfcf7187e2b9654d3016