Revert of Handle media access permission request (https://codereview.chromium.org/239793002/)
Reason for revert:
It looks like this broke Android builder:
http://build.chromium.org/p/chromium.linux/builders/Android%20Builder%20%28db...

In file included from
../../android_webview/native/permission/aw_permission_request_delegate.cc:5:0:
../../android_webview/native/permission/aw_permission_request_delegate.h:8:37:
fatal error: base/android/jni_helper.h: No such file or directory
compilation terminated.
etc

Original issue's description:
> This patch is also implements the general permission request.
> 
> - AwPermissionRequest wraps a permission request.
> - AwPermissionRequestDelegate interface should be implemented by specific permission request like media access permission request.
> - PermissionRequestHandler, send the request to AwContentsClient or Cancel a ongoing request.
> 
> NOTRY=true
> BUG=363301
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=267495

NOTREECHECKS=true
NOTRY=true
BUG=363301
TBR=michaelbai

Review URL: https://codereview.chromium.org/268543005

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@267503 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: d3c0222f2c0663456e86543313fc0420ee7416d6