Revert 221932 "Refactor KeySystems code to call a function to po..."
> Refactor KeySystems code to call a function to populate the info.
> 
> This allows KeySystems to call GetContentClient()->AddKeySystems() so we can
> move key system information to chrome/. The new ContentClient API is defined and
> called, but we still rely on key_systems_info.cc.
> 
> BUG=224793
> TEST=Existing content_unittests and content_browsertests pass.
> 
> Review URL: https://chromiumcodereview.appspot.com/23678008

It broke chromeOs compile:

FAILED: g++ -MMD -MF obj/content/renderer/media/crypto/content_renderer.key_systems_info.o.d -DCONTENT_IMPLEMENTATION -DANGLE_DX11 -DWTF_VECTOR_INITIAL_SIZE=4 -D_FILE_OFFSET_BITS=64 -DGOOGLE_CHROME_BUILD -DENABLE_RLZ -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_NSS=1 -DUSE_X11=1 -DOS_CHROMEOS=1 -DFILE_MANAGER_EXTENSION=1 -DIMAGE_LOADER_EXTENSION=1 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_INPUT_SPEECH -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DENABLE_GPU=1 -DENABLE_EGLIMAGE=1 -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_AUTOMATION=1 -DENABLE_GOOGLE_NOW=1 -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -DGL_GLEXT_PROTOTYPES -DLIBPEERCONNECTION_LIB=1 -DSK_ENABLE_INST_COUNT=0 -DSK_SUPPORT_GPU=1 '-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' -DSK_USE_POSIX_THREADS -DSK_DEFERRED_CANVAS_USES_FACTORIES=1 -DU_USING_ICU_NAMESPACE=0 -DU_STATIC_IMPLEMENTATION -DFEATURE_ENABLE_SSL -DFEATURE_ENABLE_VOICEMAIL -DEXPAT_RELATIVE_PATH -DGTEST_RELATIVE_PATH -DJSONCPP_RELATIVE_PATH -DNO_MAIN_THREAD_WRAPPING -DNO_SOUND_SYSTEM -DLINUX -DPOSIX -DCHROMEOS -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_LINUX -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DOFFICIAL_BUILD -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -I../.. -Igen -I../../third_party/khronos -I../../gpu -Igen/content -I../../third_party/skia/src/core -I../../skia/config -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../skia/ext -I../../third_party/WebKit -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -I../../third_party/libjingle/overrides -I../../third_party/libjingle/source -I../../testing/gtest/include -I../../third_party -I../../third_party/webrtc -I../../third_party/jsoncpp/overrides/include -I../../third_party/jsoncpp/source/include -I../../third_party/npapi -I../../third_party/npapi/bindings -I../../v8/include -I../../third_party/webrtc/modules/interface -I../../third_party/webrtc/modules/audio_device/include -I../../net/third_party/nss/ssl -Werror -pthread -fno-exceptions -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -g -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/nss -I/usr/include/nspr -O2 -fno-ident -fdata-sections -ffunction-sections -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare  -c ../../content/renderer/media/crypto/key_systems_info.cc -o obj/content/renderer/media/crypto/content_renderer.key_systems_info.o
../../content/renderer/media/crypto/key_systems_info.cc: In function 'void content::AddPepperBasedWidevine(std::vector<content::KeySystemInfo>*)':
../../content/renderer/media/crypto/key_systems_info.cc:104:23: error: invalid conversion from 'int' to 'content::SupportedCodecs' [-fpermissive]
ninja: build stopped: subcommand failed.

http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20ChromeOS/builds/57998/steps/compile/logs/stdio



TBR=ddorwin@chromium.org

Review URL: https://codereview.chromium.org/23578015

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@221939 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: c07b1f74c2e6d215862c2e6466b68fef7eafff44