undefined reference to symbol eina_module_free https://bugs.webkit.org/show_bug.cgi?id=76681
Patch by ChangSeok Oh <shivamidow@gmail.com> on 2012-01-20
Reviewed by Martin Robinson.

eina_module_free has been used without including eina libraries after r104936.

* wtf/PlatformEfl.cmake: Add EINA_LIBRARIES.

git-svn-id: svn://svn.chromium.org/blink/trunk@105495 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: 02236428c6fc332b2d03d89dbb7faf83d64fb369