Revert of Decouple GpuCompositorFrameSink from DisplayCompositor (patchset #7 id:120001 of https://codereview.chromium.org/2654693003/ )
Reason for revert:
Broke Win 64 builder's compile step:
https://build.chromium.org/p/chromium/builders/Win%20x64/builds/7950

[23910/48389] CXX obj/content/app/content_main_runner_child/content_main_runner.obj
FAILED: obj/content/app/content_main_runner_child/content_main_runner.obj
ninja -t msvc -e environment.x64 -- C:\b\c\cipd\goma/gomacc.exe "C:\b\depot_tools\win_toolchain\vs_files\d3cb0e37bdd120ad0ac4650b674b09e81be45616\VC\bin\amd64/cl.exe" /nologo /showIncludes /FC @obj/content/app/content_main_runner_child/content_main_runner.obj.rsp /c ../../content/app/content_main_runner.cc /Foobj/content/app/content_main_runner_child/content_main_runner.obj /Fd"obj/content/app/content_main_runner_child_cc.pdb"
c:\b\c\b\win_x64_archive\src\content\browser\gpu\gpu_process_host.h(32): fatal error C1083: Cannot open include file: 'services/ui/gpu/interfaces/gpu_host.mojom.h': No such file or directory

Original issue's description:
> Decouple GpuCompositorFrameSink from DisplayCompositor
>
> In order to reuse GpuCompositorFrameSink in other parts of Chrome
> (e.g. OffscreenCanvas), this CL decouples
> GpuCompositorFrameSinkSupport from DisplayCompositor.
>
> This CL also moves GpuCompositorFrameSInk out of
> services/ui/surfaces for now as well because we would like to use
> this code in Chrome and this is currently an incomplete internal
> implementation detail of Mus. Once code is unified between Chrome
> and Mus, components/display_compositor can probably move to
> services/ui/gpu/display_compositor.
>
> BUG=683735
> CQ_INCLUDE_TRYBOTS=master.tryserver.blink:linux_trusty_blink_rel
>
> Review-Url: https://codereview.chromium.org/2654693003
> Cr-Commit-Position: refs/heads/master@{#446223}
> Committed: https://chromium.googlesource.com/chromium/src/+/b722076b1e2c7aadbee4c1429dcf84262dbe2b44 [formerly 81183e45cf14c416dfce69b990a0c71a4e1c3399]

TBR=fsamuel@chromium.org,ben@chromium.org,kylechar@chromium.org,jam@chromium.org,danakj@chromium.org,xing.xu@intel.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=683735

Review-Url: https://codereview.chromium.org/2651213004
Cr-Commit-Position: refs/heads/master@{#446233}

Former-commit-id: c850f7de840cdb2c21ee10166a76c2acbf04cc01