Do not define POSIX.
It breaks integration with upstream re2 library on Chromium.

Without patching re2 library, with this define, it produces the
following error:

../../third_party/re2/re2/re2.h:254:5: error: expected identifier
    POSIX, // POSIX syntax, leftmost-longest match

As we define POSIX on the command line, the C preprocessor changes
RE2::POSIX to nothing and thus break the compilation. :(

See chromium-dev mailing list for this discussion in
https://groups.google.com/a/chromium.org/d/topic/chromium-dev/UXCHnX7pV44/discussion

BUG=None
R=sergeyu@chromium.org

Review URL: https://codereview.chromium.org/1096693003

Cr-Commit-Position: refs/heads/master@{#326229}

Former-commit-id: 3891bacf18a0fc5dfec32afc67c741728f8f1398