AbortError: Another PaymentRequest UI is already showing.
Before this patch, if a user attempted to open a second PaymentRequest
UI in a separate tab or window, the .show() promise would be rejected
with "AbortError: Request cancelled." This generic error message created
confusion about the reason why the PaymentRequest UI could not be
opened.

This patch keeps the AbortError, but makes the web developer visible
error message more specific to this error condition.

After this patch, if a user attempts to open a second PaymentRequest UI
in a separate tab or window, the .show() promise is rejected with
"AbortError: Another PaymentRequest UI is already showing in a
different tab or window."

Bug: 878453
Change-Id: I5d27171e21b69cfd5fc95a0a72cb6efce343ea5d
Reviewed-on: https://chromium-review.googlesource.com/1195650
Commit-Queue: Rouslan Solomakhin <rouslan@chromium.org>
Reviewed-by: Mike West <mkwst@chromium.org>
Reviewed-by: Ganggui Tang <gogerald@chromium.org>
Cr-Commit-Position: refs/heads/master@{#587610}
Former-commit-id: b2d233c40cf68e6d66ed9788d211a63086711be6