Revert 160781 - Update webrtc to 2881 and libjingle to 202.
It broke the "ChromiumOS (daisy)" bot: <http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20%28daisy%29/builds/3567/steps/BuildTarget/logs/stdio> as listed in the following snippet.
  chromeos-chrome-24.0.1290.0_alpha-r1: third_party/webrtc/common_audio/signal_processing/spl_init.c:35:13: error: 'InitPointersToC' defined but not used [-Werror=unused-function]
  chromeos-chrome-24.0.1290.0_alpha-r1: cc1: all warnings being treated as errors
  chromeos-chrome-24.0.1290.0_alpha-r1: make: *** [c/Release/obj.target/signal_processing/third_party/webrtc/common_audio/signal_processing/spl_init.o] Error 1
  chromeos-chrome-24.0.1290.0_alpha-r1: make: *** Waiting for unfinished jobs....

TEST=apprtc.appspot.com and chrome/test/functional/webrtc_call.py

Review URL: https://chromiumcodereview.appspot.com/11066063

TBR=ronghuawu@chromium.org
Review URL: https://codereview.chromium.org/11098011

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@160801 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 06e2bec34c6740eb53f647cf7254fb6ddf0ff274