Revert "desktop-pwas: Set the 'default app' installation flag"
This reverts commit f226b5c4533b1ba7960334546c0ff1cbe23ea471 [formerly 948cae415a34f5b07b46ba21b35f4b89414ba2c5].

Reason for revert: breaks compile on https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/Win%20x64%20Builder/54466

errors like

In file included from ../..\chrome/browser/web_applications/bookmark_apps/policy/web_app_policy_manager.h:8:
 error: no matching constructor for initialization of 'web_app::PendingAppManager::AppInfo'


Original change's description:
> desktop-pwas: Set the 'default app' installation flag
> 
> Adds a new bool to AppInfo; when set, the InstallationTask marks the
> installed app as a "default app", which means that the app will behave
> like other default installed Bookmark Apps.
> 
> TBR=khorimoto@chromium.org
> 
> Bug: 876173
> Change-Id: I102b85178862500ac5ba233a483192819cfb4e5c
> Reviewed-on: https://chromium-review.googlesource.com/1188732
> Reviewed-by: Giovanni Ortuño Urquidi <ortuno@chromium.org>
> Reviewed-by: Dominick Ng <dominickn@chromium.org>
> Commit-Queue: Giovanni Ortuño Urquidi <ortuno@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#586525}

TBR=khorimoto@chromium.org,ortuno@chromium.org,dominickn@chromium.org

Change-Id: I9b79c4ff827eda4f9c58952863cf99cbb1c66724
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 876173
Reviewed-on: https://chromium-review.googlesource.com/1192483
Reviewed-by: Trent Apted <tapted@chromium.org>
Commit-Queue: Trent Apted <tapted@chromium.org>
Cr-Commit-Position: refs/heads/master@{#586528}
Former-commit-id: aa2eb9e6dff12d3fe1a56b4eb3b8234ea0006655