Revert "Convert ConditionalCacheDeletionHelperBrowserTest to not depend on URLRequestContext when network service is enabled."
This reverts commit 7964366cab2b142ba66e862f7bb3897bfc530766 [formerly 56a58d7d63a1aac6e1ada54979b2b730a5d0be53].

Reason for revert: FindIt determined that this CL makes ConditionalCacheDeletionHelperBrowserTest.TimeAndURL flaky.
FindIt's analysis looks correct.

Sample failed run:
https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/Win%207%20Tests%20x64%20%281%29/45771

Sample logs:
../../content/browser/browsing_data/conditional_cache_deletion_helper_browsertest.cc(107): error: Value of: TestCacheEntry(url)
  Actual: true
Expected: false
Stack trace:
Backtrace:
	testing::internal::UnitTestImpl::CurrentOsStackTraceExceptTop [0x00000001409F75B7+87]
	testing::internal::AssertHelper::operator= [0x00000001409F713E+78]
	content::ConditionalCacheDeletionHelperBrowserTest::CompareRemainingKeys [0x000000013FD458FE+510]
	content::ConditionalCacheDeletionHelperBrowserTest_TimeAndURL_Test::RunTestOnMainThread [0x000000013FD4634A+2410]
	content::BrowserTestBase::ProxyRunTestOnMainThreadLoop [0x0000000141C5413D+445]
	content::ShellBrowserMainParts::PreMainMessageLoopRun [0x0000000142564E24+68]
	content::BrowserMainLoop::PreMainMessageLoopRun [0x0000000140CD4D3E+62]
	content::StartupTaskRunner::RunAllTasksNow [0x00000001410129BB+43]
	content::BrowserMainLoop::CreateStartupTasks [0x0000000140CD3B67+599]
	content::BrowserMainRunnerImpl::Initialize [0x0000000140CD6EDB+107]
	ShellBrowserMain [0x00000001447B04B5+21]
	content::ShellMainDelegate::RunProcess [0x00000001447AED2C+188]
	content::RunBrowserProcessMain [0x0000000140C020E9+89]
	content::ContentMainRunnerImpl::RunServiceManager [0x0000000140C02A1B+219]
	content::ContentMainRunnerImpl::Run [0x0000000140C0290E+238]
	service_manager::Main [0x00000001421C591A+554]
	content::ContentMain [0x0000000140C0202E+62]
	content::BrowserTestBase::SetUp [0x0000000141C53E44+1796]



Original change's description:
> Convert ConditionalCacheDeletionHelperBrowserTest to not depend on URLRequestContext when network service is enabled.
>
> Bug: 837753
> Change-Id: I35b75299bcea1cc2b93a3c47dcbea036cc4e2d03
> Reviewed-on: https://chromium-review.googlesource.com/c/1357567
> Reviewed-by: Clark DuVall <cduvall@chromium.org>
> Commit-Queue: John Abd-El-Malek <jam@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#612858}

TBR=jam@chromium.org,cduvall@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 910891
Change-Id: I541e21663a02cdedae6aa4991d5e8633890ffbbd
Reviewed-on: https://chromium-review.googlesource.com/c/1356946
Commit-Queue: Guido Urdaneta <guidou@chromium.org>
Reviewed-by: Guido Urdaneta <guidou@chromium.org>
Cr-Commit-Position: refs/heads/master@{#613119}
Former-commit-id: ce8869d8fe1fdcd92a729e9de386c85c10fa0332