Revert "Add the dialog controller as an observer so we can prompt the user if no browser is available"
This reverts commit 4ece1c9883184f5be8e3652948ab1c6d42519d5b [formerly df950cc336fda4298d6dd2c587c9a9c4d47b9874].

Reason for revert: 
failures:
ChromeCleanerPromptUserTest.OnInfectedBrowserNotAvailable
ChromeCleanerPromptUserTest.AllBrowsersClosed
ChromeCleanerPromptUserTest.OnInfectedBrowserAvailable
 
[ RUN      ] ChromeCleanerPromptUserTest.OnInfectedBrowserNotAvailable
GMOCK WARNING:
Uninteresting mock function call - returning directly.
    Function call: AddObserver(00000000025C5C18)
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#knowing-when-to-expect for details.
../../chrome/browser/safe_browsing/chrome_cleaner/chrome_cleaner_dialog_controller_impl_browsertest_win.cc(59): error: Actual function call count doesn't match EXPECT_CALL(mock_cleaner_controller_, state())...
         Expected: to be called once
           Actual: never called - unsatisfied and active

Original change's description:
> Add the dialog controller as an observer so we can prompt the user if no browser is available
> Bug:  http://crbug.com/734677
> 
> Change-Id: Iec5a1e85bd4887dac5a821d2bb96d6db70f33cb6
> Reviewed-on: https://chromium-review.googlesource.com/593967
> Reviewed-by: Robert Shield <robertshield@chromium.org>
> Reviewed-by: Jesse Doherty <jwd@chromium.org>
> Reviewed-by: Ali Tofigh <alito@chromium.org>
> Commit-Queue: Juan José Lopez Jaimez <jjlopezjaimez@google.com>
> Cr-Commit-Position: refs/heads/master@{#492183}

TBR=jwd@chromium.org,robertshield@chromium.org,joenotcharles@google.com,ftirelo@chromium.org,alito@chromium.org,jjlopezjaimez@google.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: http://crbug.com/734677
Change-Id: If5c3cda43b284860a5ef3bfc541813925ff491d0
Reviewed-on: https://chromium-review.googlesource.com/602833
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#492266}
Former-commit-id: e2b3698c962e14be9675d533d179d4a5335cd40e