Revert "Update GetAccessibleName() in view::ImageView and view::Button"
This reverts commit 822a4dc1b802888de9a8172f88003486677caa60 [formerly 07f45e13abeab9b8cf97e7a45aecd5d37d6d7d77].

Reason for revert: broke compilation on Win
https://ci.chromium.org/buildbot/chromium.chrome/Google%20Chrome%20Win/38615
../../chrome/browser/ui/views/policy/enterprise_startup_dialog_view.cc(171,15):  error: no member named 'SetTooltipText' in 'views::ImageView'; did you mean 'set_tooltip_text'?
  logo_image->SetTooltipText(
              ^~~~~~~~~~~~~~
              set_tooltip_text

Original change's description:
> Update GetAccessibleName() in view::ImageView and view::Button
> 
> This patch is updated duplicate code of tooltip text and accesible name
> 
> Bug: 890465
> Change-Id: I4ed08c50a91a216de5d647d0d137e8927129b6af
> Reviewed-on: https://chromium-review.googlesource.com/c/1256308
> Commit-Queue: Jongheon Kim <sapzape@gmail.com>
> Reviewed-by: Xiyuan Xia <xiyuan@chromium.org>
> Reviewed-by: Steven Bennetts <stevenjb@chromium.org>
> Reviewed-by: Michael Wasserman <msw@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#598729}

TBR=xiyuan@chromium.org,stevenjb@chromium.org,msw@chromium.org,jinho.bang@samsung.com,sapzape@gmail.com

Change-Id: Icd106f1c5e23a1a2f9322f867688f44809bd28b2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 890465
Reviewed-on: https://chromium-review.googlesource.com/c/1275856
Reviewed-by: Vasilii Sukhanov <vasilii@chromium.org>
Commit-Queue: Vasilii Sukhanov <vasilii@chromium.org>
Cr-Commit-Position: refs/heads/master@{#598734}
Former-commit-id: 03cb5c6ae11ab562bc364560972f74efdd66a761