Revert of Add PAM session wrapper (patchset #5 id:100001 of https://codereview.chromium.org/2323153002/ )
Reason for revert:
This CL seems to have broken the build - see https://uberchromegw.corp.google.com/i/official.desktop.continuous/builders/precise64%20trunk/builds/20292/steps/compile/logs/stdio :

[4004/46998] CXX obj/remoting/host/linux/remoting_user_session/remoting_user_session.o
FAILED: obj/remoting/host/linux/remoting_user_session/remoting_user_session.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/remoting/host/linux/remoting_user_session/remoting_user_session.o.d -DV8_DEPRECATION_WARNINGS -DENABLE_NOTIFICATIONS -DENABLE_PDF=1 -DUSE_UDEV -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DENABLE_TASK_MANAGER=1 -DENABLE_THEMES=1 -DUSE_PROPRIETARY_CODECS -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DOFFICIAL_BUILD -DGOOGLE_CHROME_BUILD -DENABLE_MEDIA_ROUTER=1 -DCR_CLANG_REVISION=287685-1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DCFI_ENFORCEMENT -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -I../../build/linux/debian_wheezy_amd64-sysroot/usr/include/glib-2.0 -I../../build/linux/debian_wheezy_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -fcolor-diagnostics -fdebug-prefix-map=/b/build/slave/precise64_trunk/build/src=. -flto -fwhole-program-vtables -pthread -m64 -march=x86-64 -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -O2 -fno-ident -fdata-sections -ffunction-sections -g2 --sysroot=../../build/linux/debian_wheezy_amd64-sysroot -fsanitize=cfi-vcall -fsanitize-blacklist=../../tools/cfi/blacklist.txt -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -fno-rtti -fno-exceptions -c ../../remoting/host/linux/remoting_user_session.cc -o obj/remoting/host/linux/remoting_user_session/remoting_user_session.o
../../remoting/host/linux/remoting_user_session.cc:320:5: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
    fchown(STDOUT_FILENO, pwinfo->pw_uid, pwinfo->pw_gid);
    ^~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original issue's description:
> Add PAM session wrapper
>
> Adds a wrapper to launch me2me script in a proper PAM session.
>
> BUG=616962
>
> Committed: https://crrev.com/6e68c6fabad00619372e91dbce688a066ef85660 [formerly ac6cd2ac8ea912ee4dc0c229f79b04874aee9cc3]
> Cr-Commit-Position: refs/heads/master@{#434172}

TBR=jamiewalch@chromium.org,lambroslambrou@chromium.org,sergeyu@chromium.org,rkjnsn@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=616962

Review-Url: https://codereview.chromium.org/2527713002
Cr-Commit-Position: refs/heads/master@{#434218}

Former-commit-id: 376920771f3df23499f30070f1ce9c2dc7c1a188