Fix componene debug build failure because of src/media/blink
The error log is as follows:
../../third_party/skia/include/core/SkImageInfo.h:109: error: undefined reference to 'SkDebugf_FileLine(char const*, int, bool, char const*, ...)'
collect2: error: ld returned 1 exit status

If any modules are going to use any Skia header no matter whether directly or
indirectly, the module must link Skia. src/media/blink doesn't depend on skia
directly but src/media, on which src/media/blink depends, depends on Skia. So
src/media/blink must link to Skia.

Review URL: https://codereview.chromium.org/885373003

Cr-Commit-Position: refs/heads/master@{#314554}

Former-commit-id: 5192601b41aff92488b9a458fc50dedda48507ac