Compilation fails due to missing namespace
../../ui/accessibility/platform/atk_util_auralinux_gtk2.cc:59:6: error: use of undeclared identifier 'AtkUtilAuraLinux'; did you mean 'ui::AtkUtilAuraLinux'?
bool AtkUtilAuraLinux::PlatformShouldEnableAccessibility() {
     ^~~~~~~~~~~~~~~~
     ui::AtkUtilAuraLinux
../../ui/accessibility/platform/atk_util_auralinux.h:17:7: note: 'ui::AtkUtilAuraLinux' declared here
class AtkUtilAuraLinux {
      ^
../../ui/accessibility/platform/atk_util_auralinux_gtk2.cc:74:6: error: use of undeclared identifier 'AtkUtilAuraLinux'; did you mean 'ui::AtkUtilAuraLinux'?
void AtkUtilAuraLinux::PlatformInitializeAsync() {
     ^~~~~~~~~~~~~~~~
     ui::AtkUtilAuraLinux
../../ui/accessibility/platform/atk_util_auralinux.h:17:7: note: 'ui::AtkUtilAuraLinux' declared here
class AtkUtilAuraLinux {
      ^
2 errors generated.

Change-Id: I0b683c6d1f193dfabf8ff1beac8572220262e5a3
Reviewed-on: https://chromium-review.googlesource.com/813838
Reviewed-by: Nektarios Paisios <nektar@chromium.org>
Commit-Queue: Dominic Mazzoni <dmazzoni@chromium.org>
Cr-Commit-Position: refs/heads/master@{#522941}
Former-commit-id: dbaad4aaba7885d8fa08fee909b5dd9e19f2879d