Revert of Allow headless TabSocket in isolated worlds & remove obsolete logic (patchset #12 id:220001 of https://codereview.chromium.org/2873283002/ )
Reason for revert:
This CL breaks compile step. Message:
FAILED: obj/headless/headless_browsertests/headless_web_contents_browsertest.obj
ninja -t msvc -e environment.x86 -- C:\b\c\goma_client/gomacc.exe "C:\b\depot_tools\win_toolchain\vs_files\d3cb0e37bdd120ad0ac4650b674b09e81be45616\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/headless/headless_browsertests/headless_web_contents_browsertest.obj.rsp /c ../../headless/lib/headless_web_contents_browsertest.cc /Foobj/headless/headless_browsertests/headless_web_contents_browsertest.obj /Fd"obj/headless/headless_browsertests_cc.pdb"
c:\b\c\b\win_archive\src\headless\lib\headless_web_contents_browsertest.cc(385) : error C2220: warning treated as error - no 'object' file generated
c:\b\c\b\win_archive\src\headless\lib\headless_web_contents_browsertest.cc(533) : error C2220: warning treated as error - no 'object' file generated
c:\b\c\b\win_archive\src\headless\lib\headless_web_contents_browsertest.cc(533) : warning C4702: unreachable code
c:\b\c\b\win_archive\src\headless\lib\headless_web_contents_browsertest.cc(385) : warning C4702: unreachable code

Original issue's description:
> Allow headless TabSocket in isolated worlds & remove obsolete logic
>
> This patch only affects C++ Embedders of headless_lib and should have
> no effect on normal chrome even with the --headless flag.
>
> Recently we decided to no longer allow arbitrary mojo bindings, instead
> relying on the headless::TabSocket API for js<-->C++ communications.
>
> The public headless API for registering a mojo module has already been
> removed and this patch finishes the job by removing the code from
> MojoBindingsController which injected js mojo bindings for
> BINDINGS_POLICY_HEADLESS.
>
> In this patch we are replacing BINDINGS_POLICY_HEADLESS with
> BINDINGS_POLICY_HEADLESS_MAIN_WORLD and
> BINDINGS_POLICY_HEADLESS_ISOLATED_WORLD which provide access to the
> headless::TabSocket API to either the main world or for isolated worlds
> created by the Page.CreateIsolatedWorld DevTools command.
>
> For a security point of view this patch hopefully reduces the attack
> surface for the main world because js now only has access to the
> headless::TabSocket API rather than arbitrary mojo modules.  Providing
> the headless::TabSocket API into isolated worlds is new but hopefully
> non-controversial. I note that ContentScripts have access to similar
> APIs for communication with the owning extension. I did investigate
> reusing that code but it didn't seem feasible.
>
> BUG=546953
>
> Review-Url: https://codereview.chromium.org/2873283002
> Cr-Commit-Position: refs/heads/master@{#474238}
> Committed: https://chromium.googlesource.com/chromium/src/+/d45ec58104e5c9da4027d5a6f89ac9f9e1fb3a72 [formerly 07ee7c399295b210c5338dfeb543f2d30f748340]

TBR=mkwst@chromium.org,jochen@chromium.org,skyostil@chromium.org,alexclarke@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=546953

Review-Url: https://codereview.chromium.org/2902953003
Cr-Commit-Position: refs/heads/master@{#474242}

Former-commit-id: b8618a1653256d3aae86b64e0c3c4d7c91d207c0