Revert "Reland "Split WebKit platform build file""
This reverts commit d3660575d32fc5d671a93fbd43da6a58ee1855a8 [formerly 997ce7ad904c0d5ad47fdb245773966ccc0436e5].

Reason for revert:

There still seems to be a race condition causing non-deterministic compile errors:

FAILED: obj/third_party/WebKit/Source/platform/loader/test_support/FetchTestingPlatformSupport.obj 
../../third_party/WebKit/Source\platform/blob/BlobData.h(42): fatal error C1083: Cannot open include file: 'storage/public/interfaces/blobs.mojom-blink.h': No such file or directory

Original change's description:
> Reland "Split WebKit platform build file"
> 
> platform/network/BUILD.gn lacked mojo_bindings_blink dependency.
> This caused a race on compiling.
> 
> This is a reland of 77bf6ed1d6d6226e02501ce642f55649b59f24f2 [formerly 080c70a7f837beb92ba1a6af71fd32098466656b]
> Original change's description:
> > Split WebKit platform build file
> > 
> > A race condition was found in the build of //third_party/WebKit/Source/platform/loader.
> > To resolve it necessary to extract targets  //third_party/WebKit/Source/platform/blob and //third_party/WebKit/Source/platform/network form //third_party/WebKit/Source/platform. And add correct dependencies where it is needed.
> > All of these done in this CL.
> > 
> > Original author is apisarev@yandex-team.ru, and toyoshim@chromium.org takes over it
> > to submit since it needs quick rebase works to catch up HEAD.
> > 
> > Bug: 754600
> > Change-Id: I5f70348fac10f270df99b658608cf23685ed937e
> > Test: gn check out/Release && ninja -C out/Release
> > Reviewed-on: https://chromium-review.googlesource.com/612284
> > Commit-Queue: Takashi Toyoshima <toyoshim@chromium.org>
> > Reviewed-by: Daniel Bratell <bratell@opera.com>
> > Reviewed-by: Takashi Toyoshima <toyoshim@chromium.org>
> > Reviewed-by: Kinuko Yasuda <kinuko@chromium.org>
> > Reviewed-by: Dimitri Glazkov <dglazkov@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#508661}
> 
> TBR=engedy@chromium.org
> 
> Bug: 754600
> Change-Id: I250e67581e61e1d36c32b01ccad3372b442c08bc
> Reviewed-on: https://chromium-review.googlesource.com/718243
> Commit-Queue: Takashi Toyoshima <toyoshim@chromium.org>
> Reviewed-by: Takashi Toyoshima <toyoshim@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#508993}

TBR=kinuko@chromium.org,toyoshim@chromium.org,engedy@chromium.org,bratell@opera.com,apisarev@yandex-team.ru,dglazkov@chromium.org

Change-Id: I439724cb5a6b98232b8af3b0f21af7960643023a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 754600
Reviewed-on: https://chromium-review.googlesource.com/720876
Reviewed-by: Balazs Engedy <engedy@chromium.org>
Commit-Queue: Balazs Engedy <engedy@chromium.org>
Cr-Commit-Position: refs/heads/master@{#508997}
Former-commit-id: 95e9f22cdca7f2f7b0cb104396e4ce8cccd2ed2f