Revert of Speculative fix for ui::DisplayLinkMac::StopDisplayLink crashes (patchset #2 id:20001 of https://codereview.chromium.org/1626163002/ )
Reason for revert:
Broke compile:
../../ui/accelerated_widget_mac/display_link_mac.cc:94:69: error: null passed to a callee that requires a non-null argument [-Werror,-Wnonnull]
      CVDisplayLinkSetOutputCallback(display_link_, nullptr, nullptr);
                                                    ~~~~~~~         ^

Original issue's description:
> Speculative fix for ui::DisplayLinkMac::StopDisplayLink crashes
>
> The CVDisplayLink is tied to a ScopedTypeRef data member of DisplayLinkMac.
> However, there may be other references. Since there's no guarantee that
> ~DisplayLinkMac() will invoke the last CVDisplayLinkRelease(..) and clear
> the callback automatically, clear it explicitly in ~DisplayLinkMac.
>
> BUG=564780
>
> Committed: https://crrev.com/8d87affb55dcaae75d2fd58f7f6a927e48309458 [formerly 2286ddf0119516f7a93feaff4f8ce2edff8c4543]
> Cr-Commit-Position: refs/heads/master@{#371648}

TBR=ccameron@chromium.org,tapted@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=564780

Review URL: https://codereview.chromium.org/1637313002

Cr-Commit-Position: refs/heads/master@{#371724}

Former-commit-id: 40b4841e82e2a559ffa94173d83e95ea3a64e146