Revert "Settings: Content settings can now be reset for a group of origins in All Sites."
This reverts commit 201954c3d12b5e0f0e9b411f9da63c9532b3de5c [formerly e2cac39f3c0aca0166794ea935e2244293aa9d4e].

Reason for revert: https://crbug.com/854785 (CrSettingsSiteEntryTest.All failing on chromium.mac/Mac10.13 Tests (dbg))

TypeError: this.$.menu.getIfExists is not a function
    at HTMLElement.getOverflowMenu_ (chrome://settings/site_settings/site_entry.js:115:65)
    at Context.<anonymous> (file:///b/s/w/ir/chrome/test/data/webui/settings/site_entry_tests.js:136:25)
", source: file:///b/s/w/ir/chrome/test/data/webui/mocha_adapter.js (48)

Original change's description:
> Settings: Content settings can now be reset for a group of origins in All Sites.
> 
> Add a three-dot / overflow menu to groups of origins in All Sites. This overflow
> menu allows the entire list of origins to have all their content settings reset
> in one go. This will be preceded with a confirmation dialog.
> 
> Manual test - With #enable-site-settings turned on, change a content setting via
> Page Info > Site settings on both https://permission.site and
> http://permission.site. Navigate to chrome://settings/content/all and see that
> both sites are listed under 'permission.site'. Verify there is an overflow menu
> on this entry and that inside the overflow menu, there is a 'Reset permissions'
> option. Clicking this should bring up a reset permission dialog and confirming
> the dialog should remove this entry from All Sites.
> 
> Bug: 835712, 717468
> Cq-Include-Trybots: luci.chromium.try:closure_compilation
> Change-Id: I777f759c26bf0fe7f8da086fa887969897cf9833
> Reviewed-on: https://chromium-review.googlesource.com/1098577
> Commit-Queue: Patti <patricialor@chromium.org>
> Reviewed-by: Dave Schuyler <dschuyler@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#568742}

TBR=dschuyler@chromium.org,patricialor@chromium.org

Change-Id: I227ad85a38a66a6f571dab6aabfdfb5211580280
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 835712, 717468, 854785 
Cq-Include-Trybots: luci.chromium.try:closure_compilation
Reviewed-on: https://chromium-review.googlesource.com/1108777
Reviewed-by: David Grogan <dgrogan@chromium.org>
Commit-Queue: David Grogan <dgrogan@chromium.org>
Cr-Commit-Position: refs/heads/master@{#569007}
Former-commit-id: 149bce0d01d769126d07181dd314f8090a21bbbe