Revert 222168 "Add a CodeToNativeKeycode helper that converts UI..."
UsbKeycodeMap.Basic consistently fails on the Win7 dbg main waterfall bot:
http://build.chromium.org/p/chromium.win/builders/Win7%20Tests%20(dbg)(1)
base\keycodes\usb_keycode_map_unittest.cc(36): error: Value of: "Unidentified"
Actual: 00890D98
Expected: InvalidKeyboardEventCode()
Which is: 007F90D4

> Add a CodeToNativeKeycode helper that converts UIEvent code to native code.
> Also add a SimulateKeyPress helper for browser_tests that takes both a UIEvent |code| and a ui::KeyboardCode.
> 
> issue=284754
> 
> Review URL: https://chromiumcodereview.appspot.com/23542008

TBR=weitaosu@chromium.org

Review URL: https://codereview.chromium.org/23451030

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@222199 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 38d327536f49b221a6c36f1c289e7899df501236