image_test: fix error handling with new bad users
Looks like holdover from the autotest migration.
Traceback (most recent call last):
  File ".../chromite/cros/test/image_test.py", line 580, in TestUsers
    self._CheckFile('passwd')
  File ".../chromite/cros/test/image_test.py", line 561, in _CheckFile
    is_valid = validate_func(details)
  File ".../chromite/cros/test/image_test.py", line 403, in _validate_passwd
    entry[0], entry.home)
TypeError: 'Collection_UserEntry' object does not support indexing

BUG=chromium:776023
TEST=precq passes

Change-Id: I32b085e802f8f09eede4dfee201fa688df1b8e71
Reviewed-on: https://chromium-review.googlesource.com/738280
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Jorge Lucangeli Obes <jorgelo@chromium.org>