Show an error update engine status for all unknown states.
The primary reason for this patch is so that I can add a new UPDATE_STATUS
enum value to libcros without breaking the Chrome OS build with the following
error:

"Right now we get the following error with LKGR of Chrome:
update_observer.cc: In member function 'virtual void
chromeos::UpdateObserver::Changed(chromeos::UpdateLibrary*)':
update_observer.cc:26: error: enumeration value
'UPDATE_STATUS_REPORTING_ERROR_EVENT' not handled in switch"

BUG=560
TEST=emerged chromeos-chrome with modified libcros, unit tests

Review URL: http://codereview.chromium.org/3053010

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@53409 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 540659481e1a9f87872566b59d15ba1ce75d1c1f