IWYU: include <memory> in bubble_menu_item_factory.h as it uses std::unique_ptr
GCC build fixes because of missing include of <memory>:
../../chrome/browser/ui/views/bubble_menu_item_factory.h:20:6: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
 std::unique_ptr<views::LabelButton> CreateBubbleMenuItem(

Bug: 819294
Change-Id: I1c48566175e313e964e4a474daa444eb4fccf3bf
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1879229
Commit-Queue: Bret Sepulveda <bsep@chromium.org>
Reviewed-by: Bret Sepulveda <bsep@chromium.org>
Cr-Commit-Position: refs/heads/master@{#709404}

Former-commit-id: 16082c25fb1e017903ea39a53ed167b47df6a276