Fix error when manually running http_server on Windows.
This bug was shaken out by Mac changes in r3095.

$ third_party/python_24/python webkit/tools/layout_tests/layout_package/http_server.py --server start
<snip>
ImportError: No module named layout_package.path_utils

Review URL: http://codereview.chromium.org/7095

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@3257 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: d074bcc717295e16e2fc48edd7ec5a4641f7cc39