tools/gn: depend on allocator_extension.cc to keep bootstrap working
This patch adds the missing base/allocator/allocator_extension.cc to
the sources list to keep the boostrap process working and to fix the
undefined reference error as below:

malloc_dump_provider.cc:(.text+0x92): undefined reference to
`base::allocator::GetNumericProperty(char const*, unsigned long*)'

BUG=None
TEST=./tools/gn/bootstrap/bootstrap.py
TBR=brettw@chromium.org

Review URL: https://codereview.chromium.org/1511203002

Cr-Commit-Position: refs/heads/master@{#364053}

Former-commit-id: 22d5facb2fef65c3085477319a96eeadf3650d3f