chromeos: Disable Tast test security.Mtab to unblock LKGM rolls.
It's failing with:
Error: [mtab.go:41] Root partition is mounted read/write; rootfs verification disabled?

Let's disable it while we figure out a workaround since it's blocking
lkgm rolls.

Bug: 931431
Change-Id: Ibf953f77009ead69902da163b750e53cf43c6ffe
Reviewed-on: https://chromium-review.googlesource.com/c/1468599
Reviewed-by: Dan Erat <derat@chromium.org>
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Cr-Commit-Position: refs/heads/master@{#631479}
Former-commit-id: da307f248a032e89a90a3d2facc87f7d24442276