Revert of Omnibox Watcher: Don't Flag Incidents that are Paste+Enter (patchset #5 id:80001 of https://codereview.chromium.org/795343002/)
Reason for revert:
causes crashes in official builders.
../../chrome/browser/rlz/rlz_unittest.cc:240:14:error: no matching constructor for initialization of 'OmniboxLog'
  OmniboxLog dummy(base::string16(), false, metrics::OmniboxInputType::INVALID,
             ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../chrome/browser/omnibox/omnibox_log.h:22:3: note: candidate constructor not viable: requires 13 arguments, but 12 were provided
  OmniboxLog(
  ^
../../chrome/browser/omnibox/omnibox_log.h:21:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 12 were provided
struct OmniboxLog {
       ^
1 error generated.

Original issue's description:
> Omnibox Watcher: Don't Flag Incidents that are Paste+Enter
>
> The code currently excludes paste-and-go operations.  It should probably
> also exclude paste+enter operations; these are effectively equivalent.
>
> TODO before submitting: test interactively
>
> BUG=
> TBR=bauerb@chromium.org
>
> Committed: https://crrev.com/a626ca8cc49ab3aa6efe6c8777b3ae598e8afcec [formerly c281fb257d2acdd247b0692380d084863e2dd462]
> Cr-Commit-Position: refs/heads/master@{#308233}

TBR=pkasting@chromium.org,grt@chromium.org,bauerb@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=

Review URL: https://codereview.chromium.org/800983005

Cr-Commit-Position: refs/heads/master@{#308256}

Former-commit-id: 58784d83d3c8c6ad72942e5ca8df66d27684edce