Revert of Eliminate kMojoChannelToken usage for render processes (patchset #5 id:80001 of https://codereview.chromium.org/2201183005/ )
Reason for revert:
Compile error in Webkit Mac Builder.

child_thread_impl.cc:272:47: error: non-virtual member function marked 'override' hides virtual member function
                 shell::Connector* connector) override {

Original issue's description:
> Eliminate kMojoChannelToken usage for render processes
>
> Changes RenderProcessHostImpl to connect its IPC Channel
> by requesting a nominal IPC::mojom::ChannelBootstrap
> interface from its shell::Connection to the render process.
>
> Changes ChildThreadImpl to support binding such requests
> by fusing them to its local IPC Channel if the (now deprecated)
> kMojoChannelToken was not provided.
>
> BUG=623396
> R=ben@chromium.org
>
> Committed: https://crrev.com/8a301147d77d5a738c4119cf9f1f1ed190400c85 [formerly 7a7f8f7e6977500d09270ff9d9b3817dda5e5b8a]
> Cr-Commit-Position: refs/heads/master@{#410656}

TBR=ben@chromium.org,tsepez@chromium.org,jschuh@chromium.org,rockot@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=623396

Review-Url: https://codereview.chromium.org/2222373002
Cr-Commit-Position: refs/heads/master@{#410658}

Former-commit-id: 703abc1a6e28e5df8b3757f9aa0757cb995098ca