[Telemetry] Fix abridged-story-set bug.
If you run

./run_benchmark ... --story=browse:media:flickr_infinite_scroll

You get

  ProcessCommandLineArgs at /usr/local/google/home/crouleau/chromium/chromium/src/third_party/catapult/telemetry/telemetry/story/story_filter.py:147
    '--story and --run-abridged-story-set are mutually exclusive.')
AssertionError: --story and --run-abridged-story-set are mutually exclusive.

Because None and False are different. This fixes that.

TBR=perezju@chromium.org
Bug: chromium:965158
Change-Id: Id6b967ad946772b9e111738e25cf1a58ce7a13b9
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/1938447
Reviewed-by: Caleb Rouleau <crouleau@chromium.org>
Commit-Queue: Caleb Rouleau <crouleau@chromium.org>

Former-commit-id: f9d71508e42ba9bd1df2fd3db5c2db3ed375b255