Revert "[blink] Use body loader task runner in ScriptResource"
This reverts commit fd68f2b1e275699bba8f5d1d8e69393a550b0b79 [formerly 142a9f630f6bb52d491298acae8a42c03c2b0f52].

Reason for revert:
Speculative revert due to compile error that closed the tree, where this CL touches related files:
https://ci.chromium.org/p/chromium/builders/ci/linux-rel/22414?blamelist=1#blamelist-tab

The failure is:
In file included from ../../third_party/blink/renderer/platform/loader/fetch/raw_resource.cc:35:
../../third_party/blink/renderer/platform/loader/fetch/resource_fetcher.h:36:10: fatal error: 'third_party/blink/public/mojom/service_worker/service_worker_object.mojom-blink.h' file not found
#include "third_party/blink/public/mojom/service_worker/service_worker_object.mojom-blink.h"

There could be something wrong with the build dependencies so that if you're unlucky the header has not been compiled yet, but maybe most of the time it has already been generated? I could compile locally, so revert is speculative.

Original change's description:
> [blink] Use body loader task runner in ScriptResource
> 
> The ResourceBodyLoader uses a per-request task runner (as of
> https://crrev.com/c/1539219). The manual datapipe reads in ScriptResource
> should therefore also use the same task runner.
> 
> Bug: 943059
> Change-Id: Ia99bd9403ac45cd4f71adb15ddf41c6e8752f892
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1545308
> Reviewed-by: Yutaka Hirano <yhirano@chromium.org>
> Commit-Queue: Leszek Swirski <leszeks@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#646286}

TBR=yhirano@chromium.org,leszeks@chromium.org

Change-Id: I5ca51241c39b24503930aea5b410c5268030a3b1
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 943059
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1547693
Reviewed-by: Henrik Boström <hbos@chromium.org>
Commit-Queue: Henrik Boström <hbos@chromium.org>
Cr-Commit-Position: refs/heads/master@{#646290}
Former-commit-id: 27a3ac1e7a7a7f652df960579045b7eb72359aff