Revert "Move spell checking related files from web/ to new homes in core/."
This reverts commit d54fc197ff642b87f03b68277f13ce769e66158a [formerly a4415da9dfb0dbdff9331d61b18e7e8389adb7e5].

Reason for revert: Breaks WebKit Win Builder (dbg) bot:
https://build.chromium.org/p/chromium.webkit/builders/WebKit%20Win%20Builder%20%28dbg%29/builds/120680 
FAILED: obj/third_party/WebKit/Source/core/editing/editing/TextCheckerClientImpl.obj 
ninja -t msvc -e environment.x86 -- E:\b\c\goma_client/gomacc.exe "E:\b\depot_tools\win_toolchain\vs_files\d3cb0e37bdd120ad0ac4650b674b09e81be45616\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/third_party/WebKit/Source/core/editing/editing/TextCheckerClientImpl.obj.rsp /c ../../third_party/WebKit/Source/core/editing/spellcheck/TextCheckerClientImpl.cpp /Foobj/third_party/WebKit/Source/core/editing/editing/TextCheckerClientImpl.obj /Fd"obj/third_party/WebKit/Source/core/editing/editing_cc.pdb"
e:\b\c\b\win_layout\src\third_party\webkit\source\core\exported\webtextcheckingcompletionimpl.h(43): error C2220: warning treated as error - no 'object' file generated
e:\b\c\b\win_layout\src\third_party\webkit\source\core\exported\webtextcheckingcompletionimpl.h(43): warning C4275: non dll-interface class 'blink::WebTextCheckingCompletion' used as base for dll-interface class 'blink::WebTextCheckingCompletionImpl'
e:\b\c\b\win_layout\src\third_party\webkit\public\web\webtextcheckingcompletion.h(43): note: see declaration of 'blink::WebTextCheckingCompletion'
e:\b\c\b\win_layout\src\third_party\webkit\source\core\exported\webtextcheckingcompletionimpl.h(43): note: see declaration of 'blink::WebTextCheckingCompletionImpl'

Original change's description:
> Move spell checking related files from web/ to new homes in core/.
> 
> - SpellCheckerClientImpl to core/page/.
> - TextCheckerClientImpl to core/editing/spellcheck/.
> - WebTextCheckingCompletionImpl to core/exported/.
> 
> Where required add CORE_EXPORT to make the symmols visible outside of
> core.
> 
> Bug: 712963
> Change-Id: If19c0f250b0c01102df8e561acc750bd36775252
> Reviewed-on: https://chromium-review.googlesource.com/517471
> Commit-Queue: Stuart Langley <slangley@chromium.org>
> Reviewed-by: Kentaro Hara <haraken@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#475507}

TBR=haraken@chromium.org,slangley@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
Bug: 712963

Change-Id: Ib45a17c025b26a54eaf545bf23aaa1e2a969ca10
Reviewed-on: https://chromium-review.googlesource.com/517499
Commit-Queue: Henrik Kjellander <kjellander@chromium.org>
Reviewed-by: Henrik Kjellander <kjellander@chromium.org>
Cr-Commit-Position: refs/heads/master@{#475515}
Former-commit-id: 60f73b2110522209cd44f7c7328dd234def75ba6