[Android]Fix crash on signin into chrome due to an empty account name.
The stack trace is:
java.lang.IllegalArgumentException: the name must not be empty:
at android.accounts.Account.<init>
at org.chromium.sync.signin.AccountManagerHelper.createAccountFromName
at org.chromium.chrome.browser.signin.OAuth2TokenService.notifyRefreshTokenAvailable
at org.chromium.chrome.browser.signin.SigninManager.nativeLogInSignedInUser
at org.chromium.chrome.browser.signin.SigninManager.logInSignedInUser
at org.chromium.chrome.browser.signin.SigninManager$3.onSigninComplete
at org.chromium.chrome.browser.signin.SigninManager.finishSignIn
at org.chromium.chrome.browser.signin.SigninManager.doSignIn
at org.chromium.chrome.browser.signin.SigninManager.startSignIn
at org.chromium.chrome.browser.signin.SigninManager.signInToSelectedAccount

This will change will suppress the crash in release builds.
I have replaced assert with checks in earlier places to better
understand what exactly is failing.
But I think it is probably caused when ValidateAccounts is called w/o
seeding the account id mapping and
MapAccountNameToAccountId(GetSystemAccountNames()) returns empty strings.

Also minor refactoring of code to make it more readable.
Use C++ 11 constructs (foreach loop, find) to make the code concise.
Don't use non-const refs.

BUG=535211

Review URL: https://codereview.chromium.org/1418533010

Cr-Commit-Position: refs/heads/master@{#357622}

Former-commit-id: 15884ad4894edac3d0a6de83fe2cb88aa9c1dee4