Revert of QUIC - Deleted disable_loading_server_info_for_new_servers field trial. (patchset #2 id:40001 of https://codereview.chromium.org/858323002/)
Reason for revert:
This caused a compile failure on iOS bots.

http://build.chromium.org/p/chromium.mac/builders/iOS%20Device/builds/21417

Error from log copied below:
Undefined symbols for architecture armv7:
  "net::QuicStreamFactory::QuicStreamFactory(net::HostResolver*, net::ClientSocketFactory*, base::WeakPtr<net::HttpServerProperties>, net::CertVerifier*, net::ChannelIDService*, net::TransportSecurityState*, net::QuicCryptoClientStreamFactory*, net::QuicRandom*, net::QuicClock*, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<net::QuicVersion, std::__1::allocator<net::QuicVersion> > const&, bool, bool, bool, int, bool, float, bool, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> > const&)", referenced from:
      net::test::QuicStreamFactoryTest::QuicStreamFactoryTest() in quic_stream_factory_test.o
ld: symbol(s) not found for architecture armv7
clang:error: linker command failed with exit code 1 (use -v to see invocation)

Original issue's description:
> QUIC - Deleted disable_loading_server_info_for_new_servers field trial.
> Changed the code not to load server config if there is no alternative
> protocol entry for QUIC. During our experiments, we found that
> disable_loading_server_info_for_new_servers being set to true has
> reduced the latency until crypto handshake completion.
>
> This is a revert of https://codereview.chromium.org/811073004/
>
> We check for alternative protocols only if there is a http_server_properties_ object.
>
> R=rch@chromium.org
>
> Committed: https://crrev.com/42c15a6ea3d6a708e28f1a7663ce3b0b4a0683d4 [formerly 6a454624b8f2827af3ec154bb96e61e7fdcf9e3a]
> Cr-Commit-Position: refs/heads/master@{#312741}

TBR=rch@chromium.org,rtenneti@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/871833002

Cr-Commit-Position: refs/heads/master@{#312748}

Former-commit-id: ec5c9bbcd707a2b3a852346bc21e90c8f32ab5d2