Revert 226914 "Build cast_unittest"
This seems to be preventing things landing through the CQ due to compile warnings on mac using clang, and on win-64.

Error such as 

FAILED: ninja .. ..\..\media\cast\framer\cast_message_builder_unittest.cc ...
  error C2220: warning treated as error - no 'object' file generated
  warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data

FAILED: clang++ ... -c ../../media/cast/audio_receiver/audio_receiver.cc -o obj/media/cast/audio_receiver/cast_audio_receiver.audio_receiver.o
In file included from ../../media/cast/audio_receiver/audio_receiver.cc:5:
../../media/cast/audio_receiver/audio_receiver.h:117:55:error: no newline at end of file [-Werror,-Wnewline-eof]
#endif  // MEDIA_CAST_AUDIO_RECEIVER_AUDIO_RECEIVER_H_

> Build cast_unittest
> 
> Build cast targets on all bots.
> 
> R=justinlin@chromium.org
> 
> Review URL: https://codereview.chromium.org/25891004

TBR=hclam@chromium.org

Review URL: https://codereview.chromium.org/25368003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@226960 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 652c5034fb63b8acdbf9b1a8dcc3549281954416