Revert "cros_sdk: support downloading both xz and bz2 images"
This reverts commit 8b9b634d260cd56df929094b056f8d145d6dd189

Seems to have broken the sdk builder:
http://build.chromium.org/p/chromiumos/builders/chromiumos%20sdk/builds/1606/steps/cbuildbot/logs/stdio

INFO: RunCommand: ['cros_sdk', '--chroot', 'new-sdk-chroot', '--download', '--replace', '--url', 'file:///b/cbuild/built-sdk.tbz2'] in /b/cbuild
Attempting download: file:///b/cbuild/built-sdk.tbz2
cros_sdk: Unhandled exception:
Traceback (most recent call last):
  File "/b/cbuild/chromite/bin/cros_sdk", line 67, in <module>
    ret = target()
  File "/b/cbuild/chromite/scripts/cros_sdk.py", line 398, in main
    chroot_path, options.replace)
  File "/b/cbuild/chromite/scripts/cros_sdk.py", line 205, in CreateChroot
    sdk = FetchRemoteTarballs(urls)
  File "/b/cbuild/chromite/scripts/cros_sdk.py", line 126, in FetchRemoteTarballs
    raise Exception('No valid URLs found!')
Exception: No valid URLs found!
Change-Id: I1b921eb728bc4d7dd995617f0110d3250811806b
Reviewed-on: https://gerrit.chromium.org/gerrit/21845
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>