Revert of Move vr features.gni into its own directory. (patchset #1 id:1 of https://codereview.chromium.org/2840563004/ )
Reason for revert:
Reverting to fix compile issue:

https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium%2FLinux_x64%2F38350%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

fatal error: 'device/vr/features.h' file not found

Original issue's description:
> Move vr features.gni into its own directory.
>
> This fixes some weird issues we were encountering, where we had to hide some build targets behind (!is_ios) after adding our features target to ui/gfx.
> I'm not sure if any extra code was being compiled in, but asserts in gn files were being hit related to things that shouldn't be included on ios.
> It seems other features have already done this sort of thing.
>
> TBR=jochen@chromium.org
> BUG=
>
> Review-Url: https://codereview.chromium.org/2840563004
> Cr-Commit-Position: refs/heads/master@{#467113}
> Committed: https://chromium.googlesource.com/chromium/src/+/9b9b0c98f3df900414ecc20efbe4b33c838ef5f8 [formerly faae24707ba8852ea92b56bcf77aa19878aacdab]

TBR=agrieve@chromium.org,mthiesse@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review-Url: https://codereview.chromium.org/2836013005
Cr-Commit-Position: refs/heads/master@{#467118}

Former-commit-id: ac414937946e8e50537698495b6eb8887875c453