fido: Fix GCC build after c3c04927.
Commit c3c04927 ("Consolidate {Register, Sign}Response data") introduced a
function that looks like this:

    base::Optional<AuthenticatorGetAssertionResponse>
    AuthenticatorGetAssertionResponse::CreateFromU2fSignResponse(...) {
        AuthenticatorGetAssertionResponse response = ...;
        return response;
    }

clang seems to automatically convert |response| to an rvalue reference, but
GCC fails with

    ../../device/fido/authenticator_get_assertion_response.cc: In static member function ‘static base::Optional<device::AuthenticatorGetAssertionResponse> device::AuthenticatorGetAssertionResponse::CreateFromU2fSignResponse(const std::vector<unsigned char>&, const std::vector<unsigned char>&, const std::vector<unsigned char>&)’:
    ../../device/fido/authenticator_get_assertion_response.cc:56:10: error: could not convert ‘response’ from ‘device::AuthenticatorGetAssertionResponse’ to ‘base::Optional<device::AuthenticatorGetAssertionResponse>’
       return response;

Make the code build everywhere by explicitly using std::move() on the return
value.

Change-Id: I2cd50f7d91342c6202ef7f9fbac2a10d65848dc4
Reviewed-on: https://chromium-review.googlesource.com/978005
Reviewed-by: Balazs Engedy <engedy@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#545412}
Former-commit-id: f4c441ef958e654bfb1224e75eb71a7865ffd683