Revert "cros: Fix DCHECK for rlz_lib::UpdateExistingAccessPointRlz"
This reverts commit beb130f1067825e10f4b57a37cdd8d3cf1068c1a [formerly 1d497322e9fd8d9ab1da00767e30c618186151c6].

Reason for revert: This patch breaks Chrome iOS
../../ios/chrome/browser/ios_chrome_main_parts.mm:175:56: error: allocating an object of abstract class type 'RLZTrackerDelegateImpl'
  rlz::RLZTracker::SetRlzDelegate(base::WrapUnique(new RLZTrackerDelegateImpl));


Original change's description:
> cros: Fix DCHECK for rlz_lib::UpdateExistingAccessPointRlz
> 
> In addition to fixing the DCHECK, this CL contains a speculative fix
> for flaky test (crbug.com/907379). The guess for the flakiness is
> (not able to repro the failure locally though):
> 
> |RecordProductEvent| may fail to acquire the |ScopedRlzValueStoreLock|
> when recording the CAI event, because the lock is being taken by
> |UpdateExistingAccessPointRlz|. In tests, the delay for
> |ScheduleDelayedInit| is set to zero, so it's possible for this race
> condition to happen. But in production, the delay is non-zero.
> 
> I don't think we're losing test coverage by disabling
> |UpdateExistingAccessPointRlz| here because the call is a no-op in
> tests, and another test (RlzLibTest.UpdateExistingAccessPointRlz) is
> testing its implementation.
> 
> Bug: 906293, 907379
> Change-Id: I208919f22edc09fc1a739a1efe1909a71e5a2730
> Reviewed-on: https://chromium-review.googlesource.com/c/1353990
> Reviewed-by: Roger Tawa <rogerta@chromium.org>
> Commit-Queue: Wenzhao (Colin) Zang <wzang@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#613172}

TBR=rogerta@chromium.org,wzang@chromium.org

Change-Id: Ie7888c8175087b921972a86e475415032c58db07
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 906293, 907379
Reviewed-on: https://chromium-review.googlesource.com/c/1360274
Reviewed-by: Jérôme Lebel <jlebel@chromium.org>
Commit-Queue: Jérôme Lebel <jlebel@chromium.org>
Cr-Commit-Position: refs/heads/master@{#613447}
Former-commit-id: 52f966107c7d77bc6121cfb843bcd8649801cf0f