Revert "Separate out source sets for src/chromeos subdirs"
This reverts commit f7d42be7813066b7fcca99b15f36b722a8e73c34 [formerly 23537344c6cf3f376fb9e8d87cccd085aff80493].

Reason for revert: broke compilation on CrOS
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8933046391246969968/+/steps/compile/0/stdout

../../services/device/fingerprint/fingerprint_chromeos.cc:12308: error: undefined reference to 'chromeos::DBusThreadManager::Get()'
  ../../services/device/fingerprint/fingerprint_chromeos.cc:12308: error: undefined reference to 'chromeos::DBusThreadManager::GetBiodClient()'
  ../../services/device/fingerprint/fingerprint_chromeos.cc:18906: error: undefined reference to 'chromeos::EmptyVoidDBusMethodCallback()'
  ../../services/device/fingerprint/fingerprint_chromeos.cc:19785: error: undefined reference to 'chromeos::EmptyVoidDBusMethodCallback()'
  ../../services/device/fingerprint/fingerprint_chromeos.cc:34261: error: undefined reference to 'chromeos::DBusThreadManager::Get()'
  ../../services/device/fingerprint/fingerprint_chromeos.cc:34261: error: undefined reference to 'chromeos::DBusThreadManager::GetBiodClient()'

Original change's description:
> Separate out source sets for src/chromeos subdirs
> 
> Its good to break huge packages into smaller packages,
> especially if they are already separate directories.
> 
> This breaks a number of packages out of the chromeos monolith package,
> starting with chromeos/settings, and then any other packages that are
> necessary for the chromeos/settings package to be separated.
> 
> Bug: 446937
> Change-Id: I71909b7e7afa79f4f26d1dbac5217a3f4c769b5b
> Reviewed-on: https://chromium-review.googlesource.com/c/1268315
> Commit-Queue: A Olsen <olsen@chromium.org>
> Reviewed-by: Ryo Hashimoto <hashimoto@chromium.org>
> Reviewed-by: Steven Bennetts <stevenjb@chromium.org>
> Reviewed-by: Dan Erat <derat@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#598302}

TBR=derat@chromium.org,hashimoto@chromium.org,stevenjb@chromium.org,olsen@chromium.org

Change-Id: I816d9e1df68f9d5776724854d19a0ba26f00d732
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 446937
Reviewed-on: https://chromium-review.googlesource.com/c/1273520
Reviewed-by: Vasilii Sukhanov <vasilii@chromium.org>
Commit-Queue: Vasilii Sukhanov <vasilii@chromium.org>
Cr-Commit-Position: refs/heads/master@{#598310}
Former-commit-id: 7c6aeb96da8745b949f1a246a19e41f6d6772f4b