cros_build_lib.CreateTarball: debugging for 'file changed'.
In crbug.com/547055 we have tar commands failing because 'file changed
as we read it', but we have no idea why.

So.... to help track it down, see what other processes have a file open
after we get that error. This is imperfect because we don't look until
after the tar command has exited, but it's better than nothing.

If the bug reproduces extra output will look something like:

ERROR: crbug.com/547055 lsof for file: "inputA"
COMMAND   PID     USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
dd      46597 dgarrett    1w   REG  252,1 39243776 1835416 inputA
E
======================================================================
ERROR: [chromite.lib.cros_build_lib_unittest]
CreateTarballTests.testSuccess
Create a tarfile.
----------------------------------------------------------------------
Traceback (most recent call last):
  File
  "/usr/local/google/home/dgarrett/sand/quick/chromite/lib/timeout_util.py",
  line 170, in TimeoutWrapper
    func(*args, **kwargs)
  File
  "/usr/local/google/home/dgarrett/sand/quick/chromite/lib/cros_build_lib_unittest.py",
  line 1858, in testSuccess
    cros_build_lib.CreateTarball(self.target, self.inputDir,
    inputs=self.inputs)
  File
  "/usr/local/google/home/dgarrett/sand/quick/chromite/lib/cros_build_lib.py",
  line 964, in CreateTarball
    return rc_func(cmd, cwd=cwd, **kwargs)
  File
  "/usr/local/google/home/dgarrett/sand/quick/chromite/lib/cros_build_lib.py",
  line 619, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 1; command: tar --sparse -I /usr/bin/xz
-cf /tmp/testhack/test.tar.xz inputA inputB inputC
tar: inputA: file changed as we read it

cwd=/tmp/testhack/inputs

BUG=chromium:547055
TEST=Unittests + hacked up test to modify a file was it was tarred.

Change-Id: Ib47a1a663b16e3ce159ce7c22c2d540d4c16c850
Reviewed-on: https://chromium-review.googlesource.com/340041
Commit-Ready: Don Garrett <dgarrett@chromium.org>
Tested-by: Don Garrett <dgarrett@chromium.org>
Reviewed-by: Don Garrett <dgarrett@chromium.org>