Revert "Add support for Android SuggestionSpans"
This reverts commit 9b46bc28afb347b18c26b8d7514001db0a396b8e [formerly 3fc7721d2246e06744c759c28be200f7f657ac17].

Reason for revert: Suspecting this CL for the 3 consecutive failures of the TextSuggestionMenuTest#menuDismissesWhenTappingOutside test.

see builds:
https://uberchromegw.corp.google.com/i/chromium.android/builders/Android%20N5X%20Swarm%20Builder/builds/15165
https://uberchromegw.corp.google.com/i/chromium.android/builders/Android%20N5X%20Swarm%20Builder/builds/15166
https://uberchromegw.corp.google.com/i/chromium.android/builders/Android%20N5X%20Swarm%20Builder/builds/15167

Log:
junit.framework.AssertionFailedError: Criteria not met in allotted time.
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at org.chromium.content.browser.test.util.CriteriaHelper.pollInstrumentationThread(CriteriaHelper.java:79)
	at org.chromium.content.browser.test.util.CriteriaHelper.pollUiThread(CriteriaHelper.java:117)
	at org.chromium.content.browser.test.util.CriteriaHelper.pollUiThread(CriteriaHelper.java:138)
	at org.chromium.content.browser.input.TextSuggestionMenuTest.waitForMenuToHide(TextSuggestionMenuTest.java:195)
	at org.chromium.content.browser.input.TextSuggestionMenuTest.menuDismissesWhenTappingOutside(TextSuggestionMenuTest.java:170)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.chromium.base.test.ScreenshotOnFailureStatement.evaluate(ScreenshotOnFailureStatement.java:37)
	at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
	at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.chromium.base.test.BaseJUnit4ClassRunner.runChild(BaseJUnit4ClassRunner.java:175)
	at org.chromium.base.test.BaseJUnit4ClassRunner.runChild(BaseJUnit4ClassRunner.java:40)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.chromium.base.test.BaseJUnit4ClassRunner.run(BaseJUnit4ClassRunner.java:164)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at org.chromium.base.test.BaseChromiumAndroidJUnitRunner.onStart(BaseChromiumAndroidJUnitRunner.java:98)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)

Original change's description:
> Add support for Android SuggestionSpans
> 
> This is the final CL to add support for Android SuggestionSpans (at least ones
> not marked with FLAG_MISSPELLING; there will be one or more additional CLs to
> add support for those). This CL includes:
> 
> - Changes to ImeAdapter to make it pass SuggestionSpans into
>   InputMethodController
> 
> - Changes to InputMethodController to make it create suggestion markers from the
>   passed-in SuggestionSpans
> 
> - Additional methods in TextSuggestionController for getting the list of text
>   suggestions under the cursor, and applying a suggestion
> 
> - More Mojo code to pass information about text suggestions back-and-forth
>   between browser and renderer code
> 
> - Changes to SuggestionsPopupWindow and TextSuggestionHost so we can show either
>   a spell check or a text suggestion menu
> 
> Bug: 672259
> Cq-Include-Trybots: master.tryserver.chromium.linux:linux_layout_tests_slimming_paint_v2
> Change-Id: I3f30543586901baec4648d265874a303efafbd44
> Reviewed-on: https://chromium-review.googlesource.com/627172
> Commit-Queue: Ryan Landay <rlanday@chromium.org>
> Reviewed-by: Ted Choc <tedchoc@chromium.org>
> Reviewed-by: Yoshifumi Inoue <yosin@chromium.org>
> Reviewed-by: Xiaocheng Hu <xiaochengh@chromium.org>
> Reviewed-by: Robert Sesek <rsesek@chromium.org>
> Reviewed-by: Alexandre Elias <aelias@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#501335}

TBR=yosin@chromium.org,dtrainor@chromium.org,torne@chromium.org,aelias@chromium.org,tedchoc@chromium.org,changwan@chromium.org,xiaochengh@chromium.org,rsesek@chromium.org,rlanday@chromium.org

Change-Id: I24641a2a43dffe8056a231a676033bcff39bcae7
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 672259
Cq-Include-Trybots: master.tryserver.chromium.linux:linux_layout_tests_slimming_paint_v2
Reviewed-on: https://chromium-review.googlesource.com/663760
Reviewed-by: Sebastien Seguin-Gagnon <sebsg@chromium.org>
Commit-Queue: Sebastien Seguin-Gagnon <sebsg@chromium.org>
Cr-Commit-Position: refs/heads/master@{#501379}
Former-commit-id: fc6cfd50c4eec740276d7245bb430f73faa77452