Clean out old build products from the checkout.
This helps ensure we don't have really old *.pyc files kicking around,
which can cause trouble for Python upgrades.

Example error this should fix:
  ImportError: Bad magic number in .../chromite/scripts/lddtree.pyc

BUG=chromium:206038
TEST=cbuildbot run

Change-Id: I14af7b7a071686e72dd44059429afddeafe0ccd4
Reviewed-on: https://gerrit.chromium.org/gerrit/46993
Commit-Queue: David James <davidjames@chromium.org>
Tested-by: David James <davidjames@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>