Revert "Support key up/down to move through query history."
This reverts commit a09b88456f64ab95a3ba2da25662c32fedb44699 [formerly 2a5578c2e93ec2b399be0524fe149be16f674436].

Reason for revert:
Suspect "compile" failure on linux-chromeos-dbg: 
https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/linux-chromeos-dbg/9034

https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8929285648013221200/+/steps/compile/0/logs/raw_io.output_failure_summary_/0
[1423/1718] LINK ./ash_unittests
FAILED: ash_unittests
../../ash/assistant/model/assistant_query_history_unittest.cc:38: error: undefined reference to 'ash::AssistantQueryHistory::AssistantQueryHistory(int)'
../../ash/assistant/model/assistant_query_history_unittest.cc:38: error: undefined reference to 'ash::AssistantQueryHistory::GetIterator() const'
...
ash::AssistantQueryHistory_Add_Test::TestBody(): error: undefined reference to 'ash::AssistantQueryHistory::~AssistantQueryHistory()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Original change's description:
> Support key up/down to move through query history.
> 
> We follow the behavior of linux shell:
> (1) Whenever there is a new query, the iterator is reset to the new
>     query.
> (2) Prev of the iterator moves till the first query and stick there.
> (3) Next of the iterator can move beyond last query and get an empty
>     query.
> 
> 
> Bug: b:119504796
> Change-Id: Iee1247359df78b8e2189fa86c3bd1b8b6ebfe612
> Reviewed-on: https://chromium-review.googlesource.com/c/1334271
> Commit-Queue: Yilei Li <yileili@google.com>
> Reviewed-by: Tao Wu <wutao@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#609888}

TBR=wutao@google.com,dmblack@google.com,wutao@chromium.org,yileili@google.com

Change-Id: I837ff88ed6e3b812e4499b33a2b1344d78d4aebe
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: b:119504796
Reviewed-on: https://chromium-review.googlesource.com/c/1345749
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#609903}
Former-commit-id: e825aa6c9f38cc292a1ee1402d0970b1bdf44cf8