MacViews: Fix auto raw pointer deduction in extension_popup.cc.
This is a compile error since r454453.
 error: [chromium-style] auto variable type must not deduce to a raw
  pointer type.

BUG=425229

Review-Url: https://codereview.chromium.org/2737523002
Cr-Commit-Position: refs/heads/master@{#455464}

Former-commit-id: 284939bc567f6153ad877f3a45c40ff0869c5fcb