Fix compilation on renderer/media/stream/media_stream_audio_processor.cc
... due to precision loss:

FAILED: android_clang_arm/obj/third_party/blink/renderer/platform/platform/media_stream_audio_processor.o
../../{path}/media_stream_audio_processor.cc:711:47: error: implicit conversion loses integer precision:
'long long' to 'const int' [-Werror,-Wshorten-64-to-32]
    const int total_delay_ms = capture_delay_ms + render_delay_ms;

In the expression above, |capture_delay_ms| is int64_t, while
|render_delay_ms| is 32bit sized. The result of the sum is stored
in |total_delay_ms|, which is int.

Given that |total_delay_ms| gets passed as parameter to

  webrtc::AudioProcessing::set_stream_delay_ms(int)

... in [1], CL caps |capture_delay_ms| to int too.

[1] //third_party/webrtc/modules/audio_processing/include/audio_processing.h

Issue was observed while Onion souping various files from
content/renderer/media/stream in [2].

[2] https://ci.chromium.org/p/chromium/builders/try/android-kitkat-arm-rel/313772
[3] https://ci.chromium.org/p/chromium/builders/try/android-kitkat-arm-rel/313857

BUG=704136
R=haraken@chromium.org

Change-Id: I3749ca263d60005e8541bf51dbd9a392225a879c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1708660
Auto-Submit: Antonio Gomes <tonikitoo@igalia.com>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Antonio Gomes <tonikitoo@igalia.com>
Cr-Commit-Position: refs/heads/master@{#679516}

Former-commit-id: e0d2cc79445f3d9aa5f7f50c2b74b4b0031e2542