Revert "Add more unbundle packages to sysroots"
This reverts commit 77a1bd2c6c4746cf6de70128e59ee39e9ca23f62 [formerly b828d53cbc4e24dc6f84f25e4b83c6082e717982].

Reason for revert: Causing a build failure on Google Chrome Linux x64
https://ci.chromium.org/buildbot/chromium.chrome/Google%20Chrome%20Linux%20x64/29741

/b/c/b/Google_Chrome_Linux_x64/src/out/Release/../../third_party/llvm-build/Release+Asserts/bin/ld.lld: error: duplicate symbol: exp2f@GLIBC_2.2.5
>>> defined in obj/third_party/swiftshader/src/OpenGL/compiler/swiftshader_opengl_compiler/Intermediate.o
>>> defined in obj/third_party/swiftshader/src/Renderer/swiftshader_renderer/Context.o
/b/c/b/Google_Chrome_Linux_x64/src/out/Release/../../third_party/llvm-build/Release+Asserts/bin/ld.lld: error: duplicate symbol: exp2f@GLIBC_2.2.5
>>> defined in obj/third_party/swiftshader/src/OpenGL/compiler/swiftshader_opengl_compiler/Intermediate.o
>>> defined in obj/third_party/swiftshader/src/Renderer/swiftshader_renderer/Sampler.o
/b/c/b/Google_Chrome_Linux_x64/src/out/Release/../../third_party/llvm-build/Release+Asserts/bin/ld.lld: error: duplicate symbol: powf@GLIBC_2.2.5
>>> defined in obj/third_party/swiftshader/src/Renderer/swiftshader_renderer/Surface.o
>>> defined in obj/third_party/swiftshader/src/Shader/swiftshader_shader/Constants.o
/b/c/b/Google_Chrome_Linux_x64/src/out/Release/../../third_party/llvm-build/Release+Asserts/bin/ld.lld: error: duplicate symbol: powf@GLIBC_2.2.5
>>> defined in obj/third_party/swiftshader/src/Renderer/swiftshader_renderer/Surface.o
>>> defined in obj/third_party/swiftshader/src/Common/swiftshader_common/Math.o

Original change's description:
> Add more unbundle packages to sysroots
> 
> The new packages are necessary to test unbundling of flac, libxslt, and zlib.
> 
> BUG=800977
> R=​thestig
> TBR=mark
> 
> Change-Id: I2c5f88b3819ce000e906cf303fdffa30bdde84cb
> Reviewed-on: https://chromium-review.googlesource.com/981451
> Commit-Queue: Thomas Anderson <thomasanderson@chromium.org>
> Reviewed-by: Lei Zhang <thestig@chromium.org>
> Reviewed-by: Nico Weber <thakis@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#549303}

TBR=thakis@chromium.org,thestig@chromium.org,thomasanderson@chromium.org,mark@chromium.org

Change-Id: I90188d22140d7cdd60f8bbea5b0e88705e498988
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 800977
Reviewed-on: https://chromium-review.googlesource.com/1003532
Reviewed-by: Thomas Anderson <thomasanderson@chromium.org>
Commit-Queue: Thomas Anderson <thomasanderson@chromium.org>
Cr-Commit-Position: refs/heads/master@{#549314}
Former-commit-id: 961ea628cff07b24dbd5974288f41a29bd0ab65d