Revert of 🎊 Have build_config targets depend only on other build_config targets (patchset #3 id:40001 of https://codereview.chromium.org/2095913003/ )
Reason for revert:
Sheriff: reverting on suspicion of breaking the android build.

It looks like the apk packaging step fails when a required component is not found. This change looked like a likely culprit since it changes the naming conventions, and the problem was file not found.

Link to failed build here:
https://build.chromium.org/p/chromium/builders/Android/builds/58342

Relevant section of build logs here:
FAILED: gen/android_webview/system_webview_apk__create_incremental__package.d gen/android_webview/system_webview_apk/system_webview_apk.apk_intermediates_incremental.unfinished.apk
python ../../build/android/gyp/apkbuilder.py --depfile gen/android_webview/system_webview_apk__create_incremental__package.d --resource-apk=gen/android_webview/system_webview_apk/system_webview_apk.apk_intermediates_incremental.ap_ --output-apk=gen/android_webview/system_webview_apk/system_webview_apk.apk_intermediates_incremental.unfinished.apk --assets=@FileArg\(gen/android_webview/system_webview_apk.build_config:assets\) --uncompressed-assets=@FileArg\(gen/android_webview/system_webview_apk.build_config:uncompressed_assets\) --dex-file=gen/build/android/incremental_install/bootstrap.dex --android-abi=armeabi-v7a --native-lib-placeholders=\[\"libfix.crbug.384638.so\"\]
Traceback (most recent call last):
  File "../../build/android/gyp/apkbuilder.py", line 311, in <module>
    main(sys.argv[1:])
  File "../../build/android/gyp/apkbuilder.py", line 307, in main
    depfile_deps=depfile_deps)
  File "/b/build/slave/Android/build/src/build/android/gyp/util/build_utils.py", line 527, in CallAndWriteDepfileIfStale
    pass_changes=True)
  File "/b/build/slave/Android/build/src/build/android/gyp/util/md5_check.py", line 63, in CallAndRecordIfStale
    new_metadata.AddFile(path, _Md5ForPath(path))
  File "/b/build/slave/Android/build/src/build/android/gyp/util/md5_check.py", line 381, in _Md5ForPath
    _UpdateMd5ForFile(md5, path)
  File "/b/build/slave/Android/build/src/build/android/gyp/util/md5_check.py", line 362, in _UpdateMd5ForFile
    with open(path, 'rb') as infile:
IOError: [Errno 2] No such file or directory: u'snapshot_blob.bin'
[34308/48394] ACTION //android_webview/test:android_webview_apk__create_incremental__package(//build/toolchain/android:arm)
FAILED: gen/android_webview/test/android_webview_apk__create_incremental__package.d gen/android_webview/test/android_webview_apk/android_webview_apk.apk_intermediates_incremental.unfinished.apk
python ../../build/android/gyp/apkbuilder.py --depfile gen/android_webview/test/android_webview_apk__create_incremental__package.d --resource-apk=gen/android_webview/test/android_webview_apk/android_webview_apk.apk_intermediates_incremental.ap_ --output-apk=gen/android_webview/test/android_webview_apk/android_webview_apk.apk_intermediates_incremental.unfinished.apk --assets=@FileArg\(gen/android_webview/test/android_webview_apk.build_config:assets\) --uncompressed-assets=@FileArg\(gen/android_webview/test/android_webview_apk.build_config:uncompressed_assets\) --dex-file=gen/build/android/incremental_install/bootstrap.dex --android-abi=armeabi-v7a --native-lib-placeholders=\[\"libfix.crbug.384638.so\"\]
Traceback (most recent call last):
  File "../../build/android/gyp/apkbuilder.py", line 311, in <module>
    main(sys.argv[1:])
  File "../../build/android/gyp/apkbuilder.py", line 307, in main
    depfile_deps=depfile_deps)
  File "/b/build/slave/Android/build/src/build/android/gyp/util/build_utils.py", line 527, in CallAndWriteDepfileIfStale
    pass_changes=True)
  File "/b/build/slave/Android/build/src/build/android/gyp/util/md5_check.py", line 63, in CallAndRecordIfStale
    new_metadata.AddFile(path, _Md5ForPath(path))
  File "/b/build/slave/Android/build/src/build/android/gyp/util/md5_check.py", line 381, in _Md5ForPath
    _UpdateMd5ForFile(md5, path)
  File "/b/build/slave/Android/build/src/build/android/gyp/util/md5_check.py", line 362, in _UpdateMd5ForFile
    with open(path, 'rb') as infile:
IOError: [Errno 2] No such file or directory: u'snapshot_blob.bin'

Original issue's description:
> Have build_config targets depend only on other build_config targets
>
> This works by having android target names follow a naming convention.
> If a target name matches, then it is assumed to have a .build_config file.
> gn gen will raise an error if it doesn't. Likewise, if a target name
> does not match the filters, but does create a .build_config file, gn gen
> will fail on an assert.
>
> This change adds a bunch of naming-convention exceptions, which will
> be addressed in subsequent commits.
>
> Finally, why make this change? This allows all .build_config targets to be
> generated in just a few seconds, which will allow fast generation of
> build.gradle files for Android Studio integration.
>
> BUG=620034
>
> Committed: https://crrev.com/9d542e2626674fdc5bdb4c4da736336669dbea3f [formerly 1029ca88161324eff7a62b1e2eecc84d5acf0f6c]
> Cr-Commit-Position: refs/heads/master@{#402934}

TBR=brettw@chromium.org,agrieve@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=620034

Review-Url: https://codereview.chromium.org/2110943002
Cr-Commit-Position: refs/heads/master@{#402949}

Former-commit-id: 70586184529bdc819367bcdcb4dbaf41d8325559