Revert "Run checkdeps for Java code as part of PRESUBMIT.py"
This reverts commit 9b645dbe0bbc540ad62a877988c35f53ba8af0fa.

This was not rolled in to Chrome and I believe it is causing my GN roll to fail:
https://build.chromium.org/p/tryserver.chromium.linux/builders/linux_chromium_rel_ng/builds/271570/steps/checkdeps%20%28with%20patch%29/logs/stdio

Traceback (most recent call last):
  File "/b/c/b/linux/src/buildtools/checkdeps/checkdeps.py", line 260, in <module>
    sys.exit(main())
  File "/b/c/b/linux/src/buildtools/checkdeps/checkdeps.py", line 255, in main
    deps_checker.CheckDirectory(start_dir)
  File "/b/c/b/linux/src/buildtools/checkdeps/checkdeps.py", line 94, in CheckDirectory
    file_status = checker.CheckFile(rules, full_name)
  File "/b/c/b/linux/src/buildtools/checkdeps/java_checker.py", line 126, in CheckFile
    last_import = line_num
NameError: global name 'line_num' is not defined

TBR=shenghuazhang@chromium.org

Review URL: https://codereview.chromium.org/2191213003 .