sandbox: Explicitly define BrokerSimpleMessage::EntryType's integer type
This fixes the build with GCC after a722110a ("Fix non-signal-safe calls in
BrokerClient"). GCC seems to use a different underlying integer type than
clang and fails with the following message:

    In file included from ../../sandbox/linux/syscall_broker/broker_simple_message.cc:5:
    ../../sandbox/linux/syscall_broker/broker_simple_message.h:80:33: error: enumerator value ‘3183328640’ is outside the range of underlying type ‘int’
       enum class EntryType { DATA = 0xBDBDBD80, INT = 0xBDBDBD81 };
                                     ^~~~~~~~~~
    ../../sandbox/linux/syscall_broker/broker_simple_message.h:80:51: error: enumerator value ‘3183328641’ is outside the range of underlying type ‘int’
       enum class EntryType { DATA = 0xBDBDBD80, INT = 0xBDBDBD81 };
                                                       ^~~~~~~~~~

Bug: 255063, 819294
Change-Id: I21dc7471ea6b5a28a54f7ecfad32f84d62ed16a7
Reviewed-on: https://chromium-review.googlesource.com/1059778
Reviewed-by: Greg Kerr <kerrnel@chromium.org>
Reviewed-by: Tom Sepez <tsepez@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#558751}
Former-commit-id: dcf44780a37e609b1d109f0db8c10840230f7446