pnacl-drivers: use posixpath.normpath instead of os.path.normpath.
Keep consistency of using "/" separators on windows.
E.g., some hardcoded paths in the scripts have "/"
hardcoded in them.

Followup to r14017. Trying to roll the change in showed
a key error:

    temp = self.TempMap[fullpath] + '.' + imtype
KeyError: 'tests\\barebones\\top_of_sandbox.c'

BUG=none
R=dschuff@chromium.org, maruel@chromium.org

Review URL: https://codereview.chromium.org/697193002

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@14022 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: 12f4340f3635f3043095048f2c19e5732a8c7892