Revert "Fetch external images after processing DOM."
This reverts commit 51ea17fbce20844aa07bcd54eef07616a3df5380 [formerly 0e1491041002bd91ef4ab1dc8da5f9d7412f754b].

Reason for revert: Blocking catapult roll

See e.g.:
https://chromium-review.googlesource.com/c/chromium/src/+/724272

Error is:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/b/swarm_slave/w/ir/third_party/catapult/telemetry/telemetry/internal/snap_page_util_unittest.py", line 13, in <module>
    from telemetry.internal import snap_page_util
  File "/b/swarm_slave/w/ir/third_party/catapult/telemetry/telemetry/internal/snap_page_util.py", line 10, in <module>
    import requests
ImportError: No module named requests

Original change's description:
> Fetch external images after processing DOM.
> 
> Bug: chromium:762705
> Change-Id: I0e6769fba105c734dea0316a1c0b60e1991d8297
> Reviewed-on: https://chromium-review.googlesource.com/721725
> Reviewed-by: Ned Nguyen <nednguyen@google.com>
> Commit-Queue: Walter Korman <wkorman@chromium.org>

TBR=nednguyen@google.com,wkorman@chromium.org

Change-Id: I23506d03d2ad0425695599cfd8de48bd7f82355d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: chromium:762705
Reviewed-on: https://chromium-review.googlesource.com/726219
Reviewed-by: Juan Antonio Navarro Pérez <perezju@chromium.org>
Commit-Queue: Juan Antonio Navarro Pérez <perezju@chromium.org>

Former-commit-id: 0ba7405a1f44277040c4d960d6fd00c10b0067ca