Revert "Disable viz-dependent features on WebView"
This reverts commit 0652eb239a1d982daedd5b36fd7c24dbb478af92 [formerly a5cf7b8fa6dd3ed99e74838cf4b7e0c4ac8c80e4].

Reason for revert: Breaking Android WebView L bot/tests:

https://ci.chromium.org/p/chromium/builders/ci/Android%20WebView%20L%20%28dbg%29/8779#overview-tab

java.lang.AssertionError: Android WebView is missing the following declared Blink interfaces: interface OffscreenCanvasRenderingContext2D
interface OffscreenCanvas : EventTarget
interface HTMLCanvasElement : HTMLElement.method transferControlToOffscreen
. Interfaces which are intentionally not exposed in WebView need to be added to not-webview-exposed.txt

Original change's description:
> Disable viz-dependent features on WebView
> 
> This adds a flag to disable:
> - window.OffscreenCanvas
> - Context2DCreation.desynchronize.
> - HTMLCanvasElement.transferControlToOffscreen
> 
> Bug: 940953
> Change-Id: If774e41adbaa6bef94a058f783225b27e5d0669a
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1736804
> Reviewed-by: Alex Moshchuk <alexmos@chromium.org>
> Reviewed-by: Chris Harrelson <chrishtr@chromium.org>
> Reviewed-by: Will Harris <wfh@chromium.org>
> Reviewed-by: Bo <boliu@chromium.org>
> Commit-Queue: Fernando Serboncini <fserb@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#685170}

TBR=boliu@chromium.org,chrishtr@chromium.org,alexmos@chromium.org,fserb@chromium.org,wfh@chromium.org

Change-Id: Ie8105469766f1182c9f6d44c263bc180e5067c2e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 940953
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1744516
Reviewed-by: Matthew Jones <mdjones@chromium.org>
Commit-Queue: Matthew Jones <mdjones@chromium.org>
Cr-Commit-Position: refs/heads/master@{#685253}

Former-commit-id: 1b63a4b7ba498e3f6d25ec5d33053d7bc8aa4404