Revert 251029 "Move Windows-specific code into NativeAppWindowVi..."
> Move Windows-specific code into NativeAppWindowViewsWin
> 
> NativeAppWindowViews has Windows-specific code in #ifdefs. Move this
> into derived class NativeAppWindowViewsWin.
> 
> BUG=None
> 
> Review URL: https://codereview.chromium.org/161753002

Broke windows build:

c:\b\build\slave\win\build\src\chrome\browser\ui\views\apps\native_app_window_views_win.cc(36) : error C2027: use of undefined type 'base::SequencedWorkerPool'
        c:\b\build\slave\win\build\src\base\threading\thread_restrictions.h(82) : see declaration of 'base::SequencedWorkerPool'
c:\b\build\slave\win\build\src\chrome\browser\ui\views\apps\native_app_window_views_win.cc(36) : error C2227: left of '->RunsTasksOnCurrentThread' must point to class/struct/union/generic type

TBR=tmdiep@chromium.org

Review URL: https://codereview.chromium.org/163963002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@251063 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: c7d7c12ffa6810ab1c1a063af244cef6d6c49f49