Revert of Change some new's to base::MakeUnique in metrics_reporting_handler.cc (patchset #2 id:20001 of https://codereview.chromium.org/2901513003/ )
Reason for revert:
Broke the Google Chrome Mac build bot.

metrics_reporting_handler.cc:35:24: error: no member named 'MakeUnique' in namespace 'base

Original issue's description:
> Change some new's to base::MakeUnique in metrics_reporting_handler.cc
>
> Review-Url: https://codereview.chromium.org/2901513003
> Cr-Commit-Position: refs/heads/master@{#474125}
> Committed: https://chromium.googlesource.com/chromium/src/+/88fcf0312bc211f4e46a1eb0a8aa5f9450a658c1 [formerly 3442095e69c627f2341798b54da8fc575b68342e]

TBR=dpapad@chromium.org,drgage@google.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review-Url: https://codereview.chromium.org/2905433003
Cr-Commit-Position: refs/heads/master@{#474126}

Former-commit-id: bb9ea2f988eb1988f1349e4e70ca01171487c9bd