Fix obscure Windows build errors
Compile fails with:
c:\b\build\slave\cr-win-dbg-x64\build\src\third_party\webkit\source\platform\audio\hrtfkernel.cpp(60) :error C2220: warning treated as error - no 'object' file generated
c:\b\build\slave\cr-win-dbg-x64\build\src\third_party\webkit\source\platform\audio\hrtfkernel.cpp(60) : warning C4334: '<<' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)

This CL suppresses the same warnings we used to suppress in webcore_platform.

R=eae@chromium.org

Review URL: https://codereview.chromium.org/26443004

git-svn-id: svn://svn.chromium.org/blink/trunk@159138 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: e3d7aa2e1f1b7da45f1ae9eedb06da88f67502ae