Revert "Reland "[Chromecast] Update mixer unittests""
This reverts commit 2597329e1dbb3a6356736104a769aae148e52514 [formerly 07c7facb93a04628a09a4be8a8badc5e7f9eb94d].

Reason for revert: Caused build error

https://ci.chromium.org/buildbot/chromium.linux/Fuchsia%20ARM64%20Cast%20Audio/5780
../../chromecast/media/cma/backend/stream_mixer_unittest.cc:423:13: error: unused function 'DeathRegex' [-Werror,-Wunused-function]
std::string DeathRegex(const std::string& regex) {
            ^
1 error generated.

Original change's description:
> Reland "[Chromecast] Update mixer unittests"
> 
> This reverts commit 43b2e7a6b8388d70646ba6943270b39fe9dc94b8 [formerly d0ca87de96f2177cceaa8b9d77065062b510577f].
> 
> Added ifdef guard for death tests.
> 
> Bug: internal b/71559266
> Change-Id: I204a00d7a1759a4a18407f5162843366e9229da5
> Reviewed-on: https://chromium-review.googlesource.com/941789
> Reviewed-by: Scott Graham <scottmg@chromium.org>
> Reviewed-by: Luke Halliwell <halliwell@chromium.org>
> Commit-Queue: Kenneth MacKay <kmackay@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#539976}

TBR=halliwell@chromium.org,scottmg@chromium.org,kmackay@chromium.org

Change-Id: I05ba642b66d4bb1e2f1eb8fe8e86c705b361a9a8
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: internal b/71559266
Reviewed-on: https://chromium-review.googlesource.com/942422
Reviewed-by: Tsuyoshi Horo <horo@chromium.org>
Commit-Queue: Tsuyoshi Horo <horo@chromium.org>
Cr-Commit-Position: refs/heads/master@{#539981}
Former-commit-id: 74f1ae4f4148887c249911f0c7f7ca3c38f177f6