Stop checking out third_party/shaderc/src.
Shaderc was dropped altogether from the tree in commit 7f7dd90b6 ("Remove
Shaderc"), but the code was still being checked out for no reason.
Additionally, having third_party/shaderc/src with no accompanying
README.chromium causes tools/licenses.py to fail:

    licenses.LicenseError: missing README.chromium or licenses.py SPECIAL_CASES entry in third_party/shaderc

Bug: 39240, 852620
Change-Id: Ic5e98407149ebccf320a976f2810c93f71ee6658
Reviewed-on: https://chromium-review.googlesource.com/1228053
Reviewed-by: Antoine Labour <piman@chromium.org>
Reviewed-by: Chris Blume <cblume@chromium.org>
Commit-Queue: Raphael Kubo da Costa (CET) <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#592461}
Former-commit-id: 490e363f23a54c896ec09e9e53982b23bb8bc22d