Revert "Mash browser frame: fix rendering in single tab mode"
This reverts commit fe70fb61ced3e0c9fc71d06a8d6d7b0b3f583a82 [formerly da08ce6d117f9871923fa8658c3820c5d6b91684].

Reason for revert: Suspected cause of build failure on linux-chromeos-dbg:
https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/linux-chromeos-dbg/6567

obj/chrome/browser/ui/libui.a(obj/chrome/browser/ui/ui/browser_non_client_frame_view_ash.o):browser_non_client_frame_view_ash.cc:function BrowserNonClientFrameViewAsh::UpdateFrameColors(): error: undefined reference to 'BrowserFrameAsh::kMdWebUiFrameColor'

Original change's description:
> Mash browser frame: fix rendering in single tab mode
> 
> Single tab mode makes the frame the same color as a tab.
> 
> Bug: 854704
> Change-Id: I0d7e790d977858e4ae2942f5f93009c7774bf423
> Reviewed-on: https://chromium-review.googlesource.com/1118977
> Commit-Queue: Evan Stade <estade@chromium.org>
> Reviewed-by: Michael Wasserman <msw@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#571690}

TBR=msw@chromium.org,estade@chromium.org

Change-Id: I0484532a4c9f1ef0914c2b1ba52cd563d341ff3e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 854704
Reviewed-on: https://chromium-review.googlesource.com/1121496
Reviewed-by: Thomas Anderson <thomasanderson@chromium.org>
Commit-Queue: Thomas Anderson <thomasanderson@chromium.org>
Cr-Commit-Position: refs/heads/master@{#571709}
Former-commit-id: 575a70a76428251f9b7b1c4c5a3a3f2738b48dc4