Revert "Make future changes to PrefetchItemState elements safer."
This reverts commit d53205677e9cd495bd7c8032f4e9314307896f5b [formerly 0cd76beff3456cedf8808166adc191b2169d8789].

Reason for revert: Caused ios build failure

https://ci.chromium.org/buildbot/chromium.mac/ios-device-xcode-clang/53845

In file included from ../../components/offline_pages/core/prefetch/finalize_dismissed_url_suggestion_task.cc:5:
../../components/offline_pages/core/prefetch/finalize_dismissed_url_suggestion_task.h:27:7: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
      PrefetchItemState::NEW_REQUEST,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original change's description:
> Make future changes to PrefetchItemState elements safer.
> 
> Introduce new code patterns to improve the likeliness that future
> changes to the elements of PrefetchItemState will be properly handled.
> 
> A new |kOrderedPrefetchItemStates| complements the enum definition by
> providing the full listing of existing states. A new test also checks
> that changes to the enum are reflected in this listing.
> 
> The implementation of GetAllStatesExcept was updated to use this
> official state list and accept a collection of states to filter from its
> result. New calls to this function were also added from tests where
> created a local listing of arbitrary states, what should guarantee that
> new or changed state values would have to be dealt with.
> 
> Finally uses of `default` in switch blocks for PrefetchItemState were
> replaced with the full listing of all possible states so that build
> errors would guide the proper handling of all states.
> 
> Bug: 701939
> Change-Id: I2f303c6922795f509f8046000fdd286c5e0affa9
> Reviewed-on: https://chromium-review.googlesource.com/937944
> Commit-Queue: Carlos Knippschild <carlosk@chromium.org>
> Reviewed-by: Justin DeWitt <dewittj@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#539995}

TBR=dewittj@chromium.org,carlosk@chromium.org,harringtond@chromium.org

Change-Id: I316e8d748221f616579d814c6f560cb6e5d2fdb8
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 701939
Reviewed-on: https://chromium-review.googlesource.com/942561
Reviewed-by: Tsuyoshi Horo <horo@chromium.org>
Commit-Queue: Tsuyoshi Horo <horo@chromium.org>
Cr-Commit-Position: refs/heads/master@{#540012}
Former-commit-id: 106cafd45022db063aa1bf563371793738f158ee