[EFL] WebKit DRT and WTR fail to build due to undefined reference to WTF::MD5::* https://bugs.webkit.org/show_bug.cgi?id=90868
Unreviewed EFL build fix.

Correct CMake configuration to have EFL's DRT and WebKitTestRunner link
WTF library. This is needed to resolve undefined reference to WTF::MD5::*.

Patch by Christophe Dumez <christophe.dumez@intel.com> on 2012-07-10

* DumpRenderTree/efl/CMakeLists.txt:
* WebKitTestRunner/PlatformEfl.cmake:

git-svn-id: svn://svn.chromium.org/blink/trunk@122213 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: d7f882ede2219f5a0e966af1613ed4ad402c8eae