Revert "Implement ProtoChromePromptIPC."
This reverts commit 39fe219ac226306080b2e6cbba96d181e4502372 [formerly e5f1b06d49463065691dfe49b82f1498dae7bd6f].

Reason for revert: suspect causing chrome_cleaner_unittests failure on windows-bots because of:
https://ci.chromium.org/p/chromium/builders/ci/Win10%20Tests%20x64/39695
https://ci.chromium.org/p/chromium/builders/ci/Win7%20Tests%20%281%29/94372
...
UwSPresent/ProtoChromePromptIPCTest.Communication/true_true_PromptAcceptanceACCEPTED_WITHOUT_LOGS_DisconnectedAfterCloseMessageLength
UwSPresent/ProtoChromePromptIPCTest.Communication/true_true_PromptAcceptanceDENIED_DisconnectedAfterCloseMessageLength
UwSPresent/ProtoChromePromptIPCTest.Communication/true_true_PromptAcceptanceACCEPTED_WITH_LOGS_NotDisconnected
UwSPresent/ProtoChromePromptIPCTest.Communication/true_false_PromptAcceptanceACCEPTED_WITH_LOGS_NotDisconnected

E.g. win7 tests' log
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8904641206741120976/+/steps/chrome_cleaner_unittests/0/logs/Deterministic_failure:_NoUwSPresent__x2f_ProtoChromePromptIPCTest.Communication__x2f_false_false_PromptAcceptanceDENIED_NotDisconnected__status_FAILURE_/0
[ RUN      ] NoUwSPresent/ProtoChromePromptIPCTest.Communication/false_false_PromptAcceptanceDENIED_NotDisconnected
[636:3088:0819/200428.002:5454013:ERROR:proto_chrome_prompt_ipc.h(74)] Writing a message to the pipe failed.: The pipe has been ended. (0x6D)
../../chrome/chrome_cleaner/ipc/proto_chrome_prompt_ipc_unittest.cc(648): error: Expected equality of these values:
  error_occurred_
    Which is: true
  should_have_errors
    Which is: false

../../chrome/chrome_cleaner/ipc/proto_chrome_prompt_ipc_unittest.cc(670): error: Expected equality of these values:
  expected_exit_code
    Which is: 0
  rv
    Which is: -1


Original change's description:
> Implement ProtoChromePromptIPC.
> 
> Bug: 969139
> Change-Id: I35d551b6bdb41b4e6bd7689120c21d9d683ad72f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1733747
> Commit-Queue: Oliver Li <olivierli@chromium.org>
> Reviewed-by: Will Harris <wfh@chromium.org>
> Reviewed-by: Joe Mason <joenotcharles@google.com>
> Cr-Commit-Position: refs/heads/master@{#688357}

TBR=joenotcharles@google.com,wfh@chromium.org,olivierli@chromium.org

Change-Id: If19d65f100db413bd68ca5f9bfa60aa426474e00
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 969139
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1760644
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#688406}

Former-commit-id: 68edeb13f4e94d16b89c08777d25d90e5e87b0f6