Revert "various small tweaks to blink's gperf use"
This reverts commit 12c278baa0de05fa2a0b5dbfb8ca895e6f1d7f5c [formerly 2f79d5432935b938db048a1899a0ba1150159397].

Reason for revert: Failed compile on https://ci.chromium.org/buildbot/chromium.win/WinMSVC64/1698

[74/5635] ACTION //third_party/WebKit/Source/platform:color_data(//build/toolchain/win:x64)
FAILED: gen/blink/platform/ColorData.cpp 
E:/b/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe ../../third_party/WebKit/Source/build/scripts/gperf.py ../../third_party/gperf/bin/gperf.exe --key-positions=* -D -s 2 ../../third_party/WebKit/Source/platform/ColorData.gperf --output-file=gen/blink/platform/ColorData.cpp
Traceback (most recent call last):
  File "../../third_party/WebKit/Source/build/scripts/gperf.py", line 88, in <module>
    main()
  File "../../third_party/WebKit/Source/build/scripts/gperf.py", line 85, in main
    generate_gperf(gperf_path, open(infile).read(), gperf_args))
  File "../../third_party/WebKit/Source/build/scripts/gperf.py", line 30, in generate_gperf
    gperf_output = gperf.communicate(gperf_input)[0]
  File "E:\b\depot_tools\win_tools-2_7_6_bin\python\bin\lib\subprocess.py", line 798, in communicate
    return self._communicate(input)
  File "E:\b\depot_tools\win_tools-2_7_6_bin\python\bin\lib\subprocess.py", line 1035, in _communicate
    self.stdin.write(input)
IOError: [Errno 22] Invalid argument

Original change's description:
> various small tweaks to blink's gperf use
> 
> * make gperf.py call generate_gperf() both when it's invoked via
>   use_jinja_gperf_template() as well as when it's called directly
>   as a standalone script
> 
> * make generate_gperf() do massaging of gperf's output to remove
>   uses of the `register` keyword (needed to build with -std=c++17)
>   and replace `/*FALLTHROUGH*/` with real FALLTHROUGH statements
>   (needed for -Wimplicit-fallthrough)
> 
> * remove now-unneeded suppressions for -Wdeprecated-register
> 
> * remove TODO about removing gperf.py; that's from a time when the
>   script was 1 non-comment line long
> 
> * bump check_output() requirement in comment to 3.4 (since that added
>   the input= parameter)
> 
> * add missing dependency on gperf.py to build steps calling it
>   through the jinja interface, so that these edges rerun when
>   gperf.py gets modified
> 
> * add a comment mentioning gperf.py at the start of the generated
>   outputs
> 
> * make :character_data not call gperf.py since it doesn't use gperf,
>   and make it use compiled_action() instead which is made for
>   exactly character_data's use case
> 
> No intended behavior change.
> 
> Bug: 752720,177475
> Change-Id: I56372729bb47787e2d41a5dff2f30804574770f0
> Reviewed-on: https://chromium-review.googlesource.com/891141
> Commit-Queue: Nico Weber <thakis@chromium.org>
> Reviewed-by: Darren Shen <shend@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#533269}

TBR=dcheng@chromium.org,thakis@chromium.org,shend@chromium.org

Change-Id: Iddbf12ba341fa4ea456552f449154bc5d6328073
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 752720, 177475
Reviewed-on: https://chromium-review.googlesource.com/895543
Reviewed-by: Rouslan Solomakhin <rouslan@chromium.org>
Commit-Queue: Rouslan Solomakhin <rouslan@chromium.org>
Cr-Commit-Position: refs/heads/master@{#533276}
Former-commit-id: 873601c652609d47e253c5e03672d80681be6fa7