Revert "Introduce a generic ScopedU2fDiscoveryFactory override."
This reverts commit d0420e10f2edb01a43d313414e007906b364a9d1 [formerly 0588d0628f73cfb7f01639afe4145655cf922744].

Reason for revert: break Linux Builder (dbg) Build 121988 
https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/Linux%20Builder%20%28dbg%29/121988

error: undefined symbol: device::internal::ScopedU2fDiscoveryFactory::ScopedU2fDiscoveryFactory()
>>> referenced by fake_u2f_discovery.cc:85 
error: undefined symbol: device::internal::ScopedU2fDiscoveryFactory::~ScopedU2fDiscoveryFactory()
>>> referenced by fake_u2f_discovery.cc:86 

Original change's description:
> Introduce a generic ScopedU2fDiscoveryFactory override.
> 
>  -- In preparation for introducing ScopedU2fVirtualDiscoveryFactory, create a
>     base class ScopedU2fDiscoveryFactory and let ScopedU2fFakeDiscoveryFactory
>     derive from that.
>  -- In preparation for a wider adoption of FakeU2fDiscovery in tests that could
>     not care less about when a discovery starts, add a version of the fake
>     discovery where SimulateStarted()/SimulateStopped() is called automatically.
> 
> Bug: 785955
> Change-Id: I4b1c9bd962c6e225be45971bbb0d5aad3b05a68a
> Reviewed-on: https://chromium-review.googlesource.com/959001
> Commit-Queue: Balazs Engedy <engedy@chromium.org>
> Reviewed-by: Jan Wilken Dörrie <jdoerrie@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#542507}

TBR=engedy@chromium.org,jdoerrie@chromium.org

Change-Id: Iff7c0aa010fe3ae83262508795bdded90d1f620c
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 785955
Reviewed-on: https://chromium-review.googlesource.com/959282
Reviewed-by: Luna Lu <loonybear@chromium.org>
Commit-Queue: Luna Lu <loonybear@chromium.org>
Cr-Commit-Position: refs/heads/master@{#542539}
Former-commit-id: fe2035ca9c5d0a1d17e26fe8b7fa953dc20a7fe2