fix build break: BindRequest needs to be pure virtual
Otherwise linker fails for the undefined reference to the vtable
of AssistantSettingsManager (not -Impl).

Bug: None
Test: build succeeds
Change-Id: I5b9bcd7ae67c8fcf8ac51f2b6bf53807ed180f8f
Reviewed-on: https://chromium-review.googlesource.com/1011384
Reviewed-by: Muyuan Li <muyuanli@chromium.org>
Commit-Queue: Jun Mukai <mukai@chromium.org>
Cr-Commit-Position: refs/heads/master@{#550401}
Former-commit-id: 1b8cccb1adeeebbd97e78df338e96843407f32c8