Revert of Oilpan: Attempt to fix windows build after r191735 (patchset #1 id:1 of https://codereview.chromium.org/999973002/)
Reason for revert:
broke build

Original issue's description:
> Oilpan: Attempt to fix windows build after r191735
> 
> r191735 caused the following compile error in msvc. This CL attempts to fix the issue by disambiguating it:
> e:\b\build\slave\webkit_win_oilpan__dbg_\build\src\third_party\webkit\source\bindings\core\v8\v8perisolatedata.cpp(272) : error C2666: 'blink::Persistent<T,blink::GlobalPersistents>::operator =' : 2 overloads have similar conversions
>         with
>         [
>             T=blink::ScriptDebugServer
>         ]
>         e:\b\build\slave\webkit_win_oilpan__dbg_\build\src\third_party\webkit\source\platform\heap\handle.h(317): could be 'blink::Persistent<T,blink::GlobalPersistents> &blink::Persistent<T,blink::GlobalPersistents>::operator =(std::nullptr_t)'
>         with
>         [
>             T=blink::ScriptDebugServer
>         ]
>         e:\b\build\slave\webkit_win_oilpan__dbg_\build\src\third_party\webkit\source\platform\heap\handle.h(355): or       'blink::Persistent<T,blink::GlobalPersistents> &blink::Persistent<T,blink::GlobalPersistents>::operator =(const blink::Persistent<T,blink::GlobalPersistents> &)'
>         with
>         [
>             T=blink::ScriptDebugServer
>         ]
>         e:\b\build\slave\webkit_win_oilpan__dbg_\build\src\third_party\webkit\source\platform\heap\handle.h(379): or       'blink::Persistent<T,blink::GlobalPersistents> &blink::Persistent<T,blink::GlobalPersistents>::operator =<blink::ScriptDebugServer>(const WTF::RawPtr<T> &)'
>         with
>         [
>             T=blink::ScriptDebugServer
>         ]
>         while trying to match the argument list '(blink::CrossThreadPersistent<blink::ScriptDebugServer>, WTF::RawPtr<blink::ScriptDebugServer>)'
> 
> BUG=462572
> R=tkent@chromium.org
> 
> Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=191744

TBR=oilpan-reviews@chromium.org,sigbjornf@opera.com,tkent@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=462572

Review URL: https://codereview.chromium.org/997323003

git-svn-id: svn://svn.chromium.org/blink/trunk@191745 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: ed9c788120e8ec66a6888d90052a8506742d335d