Prevent build error with the latest dep roll
The dep roll is currently blocked due to a recent change that adds a new
value to the enum:

  error: enumeration value 'InputEvent_Type_DOUBLE_TAP' not handled in
  switch [-Werror,-Wswitch]

This change unblocks the roll.

https://chromium-review.googlesource.com/c/chromiumos/platform2/+/1873850
https://chromium-review.googlesource.com/c/chromium/src/+/1907072

Test: Build
Bug: None
Change-Id: I00e27b31d35607d094dff60f196e9b7307e9e89e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1913019
Auto-Submit: Victor Hsieh <victorhsieh@chromium.org>
Reviewed-by: David Jacobo <djacobo@chromium.org>
Reviewed-by: Steven Bennetts <stevenjb@chromium.org>
Commit-Queue: Victor Hsieh <victorhsieh@chromium.org>
Cr-Commit-Position: refs/heads/master@{#714720}

Former-commit-id: a41a401f2c3ee7e7b64a1fef7e882d01ab6641fe