Mark URLRequestTestFTP.FTPGetTestAnonymous as flaky.
It failed here:
http://codf2.jail:8010/builders/Modules%20XP/builds/22848/steps/net_unittests/logs/stdio
[ RUN      ] URLRequestTestFTP.FTPGetTestAnonymous
.\url_request\url_request_unittest.cc(2094): error: Value of: static_cast<int>(file_size)
  Actual: 1563
  Expected: d.bytes_received()
  Which is: 0
[  FAILED  ] URLRequestTestFTP.FTPGetTestAnonymous (15 ms)

It passed in the next (forced) build here:
http://codf2.jail:8010/builders/Modules%20XP/builds/22849/steps/net_unittests/logs/stdio
[ RUN      ] URLRequestTestFTP.FTPGetTestAnonymous
[       OK ] URLRequestTestFTP.FTPGetTestAnonymous (16 ms)

BUG=25045
TEST=test is greener than before
TBR=phajdan.jr@chromium.org

Review URL: http://codereview.chromium.org/561062

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@38047 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 7df7001734cc8ec68d14571cccbe88ef439a09a5