Reland ""Add DeviceOffHoursController unittests""
This reverts commit 26732f028895a1dc9c6deeb31b8635fe0ee32ba9 [formerly 9508a956d8207eee48a70beffb865bfc04c40913].

Reason for revert: Fix compilation breakage and reland the original CL:
https://chromium-review.googlesource.com/723744

Original change's description:
> Revert "Add DeviceOffHoursController unittests"
> 
> This reverts commit cad5dd469229765da10827141c615c49c9a1d2be [formerly 3ccdaef7ede99969a15fce8ebb8394895de92c1c].
> 
> Reason for revert: This breaks compilation on ChromeOS.  Maybe check your deps?
> 
> Sample failure:
> 
> ../../chrome/browser/chromeos/policy/off_hours/device_off_hours_controller_unittest.cc:16:10: fatal error: 'chrome/browser/chromeos/policy/proto/chrome_device_policy.pb.h' file not found
> #include "chrome/browser/chromeos/policy/proto/chrome_device_policy.pb.h"
>          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> 
> (https://logs.chromium.org/v/?s=chromium%2Fbb%2Ftryserver.chromium.linux%2Flinux_chromium_chromeos_rel_ng%2F533304%2F%2B%2Frecipes%2Fsteps%2Fcompile__with_patch_%2F0%2Fstdout)
> 
> 
> Original change's description:
> > Add DeviceOffHoursController unittests
> > 
> > Add FakeClock classes
> > Add unittests for:
> > * basic DeviceOffHoursController
> > * Convert*
> > * Apply*
> > * UpdateOffHoursMode
> > * SuspendDone observer method
> > 
> > Original CL written by Daria Yakovleva: https://crrev.com/c/675243
> > 
> > Bug: 739713
> > 
> > Author: Daria Yakovleva <yakovleva@google.com>
> > Change-Id: I35929e374d05713066027b86946f77c4c50f8473
> > Reviewed-on: https://chromium-review.googlesource.com/723744
> > Commit-Queue: Sergey Poromov <poromov@chromium.org>
> > Reviewed-by: Maksim Ivanov <emaxx@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#510202}
> 
> TBR=emaxx@chromium.org,poromov@chromium.org
> 
> Change-Id: Idc2cece25e75d9972d8a242e346e465148044a57
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 739713
> Reviewed-on: https://chromium-review.googlesource.com/729620
> Reviewed-by: Matt Menke <mmenke@chromium.org>
> Commit-Queue: Matt Menke <mmenke@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#510294}

Change-Id: I05f10877a280dd00ea78640935884c1bac1dfea5
Bug: 739713
Reviewed-on: https://chromium-review.googlesource.com/730403
Reviewed-by: Maksim Ivanov <emaxx@chromium.org>
Reviewed-by: Sergey Poromov <poromov@chromium.org>
Commit-Queue: Sergey Poromov <poromov@chromium.org>
Cr-Commit-Position: refs/heads/master@{#510424}
Former-commit-id: 27a27f80fe1e3bbbb22821afe223093d9147c136