Revert of Add display::GetDisplayNearestView (patchset #17 id:790001 of https://codereview.chromium.org/2688413007/ )
Reason for revert:
This CL causes a compile failure on a Mac bot:
https://build.chromium.org/p/chromium/builders/Mac/builds/24801

[38396/49613] CXX obj/extensions/browser/browser_tests/system_display_apitest.o
FAILED: obj/extensions/browser/browser_tests/system_display_apitest.o
(snip)
../../extensions/browser/api/system_display/system_display_apitest.cc:58:37: error: non-virtual member function marked 'override' hides virtual member function
      gfx::NativeView window) const override {
                                    ^
../../ui/display/screen.h:61:19: note: hidden overloaded virtual function 'display::Screen::GetDisplayNearestWindow' declared here: type mismatch at 1st parameter ('gfx::NativeWindow' (aka 'NSWindow *') vs 'gfx::NativeView' (aka 'NSView *'))
  virtual Display GetDisplayNearestWindow(gfx::NativeWindow window) const = 0;
                  ^
../../extensions/browser/api/system_display/system_display_apitest.cc:200:61: error: allocating an object of abstract class type 'extensions::MockScreen'
      : provider_(new MockDisplayInfoProvider), screen_(new MockScreen) {}
                                                            ^
../../ui/display/screen.h:61:19: note: unimplemented pure virtual method 'GetDisplayNearestWindow' in 'MockScreen'
  virtual Display GetDisplayNearestWindow(gfx::NativeWindow window) const = 0;
                  ^
2 errors generated.

Original issue's description:
> Add display::GetDisplayNearestView
>
> Add a method that gets the display with a given gfx::NativeView.
> The present API |display::GetDisplayNearestWindow| was also updated
> to accept gfx::NativeWindow to match its signature.
>
> BUG=671401
> CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.linux:linux_site_isolation
> TBR=benwells@chromium.org,sky@chromium.org,boliu@chromium.org,msw@chromium.org,halliwell@chromium.org,bshe@chromium.org,alexclarke@chromium.org
>
> Review-Url: https://codereview.chromium.org/2688413007
> Cr-Commit-Position: refs/heads/master@{#457016}
> Committed: https://chromium.googlesource.com/chromium/src/+/4ef0457395106bba32c2f41ecd62a0a9c78638d8 [formerly 93bb5a29073d2cb41b20d3cc6cf59459a3906043]

TBR=oshima@chromium.org,boliu@chromium.org,tapted@chromium.org,benwells@chromium.org,sky@chromium.org,msw@chromium.org,halliwell@chromium.org,bshe@chromium.org,alexclarke@chromium.org,jinsukkim@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=671401

Review-Url: https://codereview.chromium.org/2747143005
Cr-Commit-Position: refs/heads/master@{#457025}

Former-commit-id: a0c89e94b3310fa12b58db00eaca0e66c2f98c7b