[MIPS] Add missing -L flag to mips newlib nexe action
Add missing -L flag to untrusted.gypi to match the -B flag.

This fixes the following link issues with browser_tests:

  error: cannot find -lppapi_cpp
  error: cannot find -lppapi

Review URL: https://codereview.chromium.org/1809203002


Former-commit-id: 4bac1a1e26d22d2074d271581ae86425a4e8296f