[Qt][WK2] Broken build with undefined reference to shm_open and shm_unlink https://bugs.webkit.org/show_bug.cgi?id=76538
Patch by Luciano Wolf <luciano.wolf@openbossa.org> on 2012-01-18
Reviewed by Tor Arne Vestbø.

The -lrt parameter was coming before -lWebKit2 during linkage.

Moved rt lib inclusion from Source/api.pri to WebKit2.pri as it should be aware
of its own dependencies instead of letting WebKit guess about. Letting
it on api.pri can lead to a wrong parameter's order during linker phase.
Ubuntu 11.10 was giving errors about SharedMemory (shm_open and
shm_unlink undefined symbols).

.:

* Source/api.pri:

Source/WebKit2:

The issue was fixed with the help of Aloisio Almeida and Lauro Venancio.

* WebKit2.pri:

git-svn-id: svn://svn.chromium.org/blink/trunk@105305 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: c36754859e203c5e34cd32ab923a01976dfb69b4