Revert "Merge all native enums RequestContextFrameType into single mojo enum"
This reverts commit d810cce3f02494425e6e3b49819b30d6c188790f [formerly a5b3a66158491e1dc9903c6632e8060fe81200a6].

Reason for revert:
This seems to be causing flaky build errors on chromeos-amd64-generic-rel:
https://ci.chromium.org/buildbot/tryserver.chromium.chromiumos/chromeos-amd64-generic-rel/

In file included from ../../third_party/WebKit/Source/platform/heap/ThreadState.cpp:60:
In file included from ../../third_party/WebKit/public/platform/Platform.h:56:
In file included from ../../third_party/WebKit/public/platform/WebURLLoader.h:36:
../../third_party/WebKit/public/platform/WebURLRequest.h:41:10: fatal error: 'services/network/public/interfaces/request_context_frame_type.mojom-shared.h' file not found
#include "services/network/public/interfaces/request_context_frame_type.mojom-shared.h"

Probably need to add some DEPS to BUILD.gn. I will revert for now.

Original change's description:
> Merge all native enums RequestContextFrameType into single mojo enum
> 
> This CL creates blink.mojom.RequestContextFrameType enum type and uses
> it to replace existing native enums content::RequestContextFrameType and
> blink::WebURLRequest::FrameType.
> 
> This is the preparation to impl the blink.mojom.ServiceWorkerClientInfo,
> and finally to remove content::ExtendableMessageEventSource, which is an
> incremental step toward Onion Soup: having less dependence on content types
> for service worker.
> 
> BUG=782528
> 
> Change-Id: I6f7787575f1583297a27a0213b1440d01e94e2dd
> Reviewed-on: https://chromium-review.googlesource.com/791916
> Commit-Queue: Xiaofeng Zhang <xiaofeng.zhang@intel.com>
> Reviewed-by: Kinuko Yasuda <kinuko@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Reviewed-by: Tom Sepez <tsepez@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#523699}

TBR=falken@chromium.org,horo@chromium.org,dcheng@chromium.org,kinuko@chromium.org,yhirano@chromium.org,tsepez@chromium.org,shimazu@chromium.org,xiaofeng.zhang@intel.com

Change-Id: I25d74d983877227b5482a441f6cebb74374751b9
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 782528
Reviewed-on: https://chromium-review.googlesource.com/823332
Reviewed-by: Matt Falkenhagen <falken@chromium.org>
Commit-Queue: Matt Falkenhagen <falken@chromium.org>
Cr-Commit-Position: refs/heads/master@{#523710}
Former-commit-id: 5c02cf404aea00f1e495913fc64f5043e00e1047