Revert "[Benchmarks] Smoke tests lay groundwork for move to story_filter."
This reverts commit bc9a0b6b3861ff4017bf6f92bc56644941eb5d01 [formerly 37d44dbbf4fdd2569ae193119dfc7e9e1b4c570f].

Reason for revert: Catapult roller failing with:

  AttributeError: type object 'StoryFilterFactory' has no attribute '_expectations'
https://chromium-swarm.appspot.com/task?id=47eb08c183837510

Original change's description:
> [Benchmarks] Smoke tests lay groundwork for move to story_filter.
> 
> This change
> https://chromium-review.googlesource.com/c/catapult/+/1839176
> makes it so that expectations config is passed to story_filter.py
> using the project config (sometimes referred to as the
> "environment"). This change lays the groundwork for that future
> change. Until that change is committed, this is a no-op change.
> 
> This change first requires this catapult-side change
> https://chromium-review.googlesource.com/c/catapult/+/1854882
> to make sure that we don't pass an invalid argument to
> GetRunOptions().
> 
> 
> Bug: 985103
> Change-Id: Idd53aaf7f84e792b0d7a7d0db6b45ce0562fb5f4
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1854794
> Commit-Queue: Caleb Rouleau <crouleau@chromium.org>
> Reviewed-by: Juan Antonio Navarro Pérez <perezju@chromium.org>
> Reviewed-by: Rakib Hasan <rmhasan@google.com>
> Auto-Submit: Caleb Rouleau <crouleau@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#706080}

TBR=perezju@chromium.org,crouleau@chromium.org,rmhasan@google.com

Change-Id: I9cdcf778d4feaa3ab4d1dd1bd5385b53e99e4f21
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 985103
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1864671
Reviewed-by: Juan Antonio Navarro Pérez <perezju@chromium.org>
Commit-Queue: Juan Antonio Navarro Pérez <perezju@chromium.org>
Cr-Commit-Position: refs/heads/master@{#706332}

Former-commit-id: ee6a927d07993b39ffac6189f217e96f2b830bf7