Revert of Mac: Enable NSCGLSurface for real (patchset #1 id:1 of https://codereview.chromium.org/1211893002/)
Reason for revert:
Suspected cause of test failure:

[2/2] telemetry.internal.backends.chrome_inspector.inspector_page_unittest.InspectorPageTest.testCaptureScreenshot failed unexpectedly 4.1614s:
  Traceback (most recent call last):
    File "/b/build/slave/Mac10_10_Tests/build/src/tools/telemetry/telemetry/decorators.py", line 118, in wrapper
      func(*args, **kwargs)
    File "/b/build/slave/Mac10_10_Tests/build/src/tools/telemetry/telemetry/internal/backends/chrome_inspector/inspector_page_unittest.py", line 45, in testCaptureScreenshot
      self.assertEquals(0xFF, res[1])
  AssertionError: 255 != 249

https://build.chromium.org/p/chromium.mac/builders/Mac10.10%20Tests/builds/720

Original issue's description:
> Mac: Enable NSCGLSurface for real
>
> Bugs that caused the previous revert have been found and fixed.
>
> BUG=496484
> TBR=zmo
>
> Committed: https://crrev.com/087293cc388f1b47ca833bac13cfa8dcdb222fd9 [formerly 860e477abf39606eba605f132ee96d9febce8731]
> Cr-Commit-Position: refs/heads/master@{#336170}

TBR=ccameron@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=496484

Review URL: https://codereview.chromium.org/1207273002

Cr-Commit-Position: refs/heads/master@{#336190}

Former-commit-id: 985852f1e9b0947565939993a59d04d63f39f295