binhost_test: overhaul AssertChromePrebuilts output
The current failure message looks like:
  ERROR: eve-paladin cannot find Chrome prebuilts -- <long CompatId object>

This then requires people to manually load up all the configs and
see what should have matched and what changed.  Lets improve this
output by doing some of that precalculation ourselves.  Now we have:
  ERROR: eve-paladin cannot find Chrome prebuilts (probably due to USE flags mismatch)
  Build settings: <long CompatId object>
  Closest matching configs:
      Boards: <BoardKeys>
          USE changes: <list of USE flag differences>
          Build settings <long CompatId object>
      Boards: <BoardKeys>
          USE changes: <list of USE flag differences>
          Build settings <long CompatId object>
      ...more...

The CompatId object can be long, so it can still make these things
wrap together.  But hopefully this somewhat structured output should
be enough for developers to dig through quickly.

BUG=chromium:872351
TEST=precq passes

Change-Id: I1be7d4cdf190998d64dce3f4705bd6da4587b428
Reviewed-on: https://chromium-review.googlesource.com/1213642
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Lann Martin <lannm@chromium.org>