Revert r13622, r13615 and r13614 (changes to the untrusted Gyp build)
This reverts:

r13614 (bradnelson): "Vary build settings on fastbuild + configuration + buildtype."
r13615 (bradnelson): "Only pass -O2 as a link option for pnacl test pexes."
r13622 (dschuff): "Build PNaCl debug/fastbuild IRT with O2 instead of O0"

r13614 broke the Chromium build, causing the IRT link to fail with
errors including the following:

../../out/Release/gen/tc_irt/lib64/libgles2_implementation_nacl.a(gles2_implementation_dc9b550c.o):
error: undefined reference to 'gfx::RectBase<gfx::Rect, gfx::Point, gfx::Size,
gfx::Insets, gfx::Vector2d, int>::x() const'
../../out/Release/gen/tc_irt/lib64/libgles2_implementation_nacl.a(gles2_implementation_dc9b550c.o):
error: undefined reference to 'gfx::RectBase<gfx::Rect, gfx::Point, gfx::Size,
gfx::Insets, gfx::Vector2d, int>::y() const'

r13622 was an attempted fix which apparently fixed the x86-64 IRT build
(using the PNaCl toolchain), but the error persisted with the x86-32 IRT
build (using the NaCl GCC toolchain).

This appears to be a C++ template instantiation problem.

BUG=https://code.google.com/p/chromium/issues/detail?id=388035
TEST=trybots
R=dschuff@chromium.org

Review URL: https://codereview.chromium.org/471023004

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@13623 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: bbcee2b24a58a47e70f4e9e106eb08ce9c6f533f