Revert "Add the ability to give advice on forbidden identifiers."
This reverts commit 174cb3289d4accd853e54145fdd0e7f2e6bb7cc4 [formerly 6592bd3098726ac82ea318f4946abf9f7f15d912].

Reason for revert:

OK
  checking owners took a long time: 1813ms
Traceback (most recent call last):
  File "/home/bratell/src/google/depot_tools/metrics.py", line 225, in print_notice_and_exit
    yield
  File "/home/bratell/src/google/depot_tools/git_cl.py", line 6110, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/bratell/src/google/depot_tools/git_cl.py", line 6092, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/home/bratell/src/google/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/home/bratell/src/google/depot_tools/git_cl.py", line 5086, in CMDupload
    return cl.CMDUpload(options, args, orig_args)
  File "/home/bratell/src/google/depot_tools/git_cl.py", line 1551, in CMDUpload
    change=change, parallel=options.parallel)
  File "/home/bratell/src/google/depot_tools/git_cl.py", line 1485, in RunHook
    parallel=parallel)
  File "/home/bratell/src/google/depot_tools/presubmit_support.py", line 1547, in DoPresubmitChecks
    results += executer.ExecPresubmitScript(presubmit_script, filename)
  File "/home/bratell/src/google/depot_tools/presubmit_support.py", line 1454, in ExecPresubmitScript
    result = eval(function_name + '(*__args)', context)
  File "<string>", line 1, in <module>
  File "<string>", line 182, in CheckChangeOnUpload
  File "<string>", line 164, in _CheckForForbiddenChromiumCode
  File "tools/audit_non_blink_usage.py", line 604, in check
    if not _check_entries_for_identifier(entries, identifier):
  File "tools/audit_non_blink_usage.py", line 548, in _check_entries_for_identifier
    if entry['disallowed'].match(identifier):
AttributeError: 'list' object has no attribute 'match'


Original change's description:
> Add the ability to give advice on forbidden identifiers.
> 
> Add addvice for base::Bind*
> 
> Currently we are told not to use something, but it's not always clear what
> we should use instead. This allows adding advice for the correct alternative
> to the forbidden identifies.
> 
> Change-Id: Iaadab609452d2413fdd39a31c80e3924467c42d3
> Reviewed-on: https://chromium-review.googlesource.com/c/1253526
> Reviewed-by: Kent Tamura <tkent@chromium.org>
> Reviewed-by: Taiju Tsuiki <tzik@chromium.org>
> Commit-Queue: Fergal Daly <fergal@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#596178}

TBR=tkent@chromium.org,tzik@chromium.org,fergal@chromium.org

Change-Id: I16684eee34a7e547cb6d923f38ee669e13394223
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/1258812
Reviewed-by: Fergal Daly <fergal@chromium.org>
Commit-Queue: Fergal Daly <fergal@chromium.org>
Cr-Commit-Position: refs/heads/master@{#596186}
Former-commit-id: 5d4153948d3e80c770db162d5e20ae1b273beeb4