Revert of Android: Trust large random numbers for temp files (patchset #1 id:1 of https://codereview.chromium.org/1402353002/ )
Reason for revert:
Likely cause of Android GN breakage in stack_tool_for_tombstones:
https://build.chromium.org/p/chromium.linux/builders/Android%20GN/builds/31358

Traceback (most recent call last):
  File "/b/build/slave/Android_GN/build/src/build/android/tombstones.py", line 257, in <module>
    sys.exit(main())
  File "/b/build/slave/Android_GN/build/src/build/android/tombstones.py", line 251, in main
    tombstones += _GetTombstonesForDevice(device, options)
  File "/b/build/slave/Android_GN/build/src/build/android/tombstones.py", line 197, in _GetTombstonesForDevice
    'data': _GetTombstoneData(device, tombstone_file)}]
  File "/b/build/slave/Android_GN/build/src/build/android/tombstones.py", line 79, in _GetTombstoneData
    '/data/tombstones/' + tombstone_file, as_root=True).splitlines()
  File "/b/build/slave/Android_GN/build/src/build/android/devil/android/decorators.py", line 53, in timeout_retry_wrapper
    return timeout_retry.Run(impl, timeout, retries, desc=desc)
  File "/b/build/slave/Android_GN/build/src/build/android/devil/utils/timeout_retry.py", line 161, in Run
    error_log_func=error_log_func)
  File "/b/build/slave/Android_GN/build/src/build/android/devil/utils/reraiser_thread.py", line 186, in JoinAll
    self._JoinAll(watcher, timeout)
  File "/b/build/slave/Android_GN/build/src/build/android/devil/utils/reraiser_thread.py", line 158, in _JoinAll
    thread.ReraiseIfException()
  File "/b/build/slave/Android_GN/build/src/build/android/devil/utils/reraiser_thread.py", line 81, in run
    self._ret = self._func(*self._args, **self._kwargs)
  File "/b/build/slave/Android_GN/build/src/build/android/devil/utils/timeout_retry.py", line 154, in <lambda>
    child_thread = reraiser_thread.ReraiserThread(lambda: func(*args, **kwargs),
  File "/b/build/slave/Android_GN/build/src/build/android/devil/android/decorators.py", line 44, in impl
    return f(*args, **kwargs)
  File "/b/build/slave/Android_GN/build/src/build/android/devil/android/device_utils.py", line 1441, in ReadFile
    return self._ReadFileWithPull(device_temp.name)
  File "/b/build/slave/Android_GN/build/src/build/android/devil/android/device_utils.py", line 1384, in _ReadFileWithPull
    self.adb.Pull(device_path, host_temp_path)
  File "/b/build/slave/Android_GN/build/src/build/android/devil/android/sdk/adb_wrapper.py", line 247, in Pull
    cmd, 'File not found on host: %s' % local, device_serial=str(self))
devil.android.device_errors.AdbCommandFailedError: (device: 0528be3e0a286d60) adb pull /data/local/tmp/temp_file-ff7f09e4cdfa0 /tmp/tmpYJtAXL/tmp_ReadFileWithPull: failed and output:
- File not found on host: /tmp/tmpYJtAXL/tmp_ReadFileWithPull

Original issue's description:
> Android: Trust large random numbers for temp files
>
> Saves a good amount of time (150ms per) and log pollution to not execute an adb
> command for each temp file.
>
> BUG=540857
>
> Committed: https://crrev.com/a5a882f8e9325c782db666c27831cc82f119ced7
> Cr-Commit-Position: refs/heads/master@{#354332}

TBR=jbudorick@chromium.org,agrieve@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=540857

Review URL: https://codereview.chromium.org/1412433003

Cr-Commit-Position: refs/heads/master@{#354367}

Former-commit-id: 04039962c6a2aae81750c4a09da524f10092a8ba