Use EXPECT_FALSE instead of EXPECT_EQ(false to fix linux build with gcc
gcc-4.9.3:
error: converting 'false' to pointer type for argument 1 of
'char testing::internal::IsNullLiteralHelper(testing::internal::Secret*)'
[-Werror=conversion-null]

ash/display/json_converter_unittest.cc
chrome/renderer/safe_browsing/phishing_classifier_delegate_browsertest.cc
third_party/WebKit/Source/core/layout/ImageQualityControllerTest.cpp

BUG=461205

R=darin@chromium.org

TEST= is_clang=false && ninja -C out/build all
CQ_INCLUDE_TRYBOTS=tryserver.blink:linux_blink_rel

Review-Url: https://codereview.chromium.org/2013573003
Cr-Commit-Position: refs/heads/master@{#396312}

Former-commit-id: 89d6af1e4ddfd34be8aeddbc8194f91504484d4d