Fix failure when time_to_deadline is None.
Fixes the following error introduced by CL:237075

TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'.

BUG=none
TEST=Unit tests.

Change-Id: I089cbb4ed93be3c2d9f8a31ba0cd48ffd4ea41f6
Reviewed-on: https://chromium-review.googlesource.com/238070
Trybot-Ready: David James <davidjames@chromium.org>
Reviewed-by: David James <davidjames@chromium.org>
Tested-by: David James <davidjames@chromium.org>