[jumbo] avoid operator clashes between media_devices.h and page_state.h
CL https://chromium-review.googlesource.com/c/chromium/src/+/1019245 seems
to have introduced a jumbo build failure:

./../../content/browser/renderer_host/media/media_devices_manager.cc:704:37: error: reference to overloaded function could not be resolved; did you mean to call it?
                  ignore_group_id ? operator== : EqualDeviceAndGroupID)) {
                                    ^~~~~~~~~~
../../content/common/media/media_devices.h:52:6: note: possible target for call
bool operator==(const MediaDeviceInfo& first, const MediaDeviceInfo& second);
     ^
../../content/public/common/page_state.h:63:13: note: possible target for call
inline bool operator==(const PageState& a, const PageState& b) {
            ^

Let's move page_state.h's ==/!= operators out of the global scope, to avoid this.

TBR=avi@chromium.org

Bug: 834281
Change-Id: I27f0493ee2d2957b8318c969edd5615ec4dab687
Reviewed-on: https://chromium-review.googlesource.com/1042308
Commit-Queue: Morten Stenshorne <mstensho@chromium.org>
Reviewed-by: Guido Urdaneta <guidou@chromium.org>
Cr-Commit-Position: refs/heads/master@{#555767}
Former-commit-id: 621060052dcb5bbb70c238d79047fa1feaecffb7