Revert 286542 "ui/aura: Enable the build of demo, bench and unit..."
Likely cause to break:
http://build.chromium.org/p/chromium.linux/builders/Linux%20GN%20%28dbg%29/builds/10322

obj/ui/events/test/test_support.event_generator.o:../../ui/events/test/event_generator.cc:function ui::test::EventGenerator::EventGenerator(aura::Window*): error: undefined reference to 'ui::test::EventGenerator::CreateDefaultPlatformDelegate(ui::test::EventGenerator*, aura::Window*, aura::Window*)'
obj/ui/events/test/test_support.event_generator.o:../../ui/events/test/event_generator.cc:function ui::test::EventGenerator::EventGenerator(aura::Window*, gfx::Point const&): error: undefined reference to 'ui::test::EventGenerator::CreateDefaultPlatformDelegate(ui::test::EventGenerator*, aura::Window*, aura::Window*)'
obj/ui/events/test/test_support.event_generator.o:../../ui/events/test/event_generator.cc:function ui::test::EventGenerator::EventGenerator(aura::Window*, aura::Window*): error: undefined reference to 'ui::test::EventGenerator::CreateDefaultPlatformDelegate(ui::test::EventGenerator*, aura::Window*, aura::Window*)'

> ui/aura: Enable the build of demo, bench and unittests in GN world.
> 
> They now link on Linux so we can enable them.
> 
> BUG=None
> TEST=gn gen out/Debug_gn && ninja -C out/Debug_gn ui/aura:demo ui/aura:bench ui/aura:unittests
> R=brettw@chromium.org,ben@chromium.org
> 
> Review URL: https://codereview.chromium.org/420143002

TBR=tfarina@chromium.org

Review URL: https://codereview.chromium.org/426233005

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@286557 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 35e29a202df88be8cfe30a2b1a3d72e976ddf819