libgtk2ui: Add missing //ui/display dependency
It's currently missing, causing build flakes in the waterfall such as

gtk2_ui.cc: undefined reference to 'display::Display::HasForceDeviceScaleFactor()

in

https://build.chromium.org/p/chromium.linux/builders/Linux%20Builder%20%28dbg%29%2832%29/builds/52888

BUG=597761
TBR=estade@chromium.org
NOTREECHEKS=true

Review-Url: https://codereview.chromium.org/1966123002
Cr-Commit-Position: refs/heads/master@{#392854}

Former-commit-id: 9f509e847006d97546d92b28b229c66771c49d84