Revert of Merge grit svn r 202. (patchset #1 id:1 of https://codereview.chromium.org/1437183004/ )
Reason for revert:
Looks like this breaks chromevox_tests on CrOS: http://build.chromium.org/p/tryserver.chromium.linux/builders/linux_chromium_chromeos_ozone_rel_ng/builds/87793

Error: Test Error assertEquals('A Collapsed Selected 1 of 3',
      cvox.DomUtil.getControlValueAndStateString(node))
Actual: A Collapsed Selected 1$ of 3$
Expected: A Collapsed Selected 1 of 3
    at assertEquals (test_api.js:989:13)
    at Object.<anonymous> (dom_util_test.unitjs:1174:3)
    at Object.Test.runTest (test_api.js:341:16)
    at Object.TestCase.runTest (test_api.js:478:22)
    at Object.TestCase.run (test_api.js:508:14)
    at RUN_TEST_F (test_api.js:1325:21)
    at expectFunc (test_api.js:1120:20)
    at runTestFunction (test_api.js:1193:37)
    at runTest (test_api.js:1167:18)
    at <anonymous>:1:1
obj/chrome/browser/resources/chromeos/chromevox/chromevox_tests.gen/common/dom_util_test-gen.cc:2582: Failure

Original issue's description:
> Merge grit svn r 202.
>
> Merges https://code.google.com/p/grit-i18n/source/detail?r=202
> "Fix placeholder syntax for Chrome extensions."
> to the new grit location.
>
> This merges the last change in the grit svn repo before it will be shut down.
>
> BUG=553682
> R=newt@chromium.org
> TBR=newt
>
> Committed: https://crrev.com/abe370be65f99f37412909e425cbaf9b2faee427 [formerly 38d6d9efe4e9b4655905caef04c40086b3dc079b]
> Cr-Commit-Position: refs/heads/master@{#359447}

TBR=newt@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=553682

Review URL: https://codereview.chromium.org/1434413003

Cr-Commit-Position: refs/heads/master@{#359449}

Former-commit-id: 5aa461d1cbf2985040d19d40edd78223cfeba2b2