Set public_deps for //components/web_modal.
web_contents_modal_dialog_manager.h includes files from these targets, thus they should be public_deps.

Example error:
In file included from ../../components/constrained_window/test_create_native_web_modal_manager_cocoa.cc:5:
In file included from ../../components/web_modal/web_contents_modal_dialog_manager.h:14:
In file included from ../../content/public/browser/web_contents_observer.h:15:
In file included from ../../content/public/browser/navigation_controller.h:24:
In file included from ../../content/public/common/referrer.h:10:
In file included from ../../net/url_request/url_request.h:26:
In file included from ../../net/base/net_error_details.h:9:
In file included from ../../net/http/http_response_info.h:14:
In file included from ../../net/ssl/ssl_info.h:20:
In file included from ../../net/ssl/ssl_config.h:12:
In file included from ../../net/cert/x509_certificate.h:25:
../../third_party/boringssl/src/include/openssl/base.h:68:10: fatal error: 'openssl/opensslconf.h' file not found

BUG=none

Review-Url: https://codereview.chromium.org/2819483003
Cr-Commit-Position: refs/heads/master@{#464507}

Former-commit-id: 4a7b0272fad569856d18cbf2265fdfb2ec29b4e1