Revert r4614, "Remove stale src/trusted/sandbox and selenium tests"
This change broke the Linux toolchain build, where Selenium is still
run, because it is still configured in the Buildbot config.

The "install_plugin" step fails with:

rename /home/chrome-bot/.mozilla/plugins/sel_ldr.trace to /home/chrome-bot/.mozilla/plugins/sel_ldr_bin.trace ...
...
IOError: [Errno 2] No such file or directory: '/home/chrome-bot/.mozilla/plugins/sel_ldr.trace'

BUG=http://code.google.com/p/nativeclient/issues/detail?id=1568
TEST=none
Review URL: http://codereview.chromium.org/6765003

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@4648 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: 159573a03370156611879df278a9ea5fe21d8cb4