Revert "Timer notification UI improvement:"
This reverts commit dde95b02d0e03e4f93b2bc2f1084db73720e00ce [formerly d710a7b3ef59302c00c2e3fe1b00c788310801c6].

Reason for revert: Broke compile:
https://ci.chromium.org/buildbot/chromium.chrome/Google%20Chrome%20ChromeOS/59395
../../chromeos/services/assistant/assistant_manager_service_impl.cc:33:10: fatal error: 'libassistant/shared/internal_api/alarm_timer_types.h' file not found
#include "libassistant/shared/internal_api/alarm_timer_types.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original change's description:
> Timer notification UI improvement:
> 
> * Add timer deeplinks for:
>   - Stop timer
>   - Add time to timer
> * Add "add 1 min to timer" button to timer notification.
> 
> Using a feature flag to guard the usage of the deeplink as
> AlarmTimerManager is not fully available yet.
> 
> Bug: b:119116816
> Change-Id: Ib9b28abecece1bb4fc60b88f367900f6f08f2efe
> Reviewed-on: https://chromium-review.googlesource.com/c/1340786
> Commit-Queue: Li Lin <llin@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Reviewed-by: Xiyuan Xia <xiyuan@chromium.org>
> Reviewed-by: Xiaohui Chen <xiaohuic@chromium.org>
> Reviewed-by: Tao Wu <wutao@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#614618}

TBR=xiyuan@chromium.org,dcheng@chromium.org,xiaohuic@chromium.org,dmblack@google.com,wutao@chromium.org,llin@chromium.org

Change-Id: I8ece5ad7361e379880921e2abc55085d1de6cd88
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: b:119116816
Reviewed-on: https://chromium-review.googlesource.com/c/1367081
Reviewed-by: Alan Cutter <alancutter@chromium.org>
Commit-Queue: Alan Cutter <alancutter@chromium.org>
Cr-Commit-Position: refs/heads/master@{#614622}
Former-commit-id: 28d424ea311f180535b9a5aceb6facfc61c9b59e