Fix JS error in chrome://certificate-manager occuring when rendering a managed CA
When at least one managed CA is present, the JavaScript error happened in
chrome://certificate-manager page:
Uncaught TypeError: options.ControlledSettingIndicator is not a function

The error was caused by some required JS and CSS files not being
linked in the corresponding HTML file. The same "Certificate manager"
worked correctly from the Settings page because the required files were
included in the options.html file.

BUG=569018
TEST=manual testing

Review URL: https://codereview.chromium.org/1521643002

Cr-Commit-Position: refs/heads/master@{#364835}

Former-commit-id: 2775cb329b89b75aa02e77b7f4b00f8ffee614ab