Revert "Chrome OS OOBE: Update Sync Consent screen."
This reverts commit 3d7cfd932f19206a343d8d3bc574adc355ae83c2 [formerly b3216ae77de8528fb7f82adcf7b9fd28230684a6].

Reason for revert: Caused build error
https://logs.chromium.org/v/?s=chromium%2Fbb%2Fchromium.chrome%2FGoogle_Chrome_ChromeOS%2F50007%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout
FAILED: gen/chrome/resources_stamp.d.stamp gen/chrome/grit/browser_resources.h gen/chrome/browser_resources.pak gen/chrome/browser_resources.pak.info 
python ../../tools/grit/grit.py -i ../../chrome/browser/browser_resources.grd build -o gen/chrome --depdir . --depfile gen/chrome/resources_stamp.d --write-only-new=1 --depend-on-stamp -D _google_chrome -E CHROMIUM_BUILD=google_chrome -D chromeos -D scale_factors=2x -D toolkit_views -D use_aura -D use_nss_certs -D use_ozone -D enable_app_list=true -D enable_background_mode=false -D enable_background_contents=true -D enable_extensions=true -D enable_google_now=false -D enable_hangout_services_extension=true -D enable_plugins=true -D enable_print_preview=true -D enable_printing=true -D enable_service_discovery=true -D enable_vr=false -D enable_webrtc=true -D mac_views_browser=false -D safe_browsing_mode=1 -D optimize_webui=true -D enable_hangout_services_extension -E additional_modules_list_file=gen/chrome/browser/internal/additional_modules_list.txt -E root_gen_dir=gen -f ../../tools/gritsettings/resource_ids --assert-file-list=obj/chrome/browser/resources_expected_outputs.txt
Error processing node <?xml version="1.0" encoding="UTF-8"?>
<include file="internal\resources\chromeos-sync-consent-icons.html" name="IDR_PRODUCT_CHROMEOS_SYNC_CONSENT_SCREEN_ICONS" type="BINDATA" />
Traceback (most recent call last):
  File "../../tools/grit/grit.py", line 15, in <module>
    grit.grit_runner.Main(sys.argv[1:])
  File "/b/c/b/Google_Chrome_ChromeOS/src/tools/grit/grit/grit_runner.py", line 249, in Main
    toolobject.Run(options, args[1:])
  File "/b/c/b/Google_Chrome_ChromeOS/src/tools/grit/grit/tool/build.py", line 256, in Run
    self.Process()
  File "/b/c/b/Google_Chrome_ChromeOS/src/tools/grit/grit/tool/build.py", line 397, in Process
    self.ProcessNode(self.res, output, outfile)
  File "/b/c/b/Google_Chrome_ChromeOS/src/tools/grit/grit/tool/build.py", line 320, in ProcessNode
    formatted = formatter(node, output_node.GetLanguage(), output_dir=base_dir)
  File "/b/c/b/Google_Chrome_ChromeOS/src/tools/grit/grit/format/data_pack.py", line 83, in Format
    value = node.GetDataPackValue(lang, UTF8)
  File "/b/c/b/Google_Chrome_ChromeOS/src/tools/grit/grit/node/include.py", line 87, in GetDataPackValue
    data = util.ReadFile(filename, util.BINARY)
  File "/b/c/b/Google_Chrome_ChromeOS/src/tools/grit/grit/util.py", line 207, in ReadFile
    with open(filename, mode) as f:
IOError: [Errno 2] No such file or directory: u'../../chrome/browser/internal/resources/chromeos-sync-consent-icons.html'


Original change's description:
> Chrome OS OOBE: Update Sync Consent screen.
> 
> 
> This CL adds new UI only, no C++ bindings.
> 
> 
> Bug: 822889
> Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation
> Change-Id: I849880b096f7305903f17b2389aa2f9fc731698b
> Reviewed-on: https://chromium-review.googlesource.com/1053156
> Reviewed-by: Michael Giuffrida <michaelpg@chromium.org>
> Commit-Queue: Alexander Alekseev <alemate@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#558918}

TBR=alemate@chromium.org,michaelpg@chromium.org

Change-Id: Ica1d6e438b4e7a2891e3c4eaec87841c53da760c
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 822889
Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation
Reviewed-on: https://chromium-review.googlesource.com/1059635
Reviewed-by: Tsuyoshi Horo <horo@chromium.org>
Commit-Queue: Tsuyoshi Horo <horo@chromium.org>
Cr-Commit-Position: refs/heads/master@{#558923}
Former-commit-id: e5318e973d73eeff1027dbf80d0b8f21b94ae1d1