Revert "chromeos: Disable Tast test security.Mtab to unblock LKGM rolls."
This reverts commit a0900122db7467d0c3f0a03e0a3021730a0a1efc [formerly da307f248a032e89a90a3d2facc87f7d24442276].

Reason for revert: should no longer depend on chrome_login

Original change's description:
> chromeos: Disable Tast test security.Mtab to unblock LKGM rolls.
> 
> It's failing with:
> Error: [mtab.go:41] Root partition is mounted read/write; rootfs verification disabled?
> 
> Let's disable it while we figure out a workaround since it's blocking
> lkgm rolls.
> 
> Bug: 931431
> Change-Id: Ibf953f77009ead69902da163b750e53cf43c6ffe
> Reviewed-on: https://chromium-review.googlesource.com/c/1468599
> Reviewed-by: Dan Erat <derat@chromium.org>
> Commit-Queue: Ben Pastene <bpastene@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#631479}

TBR=derat@chromium.org,achuith@chromium.org,bpastene@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 931431
Change-Id: Ia496c1f04aaaabebc2737cca585a500a02c9928a
Reviewed-on: https://chromium-review.googlesource.com/c/1475814
Reviewed-by: Ben Pastene <bpastene@chromium.org>
Reviewed-by: Achuith Bhandarkar <achuith@chromium.org>
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Cr-Commit-Position: refs/heads/master@{#632688}
Former-commit-id: 8de02e891c3440ad05d19484287e19562446c033