fix gcc 4.7 compilation errors in base_unittests
Compiling base_unittests with gcc 4.7 on linux gives these errors:
../../base/logging_unittest.cc: In member function 'virtual void logging::{anonymous}::LoggingTest_BasicLogging_Test::TestBody()':
../../base/logging_unittest.cc:68:172: error: converting 'false' to pointer type for argument 1 of 'char testing::internal::IsNullLiteralHelper(testing::internal::Secret*)' [-Werror=conversion-null]
../../base/logging_unittest.cc: In member function 'virtual void logging::{anonymous}::LoggingTest_LogIsOn_Test::TestBody()':
../../base/logging_unittest.cc:123:174: error: converting 'false' to pointer type for argument 1 of 'char testing::internal::IsNullLiteralHelper(testing::internal::Secret*)' [-Werror=conversion-null]
../../base/logging_unittest.cc:132:174: error: converting 'false' to pointer type for argument 1 of 'char testing::internal::IsNullLiteralHelper(testing::internal::Secret*)' [-Werror=conversion-null]
../../base/logging_unittest.cc:141:174: error: converting 'false' to pointer type for argument 1 of 'char testing::internal::IsNullLiteralHelper(testing::internal::Secret*)' [-Werror=conversion-null]

Switching from EXPECT_EQ(false, something) to EXPECT_TRUE(false == something)
fixes the problem.

Review URL: https://chromiumcodereview.appspot.com/14019004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@193872 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: e5e4bfb4a6adb636c7a174099edc8e766086ca88