Wait for RequireBitstreamBuffers() after reset in VEAEncoder
This CL solves the issues resulting from mid-stream resize in VEAEncoder.
- RequireBitstreamBuffers() returns the updated |vea_requested_input_coded_size|,
so we should wait for it before copying any frame. Using the older value can result in
failed VideoFrame::WrapExternalSharedMemory() call.
- Check VideoFrame::WrapExternalSharedMemory() result before moving on in case
we end up with sizes that don't work.

BUG=714132
TEST= Tested the reported extension with resize.

Review-Url: https://codereview.chromium.org/2838453003
Cr-Commit-Position: refs/heads/master@{#467344}

Former-commit-id: d149aa5e140e8158e09a8b410660a8d72b4eec56