Revert of Implement cache counting for the simple and memory backends. (patchset #3 id:40001 of https://codereview.chromium.org/1398053002/ )
Reason for revert:
Causes test failures on XP bot:
https://build.chromium.org/p/chromium.win/builders/XP%20Tests%20%281%29/builds/40465/steps/net_unittests%20on%20Windows-XP-SP3/logs/DiskCacheBackendTest.SimpleCacheCalculateSizeOfAllEntries

DiskCacheBackendTest.SimpleCacheCalculateSizeOfAllEntries (run #1):
[ RUN      ] DiskCacheBackendTest.SimpleCacheCalculateSizeOfAllEntries
c:uild\slave\win_builderuild\src
et\disk_cacheackend_unittest.cc(1730): error: Value of: result
  Actual: 7447
Expected: (count - 1) * count / 2 + total_metadata_size
Which is: 7455
c:uild\slave\win_builderuild\src
et\disk_cacheackend_unittest.cc(1747): error: Value of: new_result
  Actual: 8243
Expected: result + last_entry_size + GetEntryMetadataSize(key)
Which is: 8235
c:uild\slave\win_builderuild\src
et\disk_cacheackend_unittest.cc(1751): error: Value of: new_result
  Actual: 7455
Expected: result
Which is: 7447
[  FAILED  ] DiskCacheBackendTest.SimpleCacheCalculateSizeOfAllEntries (171 ms)

Original issue's description:
> Implement cache counting for the simple and memory backends.
>
> This is a followup to https://codereview.chromium.org/1304363013/, which implemented it for the blockfile backend.
>
> BUG=510028
>
> Committed: https://crrev.com/ca23e880a4bc0de64be8d5aea704eb8f28049497 [formerly a319545886d0e297b88301f01b804432bea602f7]
> Cr-Commit-Position: refs/heads/master@{#354037}

TBR=gavinp@chromium.org,pasko@chromium.org,ttuttle@chromium.org,msramek@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=510028

Review URL: https://codereview.chromium.org/1401053004

Cr-Commit-Position: refs/heads/master@{#354118}

Former-commit-id: 81c61dd0811b103aeca08e1a5184db725fdb19fb