cros_gdb: Specify utf-8 output encoding.
This resolves the error:
TypeError: a bytes-like object is required, not 'str'

BUG=None
TEST=manual test

Change-Id: Idfa2ddde6279ca7332f3a1d836de5c35cb87d608
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/2073119
Commit-Queue: Allen Webb <allenwebb@google.com>
Tested-by: Allen Webb <allenwebb@google.com>
Reviewed-by: Mike Frysinger <vapier@chromium.org>