Revert of [tab_grid] Hack-in TabSwitcherPanelCell and Layout (patchset #4 id:50001 of https://codereview.chromium.org/2659233003/ )
Reason for revert:
Causes following test failure:

../../ios/showcase/tab_grid/sc_tab_grid_egtest.mm:25: error: -[SCTabGridTestCase testLaunchAndTappingCell] : Exception: NoMatchingElementException

Exception Name: NoMatchingElementException
Exception Reason: UI element cannot be found.Exception with Assertion: {
  "Assert Criteria" : "assertWithMatcher: notNil",
  "Element Matcher" : "((kindOfClass('UILabel') || kindOfClass('UITextField') || kindOfClass('UITextView')) && hasText('TabCommands'))",
  "Recovery Suggestion" : "Check if element exists in the UI, modify assert criteria, or adjust element matcher"
}

Original issue's description:
> Hack-in TabSwitcherPanelCell and TabSwitcherPanelControllerLayout.
>
> The clean skeleton tab_grid now uses reusable components from tab_switcher.
> These reusable components will eventually diverge from the current
> implementation, and will be moved to ios/clean when necessary.
> Currently, only tab_switcher_panel_cell needed to be slightly refactored to
> not use the Tab class. The placeholder tab_grid_tab_cell was replaced, but
> the files were not deleted because tab_switcher_panel_cell will eventually
> be refactored into the tab_grid_tab_cell.
>
> Screenshots:
> https://screenshot.googleplex.com/RhEioV4vfhh.png
> https://screenshot.googleplex.com/yX3yLkXshVs
>
> BUG=686770
>
> Review-Url: https://codereview.chromium.org/2659233003
> Cr-Commit-Position: refs/heads/master@{#447057}
> Committed: https://chromium.googlesource.com/chromium/src/+/27cf7c7e286bf4524becd91de0a9fc2b3c702716 [formerly 8576e703d22ac09c939415b9e7eb9cc0323b2ebe]

TBR=marq@chromium.org,sczs@chromium.org,jif@chromium.org,edchin@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=686770

Review-Url: https://codereview.chromium.org/2662093002
Cr-Commit-Position: refs/heads/master@{#447088}

Former-commit-id: b97fb55f74f15f89fbfbe1716d4923cfb0488af5