build_dlc.py: Build stage DLC_ID and DLC_PACKAGE validity detailed exceptions
The reason for failure should explicitly stated to the users.

Example new output:
  Exception: -example_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa is invalid:
  Must start with alphanumeric character.
  Must only use alphanumeric and - (dash).
  Must be within 40 characters.

BUG=chromium:993869
TEST=./build_dlc_unittest

Change-Id: Ie57a1856391498dd7b6f861930a016d947e860e4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/2013890
Tested-by: Jae Hoon Kim <kimjae@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Amin Hassani <ahassani@chromium.org>