BUILD FIX (r146667): ResourceRequest constructor in SynchronousLoaderClient.cpp is ambiguous on iOS
Fixes the following build failure:

    Source/WebCore/platform/network/SynchronousLoaderClient.cpp:52:15: error: conversion from 'int' to 'const WebCore::ResourceRequest' is ambiguous
        request = 0;
                  ^
    In file included from Source/WebCore/platform/network/SynchronousLoaderClient.cpp:30:
    In file included from Source/WebCore/platform/network/ResourceHandle.h:37:
    In file included from Source/WebCore/platform/network/ios/QuickLook.h:13:
    Source/WebCore/platform/network/cf/ResourceRequest.h:79:9: note: candidate constructor
            ResourceRequest(NSURLRequest *);
            ^
    Source/WebCore/platform/network/cf/ResourceRequest.h:83:9: note: candidate constructor
            ResourceRequest(CFURLRequestRef cfRequest)
            ^
    1 error generated.

* platform/network/SynchronousLoaderClient.cpp:
(WebCore::SynchronousLoaderClient::willSendRequest): If
USE(CFNETWORK) is defined, use static_cast<CFURLRequestRef>(0),
otherwise use static_cast<NSURLRequest *>(0).

git-svn-id: svn://svn.chromium.org/blink/trunk@146719 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: 992d790d77ffc1f6553d041489a8f88de9961c5a