Fix download_toolchains.py (breakage from r12814)
The script was failing with the error:

  UnboundLocalError: local variable 'os' referenced before assignment

because "os" was used as a variable shadowing "import os".

BUG=none
TEST="run build/download_toolchains.py --hash"
TBR=dyen@chromium.org

Review URL: https://codereview.chromium.org/184253006

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@12818 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: 60d1d61fb69dcb25cae59384589d60d227413588