Revert "Windows native color mixer.  Not yet instantiated."
This reverts commit 802025ca8e5cbf75cd1c2cb0a19d723f0735812e [formerly 4a3de950433ccb1c4cc173acc086c9fe6e3cb012].

Reason for revert: Breaks Mac archiver:
FAILED: obj/ui/color/libmixers.a 
rm -f obj/ui/color/libmixers.a && TOOL_VERSION=1571679568 python ../../build/toolchain/mac/filter_libtool.py ../../build/mac_files/xcode_binaries/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static  -o obj/ui/color/libmixers.a -filelist obj/ui/color/libmixers.a.rsp
fatal error: ../../build/mac_files/xcode_binaries/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file list file: obj/ui/color/libmixers.a.rsp is empty

Original change's description:
> Windows native color mixer.  Not yet instantiated.
> 
> Bug: 1003612
> Change-Id: I4df6d0fe38efaa706e981a7dedcc19355c21fc34
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1900656
> Commit-Queue: Robert Liao <robliao@chromium.org>
> Reviewed-by: Robert Liao <robliao@chromium.org>
> Auto-Submit: Peter Kasting <pkasting@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#713065}

TBR=pkasting@chromium.org,robliao@chromium.org

Change-Id: I53aeafd8ba06f47522bb82ba3acecedfca64b7ef
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1003612
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1899900
Reviewed-by: Joshua Pawlicki <waffles@chromium.org>
Commit-Queue: Joshua Pawlicki <waffles@chromium.org>
Cr-Commit-Position: refs/heads/master@{#713081}

Former-commit-id: e0103eb467c2df72303ff69bc676d56b162055bd