vs2015: avoid narrowing warning in ListMarkerPaint.cpp
FAILED: ninja -t msvc -e environment.x86 -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe" /nologo /showIncludes /FC @obj\third_party\WebKit\Source\core\paint\webcore_remaining.ListMarkerPainter.obj.rsp /c ..\..\third_party\WebKit\Source\core\paint\ListMarkerPainter.cpp /Foobj\third_party\WebKit\Source\core\paint\webcore_remaining.ListMarkerPainter.obj /Fdobj\third_party\WebKit\Source\core\webcore_remaining.cc.pdb
d:\src\cr2\src\third_party\webkit\source\core\paint\listmarkerpainter.cpp(205): error C2220: warning treated as error - no 'object' file generated
d:\src\cr2\src\third_party\webkit\source\core\paint\listmarkerpainter.cpp(205): warning C4838: conversion from 'int' to 'UChar' requires a narrowing conversion

R=skobes@chromium.org,dsinclair@chromium.org
BUG=440500

Review URL: https://codereview.chromium.org/1111853002

git-svn-id: svn://svn.chromium.org/blink/trunk@194615 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: fbd522a202554a8167162aa21315cc3abec7b153