Fix x86-64 Linux Gyp build (standalone and Chromium builds)
This should fix the build failure that occurs when building sel_validate_image.c:
./native_client/src/trusted/validator_x86/ncopcode_desc.h:18:72: error: gen/native_client/src/trusted/validator_x86/nacl_disallows.h: No such file or directory

The failure was introduced by r1969.

BUG=http://code.google.com/p/nativeclient/issues/detail?id=318

Review URL: http://codereview.chromium.org/1609011

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@1996 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: 3e8df18739e6839995ab1d1ed599aa0b89826251