cbuildbot: trim leading/trailing whitespace with -p
Looks like in some recent refactors, trailing space in the -p argument
was no longer ignored.  This caused invocations like:
	cbuildbot -p 'chromiumos/chromite:bb ' foo
to spit out confusing messages like:
	ERROR: Project  does not exist.

Include leading/trailing space stripping when flattening args.

BUG=None
TEST=`cbuildbot -p 'chromiumos/chromite:bb' tegra2` shows usage
TEST=`cbuildbot -p '  chromiumos/chromite:bb  ' tegra2` shows usage

Change-Id: I95d21f1cfa7094220db58634d598d87ddc08e795
Reviewed-on: https://gerrit.chromium.org/gerrit/19111
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Commit-Ready: Mike Frysinger <vapier@chromium.org>