Revert r123906 "Screensaver at login screen."
This reverts commit ae7bad96d269f37953fbc3504f4d6b48e2a5e28d [formerly e165130f2b6c70c9b0bf70d2e787ba9fb86e7655].

This broke chromeos gtk build.

chrome/browser/chromeos/ui/screensaver_extension_dialog.cc: In member function 'virtual void ScreensaverExtensionDialog::Show()':
chrome/browser/chromeos/ui/screensaver_extension_dialog.cc:112: error: 'ShowFullscreen' is not a member of 'ExtensionDialog'

TBR=rkc@chromium.org
BUG=none
TEST=none

Review URL: https://chromiumcodereview.appspot.com/9488001

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@123928 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: c906070d34a4f3c6caaade604b84303859da6c27