Partially fix compilation of media_unittests with Xcode 7 (OS X 10.11 SDK).
Xcode 7 only ships with OS X 10.11 SDK that added nullable/nonnullable
annotation to most of the methods of the SDK. Use an empty NSDictionary
instead of nil.

Fixes the following error:
../../ui/gfx/image/image_mac.mm:41:32: error: null passed to a callee that requires a non-null argument [-Werror,-Wnonnull]
  NSData* ns_data = [ns_bitmap representationUsingType:NSPNGFileType
                               ^
BUG=517914

Review URL: https://codereview.chromium.org/1338313002

Cr-Commit-Position: refs/heads/master@{#348621}

Former-commit-id: 2850850b11d6cd669986bc5230832bcccf97b92b