Fix broken --help on pnacl-opt, add some more --help and tests.
At some point we refactored some code and now it will do:

Traceback (most recent call last):
  ... stuff ...
  File ".../pnacl-opt.py", line 46, in get_help
    RunOpt(['--help'])
  NameError: global name 'RunOpt' is not defined

Also:

* add --help to pnacl-strip, pnacl-ld, and pnacl-dis.
* For pnacl-strip added "--info" to list what is supported.
* Fix pnacl-clang "--help-full".


Add some tests that the get_help() methods are at least
implemented and return non-zero-length strings.
One ugly bit is that the test harness now has a bit of junk
baked in about the location of the toolchain,
but that is because some of the --help are implemented by
just calling the host binary's --help.

BUG= http://code.google.com/p/nativeclient/issues/detail?id=2481
TEST= ./scons run_pnacl_driver_tests

Review URL: https://chromiumcodereview.appspot.com/11421018

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@10340 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: 554f3c317bebdaaabac3545efc03b26ebd8b1230