cbuildbot: fix missing , in duplicate log
If you try to run cbuildbot with duplicate patches, the error message
throws an exception:
	TypeError: not enough arguments for format string
	Logged from file cros_build_lib.py, line 501

This is because the duplication logic misses a comma.

BUG=None
TEST=`cbuildbot -g 44702 link-firmware` w/local patches no longer hits this exception

Change-Id: I5b328b6cc44d255a92775e2f797016518c2b1897
Reviewed-on: https://gerrit.chromium.org/gerrit/44709
Reviewed-by: Ryan Cui <rcui@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>