Graph API: Include <vector> for std::vector
IWYU, which also fixes the build with libstdc++ after commit 4a71726 ("[PM]
Migrate IsolationContextMetrics to use public observer API"):

    In file included from ../../chrome/browser/performance_manager/graph/graph.cc:5:
    ../../chrome/browser/performance_manager/public/graph/graph.h:69:16: error: no template named 'vector' in namespace 'std'
      virtual std::vector<const FrameNode*> GetAllFrameNodes() const = 0;
              ~~~~~^
    ../../chrome/browser/performance_manager/public/graph/graph.h:70:16: error: no template named 'vector' in namespace 'std'
      virtual std::vector<const PageNode*> GetAllPageNodes() const = 0;
              ~~~~~^
    ../../chrome/browser/performance_manager/public/graph/graph.h:71:16: error: no template named 'vector' in namespace 'std'
      virtual std::vector<const ProcessNode*> GetAllProcessNodes() const = 0;
              ~~~~~^

Bug: 957519
Change-Id: I43512b31bb87bed43390f994928ac889bd4a6d88
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1688842
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Commit-Queue: Chris Hamilton <chrisha@chromium.org>
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Reviewed-by: Chris Hamilton <chrisha@chromium.org>
Cr-Commit-Position: refs/heads/master@{#674877}

Former-commit-id: acf525a206137705ea7110ad3fb99967f57a5577