Remove incorrect definition of EDQUOT errno value on Windows
This fixes compilation on Visual Studio 10.0, where we got the error:

src\shared\platform\nacl_host_desc_common.c(71) : error C2196: case
value '122' already used

MSVC 10.0 introduces a definition of ENOMSG as 122.  ENOMSG was not
defined in MSVC 9.0.  However, that conflicted with our definition of
EDQUOT, which we defined as 122.

BUG=http://code.google.com/p/nativeclient/issues/detail?id=1287
TEST=build with Windows SDK + trybots

Review URL: http://codereview.chromium.org/5967009

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@4078 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: e5b17ea9e01dfdaeb7e5010d6b67034639bbb2b7