[Telemetry] Raise exception when trace buffer is overrun.
If this change causes your Telemetry benchmark to start failing with a
TraceBufferDataLossException, then do not revert this change. The reason
is that this change is catching issues that previously might have been missed.
Note that this change uses a new M77 capability, so it will not catch issues
against stable or reference builds of Chrome right away.

To test this change, I manually edited benchmarks/v8_browsing.py in the following
way:
-  options.config.chrome_trace_config.SetTraceBufferSizeInKb(400 * 1024)
+  options.config.chrome_trace_config.SetTraceBufferSizeInKb(4)
That would force a tiny trace buffer.

I ran that without my change, and I got a the error

> TraceImportError: No clock sync markers exist pairing clock domain
> "UNKNOWN_CHROME_LEGACY" with target clock domain "TELEMETRY".

as I expected. Then I ran with my change using the command
xvfb-run ./run_benchmark v8.browsing_desktop --story-shard-begin-index=0 \
--story-shard-end-index=1 --browser=exact \
--browser-executable=<path to chrome at revision 673071>

and I hit the TraceBufferDataLossException.

I then ran without the tiny trace buffer, and that first story of
v8.browsing_desktop ran without error.


Bug: chromium:948412
Change-Id: I0176f5a92e930ea1f4e21a1998509263f51a6d79
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/1681345
Commit-Queue: Caleb Rouleau <crouleau@chromium.org>
Auto-Submit: Caleb Rouleau <crouleau@chromium.org>
Reviewed-by: Juan Antonio Navarro Pérez <perezju@chromium.org>

Former-commit-id: 85e0cba51e88d0c59849cb5bb43312f6a359763c