Revert 87396 - Added a facility in PPAPI to register interface factories which can watch GetInterface calls and return custom interfaces. Added a basic unit test to validate that the custom factory does get called.
This would eventually be used to register custom interfaces for plugins like NACL which rely on chrome\renderer
provided functionality via the webkit_glue namespace. This will help in eventually building src\content
as a dll.

BUG=82454
TEST=covered by test shell tests.
Review URL: http://codereview.chromium.org/6976035


make -k -j4 -r BUILDTYPE=Debug
  ACTION Extracting last change to /mnt/data/b/build/slave/Linux_Clang__ChromiumOS_dbg_/build/src/out/Debug/obj/gen/build/LASTCHANGE out/Debug/obj/gen/build/LASTCHANGE.always
  CXX(target) out/Debug/obj.target/glue/webkit/plugins/ppapi/plugin_module.o
  CXX(target) out/Debug/obj.target/glue/webkit/plugins/ppapi/ppapi_interface_factory.o
In file included from webkit/plugins/ppapi/ppapi_interface_factory.cc:5:
./webkit/plugins/ppapi/ppapi_interface_factory.h:40:3: error: [chromium-style] Complex constructor has an inlined body.
  PpapiInterfaceFactoryManager() {}
  ^
./webkit/plugins/ppapi/ppapi_interface_factory.h:41:3: error: [chromium-style] Complex destructor has an inline body.
  ~PpapiInterfaceFactoryManager() {}
  ^
2 errors generated.
In file included from webkit/plugins/ppapi/plugin_module.cc:75:
./webkit/plugins/ppapi/ppapi_interface_factory.h:40:3: error: [chromium-style] Complex constructor has an inlined body.
  PpapiInterfaceFactoryManager() {}
  ^
./webkit/plugins/ppapi/ppapi_interface_factory.h:41:3: error: [chromium-style] Complex destructor has an inline body.
  ~PpapiInterfaceFactoryManager() {}
  ^
make: *** [out/Debug/obj.target/glue/webkit/plugins/ppapi/ppapi_interface_factory.o] Error 1
2 errors generated.
make: *** [out/Debug/obj.target/glue/webkit/plugins/ppapi/plugin_module.o] Error 1
make: Target `all' not remade because of errors.


http://build.chromium.org/p/chromium/builders/Linux%20Clang%20%28ChromiumOS%20dbg%29/builds/5023


TBR=ananta@chromium.org
Review URL: http://codereview.chromium.org/7020014

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@87398 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: fdbb38da528f6a931d9785cffb15ea9489bd0b35