Revert of command_buffer_gles2: Implement EGL default Display as a global object (patchset #20 id:380001 of https://codereview.chromium.org/1714883002/ )
Reason for revert:
Unfortunately I have to revert this, it is causing compile failures in the chroot.

Example builder:
https://uberchromegw.corp.google.com/i/chromeos.chrome/builders/x86-alex-tot-chrome-pfq-informational/builds/19729

Failure:
chromeos-chrome-52.0.2714.0_alpha-r1: ../../../../../../../home/chrome-bot/chrome_root/src/gpu/khronos_glcts_support/native/egl_native_windowless.cc: In member function 'virtual tcu::NativeWindow* egl::native::windowless::Platform::createWindow(tcu::NativeDisplay&, EGLConfig, const EGLint*, int, int, qpVisibility)':
chromeos-chrome-52.0.2714.0_alpha-r1: ../../../../../../../home/chrome-bot/chrome_root/src/gpu/khronos_glcts_support/native/egl_native_windowless.cc:79:69: error: 'CommandBufferGLESSetNextCreateWindowSurfaceCreatesPBuffer' was not declared in this scope
chromeos-chrome-52.0.2714.0_alpha-r1:                                                                height);

Original issue's description:
> command_buffer_gles2: Implement EGL default Display as a global object
>
> Make EGL Display a global. eglGetDisplay(EGL_DEFAULT_DISPLAY) will
> return the same object.
>
> Store EGL state in a new thread-local object (ThreadState). One
> display, multiple surfaces, multiple contexts.
>
> Fix the currently implemented entry points to return specified errors
> and behave as specified. Notable changes:
> * eglGetDisplay() does not create new displays for each invocation
> * eglTerminate() invalidates the created egl objects but leaves the
>   current context intact as specified
> * eglMakeCurrent() is implemented more correctly with refcount semantics
> * eglQueryStrings() works without display for some names
> * eglReleaseThread() is implemeted
> * Config are now separate for pbuffers and windows, so that contexts
>   can be created separate from surfaces
> * Context can be made current with different surfaces
> * Catches errors related to context being set current to multiple
>   threads
> * Tries to be thread-safe
>
> In the implementation, the Display contains a lock ensuring all thread
> accesses are consistent. All functions using or changing thread-local
> state have explicit egl::ThreadState parameter.
>
> BUG=581634
> CQ_INCLUDE_TRYBOTS=tryserver.chromium.win:win_optional_gpu_tests_rel
>
> Committed: https://crrev.com/35c41501620e7999a5fd78eb99c487f0d23bfa1f [formerly de9aa3be41bca094454babbd62907815fad7f5c2]
> Cr-Commit-Position: refs/heads/master@{#377535}
>
> Committed: https://crrev.com/2151a975947d621a6677ca77a47c3eff0e3e0cfe [formerly 7b01a0867be0895009b120f37fcd4166a84f404b]
> Cr-Commit-Position: refs/heads/master@{#386613}
>
> Committed: https://crrev.com/419038d648ca6e047fc8e1d43185c6d6a8031d99 [formerly f9d5c7e6fd53570c0decc63e8ec51d30e0701c89]
> Cr-Commit-Position: refs/heads/master@{#387871}

TBR=piman@chromium.org,thakis@chromium.org,vabr@chromium.org,kkinnunen@nvidia.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=581634

Review URL: https://codereview.chromium.org/1909573002

Cr-Commit-Position: refs/heads/master@{#388523}

Former-commit-id: d4d63ccaf80bcb4b2cc61bef2513e37552bb3304