Revert "[Sheriff] Disabling PanelTest.* on ChromiumOS"
This reverts commit a9d41eb6fb95dc1208721f4c086cbb5f3dde5012 [formerly 12af72412d3a767b6d2ce5ab607ca05f30afb011].

Reason for revert: Please realnd without NOTRY as it caused compile failure.
Compile log: test_data/chrome/browser/resources/chromeos/chromevox/cvox2/background/panel_test.extjs gen/chrome/browser/resources/chromeos/chromevox/cvox2/background/panel_test-gen.cc 
python ../../tools/gypv8sh.py ./v8_shell ../../chrome/third_party/mock4js/mock4js.js ../../chrome/test/data/webui/test_api.js ../../chrome/test/base/js2gtest.js extension --external=y ../../chrome/browser/resources/chromeos/chromevox/cvox2/background/panel_test.extjs chrome/browser/resources/chromeos/chromevox/cvox2/background/panel_test.extjs gen/chrome/browser/resources/chromeos/chromevox/cvox2/background/panel_test-gen.cc test_data/chrome/browser/resources/chromeos/chromevox/cvox2/background/panel_test.extjs
undefined:68: SyntaxError: Invalid or unexpected token
#if defined(OS_CHROMEOS)
^
SyntaxError: Invalid or unexpected token
    at ../../chrome/test/base/js2gtest.js:462:6


Original change's description:
> [Sheriff] Disabling PanelTest.* on ChromiumOS
> 
> The tests are flaky on ChromiumOS.
> 
> TBR=dtseng@chromium.org, yutak@chromium.org
> NOTRY=true
> 
> Bug: 751046
> Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation
> Change-Id: Id28f1ba7cb1c42c617b041c74a3698937d21eed5
> Reviewed-on: https://chromium-review.googlesource.com/595589
> Commit-Queue: Jan Krcal <jkrcal@chromium.org>
> Reviewed-by: Jan Krcal <jkrcal@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#490929}

TBR=dtseng@chromium.org,yutak@chromium.org,jkrcal@chromium.org

Change-Id: I0e62ca5b253292bd0ae4ef5e4f12e065589494db
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 751046
Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation
Reviewed-on: https://chromium-review.googlesource.com/595687
Reviewed-by: Friedrich Horschig <fhorschig@chromium.org>
Commit-Queue: Friedrich Horschig <fhorschig@chromium.org>
Cr-Commit-Position: refs/heads/master@{#490934}
Former-commit-id: 3770f366b4a020347844f8f6c7366a7c4ab3a985