Revert of [Chromoting] Enable AppRemoting sample apps by default in all.gyp. (patchset #4 id:60001 of https://codereview.chromium.org/878793003/)
Reason for revert:
Broke the official builders:
Traceback (most recent call last):
  File "../remoting/webapp/build-webapp.py", line 413, in <module>
    sys.exit(main())
  File "../remoting/webapp/build-webapp.py", line 409, in main
    service_environment)
  File "../remoting/webapp/build-webapp.py", line 198, in buildWebApp
    + buildtype + ': ' + service_environment)
Exception: Invalid service_environment targeted for Official: dev
ninja: build stopped: subcommand failed.

http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Linux%20x64/builds/55334/steps/compile/logs/stdio#error1

Original issue's description:
> [Chromoting] Enable AppRemoting sample apps by default in all.gyp.
>
> Where "by default" = whenever we build Chromoting.
>
> BUG=
>
> Committed: https://crrev.com/3467f433a9b71b3bd02217e77ef6ecfe9c9d069e [formerly e0bf65f1e2fcd3515b92c1b49f04aa30fd0d47e6]
> Cr-Commit-Position: refs/heads/master@{#313324}

TBR=scottmg@chromium.org,garykac@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review URL: https://codereview.chromium.org/880083002

Cr-Commit-Position: refs/heads/master@{#313346}

Former-commit-id: aef028b08a623095942ff35a36cada39fc4e49e1