undefined reference to JSC::IdentifierTable::~IdentifierTable() on EFL port https://bugs.webkit.org/show_bug.cgi?id=80282
Reviewed by Antonio Gomes.

.:

Remove transitive library dependencies; they are especially
dangerous when one ends up linking against WTF, JSC and then WTF
again, since some symbols will not be defined.

Passing --no-copy-dt-needed-entries and --as-needed to the linker
(which some recent Linux distros do by default) makes the issue
even more evident.

* CMakeLists.txt: Set CMAKE_LINK_INTERFACE_LIBRARIES to an empty
list to prevent implicit transitive library dependencies from
being created by default.

Source/WebCore:

No new tests, this is a buildsystem change.

Remove transitive library dependencies; they are especially
dangerous when one ends up linking against WTF, JSC and then WTF
again, since some symbols will not be defined.

Passing --no-copy-dt-needed-entries and --as-needed to the linker
(which some recent Linux distros do by default) makes the issue
even more evident.

* CMakeLists.txt: Explicitly link to WTF as WebCore uses symbols
from it.
* PlatformEfl.cmake: Explicitly link against libjpeg and libpng.

Tools:

Remove transitive library dependencies; they are especially
dangerous when one ends up linking against WTF, JSC and then WTF
again, since some symbols will not be defined.

Passing --no-copy-dt-needed-entries and --as-needed to the linker
(which some recent Linux distros do by default) makes the issue
even more evident.

* DumpRenderTree/efl/CMakeLists.txt: Do not link directly to WTF,
as the other libraries have the needed symbols. Explicitly link
against fontconfig.

git-svn-id: svn://svn.chromium.org/blink/trunk@109983 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: 385208127d5b8bf84275330f36ce515bd8653a87