Set up self.saved_params earlier.
Fixes the below stack trace so that users get a better error message.
This doesn't fix the underlying problem (maybe the user has a funny
netrc file that Python can't parse?) but it does expose the error message so
users can debug it.

======================================================================
ERROR: [chromite.lib.gerrit_unittest] GerritHelperTest.test001SimpleQuery
Create one independent and three dependent changes, then query them.
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../lib/cros_test_lib.py", line 81, in NetworkWrapper
    test_item(*args, **kwargs)
  File ".../lib/cros_test_lib.py", line 267, in _stacked_setUp
    StackedSetup._stacked_tearDown(obj)
  File ".../lib/cros_test_lib.py", line 283, in _stacked_tearDown
    target(obj)
  File ".../lib/cros_test_lib.py", line 1279, in tearDown
    site_config._site_params.update(self.saved_params)
AttributeError: 'GerritHelperTest' object has no attribute 'saved_params'

BUG=chromium:596511
TEST=Run gerrit_unittest --network. It works with and without this patch.

Change-Id: Ic318a05a313ee8abb49f12dc59adfef70952a49d
Reviewed-on: https://chromium-review.googlesource.com/335681
Commit-Ready: David James <davidjames@chromium.org>
Tested-by: David James <davidjames@chromium.org>
Reviewed-by: Matthew Sartori <msartori@chromium.org>