WPT importer: Make test_tbr_reviewer_date_not_found() independent of time zones
The test is currently passing when run under a time zone such as
"America/Los_Angeles", but not under CET or JST:

    Traceback (most recent call last):
      File "/data/src/chromium/src/third_party/blink/tools/blinkpy/w3c/test_importer_unittest.py", line 351, in test_tbr_reviewer_date_not_found
        'ERROR: No entry found for date 1969-12-31 in rotations table.\n'
      File "/data/src/chromium/src/third_party/WebKit/Tools/Scripts/webkitpy/common/system/log_testing.py", line 237, in assertLog
        self._log.assertMessages(messages)
      File "/data/src/chromium/src/third_party/WebKit/Tools/Scripts/webkitpy/common/system/log_testing.py", line 192, in assertMessages
        self._test_stream.assertMessages(messages)
      File "/data/src/chromium/src/third_party/WebKit/Tools/Scripts/webkitpy/common/system/log_testing.py", line 72, in assertMessages
        self._test_case.assertEqual(messages, self.messages)
    AssertionError: Lists differ: ['ERROR: No entry found for da... != ['ERROR: No entry found for da...

    First differing element 0:
    'ERROR: No entry found for date 1969-12-31 in rotations table.\n'
    'ERROR: No entry found for date 1970-01-01 in rotations table.\n'

    - ['ERROR: No entry found for date 1969-12-31 in rotations table.\n']
    ?                                    ^^  - ^

    + ['ERROR: No entry found for date 1970-01-01 in rotations table.\n']
    ?                                    ^^ +  ^

Fix it by not hardcoding the expected date, but rather deriving it from
MockHost's time().

While here, also fix a potential bug in test_tbr_reviewer() by not assuming
'2017-01-01' is not the same as today -- we now use variables and timedeltas
to represent the dates in the calendar.

Bug: 834725
Change-Id: Icd6621350fe9fa2ad1c2c996205d64bc23b01e26
Reviewed-on: https://chromium-review.googlesource.com/1019403
Reviewed-by: Quinten Yearsley <qyearsley@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#552343}
Former-commit-id: d57730e226b7e5f1b598c626c84d89f053863d3c