Revert "[Mac] Created Suggested Text Touch Bar"
This reverts commit 21c45dd3c8db57d1e8b3235b92ec96e7e94592a3 [formerly 177ab6469163b4ae7d28abdccd4f44e6e61d4769].

Reason for revert:
[experimental revert]
chromedriver_py_tests has been failing on two Mac bots since this change landed.  It's the only plausible candidate on the blamelist.

First failure on each of the two bots that failed.
https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/Mac10.11%20Tests/27182
https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/Mac10.10%20Tests/32954

Four tests in this suite fail:
======================================================================
ERROR: testSendKeysToElement (__main__.ChromeDriverTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../../chrome/test/chromedriver/test/run_py_tests.py", line 677, in testSendKeysToElement
    text.SendKeys(', there!')
  File "/b/s/w/ir/chrome/test/chromedriver/test/../client/webelement.py", line 59, in SendKeys
    self._Execute(Command.SEND_KEYS_TO_ELEMENT, {'value': typing})
  File "/b/s/w/ir/chrome/test/chromedriver/test/../client/webelement.py", line 18, in _Execute
    return self._chromedriver.ExecuteCommand(command, params)
  File "/b/s/w/ir/chrome/test/chromedriver/test/../client/chromedriver.py", line 298, in ExecuteCommand
    response = self._ExecuteCommand(command, params)
  File "/b/s/w/ir/chrome/test/chromedriver/test/../client/chromedriver.py", line 291, in _ExecuteCommand
    raise _ExceptionForLegacyResponse(response)
ChromeDriverException: chrome not reachable
  (Session info: chrome=69.0.3454.0)
  (Driver info: chromedriver=2.40.565811 (cf23f3fc22cbd3cfef2dbdad1c5f1c45a041b272 [formerly 22b36989b1ba408a526d457fac93653895890b54]),platform=Mac OS X 10.10.5 x86_64)
======================================================================
ERROR: testSendingTabKeyMovesToNextInputElement (__main__.ChromeDriverTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../../chrome/test/chromedriver/test/run_py_tests.py", line 686, in testSendingTabKeyMovesToNextInputElement
    self._driver.SendKeys('snoopy')
  File "/b/s/w/ir/chrome/test/chromedriver/test/../client/chromedriver.py", line 574, in SendKeys
    self.ExecuteCommand(Command.SEND_KEYS_TO_ACTIVE_ELEMENT, {'value': typing})
  File "/b/s/w/ir/chrome/test/chromedriver/test/../client/chromedriver.py", line 298, in ExecuteCommand
    response = self._ExecuteCommand(command, params)
  File "/b/s/w/ir/chrome/test/chromedriver/test/../client/chromedriver.py", line 291, in _ExecuteCommand
    raise _ExceptionForLegacyResponse(response)
ChromeDriverException: chrome not reachable
  (Session info: chrome=69.0.3454.0)
  (Driver info: chromedriver=2.40.565811 (cf23f3fc22cbd3cfef2dbdad1c5f1c45a041b272 [formerly 22b36989b1ba408a526d457fac93653895890b54]),platform=Mac OS X 10.10.5 x86_64)
======================================================================
ERROR: testShadowDomSendKeys (__main__.ChromeDriverTest)
Checks that chromedriver can call SendKeys on a shadow DOM element.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../../chrome/test/chromedriver/test/run_py_tests.py", line 1253, in testShadowDomSendKeys
    'return document.querySelector("* /deep/ #olderTextBox").value;'))
  File "/b/s/w/ir/chrome/test/chromedriver/test/../client/chromedriver.py", line 322, in ExecuteScript
    Command.EXECUTE_SCRIPT, {'script': script, 'args': converted_args})
  File "/b/s/w/ir/chrome/test/chromedriver/test/../client/chromedriver.py", line 298, in ExecuteCommand
    response = self._ExecuteCommand(command, params)
  File "/b/s/w/ir/chrome/test/chromedriver/test/../client/chromedriver.py", line 291, in _ExecuteCommand
    raise _ExceptionForLegacyResponse(response)
ChromeDriverException: chrome not reachable
  (Session info: chrome=69.0.3454.0)
  (Driver info: chromedriver=2.40.565811 (cf23f3fc22cbd3cfef2dbdad1c5f1c45a041b272 [formerly 22b36989b1ba408a526d457fac93653895890b54]),platform=Mac OS X 10.10.5 x86_64)
======================================================================
ERROR: testSendKeysToElement (__main__.MobileEmulationCapabilityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../../chrome/test/chromedriver/test/run_py_tests.py", line 2256, in testSendKeysToElement
    text.SendKeys(', there!')
  File "/b/s/w/ir/chrome/test/chromedriver/test/../client/webelement.py", line 59, in SendKeys
    self._Execute(Command.SEND_KEYS_TO_ELEMENT, {'value': typing})
  File "/b/s/w/ir/chrome/test/chromedriver/test/../client/webelement.py", line 18, in _Execute
    return self._chromedriver.ExecuteCommand(command, params)
  File "/b/s/w/ir/chrome/test/chromedriver/test/../client/chromedriver.py", line 298, in ExecuteCommand
    response = self._ExecuteCommand(command, params)
  File "/b/s/w/ir/chrome/test/chromedriver/test/../client/chromedriver.py", line 291, in _ExecuteCommand
    raise _ExceptionForLegacyResponse(response)
ChromeDriverException: chrome not reachable
  (Session info: chrome=69.0.3454.0)
  (Driver info: chromedriver=2.40.565811 (cf23f3fc22cbd3cfef2dbdad1c5f1c45a041b272 [formerly 22b36989b1ba408a526d457fac93653895890b54]),platform=Mac OS X 10.10.5 x86_64)
----------------------------------------------------------------------
Ran 129 tests in 225.387s
FAILED (errors=4)


Original change's description:
> [Mac] Created Suggested Text Touch Bar
> 
> When text is selected in a textfield, the touch bar displays options
> to replace the selected text. Clicking on one of the options will
> replace the selected text with the selected option.
> 
> Currently, there are no functional unit tests for the suggested text
> touch bar. As functionality is fleshed out, unit tests will be
> created.
> 
> A new folder (chrome/browser/ui/cocoa/touchbar) was created to house all
> files related to the Mac touch bar. The
> CreditCardAutofillTouchBarController files and the
> WebTextfieldTouchBarController files were moved to this new folder.
> Dependencies and header guards were updated to reflect this change.
> 
> New files:
>   - suggested_text_touch_bar_controller.h
>   - suggested_text_touch_bar_controller.mm
>   - suggested_text_touch_bar_controller_browsertest.mm
> Moved files:
>   - credit_card_autofill_touch_bar_controller.h
>   - credit_card_autofill_touch_bar_controller.mm
>   - credit_card_autofill_touch_bar_controller_unittest.mm
>   - web_textfield_touch_bar_controller.h
>   - web_textfield_touch_bar_controller.mm
> 
> BUILD files were updated to accomodate the change in location for the
> moved files and to include the new files.
> 
> WebContentsImpl, WebContentsDelegate, and WebContentsObserver were
> modified so that the SuggestedTextTouchBarController can observe
> TextInputManager for a change in text selection.
> 
> A feature flag SuggestedTextTouchBar was created and added to
> chrome://about so that the new touch bar is disabled by default and
> can be enabled via command line or chrome://flags with the flag
> #enable-suggested-text-touch-bar.
> 
> This CL includes the following browser tests for
> SuggestedTextTouchBarController:
>   - SetTextTest
>   - TouchBarTest
>   - TextSelectionChangedTest
> 
> Bug: 717553
> Change-Id: Icdd796c5d7ff6f67598b58c6c6c8c17a6a85d004
> Reviewed-on: https://chromium-review.googlesource.com/1069495
> Commit-Queue: Tessa Nijssen <tnijssen@google.com>
> Reviewed-by: Avi Drissman <avi@chromium.org>
> Reviewed-by: Sarah Chan <spqchan@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#565799}

TBR=avi@chromium.org,spqchan@chromium.org,tnijssen@google.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 717553
Change-Id: I0e3c6cfd00dba3065bd74efea043f1137599460c
Reviewed-on: https://chromium-review.googlesource.com/1095674
Reviewed-by: Mark Pearson <mpearson@chromium.org>
Commit-Queue: Mark Pearson <mpearson@chromium.org>
Cr-Commit-Position: refs/heads/master@{#566163}
Former-commit-id: c28bf5aa8b20f86eae37481943fa327aeed6d5b1