Revert of Move remote_db_manager into the safe_browsing_db component. (patchset #17 id:300001 of https://codereview.chromium.org/1579403002/ )
Reason for revert:
"buildbot failure in Chromium on Win"

components\safe_browsing_db\safe_browsing_api_handler_util.cc(138) : error C2220: warning treated as error - no 'object' file generated
components\safe_browsing_db\safe_browsing_api_handler_util.cc(138) : warning C4701: potentially uninitialized local variable 'matches' used
components\safe_browsing_db\safe_browsing_api_handler_util.cc(138) : warning C4703: potentially uninitialized local pointer variable 'matches' used

Original issue's description:
> Move remote_db_manager into the safe_browsing_db component.
>
> BUG=543161
>
> Committed: https://crrev.com/f4e7d5135c1dd5cd204ef69789f5389c21e12b80 [formerly bdd302affda19c5b2051d1e868c7045f5614c955]
> Cr-Commit-Position: refs/heads/master@{#371034}

TBR=jochen@chromium.org,blundell@chromium.org,nparker@chromium.org,vakh@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=543161

Review URL: https://codereview.chromium.org/1620813005

Cr-Commit-Position: refs/heads/master@{#371050}

Former-commit-id: 2b17e4a37d9c71a1cafdb77688fe344a5034341c