[Telemetry] Add two missing methods to ios browser finder.
Fixes:
  AttributeError: 'module' object has no attribute 'SelectDefaultBrowser'

BUG=

Review URL: https://codereview.chromium.org/355513002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@279251 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: e081341883a2140276703bb36e392fa2d1575809