mac: Support the 10.13 SDK in Bluetooth adapter metrics
The 10.11 and 10.12 SDKs had CBErrorMaxConnection = 10 in their CBError
enum. This value was never documented, and it’s possible that it was
only intended to serve as a “last” marker. In the 10.13 SDK, this value
has been removed, and three new ones were added: CBErrorConnectonFailed
= 10, CBErrorConnectionLimitReached = 11, and CBErrorUnkownDevice = 12.
(Yes, there’s a typo in the last one.)

Building with the 10.13 SDK produces this error:

../../device/bluetooth/bluetooth_adapter_mac_metrics.mm:50:15: error: use of undeclared identifier 'CBErrorMaxConnection'; did you mean 'CBErrorNotConnected'?
          if (CBErrorMaxConnection == cb_error_code)
              ^~~~~~~~~~~~~~~~~~~~
              CBErrorNotConnected
…/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/CoreBluetooth.framework/Headers/CBError.h:31:2:       'CBErrorNotConnected' declared here
        CBErrorNotConnected NS_ENUM_AVAILABLE(10_9, 6_0)                        = 3,
        ^

This removes CBErrorMaxConnection and adds the three new enum values.
According to UMA, CBErrorMaxConnection has never been hit anyway.

Bug: 729895
Change-Id: I543ec05679f6cc5ba70d6fbb4ace5e8fb29989b0
Reviewed-on: https://chromium-review.googlesource.com/665497
Reviewed-by: Vincent Scheib <scheib@chromium.org>
Commit-Queue: Mark Mentovai <mark@chromium.org>
Cr-Commit-Position: refs/heads/master@{#501760}
Former-commit-id: 96b54f923106328e550a513ed1e836de8b93b97a