Revert "wrapper: handle any subdir"
Appears to be taking out cbuildbot everywhere with:
cbuildbot: Unhandled exception:
Traceback (most recent call last):
  File "chromite/buildbot/cbuildbot", line 86, in <module>
    ret = target()
TypeError: main() takes no arguments (1 given)

This reverts commit ddf48d3c850135005a72b0d24463afeab349d3ee

Change-Id: I533c9a237ecc4eb54af703e6bef7e1f1d717d287
Reviewed-on: https://gerrit.chromium.org/gerrit/23359
Reviewed-by: Chris Wolfe <cwolfe@chromium.org>
Tested-by: Chris Wolfe <cwolfe@chromium.org>