Revert of DevTools: do not use platform/ to load injected scripts into inspector/v8. (patchset #3 id:100001 of https://codereview.chromium.org/1670813003/ )
Reason for revert:
broke https://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20ChromeOS/builds/14241/steps/generate_build_files/logs/stdio :

GYP_DEFINES='branding=Chrome buildtype=Official use_goma=1 gomadir=/b/build/goma chromeos=1'
python build/gyp_chromium -G output_dir=out
  -> returned 1
Updating projects from gyp files...
Traceback (most recent call last):
  File "tools/jsbundler.py", line 48, in <module>
    import rjsmin
ImportError: No module named rjsmin
gyp: Call to 'python tools/jsbundler.py -r . -r . -r ../../../../../chrome/third_party/chromevox/third_party/closure-library/closure/goog -x testing -x _test.js chromevox/injected/loader.js' returned exit status 1 while in /b/build/slave/google-chrome-rel-chromeos/build/src/chrome/browser/resources/chromeos/chromevox/chromevox.gyp.
step returned non-zero exit code: 1

(also on https://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Full https://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Builder https://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Builder%20(dbg) )

Original issue's description:
> DevTools: do not use platform/ to load injected scripts into inspector/v8.
>
> BUG=580337
> TBR=jochen for stray gyp files.
>
> Committed: https://crrev.com/aeada6aac0b265731e6cdf5928782828f9bd1193 [formerly adce7da2534641a5385eabd8f25e9379e4f3ab27]
> Cr-Commit-Position: refs/heads/master@{#374046}

TBR=dgozman@chromium.org,jochen@chromium.org,pfeldman@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=580337

Review URL: https://codereview.chromium.org/1676093002

Cr-Commit-Position: refs/heads/master@{#374050}

Former-commit-id: 174c40c5e9028d60c65e6dd24f5965242145fae5