Reland "cc: Switch PrioritizedTextureManager to std::vector."
It was reverted because it failed in XP bots.

CCLayerTreeHostTestScrollChildLayerNormalDpi.runMultiThread:
layer_tree_host_unittest.cc(2304): error: Value of: IntSize()
Actual: 8-byte object <00-00 00-00 00-00 00-00>
Expected: rootScrollLayer->scrollDelta()
Which is: 8-byte object <00-00 00-40 00-00 00-00>
layer_tree_host_unittest.cc(2279): error: Value of: m_rootScrollLayer->scrollPosition()
Actual: 8-byte object <02-00 00-00 00-00 00-00>
Expected: IntPoint()
Which is: 8-byte object <00-00 00-00 00-00 00-00>
layer_tree_host_unittest.cc(2340): error: Value of: m_rootScrolls
Actual: 1
Expected: 0

BUG=154451
TEST=cc_unittests
R=enne@chromium.org,jamesr@chromium.org,danakj@chromium.org


Review URL: https://chromiumcodereview.appspot.com/11231023

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@163157 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 5c47074d69bc278f6fbce11cb1122c17f4a8a353