PNaCl: Update libcxxabi revision to merge from upstream
This merges upto r198643 (from r189194 previously), currently the
latest revision.  libcxxabi doesn't have release tags for 3.3, 3.4,
etc., but it doesn't really matter because the changes are small.

In particular, I needed to pull in the following for the LLVM 3.4 merge:

  r193169: Move local Db type out to namespace scope.

That change fixes the following compile error, since Clang 3.4
apparently got stricter:

libcxxabi/src/cxa_demangle.cpp:4634:9: error: templates cannot be declared inside of a local class
        template <size_t N>

BUG=https://code.google.com/p/nativeclient/issues/detail?id=3757
TEST=PNaCl toolchain trybots
R=dschuff@chromium.org

Review URL: https://codereview.chromium.org/141983002

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@12640 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: f9c5a76c77c2bac312f5026505bf8adfe2a60c1a