Update PPAPI DEPS to fix compile error when building against nacl-glibc
Fixes breakage introduced in r3222.

The error was:
ppapi/cpp/var.cc:316: error: format '%ld' expects type 'long int', but
argument 4 has type 'int32_t' [-Wformat]

BUG=none
TEST=python build.py -b

Review URL: http://codereview.chromium.org/3323013

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@3229 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: 1cf65fb21f0b9b1435c62c9f19a2cb7eed1e9e95