Reverted due to cmpile errors:
chrome/browser/ui/views/tabs/tab_strip.cc:2318:18: error: field 'drop_index' is uninitialized when used here [-Werror,-Wuninitialized]
    : drop_index(drop_index),
                 ^
chrome/browser/ui/views/tabs/tab_strip.cc:2320:18: error: field 'point_down' is uninitialized when used here [-Werror,-Wuninitialized]
      point_down(point_down) {


Revert 180006 - Aura: Fix crash on dragging URL into tab strip

The widget for the window containing the drop-location arrow needs a parent
under Aura to be placed correctly.  A parent or context for each widget is
required due to https://codereview.chromium.org/11829040/

BUG=173229
TEST=Open two tabs, verify you can drag a blue URL link into the space between the two tabs in the tab strip. The URL should open in a new tab and Chrome should not crash.

Review URL: https://codereview.chromium.org/12089084

TBR=jamescook@chromium.org
Review URL: https://codereview.chromium.org/12092099

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@180009 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: cf733fc6ab80b3078510f69535db456b92c5358d