Revert of Optimize DeviceTempFile() by combining logic into a single "adb shell" (patchset #2 id:20001 of https://codereview.chromium.org/1285263009/ )
Reason for revert:
Causing failures like these:

  AdbShellCommandFailedError: (device: 0748d378003b75d6) shell command run via adb failed on the device:
    command: test -d /data/local/tmp && for i in $(seq 10); do fn=/data/local/tmp/temp_file-$(date +%s)-"$RANDOM"'';test -e "$fn" || break;done && touch "$fn" && echo -n "$fn"
    exit status: 255
    output:
    - /system/bin/sh: seq: not found

Please don't attempt to reland this until linux_android_rel_ng is back on the CQ.

Original issue's description:
> Optimize DeviceTempFile() by combining logic into a single "adb shell"
>
> Brings the no-op case of managed_install.py from 11s -> 9s for
> chrome_modern_with_splits_managed when adb is forwarded over ssh.
>
> BUG=520082
>
> Committed: https://crrev.com/9143cf782c6288c8c75a1a2ae954b5af951c16ff [formerly 3d6974192f1d26045e8c83f2ba90c80d1d54324e]
> Cr-Commit-Position: refs/heads/master@{#345115}

TBR=agrieve@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=520082

Review URL: https://codereview.chromium.org/1304893004

Cr-Commit-Position: refs/heads/master@{#345166}

Former-commit-id: 59c47861a0900e703ca042b3b3c326b9677d85e1