buildbot: Better error reporting for failed chromeos-version.sh runs
We recently got a tree closure due to a bad chromeos-version.sh and
are trying to figure out why the script failed.  Knowing what path
was being passed to the script would do a lot to help debug the
failure.

BUG=None
TEST=./portage_utilities_unittest.py returned no errors
TEST=Copied the error message to print all the time to validate
argument formatting, then ran:
  buildbot/cros_mark_as_stable \
    --dryrun \
    --boards=ironhide \
    --overlays=/c/src/private-overlays/overlay-daisy-private \
    -p sys-kernel/chromeos-kernel-exynos \
    commit
Saw as output:
  Package chromeos-kernel-exynos has a chromeos-version.sh
  script but it returned no valid version for
  "/home/dianders/trunk/src/partner_private/kernel-exynos-staging"
Also tried changing 'not os.path.isdir(...)' to 'not not os...'
and saw:
  ERROR: Package chromeos-kernel-exynos source directory doesn't
  exist:
  "/home/dianders/trunk/src/partner_private/kernel-exynos-staging"

Change-Id: I66c0eeac44c3fc54a11965bc6065d8e17f48868a
Reviewed-on: https://gerrit.chromium.org/gerrit/19826
Tested-by: Doug Anderson <dianders@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Ready: Doug Anderson <dianders@chromium.org>