[m98] Fix build for blpwtk2/ext/rubberband (#421)
Due to the following changes:

* `IntPoint`/`IntRect` replaced with `gfx::Point`/`gfx::Rect`

* Fix warning:
  error: inline function 'blink::LayoutObject::StyleRef' is not defined [-Werror,-Wundefined-inline]

* Make some classes `GarbageCollected` to resolve these build errors:
  error: [blink-gc] Class 'RubberbandLayerContext' contains invalid fields.
  note: [blink-gc] Raw pointer field 'm_colBlock' to a GC managed class declared here:

* `DISALLOW_COPY_AND_ASSIGN` has been removed

* Restore `WidgetBase` functions that were removed in previous merge