Revert "cros: Add a double separator above context menu notifications"
This reverts commit b37c9b5ecc55fd7c32eecf134686eb9cdf9874e1 [formerly 1c822163619f765c71f5b7a21d399e727749be72].

Reason for revert: 

Linker failures:
obj/ash/app_menu/app_menu/notification_menu_view.o:notification_menu_view.cc:function ash::NotificationMenuView::NotificationMenuView(ash::NotificationItemView::Delegate*, message_center::SlideOutController::Delegate*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&): error: undefined reference to 'vtable for views::MenuSeparator'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function

Bug: 861885

Original change's description:
> cros: Add a double separator above context menu notifications
> 
> Add and remove a double separator with NOTIFICATION_CONTAINER.
> 
> Bug: 843761
> Change-Id: I45fb095079aaaf108a9a18958ab4e431072e588d
> Reviewed-on: https://chromium-review.googlesource.com/1121243
> Commit-Queue: Alex Newcomer <newcomer@chromium.org>
> Reviewed-by: Michael Wasserman <msw@chromium.org>
> Reviewed-by: James Cook <jamescook@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#573418}

TBR=jamescook@chromium.org,msw@chromium.org,newcomer@chromium.org

Change-Id: I10ce18a75e80116fa8d7a530d18e979a2dfbb395
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 843761
Reviewed-on: https://chromium-review.googlesource.com/1129661
Reviewed-by: Alex Newcomer <newcomer@chromium.org>
Commit-Queue: Alex Newcomer <newcomer@chromium.org>
Cr-Commit-Position: refs/heads/master@{#573429}
Former-commit-id: f69edefd4b309c07c800663227af7120f6dea63f