Fix run.py to work on pexes (broken by r11178)
Before this change, run.py fails with an error in the "pnacl-meta" tool:

  TypeError: GetBitcodeMetadata() takes exactly 2 arguments (1 given)

Fix this by removing use of pexe metadata from run.py.  This feature
was part of PNaCl+glibc dynamic linking support, which we are
gradually removing.

Also remove the pnacl-meta tool, since it doesn't work and isn't
tested.

BUG=https://code.google.com/p/nativeclient/issues/detail?id=3348
TEST=run run.py on a pexe

Review URL: https://codereview.chromium.org/14948012

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@11357 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: 8a1c19b6dc7deb9158d6e548e16eec8f87138feb