Revert of Why do we have this line when it makes sliders look editable? (patchset #2 id:20001 of https://codereview.chromium.org/2893963002/ )
Reason for revert:
Is causing test failures such as https://build.chromium.org/p/chromium.win/builders/Win7%20Tests%20%281%29/builds/67395

DumpAccessibilityEventsTest.AccessibilityEventsAriaSliderValueTextChange

c:\b\c\b\win\src\content\browser\accessibility\dump_accessibility_browsertest_base.cc(363): error: Value of: is_different
  Actual: true
Expected: false
[4988:5300:0523/092002.409:37981750:ERROR:dump_accessibility_browsertest_base.cc(388)] Diff:
* Line Expected
- ---- --------
*    1 EVENT_OBJECT_VALUECHANGE on role=ROLE_SYSTEM_SLIDER value="2%" IA2_STATE_EDITABLE,IA2_STATE_VERTICAL
     2 <-- End-of-file -->
Actual
------
EVENT_OBJECT_VALUECHANGE on role=ROLE_SYSTEM_SLIDER value="2%" IA2_STATE_VERTICAL
<-- End-of-file -->

Original issue's description:
> Why do we have this line when it makes sliders look editable?
>
> BUG=None
>
> Review-Url: https://codereview.chromium.org/2893963002
> Cr-Commit-Position: refs/heads/master@{#473911}
> Committed: https://chromium.googlesource.com/chromium/src/+/d26257035a72a3ffd0e0bc2c4e5a67c18158793f [formerly b78f1ba01120e4f9dfa9faf541b670d893883cfe]

TBR=dmazzoni@chromium.org,aleventhal@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=None

Review-Url: https://codereview.chromium.org/2900953004
Cr-Commit-Position: refs/heads/master@{#473944}

Former-commit-id: ad392f2d79a27751c1dc0e7142b9497ad9042f1e