Revert of Introduce wrapper version of VisibleSelectionTemplate and use it in SelectionController (patchset #1 id:1 of https://codereview.chromium.org/1356853002/ )
Reason for revert:
This doesn't build with gcc (e.g. in android component builds): In file included from ../../third_party/WebKit/Source/core/editing/EditingStyle.h:38:0,                  from ../../third_party/WebKit/Source/core/editing/FrameSelection.h:32,                  from ../../third_party/WebKit/Source/core/layout/HitTestResult.cpp:29: ../../third_party/WebKit/Source/core/editing/VisibleSelection.h:304:50: error: type attributes ignored after type is already defined [-Werror=attributes]  extern template

See also the discussion on https://codereview.chromium.org/1339763003/ – if you can, try to not export templates here.

Original issue's description:
> Introduce wrapper version of VisibleSelectionTemplate and use it in SelectionController
> 
> This patch introduces wrapper version of |VisibleSelectionTemplate| as a
> preparation of introducing full version of |VisibleSelectionTemplate| and
> utilize in |SelectionController| class.
> 
> We'll have following steps to introduce full version of
> |VisibleSelectionTemplate|:
>  1. Introduce wrapper version of |VisibleSelectionTemplate|; this patch
>  2. Utilize in |SelectionController|; this patch
>  3. Utilize in |FrameSelection|;  http://crrev.com/1353673005
>  4. Utilize in |PendingSelection|; http://crrev.com/1350303002
>    - |VisibleSelection::InDOMTree| and |InComposedTree| are gone.
>    - No behavior changes between step 1 to step 4
>  5. Introduce full version of |VisibleSelectionTemplate|
>    - Double-click to select word in composed tree
>  6. Change keyboard navigation to work in composed tree
> 
> This patch is a preparation of making selection to handle granularity for web
> component, http://crrev.com/1277863002
> 
> BUG=513568
> TEST=n/a; no behavior changes
> 
> Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=202521

TBR=yoichio@chromium.org,hajimehoshi@chromium.org,yosin@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=513568

Review URL: https://codereview.chromium.org/1346323004

git-svn-id: svn://svn.chromium.org/blink/trunk@202545 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: c6e063b08df0caaa63b12202586e14198e3005c0