PNaCl: Fixes for mixed bitcode/native linking 1) In the linker, properly handle mixed bitcode/native archive libs, in particular when using --start-group/--end-group. These mostly worked accidentally already but now they are tested. 2) When specifying the __pnacl_start entrypoint, create an undefined reference to _start. _start is referenced from the shim (which is linked at the end of the native link). Usually _start comes from libnacl and will be in the pexe, but the IRT's special _start comes from libirt_browser and the object file containing won't get pulled in otherwise. 3) Add driver tests for the --target flag for the compiler (linker tests don't really work with the current driver test framework) 4) Add test for mixed use of TLS variables. These work currently but result in a non-fatal gold error (see https://codereview.chromium.org/23484004/ )
BUG= https://code.google.com/p/nativeclient/issues/detail?id=3645
R=jvoung@chromium.org

Review URL: https://codereview.chromium.org/23469004

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@12074 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: 7368099aedbfd7ab07fdca7151ad379f72317598