Implement ArcPolicyBridge::GetPolicies, add tests
Small refactoring to make mocking of the policy service
possible. For arc unit tests, the gn-build files were not adjusted
yet. I needed to add one dependency that is needed through the
following code path:
---
FAILED: [...] gomacc [...]
obj/chrome/browser/chromeos/unit_tests/settings_bridge_unittest.o
In file included from
../../chrome/browser/chromeos/arc/settings_bridge_unittest.cc:5:
In file included from
../../chrome/browser/chromeos/arc/settings_bridge.h:13:
In file included from
../../chromeos/settings/timezone_settings.h:13:
../../third_party/icu/source/i18n/unicode/timezone.h:30:10:
fatal error: 'unicode/utypes.h' file not found
---

BUG=b/27807832

Review URL: https://codereview.chromium.org/1819883003

Cr-Commit-Position: refs/heads/master@{#384947}

Former-commit-id: 11db79c14bc1751a3e889c122362b2f364727196