net: build fix about CertificateList
clang complains it doesn't initialize const member, so this CL calls the
default constructor explicitly.

../../net/cert/multi_threaded_cert_verifier.cc:430:25: error: default initialization of an object of const type 'const CertificateList' (aka 'const vector<scoped_refptr<net::X509Certificate> >') without a user-provided default constructor
  const CertificateList empty_cert_list;
                        ^
1 error generated.

Review URL: https://codereview.chromium.org/1572253002

Cr-Commit-Position: refs/heads/master@{#368585}

Former-commit-id: 18937ad93812903be37e75f60510ed258c4117e1