Revert "Ensure RenderFrameHostImpl's RenderFrameSetupPtr doesn't die too early"
This reverts commit 9aaebb1b08528fe6eaced1a0bbde26cdb88bfe8b [formerly 235d012e9d23fbcc456a06496b246fb4e05d98d6].

Reason: caused compilation failure when compiling
content_browser_test_utils:
../../content/browser/frame_host/render_frame_host_impl.h:22:10: fatal
error: 'content/common/render_frame_setup.mojom.h' file not found

TBR=blundell@chromium.org
BUG=

Review URL: https://codereview.chromium.org/672263002

Cr-Commit-Position: refs/heads/master@{#300907}

Former-commit-id: e36cf8ec21fc5d441007920dcba8a9b8f28cf7bc