[Telemetry] Set same settings on memory cache http server that WPR sets.
It looks like the error that the windows dom_perf tests are hitting could be
caused by improperly closing the socket, which this might fix.

error: [Errno 10053] An established connection was aborted by the software in your host machine

BUG=335624

Review URL: https://codereview.chromium.org/259623003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@266074 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 8d72993ee340712ec3f789806153675a19f37767