Revert "chromeos: Remove unused constants"
This reverts commit 1adf9dbc70ffb3d56bbe07e013ccc8b4ef368a72 [formerly 5916bf776a98753bd1f8373daabbc920b8afd29c].

Reason for revert: Breaks Google Chrome ChromeOS

../../chrome/browser/chromeos/login/enrollment/auto_enrollment_controller.cc:87:19: error: no member named 'kFirmwareTypeKey' in namespace 'chromeos::system'
          system::kFirmwareTypeKey, &firmware_type) &&
          ~~~~~~~~^
../../chrome/browser/chromeos/login/enrollment/auto_enrollment_controller.cc:88:32: error: no member named 'kFirmwareTypeValueNonchrome' in namespace 'chromeos::system'
      firmware_type == system::kFirmwareTypeValueNonchrome;
                       ~~~~~~~~^
2 errors generated.

Original change's description:
> chromeos: Remove unused constants
> 
> Remove unused machine statistics from StatisticsProvider.
> 
> Bug: none
> Change-Id: Iffcc8231709b8aa48b7d9622ea1db7e5341b550b
> Reviewed-on: https://chromium-review.googlesource.com/1068944
> Reviewed-by: Dan Erat <derat@chromium.org>
> Commit-Queue: Thiemo Nagel <tnagel@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#560554}

TBR=derat@chromium.org,tnagel@chromium.org

Change-Id: If7bdcb3d4a689bbdc7ad99ff204be57892221bd3
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: none
Reviewed-on: https://chromium-review.googlesource.com/1067999
Reviewed-by: Jeremy Roman <jbroman@chromium.org>
Commit-Queue: Jeremy Roman <jbroman@chromium.org>
Cr-Commit-Position: refs/heads/master@{#560562}
Former-commit-id: f0c1eb4c4d009c543a757ae0604a514b391e7d76