Revert "Fix BLE advertisement on macOS."
This reverts commit 9b97f6c3c09ee677c5ed4f84ba7c699742977c57 [formerly b28da169692913062e2291c3d7815d7ef4437990].

Reason for revert: This is a dependent revert for 
https://chromium-review.googlesource.com/c/chromium/src/+/1142294

Root Reason:

Causes build break
device/bluetooth/bluetooth_low_energy_advertisement_manager_mac.mm:26:35: error: comparison of two values with different enumeration types ('CBManagerState' and 'CBPeripheralManagerState') [-Werror,-Wenum-compare]
  if ([peripheral_manager_ state] < CBPeripheralManagerStatePoweredOn) {
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Original change's description:
> Fix BLE advertisement on macOS.
> 
> The CoreBluetooth APIs expect CBUUID objects instead of raw UUID strings.
> 
> BUG=865851
> TBR=ortuno
> 
> Change-Id: I1ad7ac21a9213d0ee19edafe54f7de096b283347
> Reviewed-on: https://chromium-review.googlesource.com/1144657
> Commit-Queue: Tim Song <tengs@chromium.org>
> Reviewed-by: Tim Song <tengs@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#576793}

TBR=tengs@chromium.org,sacomoto@chromium.org,ortuno@chromium.org

Change-Id: I99fd190bc75a8f572d2129cb3843e8fb747c503d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 865851
Reviewed-on: https://chromium-review.googlesource.com/1145562
Reviewed-by: Robert Liao <robliao@chromium.org>
Commit-Queue: Robert Liao <robliao@chromium.org>
Cr-Commit-Position: refs/heads/master@{#576924}
Former-commit-id: 1d5b9a2b1c7638f50d80aa491e778a870bc9e28e