devtools: Bundling remote devtools modules (#680)
### Background and Motivation

Chromium inspector window has the "Accessibility" tab which can be useful for inspecting and debugging the accessibility-related features of the HTML markup. Unfortunately, it shows up blank in the current build of the terminal. This pull request fixes the issue.

### Description

The root cause of the issue is that the **accessibility_module.js** along with four other devtools modules belong to the remote modules group which are treated differently in the original version of the Chromium. More specifically, they are lazy-loaded modules which are fetched using a special URL: `devtools://devtools/remote/serve_file/@<git commit hash here>/accessibility/accessibility_module.js`. However, this is not the case for our version of the Chromium as the code related to the inspector has significantly diverged from the base Chromium code. (One obvious example of such divergence is that the base Chromium now uses the `devtools://` schema for all devtools-related requests while our inspector continues to use the old URL: `http://127.0.0.1:9223/devtools/inspector.html`.) Our version of the inspector tries to load the remote modules the same way it does for the local modules and since they are not "bundled" (Chromium build script term) into the output directory, the inspector cannot instantiate them which manifests as the following two JavaScript errors:
```
Empty response arrived for script 'http://127.0.0.1:9223/devtools/accessibility/accessibility_module.js'
```
This is because the inspector uses the local-module URL to fetch a remote module.

```
Error: Could not instantiate: Accessibility.AccessibilitySidebarView
    at Runtime.Extension._createInstance (shell.js:109)
    at async UI.ProvidedView.widget (shell.js:1159)
    at async Promise.all (index 1)
```
This is because the **accessibility_module.js** (fetched on the previous step) turned out to be empty.

Instead of trying to merge at least ~700 commits made in the last 18 months in the **devtools-frontend** directory of the upstream Chromium repository, this pull request just bundles all remote modules as if they were local modules. (The similar approach is taken for the Chrome OS build in the original Chromium.)

#### Screenshots

**Before:**
Accessibility tab:
![Empty accessibility tab](https://bbgithub.dev.bloomberg.com/storage/user/5034/files/7a5bd680-176b-11ea-86f2-5feaa157175e)

Console:
![JavaScript errors](https://bbgithub.dev.bloomberg.com/storage/user/5034/files/a37c6700-176b-11ea-89ff-4bcfe0dcc554)

**After:**
Accessibility tab:
![Accessibility tab is working](https://bbgithub.dev.bloomberg.com/storage/user/5034/files/0837c180-176c-11ea-87b5-7dcc14e24524)

Console:
![No JavaScript errors](https://bbgithub.dev.bloomberg.com/storage/user/5034/files/36b59c80-176c-11ea-8a13-60585e8ac4b1)

### Test Plan

1. Build blpwtk2_shell.exe.
2. Run it.
3. Open the inspector.
4. Navigate to the Accessibility tab.

**Expected result:** the contents of the tab is not empty.

### Dependencies and Release Plan

These changes neither add nor remove any external dependencies, switches, tunables, BREGs, or FTAMs which means the changes can be released according to the regular release schedule.

### Tickets

https://jira2.prod.bloomberg.com/browse/ENG2KITFC-303