JsLiteralHelper: Do not make overloads for base::*Value template specializations
Commit b7e7131a ("Introduce EvalJs, a replacement for ExecuteScript and
friends") broke the GCC build with the JsLiteralHelper::Convert() overloads
for base::Value and base::ListValue:

    In file included from ../../content/public/test/test_frame_navigation_observer.h:11:0,
                     from ../../content/public/test/test_frame_navigation_observer.cc:5:
    ../../content/public/test/browser_test_utils.h:416:13: error: explicit specialization in non-namespace scope ‘struct content::JsLiteralHelper<T>’
       template <>
                 ^
    ../../content/public/test/browser_test_utils.h:421:13: error: explicit specialization in non-namespace scope ‘struct content::JsLiteralHelper<T>’
       template <>
                 ^

Since base::Value and base::ListValue overloads are not template
specializations anyway, and a non-template overload is preferred over a
specialized one, we can just drop the "template <>" part and fix the build.

Bug: 819294
Change-Id: I20c4bbed63b2ad7bb3f9146d790159ae1468ece6
Reviewed-on: https://chromium-review.googlesource.com/1167059
Commit-Queue: Nick Carter <nick@chromium.org>
Reviewed-by: Nick Carter <nick@chromium.org>
Cr-Commit-Position: refs/heads/master@{#581601}
Former-commit-id: db900e74d50878e2d48399a310a6de1546e50ba3