aura: Move |observer_manager_| initialization to the member initialization list
Commit 2cc29e0ee ("aura: changes aura not to convert coordinates from ws2")
broke the GCC build:

    ../../base/scoped_observer.h: In instantiation of ‘void ScopedObserver<Source, Observer>::RemoveAll() [with Source = aura::Window; Observer = aura::WindowObserver]’:
    ../../base/scoped_observer.h:26:14:   required from ‘ScopedObserver<Source, Observer>::~ScopedObserver() [with Source = aura::Window; Observer = aura::WindowObserver]’
    ../../ui/aura/window_event_dispatcher.h:315:76:   required from here
    ../../base/scoped_observer.h:45:20: error: invalid use of incomplete type ‘class aura::Window’
           sources_[i]->RemoveObserver(observer_);
           ~~~~~~~~~~~~~^~~~~~~~~~~~~~
    In file included from ../../content/public/browser/render_frame_host.h:22:0,
                     from ../../content/public/test/test_renderer_host.h:17,
                     from ../../chrome/test/base/chrome_render_view_host_test_harness.h:9,
                     from ../../chrome/browser/plugins/pdf_iframe_navigation_throttle_unittest.cc:10:
    ../../ui/gfx/native_widget_types.h:47:7: note: forward declaration of ‘class aura::Window’
     class Window;
           ^~~~~~

Initialize |observer_manager_| in WindowEventDispatcher's constructor
instead, as aura::Window is fully declared by then.

Bug: 819294
Change-Id: I38588698f7a87c0dcf18de78c0721fc41d959b64
Reviewed-on: https://chromium-review.googlesource.com/1082316
Reviewed-by: Scott Violet <sky@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#563709}
Former-commit-id: 368f1ff61e47cafa38f20eb6dbb48be029d4502c