__asm__ instead of asm.
pnacl-clang doesn't like asm with:
tests/exception_test/exception_crash_test.c:192:1: error: extension used [-Werror,-Wlanguage-extension-token]

Use __asm__ instead.

This is in preparation to enable compiling with pnacl-clang for NonSFI NaCl.

BUG=https://code.google.com/p/chromium/issues/detail?id=408879

Review URL: https://codereview.chromium.org/536853002

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@13690 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: aa6ccc4910176b8f65003215262df7eabaf3a42b