ozone: drm: Add missing dependency on ui/gfx
This unbreaks the GN build:

../ui/ozone/platform/drm/gpu/drm_surface_unittest.cc:152: error: undefined reference to 'gfx::RectToSkRect(gfx::Rect const&)'

TEST=gn gen out_gn_ozone --args='target_os="chromeos" use_ozone=true is_component_build=true';
  ninja -C out_gn_ozone -j1000 -k50 ozone_unittests

Review URL: https://codereview.chromium.org/1342473002

Cr-Commit-Position: refs/heads/master@{#348486}

Former-commit-id: 066b8ffdcbd2723d5888c79a00428ff3e76692f6