Revert "Reland Update axe-core to v3.3.2"
This reverts commit e77e504035d326fbdfd798b484c842f4e85e3437 [formerly de35a0973ddba93070fa647b5c664077cef128be].

Reason for revert:
Failing on all platforms.
https://test-results.appspot.com/dashboards/flakiness_dashboard.html#tests=WelcomeA11y.WelcomeFlow_color_contrast
https://ci.chromium.org/p/chromium/builders/ci/Mac10.12%20Tests/27248
[18374:18374:0923/204432.097393:ERROR:CONSOLE(49)] "Mocha test failed: WelcomeFlow_color_contrast Landing Page
Error: the string "Found 1 accessibility violations." was thrown, throw an Error :)
", source: file:///b/s/w/ir/chrome/test/data/webui/mocha_adapter.js (49)
[18374:18374:0923/204432.101101:ERROR:web_ui_test_handler.cc(72)] Test Errors: 1/1 tests had failed assertions.
[18374:18374:0923/204432.101355:ERROR:web_ui_browser_test.cc(546)] CONDITION FAILURE: encountered javascript console error(s):
[18374:18374:0923/204432.101376:ERROR:web_ui_browser_test.cc(548)] JS ERROR: '[18374:18374:0923/204432.097393:ERROR:CONSOLE(49)] "Mocha test failed: WelcomeFlow_color_contrast Landing Page
Error: the string "Found 1 accessibility violations." was thrown, throw an Error :)
", source: file:///b/s/w/ir/chrome/test/data/webui/mocha_adapter.js (49)
'
[18374:18374:0923/204432.101390:ERROR:web_ui_browser_test.cc(550)] JS call assumed failed, because JS console error(s) found.
gen/chrome/test/data/webui/welcome/a11y_tests-gen.cc:285: Failure
Value of: RunJavascriptTestF( true, "WelcomeA11y", "WelcomeFlow_color_contrast")
  Actual: false
Expected: true
Stack trace:
#0 0x55ebe3920b5f StackTraceGetter::CurrentStackTrace()
#1 0x55ebe392955c testing::internal::UnitTestImpl::CurrentOsStackTraceExceptTop()
#2 0x55ebe3928ea9 testing::internal::AssertHelper::operator=()
#3 0x55ebe36c24dd WelcomeA11y_WelcomeFlow_color_contrast_Test::RunTestOnMainThread()
#4 0x55ebe60b131e content::BrowserTestBase::ProxyRunTestOnMainThreadLoop()
#5 0x55ebe5cae39c ChromeBrowserMainParts::PreMainMessageLoopRunImpl()
#6 0x55ebe5cad1ad ChromeBrowserMainParts::PreMainMessageLoopRun()
#7 0x55ebe438318f content::BrowserMainLoop::PreMainMessageLoopRun()
#8 0x55ebe4779607 content::StartupTaskRunner::RunAllTasksNow()
#9 0x55ebe4381e42 content::BrowserMainLoop::CreateStartupTasks()
#10 0x55ebe4384bf2 content::BrowserMainRunnerImpl::Initialize()
#11 0x55ebe438041f content::BrowserMain()
#12 0x55ebe5873245 content::ContentMainRunnerImpl::RunServiceManager()
#13 0x55ebe5872d76 content::ContentMainRunnerImpl::Run()
#14 0x55ebe7a2e8dd service_manager::Main()
#15 0x55ebe4c9c511 content::ContentMain()
#16 0x55ebe60b0dc6 content::BrowserTestBase::SetUp()

Original change's description:
> Reland Update axe-core to v3.3.2
> 
> This change updates the version of axe-core to the latest released
> version. As part of picking up the latest version, the following
> additional changes were made:
> 
> 1) axe-core removed the 'href-no-hash' rule, so that been removed
>    from the test list.
> 
> 2) Several 'link-in-text-block' tests started failing with
>    axe-core v3.0.2 (and later). These tests do pass in v3.0.1, but
>    are disabled as part of this change.
>      - CrManagementA11yTest.SimpleTest_link_in_text_block
>      - CrManagementA11yTestWithExtension.
>                                 ExtensionSection_link_in_text_block
>      - CrostiniAccessibilityTest.CROSTINI_link_in_text_block
>      - CrExtensionsA11yTest.NoExtensions_link_in_text_block
>      - MultideviceA11yTest.MULTIDEVICE_link_in_text_block
>      - MultideviceFeaturesA11yTest.
>               MULTIDEVICE_FEATURES_ACCESSIBILITY_link_in_text_block
> 
> 3) One 'heading-order' test started failing in v3.0.0 (and later).
>    This tests does pass in V2.4.2, but is disabled as part of this
>    change.
>      - CrExtensionsA11yTestWithMultipleExensions.
>                                        WithExtensions_heading_order
> 
> 4) Several DevTools a11y tests were failing. This change either
>    updates the baseline or excludes the rule depending upon the
>    test/rule itself.
>      - http/tests/devtools/a11y-axe-core/basic-a11y-test.js
>      - http/tests/devtools/a11y-axe-core/console-a11y-test.js
>      - http/tests/devtools/a11y-axe-core/memory/heap-profiler-a11y-test.js
>      - http/tests/devtools/a11y-axe-core/sources/dom-breakpoints-pane-a11y-test.js
> 
> I spent some time investigating the test failures, and it looks
> like axe-core is highlighting legitimate product issues.
> 
> Change-Id: I0ef08cdace91250936f83705fb3cd0fbb35bed4b
> Bug: 984817
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1809407
> Commit-Queue: Mike Jackson <mjackson@microsoft.com>
> Reviewed-by: Yang Guo <yangguo@chromium.org>
> Reviewed-by: Hector Carmona <hcarmona@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#699166}

TBR=aboxhall@chromium.org,hcarmona@chromium.org,yangguo@chromium.org,mjackson@microsoft.com,tvanderlippe@chromium.org

Change-Id: I6e74d1ddeec80407fc057dd07c95c492d7e6679f
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 984817
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1819284
Reviewed-by: Alan Cutter <alancutter@chromium.org>
Commit-Queue: Alan Cutter <alancutter@chromium.org>
Cr-Commit-Position: refs/heads/master@{#699191}

Former-commit-id: fc9a09ac6cbb28e13df87e9d80393f7deaa21788