Reland of Enable C4018 globally for the GN build, and disable per-target. (patchset #1 id:1 of https://codereview.chromium.org/1257583007/)
Reason for revert:
I believe the GN build failure was caused by a different patch of brettw's.

Original issue's description:
> Revert of Enable C4018 globally for the GN build, and disable per-target. (patchset #4 id:60001 of https://codereview.chromium.org/1246103007/)
>
> Reason for revert:
> Speculative revert based on windows gn bots failing with
>
> http://build.chromium.org/p/chromium.win/builders/Win8%20GN%20%28dbg%29/builds/10113
>
> FAILED: ninja -t msvc -e environment.x64 -- E:\b\build\goma/gomacc.exe "E:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64/cl.exe" /nologo /showIncludes /FC @obj/base/base/precompile.c.obj.rsp /c ../../build/precompile.cc /Foobj/base/base/precompile.c.obj /Fdobj/base/base_c.pdb
> e:\b\build\slave\win_x64_gn__dbg_\build\src\build\precompile.cc(8) : error C2220: warning treated as error - no 'object' file generated
> e:\b\build\slave\win_x64_gn__dbg_\build\src\build\precompile.cc(8) : warning C4206: nonstandard extension used : translation unit is empty
> ninja: build stopped: subcommand failed.
>
> In theory this warning shouldn't have affected other warnings, but there are no other clear candidates.
>
> Original issue's description:
> > Enable C4018 globally for the GN build, and disable per-target.
> >
> > This matches what the GYP build does.
> >
> > BUG=398202
> > TEST=none
> >
> > Committed: https://crrev.com/58d6f92b9c525795a81654a4d867f686fbcd6019 [formerly d408e1965f8e03629738039289ab7779c42a318c]
> > Cr-Commit-Position: refs/heads/master@{#340590}
>
> TBR=brettw@chromium.org,erg@chromium.org,pkasting@chromium.org
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=398202
>
> Committed: https://crrev.com/7d9d1ad3f3ab8070d04dddef0232250d27e92026 [formerly 4bf2ca554347fc20e1649e5ff4cf700d9fbd713a]
> Cr-Commit-Position: refs/heads/master@{#340623}

TBR=brettw@chromium.org,erg@chromium.org,ccameron@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=398202

Review URL: https://codereview.chromium.org/1259253006

Cr-Commit-Position: refs/heads/master@{#340745}

Former-commit-id: 0d79de12da6b9fcb6f2b6337064637bd1ad05ba5