Revert of Add ModuleDatabaseObserver to observe loaded modules. (patchset #4 id:60001 of https://codereview.chromium.org/2862593003/ )
Reason for revert:
Failing unit tests on Win7 Builder :(

See build https://uberchromegw.corp.google.com/i/chromium.win/builders/Win%207%20Tests%20x64%20%281%29/builds/23912

Test failure (in case it is no longer available):
[ RUN      ] ModuleDatabaseTest.Observers
c:\b\c\b\win\src\chrome\browser\conflicts\module_database_win_unittest.cc(567): error: Value of: before_load_observer.new_module_count()
  Actual: 0
Expected: 1
c:\b\c\b\win\src\chrome\browser\conflicts\module_database_win_unittest.cc(575): error: Value of: after_load_observer.new_module_count()
  Actual: 0
Expected: 1
[  FAILED  ] ModuleDatabaseTest.Observers (2 ms)
[ RUN      ] ModuleDatabaseTest.Observers
c:\b\c\b\win\src\chrome\browser\conflicts\module_database_win_unittest.cc(567): error: Value of: before_load_observer.new_module_count()
  Actual: 0
Expected: 1
c:\b\c\b\win\src\chrome\browser\conflicts\module_database_win_unittest.cc(575): error: Value of: after_load_observer.new_module_count()
  Actual: 0
Expected: 1
[  FAILED  ] ModuleDatabaseTest.Observers (2 ms)
[ RUN      ] ModuleDatabaseTest.Observers
c:\b\c\b\win\src\chrome\browser\conflicts\module_database_win_unittest.cc(567): error: Value of: before_load_observer.new_module_count()
  Actual: 0
Expected: 1
c:\b\c\b\win\src\chrome\browser\conflicts\module_database_win_unittest.cc(575): error: Value of: after_load_observer.new_module_count()
  Actual: 0
Expected: 1
[  FAILED  ] ModuleDatabaseTest.Observers (2 ms)
[ RUN      ] ModuleDatabaseTest.Observers
c:\b\c\b\win\src\chrome\browser\conflicts\module_database_win_unittest.cc(567): error: Value of: before_load_observer.new_module_count()
  Actual: 0
Expected: 1
c:\b\c\b\win\src\chrome\browser\conflicts\module_database_win_unittest.cc(575): error: Value of: after_load_observer.new_module_count()
  Actual: 0
Expected: 1
[  FAILED  ] ModuleDatabaseTest.Observers (2 ms)

Original issue's description:
> Add ModuleDatabaseObserver to observe loaded modules.
>
> This will be used to record metrics about third-party modules.
>
> BUG=717696
>
> Review-Url: https://codereview.chromium.org/2862593003
> Cr-Commit-Position: refs/heads/master@{#470011}
> Committed: https://chromium.googlesource.com/chromium/src/+/ad0d92d21da6d8119af4d2787c9aef71e158581f [formerly e056f0abedca3d2eb9df5d0ff2659b953c3dfee5]

TBR=chrisha@chromium.org,pmonette@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=717696

Review-Url: https://codereview.chromium.org/2870673003
Cr-Commit-Position: refs/heads/master@{#470051}

Former-commit-id: cfdd17a38ebc1e9d90478300fe1ad62bdf19a4c0