Fix Cocoa accessibility callbacks type mismatch
If you compile without preprocessing (first clang -E then clang, like
ccache does by default without CCACHE_CPP2), you will see warnings like:

you will see warnings like:

../../content/browser/accessibility/browser_accessibility_cocoa.mm:1155:12:error: implicit conversion of NULL constant to 'NSUInteger' (aka
'unsigned long') [-Werror,-Wnull-conversion]
    return __null;
    ~~~~~~ ^~~~~~
           0

It's because we return nil when 0 or NO should be returned instead,
normal clang compile won't catch that for some reason, perhaps because
its checking is less strict for preprocessed code.

Review URL: https://codereview.chromium.org/565383003

Cr-Commit-Position: refs/heads/master@{#294848}

Former-commit-id: 8cd33c00d45afc7879d352d471f857c9faab59db