Fix missing .Pass() on returning scoped_ptr<SdchManager::DictionarySet>
Warns on VS2015. I'm not sure why this is new, I guess something
become move-able (or not-move-able).

d:\src\cr3\src\net\base\sdch_manager.cc(459): error C2248: 'scoped_ptr<net::SdchManager::DictionarySet,base::DefaultDeleter<T>>::scoped_ptr': cannot access private
member declared in class 'scoped_ptr<net::SdchManager::DictionarySet,base::DefaultDeleter<T>>'
        with
        [
            T=net::SdchManager::DictionarySet
        ]
d:\src\cr3\src\base\memory\scoped_ptr.h(312): note: see declaration of 'scoped_ptr<net::SdchManager::DictionarySet,base::DefaultDeleter<T>>::scoped_ptr'
        with
        [
            T=net::SdchManager::DictionarySet
        ]
d:\src\cr3\src\net\base\sdch_manager.cc(463): error C2248: 'scoped_ptr<net::SdchManager::DictionarySet,base::DefaultDeleter<T>>::scoped_ptr': cannot access private
member declared in class 'scoped_ptr<net::SdchManager::DictionarySet,base::DefaultDeleter<T>>'
        with
        [
            T=net::SdchManager::DictionarySet
        ]
d:\src\cr3\src\base\memory\scoped_ptr.h(312): note: see declaration of 'scoped_ptr<net::SdchManager::DictionarySet,base::DefaultDeleter<T>>::scoped_ptr'
        with
        [
            T=net::SdchManager::DictionarySet
        ]
d:\src\cr3\src\net\base\sdch_manager.cc(467): error C2248: 'scoped_ptr<net::SdchManager::DictionarySet,base::DefaultDeleter<T>>::scoped_ptr': cannot access private
member declared in class 'scoped_ptr<net::SdchManager::DictionarySet,base::DefaultDeleter<T>>'
        with
        [
            T=net::SdchManager::DictionarySet
        ]
d:\src\cr3\src\base\memory\scoped_ptr.h(312): note: see declaration of 'scoped_ptr<net::SdchManager::DictionarySet,base::DefaultDeleter<T>>::scoped_ptr'
        with
        [
            T=net::SdchManager::DictionarySet
        ]

R=rsleevi@chromium.org
BUG=440500

Review URL: https://codereview.chromium.org/883753004

Cr-Commit-Position: refs/heads/master@{#313399}

Former-commit-id: d9afd5483d99d09ff383d77428195a00141a9d55