Fix list unpacking in wpt-import's test_importer.
Follow-up to commit 0854e7b1ad4dbacc91a8722663bb4acd8feec596 [formerly 4a301c5fdaa0bc156a967f80a45d7a97bcda9183] ("Remove the
--allow-local-commits flag from wpt-import"), which broke wpt imports:

Traceback (most recent call last):
  File "/mnt/data/b/rr/tmpFlAgpq/w/src/third_party/WebKit/Tools/Scripts/wpt-import", line 18, in <module>
    host.exit(importer.main())
  File "/mnt/data/b/rr/tmpFlAgpq/w/src/third_party/WebKit/Tools/Scripts/webkitpy/w3c/test_importer.py", line 55, in main
    if not self.checkout_is_okay():
  File "/mnt/data/b/rr/tmpFlAgpq/w/src/third_party/WebKit/Tools/Scripts/webkitpy/w3c/test_importer.py", line 230, in checkout_is_okay
    ['git', 'log', '--oneline', 'origin/master..HEAD'])[1]
ValueError: need more than 0 values to unpack

(from https://luci-milo.appspot.com/buildbot/chromium.infra.cron/wpt-importer/346)

Tbr: qyearsley@chromium.org
Change-Id: Ic5849c25add80048d4e1e9f1c573031537243ff0
Reviewed-on: https://chromium-review.googlesource.com/579069
Commit-Queue: Raphael Kubo da Costa (rakuco) <raphael.kubo.da.costa@intel.com>
Reviewed-by: Raphael Kubo da Costa (rakuco) <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#488188}
Former-commit-id: 5c9afa6d172553cee20c32241a6084cc9442e885