Move MockLocationProvider to location_provider.cc to fix Linux shared build.
Error was:
out/Release/lib.target/chrome/libbrowser.so: undefined reference to `NewMockLocationProvider()'

MockLocationProvider is used by location_arbitrator.cc resulting in the
above error.

BUG=none
TEST=compiles

Review URL: http://codereview.chromium.org/644002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@39445 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 3037a3d03af4eb75444dbd31c0605a54e5f53e45