Revert of mandoline: Add back/forward support and UI. (patchset #9 id:160001 of https://codereview.chromium.org/1326443006/ )
Reason for revert:
Broke Win x64 GN:
FAILED: ninja -t msvc -e environment.x64 -- E:\b\build\goma/gomacc.exe "E:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64/cl.exe" /nologo /showIncludes /FC @obj/components/web_view/lib/url_request_cloneable.obj.rsp /c ../../components/web_view/url_request_cloneable.cc /Foobj/components/web_view/lib/url_request_cloneable.obj /Fdobj/components/web_view/lib_cc.pdb
e:\b\build\slave\win_x64_gn\build\src\components\web_view\url_request_cloneable.cc(43) : error C2220: warning treated as error - no 'object' file generated
e:\b\build\slave\win_x64_gn\build\src\components\web_view\url_request_cloneable.cc(43) : warning C4267: 'initializing' : conversion from 'size_t' to 'uint32_t', possible loss of data
ninja: build stopped: subcommand failed.

Original issue's description:
> mandoline: Add back/forward support and UI.
>
> BUG=526268
>
> Committed: https://crrev.com/08e138e8fe29d6dc566f4bed2fdf428509aefacb [formerly f72ad72272047f3a1471de9f37e0cba7174ac0b0]
> Cr-Commit-Position: refs/heads/master@{#348673}

TBR=msw@chromium.org,sky@chromium.org,ben@chromium.org,erg@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=526268

Review URL: https://codereview.chromium.org/1343773003

Cr-Commit-Position: refs/heads/master@{#348713}

Former-commit-id: 5848b22c1ecf06ade15bd6eda6d2ac4eab2b3a13