isolateserver: pull _PushState into module scope
In order to pickle Item's, the _PushState class cannot be nested.
Otherwsie we get errors like:
  File "/usr/local/src/chromiumos/chromite/scripts/upload_symbols.py", line 465, in _Upload
    queue.put((item,))
  File "<string>", line 2, in put
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
cPickle.PicklingError: Can't pickle <class 'isolateserver._PushState'>: attribute lookup isolateserver._PushState failed

Since this is an internal class, this makes no real difference.

BUG=chromium:209442
TEST=`./tests/run_isolated_test.py` passes
R=vadimsh@chromium.org

Review URL: https://codereview.appspot.com/61480048