M-80: Files app: Fix VolumeInfoImpl when filesystem is null
Change resolveDisplayRootImpl_() to always fail if there is no file
system, regardless of volume type. This fixes error when Drive volume
couldn't resolve file system:
TypeError: Cannot read property 'root' of null

Test: browser_tests --gtest_filter="FileManagerJsTest.VolumeManagerTest"
Bug: 1041340
Change-Id: Iae60dd16c7ff6269623e605d36e2e1952120eb46
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1999893
Commit-Queue: Luciano Pacheco <lucmult@chromium.org>
Auto-Submit: Luciano Pacheco <lucmult@chromium.org>
Reviewed-by: Austin Tankiang <austinct@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#731117}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2006435
Reviewed-by: Luciano Pacheco <lucmult@chromium.org>
Cr-Commit-Position: refs/branch-heads/3987@{#595}
Cr-Branched-From: f8ec429d946866f630bf422440e162a16c8b97d1 [formerly c4e8da9871cc266be74481e212f3a5252972509d]-refs/heads/master@{#722274}

Former-commit-id: 0f1e8a3ba49d5bcea414de3c5f2d7246718b47f5