Revert "overview: Introduce OnOverviewStartAnimationComplete observer."
This reverts commit 2fff037d3367b1affdd734fdf7cdb81ccb383358 [formerly 77cbc4f0fa1c446950859be5859071b9689208ae].

Reason for revert:
Suspect compile failure on linux-chromeos-dbg.

Example:
https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/linux-chromeos-dbg/8511

Log:
FAILED: ash_unittests 
../../buildtools/third_party/libc++/trunk/include/memory:5091: error: undefined reference to 'ash::StartAnimationObserver::StartAnimationObserver()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Original change's description:
> overview: Introduce OnOverviewStartAnimationComplete observer.
> 
> Introdue a new overview observer which notifies observers when the start
> animation for overview is different.
> 
> Uses will be both in and out of overview - for example adding mask, shadow
> and animating tray, shelf.
> 
> Also modify CleanupObserverTest to use some new stuff.
> 
> Test: ash_unittests StartAnimationObserverTest.Basic
> Bug: 898222
> Change-Id: I86bdd253f0a4a4dd81ad6ba03780baf07923d256
> Reviewed-on: https://chromium-review.googlesource.com/c/1297405
> Commit-Queue: Sammie Quon <sammiequon@chromium.org>
> Reviewed-by: Mitsuru Oshima <oshima@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#602941}

TBR=oshima@chromium.org,sammiequon@chromium.org

Change-Id: I5038dbe64ae02fb0f71a7c4ffcc36bcfaaca13ca
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 898222
Reviewed-on: https://chromium-review.googlesource.com/c/1300815
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#602972}
Former-commit-id: aa89084324fd9fc9d3d665bf7fefa2863bff8089