Revert of Flip Linux bots on chromium.lkgr to GN. (patchset #1 id:1 of https://codereview.chromium.org/2057193003/ )
Reason for revert:
This breaks:

* UBSan vptr Release: https://build.chromium.org/p/chromium.lkgr/builders/UBSan%20vptr%20Release/builds/3782/steps/compile/logs/stdio
clang: error: argument unused during compilation: '-fsanitize-coverage=edge'
This is https://crbug.com/618534

* The 3 32-bit x86 with 32-bit arm v8 asan bots, e.g. https://build.chromium.org/p/chromium.lkgr/builders/ASan%20Debug%20%2832-bit%20x86%20with%20V8-ARM%29/builds/2477/steps/compile/logs/stdio
../../v8/src/base/build_config.h:145:2: error: Target architecture ia32 is only supported on ia32 host
#error Target architecture ia32 is only supported on ia32 host
 ^
I filed https://crbug.com/619503 for this.

Original issue's description:
> Reland of Flip Linux bots on chromium.lkgr to GN. (patchset #3 id:60001 of https://codereview.chromium.org/2054843002/ )
>
> Reason for revert:
> This might work now (see https://crbug.com/618702, which I forgot to mention in the revert message).
>
> Original issue's description:
> > Revert of Flip Linux bots on chromium.lkgr to GN. (patchset #3 id:40001 of https://codereview.chromium.org/2006173002/ )
> >
> > Reason for revert:
> > This had no effect: The LKGR waterfall used to be not on recipes, and mb wasn't hooked up right and in gn mode wrote its output to out/None (and runhooks still ran gyp, so gyp's ninja files were always used).
> >
> > I've now switched most of the bots to recipes, and now gn does have an effect, and all the bots now fail to build 'cause they build "chromium_builder_asan", a target that doesn't exist in the gn build.
> >
> > Reverting to get back to a working state. I'll look at fixing and will hopefully reland this soon.
> >
> > Original issue's description:
> > > Flip Linux bots on chromium.lkgr to GN.
> > >
> > > R=brettw@chromium.org, inferno@chromium.org
> > > BUG=605732
> > >
> > > Committed: https://crrev.com/3ba0f82a6eb631cb2e5dc6bdf00612459f84d90c [formerly 6864dbb0407a47f697901f70105d2c2c829c08bc]
> > > Cr-Commit-Position: refs/heads/master@{#398038}
> >
> > TBR=brettw@chromium.org,inferno@chromium.org,dpranke@chromium.org
> > # Not skipping CQ checks because original CL landed more than 1 days ago.
> > BUG=605732
> >
> > Committed: https://crrev.com/ec5dbc9e02d438f0a06d383c236bdee6fb2a68f2 [formerly 424b728048335ebf880781b600f65fc7d993e206]
> > Cr-Commit-Position: refs/heads/master@{#398904}
>
> TBR=brettw@chromium.org,inferno@chromium.org,dpranke@chromium.org
> # Not skipping CQ checks because original CL landed more than 1 days ago.
> BUG=605732
>
> Committed: https://crrev.com/8c93b47c866425bffa7347797e3cfaa991770fac [formerly e4e9b9ce3b7b6309477ac846f5ff8b565745fd75]
> Cr-Commit-Position: refs/heads/master@{#399261}

TBR=brettw@chromium.org,inferno@chromium.org,dpranke@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=605732
NOTRY=true

Review-Url: https://codereview.chromium.org/2063673002
Cr-Commit-Position: refs/heads/master@{#399427}

Former-commit-id: d83c5cb290e0e17caf4ff38d25719030780f60db