Revert 242158 "Refactor CastSocket code for the following:"
Broke Win compile:
231>C:\b\build\slave\Win\build\src\chrome/browser/extensions/api/cast_channel/cast_socket.h(19): fatalerror C1083: Cannot open include file: 'chrome/browser/extensions/api/cast_channel/cast_channel.pb.h': No such file or directory

> Refactor CastSocket code for the following:
> - Refactor the Write code to avoid recursion
> - Refactor the read code to avoid recursion
> - With read code refactored, hook it up appropriately with connection flow
>   to avoid re-entrancy of DoConnectLoop
> 
> Review URL: https://codereview.chromium.org/79673003

TBR=munjal@chromium.org

Review URL: https://codereview.chromium.org/120323002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@242199 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 13c3497e0bf749e2bf9bb4e0112bf7b1bab63933