Revert of Use the same browser instance in the sync confirmation dialog. (patchset #4 id:120001 of https://codereview.chromium.org/2771113003/ )
Reason for revert:
Reverting due to linker error on Linux ChromiumOS Builder (dbg):

FAILED: chrome
../../chrome/browser/ui/views/profiles/signin_view_controller_delegate_views.cc:190: error: undefined reference to 'SyncConfirmationUI::InitializeMessageHandlerWithBrowser(Browser*)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Original issue's description:
> Use the same browser instance in the sync confirmation dialog.
>
> Before this CL, the sync confirmation dialog used the active browser
> when dismissing the dialog. In some cases, the active browser is different
> than the browser that actually presented the sync confirmation dialog
> and this leads to unexpected behavior.
>
> This CL fixes the browser instance used by the sync confirmation dialog
> and ensures that the same instace is used throughout the lifetime of the
> sync confirmation dialog.
>
> TEST=See bug
> BUG=694476
>
> Review-Url: https://codereview.chromium.org/2771113003
> Cr-Commit-Position: refs/heads/master@{#460345}
> Committed: https://chromium.googlesource.com/chromium/src/+/2acd1cab4d4b37edb3c303685c7c5b0f0c511a12 [formerly fc05776e6cc541dc9f4b6652876be72549f41682]

TBR=anthonyvd@chromium.org,tommycli@chromium.org,pkasting@chromium.org,msarda@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=694476

Review-Url: https://codereview.chromium.org/2787453002
Cr-Commit-Position: refs/heads/master@{#460349}

Former-commit-id: 87301efc7eee4e37e3af750bc43f2977b386652b