[Cronet] fix NoClassDefFoundError crash
There have been some recent changes in JNI registration (see:
crbug.com/442327). These changes affect Cronet as well. Currently
Cronet builds are crashing with a java.lang.NoClassDefFoundError.
This CL is to fix the build.

Review URL: https://codereview.chromium.org/953603003

Cr-Commit-Position: refs/heads/master@{#317832}

Former-commit-id: 3b8f568c535855a63cb585d606a7e970f8820c58