Revert "Get rid of extraneous accessibility tree traversal code."
This reverts commit 0a6c341569cca84b9e1116838a683f9cadec090e.

This CL broke the build:

http://build.chromium.org/p/chromium.webkit/builders/Mac10.6%20Tests/builds/18426/steps/compile/logs/stdio

../../content/renderer/accessibility/renderer_accessibility_browsertest.cc:304:56:
error: no member named 'firstChild' in 'WebKit::WebAccessibilityObject'
  const WebAccessibilityObject& first_child = root_obj.firstChild();

TBR=dmazzoni@google.com

Review URL: https://codereview.chromium.org/16626002

git-svn-id: svn://svn.chromium.org/blink/trunk@152009 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: ba7edf71987985dbdb28c40fbc501b9eaa7f461e