Add some missing public_deps for //components/sync
sync_stopped_reporter.h includes files from these targets, therefore they are part of its public interface.

Example error:
In file included from ../../ios/chrome/browser/ui/tab_switcher/tab_switcher_model.mm:10:
In file included from ../../components/browser_sync/profile_sync_service.h:43:
In file included from ../../components/sync/driver/sync_stopped_reporter.h:14:
In file included from ../../net/url_request/url_fetcher.h:19:
In file included from ../../net/url_request/url_request.h:26:
In file included from ../../net/base/net_error_details.h:9:
In file included from ../../net/http/http_response_info.h:14:
In file included from ../../net/ssl/ssl_info.h:20:
In file included from ../../net/ssl/ssl_config.h:12:
In file included from ../../net/cert/x509_certificate.h:25:
../../third_party/boringssl/src/include/openssl/base.h:71:10: fatal error: 'openssl/is_boringssl.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~

BUG=none

Review-Url: https://codereview.chromium.org/2872033003
Cr-Commit-Position: refs/heads/master@{#470500}

Former-commit-id: 7b22c73b32037861ca20e3689176108b88690853