Fix truncation due to wrong abs calls found by clang's new -Wabsolute-value.
The warning looks like this:
../../third_party/WebKit/Source/core/animation/Player.cpp:304:53: error: using integer absolute value function 'abs' when argument is of floating point type [-Werror,-Wabsolute-value]
    return m_content->timeToReverseEffectChange() / abs(m_playbackRate);
                                                    ^
../../third_party/WebKit/Source/core/animation/Player.cpp:304:53: note: use function 'fabs' instead
    return m_content->timeToReverseEffectChange() / abs(m_playbackRate);
                                                    ^~~
                                                    fabs
1 error generated.

BUG=351479
R=hans@chromium.org

Review URL: https://codereview.chromium.org/195523004

git-svn-id: svn://svn.chromium.org/blink/trunk@168950 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: 791d76700e1fa90eb7e1f0f6c4d8186076855058