PictureLayerImpl: Use ceil() instead of ceilf()
ceilf() is only formally mentioned in C++17, even though previous versions
of the standard say <cmath> should have the same contents as C's math.h.

libstdc++ does not ship ceilf() in its cmath, but the ceil(float) overload
that _is_ in the standard is available everywhere, so use that instead.

This fixes the build with libstdc++ after d26224290c [formerly 77b67445ba] ("Elements with fixed
bottom and top stick to top"):

    ../../cc/layers/picture_layer_impl.cc: In member function ‘void cc::PictureLayerImpl::UpdateViewportRectForTilePriorityInContentSpace()’:
    ../../cc/layers/picture_layer_impl.cc:738:16: error: ‘ceilf’ is not a member of ‘std’
               std::ceilf(-total_controls_height * hidden_ratio));  // bottom
                    ^~~~~
    ../../cc/layers/picture_layer_impl.cc:738:16: note: suggested alternative: ‘ceil’
               std::ceilf(-total_controls_height * hidden_ratio));  // bottom
                    ^~~~~
                    ceil

Bug: 819294
Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;master.tryserver.blink:linux_trusty_blink_rel
Change-Id: Ida69eb3127ca132e7090c9aad0dd17dc314b6992
Reviewed-on: https://chromium-review.googlesource.com/c/1264537
Commit-Queue: David Bokan <bokan@chromium.org>
Reviewed-by: David Bokan <bokan@chromium.org>
Cr-Commit-Position: refs/heads/master@{#597709}
Former-commit-id: cc843eb64f6599d9ede176f711fe6355015c30b1