Revert 156088 "Remove innerSpinButtonElement() and speechButtonE..."
Breaks android builder:
../../third_party/WebKit/Source/web/WebInputElement.cpp -o obj/third_party/WebKit/Source/web/webkit.WebInputElement.o
../../third_party/WebKit/Source/web/WebInputElement.cpp:215:15: error: 'InputFieldSpeechButtonElement' does not name a type
ninja: build stopped: subcommand failed

> Remove innerSpinButtonElement() and speechButtonElement() from HTMLInputElement.
> 
> Use ShadowRoot::getElementById instead.
> 
> BUG=
> 
> Review URL: https://chromiumcodereview.appspot.com/22879005

TBR=tkent@chromium.org

Review URL: https://codereview.chromium.org/23140004

git-svn-id: svn://svn.chromium.org/blink/trunk@156091 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: 11cddeb3977dbaa68e9481b5653a61bb11b84776