Revert "Downloads Web UI: Add individual grd file"
This reverts commit 5309cfd8f07eac3563a723b4273f8d13ba56c935 [formerly e36181d3444121ab0b4f7b7e95a674e6b0dbe587].

Seems thios cause al internal chrome builders to fail with a compile error.

https://ci.chromium.org/p/chrome/builders/luci.chrome.ci/mac-google-rel
https://ci.chromium.org/p/chrome/builders/luci.chrome.ci/win-google-rel
https://ci.chromium.org/p/chrome/builders/luci.chrome.ci/linux-google-rel


[9689/40525] ACTION //chrome/browser/resources/downloads:flattened_resources_grit(//build/toolchain/linux:clang_x64)
FAILED: gen/chrome/browser/resources/downloads/flattened_resources_stamp.d.stamp gen/chrome/browser/resources/downloads/grit/downloads_resources.h gen/chrome/browser/resources/downloads/grit/downloads_resources_map.cc gen/chrome/browser/resources/downloads/grit/downloads_resources_map.h gen/chrome/browser/resources/downloads/downloads_resources.pak gen/chrome/browser/resources/downloads/downloads_resources.pak.info 
python ../../tools/grit/grit.py -i ../../chrome/browser/resources/downloads/downloads_resources.grd build -o gen/chrome/browser/resources/downloads --depdir . --depfile gen/chrome/browser/resources/downloads/flattened_resources_stamp.d --write-only-new=1 --depend-on-stamp -D _google_chrome -E CHROMIUM_BUILD=google_chrome -D desktop_linux -D toolkit_views -D use_aura -D use_nss_certs -D enable_app_list=false -D enable_arcore=false -D enable_background_mode=true -D enable_background_contents=true -D enable_extensions=true -D enable_hangout_services_extension=true -D enable_plugins=true -D enable_print_preview=true -D enable_printing=true -D enable_service_discovery=true -D enable_vr=true -D safe_browsing_mode=1 -D optimize_webui=true -E root_gen_dir=gen -f ../../tools/gritsettings/resource_ids --assert-file-list=obj/chrome/browser/resources/downloads/flattened_resources_expected_outputs.txt
Error processing node <?xml version="1.0" encoding="UTF-8"?>
<include file="${root_gen_dir}\chrome\browser\ui\webui\downloads\downloads.mojom-lite.js" name="IDR_DOWNLOADS_MOJO_LITE_JS" type="BINDATA" use_base_dir="false" />
Traceback (most recent call last):
  File "../../tools/grit/grit.py", line 15, in <module>
    sys.exit(grit.grit_runner.Main(sys.argv[1:]))
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/grit_runner.py", line 256, in Main
    return toolobject.Run(options, args[1:])
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/tool/build.py", line 256, in Run
    self.Process()
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/tool/build.py", line 381, in Process
    self.ProcessNode(self.res, output, outfile)
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/tool/build.py", line 315, in ProcessNode
    formatted = formatter(node, output_node.GetLanguage(), output_dir=base_dir)
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/format/data_pack.py", line 83, in Format
    value = node.GetDataPackValue(lang, UTF8)
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/node/include.py", line 102, in GetDataPackValue
    data = util.ReadFile(filename, util.BINARY)
  File "/b/s/w/ir/cache/builder/src/tools/grit/grit/util.py", line 206, in ReadFile
    with open(filename, mode) as f:
IOError: [Errno 2] No such file or directory: u'../../out/Release/gen/chrome/browser/ui/webui/downloads/downloads.mojom-lite.js'

Reverting to green the chomium tree.

Original change's description:
> Downloads Web UI: Add individual grd file
> 
> Change downloads to use the same approach as settings, extensions, and
> print preview:
> (1) Use an individual grd file instead of browser_resources.grd
> (2) Create unpak folder
> 
> Bug: 715296
> Change-Id: Ifd0ce1c46e11ad80ee17fa8c5e55aab33543bfa1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1598320
> Reviewed-by: Lei Zhang <thestig@chromium.org>
> Reviewed-by: Demetrios Papadopoulos <dpapad@chromium.org>
> Commit-Queue: Rebekah Potter <rbpotter@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#658369}

TBR=thestig@chromium.org,dpapad@chromium.org,rbpotter@chromium.org

Change-Id: Icbb9245ea2e3e6014f729625d217aa7cdc009f6e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 715296
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1604390
Reviewed-by: Noel Gordon <noel@chromium.org>
Commit-Queue: Noel Gordon <noel@chromium.org>
Cr-Commit-Position: refs/heads/master@{#658438}

Former-commit-id: 3f8261af2d3c893a6b39a4c875d378f22f08215a