Revert of [Home] Close the BottomSheet when a URL is loaded on the NTP (patchset #1 id:1 of https://codereview.chromium.org/2829523002/ )
Reason for revert:
Broke Lollipop Tester

junit.framework.AssertionFailedError: Sheet should be at half height expected:<1> but was:<3>
	at org.chromium.chrome.browser.ntp.ChromeHomeNewTabPageTest.validateState(ChromeHomeNewTabPageTest.java:197)
	at org.chromium.chrome.browser.ntp.ChromeHomeNewTabPageTest.createNewTab(ChromeHomeNewTabPageTest.java:168)
	at org.chromium.chrome.browser.ntp.ChromeHomeNewTabPageTest.testCloseNTP_TwoTabs(ChromeHomeNewTabPageTest.java:92)
	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
	at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
	at org.chromium.chrome.test.ChromeActivityTestCaseBase.runTest(ChromeActivityTestCaseBase.java:758)
	at org.chromium.base.test.BaseTestResult.runParameterized(BaseTestResult.java:161)
	at org.chromium.base.test.BaseTestResult.run(BaseTestResult.java:124)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)

Original issue's description:
> [Home] Close the BottomSheet when a URL is loaded on the NTP
>
> This ensures that a click on the doodle will close the BottomSheet.
>
> BUG=712607
>
> Review-Url: https://codereview.chromium.org/2829523002
> Cr-Commit-Position: refs/heads/master@{#465604}
> Committed: https://chromium.googlesource.com/chromium/src/+/e27ddef676dd385b9e2e9fd854ff56160ac0a4fd [formerly 2a80017ed38340c00d1d214a3a2445acf5a9ed05]

TBR=mvanouwerkerk@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=712607

Review-Url: https://codereview.chromium.org/2830743003
Cr-Commit-Position: refs/heads/master@{#465726}

Former-commit-id: 38ce623f9ffd74711a06046ff47d371e5ca5a48c