[Owners Extractor] Whitelist LayoutTests/FlagExpectations/.
Follow-up to commits 1f9abb1829884e [formerly 874543453709fb] ("[Owners Extractor] Fix issues found in
the actual run") and 2a8b9a9e4414d [formerly 57c4e4a54dc9e] ("[Owners Extractor] Do not assert when
LayoutTests/ itself is passed").

It turns out we were still asserting when an expectation file inside
LayoutTests/FlagExpectations/ was updated. A concrete case comes from
https://github.com/w3c/web-platform-tests/commit/27838c0248a1772d4bf6c1f378be63e25f700184,
which moved a test to a different directory. wpt-import adjusted the path in
one of the expectation files in LayoutTests/FlagExpectations/ accordingly,
but the owners extractor complained a forbidden path had been changed.

From
https://luci-milo.appspot.com/buildbot/chromium.infra.cron/wpt-importer/1005:

2017-08-31 08:35:28,494 - Gathering directory owners emails to CC.
Traceback (most recent call last):
  File "/mnt/data/b/rr/tmpCMVvWc/w/src/third_party/WebKit/Tools/Scripts/wpt-import", line 25, in <module>
    main()
  File "/mnt/data/b/rr/tmpCMVvWc/w/src/third_party/WebKit/Tools/Scripts/wpt-import", line 18, in main
    host.exit(importer.main())
  File "/mnt/data/b/rr/tmpCMVvWc/w/src/third_party/WebKit/Tools/Scripts/webkitpy/w3c/test_importer.py", line 126, in main
    self._upload_cl()
  File "/mnt/data/b/rr/tmpCMVvWc/w/src/third_party/WebKit/Tools/Scripts/webkitpy/w3c/test_importer.py", line 413, in _upload_cl
    directory_owners = self.get_directory_owners()
  File "/mnt/data/b/rr/tmpCMVvWc/w/src/third_party/WebKit/Tools/Scripts/webkitpy/w3c/test_importer.py", line 437, in get_directory_owners
    return extractor.list_owners(changed_files)
  File "/mnt/data/b/rr/tmpCMVvWc/w/src/third_party/WebKit/Tools/Scripts/webkitpy/w3c/directory_owners_extractor.py", line 43, in list_owners
    owners_file, owners = self.find_and_extract_owners(self.filesystem.dirname(relpath))
  File "/mnt/data/b/rr/tmpCMVvWc/w/src/third_party/WebKit/Tools/Scripts/webkitpy/w3c/directory_owners_extractor.py", line 75, in find_and_extract_owners
    directory, external_root)
AssertionError: /mnt/data/b/rr/tmpCMVvWc/w/src/third_party/WebKit/LayoutTests/FlagExpectations must start with /mnt/data/b/rr/tmpCMVvWc/w/src/third_party/WebKit/LayoutTests/external

Bug: 713987
Change-Id: Ib400628398b228910f54ad24a84b6107c5ffec9d
Reviewed-on: https://chromium-review.googlesource.com/645852
Reviewed-by: Philip Jägenstedt <foolip@chromium.org>
Reviewed-by: Quinten Yearsley <qyearsley@chromium.org>
Commit-Queue: Raphael Kubo da Costa (rakuco) <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#498922}
Former-commit-id: 0f8e35ed6ebe956f4ad097242d365f18cd412c49