BUILD FIX: RenderLayerFilterInfo.h needs to include Element.h with ENABLE(SVG)
Fixes the following build failures:

    In file included from Source/WebCore/rendering/RenderLayerFilterInfo.cpp:33:
    Source/WebCore/rendering/RenderLayerFilterInfo.h:118:19: error: use of undeclared identifier 'Element'
        Vector<RefPtr<Element> > m_internalSVGReferences;
                      ^
    Source/WebCore/rendering/RenderLayerFilterInfo.h:118:28: error: expected a type
        Vector<RefPtr<Element> > m_internalSVGReferences;
                               ^
    Source/WebCore/rendering/RenderLayerFilterInfo.h:118:30: error: private field 'm_internalSVGReferences' is not used [-Werror,-Wunused-private-field]
        Vector<RefPtr<Element> > m_internalSVGReferences;
                                 ^
    3 errors generated.

* rendering/RenderLayerFilterInfo.h: Include Element.h within
ENABLE(SVG).  Move ENABLE(SVG) block below unconditional
headers.

git-svn-id: svn://svn.chromium.org/blink/trunk@144574 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: cd86850098070c662567dd511157ab15851ad95d