Revert change 10975 and 10972 because it broke the purify tests, and it might have caused a unit tests failure.
purify error :  UMR in URLRequest::response_data_file
failing test:
URLFetcherHeadersTest.Headers:
c:\b\slave\chromium-rel-builder\build\src\chrome\browser\net\url_fetcher_unittest.cc(222): error: Value of: source->response_headers()->GetNormalizedHeader("cache-control", &header)
  Actual: false
Expected: true
c:\b\slave\chromium-rel-builder\build\src\chrome\browser\net\url_fetcher_unittest.cc(223): error: Value of: header
  Actual: ""
Expected: "private"
c:\b\slave\chromium-rel-builder\build\src\chrome\browser\net\url_fetcher_unittest.cc(181): error: Value of: response_code
  Actual: 404
Expected: 200

Release only.

Review URL: http://codereview.chromium.org/39191

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@10988 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: bd328ad5f82d9d7d3bbd45d98c5e38e13044b82b