Remove trailing garbage from bisect-builds.py
  File "tools/bisect-builds.py", line 897
    return m.group(1)]
                     ^
SyntaxError: invalid syntax

(introduced in http://crrev.com/2136353002)

R=dpranke@chromium.org,thakis@chromium.org
NOTRY=true

Review-Url: https://codereview.chromium.org/2146583002
Cr-Commit-Position: refs/heads/master@{#404847}

Former-commit-id: a898d221e7a213f2b011c1751276a55da6f5a0c4