[Android] Fix compilation error: unused variable 'kAllowedToAccessOnNonjoinableThread'
While building with clang=1, clang reports this error about the above variable being unused.

BUG=349521
NOTRY=true

Review URL: https://codereview.chromium.org/188003002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@255159 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 9128872c016fc45255fe06ff4431132fcc9b0c86