Revert of Rename WriteString to WriteStringPiece16 in SpdyFrameBuilder (patchset #3 id:40001 of https://codereview.chromium.org/910393003/)
Reason for revert:
Appears to be causing iOS Device compile errors on waterfall: https://build.chromium.org/p/chromium.mac/builders/iOS_Device

Last 4 builds all fail with this log:

=== BUILD TARGET net_unittests OF PROJECT net WITH CONFIGURATION Release ===

Check dependencies

Ld /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/net_unittests.app/net_unittests normal armv7
    cd /Volumes/data/b/build/slave/iOS_Device/build/src/net
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/chrome-bot/slavebin:/Volumes/data/b/depot_tools:/usr/local/git/bin:/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    /Volumes/data/b/build/slave/iOS_Device/build/src/net/../third_party/llvm-build/Release+Asserts/bin/clang++ -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk -L/Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/System/Library/Frameworks -F/Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos -filelist /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/net.build/Release-iphoneos/net_unittests.build/Objects-normal/armv7/net_unittests.LinkFileList -dead_strip -Wl,-search_paths_first -stdlib=libc++ -miphoneos-version-min=7.0 /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libbase.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libbase_i18n.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libbase_prefs_test_support.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libdynamic_annotations.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libcrcrypto.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libgmock.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libgtest.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libchrome_zlib.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/liburl_lib.a -lbalsa -lnet -lnet_extras -lnet_test_support -lquic_tools /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libcrnspr.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libcrnss.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libcrssl.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libbase_static.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/liballocator_extension_thunks.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libmodp_b64.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libicui18n.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libicuuc.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libbase_prefs.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libnss_static.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libsqlite_regexp.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libcrnssckbi.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libzlib_x86_simd.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libsdch.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libsql.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libtest_support_base.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libxml.a /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/libtld_cleanup_util.a -framework CoreFoundation -framework CoreGraphics -framework CoreText -framework Foundation -framework UIKit -lsqlite3 -framework CFNetwork -framework MobileCoreServices -framework Security -framework SystemConfiguration -lresolv -lxml2 -Xlinker -dependency_info -Xlinker /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/net.build/Release-iphoneos/net_unittests.build/Objects-normal/armv7/net_unittests_dependency_info.dat -o /Volumes/data/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/net_unittests.app/net_unittests
Undefined symbols for architecture armv7:
  "net::SpdyFrameBuilder::WriteStringPiece16(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&)", referenced from:
      net::SpdyFramerTest_DuplicateHeader_Test::TestBody() in spdy_framer_test.o
      net::SpdyFramerTest_MultiValueHeader_Test::TestBody() in spdy_framer_test.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Original issue's description:
> Rename WriteString to WriteStringPiece16 in SpdyFrameBuilder
>
> As the comment in net/spdy/spdy_frame_builder.h by hkhalil@,
> rename WriteString to WriteStringPiece16.
>
> BUG=458880
> R=bnc@chromium.org
>
> Committed: https://crrev.com/0871320ec4c167ca98a0ad7fb954e8d202e3b18b [formerly d588d971032596c63dd082b3d5c7438997467ddd]
> Cr-Commit-Position: refs/heads/master@{#319804}

TBR=bnc@chromium.org,asanka@chromium.org,mmenke@chromium.org,zhuoyu.qian@samsung.com
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=458880

Review URL: https://codereview.chromium.org/991313002

Cr-Commit-Position: refs/heads/master@{#319876}

Former-commit-id: c0be9ce8427d161e7d2391e592f0e4fd34a8c6b2