RasterInProcessContext: Rename |ContextSupport()| to avoid naming conflicts
GCC is stricter than clang when it comes to class members' names and how
they can change the meaning of a previously existing symbol with the same
name:

    In file included from ../../gpu/ipc/raster_in_process_context.cc:5:0:
    ../../gpu/ipc/raster_in_process_context.h:57:34: error: declaration of ‘gpu::ContextSupport* gpu::RasterInProcessContext::ContextSupport()’ [-fpermissive]
       ContextSupport* ContextSupport();
                                      ^
    ../../gpu/ipc/raster_in_process_context.h:17:7: error: changes meaning of ‘ContextSupport’ from ‘class gpu::ContextSupport’ [-fpermissive]
     class ContextSupport;
           ^~~~~~~~~~~~~~

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84709 contains a longer
explanation, but essentially having a |ContextSupport()| method can change
the meaning of references to |ContextSupport| in the code depending on where
it is declared, which contradicts the C++ standard.

Fix it by renaming the method to |GetContextSupport()|.

Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:win_optional_gpu_tests_rel;master.tryserver.blink:linux_trusty_blink_rel
Change-Id: Ice57ec40d9f49bdd007b07296390af1a75567f9b
Reviewed-on: https://chromium-review.googlesource.com/1019306
Reviewed-by: Jonathan Backer <backer@chromium.org>
Reviewed-by: kylechar <kylechar@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#552001}
Former-commit-id: 98f459421d97b8abea034d877cbc7c82ae3bec1e