Fix Windows XP tests by increasing time allotted to run_service_runtime_tests
Following r9855 (which added some tests to run_service_runtime_tests),
this test is "failing" on xp-glibc-opt only with:

ERROR: should have taken less than 20.000000 secs
[  FAILED  ] nacl_glibc.run_service_runtime_tests (27734 ms)

This is not a real failure because the test passes fine but is
regarded as taking too long.

In contrast, xp-newlib-opt gives:
WARNING: should have taken less than 2.000000 secs
[       OK ] nacl_newlib.run_service_runtime_tests (10781 ms)

And win7-64-glibc-opt gives:
WARNING: should have taken less than 2.000000 secs
[       OK ] nacl_glibc.run_service_runtime_tests (2203 ms)

BUG=http://code.google.com/p/nativeclient/issues/detail?id=895
TEST=none

Review URL: https://codereview.chromium.org/10986090

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@9876 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: 6e761629f18e98f4f1243878ca3b0c64e1a984ea