Revert "Indicate in the Window menu which Chrome window has an active sound playing"
The patch broke compilation on Mac with SDK 10.11.
In file included from ../../chrome/browser/ui/cocoa/browser_window_cocoa_unittest.mm:13:
In file included from ../../chrome/browser/ui/cocoa/cocoa_profile_test.h:9:
In file included from ../../chrome/browser/ui/cocoa/cocoa_test_helper.h:10:
In file included from ../../ui/gfx/test/ui_cocoa_test_helper.h:14:
In file included from ../../testing/platform_test.h:8:
../../testing/gtest/include/gtest/gtest.h:1392:16: error: comparison of integers of different signs: 'const unsigned long' and 'const long' [-Werror,-Wsign-compare]
  if (expected == actual) {
      ~~~~~~~~ ^  ~~~~~~
../../testing/gtest/include/gtest/gtest.h:1422:12: note: in instantiation of function template specialization 'testing::internal::CmpHelperEQ<unsigned long, long>' requested here
    return CmpHelperEQ(expected_expression, actual_expression, expected,
           ^
../../chrome/browser/ui/cocoa/browser_window_cocoa_unittest.mm:60:3: note: in instantiation of function template specialization 'testing::internal::EqHelper<false>::Compare<unsigned long, long>' requested here
  EXPECT_EQ([bwc->WindowTitle() rangeOfString:playing_emoji].location,
  ^

The constant NSNotFound is declared differently
10.10: enum {NSNotFound = NSIntegerMax};
10.11: static const NSInteger NSNotFound = NSIntegerMax;

This reverts commit 6b29707b2333711fb1b2b99bdb739d3cb755b3d3 [formerly 70d337daa152a75db530fa04214caba48ff39bd6].

R=shahriar.rostami@gmail.com
TBR=rsesek@chromium.org,miu@chromium.org

Review URL: https://codereview.chromium.org/1412803012

Cr-Commit-Position: refs/heads/master@{#358331}

Former-commit-id: 00c4dceedd23e6a98df0e7104e28f3ba257208da