Revert of Upgrade the windows specific version of LaunchProcess to avoid raw handles. (patchset #3 id:40001 of https://codereview.chromium.org/759903002/)
Reason for revert:
Looks like it broke the 'Google Chrome Win' builder:

FAILED: ninja -t msvc -e environment.x86 -- c:\b\build\goma/gomacc "c:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\win8\delegate_execute\delegate_execute.chrome_util.obj.rsp /c ..\..\win8\delegate_execute\chrome_util.cc /Foobj\win8\delegate_execute\delegate_execute.chrome_util.obj /Fdobj\win8\delegate_execute\delegate_execute.cc.pdb
c:\b\build\slave\google-chrome-rel-win\build\src\win8\delegate_execute\chrome_util.cc(119) : error C2665: 'base::LaunchProcess' : none of the 3 overloads could convert all the argument types
        c:\b\build\slave\google-chrome-rel-win\build\src\base\process\launch.h(161): could be 'bool base::LaunchProcess(const base::CommandLine &,const base::LaunchOptions &,base::ProcessHandle *)'
        while trying to match the argument list '(base::string16, base::LaunchOptions, base::win::ScopedHandle *)'

Original issue's description:
> Upgrade the windows specific version of LaunchProcess to avoid raw handles.
>
> This change implies that extensions::LaunchNativeProcess also changes to
> return base::Process, and that requires base::EnsureProcessTerminated to
> deal with base:Process (as it basically claims ownership of the process).
>
> This CL fixes some leaks all around.
>
> BUG=417532
>
> Committed: https://crrev.com/1fe5e60aba8b17615dc41e0c1746a56e490ee43b [formerly 6b687a5e232c80539772dc3dbe35b98095064c38]
> Cr-Commit-Position: refs/heads/master@{#306687}

TBR=cpu@chromium.org,finnur@chromium.org,gab@chromium.org,sergeyu@chromium.org,wez@chromium.org,rvargas@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=417532

Review URL: https://codereview.chromium.org/780653003

Cr-Commit-Position: refs/heads/master@{#306712}

Former-commit-id: 44b0c750ff6588cc893766ea74d3ff0203d46d75