Fix compilation on Chromium OS after r171165
r171165 broke compilation on Chromium OS bot and we had to revert Blink roll.
...
../../../../../../../home/chrome-bot/chrome_root/src/third_party/WebKit/Source/core/dom/CharacterData.cpp:146:36:
error: 'realCount' may be used uninitialized in this function
...
I simply added initialization for realCount variables to make the compiler happy.

[1] http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20%28x86%29/builds/20955

BUG=349898
TBR=sigbjornf@opera.com

Review URL: https://codereview.chromium.org/232243004

git-svn-id: svn://svn.chromium.org/blink/trunk@171240 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: 8a7c36291c7abbd088544fa4e2b67b4b3854d07a