Reland of Move about half of the clang/win bots to gn. (patchset #1 id:1 of https://codereview.chromium.org/1963433002/ )
Reason for revert:
32-bit official builds should be fixed now (see https://crbug.com/610445)

Original issue's description:
> Revert of Move about half of the clang/win bots to gn. (patchset #1 id:1 of https://codereview.chromium.org/1954313002/ )
>
> Reason for revert:
> 32-bit official builds are still busted (probably without clang too?):
> https://build.chromium.org/p/chromium.fyi/builders/CrWinClang/builds/8540/steps/compile/logs/stdio
>
> [40909/44073] ACTION //remoting/host:remoting_me2me_host_archive(//build/toolchain/win:clang_x86)
> FAILED: remoting-me2me-host-win.zip
> C:/b/depot_tools/python276_bin/python.exe ../../remoting/host/installer/build-installer-archive.py gen/installation remoting-me2me-host-win.zip --source-file-roots C:/b/build/slave/CrWinClang/build/src/remoting/host/installer/win --source-files C:/b/build/slave/CrWinClang/build/src/remoting/host/installer/win/chromoting.wxs C:/b/build/slave/CrWinClang/build/src/remoting/host/installer/win/parameters.json --generated-files remote_assistance_host.exe remote_security_key.exe remoting_core.dll remoting_desktop.exe remoting_host.exe remoting_native_messaging_host.exe remoting_start_host.exe gen/remoting/CREDITS.txt remoting/com.google.chrome.remote_assistance.json remoting/com.google.chrome.remote_desktop.json icudtl.dat ../../third_party/platformsdk_win7/files/Redist/x64/sas.dll C:/b/build/slave/CrWinClang/build/src/remoting/resources/chromoting.ico --generated-files-dst files/remote_assistance_host.exe files/remote_security_key.exe files/remoting_core.dll files/remoting_desktop.exe files/remoting_host.exe files/remoting_native_messaging_host.exe files/remoting_start_host.exe files/CREDITS.txt files/com.google.chrome.remote_assistance.json files/com.google.chrome.remote_desktop.json files/chromoting.ico files/icudtl.dat files/sas.dll --defs BRANDING=Chrome DAEMON_CONTROLLER_CLSID=b468ac72-d6a4-5f59-8dc7-ed91ba4d797b RDP_DESKTOP_SESSION_CLSID=c4868da5-d777-5d42-9ab1-4cdc952c942d VERSION=52.0.2727.0 OFFICIAL_BUILD=1
> Traceback (most recent call last):
>
>   File "../../remoting/host/installer/build-installer-archive.py", line 292, in <module>
>
>     sys.exit(main())
>
>   File "../../remoting/host/installer/build-installer-archive.py", line 286, in main
>
>     defs)
>
>   File "../../remoting/host/installer/build-installer-archive.py", line 207, in buildHostArchive
>
>     shutil.copy2(bs, dst_file)
>
>   File "C:\b\depot_tools\python276_bin\lib\shutil.py", line 130, in copy2
>
>     copyfile(src, dst)
>
>   File "C:\b\depot_tools\python276_bin\lib\shutil.py", line 82, in copyfile
>
>     with open(src, 'rb') as fsrc:
>
> IOError: [Errno 2] No such file or directory: '../../third_party/platformsdk_win7/files/Redist/x64/sas.dll'
>
> Original issue's description:
> > Reland of Move about half of the clang/win bots to gn. (patchset #1 id:1 of https://codereview.chromium.org/1948303003/ )
> >
> > Reason for revert:
> > 32-bit clang/win/gn builds might work now.
> >
> > Original issue's description:
> > > Revert of Move about half of the clang/win bots to gn. (patchset #1 id:1 of https://codereview.chromium.org/1947183004/ )
> > >
> > > Reason for revert:
> > > 32-bit builds fail like so:
> > > obj/chrome/installer/mini_installer/lib/chrome_appid.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'
> > >
> > > (The 64-bit bots look fine though.)
> > >
> > > Original issue's description:
> > > > Move about half of the clang/win bots to gn.
> > > >
> > > > The CrWinClang64(dbg) bot already is on gn.  After this change, the
> > > > following bots will be on gn:
> > > >
> > > > Pinned:
> > > > CrWinClang
> > > > CrWinClang(shared)
> > > > CrWinClang64(dbg)  (already on gn)
> > > >
> > > > ToT:
> > > > ClangToTWin(dll)
> > > > ClangToTWin64
> > > > ClangToTWin64(dll)
> > > >
> > > > These complement each other, so that each of
> > > > - 32-bit release static official
> > > > - 32-bit release shared
> > > > - 32-bit debug shared
> > > > - 64-bit release static official
> > > > - 64-bit release shared
> > > > - 64-bit debug shared
> > > > has one gyp and one gn bot (one a ToT bot, the other a pinned bot,
> > > > respectively).
> > > >
> > > > I'll also switch one of the ASan bots, but that's for a separate CL.
> > > >
> > > > Hopefully, no behavior change.
> > > >
> > > > BUG=498033
> > > > R=dpranke@chromium.org
> > > >
> > > > Committed: https://chromium.googlesource.com/chromium/src/+/8ab2cc4e27cea3af76414059f3367b9fa2e32d41 [formerly dafacdab8ad432c98028eff432c09360f28254fe]
> > >
> > > TBR=dpranke@chromium.org
> > > # Skipping CQ checks because original CL landed less than 1 days ago.
> > > NOPRESUBMIT=true
> > > NOTREECHECKS=true
> > > NOTRY=true
> > > BUG=498033
> > >
> > > Committed: https://crrev.com/a08211c3f1ae5ae2b79a444682ed4bede0c5e1e0 [formerly 0adf70552c219667ddf4df38752173f8d5dc801b]
> > > Cr-Commit-Position: refs/heads/master@{#391976}
> >
> > TBR=dpranke@chromium.org
> > # Skipping CQ checks because original CL landed less than 1 days ago.
> > NOPRESUBMIT=true
> > NOTREECHECKS=true
> > NOTRY=true
> > BUG=498033
> >
> > Committed: https://crrev.com/d4c15afd306849eca17099bbff1b427a564d8b2e [formerly 210c20eff22bee39130d425fed027e71c1a35020]
> > Cr-Commit-Position: refs/heads/master@{#392179}
>
> TBR=dpranke@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=498033
>
> Committed: https://crrev.com/308671dd2e98092f167c1809179aef387e6b81c4 [formerly db5fc4091985d801c3ff271a10fa59518ca47459]
> Cr-Commit-Position: refs/heads/master@{#392257}

TBR=dpranke@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=498033

Review-Url: https://codereview.chromium.org/1964683002
Cr-Commit-Position: refs/heads/master@{#392481}

Former-commit-id: 5c8fa80c8e451afa2f02bc074de79d6a52d38cc2