Revert "[TLS]: Add native tls perftests"
This reverts commit 255167e24bbe2edc9bcd3a28c3e5cd1e457df095 [formerly 79759021758ad309809a4603772430bb721edfd2].

Reason for revert: causes compile failure on win32-archive-rel
https://ci.chromium.org/p/chromium/builders/ci/win32-archive-rel/1248

../../base/threading/thread_local_storage_perftest.cc(152,15): error: no matching function for call to 'FlsAlloc'
  DWORD key = FlsAlloc([](void*) {});
              ^~~~~~~~

Original change's description:
> [TLS]: Add native tls perftests
> 
> Change-Id: I08289ef9d8e1cb665393823495e292a9cbc236c1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1645220
> Reviewed-by: François Doray <fdoray@chromium.org>
> Commit-Queue: François Doray <fdoray@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#667051}

TBR=fdoray@chromium.org,etiennep@chromium.org

Change-Id: I83d07562c74d69a4585101c4a1649e7da1891b0d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1647267
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#667058}

Former-commit-id: d39a510a1915cbef8081c18a3bd1519d593fe686