Remove variable shadowing in blink/modules/indexeddb and webdatabase
In an effort to reduce (any possibly ban) shadowed variables in blink, this
renames a couple of variables in modules/indexeddb so that there is no
variable shadowing.

I'm interested in turning on the shadowing warning because I think it might
prevent potential jumbo build problems.

This patch fixes these shadowing warnings:
third_party/blink/renderer/modules/indexeddb/idb_database.cc:201:12: error: declaration shadows a local variable [-Werror,-Wshadow]
      auto it = transactions.find(map_entry.first);
           ^
third_party/blink/renderer/modules/indexeddb/idb_database.cc:196:10: note: previous declaration is here
    auto it = observers_.find(map_entry.first);
         ^
third_party/blink/renderer/modules/indexeddb/inspector_indexed_db_agent.cc:490:11: error: declaration shadows a local variable [-Werror,-Wshadow]
    auto* array = key->getArray(nullptr);
          ^
third_party/blink/renderer/modules/indexeddb/inspector_indexed_db_agent.cc:474:31: note: previous declaration is here
  DEFINE_STATIC_LOCAL(String, array, ("array"));
                              ^
third_party/blink/renderer/modules/webdatabase/database.cc:845:38: error: declaration shadows a local variable [-Werror,-Wshadow]
    SQLTransaction::OnErrorCallback* callback =
                                     ^
third_party/blink/renderer/modules/webdatabase/database.cc:824:40: note: previous declaration is here
    SQLTransaction::OnProcessCallback* callback,
                                       ^
3 errors generated.

Bug: 925310
Change-Id: I5912a18ce0bbfe8bfd15a69110aa396ef216b7d8
Reviewed-on: https://chromium-review.googlesource.com/c/1477051
Commit-Queue: Kentaro Hara <haraken@chromium.org>
Auto-Submit: Daniel Bratell <bratell@opera.com>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Cr-Commit-Position: refs/heads/master@{#633128}
Former-commit-id: a23f8569a5b5563676462f3f4280ff935ec06b1e