rename Windows BrowserAccessibilityTest to BrowserAccessibilityWinTest
This avoids a conflict with the class BrowserAccessibilityTest defined in
content/browser/accessibility/browser_accessibility_unittest.cc. The
conflict caused ThinLTO builds to fail with lld-link: error:
duplicate symbol: "public: __cdecl

(??0BrowserAccessibilityTest@content@@QEAA@XZ) in
obj/content/test/content_unittests/browser_accessibility_unittest.obj
and in
obj/content/test/content_unittests/browser_accessibility_win_unittest.obj

content: :BrowserAccessibilityTest::BrowserAccessibilityTest(void)"
Change-Id: Ib0032953ee56419583b5fa55da68a2df3de039dd
Reviewed-on: https://chromium-review.googlesource.com/c/1416819
Commit-Queue: Bob Haarman <inglorion@chromium.org>
Reviewed-by: Dominic Mazzoni <dmazzoni@chromium.org>
Cr-Commit-Position: refs/heads/master@{#627571}
Former-commit-id: 2b6e5f95b66f55764626ab5b925b4acd66e033c5