Revert "Roll libyuv from 1703 to 1707"
This reverts commit f2d204b56754f80d62a381dd15bbd7cac462bbc7 [formerly de2fa0a4eeb9db3693451bed799fb7b5f60c4596].

Reason for revert: Builder ios-simulator-xcode-clang started failing in #45102 when this CL was landed.
See https://ci.chromium.org/buildbot/chromium.mac/ios-simulator-xcode-clang/?limit=100

For the error message see: https://logs.chromium.org/v/?s=chromium%2Fbb%2Fchromium.mac%2Fios-simulator-xcode-clang%2F45102%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

Error message snippet: 
408/3890] CXX obj/third_party/libyuv/libyuv_internal/row_gcc.o
FAILED: obj/third_party/libyuv/libyuv_internal/row_gcc.o 
/b/build/slave/cache/goma_client/gomacc clang++ -MMD -MF obj/third_party/libyuv/libyuv_internal/row_gcc.o.d -DV8_DEPRECATION_WARNINGS -DNO_TCMALLOC -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -DCR_XCODE_VERSION=0920 -DCR_CLANG_REVISION=\"328575-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -I../.. -Igen -I../../third_party/libyuv/include -ffp-contract=fast -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -fcolor-diagnostics -no-canonical-prefixes -arch x86_64 -Wall -Werror -Wextra -Wimplicit-fallthrough -Wthread-safety -Wunguarded-availability -Wundeclared-selector -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-address-of-packed-member -O0 -fno-omit-frame-pointer -gdwarf-2 -isysroot /b/build/slave/cache/xcode_ios_9c40b.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk -stdlib=libc++ -mios-simulator-version-min=10.0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=c++14 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../third_party/libyuv/source/row_gcc.cc -o obj/third_party/libyuv/libyuv_internal/row_gcc.o
../../third_party/libyuv/source/row_gcc.cc:585:8: error: instruction requires: AVX-512 VBMI ISA AVX-512 VL ISA
      "vpermt2b   %%ymm1,%%ymm5,%%ymm0           \n"
       ^
<inline asm>:10:1: note: instantiated into assembly here
vpermt2b   %ymm1,%ymm5,%ymm0           
^
../../third_party/libyuv/source/row_gcc.cc:586:8: error: instruction requires: AVX-512 VBMI ISA AVX-512 VL ISA
      "vpermt2b   %%ymm2,%%ymm6,%%ymm1           \n"
       ^
<inline asm>:11:1: note: instantiated into assembly here
vpermt2b   %ymm2,%ymm6,%ymm1           
^
../../third_party/libyuv/source/row_gcc.cc:587:8: error: instruction requires: AVX-512 VBMI ISA AVX-512 VL ISA
      "vpermt2b   %%ymm3,%%ymm7,%%ymm2           \n"
       ^
<inline asm>:12:1: note: instantiated into assembly here
vpermt2b   %ymm3,%ymm7,%ymm2           
^
3 errors generated.


Original change's description:
> Roll libyuv from 1703 to 1707
> 
> Contains the following changes:
> 4ad3334 Pass float parameters via vector 2 float and "w" for scalar multiply. by Frank Barchard
> d868089 Fix building with clang targeting x86_32 mingw by Martin Storsjö
> 548ec65 Require clang 6 for AVX512 support by Frank Barchard
> c21af29 jpeg remove empty function declarations by Frank Barchard
> fdad629 Add a method to force the CPU flags by Jay Civelli
> 6ecd76a Make libyuv use the hermetic xcode toolchain. by Patrik Höglund
> 9d70f13 cpuid sandbox friendlier avoiding getenv() by Frank Barchard
> 83aa751 AVX512 VMBI version of ARGBToRGB24 by Frank Barchard
> 004954c cpu disables for AVX 512 and unittest show decimal by Frank Barchard
> 1d509f2 ARGBToRGB24_AVX2 version by Frank Barchard
> 3009890 NV21ToRGB24_AVX2 and SSSE3 by Frank Barchard
> 
> Change-Id: I90cbce98ba91ebe5eb477ad9df0640f5a1bb4994
> Reviewed-on: https://chromium-review.googlesource.com/980744
> Commit-Queue: Jay Civelli <jcivelli@chromium.org>
> Reviewed-by: Frank Barchard <fbarchard@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#546676}

TBR=jcivelli@chromium.org,fbarchard@chromium.org

Change-Id: I67f918f83ec1f23f23f4c9dfd6a06d47a88ae48c
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/985872
Reviewed-by: Markus Heintz <markusheintz@chromium.org>
Commit-Queue: Markus Heintz <markusheintz@chromium.org>
Cr-Commit-Position: refs/heads/master@{#546770}
Former-commit-id: 549a2a4d996352f2c5e89179a295906be36943c7