Revert of Add --root-layer-scrolls. (patchset #2 id:20001 of https://codereview.chromium.org/662973003/)
Reason for revert:
This CL causes build failure:
http://build.chromium.org/p/chromium.chromiumos/buildstatus?builder=Linux%20ChromiumOS%20Builder%20%28dbg%29&number=54070

The error log is:
FAILED: /b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ (snip) -o interactive_ui_tests (snip)
obj/chrome/libbrowser_chromeos.a(obj/chrome/browser/chromeos/login/browser_chromeos.chrome_restart_request.o):../../chrome/browser/chromeos/login/chrome_restart_request.cc:chromeos::(anonymous namespace)::DeriveCommandLine(GURL const&, base::CommandLine const&, base::DictionaryValue const&, base::CommandLine*)::kForwardSwitches:error: undefined reference to 'switches::kRootLayerScrolls'
clang:error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

Original issue's description:
> Add --root-layer-scrolls.
>
> BUG=417782
>
> Committed: https://crrev.com/b92c91b596fe397012c0d92f63b9ef8927b3a598 [formerly 2eeec6853a1579d09754acfa9961e4dc36aa9264]
> Cr-Commit-Position: refs/heads/master@{#302588}

TBR=vollick@chromium.org,jam@chromium.org,skobes@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=417782

Review URL: https://codereview.chromium.org/695613005

Cr-Commit-Position: refs/heads/master@{#302590}

Former-commit-id: bbde2c9904670963be708bc62efdb1f90b0444f4