[cros_chrome_sdk]: Also catch GSCommandError.
Storage access errors manifest as GSCommandError, for eg:
chromite.lib.gs.GSCommandError: return code: 1; command: /usr/local/google/home/achuith/code/chrome/.cros_cache/common/gsutil_4.27.tar.gz/gsutil/gsutil -o 'Boto:num_retries=10' cat gs://chromeos-image-archive/amd64-generic-full/LATEST-10426.0.0
ServiceException: 401 Anonymous caller does not have storage.objects.get access to chromeos-image-archive/amd64-generic-full/LATEST-10426.0.0.

BUG=chromium:774599
TEST=manual

Change-Id: Iac7cae782fcb4cfe23bf3e64881440265206f39c
Reviewed-on: https://chromium-review.googlesource.com/933004
Commit-Ready: Achuith Bhandarkar <achuith@chromium.org>
Tested-by: Achuith Bhandarkar <achuith@chromium.org>
Reviewed-by: Steven Bennetts <stevenjb@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>