Revert 233297 "Fix windowed NPAPI plugins covering up dialogs on..."
Error Log:
[ RUN      ] PrintPreviewTest.WindowedNPAPIPluginHidden
[3852:2708:1106/120416:ERROR:dxva_video_decode_accelerator.cc(421)] Direct3DCreate9Ex failed, HRESULT: 0x8876086a
[3852:2708:1106/120416:ERROR:dxva_video_decode_accelerator.cc(398)] Failed to initialize D3D device and manager
[2672:2864:1106/120416:2596964:ERROR:chrome_views_delegate.cc(172)] NOT IMPLEMENTED
[2672:2864:1106/120416:2596964:ERROR:desktop_root_window_host_win.cc(688)] NOT IMPLEMENTED
[2672:3764:1106/120417:2597915:ERROR:gpu_message_filter.cc(189)] Renderer 3 tried to access a surface for renderer 0
[2672:3764:1106/120417:2597931:ERROR:gpu_message_filter.cc(189)] Renderer 3 tried to access a surface for renderer 0
[2672:3764:1106/120417:2597931:ERROR:gpu_message_filter.cc(189)] Renderer 3 tried to access a surface for renderer 0
[2672:3764:1106/120417:2597931:ERROR:gpu_message_filter.cc(189)] Renderer 3 tried to access a surface for renderer 0
[2904:3556:1106/120418:VERBOSE2:ipc_channel_win.cc(85)] sending message @0B515550 on channel @0B550EA8 with type 262228 (0 in queue)
[2904:3556:1106/120418:VERBOSE2:ipc_channel_win.cc(409)] sent message @0B515550 on channel @0B550EA8 with type 262228
[2672:2864:1106/120418:2598820:ERROR:chrome_views_delegate.cc(172)] NOT IMPLEMENTED
[2672:3764:1106/120418:2599273:ERROR:gpu_message_filter.cc(189)] Renderer 6 tried to access a surface for renderer 0
[2672:3764:1106/120419:2599351:ERROR:gpu_message_filter.cc(189)] Renderer 6 tried to access a surface for renderer 0
[2672:3764:1106/120419:2599366:ERROR:gpu_message_filter.cc(189)] Renderer 6 tried to access a surface for renderer 0
[2672:3764:1106/120419:2599366:ERROR:gpu_message_filter.cc(189)] Renderer 6 tried to access a surface for renderer 0
browser\ui\webui\print_preview\print_preview_ui_browsertest.cc(124): error: Value of: 2
Expected: result
Which is: 1
[  FAILED  ] PrintPreviewTest.WindowedNPAPIPluginHidden, where TypeParam =  and GetParam() =  (4804 ms)
[632/632] PrintPreviewTest.WindowedNPAPIPluginHidden (5614 ms)

> Fix windowed NPAPI plugins covering up dialogs on Win Aura.
> 
> The original fix stopped working with the new style of dialogs, since they're not parented to the WebContents anymore but instead to its parent. It also turns out we don't need to watch out for transient windows, as they're now top level ones with their own HWND so clipping works through the OS and we don't need to do anything special.
> 
> BUG=299224
> R=ben@chromium.org
> 
> Review URL: https://codereview.chromium.org/53153003

TBR=jam@chromium.org

Review URL: https://codereview.chromium.org/63013002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@233333 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 006f475cbc01a5e51f4bfcede9a87b732709ae62