Revert of Revert "[wrapper-tracing] Bail out tracing for empty handles" (patchset #1 id:1 of https://codereview.chromium.org/2840013003/ )
Reason for revert:
This revert breaks compile:

../../third_party/WebKit/Source/bindings/core/v8/ScriptWrappableVisitor.cpp:262:8: error: use of undeclared identifier 'm_tracingInProgress'; did you mean 'tracing_in_progress_'?
  if (!m_tracingInProgress)
       ^~~~~~~~~~~~~~~~~~~
       tracing_in_progress_
../../third_party/WebKit/Source/bindings/core/v8/ScriptWrappableVisitor.h:194:8: note: 'tracing_in_progress_' declared here
  bool tracing_in_progress_ = false;
       ^
1 error generated.

Original issue's description:
> Revert "[wrapper-tracing] Bail out tracing for empty handles"
>
> This reverts commit 2c49e9285fd6191f999121b346c0f507d812301e [formerly fc1c3f831aeceee5e63501e8c700003fc1802b2b].
>
> TBR=mlippautz@chrommium.org
> NOTRY=true
>
> Review-Url: https://codereview.chromium.org/2840013003
> Cr-Commit-Position: refs/heads/master@{#467214}
> Committed: https://chromium.googlesource.com/chromium/src/+/c893d391de27c88e2e5b992bd88dd0456d0c0273 [formerly 79f22e60f857a83a592216c33a47035268c2cda7]

TBR=haraken@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review-Url: https://codereview.chromium.org/2839023004
Cr-Commit-Position: refs/heads/master@{#467218}

Former-commit-id: 84d4dfb32ea85d528373295087f10d0766d556b6