Revert 263216 "Remove the assertion decode time > 0 from the test."
Broke ChromiumOS (amd64) Build:
http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20%28amd64%29/builds/15406

chromeos-chrome-36.0.1936.0_alpha-r1: FAILED: x86_64-cros-linux-gnu-g++ -B/usr/x86_64-pc-linux-gnu/x86_64-cros-linux-gnu/binutils-bin/2.22-gold -MMD -MF obj/content/common/gpu/media/video_decode_accelerator_unittest.video_decode_accelerator_unittest.o.d [...]
chromeos-chrome-36.0.1936.0_alpha-r1: ../../../../../../../home/chrome-bot/chrome_root/src/content/common/gpu/media/video_decode_accelerator_unittest.cc: In member function 'virtual void content::{anonymous}::VideoDecodeAcceleratorTest_TestDecodeTimeMedian_Test::TestBody()':
chromeos-chrome-36.0.1936.0_alpha-r1: ../../../../../../../home/chrome-bot/chrome_root/src/content/common/gpu/media/video_decode_accelerator_unittest.cc:1514:73: error: format '%lld' expects argument of type 'long long int', but argument 2 has type 'int64 {aka long int}' [-Werror=format=]
chromeos-chrome-36.0.1936.0_alpha-r1:        "Decode time median: %lld us", decode_time_median.InMicroseconds());

> Remove the assertion decode time > 0 from the test.
> 
> The decode time per frame can be less than 1 millisecond and
> TimeDelta::InMilliseconds will round it to 0. Remove the
> assertion to fix it. Also change the unit to microseconds.
> 
> BUG=358983
> TEST=Run the test on CrOS.
> 
> Review URL: https://codereview.chromium.org/230553002

TBR=wuchengli@chromium.org

Review URL: https://codereview.chromium.org/234603005

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@263245 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 7a3093d85ebf48a90848be175d6a12fca9ccc78d