BUILD FIX (r39641): Fix more silly errors
        Fixes the following compilation errors:

            WebIconDatabase.cpp
            ..\WebIconDatabase.cpp(85) : error C2065: 'standardPrefs' : undeclared identifier
            ..\WebIconDatabase.cpp(85) : error C2227: left of '->iconDatabaseLocation' must point to class/struct/union/generic type
                    type is ''unknown-type''
            ..\WebIconDatabase.cpp(241) : error C2575: 'isEnabled' : only member functions and bases can be virtual
            ..\WebIconDatabase.cpp(248) : error C2575: 'setEnabled' : only member functions and bases can be virtual
            ..\WebIconDatabase.cpp(253) : error C3861: 'shutDownIconDatabase': identifier not found
            ..\WebIconDatabase.cpp(256) : error C3861: 'startUpIconDatabase': identifier not found

        * WebIconDatabase.cpp:
        (WebIconDatabase::startUpIconDatabase): Redeclare standardPrefs
        since this was in init() but not in this method after it was
        extracted from init().
        (isEnabled): Don't use "virtual" in method implementation
        (silly copy-paste error).
        (setEnabled): Ditto.

git-svn-id: svn://svn.chromium.org/blink/trunk@39645 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: e54318068f14e4c1812c0a9f3c7e08fe7afafafd