Revert r7913: "Build as PIE in Gyp build."
The change broke the build of NaCl-in-Chromium, and caused the linking
of libppGoogleNaClPluginChrome.so on Linux to fail with:
  error: undefined reference to 'main'

That happens because plugin.gypi in the Chromium tree still imports
native_client/build/common.gypi and "-pie" was overriding "-shared".

To fix this, we could move "-pie" to sel_ldr's ldflags rather than
trying to make "-pie" a global setting.  For comparison, Chromium's
Gyp build adds "-pie" on a target-by-target basis.

I'm erring on the side of reverting because r7913 also broke the
linking of sel_ldr on my machine (using the locally installed gold
linker), which reduces the usefulness of the Gyp build.

BUG=http://code.google.com/p/nativeclient/issues/detail?id=2622
TEST=none

Review URL: https://chromiumcodereview.appspot.com/9564015

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@7919 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: a09e5ffec6652205ea0325bef3af2a5f6c207d8f