Fix -Wreturn-stack-address in ble_scanner_impl_unittest.cc
  ../../chromeos/services/secure_channel/ble_scanner_impl_unittest.cc:231:12:
  error: address of stack memory associated with local variable
  'fake_bluetooth_device' returned [-Werror,-Wreturn-stack-address]
      return fake_bluetooth_device.get();
             ^~~~~~~~~~~~~~~~~~~~~

I guess the test worked before because it didn't actually dereference the
pointer.

Bug: 992458
Change-Id: I82f189588644a63de1a9f16dbf158dfcdca5e5a9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1751789
Reviewed-by: Nico Weber <thakis@chromium.org>
Reviewed-by: Kyle Horimoto <khorimoto@chromium.org>
Commit-Queue: Nico Weber <thakis@chromium.org>
Cr-Commit-Position: refs/heads/master@{#686465}

Former-commit-id: 222f728c673a177e3eca932383c30b0acacd797e