//extensions:test_support depends on //chrome/common:buildflags
extensions:test_support source has extensions/browser/api/storage/settings_test_util.cc (ie. CXX obj/extensions/test_support/settings_test_util.obj).
extensions/browser/api/storage/settings_test_util.cc includes extensions/browser/api/storage/settings_test_util.h.
extensions/browser/api/storage/settings_test_util.h includes chrome/test/base/testing_profile.h.
chrome/test/base/testing_profile.h includes chrome/common/buildflags.h.
(storage_api_unittest.cc, and storage_frontend_unittest.cc also have the same deps)

Sample fail build: https://ci.chromium.org/p/chromium/builders/ci/win32-archive-rel/4213

Sample log: https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8904106168657270320/+/steps/compile/0/stdout?format=raw
---
[75418/84070] CXX obj/extensions/test_support/settings_test_util.obj
In file included from ../../extensions/browser/api/storage/settings_test_util.cc:5:
In file included from ../..\extensions/browser/api/storage/settings_test_util.h:14:
../..\chrome/test/base/testing_profile.h(19,10): fatal error: 'chrome/common/buildflags.h' file not found
#include "chrome/common/buildflags.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
---

FAILED: obj/extensions/test_support/settings_test_util.obj
Change-Id: If33bda93909d81fdaed1cdd4d6571e454784ccd8
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1768853
Reviewed-by: Ken Rockot <rockot@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#690670}

Former-commit-id: 852d725c0aa2c7086f7b4d58edce4a5adfe8b824