Revert 127471 - Rename ibus_input_methods.txt to input_methods.txt.
Build failure:
chrome/browser/chromeos/input_method/input_method_util.cc:18:69: error: chrome/browser/chromeos/input_method/ibus_input_methods.h: No such file or directory

The prefix "ibus_" is no longer relevant because IBus is not used anymore for a keyboard whose ID starts with "xkb:". Another reason to avoid the prefix is that we're likely going to reimplement some of the input methods as Chrome extensions.

BUG=chromium-os:19655
TEST=try

Review URL: https://chromiumcodereview.appspot.com/9721017

TBR=yusukes@google.com
Review URL: https://chromiumcodereview.appspot.com/9724037

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@127478 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: b2819ba4314aa2e97cf877c3034ccd1cef5eb855