Revert of Host fingerprint mojo service within the device service. (patchset #20 id:400001 of https://codereview.chromium.org/2664353002/ )
Reason for revert:
Causing build failure in Linux ChromiumOS Builder (dbg)
https://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Builder%20%28dbg%29/builds/83944/steps/compile/logs/stdio

[5011/6465] LINK ./service_unittests
FAILED: service_unittests
../../third_party/llvm-build/Release+Asserts/bin/clang++ -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -lpthread -Wl,--as-needed -fuse-ld=gold -B../../third_party/binutils/Linux_x64/Release/bin -Wl,--threads -Wl,--thread-count=4 -Wl,--icf=all -m64 -pthread -Werror --sysroot=../../build/linux/ubuntu_precise_amd64-sysroot -L/b/c/b/linux_chromeos/src/build/linux/ubuntu_precise_amd64-sysroot/lib/x86_64-linux-gnu -Wl,-rpath-link=/b/c/b/linux_chromeos/src/build/linux/ubuntu_precise_amd64-sysroot/lib/x86_64-linux-gnu -L/b/c/b/linux_chromeos/src/build/linux/ubuntu_precise_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath-link=/b/c/b/linux_chromeos/src/build/linux/ubuntu_precise_amd64-sysroot/usr/lib/x86_64-linux-gnu -L/b/c/b/linux_chromeos/src/build/linux/ubuntu_precise_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.6 -Wl,-rpath-link=/b/c/b/linux_chromeos/src/build/linux/ubuntu_precise_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.6 -L/b/c/b/linux_chromeos/src/build/linux/ubuntu_precise_amd64-sysroot/usr/lib -Wl,-rpath-link=/b/c/b/linux_chromeos/src/build/linux/ubuntu_precise_amd64-sysroot/usr/lib -Wl,-rpath-link=. -Wl,--disable-new-dtags -Wl,-rpath=\$ORIGIN/. -Wl,-rpath-link=. -Wl,--export-dynamic -o "./service_unittests" -Wl,--start-group @"./service_unittests.rsp" ./libbase.so ./libbase_i18n.so ./libicui18n.so ./libicuuc.so ./libbindings.so ./libmojo_public_system_cpp.so ./libmojo_public_system.so ./libipc.so ./liburl.so ./libfingerprint.so ./libskia.so ./libcontent.so ./libgpu.so ./libgles2_utils.so ./libgfx.so ./libgeometry.so ./librange.so ./libgl_wrapper.so ./libplatform.so ./libgl_init.so ./libui_base.so ./libui_data_pack.so ./libevents_base.so ./libkeycodes_x11.so ./libui_base_x.so ./libnet.so ./libprotobuf_lite.so ./libcrcrypto.so ./libboringssl.so ./libmedia.so ./libshared_memory_support.so ./libmojo_common_lib.so ./libgfx_ipc.so ./libgfx_ipc_geometry.so ./libgfx_ipc_skia.so ./libcapture_base.so ./libgfx_ipc_color.so ./libcc.so ./libui_base_ime.so ./libdisplay.so ./libdisplay_types.so ./libcapture_lib.so ./libcc_ipc.so ./libcc_surfaces.so ./libaccessibility.so ./libsurface.so ./liburl_ipc.so ./libmojo_system_impl.so ./libstorage_common.so ./libstorage_browser.so ./libgin.so ./libv8.so ./libblink_platform.so ./libcc_animation.so ./libcc_paint.so ./libgles2_c_lib.so ./libwtf.so ./libblink_web.so ./libsandbox_services.so ./libsuid_sandbox_client.so ./libseccomp_bpf.so ./libstartup_tracing.so -Wl,--end-group  -ldl -lrt -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lnss3 -lnssutil3 -lsmime3 -lplds4 -lplc4 -lnspr4 -lfontconfig
../../services/device/fingerprint/fingerprint_impl_chromeos_unittest.cc:58: error: undefined reference to 'device::FingerprintImplChromeOS::BiodBiometricClientRestarted()'
../../services/device/fingerprint/fingerprint_impl_chromeos_unittest.cc:61: error: undefined reference to 'device::FingerprintImplChromeOS::BiometricsScanEventReceived(unsigned int, bool)'
../../services/device/fingerprint/fingerprint_impl_chromeos_unittest.cc:66: error: undefined reference to 'device::FingerprintImplChromeOS::BiometricsAttemptEventReceived(unsigned int, std::__debug::vector<std::string, std::allocator<std::string> > const&)'
../../services/device/fingerprint/fingerprint_impl_chromeos_unittest.cc:69: error: undefined reference to 'device::FingerprintImplChromeOS::BiometricsFailureReceived()'
../../services/device/fingerprint/fingerprint_impl_chromeos_unittest.cc:52: error: undefined reference to 'device::FingerprintImplChromeOS::FingerprintImplChromeOS()'

Original issue's description:
> Host fingerprint mojo service within the device service.
> BUG=687393
>
>
> This service will get fingerprint information from biod through dbus and provide it to md-settings.
> Since biod APIs are not finalized yet, FingerprintImpl is created as a stub for now.
>
> Review-Url: https://codereview.chromium.org/2664353002
> Cr-Commit-Position: refs/heads/master@{#453458}
> Committed: https://chromium.googlesource.com/chromium/src/+/93fd7721ba068a34e95ef26091e2ab50d29e199b [formerly a84f21653890b621907da8446a217875d2bf51c1]

TBR=tsepez@chromium.org,rockot@chromium.org,blundell@chromium.org,rkc@chromium.org,stevenjb@chromium.org,steel@chromium.org,xiaoyinh@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=687393

Review-Url: https://codereview.chromium.org/2719833005
Cr-Commit-Position: refs/heads/master@{#453481}

Former-commit-id: c850f7a8cb92c40277c4343c03ce2c06be356be8