[Android WebAPK] Fix LaunchTests bug due to sdk-version change
This CL adds FLAG_ACTIVITY_NEW_TASK to make the 'relaunch intent' sent
in runActivityChain() better match
WebappLauncherActivity#createRelaunchWebApkIntent()

This fixes the following exception caused by the sdk-version change
in https://chromium-review.googlesource.com/c/chromium/src/+/1650265
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:912)
	at android.app.ContextImpl.startActivity(ContextImpl.java:888)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
	at org.chromium.webapk.shell_apk.h2o.LaunchTest.runActivityChain(LaunchTest.java:393)

BUG=891996

Change-Id: I8e1b1aec282bb96286095c850b115e0c5e898063
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1657298
Reviewed-by: Tibor Goldschwendt <tiborg@chromium.org>
Commit-Queue: Peter Kotwicz <pkotwicz@chromium.org>
Cr-Commit-Position: refs/heads/master@{#668882}

Former-commit-id: b8ed6392b04972858d5219b7e041def5d7f9f4e9