Revert "Revert "ozone: set the right GBM_BO_ flags""
This reverts commit 1683a9aac2c230bf052099608573570f70d532e6 [formerly 752bf7505381af242ded2d8c01a54f31176fa1cf].

Reason for revert: Original CL was correct.

Original change's description:
> Revert "ozone: set the right GBM_BO_ flags"
> 
> This reverts commit e30f30df07658b44ead083190fc602e2cc2f75b0 [formerly 2e75e890f790868fdb72a4b1c26b6cb6f1e82042].
> 
> Reason for revert: Breaks build for veyron_minnie and probably other devices. Sample of the compiler errors below:
> 
> ../../ui/ozone/platform/drm/gpu/drm_thread.cc:120:15: error: use of undeclared identifier 'GBM_BO_USE_TEXTURING'; did you mean 'GBM_BO_USE_RENDERING'?
>       flags = GBM_BO_USE_TEXTURING;
>               ^~~~~~~~~~~~~~~~~~~~
>               GBM_BO_USE_RENDERING
> ../../../.cros_cache/chrome-sdk/tarballs/veyron_minnie+9588.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz/usr/include/gbm.h:230:4: note: 'GBM_BO_USE_RENDERING' declared here
>    GBM_BO_USE_RENDERING    = (1 << 2),
>    ^
> 
> 
> Original change's description:
> > ozone: set the right GBM_BO_ flags
> > 
> > minigbm doesn't allow to pass no flags to gbm_bo_create(). GBM_BO_USE_TEXTURING
> > implies texture, so use GBM_BO_USE_TEXTURING to create texture buffer.
> > 
> > GBM_BO_USE_TEXTURING implies GPU_READ. GBM_BO_USE_RENDERING implies GPU_WRITE.
> > BufferUsage::SCANOUT needs both of them because it implies GPU_READ_WRITE.
> > 
> > TEST=run chrome on amd64-generic
> > BUG=683347
> > 
> > Change-Id: I7431be6f5b4a8d95e6be11d86cfbf0c14b919668
> > Reviewed-on: https://chromium-review.googlesource.com/549095
> > Reviewed-by: Daniel Nicoara <dnicoara@chromium.org>
> > Reviewed-by: Daniele Castagna <dcastagna@chromium.org>
> > Reviewed-by: David Reveman <reveman@chromium.org>
> > Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>
> > Reviewed-by: Dongseong Hwang <dongseong.hwang@intel.com>
> > Commit-Queue: Dongseong Hwang <dongseong.hwang@intel.com>
> > Cr-Commit-Position: refs/heads/master@{#488709}
> 
> TBR=marcheu@chromium.org,reveman@chromium.org,dnicoara@chromium.org,dongseong.hwang@intel.com,glevin@chromium.org,dcastagna@chromium.org,gurchetansingh@chromium.org
> 
> Change-Id: I2a8327004c3ba78ca406d08b02b28515c2b2dcf0
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 683347
> Reviewed-on: https://chromium-review.googlesource.com/582347
> Reviewed-by: Kyle Horimoto <khorimoto@chromium.org>
> Commit-Queue: Kyle Horimoto <khorimoto@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#488762}

TBR=marcheu@chromium.org,reveman@chromium.org,khorimoto@chromium.org,dnicoara@chromium.org,dongseong.hwang@intel.com,glevin@chromium.org,dcastagna@chromium.org,gurchetansingh@chromium.org

Change-Id: I1b8d898a5184dfe17d8f33eda533a39400c78a44
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 683347
Reviewed-on: https://chromium-review.googlesource.com/582310
Reviewed-by: Kyle Horimoto <khorimoto@chromium.org>
Commit-Queue: Kyle Horimoto <khorimoto@chromium.org>
Cr-Commit-Position: refs/heads/master@{#488773}
Former-commit-id: 8a00f87cc094d59f08ca24be9ee6b5c484af70a6