cc: Fix jumbo build issue
After crrev.com/c/1696901, jumbo build fails with the following error:

In file included from gen/cc/cc_jumbo_4.cc:44:
./../../../cc/trees/frame_sequence_tracker.cc:35:15: error: non-static declaration of 'kMaxHistogramIndex' follows static declaration
constexpr int kMaxHistogramIndex = 2 * kBuiltinSequenceNum;
              ^
./../../../cc/scheduler/compositor_frame_reporter.cc:56:22: note: previous definition is here
static constexpr int kMaxHistogramIndex =
                     ^
1 error generated.

This CL fixes it by renaming that variable to avoid such
naming/definition conflict issues.

Bug: None
Change-Id: Id3f43061b814d95c51b52ed0b36971b64ac4dcbf
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1702522
Reviewed-by: kylechar <kylechar@chromium.org>
Commit-Queue: Nick Yamane <nickdiego@igalia.com>
Cr-Commit-Position: refs/heads/master@{#677480}

Former-commit-id: 7c471441748f8455d62e82cc33b3c6ef91a2fb36