Revert 213636 "Switch Chromium to use Blink's blink_resources.grd"
Broke the build with:
error: 'gen/webkit/webkit_chromium_resources.pak', needed by 'DumpRenderTree.pak', missing and no known rule to make it

> Switch Chromium to use Blink's blink_resources.grd
> 
> WebKit.grd is deprecated, so we update it public/blink_resources.grd.
> 
> R=darin@chromium.org, joth@chromium.org, thestig@chromium.org
> 
> Review URL: https://codereview.chromium.org/19537010

TBR=tfarina@chromium.org

Review URL: https://codereview.chromium.org/20341002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@213640 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 55dedd6828a7e13c63f9c29e579f4b4174ed4743