Revert of Send AXLayoutComplete even when document hasn't finished loading yet. (https://codereview.chromium.org/199693003/)
Reason for revert:
Causes content_browertests to fail:

[ RUN      ] DumpAccessibilityTreeTest.AccessibilityModalDialogInIframeOpened
Testing: E:\b\build\slave\Win7_Tests\build\src\content\test\data\accessibility\modal-dialog-in-iframe-opened.html
c:\b\build\slave\win-latest-rel\build\src\content\browser\accessibility\dump_accessibility_tree_browsertest.cc(209): error: Value of: is_different
  Actual: true
Expected: false
* Line Expected
- ---- --------
     1 ROLE_SYSTEM_DOCUMENT READONLY FOCUSABLE
     2     IA2_ROLE_SECTION READONLY
     3         ROLE_SYSTEM_STATICTEXT name='Test for modal dialog opened in an iframe. '
     4         ROLE_SYSTEM_CLIENT FOCUSABLE
     5             IA2_ROLE_SCROLL_PANE
     6                 ROLE_SYSTEM_DOCUMENT READONLY FOCUSABLE
     7                     ROLE_SYSTEM_DIALOG READONLY
     8                         ROLE_SYSTEM_STATICTEXT name='Text in the dialog.'
*    9                 ROLE_SYSTEM_SCROLLBAR
    10 <-- End-of-file -->

Actual
------
ROLE_SYSTEM_DOCUMENT READONLY FOCUSABLE
    IA2_ROLE_SECTION READONLY
        ROLE_SYSTEM_STATICTEXT name='Test for modal dialog opened in an iframe. '
        ROLE_SYSTEM_CLIENT FOCUSABLE
            IA2_ROLE_SCROLL_PANE
                ROLE_SYSTEM_DOCUMENT READONLY FOCUSABLE
                    ROLE_SYSTEM_DIALOG READONLY
                        ROLE_SYSTEM_STATICTEXT name='Text in the dialog.'

Original issue's description:
> Send AXLayoutComplete even when document hasn't finished loading yet.
> 
> Because these notifications only got sent if the corresponding AXObject
> already existed, they were effectively never sent before the first
> load complete notification. This change creates the AXObject for the
> document element after the first layout, allowing future notifications too.
> 
> BUG=353067
> 
> Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=170085

TBR=eseidel@chromium.org,esprehn@chromium.org,dmazzoni@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=353067

Review URL: https://codereview.chromium.org/213883003

git-svn-id: svn://svn.chromium.org/blink/trunk@170112 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: 57db04453ba580c14546954003abfb65a79ef5aa