Revert 163290 "Create gin::IsolateHolders for blink managed Isol..."
It broke Android build.
http://build.chromium.org/p/chromium.webkit/builders/Android%20Builder/builds/31041/steps/compile/logs/stdio

../../gin/modules/module_registry.cc: In member function 'void gin::ModuleRegistry::Load(v8::Isolate*, scoped_ptr<gin::PendingModule>)':
../../gin/modules/module_registry.cc:205:65:error: 'class std::vector<v8::Handle<v8::Value> >' has no member named 'data'

> Create gin::IsolateHolders for blink managed Isolates.
> 
> This also introduces a compile time dependency on gin. So far, we
> only used constants from public headers
> 
> BUG=321631
> R=abarth@chromium.org
> 
> Review URL: https://codereview.chromium.org/106413002

TBR=jochen@chromium.org

Review URL: https://codereview.chromium.org/107583002

git-svn-id: svn://svn.chromium.org/blink/trunk@163291 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: fd94e1959745df9984c3fcc7465b7725586d172d