Fix missing include if no CDMs are enabled in build configuration
When neither ENABLE_PEPPER_CDMS nor ENABLE_BROWSER_CDMS are defined,
no include is providing a full declaration for the class
media::CdmFactory. This causes a compilation error because the
scoped_ptr in render_frame_impl.h:1130 needs the full declaration,
which is unavailable if neither of two mentioned defines are present.
This include fixes the compilation issue, which can be reproduced by
setting the build flags embedded=1, use_widevine=0, use_playready=0.

Review URL: https://codereview.chromium.org/1851083002

Cr-Commit-Position: refs/heads/master@{#384901}

Former-commit-id: 0d20bb6dec45ec4b57987bdaaa0cdde3114bba53