Revert of media: Move widevine CDM targets to WidevineCdm folder (patchset #9 id:220001 of https://codereview.chromium.org/1957643002/ )
Reason for revert:
Multiple problems. Compile failures on Mac and browser_tests failures on Linux.

Mac failure logs:

[12124/32437] SOLINK ClearKeyCdm/libclearkeycdm.dylib, POSTBUILDS
FAILED: ClearKeyCdm/libclearkeycdm.dylib ClearKeyCdm/libclearkeycdm.dylib.TOC
if [ ! -e ClearKeyCdm/libclearkeycdm.dylib -o ! -e ClearKeyCdm/libclearkeycdm.dylib.TOC ] || otool -l ClearKeyCdm/libclearkeycdm.dylib | grep -q LC_REEXPORT_DYLIB ; then /b/build/slave/cache/cipd/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-search_paths_first -Wl,-dead_strip -mmacosx-version-min=10.7 -isysroot /Applications/Xcode5.1.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -arch x86_64 -L. -install_name @rpath/libclearkeycdm.dylib -stdlib=libc++ -o ClearKeyCdm/libclearkeycdm.dylib @ClearKeyCdm/libclearkeycdm.dylib.rsp && (export BUILT_FRAMEWORKS_DIR=/b/build/slave/Mac/build/src/out/Release; export BUILT_PRODUCTS_DIR=/b/build/slave/Mac/build/src/out/Release; export CONFIGURATION=Release; export DYLIB_INSTALL_NAME_BASE=@rpath; export EXECUTABLE_NAME=libclearkeycdm.dylib; export EXECUTABLE_PATH=libclearkeycdm.dylib; export FULL_PRODUCT_NAME=libclearkeycdm.dylib; export LD_DYLIB_INSTALL_NAME=@rpath/libclearkeycdm.dylib; export MACH_O_TYPE=mh_dylib; export PRODUCT_NAME=clearkeycdm; export PRODUCT_TYPE=com.apple.product-type.library.dynamic; export SDKROOT=/Applications/Xcode5.1.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk; export SRCROOT=/b/build/slave/Mac/build/src/out/Release/../../media; export SOURCE_ROOT="${SRCROOT}"; export TARGET_BUILD_DIR=/b/build/slave/Mac/build/src/out/Release; export TEMP_DIR="${TMPDIR}"; export XCODE_VERSION_ACTUAL=0511; (cd ../../media && ../build/mac/strip_from_xcode); G=$?; ((exit $G) || rm -rf ClearKeyCdm/libclearkeycdm.dylib) && exit $G) && { otool -l ClearKeyCdm/libclearkeycdm.dylib | grep LC_ID_DYLIB -A 5; nm -gP ClearKeyCdm/libclearkeycdm.dylib | cut -f1-2 -d' ' | grep -v U$; true; } > ClearKeyCdm/libclearkeycdm.dylib.TOC; else /b/build/slave/cache/cipd/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-search_paths_first -Wl,-dead_strip -mmacosx-version-min=10.7 -isysroot /Applications/Xcode5.1.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -arch x86_64 -L. -install_name @rpath/libclearkeycdm.dylib -stdlib=libc++ -o ClearKeyCdm/libclearkeycdm.dylib @ClearKeyCdm/libclearkeycdm.dylib.rsp && (export BUILT_FRAMEWORKS_DIR=/b/build/slave/Mac/build/src/out/Release; export BUILT_PRODUCTS_DIR=/b/build/slave/Mac/build/src/out/Release; export CONFIGURATION=Release; export DYLIB_INSTALL_NAME_BASE=@rpath; export EXECUTABLE_NAME=libclearkeycdm.dylib; export EXECUTABLE_PATH=libclearkeycdm.dylib; export FULL_PRODUCT_NAME=libclearkeycdm.dylib; export LD_DYLIB_INSTALL_NAME=@rpath/libclearkeycdm.dylib; export MACH_O_TYPE=mh_dylib; export PRODUCT_NAME=clearkeycdm; export PRODUCT_TYPE=com.apple.product-type.library.dynamic; export SDKROOT=/Applications/Xcode5.1.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk; export SRCROOT=/b/build/slave/Mac/build/src/out/Release/../../media; export SOURCE_ROOT="${SRCROOT}"; export TARGET_BUILD_DIR=/b/build/slave/Mac/build/src/out/Release; export TEMP_DIR="${TMPDIR}"; export XCODE_VERSION_ACTUAL=0511; (cd ../../media && ../build/mac/strip_from_xcode); G=$?; ((exit $G) || rm -rf ClearKeyCdm/libclearkeycdm.dylib) && exit $G) && { otool -l ClearKeyCdm/libclearkeycdm.dylib | grep LC_ID_DYLIB -A 5; nm -gP ClearKeyCdm/libclearkeycdm.dylib | cut -f1-2 -d' ' | grep -v U$; true; } > ClearKeyCdm/libclearkeycdm.dylib.tmp && if ! cmp -s ClearKeyCdm/libclearkeycdm.dylib.tmp ClearKeyCdm/libclearkeycdm.dylib.TOC; then mv ClearKeyCdm/libclearkeycdm.dylib.tmp ClearKeyCdm/libclearkeycdm.dylib.TOC ; fi; fi
Traceback (most recent call last):
  File "/b/build/slave/Mac/build/src/media/../build/mac/strip_save_dsym", line 335, in <module>
    sys.exit(main(sys.argv))
  File "/b/build/slave/Mac/build/src/media/../build/mac/strip_save_dsym", line 329, in main
    if not strip_and_make_fake_dsym(macho):
  File "/b/build/slave/Mac/build/src/media/../build/mac/strip_save_dsym", line 263, in strip_and_make_fake_dsym
    macho_stat = os.stat(macho)
OSError: [Errno 2] No such file or directory: '/b/build/slave/Mac/build/src/out/Release/libclearkeycdm.dylib'

Failing Linux (dbg) tests:

MSE_ExternalClearKey/EncryptedMediaTest.Playback_Multiple_VideoAudio_WebM/0
ECKEncryptedMediaTest.LoadUnknownSession
SRC_ExternalClearKey/EncryptedMediaTest.Playback_AudioOnly_WebM/0
MSE_ExternalClearKeyDecryptOnly/EncryptedMediaTest.Playback_VideoClearAudio_WebM/0
PepperContentSettingsSpecialCasesTest.Baseline
SRC_ExternalClearKey/EncryptedMediaTest.Playback_Multiple_VideoAudio_WebM/0
SRC_ExternalClearKey/EncryptedMediaTest.Playback_VideoAudio_WebM_Opus/0
MSE_ExternalClearKey/EncryptedMediaTest.InvalidResponseKeyError/0
MSE_ExternalClearKeyDecryptOnly/EncryptedMediaTest.Playback_VideoClearAudio_WebM_Opus/0
SRC_ExternalClearKey/EncryptedMediaTest.Playback_VideoClearAudio_WebM_Opus/0
ECKEncryptedMediaTest.LoadLoadableSession
MSE_ExternalClearKeyDecryptOnly/EncryptedMediaTest.ConfigChangeVideo/0
MSE_ExternalClearKey/EncryptedMediaTest.Playback_AudioOnly_WebM/0
MSE_ExternalClearKey/EncryptedMediaTest.Playback_VideoClearAudio_WebM_Opus/0
MSE_ExternalClearKey/EncryptedMediaTest.Playback_VideoOnly_WebM/0
MSE_ExternalClearKeyDecryptOnly/EncryptedMediaTest.FrameSizeChangeVideo/0
SRC_ExternalClearKey/EncryptedMediaTest.InvalidResponseKeyError/0
ECKEncryptedMediaTest.CDMCrashDuringDecode
MSE_ExternalClearKeyDecryptOnly/EncryptedMediaTest.Playback_VideoAudio_WebM_Opus/0
MSE_ExternalClearKeyDecryptOnly/EncryptedMediaTest.InvalidResponseKeyError/0
SRC_ExternalClearKey/EncryptedMediaTest.Playback_VideoClearAudio_WebM/0
MSE_ExternalClearKeyDecryptOnly/EncryptedMediaTest.Playback_AudioClearVideo_WebM/0
MSE_ExternalClearKeyDecryptOnly/EncryptedMediaTest.Playback_Multiple_VideoAudio_WebM/0
SRC_ExternalClearKey/EncryptedMediaTest.Playback_AudioClearVideo_WebM/0
MSE_ExternalClearKey/EncryptedMediaTest.Playback_VideoAudio_WebM/0
SRC_ExternalClearKey/EncryptedMediaTest.Playback_AudioOnly_WebM_Opus/0
MSE_ExternalClearKeyDecryptOnly/EncryptedMediaTest.Playback_VideoOnly_WebM/0
MSE_ExternalClearKey/EncryptedMediaTest.Playback_AudioClearVideo_WebM/0
SRC_ExternalClearKey/EncryptedMediaTest.Playback_VideoAudio_WebM/0
MSE_ExternalClearKeyDecryptOnly/EncryptedMediaTest.Playback_VideoAudio_WebM/0
MSE_ExternalClearKey/EncryptedMediaTest.Playback_VideoClearAudio_WebM/0
ECKEncryptedMediaTest.CDMExpectedCrash
ECKEncryptedMediaTest.FileIOTest
MSE_ExternalClearKeyDecryptOnly/EncryptedMediaTest.Playback_AudioOnly_WebM/0
MSE_ExternalClearKey/EncryptedMediaTest.Playback_VP9Video_WebM/0
MSE_ExternalClearKey/EncryptedMediaTest.ConfigChangeVideo/0
MSE_ExternalClearKeyDecryptOnly/EncryptedMediaTest.Playback_VP9Video_WebM/0
SRC_ExternalClearKey/EncryptedMediaTest.Playback_VideoOnly_WebM/0
MSE_ExternalClearKey/EncryptedMediaTest.FrameSizeChangeVideo/0
SRC_ExternalClearKey/EncryptedMediaTest.FrameSizeChangeVideo/0
MSE_ExternalClearKey/EncryptedMediaTest.Playback_VideoAudio_WebM_Opus/0
MSE_ExternalClearKeyDecryptOnly/EncryptedMediaTest.Playback_AudioOnly_WebM_Opus/0
SRC_ExternalClearKey/EncryptedMediaTest.Playback_VP9Video_WebM/0
MSE_ExternalClearKey/EncryptedMediaTest.Playback_AudioOnly_WebM_Opus/0

Original issue's description:
> media: Move widevine CDM targets to WidevineCdm folder
>
> Put Widevine CDM and adapter in WidevineCdm folder in the output
> directory instead of in the output directory directly. This will make it
> easier for us to ship manifest.json file alongside with the CDM. It will
> also make it easier for use to bundle the CDM on Windows and Mac.
>
> BUG=582622
> TEST=Unit tests still pass. Manually tested on Linux.
>
> Committed: https://crrev.com/97fe312ed8daf19170558f05d4d77c04a291bc32 [formerly 3569f3d0f45b847990522f1655fb324c55dca887]
> Cr-Commit-Position: refs/heads/master@{#393672}

TBR=ddorwin@chromium.org,mark@chromium.org,rsesek@chromium.org,stgao@chromium.org,thakis@chromium.org,thestig@chromium.org,xhwang@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=582622

Review-Url: https://codereview.chromium.org/1978123002
Cr-Commit-Position: refs/heads/master@{#393762}

Former-commit-id: cdea1d3a19ffa03173b2ad4f492047488e511ded