Disable PrepopulateRespectBlack interactive_ui_test
Becomes flaky in Aura windows

browser\ui\views\find_bar_host_interactive_uitest.cc(222): error: Value of: GetFindBarText()
  Actual: L""
Expected: ASCIIToUTF16("a")
Which is: L"a"


BUG=292299
TEST=none
TBR=sky

Review URL: https://codereview.chromium.org/24129007

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@223301 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 64e0436a17febdad42b441121cc41e50502f36d3