Filter out -funwind-tables for nacl_helper_bootstrap
This flag is needed to get stack traces on ARM, but breaks
the Native Client build. Let's filter out this flag for
nacl_helper_bootstrap.

The following link error occurs if you build with -funwind-tables without this change:

../../../../../c/Release/gen/nacl_bootstrap/../../obj/native_client/src/trusted/service_runtime/linux/nacl_bootstrap_lib.nacl_bootstrap.o:(.ARM.exidx.text.fail+0x0):
undefined reference to `__aeabi_unwind_cpp_pr0'

BUG=180975


Review URL: https://chromiumcodereview.appspot.com/12541017

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@10964 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: 45364414310f00996eb03d167ab1873a0ea41c43