Revert of Blimp: add support for SSL connections. (patchset #20 id:380001 of https://codereview.chromium.org/1696563002/ )
Reason for revert:
Broke blimp_unittests_apk building on android:

FAILED: python "/b/build/slave/android_build/build/src/build/toolchain/gcc_solink_wrapper.py" --readelf="../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-readelf" --nm="../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm" --strip=../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip --sofile="./lib.unstripped/libblimp_client_android.so" --tocfile="./libblimp_client_android.so.TOC" --output="./libblimp_client_android.so" -- ../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -shared -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -fuse-ld=gold -Wl,--no-undefined -Wl,--exclude-libs=libgcc.a -Wl,--exclude-libs=libc++_static.a -Wl,--exclude-libs=libvpx_assembly_arm.a -Wl,--icf=all -Wl,--warn-shared-textrel -Wl,-O1 -Wl,--as-needed -nostdlib -Wl,--warn-shared-textrel --sysroot=../../third_party/android_tools/ndk/platforms/android-16/arch-arm  -Wl,--version-script=/b/build/slave/android_build/build/src/build/android/android_no_jni_exports.lst -L../../third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -o "./lib.unstripped/libblimp_client_android.so" -Wl,-soname="libblimp_client_android.so" @"./libblimp_client_android.so.rsp"
../../content/browser/android/in_process/synchronous_compositor_factory_impl.cc:125: error: undefined reference to 'content::SynchronousCompositorExternalBeginFrameSource::SynchronousCompositorExternalBeginFrameSource(int, content::SynchronousCompositorRegistry*)'
../../content/browser/android/in_process/synchronous_compositor_factory_impl.cc:113: error: undefined reference to 'content::SynchronousCompositorOutputSurface::SynchronousCompositorOutputSurface(scoped_refptr<cc::ContextProvider> const&, scoped_refptr<cc::ContextProvider> const&, int, content::SynchronousCompositorRegistry*, scoped_refptr<content::FrameSwapMessageQueue>)'
../../base/memory/ref_counted.h:193: error: undefined reference to 'content::FrameSwapMessageQueue::~FrameSwapMessageQueue()'
../../content/browser/android/in_process/synchronous_compositor_factory_impl.cc:93: error: undefined reference to 'content::SynchronousCompositorFactory::SetInstance(content::SynchronousCompositorFactory*)'
../../content/browser/android/in_process/synchronous_compositor_factory_impl.cc:197: error: undefined reference to 'content::StreamTextureFactorySynchronousImpl::Create(base::Callback<scoped_refptr<content::StreamTextureFactorySynchronousImpl::ContextProvider> ()> const&)'
../../content/browser/android/in_process/synchronous_compositor_factory_impl.cc:272: error: undefined reference to 'content::RenderThreadImpl::SetStreamTextureFactory(scoped_refptr<content::StreamTextureFactory>)'
../../content/browser/android/in_process/synchronous_compositor_impl.cc:102: error: undefined reference to 'content::SynchronousCompositorOutputSurface::SetTreeActivationCallback(base::Callback<void ()> const&)'
../../content/browser/android/in_process/synchronous_compositor_impl.cc:125: error: undefined reference to 'content::SynchronousCompositorOutputSurface::SetSyncClient(content::SynchronousCompositorOutputSurfaceClient*)'
../../content/browser/android/in_process/synchronous_compositor_impl.cc:126: error: undefined reference to 'content::SynchronousCompositorExternalBeginFrameSource::SetClient(content::SynchronousCompositorExternalBeginFrameSourceClient*)'
../../content/browser/android/in_process/synchronous_compositor_impl.cc:135: error: undefined reference to 'content::SynchronousCompositorOutputSurface::SetTreeActivationCallback(base::Callback<void ()> const&)'
../../content/browser/android/in_process/synchronous_compositor_impl.cc:141: error: undefined reference to 'content::SynchronousCompositorExternalBeginFrameSource::SetClient(content::SynchronousCompositorExternalBeginFrameSourceClient*)'
../../content/browser/android/in_process/synchronous_compositor_impl.cc:142: error: undefined reference to 'content::SynchronousCompositorOutputSurface::SetSyncClient(content::SynchronousCompositorOutputSurfaceClient*)'
../../content/browser/android/in_process/synchronous_compositor_impl.cc:178: error: undefined reference to 'content::SynchronousCompositorOutputSurface::ReturnResources(cc::CompositorFrameAck const&)'
../../content/browser/android/in_process/synchronous_compositor_impl.cc:215: error: undefined reference to 'content::SynchronousCompositorOutputSurface::SetMemoryPolicy(unsigned int)'
../../content/browser/android/in_process/synchronous_compositor_impl.cc:275: error: undefined reference to 'content::SynchronousCompositorExternalBeginFrameSource::BeginFrame(cc::BeginFrameArgs const&)'
../../content/browser/android/in_process/synchronous_compositor_impl.cc:320: error: undefined reference to 'content::SynchronousCompositorOutputSurface::GetMessagesToDeliver(std::__1::vector<scoped_ptr<IPC::Message, std::__1::default_delete<IPC::Message> >, std::__1::allocator<scoped_ptr<IPC::Message, std::__1::default_delete<IPC::Message> > > >*)'
../../content/browser/android/in_process/synchronous_compositor_impl.cc:167: error: undefined reference to 'content::SynchronousCompositorOutputSurface::DemandDrawHw(gfx::Size const&, gfx::Transform const&, gfx::Rect const&, gfx::Rect const&, gfx::Rect const&, gfx::Transform const&)'
../../content/browser/android/in_process/synchronous_compositor_impl.cc:187: error: undefined reference to 'content::SynchronousCompositorOutputSurface::DemandDrawSw(SkCanvas*)'
../../content/browser/android/in_process/synchronous_compositor_renderer_statics.cc:12: error: undefined reference to 'content::SynchronousCompositorProxy::SetSkCanvasForDraw(SkCanvas*)'
../../content/browser/android/synchronous_compositor_base.cc:32: error: undefined reference to 'content::InProcessGpuThread::InProcessGpuThread(content::InProcessChildThreadParams const&, gpu::GpuPreferences const&, gpu::SyncPointManager*)'
collect2: error: ld returned 1 exit status

Original issue's description:
> Blimp: add support for SSL connections.
>
> This CL allows the Blimp client to establish TLS-protected channels with the backend engine. The authenticity of the engine is validated by checking if its cert is an exact match of a certificate provided separately by the Assigner API.
>
> * Create new Blimp SSL transport class: SSLClientTransport.
> * Create custom CertValidator for checking an exact cert match against the SSL peer's cert
> * Integrate SSLClientTransport with BlimpClientSession.
> * Assignment: add certificate field.
> * AssignmentSource: add certificate file reading; PEM file parsing;
>   X509 certificate parsing.
> * Created new DEPS entries as appropriate.
>
> R=wez@chromium.org
> CC=rsleevi@chromium.org
> BUG=585279,589202
>
> Committed: https://crrev.com/ec20ed5cf43e086565e49f6a82e59f79c2bf390c [formerly c80f5095f045ad1712f1f1075a44547a561f774a]
> Cr-Commit-Position: refs/heads/master@{#378839}

TBR=wez@chromium.org,dtrainor@chromium.org,rsesek@chromium.org,rsleevi@chromium.org,kmarshall@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=585279,589202

Review URL: https://codereview.chromium.org/1757153002

Cr-Commit-Position: refs/heads/master@{#378892}

Former-commit-id: 7fa22e7520009140156013bc87f39a39fe8bd2ca