Revert "Scheme handling in the WKWebView"
This reverts commit 92d16fe23fd47746b9076bd4672991d0d36d91a7 [formerly 6aa0fd954e07511db2e7f58bd924c135393543c0].

Reason for revert: causes compile failure on iow-web-view bot:
https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/ios-webview/5539
FAILED: 
../../ios/web/web_state/ui/wk_web_view_configuration_provider.mm:124:25: error: 'setURLSchemeHandler:forURLScheme:' is only available on iOS 11.0 or newer [-Werror,-Wunguarded-availability-new]
        [configuration_ setURLSchemeHandler:scheme_handler_
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Original change's description:
> Scheme handling in the WKWebView
> 
> This CL is a prototype for letting the WKWebView handling the chrome:// scheme.
> 
> - The WKWebViewConfigurationProvider uses the WebClient's AdditionalSchemes() to set the scheme handling on the WKConfiguration.
> - The CRWWebUIManager created in CRWWebController isn't created anymore.
> - Previously, the network calls to chrome://resources/js/ios/web_ui.js were intercepted and routed to a bundled js. This bundle is now packed into one js: ui/webui/resources/js/web_ui.js
> 
> Bug: 739844
> Change-Id: Ia0a57ec3d936f0cee8f4588fce7ab01e95adf524
> Reviewed-on: https://chromium-review.googlesource.com/c/1378094
> Reviewed-by: Dan Beam <dbeam@chromium.org>
> Reviewed-by: Eugene But <eugenebut@chromium.org>
> Commit-Queue: Gauthier Ambard <gambard@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#627864}

TBR=dbeam@chromium.org,eugenebut@chromium.org,gambard@chromium.org

Change-Id: Ie49d29fb42bfef8333a81a01406a255393515ef5
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 739844
Reviewed-on: https://chromium-review.googlesource.com/c/1446266
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#627870}
Former-commit-id: 83bbd097fa09c738b5c656c5d2acf975d9681418