closure: fix compiler error via downcasting.
(ERROR) Error in: help.js
## /mnt/data/b/build/slave/Closure_Compilation_Linux/build/src/chrome/browser/resources/chromeos/user_images_grid.js:128: ERROR - as
## found   : function (new:cr.ui.ListItem, (Object|null)): ?
## required: function (new:cr.ui.ListItem, *): ?
##       this.itemConstructor =
##       ^

TBR=arv@chromium.org
BUG=393873

Review URL: https://codereview.chromium.org/653283002

Cr-Commit-Position: refs/heads/master@{#299642}

Former-commit-id: f917d62847b627f3dfbb13ba9464d18f8152bb10