Revert "First pass at supporting BLE advertisement on macOS."
This reverts commit 6e82aa8cc7e64387919b11380053a36e6e18e24e [formerly 28a79156145daedc2b6af6cd13e3f4f28ca67ab5].

Reason for revert: Causes build break
device/bluetooth/bluetooth_low_energy_advertisement_manager_mac.mm:26:35: error: comparison of two values with different enumeration types ('CBManagerState' and 'CBPeripheralManagerState') [-Werror,-Wenum-compare]
  if ([peripheral_manager_ state] < CBPeripheralManagerStatePoweredOn) {
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Mac Team Request: Please add a Mac reviewer for this reland. Thanks!

Original change's description:
> First pass at supporting BLE advertisement on macOS.
> 
> This very basic implementation currently only supports one active
> advertisement.
> 
> Future work will add tests and better handle concurrent advertisements.
> 
> BUG=846881
> 
> Change-Id: I48b76e84d67060e7265533759752fcc0e84f5cc6
> Reviewed-on: https://chromium-review.googlesource.com/1142294
> Reviewed-by: Gustavo Sacomoto <sacomoto@chromium.org>
> Reviewed-by: Giovanni Ortuño Urquidi <ortuno@chromium.org>
> Commit-Queue: Tim Song <tengs@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#576712}

TBR=tengs@chromium.org,sacomoto@chromium.org,ortuno@chromium.org

Change-Id: I13eec942b3a76ad5baa6b9dca624c41c5fc29178
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 846881
Reviewed-on: https://chromium-review.googlesource.com/1145444
Reviewed-by: Robert Liao <robliao@chromium.org>
Commit-Queue: Robert Liao <robliao@chromium.org>
Cr-Commit-Position: refs/heads/master@{#576931}
Former-commit-id: 9f3c324c7367a50548009e649b03c97e4f214197