Revert 100917 - Not use SSSE3 code that was merged accidentally
Failed on official Linux 32 builder.  (x486?)

http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Linux/builds/11240/steps/compile/logs/stdio

In file included from media/base/yuv_convert.cc:33:
/usr/lib/gcc/i486-linux-gnu/4.4.3/include/emmintrin.h:32:3:error: #error "SSE2 instruction set not enabled"
make: *** [out/Release/obj.target/yuv_convert/media/base/yuv_convert.o] Error 1


Disable SSSE3 conversion code as tests are not running.

TBR=hbono@chromium.org
BUG=None
TEST=None

Review URL: http://codereview.chromium.org/7888014

TBR=hclam@chromium.org
Review URL: http://codereview.chromium.org/7890023

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@101006 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: caf09f737c0d48bca9c541130daf78ab40fe6953