Fix for partialTrans and noUndefinedDots undeclared identifiers on windows builds
Commits 6b0ab9c5276d9a86eece8a430f9a459e033e2b39 and
56bb7170f14808ac176893274d680839a55fc6c8 added noUndefinedDots and
partialTrans translation modes on liblouis/liblouis.h.in but did not
update windows/include/liblouis.h.
It currently causes the windows build to fail with compile error C2065
(undeclared identifiers for partialTrans and noUndefinedDots). This
commit fixes the issue.