Revert of [libfuzzer] proto-based renderer fuzzer draft (patchset #1 id:1 of https://codereview.chromium.org/2744403002/ )
Reason for revert:
proto2 has the same problem:

13882/56507] CXX obj/content/test/fuzzer/html_tree_proto/html_tree.pb.obj
FAILED: obj/content/test/fuzzer/html_tree_proto/html_tree.pb.obj
ninja -t msvc -e environment.x86 -- C:\b\c\goma_client/gomacc.exe "C:\b\depot_tools\win_toolchain\vs_files\d3cb0e37bdd120ad0ac4650b674b09e81be45616\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/content/test/fuzzer/html_tree_proto/html_tree.pb.obj.rsp /c gen/content/test/fuzzer/html_tree.pb.cc /Foobj/content/test/fuzzer/html_tree_proto/html_tree.pb.obj /Fd"obj/content/test/fuzzer/html_tree_proto_cc.pdb"
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(171): error C2220: warning treated as error - no 'object' file generated
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(171): warning C4125: decimal digit terminates octal escape sequence
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(172): warning C4125: decimal digit terminates octal escape sequence
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(173): warning C4125: decimal digit terminates octal escape sequence
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(185): warning C4125: decimal digit terminates octal escape sequence
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(186): warning C4125: decimal digit terminates octal escape sequence
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(187): warning C4125: decimal digit terminates octal escape sequence
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(188): warning C4125: decimal digit terminates octal escape sequence
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(201): warning C4125: decimal digit terminates octal escape sequence
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(202): warning C4125: decimal digit terminates octal escape sequence
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(222): warning C4125: decimal digit terminates octal escape sequence
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(223): warning C4125: decimal digit terminates octal escape sequence
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(224): warning C4125: decimal digit terminates octal escape sequence
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(225): warning C4125: decimal digit terminates octal escape sequence

Original issue's description:
> [libfuzzer] proto-based renderer fuzzer draft
>
> This reverts commit 183f92b63d1982159129dda3ce7b087058e17007 [formerly 42ada11652ece20e9e564ab45552985ab9fa6308].
> Difference: proto2 instead of proto3
>
> BUG=
>
> Review-Url: https://codereview.chromium.org/2744403002
> Cr-Commit-Position: refs/heads/master@{#456497}
> Committed: https://chromium.googlesource.com/chromium/src/+/2e7ae51597c61b77b3e152cd6ce60b8603fddb21 [formerly 41fd546edd6cb8dca649b193fad39c4a86547850]

TBR=vitalybuka@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review-Url: https://codereview.chromium.org/2743323004
Cr-Commit-Position: refs/heads/master@{#456507}

Former-commit-id: 8bcc0b7a1ed6f4cbdf8d6d1dd203734390f010e5