upload_gce_image: drop
I don't think these are used anymore, and they don't seem to even work:
$ ./upload_gce_image --help
./upload_gce_image: could not import chromite module: .../chromite/contrib/compute/upload_gce_image.py: No module named compute
Traceback (most recent call last):
  File "./upload_gce_image", line 169, in <module>
    DoMain()
  File "./upload_gce_image", line 165, in DoMain
    commandline.ScriptWrapperMain(FindTarget)
  File ".../chromite/lib/commandline.py", line 890, in ScriptWrapperMain
    target = find_target_func(target)
  File "./upload_gce_image", line 140, in FindTarget
    module = cros_import.ImportModule(target)
  File ".../chromite/lib/cros_import.py", line 44, in ImportModule
    module = __import__(target)
  File ".../chromite/contrib/compute/upload_gce_image.py", line 20, in <module>
    from chromite.compute import gcloud
ImportError: No module named compute

BUG=None
TEST=None

Change-Id: I24ed9a265074319270f400acaf62941d290ff135
Reviewed-on: https://chromium-review.googlesource.com/1152469
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Jason Clinton <jclinton@chromium.org>
Reviewed-by: Don Garrett <dgarrett@chromium.org>