upload_symbols: WriteQueueToFile: drain the queue even w/no list
When we have a lot of failed entries flowing into the failed queue, but
we aren't writing them to a file, the main thread might exit before the
core queue gets a chance to send all the items into the queue.  This can
manifest at runtime as a traceback like so:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
    send(obj)
IOError: [Errno 32] Broken pipe

The answer is to drain the failed queue all the time.

BUG=None
TEST=`./buildbot/run_tests` passes
TEST=ran upload_symbols by hand to trigger race and saw it no longer crash

Change-Id: I597135011d3b72011d53262f2ae3b637cae63db4
Reviewed-on: https://chromium-review.googlesource.com/190023
Reviewed-by: David James <davidjames@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Don Garrett <dgarrett@chromium.org>