Revert of exo: Add Restore function to ShellSurface class. (patchset #1 id:1 of https://codereview.chromium.org/1658723003/ )
Reason for revert:
Caused a compile failure:
https://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20GN/builds/34606/steps/compile/logs/stdio

FAILED: /mnt/data/b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/components/exo/exo/shell_surface.o.d -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -DENABLE_MDNS=1 -DENABLE_NOTIFICATIONS -DENABLE_PEPPER_CDMS -DENABLE_PLUGINS=1 -DENABLE_PDF=1 -DENABLE_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DDONT_EMBED_BUILD_METADATA -DUSE_UDEV -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_ASH=1 -DUSE_AURA=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_OPENSSL=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DENABLE_WEBRTC=1 -DENABLE_EXTENSIONS=1 -DENABLE_CONFIGURATION_POLICY -DENABLE_TASK_MANAGER=1 -DENABLE_THEMES=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_APP_LIST=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_AUTOFILL_DIALOG=1 -DIMAGE_LOADER_EXTENSION=1 -DENABLE_HIDPI=1 -DENABLE_TOPCHROME_MD=1 -DENABLE_WAYLAND_SERVER=1 -DENABLE_BACKGROUND=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=257955-1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DOS_CHROMEOS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DTOOLKIT_VIEWS=1 -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_SUPPORT_GPU=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DMESA_EGL_NO_X11_HEADERS -I../.. -Igen -I../../third_party/khronos -I../../gpu -Igen/ash/resources -Igen/ash/strings -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/include/gpu -I../../third_party/skia/src/gpu -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/mesa/src/include -Igen -Igen/ui/views/resources -fno-strict-aliasing -funwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -fcolor-diagnostics -pthread -m64 -march=x86-64 -Wall -Wextra -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wfor-loop-analysis -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-shift-negative-value -O2 -fno-ident -fdata-sections -ffunction-sections -g0 -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -plugin-arg-find-bad-constructs -Xclang follow-macro-expansion -Wheader-hygiene -Wstring-conversion -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -Wno-reserved-user-defined-literal -fno-rtti -fno-exceptions -c ../../components/exo/shell_surface.cc -o obj/components/exo/exo/shell_surface.o
../../components/exo/shell_surface.cc:112:70: error: too few arguments to function call, expected 2, have 1
    configure_callback_.Run(widget_->GetWindowBoundsInScreen().size());
    ~~~~~~~~~~~~~~~~~~~~~~~                                          ^
../../base/callback.h:389:3: note: 'Run' declared here
  R Run(typename internal::CallbackParamTraits<Args>::ForwardType... args)
  ^
1 error generated.
ninja: build stopped: subcommand failed.

Original issue's description:
> exo: Add Restore function to ShellSurface class.
>
> Restore function can be used to have a maximized window
> return to its normal unmaximized state.
>
> BUG=549781
> TEST=exo_unittests --gtest_filter=ShellSurfaceTest.Restore
>
> Committed: https://crrev.com/e094d2cd87ce54d1e4827126c8832097c47edb5d [formerly c270e2545f9d953c50d0dbfbe9496e7692c9a83d]
> Cr-Commit-Position: refs/heads/master@{#372733}

TBR=lpique@chromium.org,reveman@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=549781

Review URL: https://codereview.chromium.org/1653153002

Cr-Commit-Position: refs/heads/master@{#372756}

Former-commit-id: c48eb196754d29cc5f446fca181634d2ab24e18c