a11y: Include <memory> for std::unique_ptr in accessibility_alert_window.h
IWYU. This fixes the libstdc++ build after commit 1ed701bc4 ("Remove fake
alert AXObjWrapper object"):

    In file included from ../../ui/views/accessibility/accessibility_alert_window.cc:5:
    ../../ui/views/accessibility/accessibility_alert_window.h:34:8: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
       std::unique_ptr<aura::Window> alert_window_;
            ^~~~~~~~~~
    ../../ui/views/accessibility/accessibility_alert_window.h:34:3: note: ‘std::unique_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?

Bug: 819294
Change-Id: I5e41e529fb5961ae2c93359328d437da40fa60fd
Reviewed-on: https://chromium-review.googlesource.com/c/1375119
Reviewed-by: Dominic Mazzoni <dmazzoni@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#616747}
Former-commit-id: 9df045779f62cbbe3fbf56be9b0329302e9a0df7