Revert "Moved GL enums from GraphicsContext3D to a more generic location."
This reverts commit db4863b848c80f914932f1f1cff4276890ae0d98.

It broke the Android build:

WebMediaPlayerClientImpl.cpp: In member function 'void blink::WebMediaPlayerClientImpl::paintOnAndroid(...)':
WebMediaPlayerClientImpl.cpp:597:98:error: 'RGBA' is not a member of 'WebCore::GraphicsContext3D'
WebMediaPlayerClientImpl.cpp:597:123:error: 'UNSIGNED_BYTE' is not a member of 'WebCore::GraphicsContext3D'

TBR=bajones@chromium.org

Review URL: https://codereview.chromium.org/113153002

git-svn-id: svn://svn.chromium.org/blink/trunk@163726 bbb929c8-8fbe-4397-9dbb-9b2b20218538

Former-commit-id: fc9b03873042e344a4ea26a579c58f82df2d3168