Revert 284995 "NaCl: Update revision in DEPS, r13506 -> r13511"
broke win64 build:

FAILED: C:\b\depot_tools\python276_bin\python.exe gyp-win-tool action-wrapper environment.x64 aot_target_build_newlib_x86_32_nonsfi_nlib__via_pnacl__363af64d0619df24e45ee3bc5549531a..rsp ..\..\ppapi\native_client\src\untrusted\pnacl_irt_shim
error: unable to open output file '../../../../../out/Debug_x64/obj/ppapi/native_client/src/untrusted/pnacl_irt_shim/aot.gen/pnacl_newlib_x86_32-nonsfi/aot/irt_shim_ppapi.o---irt_shim_ppapi.c---.po': 'Error opening output file '../../../../../out/Debug_x64/obj/ppapi/native_client/src/untrusted/pnacl_irt_shim/aot.gen/pnacl_newlib_x86_32-nonsfi/aot/irt_shim_ppapi.o---irt_shim_ppapi.c---.po': The system cannot find the path specified'
1 error generated.
..\..\..\..\..\out\Debug_x64\gen\sdk\win_x86\pnacl_newlib\bin\pnacl-clang -c irt_shim_ppapi.c -o ../../../../../out/Debug_x64/obj/ppapi/native_client/src/untrusted/pnacl_irt_shim/aot.gen/pnacl_newlib_x86_32-nonsfi/aot/irt_shim_ppapi.o -MD -MF ../../../../../out/Debug_x64/obj/ppapi/native_client/src/untrusted/pnacl_irt_shim/aot.gen/pnacl_newlib_x86_32-nonsfi/aot/irt_shim_ppapi.o.d --target=i686-unknown-nacl --pnacl-allow-native --pnacl-allow-translate -arch x86-32-nonsfi -O2 -g -Wall -fdiagnostics-show-option -Werror -DPNACL_SHIM_AOT -Wno-unused-function -Wno-char-subscripts -Wno-c++11-extensions -Wno-unnamed-type-template-args -Wno-extra-semi -Wno-unused-private-field -Wno-char-subscripts -Wno-unused-function -D__linux__ -D__STDC_LIMIT_MACROS=1 -D__STDC_FORMAT_MACROS=1 -D_GNU_SOURCE=1 -D_BSD_SOURCE=1 -D_POSIX_C_SOURCE=199506 -D_XOPEN_SOURCE=600 -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DDYNAMIC_ANNOTATIONS_PREFIX=NACL_ -DNACL_BUILD_ARCH=x86 -DV8_DEPRECATION_WARNINGS -DBLINK_SCALE_FILTERS_AT_RECORD_TIME -DNOMINMAX -DPSAPI_VERSION=1 -D_CRT_RAND_S -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -D_ATL_NO_OPENGL -D_SECURE_ATL -DCHROMIUM_BUILD -DTOOLKIT_VIEWS=1 -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DNO_TCMALLOC -DENABLE_EGLIMAGE=1 -D__STD_C -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -DNTDDI_VERSION=0x06020000 -D_USING_V110_SDK71_ -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DCLD2_DATA_SOURCE=static -DCLD_DATA_FROM_STATIC -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DWIN_PDF_METAFILE_FOR_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_WIFI_BOOTSTRAPPING=1 -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DNACL_WINDOWS=0 -DNACL_OSX=0 -DNACL_LINUX=0 -DNACL_ANDROID=0 -I../../../../../out/Debug_x64/gen/tc_pnacl_newlib/include -I../../../../.. -I../../../../../out/Debug_x64/gen -I../../../../../third_party/wtl/include -std=gnu99

FAILED: Command '..\..\..\..\..\out\Debug_x64\gen\sdk\win_x86\pnacl_newlib\bin\pnacl-clang -c irt_shim_ppapi.c -o ../../../../../out/Debug_x64/obj/ppapi/native_client/src/untrusted/pnacl_irt_shim/aot.gen/pnacl_newlib_x86_32-nonsfi/aot/irt_shim_ppapi.o -MD -MF ../../../../../out/Debug_x64/obj/ppapi/native_client/src/untrusted/pnacl_irt_shim/aot.gen/pnacl_newlib_x86_32-nonsfi/aot/irt_shim_ppapi.o.d --target=i686-unknown-nacl --pnacl-allow-native --pnacl-allow-translate -arch x86-32-nonsfi -O2 -g -Wall -fdiagnostics-show-option -Werror -DPNACL_SHIM_AOT -Wno-unused-function -Wno-char-subscripts -Wno-c++11-extensions -Wno-unnamed-type-template-args -Wno-extra-semi -Wno-unused-private-field -Wno-char-subscripts -Wno-unused-function -D__linux__ -D__STDC_LIMIT_MACROS=1 -D__STDC_FORMAT_MACROS=1 -D_GNU_SOURCE=1 -D_BSD_SOURCE=1 -D_POSIX_C_SOURCE=199506 -D_XOPEN_SOURCE=600 -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DDYNAMIC_ANNOTATIONS_PREFIX=NACL_ -DNACL_BUILD_ARCH=x86 -DV8_DEPRECATION_WARNINGS -DBLINK_SCALE_FILTERS_AT_RECORD_TIME -DNOMINMAX -DPSAPI_VERSION=1 -D_CRT_RAND_S -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -D_ATL_NO_OPENGL -D_SECURE_ATL -DCHROMIUM_BUILD -DTOOLKIT_VIEWS=1 -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DNO_TCMALLOC -DENABLE_EGLIMAGE=1 -D__STD_C -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -DNTDDI_VERSION=0x06020000 -D_USING_V110_SDK71_ -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DCLD2_DATA_SOURCE=static -DCLD_DATA_FROM_STATIC -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DWIN_PDF_METAFILE_FOR_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_WIFI_BOOTSTRAPPING=1 -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DNACL_WINDOWS=0 -DNACL_OSX=0 -DNACL_LINUX=0 -DNACL_ANDROID=0 -I../../../../../out/Debug_x64/gen/tc_pnacl_newlib/include -I../../../../.. -I../../../../../out/Debug_x64/gen -I../../../../../third_party/wtl/include -std=gnu99' returned non-zero exit status 1

ninja: build stopped: subcommand failed.

http://build.chromium.org/p/chromium.win/builders/Win%20x64%20Builder%20%28dbg%29/builds/1055/steps/compile/logs/stdio

> NaCl: Update revision in DEPS, r13506 -> r13511
> 
> This pulls in the following Native Client changes:
> 
> r13507: (noelallen) Reapply patch which was reverted due to conflict.
> r13508: (dschuff) PNaCl Driver: do not generate temp file names beyond Windows' MAX_PATH limit
> r13509: (jvoung) Add a flag to pnacl-finalize that allows users to keep function names.
> r13510: (dschuff) Disable flaky sandboxed translator tests on mac
> r13511: (dschuff) Update revision for PNaCl r13466->r13509
> 
> BUG=none
> TEST=browser_tests and nacl_integration
> CQ_EXTRA_TRYBOTS=tryserver.chromium:linux_nacl_sdk_build
> (linux_rel_precise32,linux_arm_cross_compile omitted because they are currently broken)
> 
> R=jvoung@chromium.org
> 
> Review URL: https://codereview.chromium.org/409113009

TBR=dschuff@chromium.org

Review URL: https://codereview.chromium.org/418583002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@285015 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: c52fc8f4f79162f6ce4757377d6ae32b54321acc