DragControllerTest: Rename |ChromeClient()| to avoid naming conflicts
GCC is stricter than clang when it comes to class members' names and how
they can change the meaning of a previously existing symbol with the same
name:

    ../../third_party/WebKit/Source/core/page/DragControllerTest.cpp:57:72: error: declaration of ‘blink::DragMockChromeClient& blink::DragControllerTest::ChromeClient() const’ [-fpermissive]
       DragMockChromeClient& ChromeClient() const { return *chrome_client_; }
                                                                            ^
    In file included from ../../third_party/WebKit/Source/core/loader/EmptyClients.h:39:0,
                     from ../../third_party/WebKit/Source/core/layout/LayoutTestHelper.h:17,
                     from ../../third_party/WebKit/Source/core/page/DragControllerTest.cpp:14:
    ../../third_party/WebKit/Source/core/page/ChromeClient.h:94:19: error: changes meaning of ‘ChromeClient’ from ‘class blink::ChromeClient’ [-fpermissive]
     class CORE_EXPORT ChromeClient : public PlatformChromeClient {
                       ^~~~~~~~~~~~

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84709 contains a longer
explanation, but essentially having a |ChromeClient()| method can change the
meaning of references to |ChromeClient| in the code depending on where it
is declared, which contradicts the C++ standard.

Fix it by taking advantage of covariant return types: instead of having a
GetChromeClient() method that returns a |ChromeClient| and a ChromeClient()
method that returns a |DragMockChromeClient|, make GetChromeClient() return
a |DragMockChromeClient| and do away with ChromeClient() entirely.

Change-Id: I97834bfe22acb0745e5307d13e377f596587e199
Reviewed-on: https://chromium-review.googlesource.com/968496
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Cr-Commit-Position: refs/heads/master@{#544204}
Former-commit-id: 5427e0195a70a4707778a1d7ed0b0782afab3b7f