Disable ExtensionInstallUIBrowserTest.TestThemeInstallUndoResetsToDefault
Failing on Windows. Already disabled on Linux. Errors like

[ RUN      ] ExtensionInstallUIBrowserTest.TestThemeInstallUndoResetsToDefault
c:uild\slave\win_builderuild\src\chromerowser\extensions\extension_browsertest.cc(519): error: Value of: num_after
  Actual: 6
Expected: num_before + expected_change
Which is: 5
c:uild\slave\win_builderuild\src\chromerowser\extensions\extension_install_ui_browsertest.cc(101): error: Value of: InstallExtensionWithUIAutoConfirm(theme_crx, 0, browser())
  Actual: false
Expected: true

BUG=580907
TBR=rdevlin.cronin@chromium.org

Review URL: https://codereview.chromium.org/1624943003

Cr-Commit-Position: refs/heads/master@{#371175}

Former-commit-id: 3fda0948402ca048fe0a159e49dcd912e53cf806