Revert 198736 "Land Recent QUIC changes"
Caused compile failures on the "Google Chrome ChromeOS" builder:
cc1plus: warnings being treated as errors
net/quic/quic_utils.cc:14:error: integer constant is too large for 'unsigned long' type
net/quic/quic_utils.cc:15:error: integer constant is too large for 'unsigned long' type
make: *** [out/Release/obj.target/net/net/quic/quic_utils.o] Error 1


> Land Recent QUIC changes
> 
> Implement header compression/decompression in ReliableQuicStream.
> 
> Merge internal change: 44867738
> 
> 
> QUIC: deflake proof_test.
> 
> The current proof_test removes a byte from the start of the signature in order
> to make it invalid. However, the signature is a big-endian number and, ~1% of
> the time, the first byte will be zero - thus removing it doesn't change the
> number.
> 
> This change adds a non-zero byte to the start of the signature instead.
> 
> Merge internal change: 44803399
> 
> Replace calls to scoped_ptr(NULL) with calls to scoped_ptr().
> 
> Merge internal change: 44799980
> 
> Add a blank line in order to get the dependencies correct for rebuild.
> 
> Merge internal change: 44796024
> 
> Fix "large integer implicitly truncated to unsigned type"
> 
> Merge internal change: 44793986
> 
> QUIC: compress certificates.
> 
> This change causes server certificates to be compressed using three tricks:
>   1) The client can advertise sets of common certificates that the server can
>      then simply reference. This change contains "common certificate set 0",
>      which is the set of the intermediates used twice or more in the Alexa top
>      5000. It's temporary because it's missing GIAG2 which we'll want to
>      include soon.
>   2) The client can send 64-bit, FNV-1a hashes of certificates that it already
>      has and the server can reference them by hash.
>   3) Otherwise, certifciates are gzip compressed with a dictionary that
>      includes any certificates compressed using the previous two methods and a
>      1500 byte lump of common substrings. (Again, taken from the Alexa top 5000)
> 
> POKE=1
> 
> Merge internal change: 44792710
> 
> R=rch@chromium.org
> 
> Review URL: https://chromiumcodereview.appspot.com/14651009

TBR=rtenneti@chromium.org

Review URL: https://codereview.chromium.org/15018013

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@198764 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 0439abf7532921a18e63939842a54256b1f08d55