Revert "[css-flexbox] Only do the initial child layout in one place"
This reverts commit c4e77ba4dc6bd52185fefa33aaeaefab69f90f73 [formerly 43ab10d4584e6099679cd7d93c4bd32cc2cbd345].

Reason for revert: Causing build failure: error: no member named 'DisplayLockInducesSizeContainment' in 'blink::LayoutBox'

Original change's description:
> [css-flexbox] Only do the initial child layout in one place
> 
> Instead of calling Layout in both ConstructAndAppendFlexItem and
> ComputeInnerFlexBaseSize, only call it once in ConstructAndAppendFlexItem.
> 
> This has the side-effect that the scrollbar size can't change after
> we compute it in ConstructAndAppendFlexItem, thus avoiding a check failure.
> 
> This will also avoid double layouts if UpdateBlockChildDirtyBits triggers
> a layout.
> 
> The change to MainAxisContentExtentForChildIncludingScrollbar is a followup
> to https://chromium-review.googlesource.com/c/chromium/src/+/1548326; this
> now made a test fail without that change but I should have made the change
> back then.
> 
> R=​dgrogan@chromium.org
> 
> (cherry picked from commit 8750cfef8946ebef6d261c20c1bbad4b00b1bd42 [formerly 1552b481f541f870952505758cb277a5827ab0e1])
> 
> Bug: 963137, 960014
> Change-Id: I28691c5e9d30d8425f16efcc95d2430098ca11f1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1614058
> Commit-Queue: Christian Biesinger <cbiesinger@chromium.org>
> Auto-Submit: Christian Biesinger <cbiesinger@chromium.org>
> Reviewed-by: David Grogan <dgrogan@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#660621}
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1620599
> Reviewed-by: Christian Biesinger <cbiesinger@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3770@{#725}
> Cr-Branched-From: 04e619e4964cac3f22e7ef787268f756c2b6c1c7 [formerly a9eee1c7c727ef42a15d86e9fa7b77ff0e63840a]-refs/heads/master@{#652427}

TBR=cbiesinger@chromium.org,dgrogan@chromium.org

Change-Id: I56f2416d2aa761109b438dc3fd864ea9e5142fa8
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 963137, 960014
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1621867
Reviewed-by: Ben Mason <benmason@chromium.org>
Cr-Commit-Position: refs/branch-heads/3770@{#728}
Cr-Branched-From: 04e619e4964cac3f22e7ef787268f756c2b6c1c7 [formerly a9eee1c7c727ef42a15d86e9fa7b77ff0e63840a]-refs/heads/master@{#652427}

Former-commit-id: 0195988e62bf76ecb4225a8a55b90145baa30f6d