Fix BluetoothChooserDialogTest#testSelectItem in landscape
Looking at the Android CFI bot, I was seeing some failures of
testSelectItem with messages like:
java.lang.AssertionError: Not all items have a view; positions may be incorrect. expected:<2> but was:<4>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)

The problem was the phone had ended up in landscape and thus could
not show the full list.

This changes the test to support showing a subset of the items and
scrolling to the desired position.

This also changes the exemption of the constant state drawable to
N_MR1 because it was failing constantly for me with the same problem
that was previously added for O.

BUG=773043,912316

Change-Id: I2719a36deb4852a9922922d8728fde04b7c79afb
Reviewed-on: https://chromium-review.googlesource.com/c/1456692
Reviewed-by: Matthew Jones <mdjones@chromium.org>
Commit-Queue: Ted Choc <tedchoc@chromium.org>
Cr-Commit-Position: refs/heads/master@{#629734}
Former-commit-id: d1a881e9563a5288bed3f22726d3ca6954af580b