Revert "Enable warmer welcome during Assistant launch."
This reverts commit 8e5d16a13616a4e149b5f7ba0982ef121e8023fd [formerly 29dca9fe6ae866266c976809adc33c09a2ca1088].

Reason for revert:
  ../../chromeos/services/assistant/assistant_manager_service_impl.cc:27:10: fatal error: 'chromeos/services/assistant/assistant_warmer_welcome_log.pb.h' file not found
  #include "chromeos/services/assistant/assistant_warmer_welcome_log.pb.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.

https://logs.chromium.org/logs/chromium/bb/chromium.chrome/Google_Chrome_ChromeOS/59389/+/recipes/steps/compile/0/stdout

Original change's description:
> Enable warmer welcome during Assistant launch.
> 
> 1. It is guarded by a finch flag AssistantWarmerWelcome.
> 2. WW only shows 3 times.
> 
> Bug: b:112495005
> Test: Manual
> 
> Change-Id: I80cbcfd4104c17172939d36b986be65077bf0bb3
> Reviewed-on: https://chromium-review.googlesource.com/c/1355174
> Reviewed-by: Will Harris <wfh@chromium.org>
> Reviewed-by: Xiaohui Chen <xiaohuic@chromium.org>
> Reviewed-by: Xiyuan Xia <xiyuan@chromium.org>
> Commit-Queue: Yilei Li <yileili@google.com>
> Cr-Commit-Position: refs/heads/master@{#614553}

TBR=xiyuan@chromium.org,xiaohuic@chromium.org,wfh@chromium.org,dmblack@google.com,wutao@chromium.org,yileili@google.com

Change-Id: Ib5749ef1c003be49d4923c364d8499b43a2abcf5
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: b:112495005
Reviewed-on: https://chromium-review.googlesource.com/c/1366873
Reviewed-by: Dan Beam <dbeam@chromium.org>
Commit-Queue: Dan Beam <dbeam@chromium.org>
Cr-Commit-Position: refs/heads/master@{#614577}
Former-commit-id: c71812f1007dae45bce45b451c384bf9c0dbd356