Revert "Reland "Add unittests for AudioOutputStream.""
This reverts commit 1aa8af41979fefa813b7f7aeb750e4b07ac43688 [formerly f966ce658c85b635347b89f3812ddcab500d3180].

Reason for revert: Failing tests on multiple bots:

https://build.chromium.org/p/chromium.gpu.fyi/builders/Win10%20Release%20%28Intel%20HD%20630%29/builds/1074
https://build.chromium.org/p/chromium.gpu.fyi/builders/Win10%20Release%20%28NVIDIA%29/builds/3982
https://build.chromium.org/p/chromium.gpu.fyi/builders/Win7%20Debug%20%28AMD%29/builds/3565
https://build.chromium.org/p/chromium.gpu.fyi/builders/Win7%20x64%20Release%20%28NVIDIA%29/builds/13153

Failing test: AudioOutputTest.Play200HzTone

[ RUN      ] AudioOutputTest.Play200HzTone

[4244:4412:1121/055656.174:27876973:WARNING:audio_low_latency_output_win.cc(196)] Using WASAPI output with a non-optimal buffer size, glitches from back to back shared memory reads and partial fills of WASAPI output buffers may occur.  Buffer size of 4410 is not an even divisor of 441

../../media/audio/audio_output_unittest.cc(100): error: Expected: (source.callbacks()) >= (1), actual: 0 vs 1

[  FAILED  ] AudioOutputTest.Play200HzTone (315 ms)

Original change's description:
> Reland "Add unittests for AudioOutputStream."
> 
> This is a reland of 6aecad8847b870f7d90af4434308502819ca4cb3 [formerly eec981f16b43c158dc5a660714a60b3251ec13a9]
> Original change's description:
> > Add unittests for AudioOutputStream.
> > 
> > Previosly there were no cross-platforms tests for AudioOutputStream.
> > This CL adds new tests that will run on all platforms. The tests
> > are based on Windows-specific tests in media/audio/win.
> > 
> > Bug: 737802
> > Cq-Include-Trybots: master.tryserver.chromium.android:android_optional_gpu_tests_rel;master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel
> > Change-Id: I2accac0d7dc5e5d5ac813923ec6b83c0af6c9da6
> > Reviewed-on: https://chromium-review.googlesource.com/702688
> > Commit-Queue: Sergey Ulanov <sergeyu@chromium.org>
> > Reviewed-by: Olga Sharonova <olka@chromium.org>
> > Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#509522}
> 
> Bug: 737802
> Change-Id: I6c637e731810574fabe0f6cd8d4dcc7d40380288
> Cq-Include-Trybots: master.tryserver.chromium.android:android_optional_gpu_tests_rel;master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel
> Reviewed-on: https://chromium-review.googlesource.com/728400
> Commit-Queue: Sergey Ulanov <sergeyu@chromium.org>
> Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
> Reviewed-by: Olga Sharonova <olka@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#517952}

TBR=dalecurtis@chromium.org,sergeyu@chromium.org,olka@chromium.org

Change-Id: I216c41d3f23de8b406435a1e1700a8c4a72eca98
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 737802
Cq-Include-Trybots: master.tryserver.chromium.android:android_optional_gpu_tests_rel;master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel
Reviewed-on: https://chromium-review.googlesource.com/782019
Reviewed-by: Jamie Madill <jmadill@chromium.org>
Commit-Queue: Jamie Madill <jmadill@chromium.org>
Cr-Commit-Position: refs/heads/master@{#518262}
Former-commit-id: 133582909af148b44fc286c887b0133161e97dea