Revert of Add the Play Store app search to the launcher. (patchset #17 id:300001 of https://codereview.chromium.org/2929273002/ )
Reason for revert:
Linux ChromiumOS Builder (dbg) is failing compile:

../../chrome/browser/ui/app_list/search/arc/arc_playstore_search_result.cc:0: error: undefined reference to 'app_list::kIcBadgeInstantIcon'
../../chrome/browser/ui/app_list/search/arc/arc_playstore_search_result.cc:0: error: undefined reference to 'app_list::kIcBadgePlayIcon'

Original issue's description:
> Add the Play Store app search to the launcher.
>
> Bug=736552
>
> Review-Url: https://codereview.chromium.org/2929273002
> Cr-Commit-Position: refs/heads/master@{#482130}
> Committed: https://chromium.googlesource.com/chromium/src/+/c38d2ec9a2d039d36b499345fa5932d2f7a7098b [formerly fa1bfdf6d5fb0952a524f4ca048ff104fdbdb2dd]

TBR=lhchavez@chromium.org,xiyuan@chromium.org,hejq@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
Bug=736552

Review-Url: https://codereview.chromium.org/2954223002
Cr-Commit-Position: refs/heads/master@{#482136}

Former-commit-id: 1fef8cf8bc356c704eb27eee979c45895e6f4d69