Revert "[PE] Don't reparse "restart" and "fill" repeatedly"
This reverts commit 09b00089491e85e3a35cce73d00970df32597785 [formerly f2ead72d0feb6aec5347016ee852e84b7c72aee6].

Reason for revert: Appears to be cause of compile failure on WIN MSVC64 (dbg):

https://ci.chromium.org/buildbot/chromium.win/WinMSVC64%20(dbg)/4171

../..\base/logging.h(778): error C2220: warning treated as error - no 'object' file generated
../../third_party/WebKit/Source/core/svg/animation/SVGSMILElement.cpp(1095): note: see reference to function template instantiation 'std::string *logging::CheckEQImpl<unsigned int,blink::SVGSMILElement::ActiveState>(const t1 &,const t2 &,const char *)' being compiled
        with
        [
            t1=unsigned int,
            t2=blink::SVGSMILElement::ActiveState
        ]
../..\base/logging.h(778): warning C4389: '==': signed/unsigned mismatch
../..\base/logging.h(779): warning C4389: '!=': signed/unsigned mismatch
../../third_party/WebKit/Source/core/svg/animation/SVGSMILElement.cpp(1101): note: see reference to function template instantiation 'std::string *logging::CheckNEImpl<unsigned int,blink::SVGSMILElement::ActiveState>(const t1 &,const t2 &,const char *)' being compiled
        with
        [
            t1=unsigned int,
            t2=blink::SVGSMILElement::ActiveState
        ]

Original change's description:
> [PE] Don't reparse "restart" and "fill" repeatedly
> 
> Rather than doing an attribute lookup in GetRestart() and Fill(), just
> map the attributes in ParseAttribute.
> Also get rid of the static AtomicStrings.
> 
> Noticed while looking at the referenced bug.
> 
> Bug: 823473
> Cq-Include-Trybots: master.tryserver.blink:linux_trusty_blink_rel;master.tryserver.chromium.linux:linux_layout_tests_slimming_paint_v2
> Change-Id: I19d1244c6034430c30e65c09e20c8f04552b1e5f
> Reviewed-on: https://chromium-review.googlesource.com/978246
> Reviewed-by: Philip Rogers <pdr@chromium.org>
> Commit-Queue: Fredrik Söderquist <fs@opera.com>
> Cr-Commit-Position: refs/heads/master@{#545686}

TBR=pdr@chromium.org,fs@opera.com,schenney@chromium.org

Change-Id: I78e7691c5753d6d5ef25249d0cb3a5fff0b517c6
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 823473
Cq-Include-Trybots: master.tryserver.blink:linux_trusty_blink_rel;master.tryserver.chromium.linux:linux_layout_tests_slimming_paint_v2
Reviewed-on: https://chromium-review.googlesource.com/979413
Reviewed-by: Stephen McGruer <smcgruer@chromium.org>
Commit-Queue: Stephen McGruer <smcgruer@chromium.org>
Cr-Commit-Position: refs/heads/master@{#545687}
Former-commit-id: 3e18a7bb42ff4d92525c60b74963f9554d956b5f