Revert "Reland "Reland "[GRC] Add heuristics UKM and refactor MetricsCollector."""
This reverts commit f460770ad081c3bf741a71e9a5f18f27a6816850 [formerly f28e17610a74d58803586e7296b7bf5049619f87].

Reason for revert: still fails on Win7 Debug

[ RUN      ] MetricsCollectorTest.FromBackgroundedToFirstNonPersistentNotificationCreatedUMA5MinutesTimeout
../../services/resource_coordinator/coordination_unit/metrics_collector_unittest.cc(33): error: Value of: metrics_collector_->ShouldReportMetrics( CoordinationUnitImpl::ToWebContentsCoordinationUnit(web_contents_cu))
  Actual: false
Expected: true
../../base/test/histogram_tester.cc(72): error:       Expected: count
      Which is: 1
To be equal to: 0
Histogram "TabManager.Heuristics.FromBackgroundedToFirstNonPersistentNotificationCreated" does not exist.
[  FAILED  ] MetricsCollectorTest.FromBackgroundedToFirstNonPersistentNotificationCreatedUMA5MinutesTimeout (2 ms)


Original change's description:
> Reland "Reland "[GRC] Add heuristics UKM and refactor MetricsCollector.""
> 
> This is a reland of 7bb05048773b87b1994009a87830d217c9457ae1 [formerly 6bc2eb1c983d21de6899c44a0382104ca83a5010]
> Original change's description:
> > Reland "[GRC] Add heuristics UKM and refactor MetricsCollector."
> > 
> > This is a reland of dd935441f5c266eb8d1e25a0e2d3fb105b3dfcfd [formerly e31b0b47faf7f774b7ad91d33b828218cc375c17]
> > Original change's description:
> > 
> > TBR=chrisha@chromium.org,dcheng@chromium.org,holte@chromium.org
> > > [GRC] Add heuristics UKM and refactor MetricsCollector.
> > > 
> > > This patch:
> > > 1. adds heuristics UKM;
> > > 2. rafactors MetricsCollector to unify background tabs metrics report;
> > > 3. moved metrics report 5-minutes timeout logic to MetricsCollector;
> > > 4. adds more unit tests.
> > > 
> > > BUG=731270, 753486
> > > 
> > > Change-Id: Ica08674bf6b95d88f8de571ef025a7eaf58515d7
> > > Reviewed-on: https://chromium-review.googlesource.com/627594
> > > Reviewed-by: Chris Hamilton <chrisha@chromium.org>
> > > Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> > > Reviewed-by: Steven Holte <holte@chromium.org>
> > > Commit-Queue: lpy <lpy@chromium.org>
> > > Cr-Commit-Position: refs/heads/master@{#497900}
> > 
> > Bug: 731270, 753486
> > Change-Id: I43c99c0cdc7c7d3431f08fae86cb10d6d87d99fa
> > Reviewed-on: https://chromium-review.googlesource.com/640010
> > Reviewed-by: lpy <lpy@chromium.org>
> > Commit-Queue: lpy <lpy@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#498395}
> 
> TBR=chrisha@chromium.org,dcheng@chromium.org,holte@chromium.org
> 
> Bug: 731270, 753486
> Change-Id: I65f2a5bc86e8ddd4af4b1739c306b6d1bc70b4b1
> Reviewed-on: https://chromium-review.googlesource.com/643568
> Commit-Queue: lpy <lpy@chromium.org>
> Reviewed-by: lpy <lpy@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#498965}

TBR=dcheng@chromium.org,chrisha@chromium.org,holte@chromium.org,lpy@chromium.org

Change-Id: I2a125eef30d2186f3e3a962d053bfab8b0596569
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 731270, 753486
Reviewed-on: https://chromium-review.googlesource.com/646532
Reviewed-by: Mike Wittman <wittman@chromium.org>
Commit-Queue: Mike Wittman <wittman@chromium.org>
Cr-Commit-Position: refs/heads/master@{#499045}
Former-commit-id: 2f3be9b8cb16c72fcdb0b463af0be3b1b49151cb