Revert of Add new, unused methods to SpdyFramerVisitorInterface. (patchset #3 id:40001 of https://codereview.chromium.org/1413683005/ )
Reason for revert:
Breaks compilation of flip_in_mem_edsm_server_unittests target.

https://build.chromium.org/p/chromium/builders/Linux/builds/68316/steps/compile/logs/stdio

FAILED: /b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/net/tools/flip_server/flip_in_mem_edsm_server_unittests.spdy_interface_test.o.d -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=247874-1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_X11=1 -DUSE_CLIPBOARD_AURAX11=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DENABLE_TOPCHROME_MD=1 -DUSE_UDEV -DDONT_EMBED_BUILD_METADATA -DFIELDTRIAL_TESTING_ENABLED -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=0 -DUNIT_TEST -DGTEST_HAS_RTTI=0 -DUSE_LIBPCI=1 -DUSE_OPENSSL=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../testing/gtest/include -I../../testing/gmock/include -I../../third_party/boringssl/src/include -I../.. -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /b/build/slave/Linux/build/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -momit-leaf-frame-pointer -mstack-alignment=16 -mstackrealign -fcolor-diagnostics -B/b/build/slave/Linux/build/src/third_party/binutils/Linux_x64/Release/bin -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-bitfield-width -pthread -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/nss -I/usr/include/nspr -Wno-header-guard -msse2 -mfpmath=sse -mmmx -m32 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare -std=gnu++11  -c ../../net/tools/flip_server/spdy_interface_test.cc -o obj/net/tools/flip_server/flip_in_mem_edsm_server_unittests.spdy_interface_test.o
../../net/tools/flip_server/spdy_interface_test.cc:165:36: error: allocating an object of abstract class type 'net::(anonymous namespace)::SpdyFramerVisitor'
    spdy_framer_visitor_.reset(new SpdyFramerVisitor);
                                   ^
../../net/spdy/buffered_spdy_framer.h:86:40: note: unimplemented pure virtual method 'OnHeaderFrameStart' in 'SpdyFramerVisitor'
  virtual SpdyHeadersHandlerInterface* OnHeaderFrameStart(
                                       ^
../../net/spdy/buffered_spdy_framer.h:92:16: note: unimplemented pure virtual method 'OnHeaderFrameEnd' in 'SpdyFramerVisitor'
  virtual void OnHeaderFrameEnd(SpdyStreamId stream_id, bool end_headers) = 0;
               ^
1 error generated.

Original issue's description:
> Add new, unused methods to SpdyFramerVisitorInterface.
>
> The new methods will allow SpdyFramer to pass headers to visitors through a
> SpdyHeadersHandlerInterface.
>
> There are so many descendants of SpdyFramerVisitorInterface that I thought it
> was best to start with the interface change, and add an unused stub
> implementation everywhere.
>
> This CL lands server change 106411694 by birenroy.
>
> BUG=488484
>
> Committed: https://crrev.com/4ee695892a52c817183c7ffeaa4c051c1e576f00 [formerly 5d0c7230e6d1e8da9597c5a967a7b92638a58442]
> Cr-Commit-Position: refs/heads/master@{#357084}
>
> Committed: https://crrev.com/f0f84f45717cc6e16621dbc8482057cf40360f37 [formerly 4a9943c8a656e6a3397aae7b29f09b694a0066aa]
> Cr-Commit-Position: refs/heads/master@{#357345}

TBR=rch@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=488484

Review URL: https://codereview.chromium.org/1419923003

Cr-Commit-Position: refs/heads/master@{#357348}

Former-commit-id: 16148cc245dbad6799f9bcec4b4f7d2a3d20a823