Revert "Don't warn about modules in the same directory as Chrome"
This reverts commit 4ae9de61b0ea2d4021c330e61aeafdc6e00c6c0a [formerly 12164db3517c1006b8ee39120c5bc38f82b9d79d].

Reason for revert: 
Compilation error below on official build.

Please remove |#if !defined(OFFICIAL_BUILD)| at L30.

30 #if !defined(OFFICIAL_BUILD)
31 #include "base/base_paths.h"
32 #include "base/path_service.h"
33 #endif

ompatible_applications_updater_win.cc /Foobj/chrome/browser/browser/incompatible_applications_updater_win.obj /Fd"obj/chrome/browser/browser_cc.pdb"
../../chrome/browser/conflicts/incompatible_applications_updater_win.cc(332,13):  error: no member named 'PathService' in namespace 'base'
  if (base::PathService::Get(base::DIR_EXE, &exe_path) &&
      ~~~~~~^
../../chrome/browser/conflicts/incompatible_applications_updater_win.cc(332,36):  error: no member named 'DIR_EXE' in namespace 'base'
  if (base::PathService::Get(base::DIR_EXE, &exe_path) &&
                             ~~~~~~^



Original change's description:
> Don't warn about modules in the same directory as Chrome
> 
> Bug: 876096
> Change-Id: I85a7d7d5529270a829d9849a8bb638d9d02b7813
> Reviewed-on: https://chromium-review.googlesource.com/1182341
> Commit-Queue: Patrick Monette <pmonette@chromium.org>
> Reviewed-by: Chris Hamilton <chrisha@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#584586}

TBR=chrisha@chromium.org,pmonette@chromium.org

Change-Id: Id5c5647be399362929de2a7773bd581dbbe41633
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 876096
Reviewed-on: https://chromium-review.googlesource.com/1182841
Reviewed-by: Yoshifumi Inoue <yosin@chromium.org>
Commit-Queue: Yoshifumi Inoue <yosin@chromium.org>
Cr-Commit-Position: refs/heads/master@{#584589}
Former-commit-id: 1e51ea5348a475e325eaed7e144a49fe960c810d