Revert of [libfuzzer] proto-based renderer fuzzer draft (patchset #5 id:80001 of https://codereview.chromium.org/2727123003/ )
Reason for revert:
https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium%2FWin%2F52705%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

FAILED: obj/content/test/fuzzer/html_tree_proto/html_tree.pb.obj
ninja -t msvc -e environment.x86 -- C:\b\c\goma_client/gomacc.exe "C:\b\depot_tools\win_toolchain\vs_files\d3cb0e37bdd120ad0ac4650b674b09e81be45616\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/content/test/fuzzer/html_tree_proto/html_tree.pb.obj.rsp /c gen/content/test/fuzzer/html_tree.pb.cc /Foobj/content/test/fuzzer/html_tree_proto/html_tree.pb.obj /Fd"obj/content/test/fuzzer/html_tree_proto_cc.pdb"
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(171): error C2220: warning treated as error - no 'object' file generated
c:\b\c\b\win_archive\src\out\release\gen\content\test\fuzzer\html_tree.pb.cc(171): warning C4125: decimal digit terminates octal escape sequence

Original issue's description:
> [libfuzzer] proto-based renderer fuzzer draft.
>
> This is a port of tree fuzzer to libprotobuf-mutator library.
>
> BUG=
>
> Review-Url: https://codereview.chromium.org/2727123003
> Cr-Commit-Position: refs/heads/master@{#455874}
> Committed: https://chromium.googlesource.com/chromium/src/+/7c6797ab4a8f9c45b9aadb0f6cf443aea122a877 [formerly a9e5063b0956891685f847bf4cb11bccfbacde30]

TBR=vitalybuka@google.com,vitalybuka@chromium.org,aizatsky@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review-Url: https://codereview.chromium.org/2741853002
Cr-Commit-Position: refs/heads/master@{#455888}

Former-commit-id: 42ada11652ece20e9e564ab45552985ab9fa6308