LazilyDeallocatedDeque: Include <memory> for std::unique_ptr
IWYU. This fixes the libstdc++ build after commit 68d360546 ("Add
LazilyDeallocatedDeque a custom deque for TaskQueueManager"):

    In file included from ../../third_party/blink/renderer/platform/scheduler/base/lazily_deallocated_deque_unittest.cc:5:0:
    ../../third_party/blink/renderer/platform/scheduler/base/lazily_deallocated_deque.h:302:10: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
         std::unique_ptr<Ring> next_;
              ^~~~~~~~~~
    ../../third_party/blink/renderer/platform/scheduler/base/lazily_deallocated_deque.h:354:8: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
       std::unique_ptr<Ring> head_;
            ^~~~~~~~~~

Bug: 819294
Change-Id: I3a49f212f036905d89088749431b09513b9c33b8
Reviewed-on: https://chromium-review.googlesource.com/1090717
Reviewed-by: Alex Clarke <alexclarke@chromium.org>
Reviewed-by: Alexander Timin <altimin@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#565262}
Former-commit-id: 23c2a004082f767e4a5200df253c127a31fc9822