gob: fix index error in SetReview for non-existent CLs
If you try to run a review related command on a CL that doesn't exist,
you end up getting a python error:
$ gerrit verify 161865 +1
gerrit: Unhandled exception:
Traceback (most recent call last):
  File "/usr/local/google/home/vapier/chromiumos/chromite/bin/gerrit", line 130, in <module>
    commandline.ScriptWrapperMain(FindTarget)
  File "/usr/local/src/chromiumos/chromite/lib/commandline.py", line 557, in ScriptWrapperMain
    ret = target(argv[1:])
  File "/usr/local/src/chromiumos/chromite/scripts/gerrit.py", line 351, in main
    functor(opts, *args)
  File "/usr/local/src/chromiumos/chromite/scripts/gerrit.py", line 222, in UserActVerify
    opts.gerrit.SetReview(idx, labels={'Verified': num})
  File "/usr/local/src/chromiumos/chromite/lib/gerrit.py", line 321, in SetReview
    msg=msg, labels=labels, notify='ALL')
  File "/usr/local/src/chromiumos/chromite/lib/gob_util.py", line 414, in SetReview
    if ('labels' not in response or key not in response['labels'] or
TypeError: argument of type 'NoneType' is not iterable

Have the gerrit logic check for an empty result set and raise an error
when that happens.  Now we get:
$ gerrit ready 161865 +1
17:26:02: ERROR: (404) CL 161865 not found in chromium-review.googlesource.com

BUG=None
TEST=`gerrit ready 161865 +1` presents a usable message
TEST=`./buildbot/run_tests` passes

Change-Id: I2d0e5794cf07f3d69d63e916d0d255261187c70d
Reviewed-on: https://chromium-review.googlesource.com/199322
Reviewed-by: David James <davidjames@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>