Revert of Image Capture: wire setPhotoOptions() for Win (patchset #3 id:80001 of https://codereview.chromium.org/2873143002/ )
Reason for revert:
/video_capture_device_win.obj
ninja -t msvc -e environment.x86 -- C:\b\c\goma_client/gomacc.exe "C:\b\depot_tools\win_toolchain\vs_files\d3cb0e37bdd120ad0ac4650b674b09e81be45616\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/media/capture/capture_lib/video_capture_device_win.obj.rsp /c ../../media/capture/video/win/video_capture_device_win.cc /Foobj/media/capture/capture_lib/video_capture_device_win.obj /Fd"obj/media/capture/capture_lib_cc.pdb"
c:\b\c\b\win_chrome\src\media\capture\video\win\video_capture_device_win.cc(637): error C2220: warning treated as error - no 'object' file generated
c:\b\c\b\win_chrome\src\media\capture\video\win\video_capture_device_win.cc(637): warning C4189: 'hr': local variable is initialized but not referenced
c:\b\c\b\win_chrome\src\media\capture\video\win\video_capture_device_win.cc(644): warning C4189: 'hr': local variable is initialized but not referenced
c:\b\c\b\win_chrome\src\media\capture\video\win\video_capture_device_win.cc(654): warning C4189: 'hr': local variable is initialized but not referenced
c:\b\c\b\win_chrome\src\media\capture\video\win\video_capture_device_win.cc(661): warning C4189: 'hr': local variable is initialized but not referenced
c:\b\c\b\win_chrome\src\media\capture\video\win\video_capture_device_win.cc(670): warning C4189: 'hr': local variable is initialized but not referenced
c:\b\c\b\win_chrome\src\media\capture\video\win\video_capture_device_win.cc(676): warning C4189: 'hr': local variable is initialized but not referenced
c:\b\c\b\win_chrome\src\media\capture\video\win\video_capture_device_win.cc(681): warning C4189: 'hr': local variable is initialized but not referenced
c:\b\c\b\win_chrome\src\media\capture\video\win\video_capture_device_win.cc(686): warning C4189: 'hr': local variable is initialized but not referenced
c:\b\c\b\win_chrome\src\media\capture\video\win\video_capture_device_win.cc(691): warning C4189: 'hr': local variable is initialized but not referenced

Original issue's description:
> Image Capture: wire setPhotoOptions() for Win
>
> This CL wires the photo capabilities setPhotoOptions() method:
>
> - |camera_control_| and |video_control_| are made member
>  variables, which forces trivial updates to the lambdas.
>
> - most of the controls are straightforward except white
> balance and exposure: those have a 'manual' and 'auto'
> that enable the use of |color_temperature| and
> |exposure_compensation|, resp.  Since either of them can
> be configured in subsequent setPhotoOptions() cycles, we need
> member flags to keep the manual/auto state.
>
>
>
> BUG=657128
>
> Review-Url: https://codereview.chromium.org/2873143002
> Cr-Commit-Position: refs/heads/master@{#471554}
> Committed: https://chromium.googlesource.com/chromium/src/+/9f1fc00151c494973cb138389b661e8a3a8776ac [formerly 86adb2c88ba82194458ac09d078a00616c0b22dd]

TBR=robliao@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=657128

Review-Url: https://codereview.chromium.org/2876303002
Cr-Commit-Position: refs/heads/master@{#471559}

Former-commit-id: cd356540e646a136d9ac96c49920b0611227fc29