Reland "cros: Add a double separator above context menu notifications"
This reverts commit b5655164ca9312de13dec748ae19eaf9e8f171ce [formerly f69edefd4b309c07c800663227af7120f6dea63f].

Reason for revert: Bug is fixed by adding VIEWS_EXPORT to MenuSeparator.

https://chromium-review.googlesource.com/c/chromium/src/+/1129999

Original change's description:
> Revert "cros: Add a double separator above context menu notifications"
> 
> This reverts commit 03a00f6dee0aff1e1470c201efcbda36fff04813 [formerly 1c822163619f765c71f5b7a21d399e727749be72].
> 
> Reason for revert: 
> 
> Linker failures:
> obj/ash/app_menu/app_menu/notification_menu_view.o:notification_menu_view.cc:function ash::NotificationMenuView::NotificationMenuView(ash::NotificationItemView::Delegate*, message_center::SlideOutController::Delegate*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&): error: undefined reference to 'vtable for views::MenuSeparator'
> ../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
> 
> Bug: 861885
> 
> Original change's description:
> > cros: Add a double separator above context menu notifications
> > 
> > Add and remove a double separator with NOTIFICATION_CONTAINER.
> > 
> > Bug: 843761
> > Change-Id: I45fb095079aaaf108a9a18958ab4e431072e588d
> > Reviewed-on: https://chromium-review.googlesource.com/1121243
> > Commit-Queue: Alex Newcomer <newcomer@chromium.org>
> > Reviewed-by: Michael Wasserman <msw@chromium.org>
> > Reviewed-by: James Cook <jamescook@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#573418}
> 
> TBR=jamescook@chromium.org,msw@chromium.org,newcomer@chromium.org
> 
> Change-Id: I10ce18a75e80116fa8d7a530d18e979a2dfbb395
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 843761
> Reviewed-on: https://chromium-review.googlesource.com/1129661
> Reviewed-by: Alex Newcomer <newcomer@chromium.org>
> Commit-Queue: Alex Newcomer <newcomer@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#573429}

TBR=jamescook@chromium.org,msw@chromium.org,newcomer@chromium.org

Change-Id: I70f5742583a5531d43ea5ff5b6c2815e691506da
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 861885, 843761
Reviewed-on: https://chromium-review.googlesource.com/1130140
Reviewed-by: Alex Newcomer <newcomer@chromium.org>
Commit-Queue: Alex Newcomer <newcomer@chromium.org>
Cr-Commit-Position: refs/heads/master@{#573480}
Former-commit-id: d2e1cf4163ed83cb736f5a585f70279f5b054034