Fix regression in isolate.py archive introduced in cfb608559d.
It would cause:
  ValueError: on_error.report_on_exception_exit() was called twice

R=vadimsh@chromium.org
BUG=

Review URL: https://codereview.appspot.com/105540045