Revert 229640 "Break the dependency BackTexture had on the entir..."
Broke compilation on linux chromeos:

../../gpu/command_buffer/service/gles2_cmd_decoder.cc:5760:39:error: too few arguments to function ‘void gpu::gles2::RestoreCurrentTexture2DBindings(gpu::gles2::ContextState*)’


> Break the dependency BackTexture had on the entire Decoder.
> 
> BUG=
> 
> Review URL: https://codereview.chromium.org/27762003

TBR=kloveless@chromium.org

Review URL: https://codereview.chromium.org/30823002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@229642 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: be814b0b501c167705ab9b1c221bb746099adbfb