Revert "Reland "Start gpu channel and compositor mojo pipe collection eagerly""
This reverts commit 0cc5f1954ad14012d5d383039badf8beb97f7727 [formerly eacb6ed3531606cf878fdcd635fc251c686e30b2].

Reason for revert: Makes ChromeVoxLiveRegionsUnitTests flaky:

https://crbug.com/909973
https://crbug.com/909984

https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/linux-chromeos-rel/16620

[ RUN      ] ChromeVoxLiveRegionsUnitTest.AddToLiveRegion
[23526:23526:1128/180604.087820:WARNING:chrome_browser_main_chromeos.cc(544)] Running as stub user with profile dir: test-user
[23526:23526:1128/180604.176618:WARNING:easy_unlock_service_regular.cc(523)] EasyUnlockServiceRegular::IsInLegacyHostMode: DeviceSyncClient not ready. Returning false.
[23526:23526:1128/180604.197349:INFO:remote_commands_service.cc(38)] Fetching remote commands.
[23526:23526:1128/180604.222292:WARNING:remote_commands_service.cc(40)] Client is not registered.
[23526:23526:1128/180604.222531:INFO:remote_commands_invalidator.cc(32)] Initialize RemoteCommandsInvalidator.
[23526:23526:1128/180604.222602:INFO:remote_commands_invalidator.cc(57)] Starting RemoteCommandsInvalidator.
[23526:23526:1128/180604.222654:INFO:remote_commands_invalidator.cc(123)] RemoteCommandsInvalidator ReloadPolicyData.
[23526:23526:1128/180604.222699:INFO:remote_commands_invalidator.cc(167)] Unregister RemoteCommandsInvalidator.
[23526:23526:1128/180604.245434:WARNING:wallpaper_controller_client.cc(358)] Cannot get wallpaper files id in RemovePolicyWallpaper. This should never happen under normal circumstances.
[23526:23526:1128/180604.326719:ERROR:gpu_interface_provider.cc(87)] Not implemented reached in virtual void content::GpuInterfaceProvider::RegisterOzoneGpuInterfaces(service_manager::BinderRegistry *)
[23526:23526:1128/180604.607132:INFO:CONSOLE(1281)] "Running TestCase ChromeVoxLiveRegionsUnitTest.AddToLiveRegion", source: file:///b/s/w/ir/chrome/test/data/webui/test_api.js (1281)
[23526:23526:1128/180604.617409:INFO:CONSOLE(53)] "done setup", source: file:///b/s/w/ir/chrome/browser/resources/chromeos/chromevox/testing/tester.js (53)
[23526:23526:1128/180604.636340:ERROR:web_ui_test_handler.cc(100)] Failed: RUN_TEST_F("ChromeVoxLiveRegionsUnitTest","AddToLiveRegion")
AssertionError: expected undefined to equal 'Eric'
    at Function.assert.strictEqual (file:///b/s/w/ir/third_party/chaijs/chai.js:2277:32)
    at assertEquals (file:///b/s/w/ir/chrome/test/data/webui/test_api.js:923:15)
    at ChromeVoxLiveRegionsUnitTest.<anonymous> (file:///b/s/w/ir/out/Release/test_data/chrome/browser/resources/chromeos/chromevox/chromevox/injected/live_regions_test.unitjs:157:7)
    at ChromeVoxLiveRegionsUnitTest.<anonymous> (file:///b/s/w/ir/chrome/browser/resources/chromeos/chromevox/testing/chromevox_unittest_base.js:123:12)
    at CallbackHelper.<anonymous> (file:///b/s/w/ir/chrome/browser/resources/chromeos/chromevox/testing/callback_helper.js:32:16)
    at CallFunctionAction.invoke (file:///b/s/w/ir/chrome/test/data/webui/test_api.js:1430:22)
    at RunAllAction.invoke (file:///b/s/w/ir/chrome/test/data/webui/test_api.js:1591:35)
    at file:///b/s/w/ir/chrome/browser/resources/chromeos/chromevox/testing/callback_helper.js:42:14
    at file:///b/s/w/ir/chrome/browser/resources/chromeos/chromevox/chromevox/injected/event_watcher.js:319:59
gen/chrome/browser/resources/chromeos/chromevox/chromevox/injected/live_regions_test-gen.cc:1442: Failure
Value of: RunJavascriptTestF( true, "ChromeVoxLiveRegionsUnitTest", "AddToLiveRegion")
  Actual: false
Expected: true

Original change's description:
> Reland "Start gpu channel and compositor mojo pipe collection eagerly"
> 
> This is a reland of 13eec8730d51d25b38f4205790b3520cecf34e36 [formerly 66794d00db74fff08d3c7944bab7337494beb544]
> 
> In this reland we revert changes to RenderThreadImpl and mus to make
> LayerTreeFrameSink creation asynchronous again.
> 
> Then in RenderWidget we must remember that a warmup is underway, we do
> so with a bool and a WeakPtrFactory. If it is aborted, we reset the bool
> and invalidate the WeakPtrFactory.
> 
> If a request for a frame sink beats the warmup completing, we save
> the callback and run that instead of saving the frame sink on
> RenderWidget when the warmup completes.
> 
> This ignores some weird weird corner cases like where warmup is
> aborted then we start another warmup or unfreeze the widget or something
> and will just make redundant requests. Since these are so rare they
> are not worth adding complexity for.
> 
> Original change's description:
> > Start gpu channel and compositor mojo pipe collection eagerly
> >
> > When a RenderWidget is frozen, its compositor is stopped. However when
> > the main frame is being navigated, we want to start requesting mojo
> > pipes for the gpu and display compositor immediately so that it can
> > happen in parallel with the navigation loading.
> >
> > Previously, we just always did this when creating a RenderWidget, and
> > left them active when freezing the RenderWidget. After d87589019ae8bc [formerly 678f025f7cde75]
> > however, we don't, and this causes time-to-first-pixels regressions
> > on navigation.
> >
> > So we add a WarmupCompositor() method to RenderWidget, and call this
> > from RenderFrameImpl::CreateFrame() when it makes the provisional
> > frame, and the WebFrameWidget, since we expect to make use of the
> > main frame RenderWidget shortly.
> >
> > Then, if RenderFrameImpl::FrameDetached() occurs, due to the
> > navigation failing, we will AbortWarmupCompositor() to drop the
> > mojo pipes instead of holding onto them indefinitely.
> >
> > This recovers the loading regressions introduced, while also not
> > allocating mojo channels for frozen RenderWidgets indefinitely.
> >
> > In order to do this reasonably, we drop the "callback" from the
> > request to RenderThreadImpl::RequestNewLayerTreeFrameSink so that
> > it always returns something immediately. This way RenderWidget
> > does not need to worry about having a task run to collect the
> > new frame sink, and ordering with tasks from the compositor to
> > collect it.
> >
> > R=piman@chromium.org
> >
> > Change-Id: I6007e26e1622006652ce3619cdd080539d11e7b0
> > Bug: 905191
> > Reviewed-on: https://chromium-review.googlesource.com/c/1341073
> > Commit-Queue: danakj <danakj@chromium.org>
> > Reviewed-by: danakj <danakj@chromium.org>
> > Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> > Reviewed-by: Antoine Labour <piman@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#610909}
> 
> Bug: 905191
> Change-Id: I6cb65e08a832a969156b96bece0f2e12eccd5b60
> Reviewed-on: https://chromium-review.googlesource.com/c/1351938
> Commit-Queue: danakj <danakj@chromium.org>
> Reviewed-by: danakj <danakj@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Reviewed-by: Antoine Labour <piman@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#611838}

TBR=danakj@chromium.org,dcheng@chromium.org,sergeyu@chromium.org,piman@chromium.org

Change-Id: I68e348f7fac337580bf3f79a29f618ac3ce3c6d6
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 905191
Reviewed-on: https://chromium-review.googlesource.com/c/1354725
Reviewed-by: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Commit-Queue: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Cr-Commit-Position: refs/heads/master@{#612035}
Former-commit-id: 20230dcf4bf803efc81ef997d101777a81f6c90a