Revert "Expand TLS 1.3 handshake 0-RTT UMA detail"
This reverts commit 513295039b51c0a69337d2f4a36bb31a976b2a63 [formerly ef7a869ac889444d76752283c2317737d0112ee8].

Reason for revert: Broke https://ci.chromium.org/p/chromium/builders/ci/Win%207%20Tests%20x64%20%281%29/59576:

[ RUN      ] SSLClientSocketTest.EarlyDataReasonReadServerHello
[4260:5836:1002/055310.421:661881:WARNING:embedded_test_server.cc(238)] Request not handled. Returning 404: /
[4260:5836:1002/055310.437:661896:WARNING:embedded_test_server.cc(238)] Request not handled. Returning 404: /
../../net/socket/ssl_client_socket_unittest.cc(5922): error: Value of: MakeHTTPRequest(sock_.get())
Expected: net::OK
  Actual: -103, net::ERR_CONNECTION_ABORTED

../../base/test/metrics/histogram_tester.cc(202): error: Expected equality of these values:
  expected_count
    Which is: 1
  actual_count
    Which is: 0
Histogram "Net.SSLHandshakeEarlyDataReason" does not have the right number of samples (1) in the expected bucket (2). It has (0).

../../base/test/metrics/histogram_tester.cc(217): error: Expected equality of these values:
  expected_count
    Which is: 1
  actual_count
    Which is: 0
Histogram "Net.SSLHandshakeEarlyDataReason" does not have the right total number of samples (1). It has (0).

Original change's description:
> Expand TLS 1.3 handshake 0-RTT UMA detail
> 
> This commit extends metrics coverage to provide more descriptive
> logging of TLS 1.3 handshakes' 0-RTT state, by logging the
> ssl_early_data_reason computed in BoringSSL. This records whether
> TLS 1.3 early data handshake attempts succeed and, if they fail,
> why.
> 
> R=​csharrison@chromium.org,davidben@chromium.org
> 
> Bug: 1000659
> Test: expanded prior metrics unittests to cover new cases
> Change-Id: Iaeba249c2be3ddb23900a51f9d223580481421f0
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1784159
> Commit-Queue: David Van Cleve <davidvc@chromium.org>
> Reviewed-by: David Benjamin <davidben@chromium.org>
> Reviewed-by: Charlie Harrison <csharrison@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#701978}

TBR=davidben@chromium.org,csharrison@chromium.org,davidvc@chromium.org

Change-Id: If78bf1c72917bea3a2453e3831515fa65982625f
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1000659
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1834948
Reviewed-by: Jeffrey Yasskin <jyasskin@chromium.org>
Commit-Queue: Jeffrey Yasskin <jyasskin@chromium.org>
Cr-Commit-Position: refs/heads/master@{#702113}

Former-commit-id: 55cc2a29af28cc48c838e2e4deb87597841f347e