Reland "Reland "Exclude unused java classes from gvr_common_java aar""
This reverts commit d3aae710940f4953f44b0ffc653dd70765c75585 [formerly 1ee268dfe9c0fad641c388f438fcefbb5b8db0c6].

Original change's description:
> Revert "Reland "Exclude unused java classes from gvr_common_java aar""
> 
> This reverts commit 8de4da2c72c47e5bd6687b0dcbf15a5e4c658809 [formerly 03667272d4eecebc55ea2a8606d67a123eba04ea].
> 
> Reason for revert: Causing crashes of unknown origin on K https://chromium-swarm.appspot.com/task?id=3c16a11a3d0f5b10&refresh=10&show_raw=1 (occurred with original CL as well)
> 
> Original change's description:
> > Reland "Exclude unused java classes from gvr_common_java aar"
> > 
> > This reverts commit 1ccefe753295445de678253a47a0ee60eefbbb6f [formerly f04d3bde73a80e4c882590a699aa5276f8d973f9].
> > 
> > Original change's description:
> > > Revert "Exclude unused java classes from gvr_common_java aar"
> > > 
> > > This reverts commit 4dfe614f31b51e2bd9d0731bfecf3162388f2b26 [formerly dbc48ca4d60683e289f10990ab985c288b7d94dc].
> > > 
> > > Reason for revert: Getting NoClassDefFoundError on Nougat https://chromium-swarm.appspot.com/task?id=3c01bdd86290b710&refresh=10&show_raw=1
> > > 
> > > Original change's description:
> > > > Exclude unused java classes from gvr_common_java aar
> > > > 
> > > > As far as I can tell this filters the rest of the unused java classes.
> > > > 
> > > > Please revert this CL if you see ClassNotFound Exceptions.
> > > > 
> > > > diagnose_bloat summary:
> > > > MonochromePublic.apk_Breakdown (-4,097 bytes)
> > > >     +1,731 bytes Zip Overhead
> > > >         -1 bytes Package metadata size
> > > >     -5,827 bytes Java code size
> > > > MonochromePublic.apk_Specifics
> > > >    -15,137 bytes normalized apk size
> > > >    -11,040 bytes main dex size
> > > > 
> > > > Bug: 944791
> > > > Change-Id: I53219489d0289655a72405ab1e06cbeeb065d4f4
> > > > Reviewed-on: https://chromium-review.googlesource.com/944791
> > > > Reviewed-by: Brandon Jones <bajones@chromium.org>
> > > > Commit-Queue: Michael Thiessen <mthiesse@chromium.org>
> > > > Cr-Commit-Position: refs/heads/master@{#540549}
> > > 
> > > TBR=mthiesse@chromium.org,bajones@chromium.org
> > > 
> > > Change-Id: I1b4b8c2d4acaaa9eafde507ceeb32293a164ac2b
> > > No-Presubmit: true
> > > No-Tree-Checks: true
> > > No-Try: true
> > > Bug: 944791
> > > Reviewed-on: https://chromium-review.googlesource.com/946653
> > > Reviewed-by: Brian Sheedy <bsheedy@chromium.org>
> > > Commit-Queue: Brian Sheedy <bsheedy@chromium.org>
> > > Cr-Commit-Position: refs/heads/master@{#540672}
> > 
> > TBR=mthiesse@chromium.org,bajones@chromium.org,bsheedy@chromium.org
> > 
> > # Not skipping CQ checks because original CL landed > 1 day ago.
> > 
> > Bug: 944791
> > Change-Id: I17e5095e0298d20bdd3876473e673f4ed5f07e5c
> > Reviewed-on: https://chromium-review.googlesource.com/951826
> > Commit-Queue: Michael Thiessen <mthiesse@chromium.org>
> > Reviewed-by: Michael Thiessen <mthiesse@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#541236}
> 
> TBR=mthiesse@chromium.org,bajones@chromium.org,bsheedy@chromium.org
> 
> Change-Id: I97a0f25703d4ebf80b357a8f63d4399c1fcfbb3f
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 944791
> Reviewed-on: https://chromium-review.googlesource.com/951972
> Reviewed-by: Brian Sheedy <bsheedy@chromium.org>
> Commit-Queue: Brian Sheedy <bsheedy@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#541247}

TBR=mthiesse@chromium.org,bajones@chromium.org,bsheedy@chromium.org

Change-Id: Ia8c899645df903ee40c6cdfe1b0f1d614869df68
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 944791
Reviewed-on: https://chromium-review.googlesource.com/954183
Commit-Queue: Michael Thiessen <mthiesse@chromium.org>
Reviewed-by: Michael Thiessen <mthiesse@chromium.org>
Cr-Commit-Position: refs/heads/master@{#541662}
Former-commit-id: 006a2814203d3b7fc02fe7794475c9a5fb197ba4