Pass path to gn binary to cronet_licenses.py when building for iOS.
The bot used on iOS have a different repository structure where
Chromium repository is not the primary gclient repository, and
the buildtools is not in the search path of gclient. This cause
failure when invoking gn through searching the PATH as the wrapper
from depot_tools is found and it does not find the real binary.

Instead update cronet_licenses.py to accept the path to the gn
binary and pass the path to the binary in //buildtools/mac when
building for iOS.

Fixes the following compilation error:
  python ../../components/cronet/tools/cronet_licenses.py license cronet/LICENSE --gn
  gn.py: Could not find gn executable at: /b/build/slave/chrome-ios-official/build/buildtools/mac/gn
  Traceback (most recent call last):
    File "../../components/cronet/tools/cronet_licenses.py", line 130, in <module>
      sys.exit(main())
    File "../../components/cronet/tools/cronet_licenses.py", line 108, in main
      third_party_dirs = FindThirdPartyDeps(os.getcwd())
    File "../../components/cronet/tools/cronet_licenses.py", line 74, in FindThirdPartyDeps
      subprocess.check_output(["gn", "gen", tmp_dir])
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
      raise CalledProcessError(retcode, cmd, output=output)
  subprocess.CalledProcessError: Command '['gn', 'gen', '/b/build/slave/chrome-ios-official/build/src/out/Release-iphoneos/tmppFeoga']' returned non-zero exit status 2

BUG=None

Review-Url: https://codereview.chromium.org/2246573002
Cr-Commit-Position: refs/heads/master@{#411766}

Former-commit-id: 2228c82b13e3663d176b7e76b34eb6d360f0a8f7