Revert of [Android] Switch chromium bots on chromium.android to gn. (patchset #1 id:1 of https://codereview.chromium.org/1636003003/ )
Reason for revert:
broken w/

ninja: Entering directory `/b/build/slave/android_build/build/src/out/Debug'
ninja: error: unknown target 'android_builder_tests'

or

In file included from ../../content/gpu/in_process_gpu_thread.cc:10:0:
../../content/gpu/gpu_child_thread.h:24:50: fatal error: content/common/process_control.mojom.h: No such file or directory
 #include "content/common/process_control.mojom.h"

Original issue's description:
> [Android] Switch chromium bots on chromium.android to gn.
>
> This still does not include cronet or webview.
>
> BUG=580129
>
> Committed: https://crrev.com/2babec811d83385a5725fe560d9139b5638d9a25 [formerly 1f63a1d9804b3c25dd896b52b3b3baf3700293fe]
> Cr-Commit-Position: refs/heads/master@{#371641}

TBR=dpranke@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=580129

Review URL: https://codereview.chromium.org/1632343003

Cr-Commit-Position: refs/heads/master@{#371679}

Former-commit-id: b4e418c3b91110b54b0429a38bbf323fc5cb87f9