Revert "Visually scale down the size of the Google G logo in the omnibox"
This reverts commit e0e5bab1ac04b24917309a3fa14a289b5f9ddb7e [formerly a59a4ff301b4f5c8f9c60e83dbe80e8c3c289e5c].

Reason for revert: Code crashes with following assertion:
java.lang.AssertionError: Paint should be initialized when the search engine is Google.                                                                                                                                                                                                                         
at org.chromium.chrome.browser.omnibox.status.StatusView.setStatusIcon(StatusView.java:343)  

Consulted Brandon and reverting this change as we agreed. We'll reland it when he's back.

Original change's description:
> Visually scale down the size of the Google G logo in the omnibox
> 
> Bug: 1020774
> Change-Id: I48b32fdfbcf4dc2a20ba047ee3f93783f4fa2a38
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1918047
> Commit-Queue: Brandon Wylie <wylieb@chromium.org>
> Reviewed-by: Theresa  <twellington@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#718931}

TBR=twellington@chromium.org,wylieb@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 1020774
Change-Id: I858a8f362898af35de2b255af960029f64894373
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1940720
Reviewed-by: Ender <ender@google.com>
Commit-Queue: Ender <ender@google.com>
Cr-Commit-Position: refs/heads/master@{#719724}

Former-commit-id: ebdf5c53b044b196cd7d3315f3a455f5295c1067