remoting: Remove duplicate remoting_perftests dependency
This dependency is duplicated below under the enable_remoting_host==1
condition, and doesn't exist when that condition is false. This fixes
the following error when remoting=1 enable_remoting_host=0:

KeyError: '/ssd/src/chromium/src/remoting/remoting.gyp:remoting_perftests#target'

BUG=none
TEST=GYP_DEFINES='use_ozone=1' gclient runhooks

Review URL: https://codereview.chromium.org/1351143003

Cr-Commit-Position: refs/heads/master@{#349597}

Former-commit-id: 2f2266e2c05a1e72419eea1073d33f6915dbb1cb