Require MacOS >=10.5 for scons build
The Clang build fails with -mmacosx-version-min=10.4.  Chromium builds
and our Gyp builds use -mmacosx-version-min=10.5.  It's not worth
spending effort on figuring out why we need this or why it only shows
up as a problem with Clang.  We aren't trying to support any MacOS
build environments older than what Chromium supports.

The failure seen is an undefined reference to "___eprintf".

BUG= cleanup
TEST= trybots

R=mseaborn@chromium.org

Review URL: http://codereview.chromium.org/7982030

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@6750 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: 2377493c056ec9844bbd0664eaa0af6568031a8b