Revert of Roll src/native_client/ cad577667..257dd7be6 (1 commit). (patchset #1 id:1 of https://codereview.chromium.org/1666783002/ )
Reason for revert:
Breaking the build on Win Builder and Win x64 Builder (dbg)

FAILED: C:\b\depot_tools\python276_bin\python.exe gyp-win-tool action-wrapper environment.x64 ppapi_tests_extensions_no_socket_permissions_target_build_newlib_x86_64_nexe_ff49b755b038c2b39cc59644a35b7542..rsp ..\..\ppapi\tests\extensions
Assembler messages:

Fatal error: can't create ../../../out/Debug_x64/obj/ppapi/tests/extensions/ppapi_tests_extensions_no_socket_permissions.gen/newlib-x86-64/ppapi_tests_extensions_no_socket_permissions/test_no_socket_permissions_d6663889.o: No such file or directory

x86_64-nacl-clang++.exe: error: assembler command failed with exit code 1 (use -v to see invocation)

FAILED with 1: ..\..\..\native_client\toolchain\win_x86\pnacl_newlib\bin\x86_64-nacl-clang++ -c no_socket_permissions/test_no_socket_permissions.cc -o ..\..\..\out\Debug_x64\obj\ppapi\tests\extensions\ppapi_tests_extensions_no_socket_permissions.gen/newlib-x86-64/ppapi_tests_extensions_no_socket_permissions\test_no_socket_permissions_d6663889.o -MD -MF ..\..\..\out\Debug_x64\obj\ppapi\tests\extensions\ppapi_tests_extensions_no_socket_permissions.gen/newlib-x86-64/ppapi_tests_extensions_no_socket_permissions\test_no_socket_permissions_d6663889.o.d -m64 -O2 -g -Wall -fdiagnostics-show-option -Werror -D__STDC_LIMIT_MACROS=1 -D__STDC_FORMAT_MACROS=1 -D_GNU_SOURCE=1 -D_POSIX_C_SOURCE=199506 -D_XOPEN_SOURCE=600 -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DDYNAMIC_ANNOTATIONS_PREFIX=NACL_ -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -DNOMINMAX -DPSAPI_VERSION=1 -D_CRT_RAND_S -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -D_ATL_NO_OPENGL -D_SECURE_ATL -D_HAS_EXCEPTIONS=0 -D_WINSOCK_DEPRECATED_NO_WARNINGS -DCHROMIUM_BUILD -DCR_CLANG_REVISION=259395-1 -DUSE_AURA=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DENABLE_TOPCHROME_MD=1 -DDONT_EMBED_BUILD_METADATA -DFIELDTRIAL_TESTING_ENABLED -DNO_TCMALLOC -D__STD_C -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -DNTDDI_VERSION=0x0A000000 -D_USING_V110_SDK71_ -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DUSE_LIBPCI=1 -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DNACL_WINDOWS=0 -DNACL_OSX=0 -DNACL_LINUX=0 -DNACL_ANDROID=0 -DNACL_BUILD_ARCH=x86 -DNACL_BUILD_SUBARCH=64 -I..\..\..\out\Debug_x64/gen/tc_newlib/include -I../../.. -I..\..\..\out\Debug_x64/gen -I../../../third_party/wtl/include -std=gnu++0x -Wno-deprecated-register

Compile options: ['-m64', '-O2', '-g', '-Wall', '-fdiagnostics-show-option', '-Werror', '-D__STDC_LIMIT_MACROS=1', '-D__STDC_FORMAT_MACROS=1', '-D_GNU_SOURCE=1', '-D_POSIX_C_SOURCE=199506', '-D_XOPEN_SOURCE=600', '-DDYNAMIC_ANNOTATIONS_ENABLED=1', '-DDYNAMIC_ANNOTATIONS_PREFIX=NACL_', '-DV8_DEPRECATION_WARNINGS', '-DCLD_VERSION=2', '-DNOMINMAX', '-DPSAPI_VERSION=1', '-D_CRT_RAND_S', '-DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS', '-D_ATL_NO_OPENGL', '-D_SECURE_ATL', '-D_HAS_EXCEPTIONS=0', '-D_WINSOCK_DEPRECATED_NO_WARNINGS', '-DCHROMIUM_BUILD', '-DCR_CLANG_REVISION=259395-1', '-DUSE_AURA=1', '-DUSE_DEFAULT_RENDER_THEME=1', '-DUSE_LIBJPEG_TURBO=1', '-DENABLE_ONE_CLICK_SIGNIN', '-DENABLE_WEBRTC=1', '-DENABLE_MEDIA_ROUTER=1', '-DENABLE_PEPPER_CDMS', '-DENABLE_CONFIGURATION_POLICY', '-DENABLE_NOTIFICATIONS', '-DENABLE_HIDPI=1', '-DENABLE_TOPCHROME_MD=1', '-DDONT_EMBED_BUILD_METADATA', '-DFIELDTRIAL_TESTING_ENABLED', '-DNO_TCMALLOC', '-D__STD_C', '-D_CRT_SECURE_NO_DEPRECATE', '-D_SCL_SECURE_NO_DEPRECATE', '-DNTDDI_VERSION=0x0A000000', '-D_USING_V110_SDK71_', '-DENABLE_TASK_MANAGER=1', '-DENABLE_EXTENSIONS=1', '-DENABLE_PDF=1', '-DENABLE_PLUGIN_INSTALLATION=1', '-DENABLE_PLUGINS=1', '-DENABLE_SESSION_SERVICE=1', '-DENABLE_THEMES=1', '-DENABLE_AUTOFILL_DIALOG=1', '-DENABLE_BACKGROUND=1', '-DENABLE_PRINTING=1', '-DENABLE_BASIC_PRINTING=1', '-DENABLE_PRINT_PREVIEW=1', '-DENABLE_SPELLCHECK=1', '-DENABLE_CAPTIVE_PORTAL_DETECTION=1', '-DENABLE_APP_LIST=1', '-DENABLE_SETTINGS_APP=1', '-DENABLE_SUPERVISED_USERS=1', '-DENABLE_MDNS=1', '-DENABLE_SERVICE_DISCOVERY=1', '-DV8_USE_EXTERNAL_STARTUP_DATA', '-DFULL_SAFE_BROWSING', '-DSAFE_BROWSING_CSD', '-DSAFE_BROWSING_DB_LOCAL', '-DUSE_LIBPCI=1', '-DUSE_OPENSSL=1', '-DUSE_OPENSSL_CERTS=1', '-D_CRT_NONSTDC_NO_WARNINGS', '-D_CRT_NONSTDC_NO_DEPRECATE', '-DNACL_WINDOWS=0', '-DNACL_OSX=0', '-DNACL_LINUX=0', '-DNACL_ANDROID=0', '-DNACL_BUILD_ARCH=x86', '-DNACL_BUILD_SUBARCH=64', '-I..\\..\\..\\out\\Debug_x64/gen/tc_newlib/include', '-I../../..', '-I..\\..\\..\\out\\Debug_x64/gen', '-I../../../third_party/wtl/include']

Linker options: ['-B..\\..\\..\\out\\Debug_x64/gen/tc_newlib/lib64', '-L..\\..\\..\\out\\Debug_x64/gen/tc_newlib/lib64', '-lppapi_cpp', '-lppapi', '-pthread']

Skipping unknown type  for .

Original issue's description:
> Roll src/native_client/ cad577667..257dd7be6 (1 commit).
>
> https://chromium.googlesource.com/native_client/src/native_client.git/+log/cad577667eab..257dd7be61b0
>
> $ git log cad577667..257dd7be6 --date=short --no-merges --format='%ad %ae %s'
> 2016-02-03 sbc untrusted.gypi: default to nacl-clang for newlib builds
>
> CQ_INCLUDE_TRYBOTS=tryserver.chromium.linux:linux_chromium_dbg_32_ng,linux_nacl_sdk_build
> TBR=mseaborn@chromium.org
>
> Committed: https://crrev.com/a684ec9ce8ecf1a9d975c73a659b4b5c9f8034aa [formerly b6be59a64a5a4d051ae7f61cb67f39b635ddb317]
> Cr-Commit-Position: refs/heads/master@{#373345}

TBR=mseaborn@chromium.org,nacl-deps-roller@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/1664983002

Cr-Commit-Position: refs/heads/master@{#373353}

Former-commit-id: 79b80d6a95a2a6e61200c0024755334376575be1