Reland "Add ContentSuggestionsNotifierService test"
This reverts commit 3839baaf38cc0205fcf888fe75a7071fbb33b21a [formerly 3620d98f96ae6a00d945158009d68da1774b2603].

Reason for revert: Added missing MOCK_METHOD0 for pure virtual.

Original change's description:
> Revert "Add ContentSuggestionsNotifierService test"
> 
> This reverts commit 9622a8979b9e983a0bcb151f23166d76bb686092 [formerly 1b67eea5d2f612a56982a28e4352e3f3bc1a6a62].
> 
> Reason for revert: This appears to be breaking some Android Builders (https://build.chromium.org/p/chromium.linux/builders/Android%20Builder/builds/86932):
> 
> ../../chrome/browser/android/ntp/content_suggestions_notifier_service_unittest.cc:160:29: error: field 'notifier_' is uninitialized when used here [-Werror,-Wuninitialized]
>         notifier_ownership_(notifier_),
> 
> Original change's description:
> > Add ContentSuggestionsNotifierService test
> > 
> > This is just a basic start. There's plenty more things that we would
> > want to test in practice.
> > 
> > BUG=757855
> > 
> > Change-Id: I2d0cbecfd25b690c674f8b87efec09a6c43d0d9c
> > Reviewed-on: https://chromium-review.googlesource.com/638631
> > Commit-Queue: Chris Pickel <sfiera@chromium.org>
> > Reviewed-by: Marc Treib <treib@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#498829}
> 
> TBR=treib@chromium.org,sfiera@chromium.org
> 
> Change-Id: I99f3e181d3934faf2a0f273ca69d85aa124283ed
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 757855
> Reviewed-on: https://chromium-review.googlesource.com/645926
> Reviewed-by: Anthony Vallee-Dubois <anthonyvd@chromium.org>
> Commit-Queue: Anthony Vallee-Dubois <anthonyvd@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#498833}

Change-Id: I439d0d2ed944d95f94bcf9f54c5cae9d3e18f6de
Bug: 757855
Reviewed-on: https://chromium-review.googlesource.com/645946
Reviewed-by: Marc Treib <treib@chromium.org>
Commit-Queue: Chris Pickel <sfiera@chromium.org>
Cr-Commit-Position: refs/heads/master@{#498870}
Former-commit-id: 3b4c85d14d1ce6d83478fc99de550c7e4d35ace5