Revert "Add browser tests for Chrome autofill on captured sites. (Bug 847905)"
This reverts commit 8822054c4c1f21a02096e4989affd30ce0308607 [formerly c2ec5265a6c4f2b664e4f388e44f7a13b198e76c].

Reason for revert: Broke compile on https://ci.chromium.org/buildbot/chromium/Win%20x64/23318

../../chrome/browser/autofill/autofill_captured_sites_interactive_uitest.cc(404,45): error: no viable conversion from 'const wchar_t [12]' to 'base::StringPiece' (aka 'BasicStringPiece<basic_string<char, char_traits<char>, allocator<char> > >') .AppendASCII(FILE_PATH_LITERAL("wpr_key.pem"))


Original change's description:
> Add browser tests for Chrome autofill on captured sites. (Bug 847905)
> 
> These tests are the first step in building a test framework for testing
> chrome autofill on complex, real-world sites pages. Since interacting
> with live sites are flaky and vulnerable to updates to the sites'
> features, this framework interacts with captured sites.
> 
> Sites are captured with the Web Page Replay (WPR) tool. Prior to
> running the test, the browser test will start WPR locally on the
> machine using a capture file. The test then navigates to the test
> site, interact with the site's checkout workflow, and verifies that
> autofill correctly completes the address and payment information.
> 
> Tests for 5 sites are included in this code change: Amazon, Zappos,
> Apple, Ebay and Walmart.
> 
> This change fixes the build breaks caused by the earlier change,
> 963800, and it also changes the tests from being driven by test code
> to being driven by test recipe files. The test recipe files will be
> generated by a chrome automation extension recording user actions.
> 
> Bug: 847905
> Change-Id: I0ef7b2b04be2a6caf3742c520f25ab1de80f9711
> Reviewed-on: https://chromium-review.googlesource.com/1086088
> Commit-Queue: Yiming Zhou <uwyiming@google.com>
> Reviewed-by: Sebastien Seguin-Gagnon <sebsg@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#564693}

TBR=anthonyvd@chromium.org,sebsg@chromium.org,mahmadi@chromium.org,uwyiming@google.com

Change-Id: I2e6625dd64bfa91e15c4c048d0cd3174be960fee
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 847905
Reviewed-on: https://chromium-review.googlesource.com/1088129
Reviewed-by: Lambros Lambrou <lambroslambrou@chromium.org>
Commit-Queue: Lambros Lambrou <lambroslambrou@chromium.org>
Cr-Commit-Position: refs/heads/master@{#564708}
Former-commit-id: 22387fe1750c9716f7fa48846263d7c9eff3f2c9