Revert 238466 "Revert 238036 "Revert 238025 "Let test_isolation_..."
While r238430 improved things, it didn't fix them enough. Exciting new error:

OSError: File /Volumes/data/b/build/slave/google-chrome-rel-mac/build/src/out/Release/<(mac_product_name) Framework.framework doesn't exist

(tracked at http://crbug.com/324911)

> Revert 238036 "Revert 238025 "Let test_isolation_mode default to..."
> 
> The change was reverted because swarming didn't work with branded builds,
> but r238430 should've fixed that. Relanding. (There are no branded trybots.)
> 
> > Revert 238025 "Let test_isolation_mode default to check on mac."
> > 
> > Failing on "Google Chrome Mac" (http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Mac/builds/15042)
> > In the error log, tools/swarming_client/isolate.py says "File /Volumes/data/b/build/slave/google-chrome-rel-mac/build/src/out/Release/Chromium Framework.framework doesn't exist"
> > 
> > > Let test_isolation_mode default to check on mac.
> > > 
> > > It was set to noop in https://chromiumcodereview.appspot.com/14055005 due to
> > > issues with xcode. Now that xcode is no longer used, it can be set to check
> > > again.
> > > 
> > > BUG=none
> > > 
> > > Review URL: https://codereview.chromium.org/92303002
> > 
> > TBR=thakis@chromium.org
> > 
> > Review URL: https://codereview.chromium.org/98383002
> 
> TBR=hashimoto@chromium.org
> 
> Review URL: https://codereview.chromium.org/102963003

TBR=thakis@chromium.org

Review URL: https://codereview.chromium.org/98533003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@238505 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: d595544bf8d4d35e3103149740683e364c17fe7c