Revert "Add browser tests for autofilling the shipping address info and payment info on captured sites."
This reverts commit d09052124056c59b587e6b384a89b9149ad063dc [formerly 34a6f41d2034f2a81366fc9694012ebd9f010e01].

Reason for revert: Broke the Mac and Windows build.

https://ci.chromium.org/buildbot/chromium/Mac/40485

chrome/test/base/interactive_test_utils_aura.cc:24:9: error: member access into incomplete type 'NSWindow'
  window->Hide();

https://ci.chromium.org/buildbot/chromium/Win%20x64/21368

chrome/browser/autofill/autofill_captured_sites_interactive_uitest.cc(133,9):  error: format specifies type 'char *' but the argument has type 'const wchar_t *' [-Werror,-Wformat]
        src_dir.AppendASCII("third_party/catapult/web_page_replay_go")

Original change's description:
> Add browser tests for autofilling the shipping address info and payment info on captured sites.
> 
> These tests are the first step in building a test framework for testing chrome autofill on complex, real-world sites pages. Since interacting with live sites are flaky and vulnerable to updates to the sites' features, this framework interacts with captured sites.
> 
> Sites are captured with the Web Page Replay (WPR) tool. Prior to running the test, the browser test will start WPR locally on the machine using a capture file. The test then navigates to the test site, interact with the site's checkout workflow, and verifies that autofill correctly completes the address and payment information.
> 
> Tests for 5 sites are included in this code change: Amazon, Zappos, Apple, Ebay and Walmart.
> 
> Change-Id: I4b28e645554a2912c632fcb462439cac7142cf9f
> Reviewed-on: https://chromium-review.googlesource.com/963800
> Commit-Queue: Yiming Zhou <uwyiming@google.com>
> Reviewed-by: anthonyvd <anthonyvd@chromium.org>
> Reviewed-by: Sebastien Seguin-Gagnon <sebsg@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#551190}

TBR=anthonyvd@chromium.org,sebsg@chromium.org,mahmadi@chromium.org,uwyiming@google.com

Change-Id: Ied983de9c011fb6e3099e68b03bc60641a31b056
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/1014497
Reviewed-by: Lei Zhang <thestig@chromium.org>
Commit-Queue: Lei Zhang <thestig@chromium.org>
Cr-Commit-Position: refs/heads/master@{#551207}
Former-commit-id: 6d63741eb2341faf50f9339779229e92b1e3cb8b