Revert "[Telemetry] Refactor expectations code into story_filter.py."
This reverts commit 8b3d26ef89e8b77d91dfb2aaea894ec31fed1090 [formerly 955f75d036630b0cb9da26b3733942643ad2a695].

Reason for revert: Catapult roller failing with:

  AttributeError: type object 'StoryFilterFactory' has no attribute '_expectations'
https://chromium-swarm.appspot.com/task?id=47eb08c183837510

Original change's description:
> [Telemetry] Refactor expectations code into story_filter.py.
> 
> Before this change, expectations code was littered around in several
> places including benchmark.py, story_runner.py, commands.py, etc.
> Each of those modules needed their own unit tests for
> expectations-related behavior as well. This change factors out all the
> expectations-related code into a single ShouldSkip function in
> story_filter.py. story_filter.py comes to have two related
> functionalities:
> 1. Filtering stories that should not be run or marked skipped.
> 2. Skipping stories that should be skipped.
> 
> In the future, we want to support a flag such as
> --story=<exact story name> (or maybe --stories=<list of
> exact story names>). For that feature, we will need to
> augment both 1 and 2 because:
> 1. We should filter out any story that does not match
> that flag.
> 2. We should probably ignore expectations if someone passes
> an exact story name. (Or maybe make this configurable?)
> 
> The point of the above is that this story filtering and story skipping
> code is related and could benefit from being part of a single module.
> 
> Note that this also allows improvements to the unit test
> code. In a few places, we can now mock out story_filter instead of
> having to build fake expectations. Making changes to story filtering
> or to expectations will not require editing any story_runner_unittests.
> 
> Also, turn typ_expectations_unittest.py into a real unit test
> that only tests its own functionality.
> 
> Note that the options_for_unittests.py change is required to
> enable system_health_smoke_tests.py and benchmark_smoke_tests.py
> to pass expectations to story_filter (via story_runner). The
> change to those chromium-side smoke tests is in
> https://chromium-review.googlesource.com/c/chromium/src/+/1854794
> 
> Bug: chromium:985103
> Change-Id: I966e9541b2df1e17f561077d119eea1c179e35d2
> Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/1839176
> Commit-Queue: Caleb Rouleau <crouleau@chromium.org>
> Reviewed-by: Juan Antonio Navarro Pérez <perezju@chromium.org>
> Reviewed-by: Rakib Hasan <rmhasan@google.com>

TBR=perezju@chromium.org,crouleau@chromium.org,rmhasan@google.com

Change-Id: I4b5b754e749006542824167be481c87afe2418d7
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: chromium:985103
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/1864789
Reviewed-by: Juan Antonio Navarro Pérez <perezju@chromium.org>
Commit-Queue: Juan Antonio Navarro Pérez <perezju@chromium.org>

Former-commit-id: 44806300adbd52cb4193a76c7282a2f6cb7250d0