Don't depend on the repo existing in BootstrapFromVersion.
Currently, the BootstrapFromVersion function reads the chromeos_version.sh
file prior to actually syncing the repository. This is a bug, and causes
cbuildbot to fail with the following error:

IOError: [Errno 2] No such file or directory:
  '.../src/third_party/chromiumos-overlay/chromeos/config/chromeos_version.sh'

We fix this bug by instead initializing the version_info object using the
version that was passed in.

BUG=chromium:221426
TEST=Launch a builder on a machine that doesn't have chromiumos-overlay.

Change-Id: I3c893dc2414f2d4fd055596cd1479717365176db
Reviewed-on: https://gerrit.chromium.org/gerrit/47303
Tested-by: David James <davidjames@chromium.org>
Reviewed-by: Peter Mayo <petermayo@chromium.org>
Commit-Queue: David James <davidjames@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>