Revert "Notifications: Enable inline settings for new-style notifications"
This reverts commit e4a16163a6885f723cd379a817993f9dbe1f0b38 [formerly 0839cb4844bd8e5a2e003a5545a1a60c104e5e06].

Reason for revert:

Broke Mac bots on the waterfall:
https://ci.chromium.org/buildbot/chromium/Mac/37907

../../ui/message_center/cocoa/notification_controller_unittest.mm:151:57: error: no member named 'TRAY' in 'message_center::SettingsButtonHandler'


Original change's description:
> Notifications: Enable inline settings for new-style notifications
> (when cmd line flag is specified).
> 
> Bug: 768300
> Change-Id: I729658c51a4b323181c0c16416885b0efbe8bf96
> Reviewed-on: https://chromium-review.googlesource.com/893383
> Commit-Queue: Finnur Thorarinsson <finnur@chromium.org>
> Reviewed-by: Peter Beverloo <peter@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#534981}

TBR=peter@chromium.org,finnur@chromium.org

Change-Id: I4ce487270a11ccf08f3f8ab70c5f6820f684ac24
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 768300
Reviewed-on: https://chromium-review.googlesource.com/906383
Reviewed-by: Elly Fong-Jones <ellyjones@chromium.org>
Commit-Queue: Elly Fong-Jones <ellyjones@chromium.org>
Cr-Commit-Position: refs/heads/master@{#534985}
Former-commit-id: 5a64040dc63c39874d952905d188ba398464d62d