Build error: DNSSoup.cpp:30: fatal error: CString.h: No such file or directory https://bugs.webkit.org/show_bug.cgi?id=81093
Patch by Sudarsana Nagineni <sudarsana.nagineni@linux.intel.com> on 2012-03-14
Reviewed by Philippe Normand.

Fix build error introduced by r110669.

* platform/network/soup/DNSSoup.cpp:

git-svn-id: svn://svn.chromium.org/blink/trunk@110697 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: 817c85d9fb9ebf758717824a6c4baf03f542d3fe