Revert of [Cronet] Remove JSON serialization of CronetEngine.Builder (patchset #14 id:260001 of https://codereview.chromium.org/1429863008/ )
Reason for revert:
Looks like this broke the android build:
https://build.chromium.org/p/chromium.gpu/builders/Android%20Debug%20%28Nexus%209%29/builds/4522

FAILED: /b/build/goma/gomacc /b/build/slave/Android_Debug__Nexus_9_/build/src/third_party/android_tools/ndk//toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -MMD -MF obj/components/cronet/cronet_unittests.url_request_context_config_unittest.o.d -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -D_FILE_OFFSET_BITS=64 -DNO_TCMALLOC -DDISABLE_NACL -DCHROMIUM_BUILD -DCR_CLANG_REVISION=254049-1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DUSE_PROPRIETARY_CODECS -DENABLE_BROWSER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DFIELDTRIAL_TESTING_ENABLED -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_SPELLCHECK=1 -DUSE_BROWSER_SPELLCHECKER=1 -DENABLE_SUPERVISED_USERS=1 -DVIDEO_HOLE=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DENABLE_WEBVR -DSAFE_BROWSING_DB_REMOTE -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=0 -DPROTOBUF_USE_DLLS -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DUNIT_TEST -DGTEST_HAS_RTTI=0 -DGTEST_USE_OWN_TR1_TUPLE=1 -DGTEST_HAS_TR1_TUPLE=1 -DUSE_LIBPCI=1 -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DANDROID -D__GNU_SOURCE=1 '-DCHROME_BUILD_ID=""' -DHAVE_SYS_UIO_H -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -D_DEBUG -Igen -Igen/protoc_out -I../.. -I../../third_party/protobuf -I../../third_party/protobuf/src -I../../testing/gtest/include -fstack-protector --param=ssp-buffer-size=4 -Werror -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-unused-local-typedefs -march=armv7-a -mtune=generic-armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb -fno-tree-sra -fno-caller-saves -Wno-psabi -mthumb-interwork -ffunction-sections -funwind-tables -g -fstack-protector -fno-short-enums -finline-limit=64 --sysroot=../../third_party/android_tools/ndk//platforms/android-16/arch-arm -isystem../../third_party/android_tools/ndk//sources/cxx-stl/llvm-libc++/libcxx/include -isystem../../third_party/android_tools/ndk//sources/cxx-stl/llvm-libc++abi/libcxxabi/include -isystem../../third_party/android_tools/ndk//sources/android/support/include -Os -g -fdata-sections -ffunction-sections -fomit-frame-pointer -funwind-tables -g0 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare -Wno-abi -std=gnu++11 -Wno-narrowing -Wno-literal-suffix  -c ../../components/cronet/url_request_context_config_unittest.cc -o obj/components/cronet/cronet_unittests.url_request_context_config_unittest.o
../../components/cronet/url_request_context_config_unittest.cc: In member function 'virtual void cronet::URLRequestContextConfigTest_SetQuicExperimentalOptions_Test::TestBody()':
../../components/cronet/url_request_context_config_unittest.cc:17:27: error: no matching function for call to 'cronet::URLRequestContextConfig::URLRequestContextConfig()'
   URLRequestContextConfig config;
                           ^
../../components/cronet/url_request_context_config_unittest.cc:17:27: note: candidates are:
In file included from ../../components/cronet/url_request_context_config.h:10:0,
                 from ../../components/cronet/url_request_context_config_unittest.cc:5:
../../components/cronet/url_request_context_config.h:148:28: note: cronet::URLRequestContextConfig::URLRequestContextConfig(const cronet::URLRequestContextConfig&)
   DISALLOW_COPY_AND_ASSIGN(URLRequestContextConfig);
                            ^
../../base/macros.h:27:3: note: in definition of macro 'DISALLOW_COPY_AND_ASSIGN'
   TypeName(const TypeName&);               \
   ^
../../components/cronet/url_request_context_config.h:148:28: note:   candidate expects 1 argument, 0 provided
   DISALLOW_COPY_AND_ASSIGN(URLRequestContextConfig);
                            ^
../../base/macros.h:27:3: note: in definition of macro 'DISALLOW_COPY_AND_ASSIGN'
   TypeName(const TypeName&);               \
   ^
In file included from ../../components/cronet/url_request_context_config_unittest.cc:5:0:
../../components/cronet/url_request_context_config.h:72:3: note: cronet::URLRequestContextConfig::URLRequestContextConfig(bool, bool, bool, cronet::URLRequestContextConfig::HttpCacheType, int, bool, const string&, const string&, const string&, const string&, const string&, const string&, const string&, scoped_ptr<net::CertVerifier>)
   URLRequestContextConfig(
   ^
../../components/cronet/url_request_context_config.h:72:3: note:   candidate expects 14 arguments, 0 provided
../../components/cronet/url_request_context_config_unittest.cc:35:10: error: 'struct cronet::URLRequestContextConfig' has no member named 'LoadFromJSON'
   config.LoadFromJSON(args);
          ^
ninja: build stopped: subcommand failed.

Original issue's description:
> [Cronet] Remove JSON serialization of CronetEngine.Builder
>
> There was no need to use JSON and it was imposing artificial
> limits on what we could pass from Java to native.
> Instead of JSON, now CronetEngine.Builder configuration is
> passed via JNI.
>
> TEST=CronetUrlRequestContextTest.testCronetEngineBuilderConfig
>
> Committed: https://crrev.com/ad84a9ad6c2e415f1c72ae34fc65f917105eef28 [formerly 2ab237105cf00f7d82c1006798fdf0359a38a3ad]
> Cr-Commit-Position: refs/heads/master@{#363517}

TBR=xunjieli@chromium.org,mef@chromium.org,pauljensen@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/1507783002

Cr-Commit-Position: refs/heads/master@{#363538}

Former-commit-id: 609239eb3e1d66f2cb9df43f3a1391b41a5aa921