Revert "untrusted.gypi: Factor out duplicated "--gomadir" option"
This reverts r13760, commit 0d0bb78482f491a07ea63af0a0d44fcee75aa0f5 [formerly d5610388450aad671f59425f07fff21bc50b1384].

It causes assertion failures in Chrome's gyp when run with use_goma=1

Updating projects from gyp files...
Traceback (most recent call last):
  File "/mnt/ssd/chromium-gitsvn/src/build/gyp_chromium", line 312, in <module>
    gyp_rc = gyp.main(args)
  File "/mnt/ssd/chromium-gitsvn/src/tools/gyp/pylib/gyp/__init__.py", line 537, in main
    return gyp_main(args)
  File "/mnt/ssd/chromium-gitsvn/src/tools/gyp/pylib/gyp/__init__.py", line 522, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/mnt/ssd/chromium-gitsvn/src/tools/gyp/pylib/gyp/generator/ninja.py", line 2278, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
AssertionError: make_global_settings needs to be the same for all targets. [['CC', 'third_party/llvm-build/Release+Asserts/bin/clang'], ['CXX', 'third_party/llvm-build/Release+Asserts/bin/clang++'], ['CC.host', '$(CC)'], ['CXX.host', '$(CXX)'], ['CC_wrapper', '/gomacc'], ['CXX_wrapper', '/gomacc'], ['CC.host_wrapper', '/gomacc'], ['CXX.host_wrapper', '/gomacc']] vs. [['CC', 'third_party/llvm-build/Release+Asserts/bin/clang'], ['CXX', 'third_party/llvm-build/Release+Asserts/bin/clang++'], ['CC.host', '$(CC)'], ['CXX.host', '$(CXX)'], ['CC_wrapper', '/usr/local/google/home/dschuff/goma/gomacc'], ['CXX_wrapper', '/usr/local/google/home/dschuff/goma/gomacc'], ['CC.host_wrapper', '/usr/local/google/home/dschuff/goma/gomacc'], ['CXX.host_wrapper', '/usr/local/google/home/dschuff/goma/gomacc']]


TBR=mseaborn@chromium.org
BUG=None
NOTRY=true
(git cl dcommit is broken for me for some reason)

Review URL: https://codereview.chromium.org/589393004

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@13785 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: 15cf4505166a6c85f9f3c5c78c639e63705b88fa