Add missing test dependency
Otherwise we get flaky build failures like:

../../third_party/blink/renderer/platform/bindings/name_client.h:9:10: fatal error: 'third_party/blink/renderer/platform/bindings/buildflags.h' file not found
	#include "third_party/blink/renderer/platform/bindings/buildflags.h"
	         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: Ie9737e7e28a3e836cce94c5ff0eff8449096b651
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1948053
Commit-Queue: Guido Urdaneta <guidou@chromium.org>
Reviewed-by: Antonio Gomes <tonikitoo@igalia.com>
Reviewed-by: Guido Urdaneta <guidou@chromium.org>
Cr-Commit-Position: refs/heads/master@{#721529}

Former-commit-id: 8ba3504522ed951f99c5c90eb0edbadd3cba9f0b