RELAND: ShapeDetection: add support for Text Detection in Mac
The original CL got reverted due to out-of-bots partial availability
warnings such as :
../../services/shape_detection/text_detection_impl_mac.mm:68:8:
> error: 'CIRectangleFeature' is only available on macOS 10_10 or newer
(1st spotted in https://codereview.chromium.org/2726843006/#msg29)
This CL adds forward-declaration of this class before 10.11.

Incidentally, it's the same issue addressed in e.g.
https://bugs.chromium.org/p/chromium/issues/detail?id=665150#c24

Original issue's description:
> ShapeDetection: add support for Text Detection in Mac
>
> This CL adds text detection for Mac in services/shape_detection,
> and also adds unittest for it, that will be run, like the
> other specific unittests, in the mac gpu bots.
>
> BUG=697925
> CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.mac:mac_optional_gpu_tests_rel
> TEST= unittests that can be run anywhere like this:
> out/gn/service_unittests  --gtest_filter=*TextDetection* --use-gpu-in-tests
>
> and demo page, e.g.
> ./out/gn/Chromium.app/Contents/MacOS/Chromium  --enable-blink-features=ShapeDetection https://codepen.io/miguelao/full/ygxVqg
>
> Review-Url: https://codereview.chromium.org/2726843006
CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.mac:mac_optional_gpu_tests_rel

TBR=avi@chromium.org, rsesek@chromium.org since it's a trivial fwd-declaration.

Review-Url: https://codereview.chromium.org/2734703002
Cr-Commit-Position: refs/heads/master@{#454816}

Former-commit-id: 9eba8ffcc405012f235a5bfb5ce49485a746b379