Revert 239864 "Add GetMinimumSize() for Labels and ensure it's z..."
[727/844] CXX obj/chrome/browser/chromeos/ui/browser_chromeos.idle_logout_dialog_view.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/browser/ui/views/browser_ui.status_bubble_views.o.d -DANGLE_DX11 -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCOMPONENT_BUILD -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_NSS=1 -DUSE_X11=1 -DOS_CHROMEOS=1 -DUSE_XI2_MT=2 -DFILE_MANAGER_EXTENSION=1 -DIMAGE_LOADER_EXTENSION=1 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_INPUT_SPEECH -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DUSE_UDEV -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -DENABLE_EGLIMAGE=1 -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_AUTOMATION=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -DNACL_WINDOWS=0 -DNACL_LINUX=1 -DNACL_OSX=0 -DNACL_TARGET_SUBARCH=64 -DNACL_TARGET_ARCH=x86 -DNACL_BUILD_SUBARCH=64 -DNACL_BUILD_ARCH=x86 -DFULL_SAFE_BROWSING -DGL_GLEXT_PROTOTYPES -DLIBPEERCONNECTION_LIB=1 -DUSE_BRLAPI -DPROTOBUF_USE_DLLS -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DSKIA_DLL -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_ENABLE_INST_COUNT=0 -DSK_SUPPORT_GPU=1 '-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' -DSK_ENABLE_LEGACY_API_ALIASING=1 -DSK_ATTR_DEPRECATED=SK_NOTHING_ARG1 -DSK_SUPPORT_LEGACY_COLORTYPE=1 -DSK_USE_POSIX_THREADS -DSK_DEFERRED_CANVAS_USES_FACTORIES=1 -DU_USING_ICU_NAMESPACE=0 -DLIBXML_STATIC -DHUNSPELL_STATIC -DHUNSPELL_CHROME_CLIENT -DUSE_HUNSPELL -DFEATURE_ENABLE_SSL -DFEATURE_ENABLE_VOICEMAIL -DEXPAT_RELATIVE_PATH -DGTEST_RELATIVE_PATH -DJSONCPP_RELATIVE_PATH -DNO_MAIN_THREAD_WRAPPING -DNO_SOUND_SYSTEM -DLINUX -DPOSIX -DCHROMEOS -DV8_SHARED -DUSING_V8_SHARED -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -D_DEBUG -D_GLIBCXX_DEBUG=1 -I../.. -Iobj/chrome/browser_ui.gen -Igen -Iobj/chrome/browser_ui.gen/chrome -I../../skia/config -I../../third_party/khronos -I../../gpu -I../../third_party/WebKit/Source -Igen/protoc_out -I../../third_party/protobuf -I../../third_party/protobuf/src -Igen/chrome -Igen/components/strings -I../../net/third_party/nss/ssl -I../../third_party/skia/src/core -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../skia/ext -I../../third_party/cacheinvalidation/overrides -I../../third_party/cacheinvalidation/src -I../../third_party/cacheinvalidation/google/cacheinvalidation -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -I../../third_party/libusb/src/libusb -I../../third_party/libxml/linux/include -I../../third_party/libxml/src/include -I../../third_party/zlib -Igen/ui/app_locale_settings -Igen/ui/ui_strings -Igen/ui/ui_resources -I../../third_party/leveldatabase/src/include -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase -I../../third_party/libjingle/overrides -I../../third_party/libjingle/source -I../../testing/gtest/include -I../../third_party -I../../third_party/webrtc -I../../third_party/jsoncpp/overrides/include -I../../third_party/jsoncpp/source/include -I../../third_party/npapi -I../../third_party/npapi/bindings -I../../third_party/re2 -I../../v8/include -Igen/webkit -Igen/policy -Igen/ash_strings -Igen/ash/ash_resources -Igen/ui/keyboard -Igen/ui/gl -I../../third_party/mesa/src/include -Werror -pthread -fno-exceptions -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-reserved-user-defined-literal -Wno-deprecated-register -Xclang -load -Xclang /b/build/slave/chromium-dbg-linux-chromeos-clang/build/src/tools/clang/scripts/../../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/nss -I/usr/include/nspr -Wno-header-guard -Wno-unknown-pragmas -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -Wexit-time-destructors -O0 -g -g0 -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare -std=gnu++11  -c ../../chrome/browser/ui/views/status_bubble_views.cc -o obj/chrome/browser/ui/views/browser_ui.status_bubble_views.o
../../chrome/browser/ui/views/status_bubble_views.cc:124:8:error: 'StatusBubbleViews::StatusView::SetText' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
  void SetText(const base::string16& text, bool should_animate_open);
       ^
../../ui/views/controls/label.h:73:16: note: hidden overloaded virtual function 'views::Label::SetText' declared here: different number of parameters (1 vs 2)
  virtual void SetText(const string16& text);
               ^
1 error generated.

> Add GetMinimumSize() for Labels and ensure it's zero for empty Links.
> 
> This requires auto-disabling focusability for empty links.  I also reordered the
> overrides for Link to match the View declaration order.
> 
> This also requires some major reworking of StyledLabel, which previously assumed
> all Links had a focus border, and to make layout easier just forced space for a
> focus border on all children at all times, as well as always reserving space
> itself.  I've changed this so StyledLabel lays out children correctly,
> accounting for their focus borders, and only adds space for one itself if any
> children have a focus border.  This eliminates the need for
> Label::SetHasFocusBorder(), which only had one non-StyledLabel caller (who
> didn't need it).
> 
> BUG=none
> TEST=none
> R=sky@chromium.org
> 
> Review URL: https://codereview.chromium.org/111023004

TBR=pkasting@chromium.org

Review URL: https://codereview.chromium.org/112023007

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@239899 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 082489ead56b14e6d6ff0ba8c25670f63ecab083