<http://webkit.org/b/28367> bugzilla.py: replace ScriptError class with BugzillaError class
        Reviewed by David Levin.

        The ScriptError class doesn't exist in bugzilla.py, so any
        errors print error messages about ScriptError instead of the
        actual error:

            NameError: global name 'ScriptError' is not defined

        * Scripts/modules/bugzilla.py:
        (BugzillaError): Added class.  Modeled after ScriptError class
        in scm.py.
        (Bugzilla.authenticate): Changed to use BugzillaError instead of
        ScriptError.
        (Bugzilla._check_create_bug_response): Ditto.

git-svn-id: svn://svn.chromium.org/blink/trunk@47344 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: b812388ad43770bdc11aad77ad4b3c6d9b6fd413