Revert "Re-adding dummy benchamrks to chromium debug waterfalls."
This reverts commit a6129995eb5fbc6dec969cd8a8707f22381c232f [formerly 81715b6193a1841807e99bc416712b62a3df0c58].

Reason for revert: Breaks on Win10 Tests x64 (dbg).

"""
BrowserFinderException: Cannot find browser of type debug. 

Available browsers:
debug_x64
reference
"""

and

"""
Traceback (most recent call last):
  File "..\..\testing\scripts\run_performance_tests.py", line 312, in <module>
    sys.exit(main())
  File "..\..\testing\scripts\run_performance_tests.py", line 284, in main
    sharding = sharding_map[shard_index]['benchmarks']
KeyError: '7'
"""

depending on shard number

Original change's description:
> Re-adding dummy benchamrks to chromium debug waterfalls.
> 
> Previously
> reviewed here: https://chromium-review.googlesource.com/c/chromium/src/+/1055776
> and then reverted.
> 
> We have to set the browser for each configuration that we run on.
> It will be one of debug, release or android-chromium.  We can do this one
> of two ways:
> 
> 1) multiple entries in test_suites.pyl
> 2) add each entry in test_suite_exceptions.pyl
> 
> Although #1 is less verbose I think #2 is how these files are intended
> to be used.
> 
> Bug: 840427
> Change-Id: Idff4c36a248215dbfdf0faed45b483800046bf26
> Reviewed-on: https://chromium-review.googlesource.com/1066088
> Reviewed-by: John Budorick <jbudorick@chromium.org>
> Commit-Queue: Emily Hanley <eyaich@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#560571}

TBR=nednguyen@google.com,eyaich@chromium.org,jbudorick@chromium.org

Change-Id: I89ca43c0eb6292ee252c459e1db94749bfb603b0
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 840427,845543
Reviewed-on: https://chromium-review.googlesource.com/1069420
Reviewed-by: Jeremy Roman <jbroman@chromium.org>
Commit-Queue: Jeremy Roman <jbroman@chromium.org>
Cr-Commit-Position: refs/heads/master@{#560744}
Former-commit-id: 4e653b28d15b1f801007c670bada8e64149211bc