Revert "Move the app_service code to //chrome/services"
This reverts commit ffee67a3a0d1d07cc2174c2185294c7d1ea16f37 [formerly f3fe6cc9f557d48dd59b59a504be004041435be4].

Reason for revert: Broke compile: https://ci.chromium.org/buildbot/chromium.chrome/Google%20Chrome%20ChromeOS/58434

Snippet:
In file included from ../../chrome/browser/devtools/devtools_window.cc:31:
  In file included from ../../chrome/browser/ui/browser_window.h:31:
  ../../chrome/browser/chromeos/apps/intent_helper/apps_navigation_types.h:13:10: fatal error: 'chrome/browser/apps/foundation/app_service/public/mojom/types.mojom.h' file not found
  #include "chrome/browser/apps/foundation/app_service/public/mojom/types.mojom.h"

Original change's description:
> Move the app_service code to //chrome/services
> 
> The app_service code was originally created under //chrome/browser,
> specifically //chrome/browser/apps/foundation. This was because of an
> early concern that the app_service implementation would need to be
> tightly coupled to browser concepts, especially a Profile. More recent
> prototyping suggests that this won't be the case.
> 
> This is just a "git mv" plus some semi-mechanical clean-up, e.g. keeping
> "#include" lines sorted.
> 
> Change-Id: I0e511f5cab636afb7ac5e5235139873d75230377
> Reviewed-on: https://chromium-review.googlesource.com/c/1312435
> Reviewed-by: Dominic Battré <battre@chromium.org>
> Reviewed-by: Avi Drissman <avi@chromium.org>
> Reviewed-by: Ken Rockot <rockot@google.com>
> Reviewed-by: Dominick Ng <dominickn@chromium.org>
> Commit-Queue: Nigel Tao <nigeltao@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#605876}

TBR=avi@chromium.org,battre@chromium.org,rockot@google.com,dominickn@chromium.org,nigeltao@chromium.org

Change-Id: I24d6e63366a96f0bf24ce62c74951187e2151bca
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/1321771
Reviewed-by: Dmitry Titov <dimich@chromium.org>
Commit-Queue: Dmitry Titov <dimich@chromium.org>
Cr-Commit-Position: refs/heads/master@{#605882}
Former-commit-id: 8ea3fece31ce5780ea5b999b9451bac3aec7ee60