Revert of cmaa, gpu: use R8 image texture when GL_NV_image_formats is available. (patchset #4 id:60001 of https://codereview.chromium.org/2693653002/ )
Reason for revert:
This breaks:
https://build.chromium.org/p/chromium.gpu/builders/Linux%20Debug%20%28NVIDIA%...

Error from the output:
[4533:4533:0307/120003.054303:1731388651:ERROR:gles2_cmd_apply_framebuffer_attachment_cmaa_intel.cc(647)]
ApplyFramebufferAttachmentCMAAINTEL: shader compilation failed:
GL_FRAGMENT_SHADER shader compilation failed: 0(1) : error C0000: syntax error,
unexpected $undefined at token "<undefined>"
0(1) : error C0155: integer constant overflow
0(4) : warning C7022: unrecognized profile specifier "highp"
0(4) : warning C7022: unrecognized profile specifier "precision"

Original issue's description:
> cmaa, gpu: use R8 image texture when GL_NV_image_formats is available.
>
> Recently Mesa supports GL_NV_image_formats extension for r8 image texture for ES 3.1.
> https://bugs.freedesktop.org/show_bug.cgi?id=98480
> So CMAA can use R8 texture, instead of RGBA8.
>
> In addition, CMAA implementation checks R8 support tests, and it slows down GPU
> initialization. Remove all unnecessary tests and just check certain extensions.
>
> BUG=535198, 642290
> CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.android:android_optional_gpu_tests_rel;master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel
>
> Review-Url: https://codereview.chromium.org/2693653002
> Cr-Commit-Position: refs/heads/master@{#455170}
> Committed: https://chromium.googlesource.com/chromium/src/+/78181bc198f0a8f7524a5aff3f85876a8747f6dc [formerly 8d2609f6aa6f0a9f8ae238b8af06770337d726eb]

TBR=dongseong.hwang@chromium.org,piman@chromium.org,kbr@chromium.org,machenbach@chromium.org,dongseong.hwang@intel.com
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=535198, 642290

Review-Url: https://codereview.chromium.org/2738213003
Cr-Commit-Position: refs/heads/master@{#455805}

Former-commit-id: 870bce2d5e6ed3ba5d7b513b69d55fdb26efc2d6