Revert "Make AppMenuModel keep most submenus in a vector."
This reverts commit b01ea5dd4177ed3eb197c374f1528100aa3945be [formerly 849315dd50b3cb3ea9c1b4cf0d2f880fbce5022e].

Reason for revert: Suspecting this CL for compile failures on windows e.g. https://ci.chromium.org/p/chrome/builders/ci/win64-builder-perf/127136
[7893/15918] CXX obj/chrome/browser/ui/ui/app_menu_model.obj
FAILED: obj/chrome/browser/ui/ui/app_menu_model.obj
c:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
../../chrome/browser/ui/toolbar/app_menu_model.cc(166,21): error: no class named 'HelpMenuModel' in 'AppMenuModel'
class AppMenuModel::HelpMenuModel : public ui::SimpleMenuModel {
~~~~~~~~~~~~~~^
../../chrome/browser/ui/toolbar/app_menu_model.cc(819,41): error: unknown type name 'HelpMenuModel'; did you mean 'AppMenuModel'?
sub_menus_.push_back(std::make_unique<HelpMenuModel>(this, browser_));
^~~~~~~~~~~~~
AppMenuModel

Original change's description:
> Make AppMenuModel keep most submenus in a vector.
> 
> They are only needed for ownership, so no need to give them names and concrete
> types. Removes some forward declarations from the header and serendipitously
> happens to remove GOOGLE_CHROME_BUILD from the header as well.
> 
> No intended behavior change.
> 
> Bug: 961769
> Change-Id: Ibaaf3375bd9d367b4cc83b9a8ec3e64193750a69
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1894032
> Commit-Queue: Robert Sesek <rsesek@chromium.org>
> Auto-Submit: Nico Weber <thakis@chromium.org>
> Reviewed-by: Robert Sesek <rsesek@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#711431}

TBR=thakis@chromium.org,rsesek@chromium.org

Change-Id: I40cdc0d770d2d49ed568fb2c7d22fa791088c0a2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 961769
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1893861
Reviewed-by: Kevin McNee <mcnee@chromium.org>
Commit-Queue: Kevin McNee <mcnee@chromium.org>
Cr-Commit-Position: refs/heads/master@{#711450}

Former-commit-id: 49b10b7cb6946cce66463a103dbe3d40f9ffea1f