Fix -Wdefaulted-function-deleted warning
This is part of cleaning up for a new Clang warning that's currently disabled:

In file included from ../../ash/app_list/home_launcher_gesture_handler.cc:19:
../../ash/wm/window_transient_descendant_iterator.h:69:43: error: explicitly
defaulted copy assignment operator is implicitly deleted
[-Werror,-Wdefaulted-function-deleted]
  WindowTransientDescendantIteratorRange& operator=(
                                          ^
../../ash/wm/window_transient_descendant_iterator.h:72:37: note: copy
assignment operator of 'WindowTransientDescendantIteratorRange' is implicitly
deleted because field 'begin_' has an inaccessible copy assignment operator
  WindowTransientDescendantIterator begin_;
                                    ^

Bug: 890307
Change-Id: Ic47bc989f9fe26e1387f9a6a8c00f19fcf6b91ce
Reviewed-on: https://chromium-review.googlesource.com/c/1340331
Commit-Queue: Hans Wennborg <hans@chromium.org>
Reviewed-by: Robert Flack <flackr@chromium.org>
Cr-Commit-Position: refs/heads/master@{#609220}
Former-commit-id: b380e5d7324864fc5c60eca905be80d54c7a787b