Revert "parallel_emerge: Implement prefetching of packages."
This reverts commit 710ab070f98cc65337bffcfddcfa6fb20acba84b
See I6edfe0b5.

We see failures like this:
Traceback (most recent call last):
  File "/home/chrome-bot/trunk/chromite/bin/parallel_emerge", line 64, in <module>
    ret = target()
  File "/home/chrome-bot/trunk/chromite/scripts/parallel_emerge.py", line 1658, in main
    scheduler.Run()
  File "/home/chrome-bot/trunk/chromite/scripts/parallel_emerge.py", line 1469, in Run
    self._Retry()
  File "/home/chrome-bot/trunk/chromite/scripts/parallel_emerge.py", line 1413, in _Retry
    if self._Schedule(target):
  File "/home/chrome-bot/trunk/chromite/scripts/parallel_emerge.py", line 1307, in _Schedule
    this_pkg = pkg_state.info
AttributeError: 'str' object has no attribute 'info'

Example: http://chromegw.corp.google.com/i/chromeos/builders/x86-alex%20canary/builds/1829/steps/UnitTest%20%5Bx86-alex%5D/logs/stdio

BUG=chromium-os:13401
TEST=none

Change-Id: I7b9dabd323613be45ea60b0a70b36f9f9ed936f1
Reviewed-on: https://gerrit.chromium.org/gerrit/19033
Reviewed-by: David James <davidjames@chromium.org>
Tested-by: David James <davidjames@chromium.org>