Revert "Roll src/third_party/perfetto 56445ec1e273..13e2ebff3976 (14 commits)"
This reverts commit 0422d4e7b04b2b912caf5749b6e4e512b4169171 [formerly 943d8a16229c2a0ade3a160db2f1170e46b4f23c].

Reason for revert: https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/win32-rel/11038

../../third_party/perfetto/include\perfetto/base/string_writer.h(117,31):  error: use of undeclared identifier 'strndup'


Original change's description:
> Roll src/third_party/perfetto 56445ec1e273..13e2ebff3976 (14 commits)
> 
> https://android.googlesource.com/platform/external/perfetto.git/+log/56445ec1e273..13e2ebff3976
> 
> 
> git log 56445ec1e273..13e2ebff3976 --date=short --no-merges --format='%ad %ae %s'
> 2019-02-11 hjd@google.com Merge "Fix Chromium roll"
> 2019-02-11 ilkos@google.com Fix g3 compilation
> 2019-02-11 rsavitski@google.com Merge "heapprofd cts test: add profileable and release apps"
> 2019-02-11 ilkos@google.com Merge "Allow variant type for non-primary key elements"
> 2019-02-11 eseckler@google.com Merge "base: Fix string writer win compile for chromium roll."
> 2019-02-11 taylori@google.com Merge "perfetto-ui: Show vertical line on note preview"
> 2019-02-11 ilkos@google.com Fix -q flag for empty results set
> 2019-02-11 lalitm@google.com Merge "trace_processor: add support for systrace output"
> 2019-02-11 ilkos@google.com Merge "Allow loading a query file and remaining in an interactive shell"
> 2019-02-08 eseckler@google.com Merge "service: Add stats for discarded chunks + patches"
> 2019-02-08 hjd@google.com Merge "Add protozero static lib target"
> 2019-02-08 fmayer@google.com Merge "Use PLOG for CHECK."
> 2019-02-08 lalitm@google.com Merge "perfetto: add string writer class for formatting strings"
> 2019-02-08 fmayer@google.com Merge "Pad fuzzer input to 2^n * kPageSize."
> 
> 
> Created with:
>   gclient setdep -r src/third_party/perfetto@13e2ebff3976
> 
> The AutoRoll server is located here: https://autoroll.skia.org/r/perfetto-chromium-autoroll
> 
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+/master/autoroll/README.md
> 
> If the roll is causing failures, please contact the current sheriff, who should
> be CC'd on the roll, and stop the roller if necessary.
> 
> 
> TBR=perfetto-bugs@google.com
> 
> Change-Id: Iaba87ec3dda9cece7804df5f72be4cb4c1c02573
> Reviewed-on: https://chromium-review.googlesource.com/c/1464240
> Reviewed-by: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/master@{#630847}

TBR=chromium-autoroll@skia-public.iam.gserviceaccount.com,perfetto-bugs@google.com

Change-Id: I66d046ffa81e6fe9aa6140d5bc4836afee119799
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/1464500
Reviewed-by: Nico Weber <thakis@chromium.org>
Commit-Queue: Nico Weber <thakis@chromium.org>
Cr-Commit-Position: refs/heads/master@{#630857}
Former-commit-id: 28f0ecf737961e617855127b08c7526e326669b4