Raise an exception when the wpr_archive_info isn't created.
This is to provide a more user friendly error. This:

  AssertionError: Pageset archive_data_file path must be specified.

instead of this:

  AttributeError: 'NoneType' object has no attribute 'AddNewTemporaryRecording'

BUG=

Review URL: https://codereview.chromium.org/660143002

Cr-Commit-Position: refs/heads/master@{#300050}

Former-commit-id: 29846e0abbd27b05029bb3e937a6bdcbc1f31b0e