Kerberos: Switch to async/await pattern
Switches the Kerberos browser tests from a .then(()=>{...}) pattern
to a pattern using async/await. This reduces nesting and improves error
messages.

Also removes the done() function used in a couple of places. That's not
necessary anymore since we switched to from setTimeout() to flushTasks()
in a previous CL. This improves error messages, e.g.
  [260227:260227:0812/190044.402413:ERROR:web_ui_browser_test.cc(548)] JS ERROR: '[260227:260227:0812/190017.264389:ERROR:CONSOLE(2277)] "Uncaught (in promise) AssertionError: expected 49 to equal 0", source: file:///usr/local/google/home/ljusten/chromium/src/third_party/chaijs/chai.js (2277)
vs
  [261366:261366:0812/190333.758659:ERROR:CONSOLE(49)] "Mocha test failed: KerberosAddAccountTests AdvancedConfigurationValidationError
  AssertionError: expected 49 to equal 0
      at Function.assert.strictEqual (file:///usr/local/google/home/ljusten/chromium/src/third_party/chaijs/chai.js:2277:32)
      at assertEquals (file:///usr/local/google/home/ljusten/chromium/src/chrome/test/data/webui/test_api.js:818:15)
      at Context.<anonymous> (file:///usr/local/google/home/ljusten/chromium/src/chrome/test/data/webui/settings/chromeos/people_page_kerberos_accounts_test.js:704:7)

BUG=952232
TEST=Ran browser test

Change-Id: If2202ba53679eeb83c50eb87bfb14d2691d07881
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1748697
Reviewed-by: Michael Giuffrida <michaelpg@chromium.org>
Commit-Queue: Lutz Justen <ljusten@chromium.org>
Auto-Submit: Lutz Justen <ljusten@chromium.org>
Cr-Commit-Position: refs/heads/master@{#689374}

Former-commit-id: 6758a0879931bc4df630a80a36c82d7855ae3155