Revert "Chrome updater: implement support for creating task scheduler tasks."
This reverts commit 3b16112231d1b33f62ca128f5511226fc0d9ebe8 [formerly 9d00bfef3d2bccc26dee145a23a55750475216ee].

Reason for revert: Broke the build on win-archive-rel

[34793/69495] CXX obj/chrome/updater/win/test/updater_test_process/test_process_main.obj
FAILED: obj/chrome/updater/win/test/updater_test_process/test_process_main.obj
C:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\thi...
../../chrome/updater/win/test/test_process_main.cc(23,12): error: no member named 'InitializeOSUtils' in namespace 'updater'
updater::InitializeOSUtils();
~~~~~~~~~^
1 error generated.

Original change's description:
> Chrome updater: implement support for creating task scheduler tasks.
> 
> This CL implements the updater::TaskScheduler class to allow
> creating scheduled tasks using Windows's task scheduler.
> 
> The code is similar to what //chrome/chrome_cleaner/os has for this
> purpose. Future refactoring work to eliminate duplicated code is
> possible but unknown at this point how such effort could proceed.
> 
> Several dependencies are needed for unit testing this code. The
> general idea is that a program is invoked by the unit tests
> scheduled tasks. To detect that such program has run, synchronization
> with the unit test execution is required.
> 
> Since the MS task scheduler API is finicky, minimal changes were done to
> the TaskScheduler class implementation.
> 
> Bug: 992551
> Change-Id: Ia315fa1d2b6d711b0639af20878e96a3659523b1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1747031
> Commit-Queue: Sorin Jianu <sorin@chromium.org>
> Reviewed-by: Joshua Pawlicki <waffles@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#686267}

TBR=sorin@chromium.org,waffles@chromium.org

Change-Id: Ib7ad61b3dfda22281a14f59b550270058e9bd668
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 992551
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1750522
Reviewed-by: Fergus Dall <sidereal@google.com>
Commit-Queue: Fergus Dall <sidereal@google.com>
Cr-Commit-Position: refs/heads/master@{#686278}

Former-commit-id: dc886bed0eed7ba9377d832e9d24110d2cfa51d3