Bump archived bitcode test revs to 11284.
Version 11284 is the version we currently assume for the
Examples App, and for the browser translator.  If the bot
goes red, that is *sort of* a sign to update them.

Bot can still go red because of superfluous driver changes
(such as commandline flags).  Also doesn't reflect the
current bitcode ABI, since it is the frontend that does
verification right now.  Bot can miss stuff like calling
convention changes, since it only tests against irt_core.

Bump both the archived frontend test and archived pexe test,
since both are broken right now.

One of the current errors:

__PNACL_GENERATED:<SRPC stream>:function __unnamed_1692: error: undefined reference to '_Unwind_Resume'

BUG=none
R=dschuff@chromium.org

Review URL: https://codereview.chromium.org/15367009

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@11369 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2

Former-commit-id: e028f0d8e77e3d4fd4415be7ec703450161825eb