Revert of Play Host Audio on Android (patchset #6 id:160001 of https://codereview.chromium.org/1867993002/ )
Reason for revert:
Breaks linking on clang-clankium-tot-builder:
https://uberchromegw.corp.google.com/i/internal.client.clank_tot/builders/clang-clankium-tot-builder/builds/24966

obj/remoting/client/jni/remoting_client_jni.chromoting_jni_instance.o:../../remoting/client/jni/chromoting_jni_instance.cc:function remoting::ChromotingJniInstance::ConnectToHostOnNetworkThread(): error: undefined reference to 'remoting::AudioPlayerAndroid::AudioPlayerAndroid()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Original issue's description:
> Play Host Audio on Android
>
> Currently we are sending host audio packets to the android client but
> on Android we just ignore all these packets. This change is to play host
> audio on Android.
>
> Doc: https://docs.google.com/a/google.com/document/d/18N4qEpm9gVTpmoS0j1XBkFZvmU8Dopb7FCpqIiMzvtY/edit?usp=sharing
>
> BUG=270421
>
> Committed: https://crrev.com/ca85874fcb9086b99a58e6af92ec60c04715ce82 [formerly bb926d66aa44663a738c03be3b14cd674a48bfba]
> Cr-Commit-Position: refs/heads/master@{#387124}

TBR=sergeyu@chromium.org,yuweih@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=270421

Review URL: https://codereview.chromium.org/1887883002

Cr-Commit-Position: refs/heads/master@{#387153}

Former-commit-id: e6f6000962d52c4fb23343dcabc1d8de35214b52