[chromium] Unreviewed build fix on Linux clang.
../../third_party/WebKit/Source/WebKit/chromium/src/FrameLoaderClientImpl.cpp:1055:63: error:
C++98 requires an accessible copy constructor for class 'WebKit::WebCachedURLRequest' when binding
a reference to a temporary; was private [-Werror,-Wbind-to-temporary-copy]

* src/FrameLoaderClientImpl.cpp:
(WebKit::FrameLoaderClientImpl::dispatchWillRequestResource):

git-svn-id: svn://svn.chromium.org/blink/trunk@135877 bbb929c8-8fbe-4397-9dbb-9b2b20218538
Former-commit-id: c5a1e760d6724d927d4fec30ddd0ddd714486eb2