Revert of Add SingleLogSource to system_logs sources (patchset #16 id:300001 of https://codereview.chromium.org/2844163005/ )
Reason for revert:
Broke chromeos builder:
https://build.chromium.org/p/chromiumos.chromium/builders/x86-generic-tot-chromium-pfq-informational/builds/11856

chromeos-chrome-60.0.3098.0_alpha-r1: FAILED: obj/chrome/browser/chromeos/chromeos/single_log_source.o
chromeos-chrome-60.0.3098.0_alpha-r1: i686-pc-linux-gnu-g++ -B/usr/x86_64-pc-linux-gnu/i686-pc-linux-gnu/binutils-bin/2.25.51-gold -MMD -MF obj/chrome/browser/chromeos/chromeos/single_log_source.o.d -DUSE_CRAS -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_ASH=1 -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DOS_CHROMEOS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DUSE_EGL -DTOOLKIT_VIEWS=1 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_SUPPORT_GPU=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DV8_USE_EXTERNAL_STARTUP_DATA -DMESA_EGL_NO_X11_HEADERS -DLEVELDB_PLATFORM_CHROMIUM=1 -DFEATURE_ENABLE_VOICEMAIL -DEXPAT_RELATIVE_PATH -DGTEST_RELATIVE_PATH -DNO_SOUND_SYSTEM -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DCHROMEOS -I../../../../../../../home/chrome-bot/chrome_root/src -Igen -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/khronos -I../../../../../../../home/chrome-bot/chrome_root/src/gpu -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/protobuf/src -Igen/protoc_out -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/protobuf/src -I../../../../../../../home/chrome-bot/chrome_root/src/skia/config -I../../../../../../../home/chrome-bot/chrome_root/src/skia/ext -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/skia/include/c -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/skia/include/config -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/skia/include/core -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/skia/include/effects -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/skia/include/images -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/skia/include/lazy -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/skia/include/pathops -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/skia/include/pdf -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/skia/include/pipe -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/skia/include/ports -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/skia/include/utils -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/skia/third_party/vulkan -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/skia/include/gpu -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/skia/src/gpu -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/skia/src/sksl -Igen -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/ced/src -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/icu/source/common -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/icu/source/i18n -Igen -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/libwebm/source -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/boringssl/src/include -I/build/x86-generic/usr/include/nss -I/build/x86-generic/usr/include/nspr -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/WebKit -Igen/third_party/WebKit -I../../../../../../../home/chrome-bot/chrome_root/src/v8/include -Igen/v8/include -Igen/components/metrics/proto -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/re2/src -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/mesa/src/include -Igen -I/build/x86-generic/usr/include/dbus-1.0 -I/build/x86-generic/usr/lib/dbus-1.0/include -Igen -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/cacheinvalidation/overrides -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/cacheinvalidation/src -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/leveldatabase -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/leveldatabase/src -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/leveldatabase/src/include -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/libusb/src/libusb -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/webrtc_overrides -I../../../../../../../home/chrome-bot/chrome_root/src/testing/gtest/include -I../../../../../../../home/chrome-bot/chrome_root/src/third_party -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/webrtc_overrides -I../../../../../../../home/chrome-bot/chrome_root/src/third_party -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/zlib -fno-strict-aliasing -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -m32 -msse2 -mfpmath=sse -mmmx -pthread -Wall -Werror -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-unused-parameter -Os -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g2 -gsplit-dwarf --sysroot=../../../../../../../build/x86-generic -fvisibility=hidden -std=gnu++11 -Wno-narrowing -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -march=i686 -pipe -march=i686 -pipe -pipe -march=i686 -mfpmath=sse -mmmx -msse -msse2 -msse3 -D__google_stl_debug_vector=1 -femit-struct-debug-reduced -c ../../../../../../../home/chrome-bot/chrome_root/src/chrome/browser/chromeos/system_logs/single_log_source.cc -o obj/chrome/browser/chromeos/chromeos/single_log_source.o
chromeos-chrome-60.0.3098.0_alpha-r1: ../../../../../../../home/chrome-bot/chrome_root/src/chrome/browser/chromeos/system_logs/single_log_source.cc: In function 'std::string system_logs::{anonymous}::GetLogFileSourceFilename(system_logs::SingleLogSource::SupportedSource)':
chromeos-chrome-60.0.3098.0_alpha-r1: ../../../../../../../home/chrome-bot/chrome_root/src/chrome/browser/chromeos/system_logs/single_log_source.cc:25:1: error: control reaches end of non-void function [-Werror=return-type]

Original issue's description:
> Add new SystemLogsSource type: SingleLogSource
>
> This patch adds a new type of SystemLogsSource, SingleLogSource, which
> provides a single log source in contrast to the many log sources provided
> by the other implementations of SystemLogsSource.
>
> The SingleLogSource currently supports incremental read of a limited set
> of log files. It can be expanded to include other log files and other log
> sources.
>
> BUG=chromium:715263
>
> Review-Url: https://codereview.chromium.org/2844163005
> Cr-Commit-Position: refs/heads/master@{#471353}
> Committed: https://chromium.googlesource.com/chromium/src/+/3248b228db9406487c791a2835b4740197cb7c7d [formerly def38083bf08ec479bcb340b8f8c6c5529498dd3]

TBR=rkc@chromium.org,afakhry@chromium.org,sque@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=chromium:715263

Review-Url: https://codereview.chromium.org/2883553002
Cr-Commit-Position: refs/heads/master@{#471408}

Former-commit-id: d6ad23b81b42444c6e7ecb4d14fe053b01a0ba26