Revert "Support for unicorn accounts."
This reverts commit 71dffe0daa050be3b13df5856f866c96e1873d12 [formerly 03eb5c4559c04ff56869c2d29c4d0af849892586].

Reason for revert: consistently failing test
https://ci.chromium.org/p/chromium/builders/luci.chromium.try/chromeos-amd64-generic-rel/183637
[1/1] telemetry.internal.backends.chrome.cros_unittest.CrOSLoginTest.testGetCredentials failed unexpectedly 0.1409s:
  Traceback (most recent call last):
    File "/b/s/w/ir/third_party/catapult/telemetry/telemetry/internal/backends/chrome/cros_unittest.py", line 83, in testGetCredentials
      self.assertEquals(username, 'user%d@gmail.com' % i)
  AssertionError: 'user1' != 'user1@gmail.com'

Original change's description:
> Support for unicorn accounts.
> 
> * Implement NavigateUnicornLogin which takes child and parent
> credentials.
> * _ClickGaiaButton is a helper that clicks a button on the GAIA page
> with pattern matching.
> * Canonicalize moved into oobe.py from cros_unittest.py
> * _GetCredentials replaced with an iterator since we need multiple lines
> of credentials from credentials.txt. testGetCredentials is the unit
> test.
> * testUnicornLogin to unit test NavigateUnicornLogin.
> 
> BUG=chromium:924290
> TEST=testUnicornLogin
> TBR=perezju@chromium.org
> 
> Change-Id: I799f48f9d35c93e372743cf3045440e09516f15c
> Reviewed-on: https://chromium-review.googlesource.com/c/1444734
> Reviewed-by: Achuith Bhandarkar <achuith@chromium.org>
> Commit-Queue: Achuith Bhandarkar <achuith@chromium.org>

TBR=achuith@chromium.org,dhaddock@chromium.org,perezju@chromium.org

Change-Id: I77ce2aec86c268c380c5be5059dc066e6d44357b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: chromium:924290
Reviewed-on: https://chromium-review.googlesource.com/c/1451111
Reviewed-by: Ben Hayden <benjhayden@chromium.org>
Commit-Queue: Ben Hayden <benjhayden@chromium.org>

Former-commit-id: 7495e29869df055cf838bad90b54e29438d70228