Revert 285661 "Remove some dead app host code."
Causes compile failures on official builders:

e.g.,
http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Win/

FAILED: ninja -t msvc -e environment.x64 -- c:\b\build\goma/gomacc "c:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\chrome\installer\util\installer_util_nacl_win64.chrome_app_host_distribution.obj.rsp /c ..\..\chrome\installer\util\chrome_app_host_distribution.cc /Foobj\chrome\installer\util\installer_util_nacl_win64.chrome_app_host_distribution.obj /Fdobj\chrome\installer_util_nacl_win64.cc.pdb 
c:\b\build\slave\google-chrome-rel-win\build\src\chrome\installer\util\chrome_app_host_distribution.cc(126) :error C2065: 'kChromeAppHostGuid' : undeclared identifier
ninja: build stopped: subcommand failed.


> Remove some dead app host code.
> 
> app_host.exe was removed in r220555. This change removes some dead code
> that was left behind. Specifically:
> - chrome_launcher_support no longer exposes any methods related to the
>   AppHost.
> - Chrome's uninstall prompt no longer has a special case to handle
>   suppressing the "delete your profile" checkbox.
> - Chrome and its installer no longer have a dependency on
>   launcher_support.
> - The installer no longer supports installing items from the webstore.
> - GetUntrustedDataValue no longer has consumers and is gone.
> 
> BUG=297647
> R=benwells@chromium.org,huangs@chromium.org,gab@chromium.org
> 
> Review URL: https://codereview.chromium.org/422453004

TBR=grt@chromium.org

Review URL: https://codereview.chromium.org/422593002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@285706 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: efde268d313a402ff730906cc30719d71a7e07b0