Fix generate_buildbot_json_unittest.py to work on Windows.
The comparison in generate_buildbot_json_unittest.py was looking
for forward slashes v/s backslashes on Windows, causing a
presubmit error at line 22:
KeyError: '..\\..\\infra\\config\\global\\luci-milo.cfg'.

Bug: 844261
Change-Id: I14418248409d58a451d9bd0520f24fcc50d27a2a
Reviewed-on: https://chromium-review.googlesource.com/1064475
Reviewed-by: Kenneth Russell <kbr@chromium.org>
Commit-Queue: Kenneth Russell <kbr@chromium.org>
Cr-Commit-Position: refs/heads/master@{#559761}
Former-commit-id: 808efbb28c52cb8077f2a07fe471fc5c92fe8691