Revert 98168, it caused compile errors on mac:
/b/build/slave/cr-mac-rel/build/src/chrome/browser/safe_browsing/browser_feature_extractor.cc:456:12:error: no member named 'set_suffix_prefix_hash' in 'safe_browsing::ClientPhishingRequest'
  request->set_suffix_prefix_hash(
  ~~~~~~~  ^
1 error generated.

/b/build/slave/cr-mac-rel/build/src/chrome/browser/safe_browsing/client_side_detection_service.cc:281:20:error: no member named 'has_suffix_prefix_hash' in 'safe_browsing::ClientPhishingRequest'
  if (full_request.has_suffix_prefix_hash()) {
      ~~~~~~~~~~~~ ^
/b/build/slave/cr-mac-rel/build/src/chrome/browser/safe_browsing/client_side_detection_service.cc:282:24:error: no member named 'set_suffix_prefix_hash' in 'safe_browsing::ClientPhishingRequest'
    sanitized_request->set_suffix_prefix_hash(
    ~~~~~~~~~~~~~~~~~  ^
/b/build/slave/cr-mac-rel/build/src/chrome/browser/safe_browsing/client_side_detection_service.cc:283:22:error: no member named 'suffix_prefix_hash' in 'safe_browsing::ClientPhishingRequest'
        full_request.suffix_prefix_hash());
        ~~~~~~~~~~~~ ^
3 errors generated.

Add support for client-side phishing detection for non-UMA users.

In this mode, a sanitized pingback is sent that does not include the URL or any
tokens extracted from the URL or page content.  Currently, this feature is
behind a command-line flag.

BUG=none
TEST=ClientSideDetectionServiceTest,BrowserFeatureExtractorTest


Review URL: http://codereview.chromium.org/7635010

TBR=bryner@chromium.org
Review URL: http://codereview.chromium.org/7746011

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@98170 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 3b700c860d3297726f9f403ce2ef5345040dfaca