Revert of sOfNodeAreVisuallyDistinctPositions() should return true when having invisible children (patchset #1 id:1 of https://codereview.chromium.org/1764873003/ )
Reason for revert:
Compile failed:
https://build.chromium.org/p/chromium.webkit/builders/WebKit%20Linux%20non-Oilpan%20Builder/builds/1574

FAILED: /b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/WebKit/Source/web/webkit_unit_tests/VisibleUnitsTest.o.d -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -DENABLE_MDNS=1 -DENABLE_NOTIFICATIONS -DENABLE_PEPPER_CDMS -DENABLE_PLUGINS=1 -DENABLE_PDF=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_UDEV -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_CLIPBOARD_AURAX11=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_GLIB=1 -DUSE_OPENSSL=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DENABLE_WEBRTC=1 -DENABLE_EXTENSIONS=1 -DENABLE_CONFIGURATION_POLICY -DENABLE_TASK_MANAGER=1 -DENABLE_THEMES=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_TOPCHROME_MD=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=261368-1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBLINK_IMPLEMENTATION=1 -DINSIDE_BLINK -DGL_GLEXT_PROTOTYPES -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=0 -DGTEST_HAS_RTTI=0 -DMOJO_USE_SYSTEM_IMPL -DMOJO_USE_GLES2_IMPL -DTOOLKIT_VIEWS=1 -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_SUPPORT_GPU=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DUSE_LIBJPEG_TURBO=1 -DENABLE_LAYOUT_UNIT_IN_INLINE_BOXES=0 -DWTF_USE_CONCATENATED_IMPULSE_RESPONSES=1 -DENABLE_INPUT_MULTIPLE_FIELDS_UI=1 -DWTF_USE_ICCJPEG=1 -DWTF_USE_QCMSLIB=1 -DWTF_USE_WEBAUDIO_FFMPEG=1 -DWTF_USE_DEFAULT_RENDER_THEME=1 -DCHROME_PNG_WRITE_SUPPORT -DPNG_USER_CONFIG -DUNIT_TEST -DLIBXSLT_STATIC -I../.. -Igen -I../../third_party/WebKit/Source -I../../third_party/WebKit -Igen/blink -I../../build/linux/debian_wheezy_amd64-sysroot/usr/include/glib-2.0 -I../../build/linux/debian_wheezy_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../third_party/khronos -I../../gpu -I../../third_party/libwebp -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../testing/gtest/include -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/include/gpu -I../../third_party/skia/src/gpu -I../../third_party/WebKit -I../../v8/include -I../../third_party/npapi -I../../third_party/npapi/bindings -I../../third_party/libjpeg_turbo -I../../third_party/iccjpeg -I../../third_party/libpng -I../../third_party/zlib -I../../third_party/ots/include -I../../third_party/qcms/src -I../../v8/include -I../../testing/gmock/include -I../../third_party/WebKit/Source -Igen/blink -I../../third_party/angle/include -I../../third_party/libxml/src/include -I../../third_party/libxml/linux/include -I../../third_party/libxslt -I../../third_party/snappy/src -I../../third_party/snappy/linux -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -fcolor-diagnostics -fdebug-prefix-map=/b/build/slave/WebKit_Linux_non-Oilpan_Builder/build/src=. -pthread -m64 -march=x86-64 -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-shift-negative-value -O2 -fno-ident -fdata-sections -ffunction-sections -g0 --sysroot=../../build/linux/debian_wheezy_amd64-sysroot -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -plugin-arg-find-bad-constructs -Xclang follow-macro-expansion -Wheader-hygiene -Wstring-conversion -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libBlinkGCPlugin.so -Xclang -add-plugin -Xclang blink-gc-plugin -DLIBXML_STATIC= -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -fno-rtti -fno-exceptions -c ../../third_party/WebKit/Source/core/editing/VisibleUnitsTest.cpp -o obj/third_party/WebKit/Source/web/webkit_unit_tests/VisibleUnitsTest.o
../../third_party/WebKit/Source/core/editing/VisibleUnitsTest.cpp:1316:11: error: no viable conversion from 'WTF::PassRefPtr<Element>' to 'blink::Node *'
    Node* button = document().querySelector("button", ASSERT_NO_EXCEPTION);
          ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../third_party/WebKit/Source/wtf/PassRefPtr.h:90:5: note: candidate function
    operator UnspecifiedBoolType() const { return m_ptr ? &PassRefPtr::m_ptr : 0; }
    ^
../../third_party/WebKit/Source/core/editing/VisibleUnitsTest.cpp:1327:11: error: no viable conversion from 'WTF::PassRefPtr<Element>' to 'blink::Node *'
    Node* button = document().querySelector("button", ASSERT_NO_EXCEPTION);
          ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../third_party/WebKit/Source/wtf/PassRefPtr.h:90:5: note: candidate function
    operator UnspecifiedBoolType() const { return m_ptr ? &PassRefPtr::m_ptr : 0; }

Original issue's description:
> Reland of ndsOfNodeAreVisuallyDistinctPositions() should return true when having invisible children (patchset #1 id:1 of https://codereview.chromium.org/1678223003/ )
>
> Reason for revert:
> The failing of All/ParameterizedWebFrameTest.CompositedSelectionBoundsCleared/1 is due to the test itself, not 9ff84c4fa833f3c8309900b37e04813d81d8d5ce [formerly 7f591ee82d833109224092a1fe60577eb2ad534d]. The test has also been disabled on Mac ASan.
>
> See crbug.com/588769.
>
> Original issue's description:
> > Revert of endsOfNodeAreVisuallyDistinctPositions() should return true when having invisible children (patchset #5 id:80001 of https://codereview.chromium.org/1672693002/ )
> >
> > Reason for revert:
> > Speculative revert to see if it fixes webkit_unit_tests in mac_asan (https://build.chromium.org/p/chromium.memory/builders/Mac%20ASan%2064%20Tests%20(1)). Will reland if this turns out not to be the culprit.
> >
> > Snippet of failure:
> >
> > All/ParameterizedWebFrameTest.CompositedSelectionBoundsCleared/1 (run #1):
> > [ RUN      ] All/ParameterizedWebFrameTest.CompositedSelectionBoundsCleared/1
> > =================================================================
> > ==696==ERROR: AddressSanitizer: heap-use-after-free on address 0x610000001d50 at pc 0x0001125f2895 bp 0x7fff546d09b0 sp 0x7fff546d09a8
> > READ of size 8 at 0x610000001d50 thread T0
> >     #0 0x1125f2894 in blink::PaintLayerScrollableArea::scrollbarsCanBeActive() const (in webkit_unit_tests) + 420
> >     #1 0x10d26f27b in blink::ScrollAnimatorMac::updateScrollerStyle() (in webkit_unit_tests) + 283
> >     #2 0x7fff9180c0cf in +[NSScrollerImpPair _updateAllScrollerImpPairsForNewRecommendedScrollerStyle:] (in AppKit) + 402
> >     #3 0x7fff94de5ed9 in _CFXNotificationPost (in CoreFoundation) + 2553
> >     #4 0x7fff90b0a795 in -[NSNotificationCenter postNotificationName:object:userInfo:] (in Foundation) + 63
> >
> > Original issue's description:
> > > endsOfNodeAreVisuallyDistinctPositions() should return true when having invisible children
> > >
> > > The function should return true when "there is a VisiblePosition inside
> > > an empty inline-block container." (quoted from the comments in this function).
> > >
> > > Previously, the functions only checks DOM tree for emptiness, which
> > > makes it return false when the node has only invisible children.
> > >
> > > This CL checks the layout tree, and returns false only if it finds a child
> > > with non-zero-sized layout object.
> > >
> > > BUG=582247,584030
> > > TEST=webkit_unit_tests --gtest_filter=VisibleUnitsTest.endsOfNodeAreVisuallyDistinctPositions*
> > >
> > > Committed: https://crrev.com/9ff84c4fa833f3c8309900b37e04813d81d8d5ce [formerly 7f591ee82d833109224092a1fe60577eb2ad534d]
> > > Cr-Commit-Position: refs/heads/master@{#374344}
> >
> > TBR=yosin@chromium.org,kojii@chromium.org,xiaochengh@chromium.org
> > # Skipping CQ checks because original CL landed less than 1 days ago.
> > NOPRESUBMIT=true
> > NOTREECHECKS=true
> > NOTRY=true
> > BUG=582247,584030
> >
> > Committed: https://crrev.com/4a9f564e55ceaeaebdae31773785c41a57eca398 [formerly e63dd24d7382dae08d2d83392d8fa410aa0e0b78]
> > Cr-Commit-Position: refs/heads/master@{#374362}
>
> TBR=yosin@chromium.org,kojii@chromium.org,blundell@chromium.org
> # Not skipping CQ checks because original CL landed more than 1 days ago.
> BUG=582247,584030
>
> Committed: https://crrev.com/ceece64b40b10071b2fdd098362c6658fc734972 [formerly ceddbf3f6c5530e28e72e6db694e4925c1aafec8]
> Cr-Commit-Position: refs/heads/master@{#379237}

TBR=yosin@chromium.org,blundell@chromium.org,kojii@chromium.org,xiaochengh@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=582247,584030

Review URL: https://codereview.chromium.org/1760983003

Cr-Commit-Position: refs/heads/master@{#379244}

Former-commit-id: 6097dd9dbd9b98a5297c962bbf7d9d2f7c6da153