Revert of components: Fix a couple of the TODO(GYP) todos. (https://codereview.chromium.org/420113003/)
Reason for revert:
Likely caused build falure:

FAILED: ninja -t msvc -e environment.x86 -- C:\b\build\goma/gomacc "C:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\components\invalidation\invalidation_test_support.invalidator_test_template.obj.rsp /c ..\..\components\invalidation\invalidator_test_template.cc /Foobj\components\invalidation\invalidation_test_support.invalidator_test_template.obj /Fdobj\components\invalidation_test_support.cc.pdb 
c:\b\build\slave\win\build\src\components\invalidation\invalidator_test_template.h(87) : fatalerror C1083: Cannot open include file: 'google/cacheinvalidation/types.pb.h': No such file or directory
ninja: build stopped: subcommand failed.

http://build.chromium.org/p/chromium/builders/Win/builds/22963/steps/compile/logs/stdio



Original issue's description:
> components: Fix a couple of the TODO(GYP) todos.
> 
> BUG=None
> TEST=gn gen out/Debug_gn + build the effected targets with ninja.
> R=brettw@chromium.org
> TBR=jochen@chromium.org
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=286362

TBR=brettw@chromium.org,tfarina@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=None

Review URL: https://codereview.chromium.org/428123002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@286467 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 2238c0fc5a50a92e31a0650b65c164853817650d