Revert of Add PA_LOG() macro to for logging messages specific to Proximity Auth. (patchset #4 id:80001 of https://codereview.chromium.org/1113023006/)
Reason for revert:
Broke GN bots:
http://build.chromium.org/p/chromium.win/builders/Win%20x64%20GN/builds/858/steps/compile/logs/stdio

e:\b\build\slave\win_x64_gn\build\src\components\proximity_auth\logging\logging_unittest.cc(98) :error C2220: warning treated as error - no 'object' file generated
e:\b\build\slave\win_x64_gn\build\src\components\proximity_auth\logging\logging_unittest.cc(98) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data

Original issue's description:
> Add PA_LOG() macro to for logging messages specific to Proximity Auth.
>
> This macro is built on top of the standard logging system defined in
> base/logging.h, but also allows us to show Proximity Auth specific logs in the
> debug WebUI at chrome://proximity-auth.
>
> BUG=409158
> TEST=unit test
>
> Committed: https://crrev.com/ef8ff955298cb7ba3973af5b01471edf89cc61c4 [formerly dda9f80847aa2966b03a9625419fbe01c8e47192]
> Cr-Commit-Position: refs/heads/master@{#328026}

TBR=isherman@chromium.org,tengs@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=409158

Review URL: https://codereview.chromium.org/1125503002

Cr-Commit-Position: refs/heads/master@{#328029}

Former-commit-id: b355a1cccf5910eed5da17e7384a6fee1e829b49