Revert "[iOS] Add drag-n-drop to the omnibox."
This reverts commit ef04f2bb9999e51b1885e68f85dfce64c9c061b0 [formerly 7f7424773cd566fe1b2204d41afc882bc09714fa].

Reason for revert: break compilation with iOS 11 SDK.

../../ios/chrome/browser/drag_and_drop/drop_and_navigate_interaction_unittest.mm:17:33: error: unused variable 'interaction' [-Werror,-Wunused-variable]
    DropAndNavigateInteraction* interaction =
                                ^
1 error generated.


Original change's description:
> [iOS] Add drag-n-drop to the omnibox.
> 
> The purpose of the DropAndNavigateInteraction class is to be added to
> any view where it would make sense to receive a URL.
> For now, that class only handles drags containing URLs, but it could
> optionally generate queries for drags only containing NSStrings,
> UIImages, etc...
> 
> Bug: 753331
> Change-Id: I9643a40b617fcddbb521ebab4746b4bdb36c0273
> Reviewed-on: https://chromium-review.googlesource.com/606648
> Commit-Queue: Jean-François Geyelin <jif@chromium.org>
> Reviewed-by: Sylvain Defresne <sdefresne@chromium.org>
> Reviewed-by: Justin Cohen <justincohen@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#492944}

TBR=jif@chromium.org,sdefresne@chromium.org,justincohen@chromium.org

Change-Id: I4c9c5cd7b998ad47f4e5535e5b2af1b02110e0fe
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 753331
Reviewed-on: https://chromium-review.googlesource.com/608207
Reviewed-by: Sylvain Defresne <sdefresne@chromium.org>
Commit-Queue: Sylvain Defresne <sdefresne@chromium.org>
Cr-Commit-Position: refs/heads/master@{#492951}
Former-commit-id: 93298ef3ef5fcfd59a375654465cfe0c857fbd07