Revert 214254 "Add initial prototype for the GN meta-buildsystem."
It broke the check_licenses step on Android (see http://build.chromium.org/p/chromium.linux/builders/Android%20Builder%20%28dbg%29/builds/39904/steps/check_licenses/logs/stdio):

@@@BUILD_STEP check_licenses@@@
> /b/build/slave/Android_Builder__dbg_/build/src/android_webview/tools/webview_licenses.py scan
Got LicenseError "missing README.chromium or licenses.py SPECIAL_CASES entry" while scanning tools/gn/secondary/base/third_party/dynamic_annotations
Got LicenseError "missing README.chromium or licenses.py SPECIAL_CASES entry" while scanning tools/gn/secondary/third_party/modp_b64
< /b/build/slave/Android_Builder__dbg_/build/src/android_webview/tools/webview_licenses.py scan
ERROR: process exited with code 2
@@@STEP_FAILURE@@@


> Add initial prototype for the GN meta-buildsystem.
> 
> This is currently not hooked into the build. To build, add a reference to the
> gn.gyp file to build/all.gyp
> 
> R=darin@chromium.org, scottmg@chromium.org
> 
> Review URL: https://codereview.chromium.org/21114002

TBR=brettw@chromium.org

Review URL: https://codereview.chromium.org/21084010

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@214325 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 69a4548e0ab3fbb1531b4df89708bfab9cf0df20