Revert "Remove input field selection regression in Gallery"
This reverts commit f55153d0cef1f8db2138ed70438df3793c1b6417 [formerly eff97af594b79428ab62e834a09fd99646e7beab].

Reason for revert: Can cause "Uncaught TypeError: input.select is not a function"

Bug: 931157

Original change's description:
> Remove input field selection regression in Gallery
> 
> Change https://chromium-review.googlesource.com/c/chromium/src/+/1217747/
> introduced a side-effect that causes the entire input field to be
> selected on a focus event. In the gallery app this caused the Width
> input field to be fully selected when doing an image resize. This
> change explicitly sets the selection to the end of the field as it
> used to work before the regression.
> 
> Bug: 914741
> Tests: Ran all browser and unit tests, manually checked as well.
> Change-Id: I579660ebdbad43bd8ab739c76ada7289f3e6d943
> Reviewed-on: https://chromium-review.googlesource.com/c/1453696
> Reviewed-by: Joel Hockey <joelhockey@chromium.org>
> Commit-Queue: Alex Danilo <adanilo@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#629349}

TBR=joelhockey@chromium.org,adanilo@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 914741
Change-Id: I1d0777f3118b4a2c6eaf8d3fd51c509c3ca587d1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1519947
Reviewed-by: Trent Apted <tapted@chromium.org>
Reviewed-by: Joel Hockey <joelhockey@chromium.org>
Commit-Queue: Trent Apted <tapted@chromium.org>
Cr-Commit-Position: refs/heads/master@{#640215}
Former-commit-id: 5e6e5df2994ca4c9c012f8f4133981841f3ae04a