Rolling GYP to r1568. Changes:
- r1568: Reverting accidental change to test/lib/TestGyp.py (from r1567)
- r1567: Speculative fix for mt.exe general error c101008a (The parameter is incorrect).
- r1566: Xcode: Coalesce multiple "copies" sections in the same target with the same "destination" property into the same PBXCopyFilesBuildPhase.

BUG=173052

TBR=scottmg@chromium.org

Review URL: https://codereview.chromium.org/12204002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@180567 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 41db7a692d977b3c13bc1f968c100315a702ad03