Revert "Move EventAutoRepeatHandler out of /evdev umbrella"
This reverts commit 3126af4baa64760a3ca02f4e23ca1f1b02519da5 [formerly f3dfbe6fae0e36d136900587695f35b1846df4a6].

Reason for revert: Build failure causing a tree closure:
https://ci.chromium.org/buildbot/chromium.chromiumos/linux-chromeos-dbg/3890

Snippet from test:
FAILED: libevents_ozone_evdev.so libevents_ozone_evdev.so.TOC 
python "../../build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="nm" --sofile="./libevents_ozone_evdev.so" --tocfile="./libevents_ozone_evdev.so.TOC" --output="./libevents_ozone_evdev.so"  -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -lpthread -Wl,--as-needed -fuse-ld=gold -B../../third_party/binutils/Linux_x64/Release/bin -Wl,--threads -Wl,--thread-count=4 -Wl,--icf=all -m64 -Werror -Wl,--gdb-index -Wl,--fatal-warnings -nostdlib++ --sysroot=../../build/linux/debian_stretch_amd64-sysroot -L../../build/linux/debian_stretch_amd64-sysroot/lib/x86_64-linux-gnu -Wl,-rpath-link=../../build/linux/debian_stretch_amd64-sysroot/lib/x86_64-linux-gnu -L../../build/linux/debian_stretch_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath-link=../../build/linux/debian_stretch_amd64-sysroot/usr/lib/x86_64-linux-gnu -o "./libevents_ozone_evdev.so" -Wl,-soname="libevents_ozone_evdev.so" @"./libevents_ozone_evdev.so.rsp"
../../ui/events/ozone/evdev/keyboard_evdev.cc:12871: error: undefined reference to 'ui::EventAutoRepeatHandler::EventAutoRepeatHandler(ui::EventAutoRepeatHandler::Delegate*)'
obj/ui/events/ozone/events_ozone_evdev/keyboard_evdev.o:keyboard_evdev.cc:function ui::KeyboardEvdev::~KeyboardEvdev(): error: undefined reference to 'ui::EventAutoRepeatHandler::~EventAutoRepeatHandler()'
obj/ui/events/ozone/events_ozone_evdev/keyboard_evdev.o:keyboard_evdev.cc:function ui::KeyboardEvdev::OnKeyChange(unsigned int, bool, bool, base::TimeTicks, int): error: undefined reference to 'ui::EventAutoRepeatHandler::UpdateKeyRepeat(unsigned int, bool, bool, int)'
obj/ui/events/ozone/events_ozone_evdev/keyboard_evdev.o:keyboard_evdev.cc:function ui::KeyboardEvdev::IsAutoRepeatEnabled(): error: undefined reference to 'ui::EventAutoRepeatHandler::IsAutoRepeatEnabled()'
obj/ui/events/ozone/events_ozone_evdev/keyboard_evdev.o:keyboard_evdev.cc:function ui::KeyboardEvdev::SetAutoRepeatEnabled(bool): error: undefined reference to 'ui::EventAutoRepeatHandler::SetAutoRepeatEnabled(bool)'
obj/ui/events/ozone/events_ozone_evdev/keyboard_evdev.o:keyboard_evdev.cc:function ui::KeyboardEvdev::SetAutoRepeatRate(base::TimeDelta const&, base::TimeDelta const&): error: undefined reference to 'ui::EventAutoRepeatHandler::SetAutoRepeatRate(base::TimeDelta const&, base::TimeDelta const&)'
obj/ui/events/ozone/events_ozone_evdev/keyboard_evdev.o:keyboard_evdev.cc:function ui::KeyboardEvdev::GetAutoRepeatRate(base::TimeDelta*, base::TimeDelta*): error: undefined reference to 'ui::EventAutoRepeatHandler::GetAutoRepeatRate(base::TimeDelta*, base::TimeDelta*)'


Original change's description:
> Move EventAutoRepeatHandler out of /evdev umbrella
> 
> Code is not evdev dependent, so CL moves it out of it.
> 
> BUG=None
> 
> Change-Id: I43c7df188bc3193e8b684c334e3cac71ab98d8af
> Reviewed-on: https://chromium-review.googlesource.com/881961
> Reviewed-by: Michael Spang <spang@chromium.org>
> Commit-Queue: Antonio Gomes <tonikitoo@igalia.com>
> Cr-Commit-Position: refs/heads/master@{#531395}

TBR=spang@chromium.org,tonikitoo@igalia.com

Change-Id: I7a70741a8d90e235c8068193c4adf98567beeaf2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: None
Reviewed-on: https://chromium-review.googlesource.com/882721
Reviewed-by: Joe Downing <joedow@chromium.org>
Commit-Queue: Joe Downing <joedow@chromium.org>
Cr-Commit-Position: refs/heads/master@{#531400}
Former-commit-id: 13d20807b008fa9c64a40b2e70d9b3e54d17a646