Reland: Differentiate credit, debit, and prepaid cards.
Originally landed in: http://crrev.com/c/509808

Reverted in: http://crrev.com/c/540793

Reason for revert:
Compile failure on Chromium OS bot.
chrome/browser/ui/views/payments/payment_method_view_controller.cc:175:10:
    error: cannot bind 'std::unique_ptr<views::Label>' lvalue to
    'std::unique_ptr<views::Label>&&'
  return label;
         ^

Original description:

Before this patch, calling PaymentRequest with a card type (credit,
debit, prepaid) filter outputs a DevTools console warning "Unable to
differentiate card types" and does not perform any filtering in user
interface. This prevented merchants that accept debit cards only, for
example, from using PaymentRequest API.

This patch adds a "type" field to "masked_credit_cards" autofill table.
This field is populated from sync, because the card type is known only
for server cards.

PaymentRequest UI now filters out cards that don't match the merchant's
requested card type explicitly. For example, suppose merchant requests
debit cards, then the UI will filter out credit and prepaid cards. The
user can still use unknown card types, but the user has to explicitly
select a card of unknown type in UI, because Chrome does not pre-select
it.

The PaymentRequest UI on Android and desktop has two changes when
merchant website requests a subset of [credit, debit, prepaid] card
types:
1) The payment methods section shows which card types are accepted. For
   example: "Debit cards are accepted." This helps the user to make the
   right choice when Chrome has not been able to determine card type.
2) The "Accepted cards" label for the card issuer network icons in the
   editor dialogs is customized based on the accepted card types. For
   example, "Accepted debit cards."
Throughout Chrome UI, the term "credit card" has been changed to "card."

Bonus: PaymentRequest UI on desktop now shows "Select shipping address
to see available shipping options" in the shipping address view for
merchants that require to see the shipping address first before
calculating the shipping prices.

This patch does not modify iOS behavior.

BUG=602665
TBR=pkasting, zea, nyquist, finnur, mathp, dpapad, anthonyvd, gogerald, jochen

Change-Id: I0181d51757ab52a4233e150765c6681da6147858
Reviewed-on: https://chromium-review.googlesource.com/541476
Commit-Queue: Rouslan Solomakhin <rouslan@chromium.org>
Reviewed-by: Rouslan Solomakhin <rouslan@chromium.org>
Cr-Commit-Position: refs/heads/master@{#482000}
Former-commit-id: 25d708b7e24d70becb747d3863a959c239159117